votingworks/vxsuite

frontends/election-manager/src/components/confirm_removing_file_modal.tsx, frontends/election-manager/src/components/export_ballot_pdfs_button.tsx, frontends/election-manager/src/components/export_election_ballot_package_modal_button.tsx, frontends/election-manager/src/components/print_all_ballots_button.tsx
These variables were treated as `any` by TypeScript, but annoyingly don't trigger the `noImplicitAny` configuration in `tsconfig.json`. This commit adds a type annotation so the type can be properly enforced.
n/a
n/a
=> fix(types): no implicit `any`

frontends/election-manager/src/screens/unconfigured_screen.tsx, integration-testing/election-manager/cypress/e2e/candidate_contest_tallies.cy.ts, integration-testing/election-manager/cypress/e2e/configuration.cy.ts, integration-testing/election-manager/cypress/e2e/tallies.cy.ts, integration-testing/election-manager/cypress/e2e/yes_no_contest_tallies.cy.ts
The previous fix caused a UX lag when converting that could be confusing. The `isLoading` state is still useful. So brought it back, and moved the state transitions to strictly when they're needed, so it doesn't happen on every load.
There's likely still some further refactoring we could do here, just to simplify the `updateStatus` approach. Leaving that to later work.
=> Better converter fix

libs/plustek-sdk/src/mocks.ts
Rather than using a ternary expression, which Istanbul checks both branches for execution, just pick one from an array so the code will always be considered covered.
Fixes #2589 
n/a
Automated.
=> test(plustek-sdk): fix flaky coverage

libs/ballot-interpreter-nh/src/convert.test.ts, libs/ballot-interpreter-nh/src/convert.ts, libs/ballot-interpreter-nh/src/interpret/index.test.ts, libs/ballot-interpreter-nh/test/fixtures/amherst-2022-07-12/election.json, libs/ballot-interpreter-nh/test/fixtures/hudson-2020-11-03/election.json
New election definitions converted from NH format will no longer have the `BlankBallot` adjudication reason, per NH SoS.
Closes #2578 
n/a
n/a
=> feat(scan-nh): remove `BlankBallot` adjudication reason

frontends/election-manager/src/screens/tally_report_screen.tsx
When the tally report screen loads it calls react query for the write in summary information. It immediately calls it twice, the first set of results is stale and writeInSummaryQuery.isStale is true, long term the better fix here is probably to be using that variable and show a loading state or something while isState is true, but its immediately re-called and then given new data. However since the counts are not in this useEffect that shows the preview on the screen it is not redrawn with the new data when it gets loaded, like the write in tally report does, so the new data never appears. This was the most minimal change to fix that but I defer to @eventualbuddha on if we should be using isStale or doing something else long term as the better solution here. 
Adjudicated write-ins …
=> fix bug with tally report not loading adjudications on first load

frontends/election-manager/src/screens/print_test_deck_screen.tsx
This reverts commit 8fc721f4ba6cb4c9a8347683b33be4e9c05877a1. [Slack context](https://votingworks.slack.com/archives/CEL6D3GAD/p1664055582530589). Refs #1864.
n/a
@arsalansufi found that the change this reverts created duplicate keys in some circumstances. This fixes it by reverting.
=> Revert "fix(admin): use non-array index key (#2583)"

services/scan/bin/retry-scan, services/scan/src/workers/child_process_worker.js, services/scan/src/workers/pool.test.ts, services/scan/src/workers/pool/inline_worker_ops.ts, services/scan/src/workers/pool/worker_pool.ts, services/scan/src/workers/worker_thread_worker.js
Makes a couple minor improvements to error handling with `retry-scan` and anything that uses the worker pool. When an error was thrown while a worker was running a job it would return an object from `pool.call` like `{ type: 'error', error: 'message' }` rather than throwing. We now throw (i.e. return a rejected promise) when the worker throws.
n/a
Tested locally with `retry-scan` manually, lots of automated testing.
=> fix(scan): improve `retry-scan` error handling

libs/res-to-ts/src/mime.test.ts, libs/res-to-ts/src/mime.ts, services/scan/bin/retry-scan, services/scan/src/workers/child_process_worker.js, services/scan/src/workers/pool.test.ts, services/scan/src/workers/pool/inline_worker_ops.ts, services/scan/src/workers/pool/worker_pool.ts, services/scan/src/workers/worker_thread_worker.js
I'll be adding an `.xml` fixture soon and I need to be able to use `.asText()` with it.
n/a
Tested manually in a later commit built on top of this.
=> feat(res-to-ts): count `application/xml` as text

integration-testing/election-manager/cypress/e2e/candidate_contest_tallies.cy.ts, integration-testing/election-manager/cypress/e2e/configuration.cy.ts, integration-testing/election-manager/cypress/e2e/tallies.cy.ts, integration-testing/election-manager/cypress/e2e/yes_no_contest_tallies.cy.ts, integration-testing/election-manager/cypress/support/auth.ts
Unlike with pastries, with tests we do _not_ want flakiness. 🥐 
The most common inconsistent test failure in the EM tests was trying to click "Lock Machine". The error said that the DOM element being clicked was detached from the document, and helpfully pointed to [some documentation][1]. That documentation, in turn, pointed to an [even more helpful blog post on this particular race condition][2]. The problem is similar to race conditions we've encountered with Jest DOM tests where the test runner gets ahead of the application under test. The solution is also the same in both cases: wait for the conditions to be right before performing more actions.
In the case of the "Lock Machine" flake, the problem is that we render that button as part of the `NavigationScreen`, but that screen is …
=> test(cypress): improve flakiness

frontends/election-manager/src/screens/unconfigured_screen.tsx
I don't think this is actually an issue at runtime, but the `smartcard_modal.test.tsx` tests were [printing `failed updateStatus() 'path' is not a property of undefined`](https://app.circleci.com/pipelines/github/votingworks/vxsuite/5950/workflows/5d15738a-c5db-4aae-8600-a070d3fe8fe2/jobs/139163?invite=true#step-108-141).
n/a
n/a
=> fix(admin): ignore missing converter output

frontends/bas/src/app_root.tsx, frontends/election-manager/src/screens/unconfigured_screen.tsx
Per https://beta.reactjs.org/learn/you-might-not-need-an-effect, we shouldn't use `useEffect` to set state as it just causes additional renders. Instead, just compute the values at the component top level. In the case of the converter client, use `useMemo` since the client is potentially stateful.
I found these by searching for `( *)useEffect\(\(\) => \{\n\1 *set[A-Z]`. There were a couple other matches, but they were both `setTimeout` and not a `useState` setter.
n/a
Tested the MS converter flow for VxAdmin manually.
=> refactor(hooks): more idiomatic `useEffect`

codemods/package.json, frontends/bas/package.json, frontends/bmd/package.json, frontends/bsd/package.json, frontends/election-manager/package.json, frontends/precinct-scanner/package.json, libs/api/package.json, libs/ballot-encoder/package.json, libs/ballot-interpreter-nh/package.json, libs/ballot-interpreter-vx/package.json, libs/cdf-schema-builder/package.json, libs/cdf-types-cast-vote-records/package.json, libs/cdf-types-election-event-logging/package.json, libs/cvr-fixture-generator/package.json, libs/eslint-plugin-vx/package.json, libs/fixtures/package.json, libs/image-utils/package.json, libs/logging/package.json, libs/lsd/package.json, libs/plustek-sdk/package.json, libs/res-to-ts/package.json, libs/test-utils/package.json, libs/types/package.json, libs/ui/package.json, libs/utils/package.json, services/admin/package.json, services/scan/package.json
Death to flakes! ⚔️ 🥐 
Per https://support.circleci.com/hc/en-us/articles/360005442714-Your-test-tools-are-smart-and-that-s-a-problem-Learn-about-when-optimization-goes-wrong-, Jest may be trying to run too much at once. This may be causing tests to take much too long and time out. I picked `--maxWorkers=7` because `xlarge` instances have 8 CPUs.
Using `services/scan` as an example:
```
PASS  src/backup.test.ts (29.173 s)
PASS  src/build_cast_vote_record.test.ts (28.031 s)
PASS  src/central_scanner_app.test.ts (30.405 s)
PASS  src/cli/mock-scanner/index.test.ts (24.223 s)
PASS  src/cli/read-qrcode/index.test.ts (26.079 s)
PASS  src/cli/render_pages.test.ts (30.101 s)
PASS  src/cli/retry-scan/index.test.ts (28.301 s)
PASS  src/cli/retry-scan/main.test.ts (29.009 s)
PASS …
```
=> ci(jest): limit `maxWorkers`

services/scan/src/cli/render_pages.test.ts, services/scan/src/cli/render_pages.ts, services/scan/src/util/images.ts
This is useful for generating the images needed for the `ballot-interpreter-nh/bin/convert` binary since it expects 72ppi rather than the default 144ppi that `render-pages` uses.
I changed `writeImageData` to use `pipeline` from `stream/promises` both because [it's more idiomatic](https://stackoverflow.com/a/68750761) and because it fixes an issue where the `imageStream` would be done but the `fileWriter` was not yet for PNG images. This wasn't a problem when using the binary for real, but was a problem with tests.
```
❯ ./bin/render-pages ../../libs/fixtures/data/electionFamousNames2021/ballot.pdf
📝 ../../libs/fixtures/data/electionFamousNames2021/ballot-p1.jpg
📝 ../../libs/fixtures/data/electionFamousNames2021/ballot-p2.jpg
❯ file …
```
=> feat(scan): add `scale` option to `render-pages`

frontends/precinct-scanner/src/screens/scan_processing_screen.tsx
Close #2619: Replacing "checking for errors" language on the scan progress screen with friendlier messaging.
**Before:**
**After:**
Ran locally to verify.
=> Remove 'error' language on scan progress screen

libs/ui/src/remove_card_screen.tsx
Close #2420: After successful authentication, replace screen header text with "VxAdmin Unlocked" to match the "VxAdmin is locked" messaging in the previous screen.
=> VxAdmin: use consistent locked/unlocked language

frontends/election-manager/src/screens/write_ins_screen.test.tsx, frontends/election-manager/src/screens/write_ins_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/2593
- Disable action buttons on the WIA screen after results have been marked as official.
- Additionally, adding messaging in the header for the screen to explain why editing has been disabled.
https://user-images.githubusercontent.com/264902/194391008-326b6aae-18bf-45af-88d9-533cf44dcf43.mov
- Added unit test for the new case to verify disabled buttons and presence of explanation message
- Sanity check with local runthrough
=> WIA: disable adjudication after finalizing results

frontends/bsd/src/app.test.tsx, frontends/bsd/src/app_root.tsx, frontends/election-manager/src/components/election_manager.tsx, libs/ui/src/remove_card_screen.test.tsx, libs/ui/src/remove_card_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/2642:
Updating the `RemoveCardScreen` component with product-specific copy, instead of hardcoding "VxAdmin" (introduced in PR https://github.com/votingworks/vxsuite/pull/2630), since it's also used in VxCentralScan.
- Updated unit tests to check for product name
- Verified locally
=> [VxAdmin|VxCentralScan] use product-specific copy on unlock screen

frontends/election-manager/src/app.test.tsx, frontends/election-manager/src/app_root.tsx, frontends/election-manager/src/app_write_in_flows.test.tsx, frontends/election-manager/src/components/election_manager_tally_report.tsx, frontends/election-manager/src/components/election_manager_writein_tally_report.tsx, frontends/election-manager/src/contexts/app_context.ts, frontends/election-manager/src/screens/manual_data_import_index_screen.test.tsx, frontends/election-manager/src/screens/manual_data_import_index_screen.tsx, frontends/election-manager/src/screens/manual_data_import_precinct_screen.test.tsx, frontends/election-manager/src/screens/manual_data_import_precinct_screen.tsx, frontends/election-manager/src/screens/tally_report_screen.tsx, frontends/election-manager/src/screens/tally_writein_report_screen.tsx, frontends/election-manager/src/utils/external_tallies.test.ts, frontends/election-manager/src/utils/external_tallies.ts, frontends/election-manager/src/utils/write_ins.test.ts, frontends/election-manager/src/utils/write_ins.ts, frontends/election-manager/test/helpers/build_external_tally.ts, frontends/election-manager/test/render_in_app_context.tsx
Closes #2585. Adds the ability to manually add write-in candidates and their vote counts via our manually entered data flow.
[manual-write-ins.webm](https://user-images.githubusercontent.com/37960853/195188836-dde635da-f480-4ab1-b51c-79f9fadafc40.webm)
- Manual and Automated Testing
=> Add Manual Write-In Results

frontends/election-manager/src/app_write_in_flows.test.tsx, frontends/election-manager/src/components/election_manager_writein_tally_report.tsx, frontends/election-manager/src/screens/tally_writein_report_screen.tsx, frontends/election-manager/src/utils/write_ins.ts, libs/ui/src/contest_writein_tally.test.tsx, libs/ui/src/contest_writein_tally.tsx
Clsoes #2595. Rather than say that adjudication hasn't been completed for contests with no non-official write-in candidates in the scatter report, just don't show those contests. If there are no contests on a primary report, don't show that party's part of the report. If there are no reports at all, don't show any report at all.
- Wrote new write-in report flow test
=> Don't Show Contests in Write-In Report if they have no data

frontends/election-manager/src/components/election_manager_tally_report.tsx, frontends/election-manager/src/screens/reports_screen.tsx, frontends/election-manager/src/utils/generate_results_csv.ts, libs/ui/src/precinct_scanner_tally_report.tsx, libs/ui/src/tally_report_summary.test.tsx, libs/ui/src/tally_report_summary.tsx, libs/utils/src/elections.test.ts, libs/utils/src/elections.ts, libs/utils/src/index.ts
https://github.com/votingworks/vxsuite/issues/2631:
- Hiding tallies broken down by voting method whenever we're unable to distinguish voting methods for an election.
- Adding `canDistinguishPrecinctAndAbsenteeBallots` util (currently just a proxy for absence of `gridLayouts` in the election definition).
- Unit test coverage and local verification
=> [VxAdmin|VxScan] Hide tally by voting method if unable to distinguish

libs/ballot-interpreter-nh/src/cli/interpret/index.test.ts, libs/ballot-interpreter-nh/src/cli/interpret/index.ts
I needed to get access to the normalized images generated by the interpretation process. This new flag causes the normalized images to be written to disk alongside the originals.
n/a
Tested manually with the new flag.
=> feat(scan-nh): add `--write-normalized-images` CLI flag

frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
It's unlikely we'll encounter a situation anytime soon where this will make a difference, but it's better to have it be correct to serve as an example.
n/a
n/a
=> fix(admin): format both `X of Y` as counts

services/scan/src/precinct_scanner_app.ts
Closes #2663. The bug only affects single precinct elections and was introduced in #2641. The interpreter was not being updated after we auto-set the precinct. Further, now that the precinct can be set before templates are done being uploaded, we have to update the interpreter after we add each template. 
It seems like we could manage interpreter state a little more cleanly, because right now anytime we add something that changes interpreter inputs we have to remember to update the interpreter. If we forget, as I did in the linked PR, bugs! Why can't the interpreter just use the state from the store? I haven't dug into this yet, just musing.
Manual only.
=> fix broken reconfigure for single-precinct

frontends/precinct-scanner/src/screens/scan_warning_screen.tsx
In the rare case where there are two contests with the same title, ensure the contest names and count are correct.
n/a
Discovered this while testing with an election that had multiple contests with the same title (due to #2643).
=> fix(scan): de-dupe contests by ID, not title

frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
- Uses `format.count` to properly display an integer count (i.e. grouping separators for 1,000+).
- Shows "1 write-in to transcribe" when there's only one left (instead of "1 write-ins to transcribe").
|-|-|
| <img width="429" alt="Screen Shot 2022-10-13 at 1 55 25 PM" src="https://user-images.githubusercontent.com/1938/195709904-4b3ee226-3d2d-4e1e-9d2c-082e00cd61dc.png"> | <img width="431" alt="Screen Shot 2022-10-13 at 1 55 05 PM" src="https://user-images.githubusercontent.com/1938/195709926-9d26b30f-f4b4-46ef-bb0c-7fb2f26d018d.png"> |
| <img width="438" alt="Screen Shot 2022-10-13 at 2 03 51 PM" src="https://user-images.githubusercontent.com/1938/195710183-0d11b2bd-c154-46b8-a957-dfa92b2228d8.png"> | <img width="445" alt="Screen Shot 2022-10-13 at 1 58 41 PM" …
=> fix(admin): improve display of transcriptions remaining

frontends/bmd/src/app_root.tsx, frontends/bmd/src/app_single_precinct_election.test.tsx, frontends/bmd/src/pages/admin_screen.tsx, frontends/precinct-scanner/src/app.test.tsx, frontends/precinct-scanner/src/screens/election_manager_screen.test.tsx, frontends/precinct-scanner/src/screens/election_manager_screen.tsx
Not an explicit requirement, but I wanted the behavior in VxMark to match the behavior in VxScan after #2641. With this change (first commit), if you load an election into VxMark that has only one precinct, it will automatically set the precinct. 
There's a second very small commit in which I revert a UI tweak in VxScan. I had hidden the "Select a precinct for this device..." menu option after a precinct was selected, but I noticed in VxMark that it actually changed the width of the dropdown in an unflattering way and it's weird to have a dropdown with only one option. Ideally, if there's only one precinct, there's no dropdown at all. But in this PR I just wanted things to align across apps.
=> BMD - Automatically set precinct if only one

services/admin/src/server.ts
I think there are problems beyond this with loading a very large cvr (testing with a 1.4GB cvr for 967 write ins) into VxAdmin but this definitely needs to be bumped for it to work.
=> bump max size limit in admin server

libs/@types/kiosk-browser/kiosk-browser.d.ts
This must have been the result of a bad merge or something. It never affected type checking because TS doesn't have a problem with overloads with identical signatures.
n/a
n/a
=> fix(types): remove duplicate `writeFile` overloads

frontends/bsd/src/components/export_logs_modal.tsx, frontends/bsd/src/components/export_results_modal.tsx, frontends/election-manager/src/components/export_logs_modal.tsx, frontends/election-manager/src/components/save_file_to_usb.tsx, frontends/precinct-scanner/src/components/export_backup_modal.tsx, frontends/precinct-scanner/src/components/export_results_modal.tsx
Same thing as elsewhere: double-click the USB icon.
n/a
n/a
=> feat(all): allow file picker for various exports

frontends/precinct-scanner/src/api/scan.test.ts, frontends/precinct-scanner/src/api/scan.ts, frontends/precinct-scanner/src/app.test.tsx, frontends/precinct-scanner/src/app_tally_report_paths.test.tsx, frontends/precinct-scanner/src/components/export_backup_modal.test.tsx, frontends/precinct-scanner/src/components/export_backup_modal.tsx, frontends/precinct-scanner/src/components/export_results_modal.test.tsx, frontends/precinct-scanner/src/components/export_results_modal.tsx, frontends/precinct-scanner/src/screens/poll_worker_screen.tsx, frontends/precinct-scanner/src/utils/download.test.ts, frontends/precinct-scanner/src/utils/download.ts, frontends/precinct-scanner/src/utils/save_cvr_export_to_usb.test.ts, frontends/precinct-scanner/src/utils/save_cvr_export_to_usb.ts, libs/api/src/services/scan/index.ts, services/scan/src/precinct_scanner_app.test.ts, services/scan/src/precinct_scanner_app.ts, services/scan/src/store.test.ts, services/scan/src/store.ts
Does two things:
1. Makes CVR exports streaming (from the backend to the frontend to the download) to accommodate larger CVRs
2. Sets up option to get CVRs without inline images for tally purposes, to speed up polls closing
Now that we are downloading the file from the backend, we should set it's file name via the content disposition. However, currently we don't have access to the machine ID (which needs to be in the filename) in the backend. That's easy to do, but to do it right, we should abstract out the machine config provider to `utils` which I didn't want to bother with on the fly.
- Edited a bunch of tests, added a few
- Manual testing _in kiosk-brower_
- Note: I have not tested this in the browser. We have some logic for downloads in the browser for dev purposes, and I have not …
=> VxScan: Stream CVR Exports

frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
=> scale images up that are at 50%

libs/api/src/services/admin/endpoints.ts, libs/api/src/services/admin/types.ts, services/admin/schema.sql, services/admin/src/server.test.ts, services/admin/src/server.ts, services/admin/src/store.test.ts, services/admin/src/store.ts, services/admin/src/util/sha256_file.test.ts, services/admin/src/util/sha256_file.ts
CVR files that have a lot of write-in images can be pretty large, i.e. 1GB+. Attempting to read this in as a string is a really bad idea and NodeJS will simply not allow it as it exceeds the maximum length of a string in V8.
This commit fixes the issue by:
a) passing in the file path when importing rather than the contents
b) computing the sha256 hash via a file read stream
c) reading the CVR file one line at a time
We end up reading the file twice (once for the hash, once for the CVR entry import), but overall this is both more efficient and faster even for strings that do fit in memory.
**NOTE:** This does _not_ change the client-side CVR handling which still doesn't seem happy with CVR files this large.
https://user-images.githubusercontent.com/1938/196287850-24a74875-9a08-48ca-87a5-f5d …
=> fix(admin): handle larger CVR file import

frontends/election-manager/src/components/smartcard_modal/card_details_view.tsx, frontends/election-manager/src/components/smartcard_modal/program_election_card_view.tsx, frontends/election-manager/src/components/smartcard_modal/program_system_administrator_card_view.tsx, frontends/election-manager/src/components/smartcard_modal/smartcard_modal.test.tsx, frontends/election-manager/src/components/smartcard_modal/status_message.tsx, libs/utils/src/index.ts, libs/utils/src/pins.test.ts, libs/utils/src/pins.ts
https://github.com/votingworks/vxsuite/issues/1926:
Moving `generatePin` utility to `lib/utils` to prepare for moving PIN generation logic to the admin service
- Using existing tests as regression tests
- Verified locally
=> Move generatePin to utils lib for later use in admin service

script/src/run-dev/index.ts
We have a bootstrapping problem. After setting up development and running `pnpm install`, nothing is actually built yet. When running a frontend we run the associated services and their build in watch mode. But because the service has never been built the service fails to run and the build does not complete because `concurrently` kills it when the service run process exits.
This commit fixes the bootstrapping problem by waiting to run the service until the build completes.
Note the "Waiting for build…" in the output below.
```
❯ pnpm start            
> @votingworks/election-manager@0.1.0 start /home/brian/code/vxsuite/frontends/election-manager
> pnpm -w run-dev -- election-manager
> vxsuite@ run-dev /home/brian/code/vxsuite
> script/run-dev "election-manager"
[converter-ms-sems:run] …
```
=> build(all): wait for service build before running

services/scan/src/central_scanner_app.test.ts, services/scan/src/central_scanner_app.ts, services/scan/src/importer.ts, services/scan/src/precinct_scanner_app.ts, services/scan/src/store.ts
Small tweaks to follow #2681. Three commits:
1. Safely waits for writeStream to be ready to consume data before writing to it
2. Passes electionDefinition as an argument to stop hitting the DB (this the time of the `exportCvrs` method from about 8 to 2 seconds when not exporting write-ins)
3. Gets rid of intermediary Passthrough stream.
This fixes the problem where the file-picker doesn't come up write away AND it means the `exportCvrs` method is no longer blocking.
=> Improve Performance + Safety of Large CVR Export

services/admin/src/server.test.ts, services/admin/src/server.ts, services/admin/src/server.writeins.test.ts, services/admin/src/util/workspace.ts
Previously we were storing uploads in a temporary file in `/tmp`, but they were never getting cleaned up. Eventually the `/tmp` partition would run out of disk space and we'd be unable to upload anything new, and other operations that used `/tmp` would start to fail as well.
Now, we upload to the `uploads` folder within the current workspace. After the request finishes we delete the uploaded file.
Watching the `uploads` directory during the upload of a 1.3GB CVR file:
```
while true; do du -a ~/code/vxsuite/services/admin/dev-workspace/uploads/ | sort -rn | head -n 5; sleep 1; done
4	/home/brian/code/vxsuite/services/admin/dev-workspace/uploads/
4	/home/brian/code/vxsuite/services/admin/dev-workspace/uploads/
4	/home/brian/code/vxsuite/services/admin/dev-workspace/uploads/
4 …
```
=> fix(admin): clear uploads after request

libs/ballot-interpreter-nh/src/interpret/index.ts, services/scan/src/workers/interpret_nh.ts
Fixes #2703 
From a CVR export after the fix:
```json
{"_ballotId":"e93735c6-e16e-493a-8771-dca935de1a7b",
"_ballotStyleId":"card-number-3",
"_ballotType":"standard",
"_batchId":"dd6f4ffb-fa28-4232-a156-365970a7b3e3",
"_batchLabel":"Batch 3",
"_precinctId":"town-id-00701-precinct-id-",
"_scannerId":"000",
"_testBallot":true,
"_locales":{"primary":"unknown"},
"_pageNumbers":[1,2],
```
Scanned some NH ballots and found the CVR exports respected the current test mode setting.
=> fix(scan-nh): pass test/live mode through to interpreter

services/admin/src/server.ts, services/admin/src/util/workspace.ts, services/scan/src/central_scanner_app.test.ts, services/scan/src/central_scanner_app.ts, services/scan/src/end_to_end.test.ts, services/scan/src/end_to_end_hmpb.test.ts, services/scan/src/precinct_scanner_app.ts, services/scan/src/server.ts, services/scan/src/util/workspace.ts
Similar as #2701, but for `services/scan`. Also clears uploads on startup, and adds the same for `services/admin`.
n/a
Tested manually similarly to how I did it in #2701.
=> fix(scan): clear uploads after request

libs/ballot-interpreter-nh/src/cli/interpret/index.test.ts, libs/ballot-interpreter-nh/src/cli/interpret/index.ts, libs/ballot-interpreter-nh/src/interpret/index.test.ts, libs/ballot-interpreter-nh/src/interpret/index.ts, services/scan/src/precinct_scanner_interpreter.test.ts, services/scan/src/precinct_scanner_interpreter.ts
Fixes #2703 (for real this time)
In #2706 I only passed the test mode config through in the VxCentralScan code path. I had added `isTestMode` as a config parameter to the NH `interpret` function, but I'd made it optional so the type checking didn't complain when we didn't pass it in the VxScan code path. This time I made `isTestMode` required and added it in the VxScan code path.
Exported CVR from a ballot scanned using VxScan in test mode:
```json
{"_ballotId":"22032f7b-a225-4825-a286-1af205849265",
"_ballotStyleId":"card-number-59",
"_ballotType":"standard",
"_batchId":"c685ede0-41a6-4a7e-af92-03742f76a3d0",
"_batchLabel":"Batch 4",
"_precinctId":"town-id-25901-precinct-id-",
"_scannerId":"000",
"_testBallot":true
```
Tested manually with VxScan, added some unit tests.
=> fix(scan-nh): enforce configuring test mode

frontends/election-manager/src/screens/tally_writein_report_screen.tsx
I think this report used to live under the Tally tab and when we moved it we didn't change the "Back to Tally Index" button.
[Slack context](https://votingworks.slack.com/archives/CEL6D3GAD/p1666201476079439)
Tested manually in VxAdmin w/kiosk-browser.
=> fix(admin): make write-in report "Back" go to reports

services/admin/src/store.test.ts, services/admin/src/store.ts
When importing multiple files that have any duplicate CVRs we store each CVR only once but link them to all the CVR files they are present in via the `cvr_file_entries` table. When getting the write-in records for an election we need to join `write_ins` with `cvr_file_entries` and `cvr_files`, which means that a write-in record will show up however many times its CVR appears in `cvr_file_entries`. To fix this, we `select distinct` to ensure that only one of each write-in is returned.
Closes #2710 
When importing [two CVR files that duplicate 200 write-ins per contest (600 for State Representative)](https://votingworks.slack.com/archives/C02Q3M874SV/p1666202204325849?thread_ts=1666192691.204109&cid=C02Q3M874SV):
|-|-|
|<img width="662" alt="image" …
=> fix(admin): do not duplicate write-ins from multiple CVR files

services/scan/src/backup.ts, services/scan/src/precinct_scanner_app.ts
In #2696, we made it so we only write to the CVR stream when it is ready to write (it drains). This improves performance when we're writing to a `response`.
However, in many cases, we are writing to stream which is not being piped anywhere. In other words, it is not being drained, so there is no `drain` event. Thus, it hangs. When we use streams like this (e.g. `new WritableStream()`) we need to set the `highWaterMark` to something that is larger than the expected data size so that it never blocks.
In this PR, I both set the `highWaterMark` and `pipe` the export stream directly into the zip file stream (via a `Passthrough`) which improves efficiency.
Also left some useful debugging in there.
=> fix(ps): backup cvr stream blockage

frontends/precinct-scanner/src/screens/poll_worker_screen.tsx
#2718 fixes the issue but could fail as a fix if the execution order / state updates are different. this is an improvement.
=> print correct report in more states

libs/utils/src/pins.test.ts, libs/utils/src/pins.ts
Fixes #2723
Uses [`randombytes`](https://www.npmjs.com/package/randombytes):
> randombytes from node that works in the browser. In node you just get `crypto.randomBytes`, but in the browser it uses `.crypto/msCrypto.getRandomValues`
Tested with `REACT_APP_VX_ENABLE_ALL_ZERO_SMARTCARD_PIN_GENERATION=false`.
=> fix(utils): use secure RNG for PINs

libs/ballot-interpreter-nh/src/layout.ts
Sometimes, `generateBallotPageLayouts` outputs contest layouts in an order different from the election definition. That messes up write-in adjudication downstream.
I considered alternate fixes:
- fixing the election definition converter so that it would always yield grid layouts in an order that would yield the right contest layout downstream, but that seemed a bit flimsy.
- changing the data structure to a map keyed on `contestId`, but that seems like a large, risky, and unnecessary change when we already often rely on contest ordering identical to the election definition.
=> fix(ballot-interpreter-nh): ensure the contest layout bounds are generated in right order

libs/ballot-interpreter-nh/src/layout.ts, services/admin/src/server.ts
In locating the proper portions of the ballot for write-in adjudication, we go through each page's layout and find the current contest's index on its current page. To do that, we subtract from the index the contests that appear on prior pages.
There was a bug where we were subtracting the number of contests on the *current* page, rather than the previous page. This wasn't noticed before because we happened to be testing on an election that had the same number of contests on the front and back pages.
=> fix(wia): adjust contest index based on the previous page's number of contests

.gitignore, jest.config.shared.js
It's possible to end up with very confusing jest errors if jest is relying on its cached directory structure. By default, it's `/tmp/jest_rs`. Setting it within the repository means it will be cleared with `clean-all`.
https://jestjs.io/docs/configuration#cachedirectory-string
=> clear jest cache on clean-all

frontends/election-manager/src/index.tsx
The React Query devtools flower toggle button was showing up in printed ballots and reports when it is present (which is not the default).
|-|-|
| <img width="312" alt="Screen Shot 2022-10-24 at 9 55 53 AM" src="https://user-images.githubusercontent.com/1938/197582823-dcd88a2b-908a-4239-9505-8e75a3318554.png"> | <img width="311" alt="Screen Shot 2022-10-24 at 9 56 33 AM" src="https://user-images.githubusercontent.com/1938/197582833-325098c4-3873-49f1-824f-2f7f5ac527ed.png"> |
Tested manually with Chrome's print preview.
=> fix(admin): don't print the React Query devtools

vxsuite.code-workspace
Excludes it from both the file explorer and project search.
|-|-|
| <img width="456" alt="image" src="https://user-images.githubusercontent.com/1938/197649329-57250fe4-07c7-4d81-a025-c5f6aea62a29.png"> | <img width="460" alt="image" src="https://user-images.githubusercontent.com/1938/197649308-796e8a79-0ced-44dd-a367-d5f356c6f50e.png"> |
Tested locally in VS Code.
=> chore(vscode): ignore `.jestcache`

services/admin/src/store.test.ts, services/admin/src/store.ts
Related: https://github.com/votingworks/vxsuite/issues/2716
Remove `getCastVoteRecordFile()`, which looks like a duplicate of `getCastVoteRecordFileMetadata()`
Verified no other references exist, besides in the deleted test
=> [services/admin] Remove dupulicate CVR store function

frontends/election-manager/src/contexts/services_context.ts, frontends/election-manager/src/hooks/use_adjudicate_transcription_mutation.test.tsx, frontends/election-manager/src/hooks/write_in_adjudication_end_to_end.test.tsx, frontends/election-manager/src/index.tsx, frontends/election-manager/src/screens/ballot_screen.tsx, frontends/election-manager/test/render_in_app_context.tsx
Previously ballot type and mode would reset every time you go back to the ballot screen. Now they will be remembered and restored on a per user role basis. That is, the sysadmin role and election manager role will have separate settings.
See [Slack discussion](https://votingworks.slack.com/archives/CJU9MSC6S/p1666649531051729)
https://user-images.githubusercontent.com/1938/198076197-5c4cd394-cfde-4137-80d6-b8321a6e342c.mov
Tested manually in Chrome as shown in the video.
=> feat(admin): remember ballot settings

frontends/election-manager/src/hooks/use_election_manager_store.ts
Removing unused `addCastVoteRecordFile` mutation function from the `ElectionManagerStore` - there's already an implementation in use in a separate [use_add_cast_vote_record_file_mutation.ts](https://github.com/votingworks/vxsuite/blob/main/frontends/election-manager/src/hooks/use_add_cast_vote_record_file_mutation.ts) file.
- Relying on existing tests as regression guard
- Verified that CVR import functionality doesn't break locally
- [n/a] I have …
=> [VxAdmin] Remove unused ElectionManagerStore function

services/scan/src/interpreter.test.ts, services/scan/src/interpreter.ts, services/scan/src/precinct_scanner_interpreter.ts, services/scan/src/util/images.ts, services/scan/src/util/save_images.ts, services/scan/src/workers/interpret_vx.ts, services/scan/src/workers/qrcode.test.ts
Such files are a temporary workaround for the Custom scanner not working with JPEG. This is only a problem because we're using the same approach as `plustekctl` which writes the files to disk, but long term we should consider loading the scanned images directly in memory.
n/a
Tested manually with the files generated by the [`plustekctl` for Custom](https://github.com/votingworks/plustekctl/compare/customctl).
=> feat(scan): support loading raw image files

frontends/bmd/src/setupTests.tsx, frontends/precinct-scanner/src/setupTests.ts, libs/test-utils/src/expect_print.test.ts, libs/test-utils/src/expect_print.ts
Closes #2758.
- When test assertions fail within `expectPrint`, the DOM printed now only includes the printed container
- Cleans up `expectPrint` module state between tests and failures
=> `expectPrint` Polish

services/scan/src/store.test.ts
=> test(scan): remove duplicate `adjudicateSheet` call

libs/db/src/client.test.ts, libs/db/src/client.ts, services/admin/src/server.ts, services/admin/src/store.test.ts, services/admin/src/store.ts
- Now using the `parseCvr()` util (used in the client) in the server
- Failing CVR file imports whenever any validation errors are found
- Showing generic messaging to the user on most errors, but adding special handling for the following, given the issue mentioned in https://github.com/votingworks/vxsuite/issues/2680:
- Mismatched election - CVR contains contests not found in the election definition
- Invalid vote - a yes/no or candidate choice has an invalid value
- Also updated `addCastVoteRecordFile()` to use a modified `DbClient.transaction` to avoid the chance of forgetting to roll back transactions when returning errors
https://user-images.githubusercontent.com/264902/201155601-359d0b8d-f3bc-4035-bd1f-fa98bacef448.mov
- …
=> [VxAdmin] Block CVR file imports on failed validation

frontends/election-manager/src/hooks/use_cvr_file_analysis_query.ts, frontends/election-manager/src/lib/backends/admin_backend.test.ts, frontends/election-manager/src/lib/backends/admin_backend.ts, frontends/election-manager/src/lib/backends/memory_backend.ts, frontends/election-manager/src/lib/backends/types.ts
Adding a `use_cvr_file_analysis_query` hook  which leverages the existing `analyzeOnly` option flag in the `POST /admin/elections/:id/cvr-files` server endpoint.
This is in preparation for replacing the client-side file analysis in the `ImportCvrFilesModal` with server calls to get information about files discovered on the USB drive, although there's still a bit of work to do in follow-up PRs to return additional data we can use for that.
- Backfilled a couple test cases for the `admin_backend.addCastVoteRecordFile()` function and added a case for the `analyzeOnly` path.
- Not hooked up to any user flows yet, so will test locally later as this gets fleshed out
- [n/a] I have added …
=> [VxAdmin] Add react query for analyzing CVR file contents before import

frontends/election-manager/src/components/import_cvrfiles_modal.test.tsx, frontends/election-manager/src/components/import_cvrfiles_modal.tsx, frontends/election-manager/src/config/types.ts, frontends/election-manager/src/utils/cast_vote_record_files.test.ts, frontends/election-manager/src/utils/cast_vote_record_files.ts
- Removing client-side logic around pre-loading/parsing CVR files found on the USB drive to detect duplicate CVRs prior to importing.
- This simplifies the code a bit as we move CVR data management to the backend and should improve performance in cases where there are multiple large CVR files on the USB drive.
- Side-effects:
- We no longer show duplicate CVR counts in the import modal (these are still surfaced in the confirmation modal after import)
- All information displayed in the CVR table are now based solely on information from the filename (as was the case before the pre-loading logic was added)
More context around the decision in [this slack thread](https://votingworks.slack.com/archives/CEL6D3GAD/p1668541124423049)
- …
=> [VxAdmin] Remove client-side CVR pre-loading logic

frontends/election-manager/src/components/import_cvrfiles_modal.test.tsx, frontends/election-manager/src/components/import_cvrfiles_modal.tsx, frontends/election-manager/src/hooks/use_cvr_file_analysis_query.ts, frontends/election-manager/src/lib/backends/admin_backend.test.ts, frontends/election-manager/src/lib/backends/admin_backend.ts, frontends/election-manager/src/lib/backends/backends.test.ts, frontends/election-manager/src/lib/backends/memory_backend.ts, frontends/election-manager/src/lib/backends/types.ts, libs/api/src/services/admin/endpoints.ts, libs/api/src/services/admin/types.ts, services/admin/src/server.test.ts, services/admin/src/server.ts, services/admin/src/server.writeins.test.ts, services/admin/src/store.test.ts, services/admin/src/store.ts
Adding additional data to the `PostCvrFileResponse` from the admin backend to match what's used client-side for listing CVR files on the USB drive.
- Added new test cases and updated any relevant existing tests
- Not hooked up to any user flows yet, but will be also be testing locally once that's done
- [n/a] I have added the "user_facing_change" label to this PR to automate …
=> [VxAdmin] Expand CVR import API response for parity w/client-side code

libs/api/src/services/admin/endpoints.ts, services/admin/src/server.test.ts, services/admin/src/server.ts, services/admin/src/store.test.ts, services/admin/src/store.ts
- Adding a `GET .../cvr-files` endpoint for retrieving metadata about CVR files imported for the given election.
- Updated the store method to return CVR files matching an election ID, instead of a single CVR file matching a CVR file ID, since we didn't have any consumers yet for the latter. Still leaves the door open for adding a filtering option if we need it down the line.
- Future PRs will hook this up to the client to replace the calls to local storage.
- Added test cases for the store method and API handler
- …
=> [VxAdmin] Add a cvr-files GET API to admin service

frontends/bmd/src/app_polls_flows.test.tsx, frontends/bmd/src/pages/poll_worker_screen.tsx
[Slack thread](https://votingworks.slack.com/archives/CEL6D3GAD/p1668628984553129). Currently, VxMark will print any report that is on an inserted poll worker card. We want this to be the case within modes, but not across modes (test vs. live election). If a report is somehow left on a card from L&A, it could print on election day (if poll worker does process in the wrong order) and confuse poll workers. This PR makes it so that the "Tally Report On Card" modal only appears if the report on the card matches the mode of the VxMark.
=> Do not print reports from card on VxMark if the mode does not match

frontends/bmd/src/app_polls_flows.test.tsx, libs/utils/src/polls.test.ts, libs/utils/src/polls.ts
[Slack thread](https://votingworks.slack.com/archives/CEL6D3GAD/p1668628984553129). Currently there is a poll worker footgun where, if you have a polls closed report on a card from VxScan, and you print that at VxMark, you will move VxMark from "initial closed" to "final closed." I'm not quite sure how you would end up in that position, but it seems like the safer logic is to print the report but _not_ change polls state. If the user really needed to change the state to polls closed on VxMark, they could use the direct option on the poll worker menu.
**Old Logic**: VxMark would transition to any state that it could feasibly be in in the future
**New Logic**: VxMark will only do transitions that would be possible on VxScan
=> Do not allow polls closed to closed on VxMark

frontends/election-manager/src/__snapshots__/app.test.tsx.snap, frontends/election-manager/src/app.test.tsx, frontends/election-manager/src/components/__mocks__/hand_marked_paper_ballot.tsx, frontends/election-manager/src/components/full_test_deck_tally_report_button.tsx, frontends/election-manager/src/components/print_all_ballots_button.test.tsx, frontends/election-manager/src/screens/print_test_deck_screen.test.tsx, frontends/election-manager/src/screens/print_test_deck_screen.tsx, frontends/election-manager/test/util/load_ballot_seal_images.ts
Part of #2759. Closes #2289. Uses the new print approach - in which we semantically print an element rather than render an element and print the whole screen (although under the hood, that is what is happening) - for the test deck printing.
N/A
Updated (expanded!) automated testing and manually tested the letter and non-letter ballot flow.
=> Test Deck Print Refactor

frontends/election-manager/src/hooks/use_add_cast_vote_record_file_mutation.ts, frontends/election-manager/src/hooks/use_clear_cast_vote_record_files_mutation.ts, frontends/election-manager/src/hooks/use_cvr_files_query.ts, frontends/election-manager/src/hooks/use_election_manager_store.ts, frontends/election-manager/src/lib/backends/admin_backend.test.ts, frontends/election-manager/src/lib/backends/admin_backend.ts, frontends/election-manager/src/lib/backends/memory_backend.ts, frontends/election-manager/src/lib/backends/types.ts
Adding a react-query hook (and relevant backend client code) for fetching CVR files for the current election from the admin service.
- Added test cases for the new backend client code
=> [VxAdmin] Add a react-query hook for fetching CVR files from the backend

frontends/election-manager/src/hooks/use_add_cast_vote_record_file_mutation.ts, frontends/election-manager/src/hooks/use_clear_cast_vote_record_files_mutation.ts, frontends/election-manager/src/hooks/use_cvrs_query.ts, frontends/election-manager/src/hooks/use_election_manager_store.ts, frontends/election-manager/src/lib/backends/admin_backend.test.ts, frontends/election-manager/src/lib/backends/admin_backend.ts, frontends/election-manager/src/lib/backends/memory_backend.ts, frontends/election-manager/src/lib/backends/types.ts, libs/api/src/services/admin/endpoints.ts, pnpm-lock.yaml, services/admin/package.json, services/admin/src/server.test.ts, services/admin/src/server.ts, services/admin/src/store.ts
- Adding a `GET .../cvrs` endpoint to the admin service for fetching all CVRs for a given election.
- Also adding the relevant client code and react-query hook for interacting with the server endpoint.
- Will be used for generating tallies in the client, in lieu of the CVRs from local storage
- New test cases for the new API handler and client code
- Manual verification that API call returns expected data
- [n/a] I have added the "user_facing_change" label to this PR to automate an announcement in …
=> [VxAdmin] Add API and client for fetching CVRs for the current election

frontends/election-manager/src/app_root.tsx, frontends/election-manager/src/hooks/use_cvrs_query.ts, frontends/election-manager/src/lib/backends/admin_backend.ts, frontends/election-manager/src/lib/backends/memory_backend.ts
Updates client-side tally computation logic to use CVRs from the server to enable removing all CVR data from client-side local storage.
https://user-images.githubusercontent.com/264902/204389687-10a35364-af40-403d-8c6e-d8d3938b958f.mov
- Existing tests for regression detection
- Local run to verify tallies are computed and cleared appropriately
=> [VxAdmin] Use CVRs from the server when computing tallies

frontends/bas/script/react-scripts, frontends/bmd/script/react-scripts, frontends/bsd/script/react-scripts, frontends/election-manager/script/react-scripts, frontends/precinct-scanner/script/react-scripts
I couldn't find the script that these links were pointing to, so I assume it was removed when we migrated to vite.
N/A
N/A
=> chore: Remove dead link to script/react-scripts

frontends/bmd/src/app_end_to_end.test.tsx, frontends/bmd/src/app_polls_flows.test.tsx, frontends/bmd/src/pages/poll_worker_screen.test.tsx, frontends/bmd/src/pages/poll_worker_screen.tsx, frontends/precinct-scanner/src/app.test.tsx, frontends/precinct-scanner/src/app_tally_report_paths.test.tsx, frontends/precinct-scanner/src/screens/poll_worker_screen.tsx, libs/fixtures/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingPausedAllPrecincts.json, libs/fixtures/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingPausedSinglePrecinct.json, libs/fixtures/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingResumedAllPrecincts.json, libs/fixtures/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingResumedSinglePrecinct.json, libs/fixtures/src/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingPausedAllPrecincts.json.ts, libs/fixtures/src/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingPausedSinglePrecinct.json.ts, libs/fixtures/src/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingResumedAllPrecincts.json.ts, libs/fixtures/src/data/electionMinimalExhaustiveSample/precinctScannerCardTallies/votingResumedSinglePrecinct.json.ts, libs/types/src/polls.ts, libs/ui/src/index.ts, libs/ui/src/precinct_scanner_ballot_count_report.test.tsx, libs/ui/src/precinct_scanner_ballot_count_report.tsx, libs/ui/src/precinct_scanner_tally_report.tsx, libs/ui/src/precinct_scanner_tally_reports.test.tsx, libs/ui/src/precinct_scanner_tally_reports.tsx, libs/utils/src/polls.test.ts, libs/utils/src/polls.ts, libs/utils/src/types.test.ts, libs/utils/src/types.ts
Closes #2799. Aims to meet an exhaustive interpretation of VVSG 1.1.9-K:
> The voting system must prevent the printing of vote data reports and extracting vote tally data while the polls are open. Discussion: Providing ballot counts does not violate this requirement. The prohibition is against providing vote totals for ballot contests.
Arguably, having the vote tally data on the card is a way of extracting vote tally data - even if, with java cards, it will become impossible to do so. This PR introduces more specific typing for the reports saved to the card and, in the process, refactors code around the saving, loading, and usage of the card data.
Manually tested the flow with the various types of reports.
=> Removes Tallies from Card for Suspension Reports

frontends/precinct-scanner/src/app.test.tsx, frontends/precinct-scanner/src/screens/poll_worker_screen.test.tsx, frontends/precinct-scanner/src/screens/poll_worker_screen.tsx, libs/logging/src/helpers.test.ts, libs/logging/src/helpers.ts, libs/logging/src/index.ts
To meet VVSG 2.0 1.1.3-B as part of #2800. If we're only doing the warning on VxScan, it closes that issue. If we have to do it on VxMark as well, will make a separate PR. Please review copy below, knowing that this copy will almost certainly never be seen in production. 
I also added logging to the regular polls closed/open/paused actions in a second commit, as this was something missed in the first pass.
Automated testing and added this screen to the Preview App for easy viewing.
=> Non-Zero Total Warning on VxScan

frontends/precinct-scanner/src/screens/election_manager_screen.tsx, services/scan/src/central_scanner_app.test.ts, services/scan/src/cli/render_pages.test.ts, services/scan/src/cli/render_pages.ts, services/scan/src/cli/retry-scan/index.test.ts, services/scan/src/cli/retry-scan/index.ts, services/scan/src/cvrs/export.test.ts, services/scan/src/end_to_end.test.ts, services/scan/src/end_to_end_hmpb.test.ts, services/scan/src/importer.test.ts, services/scan/src/importer.ts, services/scan/src/precinct_scanner_app.ts, services/scan/src/server.ts, services/scan/src/store.test.ts, services/scan/src/store.ts, services/scan/src/util/workspace.ts, services/scan/src/workers/interpret_nh.test.ts, services/scan/src/workers/interpret_nh.ts, services/scan/src/workers/interpret_vx.ts, services/scan/test/helpers/mock_layouts.ts, services/scan/test/helpers/precinct_scanner_app.ts
Instead of #2797, in which I introduced loading screens to handle the slow precinct change, here we optimize on the backend to make the operation faster. This also makes switching modes faster (see video), although switch modes could take longer than in the video if there were more ballots scanned.
https://user-images.githubusercontent.com/37960853/204388692-dac9580c-6d5d-44c8-b8dd-24581fb959a1.mov
=> Fix Precinct Change Lag on VxScan Backend

frontends/election-manager/src/app.test.tsx, frontends/election-manager/src/screens/manual_data_import_precinct_screen.test.tsx, frontends/election-manager/src/screens/write_ins_screen.test.tsx
With the introduction of React Query, we are getting a lot test warnings about updates to unmounted components. This can make it hard to read the test output and can obscure more concerning warnings.
The cause seems to be that React Query is fetching and making state updates after tests have ended. RTL good practice would be to wait for changes on the screen before ending or continuing the test. But in some cases, there are no changes on the screen, because the data is simply refetching or it is fetching data for which we have a default value (so there is no change on screen). I'll comment to point out some of the different cases.
I don't necessarily intend to merge this PR, but I was curious to see what it took to sort out the warnings and to start a discussion around it.
=> Fix Test Warnings in VxAdmin

frontends/election-manager/src/app.test.tsx, frontends/election-manager/src/app_root.tsx, frontends/election-manager/src/app_write_in_flows.test.tsx, frontends/election-manager/src/components/confirm_removing_file_modal.tsx, frontends/election-manager/src/components/import_cvrfiles_modal.test.tsx, frontends/election-manager/src/components/import_cvrfiles_modal.tsx, frontends/election-manager/src/config/types.ts, frontends/election-manager/src/contexts/app_context.ts, frontends/election-manager/src/hooks/use_add_cast_vote_record_file_mutation.ts, frontends/election-manager/src/hooks/use_clear_cast_vote_record_files_mutation.ts, frontends/election-manager/src/hooks/use_cvrs_query.ts, frontends/election-manager/src/hooks/use_election_manager_store.ts, frontends/election-manager/src/index.tsx, frontends/election-manager/src/lib/backends/admin_backend.test.ts, frontends/election-manager/src/lib/backends/admin_backend.ts, frontends/election-manager/src/lib/backends/backends.test.ts, frontends/election-manager/src/lib/backends/memory_backend.ts, frontends/election-manager/src/lib/backends/types.ts, frontends/election-manager/src/screens/reports_screen.tsx, frontends/election-manager/src/screens/tally_report_screen.tsx, frontends/election-manager/src/screens/tally_screen.tsx, frontends/election-manager/src/screens/write_ins_screen.test.tsx, frontends/election-manager/src/screens/write_ins_screen.tsx, frontends/election-manager/src/utils/cast_vote_record_files.test.ts, frontends/election-manager/src/utils/cast_vote_record_files.ts, frontends/election-manager/test/render_in_app_context.tsx
Closes https://github.com/votingworks/vxsuite/issues/2716:
- Replacing all references to CVR data in client-side local storage with queries for server-side data.
- Removing all logic around writing to and reading CVR data from local storage.
- Leaving the `CastVoteRecords` class mostly intact, since it's used with our `memory_backend` test utility.
https://user-images.githubusercontent.com/264902/204634905-846ff00f-13c9-4243-9e34-934cade05b7b.mov
- Updated existing tests to account for the changes
- Manual functional verification, clicking through the various user flows that read/write CVR data and also checking for console errors/warnings:
- Tally screen + import/delete modals
- Write-ins screen
- Reports screen and tally report
- [n/a] I have added …
=> [VxAdmin] Update client to use CVR file metadata from the server

apps/vx-scan/backend/package.json, pnpm-lock.yaml
Accidentally removed too soon in #2821 
It's needed by run-dev when running the backend.
=> Add nodemon back to vx-scan/backend

apps/vx-scan/backend/src/env.d.ts, apps/vx-scan/backend/src/globals.ts, apps/vx-scan/backend/src/interpreter.ts, apps/vx-scan/backend/src/precinct_scanner_state_machine.ts, apps/vx-scan/backend/src/util/images.ts, apps/vx-scan/backend/src/workers/qrcode.ts, libs/image-utils/src/image_data.test.ts, libs/image-utils/src/image_data.ts, libs/plustek-sdk/src/scanner.ts, libs/types/src/result.test.ts, libs/types/src/result.ts
Allows running VxScan with `PLUSTEKCTL_PATH=/path/to/customctl` to work with the Custom America A4 scanner.
```sh
PLUSTEKCTL_PATH=$HOME/code/plustekctl/customctl pnpm start
```
Tested manually with the `customctl` branch of the `plustekctl` repo with an IdeaPad Flex running vxsuite and the UI running in Chrome on macOS. Used the Ashland 11/8/22 election.
=> Add support for `customctl`

libs/image-utils/src/image_data.ts, libs/types/src/result.test.ts, libs/types/src/result.ts
@jonahkagan pointed out this would be closer to idiomatic TypeScript here: https://github.com/votingworks/vxsuite/pull/2828#discussion_r1041315602
n/a
n/a
=> refactor(types): use `assertOk` instead of `unsafeExpect`

frontends/election-manager/src/components/full_test_deck_tally_report_button.test.tsx, frontends/election-manager/src/components/full_test_deck_tally_report_button.tsx, frontends/election-manager/src/components/test_deck_tally_report.tsx, frontends/election-manager/src/screens/print_test_deck_screen.tsx, frontends/election-manager/src/utils/election.ts
Closes #2772 by fixing full test deck tallies for primaries. The problem was that the `ElectionManagerTallyReport` component was expecting / looking for pre-computed party sub-tallies, and we weren't providing them for the test deck tally. Added testing for regressions.
If you look at the PDF, there may be some CSS shading issue with the ballot count breakdown table header. Looking into that.
[fixed_full_test_deck_report.pdf](https://github.com/votingworks/vxsuite/files/10126036/fixed_full_test_deck_report.pdf)
=> fix broken full test deck tally report

apps/vx-scan/frontend/src/components/export_results_modal.test.tsx, apps/vx-scan/frontend/src/components/export_results_modal.tsx, apps/vx-scan/frontend/src/screens/poll_worker_screen.tsx, apps/vx-scan/frontend/src/utils/save_cvr_export_to_usb.test.ts, apps/vx-scan/frontend/src/utils/save_cvr_export_to_usb.ts
Task: #2814 
Before moving the CVR export logic to the backend, simplifying it by removing the ability to save it anywhere other than a USB.
- Manual test
- Removed relevant automated tests
=> feat(vx-scan): Remove option to export CVR to custom location

libs/image-utils/src/image_data.test.ts, libs/image-utils/src/image_data.ts
The `.raw` format we previously supported was just my workaround for not having `libjpeg` integrated with `customctl`. For now we still need a workaround, but I found the old standard [PGM file format](https://en.wikipedia.org/wiki/Netpbm) that we can use instead.
n/a
=> feat(image-utils): use the standard PGM raw image format

apps/vx-scan/backend/package.json, apps/vx-scan/backend/src/app.ts, apps/vx-scan/backend/src/app_config.test.ts, apps/vx-scan/backend/src/app_scan.test.ts, apps/vx-scan/backend/src/backup.ts, apps/vx-scan/backend/src/index.ts, apps/vx-scan/backend/src/interpret.ts, apps/vx-scan/backend/src/state_machine.ts, apps/vx-scan/backend/src/store.ts, apps/vx-scan/backend/src/types.ts, apps/vx-scan/backend/test/helpers/app_helpers.ts, apps/vx-scan/frontend/package.json, apps/vx-scan/frontend/src/app.test.tsx, apps/vx-scan/frontend/src/app_root.tsx, apps/vx-scan/frontend/src/components/calibrate_scanner_modal.test.tsx, apps/vx-scan/frontend/src/components/calibrate_scanner_modal.tsx, apps/vx-scan/frontend/src/hooks/use_precinct_scanner_status.test.tsx, apps/vx-scan/frontend/src/hooks/use_precinct_scanner_status.ts, apps/vx-scan/frontend/src/screens/election_manager_screen.tsx, apps/vx-scan/frontend/src/screens/scan_error_screen.tsx, apps/vx-scan/frontend/test/helpers/helpers.ts, apps/vx-scan/frontend/test/helpers/mock_api_client.ts, frontends/bsd/src/screens/ballot_eject_screen.tsx, frontends/bsd/src/screens/dashboard_screen.test.tsx, frontends/bsd/src/screens/dashboard_screen.tsx, libs/api/src/services/scan/index.ts, libs/types/src/election.ts, pnpm-lock.yaml, services/scan/src/store.ts
Task: #2814 
There were a bunch of types that were used by the scan service but only applied to the precinct scanner. Now that VxScan is its own contained app, those types can live within the backend and be imported by the frontend.
There were also a few shared scanning types that I moved into libs/types. Now libs/api/scan only contains types used by VxCentralScan, so when we convert it to the new app-based architecture, we can similarly move those types into the app.
N/A
- Existing tests
=> refactor(vx-scan): Move types from libs/api into apps/vx-scan/backend

libs/grout/src/grout.test.ts, libs/grout/src/server.ts
Task: #2858 
To aid debugging unexpected errors, make sure we log the actual error so we can see a stack trace.
N/A
- Added unit test
=> feat(grout): Log unexpected errors to console to show stack trace

apps/vx-scan/backend/src/app.ts, libs/grout/README.md, libs/grout/src/client.ts, libs/grout/src/grout.test.ts, libs/grout/src/server.ts, libs/grout/test-utils/src/mock_client.test.ts, libs/grout/test-utils/src/mock_client.ts
Task: #2858 
Many of our RPC methods won't actually be async functions on the backend
since we use a sync db interface. This small change allows those
methods to be defined sync in the server and still be typed as async
functions in the client.
N/A
- Updated tests
=> feat(grout): Allow sync methods to not return a Promise

docs/commit_signing.md
Uses Git's newish support for signing commits with SSH keys. Configures an SSH agent run by 1Password to provide both SSH auth and commit signing.
[Rendered](https://github.com/votingworks/vxsuite/blob/docs/1password-commit-signing/docs/commit_signing.md)
Documented as I set it up on my machine. I'd like at least one other reviewer to try it and fix any steps that don't work for them before merging.
=> docs: add instructions for signing commits

apps/vx-scan/frontend/src/screens/unconfigured_election_screen.tsx, libs/ui/package.json, libs/ui/src/hooks/use_change_listener.test.ts, libs/ui/src/hooks/use_change_listener.ts, libs/ui/src/index.ts, pnpm-lock.yaml
Adds two new hooks to `libs/ui` for registering a change listener to run on external state changes. See hook documentation in the code for full explanation. The goal is to make a safer alternative to using a `useEffect` hook to try to listen to an external state change.
Uses one of these hooks in VxScan as an example.
N/A
=> feat(ui): Change listener hooks

.circleci/config.yml
Upgrading the circleci `browser-tools` to v1.4.1 to fix the integration test failures that started yesterday.
Relevant issue here: https://github.com/CircleCI-Public/browser-tools-orb/issues/62
=> Try upgrading circleci orb version to fix integration test builds

.circleci/config.yml, frontends/election-manager/src/app.test.tsx
A couple of our `election-manager` tests are passing in CI but not locally. In CI, we copy the `.env` file from the root of `vxsuite` to the root of the library. 
To avoid this confusion (speaking for myself, a confused lad), I'd prefer to remove the special treatment in CI and update the tests so that they are passed the necessary information within the test. Alternatively, we could update the `package.json` script to use the env variable, but I am not sure we will always want `REACT_APP_VX_CONVERTER=ms-sems` and don't want to be locked into that.
=> Avoid relying on env variables for election manager tests

docs/commit_signing.md
https://github.blog/2023-01-17-git-security-vulnerabilities-announced-2/
n/a
Ran the commands myself, verified `git --version` outputs `2.39.1`.
=> docs: update git version to 2.39.1

libs/eslint-plugin-vx/src/rules/gts_spread_like_types.ts, libs/eslint-plugin-vx/tests/rules/gts_spread_like_types.test.ts
I guess we don't use classes much. Before, this error would occur with e.g. `new A(...b)`:
```
Error: unexpected spread element parent: NewExpression
Occurred while linting /home/brian/code/vxsuite/libs/message-coder/src/literal_coder.ts:66
Rule: "vx/gts-spread-like-types"
```
See above.
Fixed the issue and tested on the code that originally caused the above error.
=> fix(lint): make `gts-spread-like-types` work with `new`

libs/ui/.storybook/preview.tsx, libs/ui/src/prose.stories.tsx
Related to: https://github.com/votingworks/vxsuite/issues/2743
- Updated storybook.js configuration to include global color and size theme pickers.
- Added a bit more content to the `<Prose>` demo to see how sub-elements change with different base font sizes.
https://user-images.githubusercontent.com/264902/214975537-c27f24c0-0366-454d-a000-d66d1bbc9781.mov
- Just manual testing for this one
=> [lbis/ui] Add color/size theme pickers to storybook

apps/vx-mark/frontend/script/prod-build
This symlink needed to be updated for moving this directory 1 step further in the nesting.
=> Fix build script symlink for vxmark

apps/vx-mark/frontend/src/setupTests.tsx, apps/vx-scan/frontend/src/setupTests.ts, frontends/bsd/src/setupTests.ts, frontends/election-manager/src/setupTests.ts, libs/test-utils/src/index.ts, libs/test-utils/src/react.ts, libs/ui/src/setupTests.ts
Suppresses this warning which is not a warning in React 18:
> Can't perform a React state update on an unmounted component.
|-|-|
|<img width="969" alt="image" src="https://user-images.githubusercontent.com/1938/217073493-911b2279-9708-405e-8b85-84172d1644df.png">|<img width="672" alt="image" src="https://user-images.githubusercontent.com/1938/217073605-fcea741c-a7c3-4e65-a714-6ac7e2f98c43.png">|
Tested locally, also can examine CircleCI output.
=> test: suppress non-useful React 17 error in tests

apps/vx-scan/backend/src/app.ts, apps/vx-scan/backend/src/app_scan.test.ts, apps/vx-scan/backend/src/state_machine.ts, apps/vx-scan/backend/src/types.ts, apps/vx-scan/frontend/src/api.ts, apps/vx-scan/frontend/src/app.test.tsx, apps/vx-scan/frontend/src/app_unhappy_paths.test.tsx, apps/vx-scan/frontend/src/components/calibrate_scanner_modal.test.tsx, apps/vx-scan/frontend/src/components/calibrate_scanner_modal.tsx, apps/vx-scan/frontend/src/screens/election_manager_screen.test.tsx, apps/vx-scan/frontend/src/screens/election_manager_screen.tsx, apps/vx-scan/frontend/src/screens/scan_error_screen.tsx, apps/vx-scan/frontend/test/helpers/mock_api_client.tsx, libs/plustek-scanner/src/mocks.test.ts, libs/plustek-scanner/src/mocks.ts, libs/plustek-scanner/src/scanner.ts
The Custom scanner does not seem to support calibration. This adds the `supportsCalibration` API to determine whether the current scanner supports calibration. Currently it is hardcoded to return `true`, but that will change with the introduction of the Custom scanner.
Tested manually, added automated tests.
=> feat(vx-scan): add `supportsCalibration` API

script/setup-dev
When the setup-dev script runs even if node doesn't need to be updated we should still run corepack enable in case things like pnpm need updates. VxDev relies on this script for keeping things up to date.
=> fix subtle issue with setup dev script

apps/vx-mark/backend/Makefile
vx-mark's backend has no real `make install` requirement. Rather than calling the `build` directive, which introduces dependencies that can fail on a clean system, make it a no-op. This will eventually go away as system level configuration is moved out of Makefiles, but this is a fix for now.
=> define a no-op for make install so complete-system build doesnt fail

libs/message-coder/src/constants.ts, libs/message-coder/src/uint16_coder.test.ts, libs/message-coder/src/uint16_coder.ts, libs/message-coder/src/uint24_coder.test.ts, libs/message-coder/src/uint24_coder.ts, libs/message-coder/src/uint2_coder.test.ts, libs/message-coder/src/uint2_coder.ts, libs/message-coder/src/uint32_coder.test.ts, libs/message-coder/src/uint32_coder.ts, libs/message-coder/src/uint4_coder.test.ts, libs/message-coder/src/uint4_coder.ts, libs/message-coder/src/uint8_coder.test.ts, libs/message-coder/src/uint8_coder.ts, libs/message-coder/src/uint_coder.ts
Without this we'd just call e.g. `Buffer#writeUInt8` and throw an exception. Now we properly return an `Err` result.
n/a
New automated tests.
=> fix(message-coder): validate uint values

apps/admin/backend/src/server.test.ts, apps/admin/backend/src/server.ts, apps/central-scan/backend/src/central_scanner_app.test.ts, apps/central-scan/backend/src/central_scanner_app.ts, apps/scan/backend/src/app.ts, apps/scan/backend/src/app_config.test.ts, libs/auth/src/dipped_smart_card_auth.ts, libs/auth/src/dipped_smart_card_auth_with_memory_card.test.ts, libs/auth/src/dipped_smart_card_auth_with_memory_card.ts, libs/auth/src/inserted_smart_card_auth.ts, libs/auth/src/inserted_smart_card_auth_with_memory_card.test.ts, libs/auth/src/inserted_smart_card_auth_with_memory_card.ts, libs/auth/src/test_utils.ts, vxsuite.code-workspace
_Reviewing by commit recommended_
This PR adjusts how the auth lib accesses the election definition. I've thus far been having backends configure the auth lib with the election definition on startup and subsequent election definition changes, meaning that the auth lib is essentially caching the election definition. This is error prone since we have to remember to update the auth lib's copy of the election definition any time it changes in the containing backend.
This PR looks at an alternative: having the backend provide the election definition on every auth lib call. Even though the frontend polls auth status, we're not worried about this from a performance perspective since 1) SQLite can comfortably handle this read pattern and 2) we're in a fully local context.
=> Take election def as input in auth lib methods

libs/types/src/ui_theme.ts, libs/ui/.storybook/preview.tsx, libs/ui/src/global_styles.tsx, libs/ui/src/themes/make_theme.ts, libs/ui/src/typography.stories.tsx, libs/ui/src/typography.tsx
- Adding colors for low-luminosity/low-contrast (4.5:1) and medium-contrast (10:1) themes
- Adding border size config that will be used later for components like <Button>
- Adding `semiBold` option for font weight for cases where bold is just too bold
- Fixing an issue with stacked headings not having their margins collapsed - didn't initially take into account the fact that we can render <H3 as="h2"> for example. Now just collapsing margins between all adjacent headings.
https://user-images.githubusercontent.com/264902/218521170-9ec17b01-ac3d-462a-9761-eeb0b298fbd4.mov
- Config/styling changes only - no tests needed...what a time to be alive!
- [n/a] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system …
=> Update UI theme settings, based on prototype and team feedback

libs/message-coder/src/base_coder.test.ts, libs/message-coder/src/base_coder.ts, libs/message-coder/src/fixed_string.test.ts, libs/message-coder/src/fixed_string.ts, libs/message-coder/src/literal_coder.test.ts, libs/message-coder/src/literal_coder.ts, libs/message-coder/src/message_coder.test.ts, libs/message-coder/src/message_coder.ts, libs/message-coder/src/padding_coder.test.ts, libs/message-coder/src/padding_coder.ts, libs/message-coder/src/types.ts, libs/message-coder/src/uint16_coder.ts, libs/message-coder/src/uint1_coder.test.ts, libs/message-coder/src/uint1_coder.ts, libs/message-coder/src/uint24_coder.ts, libs/message-coder/src/uint2_coder.test.ts, libs/message-coder/src/uint2_coder.ts, libs/message-coder/src/uint32_coder.ts, libs/message-coder/src/uint4_coder.ts, libs/message-coder/src/uint8_coder.ts, libs/message-coder/src/uint_coder.ts, libs/message-coder/src/unbounded_string_coder.test.ts, libs/message-coder/src/unbounded_string_coder.ts
Useful for building values for coders in tests.
n/a
Automated.
=> feat(message-coder): create default values from coders

libs/types/src/hmpb.test.ts, libs/types/src/hmpb.ts
It's similar to the index parameter on the `map` callback and is similarly useful in some cases.
n/a
n/a
=> feat(types): add side parameter to `mapSheet`

libs/ui/src/react_query.test.ts, libs/ui/src/react_query.ts
With the shift to react-query and our specific default options (notably `retry: false` and `useErrorBoundary: true`), we often see the frontend error boundary get triggered when the backend is spinning up or restarting due to changes. We've seen this in dev, but I suspect it could affect prod, too.
<table><tr><td>
</table></tr></td>
This PR modifies our react-query query client default options with a custom retry function in place of `retry: false` to prevent this.
=> Modify react-query query client default options

libs/grout/src/serialization.ts
The helper function to determine if a value is a JSON built-in value was mistakenly identifying `undefined` as a built-in, which it's not (it only exists in JS value space, not JSON). This didn't actually impact the end logic that used this function, but that was just by chance. Fixing this to prevent any future bugs that might occur from this being wrong.
N/A
Existing tests still pass
=> fix(grout): Fix latent bug in serializing undefined

README.md
Fixes formatting and path for BMD app in the README. Other paths at the top of the README are also outdated but I don't know the new paths; feel free to comment and I'll update
Before
After
N/A README change only
Not applicable:
=> fix formatting and BMD path in README

apps/scan/backend/src/index.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, libs/custom-scanner/package.json, libs/custom-scanner/src/cli/demo/index.ts, libs/custom-scanner/src/custom_a4_scanner.ts, libs/custom-scanner/src/protocol.ts, libs/custom-scanner/src/types/custom_scanner.ts, pnpm-lock.yaml
Improves jam error handling to pause before retrying scanning which seems to prevent a variety of strange race conditions in the custom scanner. It also introduces a "jam_cleared" state where when all the paper sensors are 0 after a jam has been encountered we will try to reset the hardware, which involves issuing a reset command and then reestablishing a new connection to the scanner. If the jam is cleared the internal isPaperJam status of the custom scanner will reset to false by doing this.
In a second commit I made some changes to the demo program in libs/custom-scanner to make it easier to work with for manual testing. It's not that well thought out right now just calls anything you can call in Scanner, we should improve this in the future but I think its ok for now.  …
=> Custom scanner tweaks

libs/auth/src/apdu.ts, libs/auth/src/card.ts, libs/auth/src/card_reader.ts, libs/auth/src/java_card.ts, libs/auth/src/memory_card.ts
Issue link: https://github.com/votingworks/vxsuite/issues/2908
This PR completes the Java Card implementation of the card API's data storage methods (`readData`, `writeData`, and `clearData`).
Automated tests will be coming in follow-up PRs!
=> Complete Java Card implementation of data storage methods

libs/backend/src/scan/cast_vote_records/build_report_metadata.ts, libs/backend/src/scan/cast_vote_records/export.ts, libs/utils/src/index.ts, libs/utils/src/json_stream.test.ts, libs/utils/src/json_stream.ts, libs/utils/src/votes.test.ts
This is some follow-up to #3032, which I was doing a light review of while it got merged. I found the `JSON.stringify(…).replace(…)` we had there to be pretty janky and thought we should do better. This is my attempt to do that.
=> refactor(backend): use `jsonStream` to simplify CVR streams

libs/auth/src/card_reader.ts, libs/auth/src/certs.ts, libs/auth/src/index.ts, libs/auth/src/java_card.ts, libs/auth/src/openssl.ts, libs/auth/src/piv.ts, libs/auth/test/utils.ts
_Reviewing by commit recommended_
Issue link: https://github.com/votingworks/vxsuite/issues/2909
This PR completes the Java Card implementation of the card API's card programming methods (`program` and `unprogram`). By extension, this completes the Java Card implementation of the card API!
It also cleans up existing Java Card code, better organizing across files:
- `openssl.ts` - Generic openssl commands (not VotingWorks-specific)
- `piv.ts` - PIV standards (not VotingWorks-specific)
- `certs.ts` - VotingWorks-specific cert logic
- `java_card.ts` - Top-level logic
Automated tests will be coming in follow-up PRs!
=> Complete Java Card implementation of card programming methods

services/scan/src/precinct_scanner_interpreter.ts
In a different part of the code this is the logic for figuring out if a sheet requires adjudication, both pages must be "blank" but any pages with 0 possible marks are automatically considered blank, so I'm updating this part of the code that tells the state machine what to tell the frontend about the adjudication reason to do the same thing
=> handle single sided blank ballots properly

apps/scan/backend/src/interpret.ts
Fixes a bug where if a ballot is blank, the BlankBallot adjudication reason will not work properly if there are only contests on one side of the ballot in precinct-scanner. It will be marked as requiring adjudication as the code in vx_interpret does the right thing, but this part of the code does not (why is this logic duplicated?). Testing this would be complicated as I don't think we have an election definition that has this case so I'm just fixing the bug right now. 
=> Fix blank ballot adjudication on precinct scanner

apps/scan/frontend/src/app.tsx, apps/scan/frontend/src/preview_app.tsx, apps/scan/frontend/src/scan_app_base.tsx
Related to: https://github.com/votingworks/vxsuite/issues/2744
- Creating a `ScanAppBase` that renders `libs/ui/AppBase` with the VxScan defaults, so they can be shared between the production app and preview app.
- Also moving the app base to the top level of the render tree to make sure all components use the global styles/themes (including the newly added top-level `ErrorBoundary`)
N/A - No functional changes
- [N/A] I have added
- [n/a] I have added the "user_facing_change" label to this PR to automate an
=> [VxScan] Make sure prod app and preview app share global styles/themes

apps/admin/backend/src/server.ts, apps/central-scan/backend/src/server.ts, apps/mark/backend/src/server.ts, apps/scan/backend/src/server.ts, libs/auth/src/dipped_smart_card_auth.test.ts, libs/auth/src/dipped_smart_card_auth.ts, libs/auth/src/inserted_smart_card_auth.test.ts, libs/auth/src/inserted_smart_card_auth.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/src/log_documentation.test.ts, libs/logging/src/log_event_ids.ts
Issue links: https://github.com/votingworks/vxsuite/issues/3056, https://github.com/votingworks/vxsuite/issues/2528
This PR re-adds auth logging that I consciously dropped while moving auth to the backend.
Will cover logging in upcoming automated tests as well!
=> Re-add auth logging

libs/auth/jest.config.js, libs/auth/package.json, libs/auth/src/apdu.test.ts, libs/auth/src/apdu.ts, libs/auth/src/card_reader.test.ts, libs/auth/src/card_reader.ts, libs/auth/src/certs.test.ts, libs/auth/src/certs.ts, libs/auth/src/piv.test.ts, libs/auth/test/utils.ts, libs/auth/tsconfig.build.json, libs/auth/tsconfig.json, pnpm-lock.yaml
_Reviewing by commit recommended_
Issue link: https://github.com/votingworks/vxsuite/issues/3057
I'm finally going back and adding all the `libs/auth` tests that I've been punting on 😅
This PR covers some of the lower-level files: `apdu.ts`, `card_reader.ts`, `certs.ts`, and `piv.ts`. I'll cover the rest of the files and reach 100% code coverage in a next PR (or PRs).
=> Add libs/auth tests, part 1

apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/types.ts, apps/scan/frontend/src/screens/scan_error_screen.tsx, libs/custom-scanner/.gitignore
Makes a few changes to the state machine:
- If paper is seen when an accept is processing, it will be interrupted with a load paper command and the first sheet will be accepted. If the second sheet is in the scanner after this it will be rejected forward and scanned through as well.
- If the scanner cover opens we will go to internal connection problem screen until closed
- If the scanner disconnects it now properly goes to the disconnected state so that it recovers when reconnected
I also noticed we were handling jams strangely in debugging issues here and I think we need to handle jams that are unexpected situations we treat like a jam differently from when the scanner is actually telling us there is a jam. We do not need to do the resetHardware thing when the scanner isn't telling us …
=> Improve Custom State Machine Handling

apps/admin/frontend/jest.config.js, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/full_test_deck_tally_report_button.test.tsx, apps/admin/frontend/src/components/full_test_deck_tally_report_button.tsx, apps/admin/frontend/src/components/save_file_to_usb.tsx, apps/admin/frontend/src/screens/print_test_deck_screen.test.tsx, apps/admin/frontend/src/screens/print_test_deck_screen.tsx, apps/admin/frontend/src/screens/printed_ballots_report_screen.test.tsx, apps/admin/frontend/src/screens/printed_ballots_report_screen.tsx, apps/admin/frontend/src/screens/tally_report_screen.tsx, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/src/log_documentation.test.ts, libs/logging/src/log_event_ids.ts, libs/ui/src/print_element.tsx
Adds a "Save PDF" option in all places we were missing it in VxAdmin.
Added simple tests for render of `SaveFileToUsb` modal. There are 2 options for more robust tests
1. Trust that SaveFileToUsb is covered by its own tests; validate that `SaveFileToUsb` is wired up with the correct props in each case
2. Write a functional test with mock USB to assert files are saved with the correct data
- The existing SaveFileToUsb component logs when file writing succeeds or fails
- no new exports
=> Support save PDF option in all places we print from vxadmin

apps/scan/backend/src/app_config.test.ts, apps/scan/backend/src/cvrs/export.test.ts, apps/scan/backend/src/cvrs/export.ts, apps/scan/backend/src/store.ts
Reapplies the change made in #2692 which was somehow lost along the way, which is a privacy concern. VxScan no longer has option to export them in a non-randomized order, so the testing should keep it random.
=> Ensure VxScan CVRs are randomly sorted

services/scan/src/precinct_scanner_app.ts
Analogous to #3090 applied to `main`, but looks a lot different because at this time the `scan` backends were not split and VxScan was not using `grout`.
=> fix(scan): orderBySheetId in VxScan for voter privacy

apps/central-scan/backend/src/store.test.ts, apps/central-scan/backend/src/store.ts, apps/central-scan/frontend/src/app.test.tsx, apps/central-scan/frontend/src/screens/dashboard_screen.test.tsx, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, libs/backend/src/scan/cast_vote_records/build_report_metadata.test.ts, libs/backend/src/scan/cast_vote_records/build_report_metadata.ts, libs/types/src/cdf/cast-vote-records/index.test.ts, libs/types/src/cdf/cast-vote-records/index.ts, libs/types/src/cdf/cast-vote-records/vx-schema.json, libs/types/src/election.ts
Per [internal discussion](https://votingworks.slack.com/archives/CEL6D3GAD/p1678208279298859) about making our cast vote records more audit friendly, this change adds the following batch information to the CDF CVR (still feature-flagged):
- SequenceId (or batchNumber)
- Batch Start Time
- Batch End Time (if exists)
- Batch Size
One wrinkle on precinct scanner may be that we may export cast vote records before the polls are officially closed, so the last (and likely only) batch will not have an end time. I don't think solving that problem is within the scope of this PR if it is important.
=> Add Batch Info to CVR

libs/auth/jest.config.js, libs/auth/src/apdu.test.ts, libs/auth/src/card_reader.test.ts, libs/auth/src/certs.test.ts, libs/auth/src/openssl.test.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3057
Another day 🌅, another `libs/auth` tests PR. This PR specifically adds tests for openssl helpers.
=> Add libs/auth tests, part 2

apps/scan/backend/src/interpret_nh_next_adapter.ts
The interpreter already takes care of putting page 1 as front and page 2 as back. This is of course not compatible with multi-sheet ballots but in general I'm not sure we are yet, and a fix for that would be a lot more involved.
=> fix(nh-next): ensure proper pageNumber on back page

apps/admin/frontend/src/components/hand_marked_paper_ballot.tsx
Currently, the text of "Yes" and "No" options in our ballot measures are not allowed to wrap in the ballot. With the recent change removing the special casing of either-neither in the hand-marked paper ballot (#2972), that means that our either-neither ballots are currently broken. This means they won't scan, their layouts won't be generated correctly, and we can't infer a lot of information about them.
I know we're going to change our ballot generation and layout soon but even if it's only in the interim I'd like to merge this and not have some of or main fixtures broken.
=> Fix Broken Either Neither

libs/backend/src/scan/cast_vote_records/__snapshots__/export.test.ts.snap, libs/backend/src/scan/cast_vote_records/build_cast_vote_record.test.ts, libs/backend/src/scan/cast_vote_records/build_cast_vote_record.ts, libs/types/src/cdf/cast-vote-records/index.test.ts, libs/types/src/cdf/cast-vote-records/index.ts, libs/types/src/cdf/cast-vote-records/vx-schema.json
We've discussed whether this is necessary, but might as well just do it as long as it's easy per discussions with Jessica. See discussion in #1240. We already have a count of write-ins per contest if any exist. This adds a cumulative count of write-ins at the at the CVr snapshot level, if it exists.
=> Add Total Write-In Count

libs/types/package.json, libs/types/src/cdf/cast-vote-records/index.test.ts, libs/types/src/cdf/cast-vote-records/index.ts, libs/types/src/cdf/cast-vote-records/vx-schema.json, libs/types/test/cdf_schema_utils.test.ts, libs/types/test/cdf_schema_utils.ts, pnpm-lock.yaml
_Review commit-by-commit_
Add a few restrictions on the CDF CVR. Primarily:
- Requiring some VVSG 2.0 necessary metadata on the CVR
- Requiring batch information in the report
- Removing party & retention contests
Also added testing for the CDF CVR schema in this PR similar to the ballot definition schema. A few adjustments had to be made:
- The NIST schema has unused definitions, so only testing that on the VX schema
- The NIST schema (and forked VX schema) are a different version of the JSON schema spec and thus require a variant library of `ajv`
- In the VX schema for cast vote records we've added a definition, so I needed to add a carveout to the subset validation that allowed custom definitions prefixed with `vx`.
=> CDF CVR Schema Restrictions & Testing

libs/auth/README.md, libs/auth/jest.config.js, libs/auth/src/card.ts, libs/auth/src/dipped_smart_card_auth.ts, libs/auth/src/inserted_smart_card_auth.ts, libs/auth/src/java_card.ts, libs/auth/src/memory_card.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/src/log_event_ids.ts, libs/types/src/auth/dipped_smart_card_auth.ts, libs/types/src/auth/inserted_smart_card_auth.ts, libs/ui/src/unlock_machine_screen.test.tsx, libs/ui/src/unlock_machine_screen.tsx
A miscellaneous auth cleanup PR. I was making these changes as I was working on auth tests and decided to extract them into their own PR.
The changes include:
- More comprehensively and holistically handling PIN check errors
- Cleaning up auth logging (specifically card programming logging) and including more details where possible
As part of the updates to PIN check error handling, I introduced this new screen:
Should be seen very rarely if ever (e.g. if a card malfunctions during PIN checking) but is now there for completeness!
Automated tests are on their way in my next PR 🤖
=> Miscellaneous auth cleanup

apps/admin/backend/package.json, apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/cvr_files.test.ts, apps/admin/backend/src/cvr_files.ts, apps/admin/backend/src/server.test.ts, apps/admin/backend/src/server.ts, apps/admin/backend/src/types.ts, apps/admin/backend/src/util/usb.ts, apps/admin/backend/test/app.ts, apps/admin/backend/tsconfig.build.json, apps/admin/backend/tsconfig.json, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/components/import_cvrfiles_modal.test.tsx, apps/admin/frontend/src/components/import_cvrfiles_modal.tsx, apps/admin/frontend/test/helpers/api_mock.ts, libs/backend/jest.config.js, libs/backend/src/index.ts, libs/backend/src/list_directory.test.ts, libs/backend/src/list_directory.ts, pnpm-lock.yaml
We list available CVR files on a USB drive for the user when they are importing CVR files. This PR moves the listing (reading of the directory on the USB drive) from the frontend to the backend. We'll have to update this listing and loading code when we switch to CVR CDF so it seemed appropriate to first move it to the backend.
Closes #3076, but does not achieve one of its main goals - re-enabling the integration testing disabled in #3052. See below for discussion.
- Testing in `libs/backend`, `admin/backend` and `admin/frontend`
=> VxAdmin: List Available CVR Files on Backend

.github/pull_request_template.md
GitHub seemingly has different Markdown renderers. The README renderer is fine with the formatting as it was and renders it as expected. The PR description one renders the whitespace differently, so we have to put it all on one line if we want it rendered properly.
n/a
n/a
=> chore: fix PR template formatting

apps/admin/frontend/src/components/smartcard_modal/smartcard_modal.test.tsx, apps/admin/frontend/src/components/smartcard_modal/smartcard_modal.tsx, apps/mark/backend/src/server.ts, apps/scan/backend/src/server.ts, libs/auth/jest.config.js, libs/auth/src/card.ts, libs/auth/src/card_reader.ts, libs/auth/src/certs.ts, libs/auth/src/dipped_smart_card_auth.test.ts, libs/auth/src/dipped_smart_card_auth.ts, libs/auth/src/inserted_smart_card_auth.test.ts, libs/auth/src/inserted_smart_card_auth.ts, libs/auth/src/inserted_smart_card_auth_api.ts, libs/auth/src/java_card.ts, libs/auth/src/memory_card.ts, libs/auth/test/utils.ts, libs/basics/src/errors.test.ts, libs/basics/src/errors.ts, libs/basics/src/index.ts, libs/types/src/auth/auth.ts, libs/types/src/auth/dipped_smart_card_auth.ts, libs/types/src/auth/inserted_smart_card_auth.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3057
More `libs/auth` tests, this time for the top-level auth API implementations
=> Add libs/auth tests, part 3

libs/utils/src/json_stream.test.ts
- `fc.jsonObject()` might produce `-0` which serializes to `"0"` which then parses as `0` which Jest `toEqual` considers different from `-0` (see [failing build](https://app.circleci.com/pipelines/github/votingworks/vxsuite/8427/workflows/9f690331-aacc-4e5a-a8b7-696c01bf3c6a/jobs/230657))
- stop using `any` to get rid of warnings
n/a
Automated.
=> test(utils): fix minor issues

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
As long as we're aping Rust's `Iterator`, let's do it properly! https://doc.rust-lang.org/1.68.0/std/iter/trait.Iterator.html
I took [this comment](https://github.com/votingworks/vxsuite/pull/3129#discussion_r1142593332) as tacit support for this.
n/a
Automated.
=> feat(basics): add `windows` method for `iter`

libs/ballot-interpreter-vx/src/interpreter/enforcing_test_vs_live_mode.test.ts, libs/ballot-interpreter-vx/src/interpreter/handles_lines_connecting_contest_boxes.test.ts, libs/ballot-interpreter-vx/src/interpreter/interpret_bailout_on_skew.test.ts, libs/ballot-interpreter-vx/src/layout.ts, libs/ballot-interpreter-vx/test/helpers/fixtures_to_templates.ts
Investigation into how to stop using/remove `Interpreter#interpretTemplate` per https://github.com/votingworks/vxsuite/pull/3180#discussion_r1145148569.
=> proof-of-concept for removing `Interpreter#interpretTemplate`

apps/scan/frontend/src/screens/scan_warning_screen.tsx
Noticed the undervote warning screen was showing two primary buttons while auditing VxScan screens. Changing the "Cast Ballot As Is" to a regular button to match the behaviour of the overvote warning screen.
=> [VxScan] Fix undervote warning screen showing two primary buttons

.circleci/config.yml
This PR updates our CircleCI config to use an updated set of docker images with Rust already installed to a pinned version. It also sets up the necessary ENV vars.
Run CircleCI with it. All tests should pass.
=> use updated image with rust installed

apps/admin/frontend/src/screens/unconfigured_screen.tsx
I noticed when working in VxAdmin that the `UnconfiguredScreen` was rendering around 1000 times / second. After some debugging, I found there was re-rendering loop:
1. `UnconfiguredScreen` renders
2. `configureMutation` changes - @jonahkagan, every time we use `useMutation` it's a distinct entity because the `useMutation` function creates and returns a new function. Is this desirable behavior? Could it be memoized?
3. `configureMutateAsync` callback changes
4. `getOutputFile` callback changes
5. `updateStatus` callback changes
6. `useEffect` runs
7. `updateStatus` called
8. `setInputConversionFiles` called
9. `inputConversionFiles` state changes
10. `UnconfiguredScreen` renders
11. ...
I must have introduced this in #3052.
I'm not sure why, but this re-rendering loop was preventing me …
=> Unconfigure Screen Re-Render Cycle Fix

.gitignore
Rust has a `target` directory that is used for build artifacts. Ignoring it at the root is useful when working on a Rust project that isn't checked into all branches, preventing all the `target` files from being shown as untracked when switching branches.
=> chore(git): add Rust `target` to `.gitignore`

libs/utils/src/json_stream.test.ts
I'd previously tried to address an issue with this test failing due to `-0` in #3174, but I only filtered `-0` at the top level, so e.g. `{"":-0}` could [still cause issues](https://app.circleci.com/pipelines/github/votingworks/vxsuite/8617/workflows/77db4d0a-38ef-4164-b940-dae71d66a6b7/jobs/238226). This commit fixes the issue by running the input through `JSON.parse(JSON.stringify(…))` which also drops `-0`.
n/a
Automated.
=> test(utils): fix `-0` issue

apps/scan/backend/src/app.ts, apps/scan/backend/src/index.ts, apps/scan/backend/src/scanners/plustek/app_config.test.ts, apps/scan/backend/src/scanners/plustek/app_scan.test.ts, apps/scan/backend/src/scanners/plustek/app_scan_calibrate.test.ts, apps/scan/backend/src/scanners/plustek/app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/plustek/app_scan_jam.test.ts, apps/scan/backend/src/scanners/plustek/app_scan_power_off.test.ts, apps/scan/backend/src/scanners/plustek/app_scan_precinct_config.test.ts, apps/scan/backend/src/scanners/plustek/state_machine.ts, apps/scan/backend/src/server.test.ts, apps/scan/backend/src/server.ts, apps/scan/backend/src/types.ts, apps/scan/backend/test/helpers/plustek_helpers.ts, apps/scan/backend/test/helpers/shared_helpers.ts, apps/scan/frontend/src/screens/scan_error_screen.tsx
Progress toward #3166. I'm landing this separately because I've done this bit three times now and `main` keeps changing out from under me and generates conflicts in ways that are hard to resolve.
The next step will be to introduce the Custom scanner support alongside the plustek support.
n/a
Automated.
=> refactor(scan): isolate plustek-specific code

apps/admin/frontend/src/components/export_election_ballot_package_modal_button.tsx
Write `DEFAULT_SYSTEM_SETTINGS` from VxAdmin.
Fixes a bug where VxAdmin writes `{}` if no system settings are present, but other machines can't read empty object for system settings.
Will do in a separate PR to unblock others
Does not apply
=> write default system settings

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
Also improves support for the async iterable methods to take either async or sync iterables.
```ts
/// BEFORE
const loadedLayouts: BallotPageLayoutWithImage[] = [];
for (const [pdf, layouts] of templates) {
for await (const { page, pageNumber } of pdfToImages(pdf, { scale: 2 })) {
const ballotPageLayout = layouts[pageNumber - 1];
loadedLayouts.push({
ballotPageLayout,
imageData: page,
});
}
}
this.cachedLayouts = loadedLayouts;
return loadedLayouts;
/// AFTER
this.cachedLayouts = await iter(templates)
.async()
.flatMap(([pdf, layouts]) =>
iter(pdfToImages(pdf, { scale: 2 }))
.zip(layouts)
.map(([{ page: imageData }, ballotPageLayout]) => ({
ballotPageLayout,
imageData,
}))
)
.toArray();
return this.cachedLayouts;
```
=> feat(basics): add `#flatMap`

libs/auth/scripts/generate_dev_keys_and_certs.ts, libs/auth/src/certs.ts, libs/auth/src/java_card.test.ts, libs/auth/src/java_card.ts, libs/auth/src/openssl.test.ts, libs/auth/src/openssl.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3110
This PR implements card cert expiries, specifically:
- 100 years for VotingWorks-issued card certs 🧓
- 5 years for VxAdmin-issued sys admin card certs 🧒
- 6 months for VxAdmin-issued election card certs 👶
Certs generated by the `generate-dev-keys-and-certs` and `generate-test-keys-and-certs` scripts will continue to last for 100 years.
The PR also cleans up the openssl command that we're using for cert generation for added clarity.
=> Implement card cert expiries

apps/admin/frontend/src/components/ballot_mode_toggle.tsx, apps/admin/frontend/src/components/ballot_type_toggle.tsx, apps/admin/frontend/src/screens/ballot_list_screen.tsx, apps/admin/frontend/src/screens/ballot_screen.tsx, apps/admin/frontend/src/screens/definition_contests_screen.tsx, apps/admin/frontend/src/screens/manual_data_import_index_screen.tsx, apps/mark/frontend/src/app_cardless_voting.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/components/settings_text_size.tsx, apps/mark/frontend/src/pages/admin_screen.tsx, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, libs/types/src/ui_theme.ts, libs/ui/src/button.tsx, libs/ui/src/index.ts, libs/ui/src/segmented_button.stories.tsx, libs/ui/src/segmented_button.test.tsx, libs/ui/src/segmented_button.tsx, libs/ui/src/themes/make_theme.ts
Related to: https://github.com/votingworks/vxsuite/issues/3185
Deprecating the existing `SegmentedButton` component and adding a new one that satisfies VVSG2.0 requirements WRT [size](https://docs.google.com/document/d/1A5UX8Z0v12Vvf_jVOUmrOEvUNah2Xxmtltll6ZJW6Ps/edit#bookmark=id.4wj2pvb6lism), [contrast](https://docs.google.com/document/d/1A5UX8Z0v12Vvf_jVOUmrOEvUNah2Xxmtltll6ZJW6Ps/edit#bookmark=id.9enr31j2ams1) and [touch area size and separation](https://docs.google.com/document/d/1A5UX8Z0v12Vvf_jVOUmrOEvUNah2Xxmtltll6ZJW6Ps/edit#bookmark=id.istc3x4un6r)
Technically no longer a "segmented button", since we needed to add the touch area separation, but kept the naming anyway, since folks might be used to looking for that component for certain use cases.
Only replacing the uses in the …
=> [libs/ui] Add VVSG2-compliant SegmentedButton component

libs/ui/src/__snapshots__/button_bar.test.tsx.snap, libs/ui/src/button_bar.stories.tsx, libs/ui/src/button_bar.tsx, libs/ui/src/themes/make_theme.ts
Related to: https://github.com/votingworks/vxsuite/issues/3185
Updating the `ButtonBar` component to satisfy VVSG 2.0 requirements WRT [size](https://docs.google.com/document/d/1A5UX8Z0v12Vvf_jVOUmrOEvUNah2Xxmtltll6ZJW6Ps/edit#bookmark=id.4wj2pvb6lism), [contrast](https://docs.google.com/document/d/1A5UX8Z0v12Vvf_jVOUmrOEvUNah2Xxmtltll6ZJW6Ps/edit#bookmark=id.9enr31j2ams1) and [touch area size and separation](https://docs.google.com/document/d/1A5UX8Z0v12Vvf_jVOUmrOEvUNah2Xxmtltll6ZJW6Ps/edit#bookmark=id.istc3x4un6r)
No changes to the child element ordering, but did replace the `<nav>` container element with a `<div>` since that better describes its role and the `ButtonBar` is currently only used in the `Modal`
https://user-images.githubusercontent.com/264902/230469515-de9f7490-3cf1-4fb7-9 …
=> [libs/ui] Apply VVSG2 themes to ButtonBar component

libs/ui/src/__snapshots__/modal.test.tsx.snap, libs/ui/src/modal.stories.tsx, libs/ui/src/modal.tsx
Related to: https://github.com/votingworks/vxsuite/issues/3185
Minor styling updates to the `Modal` component to use the VVSG-compliant color themes.
- Match modal background to background color for the active theme.
- Thicken border for a bit more contrast between modal content and the translucent overlay behind it.
- Reduced padding to increase usable screen real estate, especially at larger text sizes
- Added storybook.js entry for dev/demos
- Updated affected jest snapshots
=> [libs/ui] Apply VVSG themes to Modal component

libs/custom-scanner/.gitignore, libs/custom-scanner/package.json, libs/custom-scanner/src/cli/demo/index.ts, libs/custom-scanner/src/utils/status_watcher.test.ts, libs/custom-scanner/src/utils/status_watcher.ts, pnpm-lock.yaml
Adds the ability to go into autoscan mode for load testing in the custom scanner demo program, this will continually watch for paper scan it and eject it without interpretation and keep track of the number of ballots counted. 
cc @benadida this should unblock load testing for you if you run the bin/demo program from libs/custom-scanner here
=> add autoscan functionality to custom scanner demo program

apps/central-scan/frontend/src/app.test.tsx, apps/mark/frontend/src/app.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, libs/test-utils/package.json, libs/test-utils/src/console.test.ts, libs/test-utils/src/console.ts, libs/test-utils/src/index.ts, libs/ui/src/error_boundary.test.tsx, pnpm-lock.yaml
Some of our tests, especially when testing `react-query` error handling, log to `console.log` or `console.error` in a way that pollutes the test output. This helper makes it easy to avoid that.
=> feat(test-utils): add `suppressingConsoleOutput` helper

libs/custom-scanner/src/cli/demo/index.ts, libs/custom-scanner/src/parameters.ts
Adds ultrasonic options to the custom scanner demo program and properly feeds through the ultrasonic parameter on scanning, this will disable ultrasonic for all scanning by default. 
Ran demo program with various options, verified with @mattroe on his ultrasonic that double sheet detection was happening when turning it on and not happening by default.
=> Disable double sheet detection and add ultrasonic settings to custom scanner demo program 

apps/central-scan/backend/package.json, apps/central-scan/backend/src/workers/interpret_nh.ts, apps/central-scan/backend/tsconfig.build.json, apps/central-scan/backend/tsconfig.json, apps/scan/backend/src/interpret.ts, libs/ballot-interpreter-nh-next/package.json, libs/ballot-interpreter-nh-next/ts/src/adapter.test.ts, libs/ballot-interpreter-nh-next/ts/src/adapter.ts, libs/ballot-interpreter-nh-next/ts/src/index.ts, libs/ballot-interpreter-nh-next/tsconfig.build.json, libs/ballot-interpreter-nh-next/tsconfig.json, pnpm-lock.yaml
This moves the adapter layer from `apps/scan` to `ballot-interpreter-nh-next` itself so `apps/central-scan` can use it, then replaces the `interpret` call from `ballot-interpreter-nh` with the new compatible one from `ballot-interpreter-nh-next`.
This doesn't remove the dependency on `ballot-interpreter-nh` because it wasn't clear that it was safe to do so since it's still used in `store.ts`, though the code that uses it is slated to be removed and may itself be unused.
https://user-images.githubusercontent.com/1938/230976578-fa2498e6-8964-47cb-95dd-51586aa9f744.mov
=> feat(cental-scan): use NH-next interpreter

apps/central-scan/backend/package.json, apps/central-scan/backend/src/auth.test.ts, apps/central-scan/backend/src/central_scanner_app.test.ts, apps/central-scan/backend/src/central_scanner_app.ts, apps/central-scan/backend/src/end_to_end.test.ts, apps/central-scan/backend/src/end_to_end_hmpb.test.ts, apps/central-scan/backend/src/server.ts, apps/central-scan/frontend/src/api.ts, apps/central-scan/frontend/src/app_root.tsx, apps/central-scan/frontend/src/components/delete_batch_modal.test.tsx, apps/central-scan/frontend/src/components/delete_batch_modal.tsx, apps/central-scan/frontend/src/screens/dashboard_screen.test.tsx, apps/central-scan/frontend/src/screens/dashboard_screen.tsx, apps/central-scan/frontend/test/api.tsx, libs/auth/src/test_utils.ts, pnpm-lock.yaml
I wanted to try out transitioning an API endpoint to use Grout and this seemed like a good one to illustrate both the actual Grout usage and how using `react-query` with a mutation can simplify our client code.
n/a
New automated tests, light manual testing.
=> refactor(central-scan): extract "Delete Batch" modal

apps/scan/backend/README.md, apps/scan/backend/src/app.ts, apps/scan/backend/src/env.d.ts, apps/scan/backend/src/globals.ts, apps/scan/backend/src/interpret.test.ts, apps/scan/backend/src/interpret.ts, apps/scan/backend/src/vx_interpreter.test.ts, libs/ballot-interpreter-nh/src/interpret/index.ts
It's shown to be reliable and fast, and it's too easy to forget the `USE_NH_NEXT` environment variable.
n/a
Automated.
=> feat(scan): always use `nh-next` interpreter

apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/components/__snapshots__/election_info.test.tsx.snap, apps/mark/frontend/src/components/__snapshots__/yes_no_contest.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/cast_ballot_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/not_found_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/start_page.test.tsx.snap, libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap, libs/ui/src/__snapshots__/loading.test.tsx.snap, libs/ui/src/__snapshots__/prose.test.tsx.snap, libs/ui/src/__snapshots__/setup_card_reader_page.test.tsx.snap, libs/ui/src/prose.tsx
_Note: Relevant change is in e243ea1ff6be824928ad949d8b1d0d1064543d56 -- the 2nd commit is just test snapshot updates_
Missed this edge case in https://github.com/votingworks/vxsuite/pull/3252 - the `Prose` component was already overriding font sizes for heading components, but not explicitly doing so for paragraph (`p`) elements.
Adding an override for `p` now to preserve old styling when using the legacy theme.
- Updated changed snapshots
- ~[ ] I have added JSDoc comments to any newly introduced exports~
=> [libs/ui] Let <Prose> override font size for <P> in legacy mode

libs/ui/src/__snapshots__/election_info_bar.test.tsx.snap, libs/ui/src/typography.tsx
Similar to https://github.com/votingworks/vxsuite/pull/3259, the old `<Prose>` component is intended to override font sizes for child elements, but since the new `<Caption>` component sets an explicit `rem`-based font-size, that slipped through the cracks in previous PRs.
This conditionally sets the `<Caption>` size to `0.75em` or `0.75rem`, for legacy and VVSG-compliant themes respectively.
- ~[ ] I have added JSDoc comments to any newly introduced exports~
=> [libs/ui] Update <Caption> to work with <Prose> in legacy mode

frontends/precinct-scanner/src/app_root.tsx, frontends/precinct-scanner/src/app_unhappy_paths.test.tsx, frontends/precinct-scanner/src/screens/scan_error_screen.test.tsx, frontends/precinct-scanner/src/screens/scan_error_screen.tsx, services/scan/Makefile, services/scan/src/precinct_scanner_app.test.ts, services/scan/src/precinct_scanner_app.ts, services/scan/src/precinct_scanner_state_machine.ts
#2844 
~- [ ] I have added JSDoc comments to any newly introduced exports~
=> Lead poll worker through unplug/replug in case of unrecoverable error

apps/scan/frontend/src/screens/poll_worker_screen.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.tsx, libs/@types/kiosk-browser/kiosk-browser.d.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/src/log_documentation.test.ts, libs/logging/src/log_event_ids.ts, libs/test-utils/src/fake_kiosk.ts, libs/ui/src/index.ts, libs/ui/src/power_down_button.test.tsx, libs/ui/src/power_down_button.tsx, libs/ui/src/system_administrator_screen_contents.tsx
https://github.com/votingworks/vxsuite/issues/3178
https://user-images.githubusercontent.com/14897017/231341026-c8d4e465-3eef-4ff9-a031-aec1600be599.mov
Manually tested through both poll worker and sys admin screens, will require locked down image testing to some degree.
=> add power down button to vxscan

libs/backend/src/ballot_package/ballot_package_io.test.ts, libs/backend/src/ballot_package/ballot_package_io.ts
https://github.com/votingworks/vxsuite/issues/3236
When loading ballot packages from a USB, the ballot package IO library will load the newest file in the `ballot-packages` directory. If the newest file is a hidden `._foo.zip` file [left by OS X](https://apple.stackexchange.com/questions/14980/why-are-dot-underscore-files-created-and-how-can-i-avoid-them) the ballot package library will try and fail to parse it as a zip.
This PR makes it so we ignore `._`-prefixed files when reading `ballot-packages`. There's an argument to be made to ignore all hidden files prefixed by `.`, but since we also check for the `.zip` suffix, I don't know of any other cases where an OS would accidentally make `.foo.zip` files.
Old
https://user-images.githubusercontent.com/1060688/230693060-59ed6677-4b04-439e-8e …
=> ignore hidden files with "." prefix in ballot package dir

apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_tally_report_paths.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/insert_ballot_screen.tsx
_Code change in 1st commit, test updates in 2nd_
Related to: https://github.com/votingworks/vxsuite/issues/3185
- Updating copy on the "Insert Ballot" screen to reflect new ballot feed tray location on the VxScanMax.
- Also removing the arrow in the animation - it was decided it would be confusing if it points upward, so dropping altogether.
- Manual verification
- Updated tests that expect the old wording
=> [VxScan] Update 'Insert Ballot' screen copy for VxScanMax

docs/development/best_practices/rust.md
The old one seems to be out of date, but is the first thing that comes up when googling "rust style guide".
=> docs: update link to Rust style guide

Cargo.lock, apps/central-scan/backend/src/cvrs/export.ts, apps/scan/backend/src/cvrs/export.ts, libs/backend/src/scan/cast_vote_records/export.ts, libs/ballot-interpreter-nh-next/Cargo.toml, libs/ballot-interpreter-nh-next/README.md, libs/ballot-interpreter-nh-next/package.json, libs/ballot-interpreter-nh-next/src/election.rs, libs/ballot-interpreter-nh-next/src/geometry.rs, libs/ballot-interpreter-nh-next/src/interpret.rs, libs/ballot-interpreter-nh-next/src/layout.rs, libs/ballot-interpreter-nh-next/src/lib.rs, libs/ballot-interpreter-nh-next/src/timing_marks.rs, libs/ballot-interpreter-nh-next/ts/src/__snapshots__/adapter.test.ts.snap, libs/ballot-interpreter-nh-next/ts/src/__snapshots__/interpret.test.ts.snap, libs/ballot-interpreter-nh-next/ts/src/adapter.test.ts, libs/ballot-interpreter-nh-next/ts/src/adapter.ts, libs/ballot-interpreter-nh-next/ts/src/cli.ts, libs/ballot-interpreter-nh-next/ts/src/interpret.test.ts, libs/ballot-interpreter-nh-next/ts/src/interpret.ts, libs/ballot-interpreter-nh-next/ts/src/rust-addon.d.ts, libs/ballot-interpreter-nh-next/ts/src/types.ts, pnpm-lock.yaml
Task: #3143
In order to get write-in adjudication working with the nh-next interpreter, we modify the interpreter to return normalized ballot images and computed ballot layout information.
N/A
- Manual tests
- Added some basic automated tests (mainly testing plumbing, plus a few invariants on the computed layouts)
- @eventualbuddha did performance testing
=> feat(nh-next): Return normalized images and computed ballot layouts

.circleci/config.yml
To simplify the dev experience, we've decided to revert to a user-local install of Rust on our systems. That PR is here: https://github.com/votingworks/vxsuite-build-system/pull/26
This also updates our CircleCI config to use version 2.0.3 of our Docker images.
Trigger a CircleCI run. Test suite will pass.
=> updated to 2.0.3 circle image to use local rust install and config

apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/components/layout.tsx, apps/scan/frontend/src/components/replace_ballot_bag_screen.tsx, apps/scan/frontend/src/screens/card_error_screen.tsx, apps/scan/frontend/src/screens/insert_usb_screen.tsx, apps/scan/frontend/src/screens/invalid_card_screen.tsx, apps/scan/frontend/src/screens/loading_configuration_screen.tsx, apps/scan/frontend/src/screens/scan_busy_screen.tsx, apps/scan/frontend/src/screens/scan_error_screen.tsx, apps/scan/frontend/src/screens/scan_jam_screen.tsx, apps/scan/frontend/src/screens/scan_processing_screen.tsx, apps/scan/frontend/src/screens/scan_returned_ballot_screen.tsx, apps/scan/frontend/src/screens/scan_warning_screen.tsx, apps/scan/frontend/src/screens/setup_scanner_screen.tsx, apps/scan/frontend/src/screens/unconfigured_election_screen_wrapper.tsx, apps/scan/frontend/src/screens/unconfigured_precinct_screen.tsx
_Closes https://github.com/votingworks/vxsuite/issues/3126_
Per [discussion in slack](https://votingworks.slack.com/archives/CEL6D3GAD/p1681330267773369), we're going to try out persisting the election info bar on all screens in VxScan, since:
- it's potentially less attention to always have it visible than to have it pop in and out and
- we have a lot more vertical real estate to play with now in portrait mode.
As before, the info bar is still only rendered when there's a configured election.
=> [VxScan] Persist ElectionInfoBar across all screens

apps/scan/frontend/src/components/calibrate_scanner_modal.tsx, apps/scan/frontend/src/components/export_backup_modal.tsx, apps/scan/frontend/src/components/export_results_modal.tsx, apps/scan/frontend/src/components/live_check_modal.tsx, apps/scan/frontend/src/components/set_mark_thresholds_modal.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, apps/scan/frontend/src/screens/scan_warning_screen.tsx, libs/ui/src/modal.stories.tsx, libs/ui/src/modal.test.tsx, libs/ui/src/modal.tsx
_Closes https://github.com/votingworks/vxsuite/issues/3144_
Most instance of the `Modal` content render an `H1`-sized title - this looks a little crowded with the new VVSG themes, even at the default medium text size setting. Swapping these out for a `H2` title instead (using `as="h1"` to maintain proper a11y heading hierarchy.
- Adding an optional `title` prop to the `Modal` component, so we can standardize title styling across modals.
- Moving the custom title elements in VxScan into the `title` prop. Will migrate other apps as needed, when we switch them to the new themes.
- Also reduced the transparency of the background overlay a bit to improve the separation of the modal from the page content - noticed I was having a hard time focusing on the modal on noisy pages like the election …
=> [VxScan] Tame modal headings to fit in default size mode

apps/scan/frontend/src/screens/election_manager_screen.tsx, libs/ui/src/change_precinct_button.tsx
At the default VVSG size setting, the Election Manager Screen is getting a little crowded and in some states, content overflows and gets rendered below the fold.
This page could us a re-design, but in the meantime, taming a few elements on the screen so things fit at least at the default "medium" text size:
- Render an `H2`-sized page title instead of `H1` (with `as="h1"` to preserve a11y heading hierarchy)
- Stop rendering the `ChangePrecinctButton` as `<Select large>` so we make a bit of room - it's a little too large now with the VVSG styling.
- Change the disabled button explanation text at the bottom from `<P>` to `<Caption>`
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, …
=> [VxScan] Reduce crowding on ElectionManagerScreen

apps/scan/backend/schema.sql, apps/scan/backend/src/app.ts, apps/scan/backend/src/scanners/custom/app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/scanners/plustek/state_machine.ts, apps/scan/backend/src/server.test.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/src/types.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, apps/scan/frontend/src/screens/scan_double_sheet_screen.test.tsx, apps/scan/frontend/src/screens/scan_double_sheet_screen.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/custom-scanner/src/mocks/simple_scanner.ts
Makes double sheet detection enabled by default but with the option to disable. When there is a double sheet jam shows a specific UI relevant to multiple sheets. 
https://github.com/votingworks/vxsuite/issues/3235
https://user-images.githubusercontent.com/14897017/231652221-0d5aeb23-07cc-4c7f-8d65-fffe78b3f3b3.mov
All scans in above video are two sheets layered on top of one another
Manually tested various moments of double sheet feeding, manually tested that killing and restarting app keeps the disable state
=> Enable double sheet detection with the option to disable

apps/admin/frontend/src/screens/write_ins_transcription_screen.test.tsx, apps/admin/frontend/src/screens/write_ins_transcription_screen.tsx, libs/ballot-interpreter-nh-next/src/layout.rs, libs/ballot-interpreter-nh-next/ts/src/__snapshots__/adapter.test.ts.snap, libs/ballot-interpreter-nh-next/ts/src/__snapshots__/interpret.test.ts.snap
An assortment of small improvements to write-in cropping for the adjudication transcription flow.
https://user-images.githubusercontent.com/530106/231900491-d11224c8-a19f-445c-81af-8886868af4a1.mov
- Manual tests
=> fix(admin): Write-in image cropping tweaks

libs/ui/src/__snapshots__/modal.test.tsx.snap, libs/ui/src/modal.tsx
Fixes a small bug introduced in https://github.com/votingworks/vxsuite/pull/3230.
Before
After
- Manual test
=> fix(ui): Don't show border for fullscreen modals

apps/scan/frontend/src/screens/scan_double_sheet_screen.tsx
Probably got mixed up in a rebase when #3279 was merged.
=> fix(scan): Remove outdated infoBar prop from double sheet screen

apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/components/layout.tsx
@carolinemodic just uncovered a confusing sequence in VxScan. When VxScan is unconfigured, inserting an invalid card doesn't surface the invalid card screen; it surfaces a variation of the screen that was already being displayed.
This PR ensures that the invalid card screen is displayed when VxScan is unconfigured. It also updates the ballot count to only be displayed once VxScan has been configured.
https://user-images.githubusercontent.com/12616928/232066809-85833909-f9be-4413-87e5-fef05e69ad15.mov
https://user-images.githubusercontent.com/12616928/232067833-d395fe7a-3a0f-4637-b759-b858975746bb.mov
=> Ensure invalid card screen is displayed when VxScan is unconfigured (bug fix)

apps/admin/frontend/src/components/election_manager.tsx, apps/central-scan/frontend/src/app_root.tsx, apps/mark/frontend/src/app_root.tsx, apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/screens/poll_worker_screen.tsx, libs/ui/src/unlock_machine_screen.tsx
Issue link: https://github.com/votingworks/vxsuite/issues/3275
Due to a number of reasons, including moving auth to the backend, using a synchronous react-query method, and PIN checking becoming a slower operation with Java Cards, the PIN entry UX has become a bit funky. After you submit your PIN, the PIN immediately clears, but checking doesn't finish until after a noticeable delay. You can still press the keypad in the interim.
This PR makes the simplest possible change to improve the UX, disabling the keypad while PIN-checking is in progress and not clearing the PIN until PIN-checking is complete.
Still plenty of room for improvement (e.g. you can sometimes catch a flicker as the PIN clears, before we proceed to the next screen) but just wanted to get something simple in place before …
=> Improve PIN entry UX

apps/scan/backend/src/scanners/custom/app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts
Adds a short delay when we see a jam when scanning before deciding which jam screen to go to, we are adding this because with double sheets for some reason it often quickly gives a general jam status before showing the double sheet specific information
=> add delay before routing jam on scanning

apps/admin/backend/src/app.test.ts
It was loudly logging an error.
Automated.
=> test(admin): quiet `app.test.ts` a bit

libs/backend/jest.config.js, libs/backend/src/scan/cast_vote_records/page_layouts.test.ts, libs/backend/src/scan/cast_vote_records/page_layouts.ts
For some reason we still generate VX-style ballots when building ballot packages for grid-based elections, which means that a layout is generated too. That layout is unlikely to put contests on the same pages as the real layout, which can result in contests appearing on the wrong pages. This affects write-in adjudication because a write-in may be ignored if the two layouts disagree about which page it is on. This commit fixes the issue by always using the generated layouts for grid-based elections, ignoring the vestigial VX-style ballots generated for such elections.
[Slack context](https://votingworks.slack.com/archives/C04U11L9SCR/p1681843934357579)
In the table below, the write-in votes for the "Planning Board Members" contest are ignored because they are mistakenly thought to be on …
=> fix(scan): use correct layout for grid-based elections

apps/admin/backend/src/app.ts, apps/admin/backend/src/store.test.ts, apps/admin/backend/src/store.ts
We appear to be crashing due to memory limitations when the number of CVRs gets around 3,000 when the CVRs have lots of write-ins. This seems to be due to when we are returning CVRs to the frontend and parsing them all. In this patch, I stream CVRs out of the store rather than returning them all at once, so the parsing is happening one at a time.
=> use generator for CVRs retrieved from db

libs/ui/src/themes/render_with_themes.test.tsx
This test case runs an `expect().toThrow()`, which produces noisy console error logs - using the new log suppression test util to swallow those.
- Ran test with and without suppression to verify the change
=> [libs/ui] Suppress console logs for expected test exception

apps/admin/integration-testing/cypress/support/auth.ts, apps/central-scan/integration-testing/cypress/e2e/configuration.cy.ts, apps/mark/integration-testing/cypress/support/e2e.js, libs/auth/package.json, libs/auth/scripts/generate_dev_keys_and_certs.ts, libs/auth/scripts/mock_card.ts, libs/auth/scripts/program_system_administrator_java_card.ts, libs/auth/src/certs.test.ts, libs/auth/src/certs.ts, libs/auth/src/constants.ts, libs/auth/src/index.ts, libs/auth/src/java_card.test.ts, libs/auth/src/java_card.ts, libs/auth/src/memory_card.ts, libs/auth/src/mock_file_card.test.ts, libs/auth/src/openssl.test.ts, libs/auth/src/openssl.ts, libs/auth/src/types.ts, libs/auth/test/utils.ts, pnpm-lock.yaml
Rather than implementing our own `tmp`-like functionality, let's just use the `tmp` package. Advantages:
- we don't have to hardcode a particular place to put files
- we don't have to implement logic to avoid writing to an existing file
- we can use the existing `tmp` cleanup facility
All of the above simplifies the tests somewhat as well.
n/a
Automated.
=> refactor(auth): use `tmp` directly

apps/admin/frontend/src/app.tsx, apps/central-scan/frontend/src/app.tsx, apps/mark/frontend/src/app.tsx, apps/scan/frontend/src/scan_app_base.tsx, libs/ui/.storybook/preview.tsx, libs/ui/src/app_base.test.tsx, libs/ui/src/app_base.tsx, libs/ui/src/index.ts, libs/ui/src/theme_manager_context.tsx, libs/ui/src/themes/render_with_themes.tsx, libs/ui/src/typography.test.tsx
Adding a theme management API (`setColorMode`, `setSizeMode`, `resetThemes`) which will initially be used by the voter-facing display settings component.
- Updating  the `colorMode`, `sizeMode` props on `AppBase` to a more appropriately named `default*Mode` - these will now represent the initial/default state of the UI that we return to when `resetThemes` is used.
- Also updating the storybook bootstrap code to use the theme manager API when switching between modes.
- Added test case for the `AppBase` implementation of the `ThemeManagerContext`
- ~[ ] I have added a screenshot …
=> [libs/ui] Add a theme management API context to AppBase

libs/ui/.storybook/main.ts, libs/ui/src/icons.tsx, libs/ui/src/index.ts, libs/ui/src/radio_group/index.tsx, libs/ui/src/radio_group/radio.tsx, libs/ui/src/radio_group/radio_button.tsx, libs/ui/src/radio_group/radio_group.stories.tsx, libs/ui/src/radio_group/radio_group.test.tsx, libs/ui/src/radio_group/types.ts
Adding a `RadioGroup` component that uses native `<fieldset>` and `<input type="radio">` semantic elements, styled with our VVSG themes.
Initial usage will be in the voter-facing display settings screen in upcoming PRs.
- Broken out into subcomponent files within the `src/radio_group` folder:
- `index.tsx`: Glue component and outer container styling
- `radio_button.tsx`: Single radio option component with state-specific styling for option container and label
- `radio.tsx`: Wrapper around browser-native radio input with event handling and VxSuite-specific styling.
https://user-images.githubusercontent.com/264902/233213540-7f8d68cc-205b-4304-ae75-97d476a87083.mov
- New unit tests for RadioGroup - functionality and a11y
- Visual testing via storybook …
=> [libs/ui] Add RadioGroup component

apps/mark/backend/src/util/workspace.ts, libs/db/src/client.ts
The workspace directory needs to be created if it doesn't exist. Copied this fix from apps/admin.
N/A
Couldn't run the app before, now I can!
=> fix(mark): Ensure workspace dir exists

apps/scan/backend/test/helpers/shared_helpers.ts
This PR bumps a wait time to hopefully decrease flakiness we've been seeing with VxScan backend tests. My rudimentary testing (i.e. retrying in CircleCI a few times) suggests that this will help!
=> Bump wait time to hopefully decrease flakiness

libs/ballot-interpreter-nh-next/src/interpret.rs, libs/ballot-interpreter-nh-next/src/js/args.rs, libs/ballot-interpreter-nh-next/src/js/image_data.rs, libs/ballot-interpreter-nh-next/src/js/mod.rs, libs/ballot-interpreter-nh-next/src/layout.rs, libs/ballot-interpreter-nh-next/src/lib.rs, libs/ballot-interpreter-nh-next/src/timing_marks.rs, libs/ballot-interpreter-nh-next/ts/src/__snapshots__/interpret.test.ts.snap, libs/ballot-interpreter-nh-next/ts/src/debug.test.ts, libs/ballot-interpreter-nh-next/ts/src/interpret.test.ts, libs/ballot-interpreter-nh-next/ts/src/interpret.ts, libs/ballot-interpreter-nh-next/ts/src/rust-addon.d.ts
Previously we required passing paths to image files to load. Now we can pass `ImageData` objects directly. This has the potential to be faster, though in my basic testing it was only faster some of the time. I'm hoping that eliminating the encode+write of the images does make a difference, though.
n/a
Automated.
=> feat(scan-nh): allow interpreting `ImageData`

libs/grout/src/serialization.test.ts, libs/grout/src/serialization.ts
In general we won't use this because we do most data processing on the backend. However, we still have some use cases for sending binary data back and forth. This makes doing so easier.
n/a
Automated.
=> feat(grout): add `Buffer` support

libs/ui/src/display_settings/color_settings.test.tsx, libs/ui/src/display_settings/color_settings.tsx, libs/ui/src/display_settings/settings_pane.tsx, libs/ui/src/display_settings/size_settings.test.tsx, libs/ui/src/display_settings/size_settings.tsx, libs/ui/src/display_settings/types.ts
Adding components for the `ColorSettings` and `SizeSettings` panes within the upcoming display settings screen component.
Both render the display options as `RadioGroup` components and use the theme manager context API to modify the global theme.
https://user-images.githubusercontent.com/264902/234090389-2f7ebfd7-2be3-4291-80f1-ae273746ccbc.mov
- Added unit tests to verify rendered options and theme-change functionality
=> [libs/ui] Add ColorSettings and SizeSettings components

libs/ui/src/display_settings/tab_bar.test.tsx, libs/ui/src/display_settings/tab_bar.tsx, libs/ui/src/icons.tsx
Adding the `TabBar` subcomponent for the upcoming display settings screen.
Renders tabs as detached `Button`s, since VVSG 2.0 requires a minimum amount of separation between touch targets.
https://user-images.githubusercontent.com/264902/234335868-6ce7667d-b3ee-45fb-8c5b-54f311188b33.mov
- Unit tests to verify a11y and event handling
- Visual testing in context
=> [libs/ui] Add TabBar component for the display settings screen

libs/cvr-fixture-generator/README.md, libs/cvr-fixture-generator/src/cli/generate/main.test.ts, libs/cvr-fixture-generator/src/cli/generate/main.ts, libs/cvr-fixture-generator/src/generate_cvrs.ts
A couple quick additions to CVR fixture generation to more easily make CVR fixtures for performance testing:
1. **Ballot Prefix ID** - useful when wanting to create multiple CVRs for the same election without ID collision
2. **BMD Ballots** - useful when wanting to test without images. We can generate CVRs without images by default, if we don't use the `--includeBallotImages` flag, but the CVRs still have write-ins so they fail VxAdmin validation. Rather than tweaking validation, I wanted to be able to produce BMD ballots. They aren't procedurally valid - they contain overvotes which are not possible on a BMD - but they are formally valid.
=> CVR Fixture Generation Tweaks

apps/mark/backend/src/app.auth.test.ts, apps/mark/backend/src/app.test.ts, apps/mark/backend/src/app.ts, apps/mark/backend/test/app_helpers.ts, apps/mark/frontend/src/api.ts, apps/mark/frontend/src/app.tsx, apps/mark/frontend/src/app_cardless_voting.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/app_polls_flows.test.tsx, apps/mark/frontend/src/app_quit_on_idle.test.tsx, apps/mark/frontend/src/app_root.tsx, apps/mark/frontend/src/app_voter_settings_landscape.test.tsx, apps/mark/frontend/src/components/session_time_limit_tracker.tsx, apps/mark/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/test/helpers/mock_api_client.tsx
Now that VxMark persists the election definition on the backend (thanks Kevin!), we can pull election hash from the backend store for auth calls, instead of having the frontend provide it. This simplifies the code quite a bit and makes VxMark better match the other machines.
Tackling this as a precursor to VxMark jurisdiction state management.
=> Update VxMark backend to pull election hash from backend store

apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/components/__snapshots__/yes_no_contest.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/cast_ballot_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/not_found_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/start_page.test.tsx.snap, libs/ui/src/display_settings/color_settings.tsx, libs/ui/src/display_settings/display_settings.stories.tsx, libs/ui/src/display_settings/display_settings.test.tsx, libs/ui/src/display_settings/index.tsx, libs/ui/src/index.ts
_1st commit has relevant changes - 2nd commit is just unrelated test snapshot updates_
Adding the `DisplaySettings` component for modifying the active UI theme. Intended to be rendered as a fullscreen component within VxSuite apps.
Ties together the previously added `ColorSettings` and `SizeSettings` subcomponents and includes a "Reset" button to return the UI to the default theme specified by the app in `AppBase`
Also sneaking in a quick fix to the color settings ordering (meant to go from darkest to lightest).
https://user-images.githubusercontent.com/264902/234351430-657ce2ef-8fdb-488b-97b0-c86763d9f6d2.mov
- Unit tests for proper rendering and event handling
- Visual testing for ELO screen fit
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) …
=> [libs/ui] Add DisplaySettings component

apps/mark/backend/schema.sql, apps/mark/backend/src/app.auth.test.ts, apps/mark/backend/src/app.test.ts, apps/mark/backend/src/app.ts, apps/mark/backend/src/store.test.ts, apps/mark/backend/src/store.ts, apps/mark/backend/test/app_helpers.ts, apps/mark/integration-testing/cypress/support/e2e.js
Issue link: https://github.com/votingworks/vxsuite/issues/2912
The VxMark equivalent of https://github.com/votingworks/vxsuite/pull/3348 for VxCentralScan. Largely copying from that PR's description:
This PR replaces the hardcoded dev jurisdiction in VxMark with proper jurisdiction state management. When the machine is configured, the jurisdiction will be set to the jurisdiction on the election manager card used to auth onto the machine. And when the machine is unconfigured, the jurisdiction will be cleared.
When a jurisdiction is set, the machine will only accept cards from that jurisdiction. And when no jurisdiction is set, the machine will accept cards from all jurisdictions. This logic already exists and lives in the auth lib.
=> Add jurisdiction state management to VxMark

libs/basics/src/result.test.ts, libs/basics/src/result.ts, libs/custom-scanner/src/custom_a4_scanner.ts, libs/custom-scanner/src/protocol.ts, libs/message-coder/src/base_coder.ts, libs/message-coder/src/fixed_string.ts, libs/message-coder/src/literal_coder.ts, libs/message-coder/src/message_coder.ts, libs/message-coder/src/types.ts, libs/message-coder/src/uint16_coder.ts, libs/message-coder/src/uint24_coder.ts, libs/message-coder/src/uint2_coder.ts, libs/message-coder/src/uint32_coder.ts, libs/message-coder/src/uint4_coder.ts, libs/message-coder/src/uint8_coder.ts, libs/message-coder/src/uint_coder.ts, libs/message-coder/src/unbounded_string_coder.ts
_(I recommend reviewing with ["Hide whitespace" enabled](https://github.com/votingworks/vxsuite/pull/3367/files?diff=split&w=1))_
Rust has the [`?` operator](https://doc.rust-lang.org/reference/expressions/operator-expr.html#the-question-mark-operator) to return early from functions if the `Result` operand is `Err`. This is convenient, and the lack of it with our `Result` type means a lot of extra error checks with early returns. This is annoying boilerplate, but it also makes complete code coverage difficult to achieve since you need to write tests that cover what is essentially just propagating an error.
A note about the design of this API: it uses JavaScript exceptions. This is not ideal but is unavoidable since it's the only way to return early from a function without `return`. …
=> feat(basics): add early-return for `Result` functions

frontends/election-manager/src/components/bubble_mark.tsx, frontends/election-manager/src/components/hand_marked_paper_ballot.tsx
- Small bubble alignment fix
- Fix capitalization in instructions
Before (density 2)
After (density 2)
Visual inspection of density 0, density 1, and density 2 ballots
=> m16: HMPB density tweaks

apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/app_contest_ms_either_neither.test.tsx, apps/mark/frontend/src/app_contest_write_in.test.tsx, apps/mark/frontend/src/components/__snapshots__/settings_text_size.test.tsx.snap, apps/mark/frontend/src/components/__snapshots__/yes_no_contest.test.tsx.snap, apps/mark/frontend/src/config/types.ts, apps/mark/frontend/src/pages/__snapshots__/cast_ballot_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/not_found_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/start_page.test.tsx.snap, apps/mark/frontend/src/pages/review_page.tsx, libs/ui/src/button.tsx, libs/ui/src/card.tsx
Using the theme-aware `VoterContestSummary` component from libs/ui on the VxMark review page
- Needed to update the `Button` component to allow its content to grow to fit its container to make sure the summary cards are rendered to fill the available horizontal space.
- Also fixed a small bug in the `Card` components content padding.
- Mostly a refactor - updated some element queries in affected tests
=> [VxAdmin] Use new theme-aware VoterContestSummary cards on ReviewPage

apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/components/__snapshots__/election_info.test.tsx.snap, apps/mark/frontend/src/components/candidate_contest.tsx, apps/mark/frontend/src/components/election_info.tsx, apps/mark/frontend/src/components/ms_either_neither_contest.tsx, apps/mark/frontend/src/pages/__snapshots__/cast_ballot_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark/frontend/src/pages/accessible_controller_diagnostic_screen.tsx, apps/mark/frontend/src/pages/admin_screen.tsx, apps/mark/frontend/src/pages/cast_ballot_page.tsx, apps/mark/frontend/src/pages/contest_page.tsx, apps/mark/frontend/src/pages/diagnostics_screen.test.tsx, apps/mark/frontend/src/pages/diagnostics_screen.tsx, apps/mark/frontend/src/pages/insert_card_screen.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/src/pages/replace_election_screen.tsx, libs/ui/src/icons.tsx, libs/ui/src/typography.tsx
Replacing last remaining bits of typography in VxAdmin with the newer theme-aware components from `libs/ui`:
- `<Text>` -> `<P>`
- `<Text small>` -> `<Caption>` (wrapped in a `<P>` when intended as a standalone paragraph).
- `<Text as="span">` -> `<Font>` (or removed entirely in a couple cases, where it's unnecessary).
- `<Text warning|error|etc>` -> `<P color="...">` or `<Font color="...">` if rendered as span within surrounding text.
- Additionally, adding appropriate icons whenever we use color, as recommended by VVSG (since not all contrast modes support colors).
- `<Text bold|light>` -> `<P weight="...">` or `<Font weight="...">`
- `<Text italic>` -> `<P>` or `<P weight="bold">` in rare cases where we actually need the text emphasized - italic text can be tough to parse for some …
=> Vxmark replace text components

libs/auth/scripts/generate_dev_keys_and_certs.ts, libs/auth/src/card.ts, libs/auth/src/cypress.ts, libs/auth/src/dipped_smart_card_auth.test.ts, libs/auth/src/dipped_smart_card_auth.ts, libs/auth/src/inserted_smart_card_auth.test.ts, libs/auth/src/java_card.ts, libs/auth/src/mock_file_card.test.ts, libs/auth/src/mock_file_card.ts, libs/auth/src/openssl.test.ts, libs/auth/src/openssl.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3346
@eventualbuddha recently noticed that card mocking can get thrown off if the `/tmp` directory is cleaned up ([comment](https://github.com/votingworks/vxsuite/pull/3331#discussion_r1173170682)). With the addition of the dev dock, I've now actually seen us hit errors due to the file underlying card mocking not existing:
This PR makes sure that the relevant file always exists.
The PR also makes an unrelated tweak to the MockFileCard's data schema, using an existing field for the number of incorrect PIN attempts instead of creating a new one.
=> Consistently initialize file underlying MockFileCard

frontends/precinct-scanner/jest.config.js, frontends/precinct-scanner/src/app_root.tsx, frontends/precinct-scanner/src/components/replace_ballot_bag_screen.tsx, frontends/precinct-scanner/src/screens/poll_worker_screen.test.tsx, frontends/precinct-scanner/src/screens/poll_worker_screen.tsx
This is a minimal change to allow for replacing the ballot bag at any time from the poll worker screen.
This is a little bit more convoluted than I would have liked, in that the existing replace-ballot-bag-screen was fairly tightly bound, in its behavior, to a situation where the ballot bag *must* be replaced. I made two changes:
- update the ballot bag counter the moment the confirm button is hit, independent of auth status.
- force the replace ballot bag screen to continue to be shown until the poll worker card is removed.
I *think* this logic is better, but this is a slightly bigger change than I would have liked.
=> m16 replace ballot bag any time poll worker wants to

frontends/election-manager/src/screens/tally_screen.tsx
When jurisdictions import CVRs from multiple precinct scanners, having a quick count of how many CVR files have been loaded makes it very easy to know how many you've got left to load. We've seen this in the field. This just adds numbering to the list of CVR files in election-manager.
I'll also PR this into `main` separately.
Before:
After:
Manually tested.
- [ X ] I have added a screenshot and/or video to this PR to demo the change
=> feat(election-manager): number the CVR files.

libs/ballot-interpreter-nh/src/metadata.rs, libs/ballot-interpreter-nh/src/timing_marks.rs
When exploring designing our own ballots from scratch, I ran into some small snags with the interpreter:
- A confusing error message when the corner timing marks couldn't be found
- An expectation that the horizontal spacing between timing marks is equivalent to the vertical spacing
I made attempts to fix both of these in a way that I think is a net improvement, but would like to hear if there's a good reason things were set up that way before.
N/A
Manually tested on the ballots I've been designing, relying on existing tests to prevent regressions.
(Side note: now that we're investing in this interpreter, it might be good to think about beefing up the testing so that it's easy to add new tests or change tests for situations like this)
=> Improve interpreter timing mark detection

apps/admin/frontend/src/screens/tally_screen.tsx
Apply the same patch as in #3426, this time to `main`. Same reasons.
tested manually, looks good.
- [ X ] I have added a screenshot and/or video to this PR to demo the change
=> feat(admin): number the CVR files in the tally screen.

libs/backend/src/scan/cast_vote_records/build_cast_vote_record.test.ts, libs/backend/src/scan/cast_vote_records/build_cast_vote_record.ts, libs/fixtures/data/electionGridLayoutNewHampshireAmherst/cvr-files/standard/cast-vote-record-report.json, libs/fixtures/data/electionMinimalExhaustiveSample/cvr-files/standard/cast-vote-record-report.json
Makes the `Overvotes` count in our CVRs consistent with a) our interpretation of the CDF spec and b) the way we count overvotes when tallying.
=> Change How We Count Overvotes in CDF CVRs

apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/app_contest_write_in.test.tsx, apps/mark/frontend/src/components/candidate_contest.test.tsx, apps/mark/frontend/src/components/candidate_contest.tsx, libs/ui/jest.config.js, libs/ui/src/index.ts, libs/ui/src/touch_text_input.tsx, libs/ui/src/virtual_keyboard.stories.tsx, libs/ui/src/virtual_keyboard.test.tsx, libs/ui/src/virtual_keyboard.tsx
Final piece (I think) of VVSG design updates for VxMark - re-styling the write-in candidate modal:
- Moved `VirtualKeyboard` to libs/ui for easier design iteration
- Meant to move out the rest of the write-in form as well, but didn't fit in the time box - punting for later.
- Did break out the fake input box to `libs/ui/TouchTextInput` - not the best of names, so open to suggestions if you feel inspired.
- Moved contest title to the modal title to de-clutter the UI
- Changed character limit warning to a "characters remaining" countdown to minimise the UI flicker when it used to pop in and out of existence.
- Removed the key row staggering that we had in place before to mimic a real keyboard - causing issues at larger sizes and doesn't feel like we've taken a usability hit without it.
- …
=> [VxMark] VVSG Design Updates for Write-In Modal

libs/usb-mocking/insert.sh
We were `grep`ping for `${DEVICE_BASENAME}p1 vfat`, but because `lsblk` prints it as a table it might not be the case that there's a single space between the `p1` and `vfat`. This commit accounts for that.
Related [Slack thread](https://votingworks.slack.com/archives/CEL6D3GAD/p1683844280388539).
```
debian--11--vg-root   ext4        1.0                  1ea4b907-0a2c-4f85-8f46-d932ec8f3fbd     33.1G    40% /
debian--11--vg-swap_1 swap        1                    db2ddb9e-d9b5-4b5e-8b7e-8142e0b19ddd                  [SWAP]
loop0p1               vfat        FAT32    VIRTUAL-USB A58C-44AE
```
Tested manually.
=> fix(usb-mocking): fix `insert.sh` parsing of `lsblk` output

apps/admin/frontend/jest.config.js, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/app_write_in_flows.test.tsx, apps/admin/frontend/src/screens/manual_data_import_precinct_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_import_precinct_screen.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx, apps/admin/frontend/src/utils/manual_tallies.ts, apps/admin/frontend/src/utils/write_ins.test.ts, apps/admin/frontend/src/utils/write_ins.ts, apps/admin/frontend/test/helpers/api_mock.ts
In order to move manual tally data to the backend, I needed to make this transition PR changing how we treat write-in candidates in manual data.
I added the ability to add write-in candidates to manual tallies in #2649. I recommend watching the video in that PR description for context. The way I implemented it had two main problems:
1. Feature Limitation: Write-in candidates from on-screen adjudication would pre-populate in the manual tally entry screens, but write-in candidates from manual tally entry would not pre-populate in on-screen adjudication. We assumed that the flow would move in that direction, but we know we can't always guarantee it
2. Technical Issue: The way that manual data added write-in candidates were tracked was by having a key value pair in the manual tally. But, …
=> change how we handle write-in candidates in manual tally entry

apps/central-scan/backend/bin/extract-backup, apps/central-scan/backend/schema.sql, apps/central-scan/backend/src/backup.test.ts, apps/central-scan/backend/src/backup.ts, apps/central-scan/backend/src/central_scanner_app.test.ts, apps/central-scan/backend/src/central_scanner_app.ts, apps/central-scan/backend/src/importer.ts, apps/central-scan/backend/src/store.test.ts, apps/central-scan/backend/src/store.ts, apps/scan/backend/bin/extract-backup, apps/scan/backend/schema.sql, apps/scan/backend/src/backup.test.ts, apps/scan/backend/src/backup.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/src/tally-cvrs/export.test.ts, apps/scan/backend/test/helpers/shared_helpers.ts, libs/backend/src/scan/cast_vote_records/export.test.ts, libs/backend/src/scan/cast_vote_records/export.ts, libs/backend/src/scan/interpretation/interpret.ts, libs/backend/src/scan/interpretation/interpret_and_save_files.test.ts, libs/backend/src/scan/interpretation/interpret_and_save_files.ts, libs/backend/src/scan/interpretation/save_images.test.ts, libs/backend/src/scan/interpretation/save_images.ts, libs/ballot-interpreter-nh/ts/src/cli.ts, libs/types/src/election.ts, libs/types/src/interpretation.ts
We previously stored both the "original" (image from the scanner) and "normalized" (scaled/deskewed/rotated/etc) versions of the scanned ballot images. However, we've decided we don't actually need the original image. This consolidates down to just using the normalized image and calling it `imagePath` (`front_image_path` and `back_image_path`) in the database.
```
.
├── ballot-images
│   └── 8d2f7b03-09bf-4bad-be77-4c2ce1e57b15
│       └── 2f5b5e2b-8115-466a-976b-1adf777feb24-front.jpg
├── ballot-layouts
│   └── 8d2f7b03-09bf-4bad-be77-4c2ce1e57b15
│       └── 2f5b5e2b-8115-466a-976b-1adf777feb24-front.layout.json
└── cast-vote-record-report.json
4 directories, 3 files
```
Automated. Manually tested VxScan and VxCentralScan with a NH HMPB election.
=> [scan] consolidate normalized/original ballot images

apps/admin/frontend/package.json, apps/central-scan/backend/src/central_scanner_app.test.ts, apps/central-scan/backend/src/central_scanner_app.ts, apps/central-scan/backend/src/end_to_end.test.ts, apps/central-scan/backend/src/end_to_end_hmpb.test.ts, apps/central-scan/frontend/src/api.ts, apps/central-scan/frontend/src/api/config.ts, apps/central-scan/frontend/src/app.test.tsx, apps/central-scan/frontend/src/app_root.tsx, libs/api/src/services/scan/index.test.ts, libs/api/src/services/scan/index.ts, libs/backend/src/exporter.test.ts, libs/backend/src/exporter.ts, pnpm-lock.yaml
Chips away more at `@votingworks/api`, replacing it with Grout APIs.
n/a
Automated. Manually tested toggling test mode in VxCentralScan.
=> Minor API Cleanup

libs/message-coder/src/uint16_coder.test.ts, libs/message-coder/src/uint16_coder.ts, libs/message-coder/src/uint32_coder.test.ts, libs/message-coder/src/uint32_coder.ts
Supports big-endian `Uint16` and `Uint32` in `message-coder`.
* Updated automated tests for big endian case
- [ x] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
=> support big-endian in uint16 and uint32 coders

frontends/bmd/src/app_root.tsx, frontends/bmd/src/config/types.ts, frontends/bmd/src/pages/__snapshots__/cast_ballot_page.test.tsx.snap, frontends/bmd/src/pages/cast_ballot_page.tsx, frontends/bmd/src/utils/ScreenReader/kiosk_text_to_speech.test.ts, frontends/bmd/src/utils/ScreenReader/kiosk_text_to_speech.ts, libs/@types/kiosk-browser/kiosk-browser.d.ts
Make use of the new kiosk-browser API that caches spoken utterances, to warm the text-to-speech cache.
Tested manually
=> pre-warm cache of tts

frontends/precinct-scanner/jest.config.js, frontends/precinct-scanner/src/app.test.tsx, frontends/precinct-scanner/src/app_tally_report_paths.test.tsx, frontends/precinct-scanner/src/app_unhappy_paths.test.tsx, frontends/precinct-scanner/src/screens/poll_worker_screen.tsx
Removed the shortcut screens "do you want to open/close the polls?" because it became confusing to change the ballot bag before the hard limit is reached, you'd have insert poll worker card, tap "no" explicitly to move to the next screen, and that's just unintuitive.
Manually tested and updated automated tests.
~- [ ] I have added a screenshot and/or video to this PR to demo the change~
=> remove the shortcut open/close polls screens.

frontends/bmd/src/utils/ScreenReader/aria_screen_reader.ts
If a blind voter doesn't put on the headphones at the right time, or misses a cue, they're lost. This is a small step to fixing that, by repeating the utterances on a regular interval.
manual testing
~- [ ] I have added a screenshot and/or video to this PR to demo the change~
=> repeat spoken words on an interval.

.circleci/config.yml, libs/cvr-fixture-generator/package.json, libs/monorepo-utils/bin/generate-circleci-config, libs/monorepo-utils/bin/prune-unused, libs/monorepo-utils/bin/remove-package, libs/monorepo-utils/package.json, libs/monorepo-utils/src/circleci.test.ts, libs/monorepo-utils/src/circleci.ts, libs/monorepo-utils/src/dependencies.test.ts, libs/monorepo-utils/src/dependencies.ts, libs/monorepo-utils/src/index.ts, libs/monorepo-utils/src/pnpm.test.ts, libs/monorepo-utils/src/pnpm.ts, libs/monorepo-utils/src/unused.test.ts, libs/monorepo-utils/src/unused.ts, libs/res-to-ts/package.json, package.json, pnpm-lock.yaml, script/src/validate-monorepo/cli.ts, script/src/validate-monorepo/validation/circleci.ts, script/src/validate-monorepo/validation/index.ts, script/src/validate-monorepo/validation/packages.ts, script/src/validate-monorepo/validation/tsconfig.ts
I forked `vxsuite` for RAVE but don't want all the packages. I plan to use the scripts from this commit to remove the packages I don't want and re-generate the CircleCI config.
n/a
=> feat(monorepo-utils): add some features for RAVE

libs/custom-paper-handler/package.json, libs/custom-paper-handler/src/driver/driver.test.ts, libs/custom-paper-handler/src/driver/driver.ts, libs/custom-paper-handler/src/driver/scanner_config.ts, libs/custom-paper-handler/src/driver/test_utils.ts, pnpm-lock.yaml
Adds tests for most commands in the existing paper handler driver (ie. tests for legacy implementation). After this merges and #3443 is rebased on main, the test file diff should be easier to read.
N/A
Automated
=> Paper handler driver test

apps/scan/backend/src/scanners/custom/app_scan.test.ts, apps/scan/backend/src/scanners/custom/app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/custom/app_scan_jam.test.ts, apps/scan/backend/src/scanners/custom/app_scan_power_off.test.ts, apps/scan/backend/src/scanners/custom/app_scan_precinct_config.test.ts, apps/scan/backend/test/helpers/custom_helpers.ts
There's a race condition in the interaction between scanner mocks and the state machine. The state machine [tries to check the paper status](https://github.com/votingworks/vxsuite/blob/80511f6597388683b51c23126f7f31eaa971d78b/apps/scan/backend/src/scanners/custom/state_machine.ts#L828-L835) after completing the scan command. If it still says READY_TO_SCAN, then the scanner transitions to retry scanning, then checks the paper status again. If it then says READY_TO_EJECT, the state machine [moves to the rejecting state](https://github.com/votingworks/vxsuite/blob/80511f6597388683b51c23126f7f31eaa971d78b/apps/scan/backend/src/scanners/custom/state_machine.ts#L879).
Since we weren't updating the mocks to switch to a READY_TO_EJECT state soon enough, it was possible that it would switch in …
=> apps/scan/backend: Ensure scanner mocks simulate paper status after scan

apps/admin/frontend/src/api.ts
Noticed VxAdmin was running slowly and stuttering sometimes, CSS transitions weren't working, and my computer generally seemed to be working a little harder than it should.
Dug a bit and realised our auth status polling is done at the root component level and triggers a re-render of everything (every 100ms - just short enough to kill my beautiful transitions).
Started off by using the `isDataEqual()` react-query param, but got console warnings about it being deprecated, so using the unfortunately named `structuralSharing()` param instead. This does mean we're doing an object compare every 100ms, but it's a negligible cost compared to recomputing the render tree. Open to change suggestions if there are better workarounds here.
@adghayes - not 100% sure, but this could be what was slowing …
=> [VxAdmin] Reduce unnecessary rapid re-renders of the full React tree

frontends/precinct-scanner/jest.config.js, frontends/precinct-scanner/src/app_root.tsx, frontends/precinct-scanner/src/app_unhappy_paths.test.tsx
Before, we were aggressively showing it also on disconnected errors, but then it becomes tricky to show a stable error screen because the battery status takes a couple seconds to update. It appears to be safe to just show our new unplug/replug screens on unrecoverable_error, so we remove this additional special case.
=> fix(precinct-scanner): show the unplug-replug screen only on unrecoverable_error

frontends/precinct-scanner/src/app_root.tsx, frontends/precinct-scanner/src/app_unhappy_paths.test.tsx, frontends/precinct-scanner/src/screens/scan_error_screen.test.tsx, frontends/precinct-scanner/src/screens/scan_error_screen.tsx, frontends/precinct-scanner/src/screens/setup_scanner_screen.test.tsx, frontends/precinct-scanner/src/screens/setup_scanner_screen.tsx
Rework the error handling for a disconnected plustek to always prompt for unplug / replug.
Wait 3s before deciding what to show so that we don't show an unnecessary and confusing error if the cord is unplugged.
=> fix(precinct-scanner): properly handle all the ways plustek crashes

pnpm-workspace.yaml, script/src/validate-monorepo/validation/index.ts, script/src/validate-monorepo/validation/packages.ts
We no longer have any node packages in there, so just remove it from `validate-monorepo` etc.
n/a
Manually ran `script/validate-monorepo`.
=> fix(monorepo): remove `services` directory

apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/components/layout.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, libs/ui/jest.config.js, libs/ui/src/index.ts, libs/ui/src/tabbed_section/index.ts, libs/ui/src/tabbed_section/tab_bar.tsx, libs/ui/src/tabbed_section/tabbed_section.tsx
Updating the Election Manager Settings screen to fit within a landscape 13" ELO layout.
Had to break out the various actions into separate tabs so everything could fit above the fold. Got some input from the team on categories tab grouping/naming (https://uxmetrics.com/card_sort_reports/iIydf7) and used that as a starting point,  but I'm sure we'll tweak as needed over time.
https://github.com/votingworks/vxsuite/assets/264902/1978d4e0-1bdd-4b8b-98f2-5f654e5ccc95
- Visual testing
- Updated automated tests to expect a tabbed layout.
=> [VxScan] Fit Election Manager screen to landscape 13" screen

apps/central-scan/backend/jest.config.js, apps/central-scan/backend/src/central_scanner_app.ts, apps/central-scan/backend/src/server.ts
Continuation of https://github.com/votingworks/vxsuite/pull/3539.
n/a
=> ci(central-scan): use `v8` coverage

apps/scan/backend/jest.config.js, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/server.ts
Continuation of https://github.com/votingworks/vxsuite/pull/3538.
n/a
=> ci(scan): use `v8` coverage

libs/custom-scanner/jest.config.js, libs/custom-scanner/src/custom_a4_scanner.ts, libs/custom-scanner/src/index.ts, libs/custom-scanner/src/mocks/coder.ts, libs/custom-scanner/src/mocks/protocol.ts, libs/custom-scanner/src/mocks/simple_scanner.ts, libs/custom-scanner/src/mocks/web_usb_device.ts, libs/custom-scanner/src/parameters.ts, libs/custom-scanner/src/protocol.ts, libs/custom-scanner/src/usb_channel.ts
Continuation of https://github.com/votingworks/vxsuite/pull/3537.
n/a
=> ci(custom-scanner): use `v8` coverage

apps/scan/frontend/src/components/layout.tsx
Since we're moving from the 15" ELO screen to the smaller 13" (and switching to a landscape orientation), the election info bar no longer really works at larger size modes.
Briefly discussed with @mattroe the possibility of hiding the bar on some screens like we used to, but we fortunately don't need to at the default size. Makes sense to hide it when a voter explicitly decides to bump up the text size.
- Manual
=> [VxScan] Hide election info bar in large size modes

libs/ui/src/__snapshots__/test_mode.test.tsx.snap, libs/ui/src/test_mode.tsx
Previously tried to lock the `TestMode` banner to the 's' size mode by overriding the active theme, but missed the fact that component sizes are based on the root font size, which isn't affected by theme overrides. This became a little more obvious in landscape mode.
Updating this to explicitly use the `fontDefault` on the locked theme as the base font size instead.
- Manual
=> [VxScan] Lock TestMode banner size mode to 'small'

apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/scan/frontend/src/components/full_screen_prompt_layout.tsx, apps/scan/frontend/src/components/replace_ballot_bag_screen.tsx, apps/scan/frontend/src/preview_app.tsx, apps/scan/frontend/src/scan_app_base.tsx, apps/scan/frontend/src/screens/insert_ballot_screen.tsx, apps/scan/frontend/src/screens/scan_busy_screen.tsx, apps/scan/frontend/src/screens/scan_double_sheet_screen.tsx, apps/scan/frontend/src/screens/scan_error_screen.tsx, apps/scan/frontend/src/screens/scan_jam_screen.tsx, apps/scan/frontend/src/screens/scan_success_screen.tsx, apps/scan/frontend/src/screens/scan_warning_screen.tsx, libs/mark-flow-ui/src/components/__snapshots__/contest.test.tsx.snap, libs/mark-flow-ui/src/components/__snapshots__/yes_no_contest.test.tsx.snap, libs/mark-flow-ui/src/pages/__snapshots__/cast_ballot_page.test.tsx.snap, libs/ui/src/svg.tsx, libs/ui/src/with_scroll_buttons.tsx
Re-arranging content on voter-facing screens to make sure things fit in the new landscape orientation on the 13" ELO screen. Also updating the `screenType` setting for theme generation to `'elo13'`, now that most screens are compatible.
Expecting the styling to get tweaked a bit after design feedback, but this should at least unblock SLI testing on the new hardware configuration.
A few sample screen updates shown below - all updated screens use the same shared `FullScreenPromptLayout` component, so they all follow the same pattern.
For wordy screens (or in L/XL mode where there's bound to be content overflow), scroll buttons will appear - there's still some future work pending to update how we list out problem contests, but that's out of scope for now.
- Manual …
=> [VxScan] Fit voter-facing screens to landscape ELO13

apps/scan/frontend/src/screens/poll_worker_screen.tsx, apps/scan/frontend/src/screens/polls_not_open_screen.tsx
Updating the last few (Poll Worker) screens that weren't fitting properly in the new landscape 13" ELO format
- Visual
=> [VxScan] Fit Poll Worker screens to the landscape ELO13

apps/scan/frontend/src/components/full_screen_prompt_layout.tsx
Previous footer implementation for the FullScreenPromptLayout was a little brittle, assuming either 0 or 2 action buttons - noticed while testing an NH election that we get a weirdly left-aligned button when there's only one action.
Making the footer a little more flexible to handle that case.
- Manual
=> [VxScan] Stop assuming exactly 2 buttons in FullScreenPromptLayout

apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_tally_report_paths.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/insert_ballot_screen.tsx
We switched from "insert ballot below" to "insert ballot above" for the last machine build - switching back to a ballot tray below the screen, but now dropping the "above/below" wording altogether with the assumption that it's intuitive enough with the current build.
=> [VxScan] Update 'Insert Ballot' copy to exclude tray location

apps/admin/backend/src/app.ts
Both @kshen0 and I get a permissions error when the ballot package export code uses `fs.copyFile`:
```
[backend:run] [Error: EPERM: operation not permitted, copyfile '/tmp/tmp-498487-NDSXKpjA9TXF/franklin-county_lincoln-municipal-general-election_b4e07814b4__2023-06-07_13-41-04.zip' -> '/media/vx/usb-drive/ballot-packages/franklin-county_lincoln-municipal-general-election_b4e07814b4__2023-06-07_13-41-04.zip'] {
[backend:run]   errno: -1,
[backend:run]   code: 'EPERM',
[backend:run]   syscall: 'copyfile',
[backend:run]   path: '/tmp/tmp-498487-NDSXKpjA9TXF/franklin-county_lincoln-municipal-general-election_b4e07814b4__2023-06-07_13-41-04.zip',
[backend:run]   dest: '/media/vx/usb-drive/ballot-packages/franklin-county_lincoln-municipal-general-election_b4e07814b4__2023-06-07_13-41-04.zip' …
```
=> Fix ballot package exports

libs/backend/src/exporter.test.ts, libs/backend/src/exporter.ts, libs/backend/src/scan/cast_vote_records/export.test.ts, libs/backend/src/scan/cast_vote_records/export.ts, libs/backend/src/scan/globals.ts
Issue link: https://github.com/votingworks/vxsuite/issues/2866
The equivalent of https://github.com/votingworks/vxsuite/pull/3554 but for CVRs. Copying from that PR's description:
>  If we write data to USB and then sign that USB data, our security narrative relies on USBs not being compromised/faulty, as a compromised/faulty USB could claim to have written the data that we asked it to but actually have written something else. So even if the artifact and its signature match, the underlying artifact might be invalid. While it's highly unlikely that this situation would arise in practice, let's harden our security narrative by signing data on machine rather than USB.
This PR applies this change to CVR signing.
=> Sign CVRs using data on machine rather than USB

apps/admin/backend/jest.config.js, apps/admin/backend/src/cvr_files.ts, apps/admin/backend/src/globals.ts, apps/admin/backend/src/server.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/tabulation/full_results.ts, apps/admin/backend/src/tabulation/manual_results.test.ts, apps/admin/backend/src/tabulation/manual_results.ts, apps/admin/backend/src/tabulation/write_ins.test.ts, apps/admin/backend/src/tabulation/write_ins.ts, apps/admin/backend/src/types.ts, apps/admin/backend/src/util/cvrs.ts, apps/admin/backend/test/mock_cvr_file.ts, libs/types/src/tabulation.ts
_review commit-by-commit, first commit is just #3541 _
Ends the VxAdmin Tally Foundations mini-series. This PR ups test coverage to 100% for any new tabulation code. As a prerequisite to improving test coverage, it does a little refactoring and adds a test util to add CVRs to the store via a means other than cast vote record files. It refactors some of the tabulation utilities in VxAdmin and patches a couple bugs identified in testing. 
With this merged, it will be time to tackle the actual exports.
=> VxAdmin Tally Foundations Pt. 3 - Testing & Cleanup

apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/election_manager.tsx, apps/admin/frontend/src/components/navigation_screen.tsx, apps/admin/frontend/src/screens/ballot_list_screen.tsx, apps/admin/frontend/src/screens/logic_and_accuracy_screen.test.tsx, apps/admin/frontend/src/screens/logic_and_accuracy_screen.tsx
In recent threads related to documentation, we've decided to remove the "VxAdmin does not produce ballots for this election" messaging and just not show the relevant UI in those cases:
- Removing the "Ballots" nav button and screen from the System Administrator view, since it just contained instructions to log in as an Election Manager to save ballot packages.
- Removing the "L&A" nav button and screen from the Election Manager view for elections where we don't produce ballots/L&A packages
- Removing the "does not produce ballots" messaging from the "Ballots" screen - looks like remnants of deprecated functionality.
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates …
=> [VxAdmin] Prune UI related to ballot generation when not relevant

libs/usb-drive/src/unmount.sh
technically, I made the allowable mountpoint regex more permissive, but I don't see this increasing any risk, and it is simpler with fewer dependencies like `logname` which don't work in a systemd service.
=> fix(usb): simplify unmount to allow it to run in a systemd service

apps/admin/backend/src/app.cvr_files.test.ts, apps/admin/backend/src/app.results.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/card_counts.test.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/manual_results.test.ts, apps/admin/backend/src/tabulation/manual_results.ts, apps/admin/backend/src/types.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/app_write_in_flows.test.tsx, apps/admin/frontend/src/components/ballot_counts_table.test.tsx, apps/admin/frontend/src/components/ballot_counts_table.tsx, apps/admin/frontend/src/screens/reports_screen.test.tsx, apps/admin/frontend/src/screens/reports_screen.tsx, apps/admin/frontend/test/helpers/api_expect_helpers.ts, apps/admin/frontend/test/helpers/api_mock.ts, libs/types/src/tabulation.ts, libs/utils/src/tabulation.ts
Closes #3455.
We have the "Ballot Counts Tables" on the reports screen that give a ballot count for each precinct, each party (if primary election), each voting method, each scanner and each batch (if selected). This is not a design that we will certify on. It does not scale, and is inflexible. In the future, we might show ballot counts for voting method and party, maybe on the reports page and maybe elsewhere. Given that, I wanted to create the backend methods for getting those ballot counts in a way that will continue to be useful when we move to another format. Instead of giving the frontend a blob with all the different category breakdowns, each one is a different query. For the short term, this leads a less than ideal scenario where the reports page is making 5 - 7 requests for …
=> refactor(admin): Migrate Ballot Count Displays

libs/auth/src/artifact_authenticator.test.ts, libs/auth/src/artifact_authenticator.ts, libs/auth/src/config.ts, libs/auth/src/java_card.test.ts, libs/auth/src/java_card.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3581
Both @kofi-q and I have encountered sporadic auth errors when importing CVRs exported by VxScan in prod for m17a QA.
In these error cases, the CVRs are missing a corresponding `.vxsig` signature file. Turns out, the signature file isn't being flushed to the USB drive before the USB drive is removed. We make use of `sync -f` throughout the codebase to ensure data is written to USBs before their removal. We were just missing a `sync -f` in this specific code path. As we continue to hash out `libs/usb-drive`, I'm sure we can find a way to make this even more foolproof.
=> Ensure CVR export signature files are flushed to USB drives

libs/grout/src/server.ts
Fixes #3592 
Quick fix for a bug where VxAdmin couldn't load large election definitions. In the long term, it might not be necessary to support large request payloads in Grout, since we generally try to process large data on the backend. But this will temporarily resolve the blocking issue for today.
N/A
=> grout: Increase request size limit

apps/admin/backend/src/app.results.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/exports/batch_results.test.ts, apps/admin/backend/src/exports/batch_results.ts, apps/admin/backend/src/exports/csv_results.test.ts, apps/admin/backend/src/exports/csv_results.ts, apps/admin/backend/src/exports/sems_tallies.ts, apps/admin/backend/src/tabulation/card_counts.test.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/tabulation/full_results.ts, apps/admin/backend/src/tabulation/manual_results.test.ts, apps/admin/backend/src/tabulation/manual_results.ts, apps/admin/backend/src/tabulation/write_ins.test.ts, apps/admin/backend/src/tabulation/write_ins.ts, apps/admin/backend/src/types.ts, libs/types/src/tabulation.ts, libs/utils/src/tabulation.test.ts, libs/utils/src/tabulation.ts
_highly recommend commit-by-commit review_
Part of #3452. Adds methods to get data for tally report from the frontend. Specifically, that is: scanned results with write-in adjudication information, but write-ins grouped and, separately, manual results. 
The first two commits are refactors of the tabulation infrastructure that I've been building. The first adds a helper to help merge tabulation groups. The second is a bigger change - tabulation groups are now keyed with keys that can be converted into their group specifiers, so it's not required that the groups always maintain group specifiers. This was beginning to look like a footgun - e.g. you merge some tabulation groups and forget to include the `precinctId` labels, making the groups impossible to distinguish at the end of the …
=> Tally Report Part 1 - Backend Methods

apps/admin/backend/src/app.ts, libs/grout/src/util.test.ts, libs/grout/src/util.ts
I've come across an issue in the VxAdmin backend where, if I send records pulled directly from the store through `grout`, serialization fails. It says the records are not plain objects because their prototypes do not equal `Object.prototype`. Actually, both of the prototypes are "null prototypes", but two different null prototypes don't evaluate as equal. Why `better-sqlite3` returns objects with a different null prototype, I do not know.
=> refactor(grout): Grout Serialization Plain Object Prototype Requirement Tweak

apps/admin/frontend/src/screens/unconfigured_screen.tsx
Applying the new VVSG design updates to the `UnconfiguredScreen` in VxAdmin.
- N/A - no functional changes
=> [VxAdmin] VVSG Design Updates: UnconfiguredScreen

apps/admin/backend/src/app.auth.test.ts, apps/admin/backend/src/app.ts, apps/admin/integration-testing/cypress/support/auth.ts, apps/central-scan/integration-testing/cypress/e2e/configuration.cy.ts, apps/mark/integration-testing/cypress/support/e2e.js, libs/auth/scripts/mock_card.ts, libs/auth/src/card.ts, libs/auth/src/dipped_smart_card_auth.test.ts, libs/auth/src/dipped_smart_card_auth.ts, libs/auth/src/dipped_smart_card_auth_api.ts, libs/auth/src/intermediate-scripts/create_cert.ts, libs/auth/src/intermediate-scripts/sign_message.ts, libs/auth/src/java_card.test.ts, libs/auth/src/java_card.ts, libs/auth/src/mock_file_card.test.ts, libs/auth/src/mock_file_card.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3602
This PR updates card programming code to no longer write the full election definition to election manager cards. Now that VxMark is also configured via USB, nowhere in VxSuite do we now read the full election definition from election manager cards.
This cleanup has become more urgent because the all-bubble-ballot election definitions that SLI will be using are too large to fit on a Java Card and result in card programming errors with the current code.
=> No longer write full election definition to election manager cards 

apps/admin/frontend/src/app.tsx
Enabling the new VVSG2-compatible theme in VxAdmin.
Not all components have been updated to their theme-aware versions yet, but this is close enough to the final state that it unblocks code freeze and documentation pass for the m17a release.
- Did a click-through of the app to make sure nothing's too severely wonky (see [slack thread](https://votingworks.slack.com/archives/C05BNBX5C3G/p1687367406860259) for video/discussion).
=> [VxAdmin] Enable new VVSG theme

apps/admin/frontend/src/screens/settings_screen.test.tsx, apps/admin/frontend/src/screens/settings_screen.tsx, apps/central-scan/frontend/src/screens/admin_actions_screen.test.tsx, apps/central-scan/frontend/src/screens/admin_actions_screen.tsx, apps/mark-scan/frontend/src/pages/admin_screen.test.tsx, apps/mark-scan/frontend/src/pages/admin_screen.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx, apps/mark/frontend/src/pages/admin_screen.test.tsx, apps/mark/frontend/src/pages/admin_screen.tsx, apps/mark/frontend/test/helpers/mock_api_client.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/ui/src/set_clock.test.tsx, libs/ui/src/set_clock.tsx
Issue link: https://github.com/votingworks/vxsuite/issues/3324
This PR updates VxSuite apps to log out after clock changes as a heavy-handed means of preventing people from bypassing the session time limit by changing the clock.
As noted in the linked issue:
> You can currently bypass session time limits by changing the clock to a time in the past. Similarly, if you change the clock to a time far enough in the future, you'll be automatically logged out.
My first attempt at a fix (https://github.com/votingworks/vxsuite/pull/3608) 1) introduced other bugs, like flashing modals or the inactive session timeout being triggered, all stemming from the fact that changing the clock and updating the session expiry weren't an atomic operation, and 2) pushed us farther away from a desired long-term …
=> Log out after clock changes

apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, apps/admin/frontend/src/screens/tally_report_screen.tsx
Applying VVSG design updates to the `TallyReportScreen`:
- Replacing typography components with theme-aware versions
- Removing instances of the deprecated `Prose` component
- Not changing the shared `TallyReportMetadata` component, since that's also used for printouts - don't want to break any styling there until we can look at print components more holistically.
- Visual check
=> [VxAdmin] VVSG Design Updates: Tally Report Screen

libs/backend/src/scan/cast_vote_records/build_cast_vote_record.ts, libs/backend/src/scan/cast_vote_records/export.ts, libs/backend/src/scan/cast_vote_records/option_map.test.ts, libs/backend/src/scan/cast_vote_records/option_map.ts
Addresses a time complexity issue that arises when contests have many candidates, as in the bubble ballot. I'm hoping this will speed up the export.
=> build lookup for contest option indices so we don't have log(n^2) 

apps/admin/backend/src/cvr_files.ts
A tweak similar in spirit to https://github.com/votingworks/vxsuite/pull/3621 and https://github.com/votingworks/vxsuite/pull/3623, this PR speeds up VxAdmin CVR imports, specifically for ballots with large numbers of candidates (as is the case for the all-bubble ballot SLI will be using).
On my Mac VM, I'm seeing an import of 715 filled all-bubble ballot CVRs go from 12:40 minutes to 5:40 minutes!
=> Speed up VxAdmin CVR imports

libs/ui/src/reports/tally_report.tsx
Tally reports with longer content were overflowing the letter size page when printed. My guess is that the printer interpreted it as a legal size page instead of letter (I'm not sure exactly why). I couldn't find anywhere in the stack that the page size was specified, so it must be using some default logic.
I noticed that the CSS for BMD ballots specified a letter page size, so I tried adding that to the tally report CSS and that fixed the problem!
Before (left) and after (right)
Manually tested with Polls Opened and Polls Closed reports in VxScan
=> Fix overflowing tally reports

apps/admin/frontend/src/components/import_cvrfiles_modal.tsx, libs/ui/src/__snapshots__/modal.test.tsx.snap, libs/ui/src/modal.tsx
Updating the `ImportCvrFilesModal` in VxAdmin to use the new theme-aware typography components and removing instances of the now-deprecated `Prose` component.
Also noticed the modal contents aren't scrollable with a lot of CVR files on the USB drive, so locking the max height of the shared `Modal` component and adding scroll controls to the CVR files table, so that the modal actions are always visible.
Out of scope for now:
- Table styling (borders, spacing, contents)
https://github.com/votingworks/vxsuite/assets/264902/97c18607-5e46-4a76-adc4-4f9fa12d6dbf
- Updated changed snapshots
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system …
=> [VxAdmin] VVSG Design Updates: ImportCvrFilesModal

apps/admin/frontend/src/screens/tally_screen.tsx
__(Easier to review with the `?w=1` query param)__
Updating the `TallyScreen` in VxAdmin to use the new theme-aware typography components and removing instances of the now-deprecated `Prose` component.
Also removing italics for a11y/readability as recommended at http://www.tader.info/display.html
- Visual spot checks
=> [VxAdmin] VVSG Design Updates: TallyScreen

script/src/prod-build/index.ts
Production builds have been failing due to a breaking change in a Rust dependency (`half@2.3.1` requires Rust 1.70.0, but we're only on Rust 1.68.0). Our [Cargo.lock specifies a compatible version of that dependency](https://github.com/votingworks/vxsuite/blob/7010d9a3a17d22ed9cd1c69fe438e51ac42c2dbe/Cargo.lock#L372-L373), yet we aren't using that version (`half@2.2.1`).
The issue turned out to be a bug/gap in vxsuite's production build script. The script forgets to copy over our Cargo.toml and Cargo.lock to production build workspaces so that we use correct locked dependency versions. This PR fixes that 🛠️
=> Fix production builds

libs/dev-dock/backend/src/dev_dock_api.ts
Decrease the likelihood of running out of space when exporting large files.
=> dev-dock: Increase mock USB drive size from 100MB to 1GB

apps/admin/frontend/src/screens/tally_writein_report_screen.tsx
Updating the `TallyWriteInReportScreen` in VxAdmin to use the new theme-aware typography components and removing instances of the now-deprecated `Prose` and `Text` components.
Also moving the much longer screen title down into a page subtitle and using the parent page's "Election Reports" title.
- Visual spot checks
=> [VxAdmin] VVSG Design Updates: TallyWriteInReportScreen

libs/image-utils/bin/pdf-to-images, libs/image-utils/package.json, libs/image-utils/src/pdf_to_images.ts, pnpm-lock.yaml
A simple script wrapper around the `pdfToImages` function that takes a PDF file and writes a JPG image for each page in the PDF. I didn't give the script any flexibility or options to start, but if we need to extend it later we can.
=> image-utils: Add pdf-to-images script

apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx, apps/admin/frontend/src/screens/write_ins_screen.test.tsx, libs/ui/src/icons.tsx
Updating the `WriteInsAdjudicationScreen` in VxAdmin to use the new theme-aware typography components and removing instances of the now-deprecated `Prose` and `Text` components.
Also re-organising the UI to better utilise available screen space and fit more candidate options above the fold:
- Moved contest info, ballot info, and navigation controls to a full-width horizontal header
Additional nit update to the action button labels to be phrase/sentence case instead of title case.
https://github.com/votingworks/vxsuite/assets/264902/f01ff88a-1f68-414a-a4c1-8b05e55a9c74
https://github.com/votingworks/vxsuite/assets/264902/68445b2b-dd0d-4c74-86b5-dc4fc4a9e3a3
- Updated affected existing tests. …
=> [VxAdmin] VVSG Design Updates: Adjudication Screen

apps/design/backend/package.json, apps/design/backend/src/ballot_interpretation.test.ts, apps/design/backend/tsconfig.build.json, apps/design/backend/tsconfig.json, apps/design/shared/src/layout.ts, pnpm-lock.yaml
Add some basic tests to make sure we maintain the interpretability of ballots created by VxDesign.
This is a landmark moment (IMHO) because it these are the first tests that use dynamically generated ballots which can never get outdated (rather than fixtures).
I thought about putting these tests in libs/ballot-interpreter with the rest of our interpretation tests, but decided to keep them here for now since I'll be doing the majority of my development in apps/design for the moment. Open to feedback on this
A dynamically generated and marked ballot
=> VxDesign ballot interpretation tests

apps/admin/frontend/src/screens/machine_locked_screen.tsx
Applying VVSG design updates to the `MachineLockedScreen` in VxAdmin:
- Replace typography components with theme-aware versions
- Remove deprecated `Prose` component
- Visual
=> [VxAdmin] VVSG Design Updates: MachineLockedScreen

apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, apps/admin/frontend/src/screens/write_ins_screen.tsx, libs/ui/src/table.tsx
Applying VVSG design updates to the `WriteInsScreen` in VxAdmin:
- Replacing typography elements with theme-aware versions
- Removing deprecated `Prose` and `Text` instances
- Replaced `<Text muted>` with `<Font weight="light">` where appropriate - the former was applying a faded gray, which we don't currently have in the default color theme, so using font weight to convey which rows require action instead.
- Changed the table header font size to the document default, since it looked noticeably small compared to the table body.
Additional cleanup to render the adjudication flow screen as a full-page screen instead of a `<Modal fullscreen>`
- Manual - no functional changes
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any …
=> [VxAdmin] VVSG Design Updates: WriteInsScreen

apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, apps/admin/frontend/src/app.tsx, apps/admin/frontend/src/index.tsx
Applying VVSG design updates to the app root `ErrorBoundary` in VxAdmin:
- Replacing typography elements with theme-aware versions
Also fixing an old bug where app fonts and global styling aren't available to the ErrorBoundary by moving the libs/ui `AppBase` component to the top of the render tree.
- Manually, by throwing an exception in one of the screens
=> [VxAdmin] VVSG Design Updates: ErrorBoundary

libs/ui/src/export_logs_modal.tsx
Applying VVSG design updates to the `ExportLogsModal`, used across VxSuite central system apps:
- Replacing typography components with theme-aware versions
- Removing deprecated `Prose` instances
- Moving title elements into the newer `Modal.title` prop for styling/sizing consistency. 
Not pictured: other states of the modal - no major changes.
- Manual - no functional changes
=> [libs/ui] VVSG Design Updates: ExportLogsModal

apps/central-scan/frontend/src/app.tsx
Enabling the VVSG themes in CentralScan for consistency across VxSuite. Setting the color mode to the VVSG default medium contrast and text size mode to "small" for a start, similar to VxAdmin.
Will be updating typography/colors to their theme-aware versions over the course of the next few PRs and fixing anything that might look off as a result of switching to the new themes.
Also moving the global styles component to the top of the render tree and replacing typography components in the `ErrorBoundary` while I'm here.
https://github.com/votingworks/vxsuite/assets/264902/c4c92d00-5d18-490d-8e6b-014b388623a8
- Manual spot checks
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where …
=> [CentralScan] Enable VVSG Themes

apps/central-scan/frontend/src/components/main_nav.tsx
Updating the CentralScan nav bar to use colors from the global theme. Mostly matching VxAdmin in the header-only mode (on the adjudication screen), but punting for now on updating the logo to match.
Side note for later:
Would actually prefer a solid background for visual separation, but with the current default theme, there isn't really a good option that doesn't look too intense (black or the dark vx purple) - thinking we can add a central-system-specific color theme that's somewhere in-between the low contrast and medium contrast modes so we have a bit more flexibility (prompted by some discussion with Jonah on previous PRs).
- Manual/visual
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/l …
=> [CentralScan] VVSG Nav Bar

apps/central-scan/frontend/src/components/delete_batch_modal.tsx
Apply VVSG design updates to the `DeleteBatchModal`:
- Replacing typography components with theme-aware versions and removing deprecated `<Prose>` 
- Moving title into `title` prop
- Removing text centring for readability
- Visual
=> [CentralScan] VVSG Design Updates: DeleteBatchModal

apps/central-scan/frontend/src/components/export_results_modal.tsx
Apply VVSG design updates to the `ExportResultsModal`:
- Replacing typography components with theme-aware versions and removing deprecated `<Prose>` 
- Moving titles into `title` prop
No significant visual changes beyond sizing/spacing.
- Visual
=> [CentralScan] VVSG Design Updates: ExportResultsModal

apps/central-scan/frontend/src/components/set_mark_thresholds_modal.test.tsx, apps/central-scan/frontend/src/components/set_mark_thresholds_modal.tsx
Apply VVSG design updates to the `SetMarkThresholdsModal`:
- Replacing typography components with theme-aware versions and removing deprecated `<Prose>` 
- Moving title into `title` prop
- Minor typography tweaks to try to improve readability/a11y
- Visual
=> [CentralScan] VVSG Design Updates: SetMarkThresholdsModal

apps/central-scan/frontend/src/screens/admin_actions_screen.tsx
Apply VVSG design updates to the `AdminActionsScreen` in CentralScan:
- Replacing typography components with theme-aware versions and removing deprecated `<Prose>` 
- Moving modal titles into `title` prop
- Removing `danger` button variant styling from the non-destructive buttons that open confirmation modals.
https://github.com/votingworks/vxsuite/assets/264902/6de1c25e-cca0-41d6-8670-d6af736edf05
- Visual
=> [CentralScan] VVSG Design Updates: AdminActionsScreen

libs/backend/package.json, libs/backend/tsconfig.build.json, libs/backend/tsconfig.json, pnpm-lock.yaml
Just noticed this while pruning dependencies in `rave`.
n/a
n/a
=> chore(backend): remove unused `image-utils` dependency

apps/admin/frontend/src/components/election_manager.tsx, apps/admin/frontend/src/components/navigation_screen.tsx, apps/admin/frontend/src/router_paths.ts, apps/admin/frontend/src/screens/election_manager_system_screen.tsx, apps/scan/frontend/src/app_root.tsx, libs/ui/src/live_check_modal.tsx, libs/ui/src/system_administrator_screen_contents.tsx
A quick follow-up to https://github.com/votingworks/vxsuite/pull/3670, this PR adds the Live Check button to the VxAdmin election manager UI (under a new System tab) and the VxScan sys admin UI. Now, every user role can access the Live Check button on VxAdmin and VxScan (when the Live Check feature flag is enabled).
_VxAdmin election manager UI_
https://github.com/votingworks/vxsuite/assets/12616928/57ba6199-8457-49b9-a262-be91a5fc06fe
_VxScan sys admin UI_
https://github.com/votingworks/vxsuite/assets/12616928/1f667220-213e-4931-b54f-dcf2c7ec4da6
=> Add Live Check button to remaining user roles' UIs in VxAdmin and VxScan

apps/mark-scan/frontend/src/pages/print_page.tsx, apps/mark/frontend/src/pages/print_page.tsx, libs/mark-flow-ui/src/config/globals.ts, libs/mark-flow-ui/src/pages/print_page.test.tsx, libs/mark-flow-ui/src/pages/print_page.tsx
Rather than assuming that all users of this component has `updateTally` and `resetBallot` steps, just call back once the print job has started and let the parent component handle it.
I plan to use this in `rave-mark`.
n/a
n/a
=> refactor(mark): more generic print page callback

apps/central-scan/frontend/src/app_root.tsx, apps/central-scan/frontend/src/components/toggle_test_mode_button.tsx, apps/central-scan/frontend/src/screens/ballot_eject_screen.tsx, apps/central-scan/frontend/src/screens/machine_locked_screen.tsx
Closes: https://github.com/votingworks/vxsuite/issues/3570
Applying the last few bits of VVSG design updates to CentralScan:
- Replace heading and paragraph components with theme-aware versions
- Remove deprecated "Prose" elements
- Move modal titles into the `Modal.title` prop and remove unnecessary text centring
- Visual
=> [CentralScan] VVSG Design Updates: Typography Odds & Ends

libs/ui/src/set_clock.tsx
Realized that I never added a comment to the code explaining the motivation behind  https://github.com/votingworks/vxsuite/pull/3614 (logging out after clock changes). Could be hard to intuit why we do this without some added context.
=> Add clarifying comment

apps/admin/frontend/src/components/import_cvrfiles_modal.test.tsx, apps/admin/frontend/src/components/import_cvrfiles_modal.tsx
CVR import modal shows "X CVRs Loaded" but when it's in the thousands it needs to be number formatted to be readable.
=> Add Commas to Number in CVR Modal

libs/backend/src/scan/cast_vote_records/build_cast_vote_record.ts
Referencing the base type of `CVR.CVR` means we get hover tooltips for properties.
n/a
=> refactor(backend): reference base type for intellisense

apps/scan/backend/src/types.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app.tsx, apps/scan/frontend/src/components/display_settings_manager.test.tsx, apps/scan/frontend/src/components/display_settings_manager.tsx
From VVSG 2.0:
> 7.1-A – Reset to default settings
> If the adjustable settings of the voter interface have been changed by the voter or election worker during the voting session, the system must automatically reset to the default setting when the voter finishes voting, verifying, and casting.
- Adds a utility component that monitors the scanner status and resets the display settings to the default when we detect the end of a scanning session (currently, when we move from `'accepted'` to `'no_paper'`).
- Additionally, resetting to the default settings whenever an election official card is inserted, since non-voter-facing screens are optimised for the default display settings.
- When the card is removed, we restore the display settings to the previous voter state before the card was …
=> [VxScan] Reset voter display settings after each session

apps/admin/backend/src/app.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/tabulation/full_results.ts, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/full_test_deck_tally_report_button.test.tsx, apps/admin/frontend/src/components/full_test_deck_tally_report_button.tsx, apps/admin/frontend/src/components/test_deck_tally_report.tsx, apps/admin/frontend/src/screens/print_test_deck_screen.tsx, apps/admin/frontend/src/utils/election.ts, libs/utils/src/tabulation.test.ts, libs/utils/src/tabulation.ts
A performance issue in VxAdmin, which a few PRs will address, is long-running backend methods. It's completely reasonable, with the current scale of our customers, that things like tabulation take some seconds or even minutes. E.g. tallying a full election with 500,000 votes taking 7 seconds - we wish it were better, but all things considered, not bad.
What's _not_ OK is when these methods are synchronous, because it means that as long as they're running, all other backend methods will hang including statuses like `getAuthStatus`. I wonder if things like `getAuthStatus` should be running in another process... but that's a bigger change, out of scope, and not strictly necessary. For now, I'm simply identifying the bottlenecks and making synchronous methods `async`, or speeding them up …
=> yield to event loop during CVR tabulation

apps/central-scan/frontend/src/components/main_nav.tsx
Flagged in the [#m17b-qa channel](https://votingworks.slack.com/archives/C05GPCQTV53/p1689194820043139) - the test mode banner title is wrapping due to limited space in the nav bar, so we're trimming the text down to fit.
Visual
=> [CentralScan] Trim the Test Mode banner text to fit better

apps/admin/backend/jest.config.js, apps/admin/backend/src/app.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/screens/election_manager_system_screen.tsx, apps/central-scan/backend/src/central_scanner_app.ts, apps/central-scan/frontend/src/api.ts, apps/central-scan/frontend/src/screens/admin_actions_screen.tsx
Allow the user to switch from VxAdmin to VxCentralScan and back. This is a prototype.
=> buttons and API calls to switch from vxadmin to vxcentralscan and back.

apps/admin/frontend/src/components/save_backend_file_modal.tsx, apps/admin/frontend/src/components/save_frontend_file_modal.tsx, apps/admin/frontend/src/screens/print_test_deck_screen.tsx
a few loading modals in VxAdmin are clipping text because they have fixed lengths that are too short. we should have a setting for variable length modals but I wanted a quick polish fix for m17b by just using the wide setting on these modals
Before
After
=> fix(admin): a few loading modals in VxAdmin are clipping text

libs/utils/src/Hardware/utils.ts
recognize the broadcom card reader USB device as a card reader. Should be enough, as we use PCSClite to interface with the card reader and that interface should abstract out the card reader model. This fix just makes sure the front-end is happy that there is a card reader plugged in at all.
=> feat(utils): add broadcom card reader support.

apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/components/button_footer.tsx, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark/frontend/src/pages/contest_page.tsx, apps/mark/frontend/src/pages/review_page.tsx
**Context:** We would like to be able to continue upgrading older 14" landscape VxMark machines, so we need to make sure the updated styling also fits that screen format.
Updating the `ContestPage` and `ReviewPage` to fit better (especially at larger text sizes) in landscape mode:
- Moving the button nav bar to the right side of the screen in landscape mode
- Switching from a horizontal to vertical layout for the nav buttons in landscape mode
Looks a little meh to me (very technical design verdict), so let me know if you have ideas for any tweaks/different approaches.
Initially considered a split column approach, which would allow us display a ton more candidates above the fold, but it would've created too much code complexity with handling all the edge cases and not sure it's worth the …
=> [VxMarkOld] Use side nav layout for contest and review screens

apps/design/backend/src/ballot_interpretation.test.ts, apps/design/shared/src/env.d.ts, apps/design/shared/src/layout.test.ts, apps/design/shared/src/layout.ts
Adds support for ballot measures to the ballot layout code. For now, ballot measures all go in one section at the end (until we add support for user-defined sections) and always span the entire width of the page.
The big change is to split contest lay out into two phases:
- Figuring out the height of each contest
- Laying out the contests into columns based on their heights
There are a few notable pieces to this PR:
- Rudimentary text wrapping (using a fixed conservative estimate for character width)
- A new algorithm for laying out abstract elements in columns based on their heights
- New simplified ContestColumn and ContestSection components that take the results of the column layout algorithm
- Visual inspection of ballots
- Automated tests for interpretation
=> VxDesign: Ballot Measures

apps/design/backend/src/ballot_interpretation.test.ts, apps/design/frontend/src/app.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/layout.tsx, apps/design/frontend/src/segmented_control.tsx, apps/design/shared/src/document_svg.tsx, apps/design/shared/src/document_types.ts, apps/design/shared/src/layout.ts
Adds a new toggle in VxDesign to lay out bubbles on the left or the right. Updates the ballot layout code accordingly. Note that moving bubbles to the right also means right-aligning all of the text, which required some new SVG rendering functionality.
https://github.com/votingworks/vxsuite/assets/530106/1e2e656e-b1b3-4d9e-9978-6e7326030abc
- Visual inspection of ballots
- Automated tests for interpretation
=> VxDesign: Bubble position option (left/right)

apps/admin/frontend/src/utils/get_ballot_layout_page_size.ts, apps/central-scan/backend/src/fujitsu_scanner.ts, apps/design/backend/src/all_bubble_ballots.ts, apps/design/backend/src/ballot_interpretation.test.ts, apps/design/backend/src/render_ballot.tsx, apps/design/frontend/src/ballot_viewer.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/radio.tsx, apps/design/frontend/src/segmented_control.tsx, apps/design/shared/src/layout.test.ts, apps/design/shared/src/layout.ts, libs/cvr-fixture-generator/src/cli/generate/main.ts, libs/types/src/election.ts, libs/types/src/schema.test.ts, libs/ui/src/icons.tsx
Adds a toggle in VxDesign to switch between letter, legal, and custom longer paper sizes.
Legal ballots are already supported by the interpreter (which detects their dimensions from the scanned image), so there's no change needed there. We don't need to support interpreting the custom longer sizes yet.
The only adjustments needed were to configure the page size and timing mark grid in the layout algorithm.
Legal ballot
https://github.com/votingworks/vxsuite/assets/530106/7cbcfca9-be1f-4256-80e4-a74bd7ac40bd
- Visual inspection of ballots
- Automated testing of interpretation
=> VxDesign: Ballot paper size option

libs/custom-scanner/src/custom_a4_scanner.ts
see slack discussion: https://votingworks.slack.com/archives/CEL6D3GAD/p1689619057036929
I confirmed that the skipped lines are excluded from coverage reports
=> libs(custom-scanner): ignore flaky coverage lines

apps/mark-scan/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/pages/contest_page.tsx, apps/mark/frontend/src/pages/review_page.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/ui/src/__snapshots__/modal.test.tsx.snap, libs/ui/src/index.ts, libs/ui/src/modal.tsx
In order to continue to support/upgrade old landscape VxMark machines, this updates the newly re-styled write-in modal to fit in a landscape format.
- Moving modal action buttons to a vertical column on the right when the screen is in a landscape orientation.
- Expanding the max width of the write-in modal to accommodate the new layout.
Also fixing a minor bug from a previous PR to make sure the contest page and review page only use the side nav layout when in landscape mode.
https://github.com/votingworks/vxsuite/assets/264902/0e093918-178d-4f0f-b9c8-2e0091d6419b
- Manual
=> [VxMarkOld] Move write-in modal to vertical sidebar in landscape mode

libs/ballot-interpreter-nh/src/timing_marks.rs
Sometimes based on lighting conditions, there can be a strip of grainy pixels on one side of a ballot image. This causes any timing marks on a full-bleed ballot to be partially grainy. The contour detection algorithm sometimes finds contours in the grainy area, which can lead to rejected timing marks.
To fix this, we remove the logic to filter out timing marks contours that contain other contours inside of them. We think this filter was actually unnecessarily strict.
Manually tested with various scan backups, diffed the results and found negligible differences in scored marks.
=> interpreter: Fix timing mark detection for partially grainy marks

libs/ballot-interpreter-nh/src/timing_marks.rs
If for whatever reason, the interpreter can't find any timing marks on the left or right edge, we should reject the ballot.
Previously, we would infer the entire column of timing marks using the corner marks found from the top and bottom row. This could be problematic if the top and bottom row didn't match up (e.g. since the bottom row is sparsely encoded metadata).
An example of when this could happen is detailed in #3737.
To fix this, before inferring missing timing marks for the left/right edges, we check that we found at least 25% of the expected number of timing marks on that edge. This makes sure that we're still liberal in allowing for missing timing marks, but we have enough timing marks to have confidence in our best fit line.
An example of inferring an incorrect left-side timing …
=> interpreter: Guard against missing left/right timing marks

apps/admin/backend/schema.sql, apps/admin/backend/src/app.cvr_files.test.ts, apps/admin/backend/src/app.exports.test.ts, apps/admin/backend/src/app.results.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/app.writeins.test.ts, apps/admin/backend/src/cvr_files.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/types.ts, apps/admin/backend/src/util/write_ins.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/components/adjudication_ballot_image_viewer.tsx, apps/admin/frontend/src/components/adjudication_double_vote_alert_modal.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.test.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx, apps/admin/frontend/test/helpers/api_mock.ts
@kofi-q review commit-by-commit recommended
When loading up VxAdmin with lots of CVRs and write-ins, the write-in adjudication flow became very sluggish. We were fetching a ton of data after every adjudication. The main point of this PR is to make the data fetching more efficient so the WIA UI is more responsive.
The PR also introduces two flow tweaks to make WIA easier:
- maintains a write-in sequence, based on when a write-in was imported, such that whenever write-ins are added they are added to the end of the queue
- when you click to adjudicate a contest, will automatically drop you on the _first pending_ write-in. so you don't have to scroll forward to adjudicate a new batch, and if you accidentally miss one you can find it easily.
(has audio) …
=> Write-In Adjudication Performance Changes + Flow Tweaks

libs/ballot-interpreter-nh/ts/src/cli.ts
I was getting an error when trying to use the interpreter CLI to pick out a specific sheet from a backup. Seems like better-sqlite3 doesn't support interpolating arrays, so to fix I just joined the array of sheet ids into a string.
=> interpret: Fix SQL query for multiple sheet ids from backup

apps/admin/backend/src/app.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/write_ins.ts, apps/admin/backend/src/util/export_file.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/ballot_counts_table.tsx, apps/admin/frontend/src/screens/reports_screen.tsx
Ultimately, I've been staring at this app a little too long to have a good polisher's eye, but I patched up some small things I've noticed along the way. I also tested the app at 1,000,000 CVRs where it performed as well as I'd expected. See video and details below. 
Should not be taken as actual benchmarks, because they were done on my Mac M1, but I checked how long various common actions took in seconds:
| Action | Time (seconds) |
| Importing 100,000 CVR File | 330  |
| Loading CVR File List  | 5  |
| Loading Write-In Summary Page | < 1  |
| Loading Summary Ballot Counts |  < 1 |
| Generating Full Election Tally Report | 11  |
| Generating Scanner Report (10% of CVRs) | 2  |
| Generating Write-In Adjudication Report | 3  |
| Exporting Batch Results | 9 …
=> VxAdmin Polish Pass

apps/admin/backend/schema.sql, apps/admin/backend/src/app.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/card_counts.test.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/utils.ts
To meet VVSG 1.1.9-B.5, we must be able to offer a count of blank ballots. It was quick to add this to the backend, so just did it now while `admin-backend` is fresh for me. We can build the UI when we build the other reporting UI. Although I wonder if these counts will be more useful in an expanded ballot adjudication flow. Either way.
=> Counting Blank Ballots Backend

libs/custom-paper-handler/src/driver/coders.ts, libs/message-coder/src/byte_array_with_length_prefix.test.ts, libs/message-coder/src/byte_array_with_length_prefix.ts
This flake conforms to @eventualbuddha's `fast-check` hypothesis, that sometimes `fast-check` generates values that lead to 100% coverage and sometimes they don't. 
In this case I actually refactor the code so that `bytesRequired` is never 0, because we always require at least one byte for a number. A semantic change, really, which helps avoid the flaky switch case.
=> refactor(message-coder): fix flaky test

apps/mark-scan/frontend/src/app.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark/frontend/src/app.test.tsx, apps/mark/frontend/src/app_root.tsx, libs/mark-flow-ui/src/hooks/use_display_settings_manager.test.tsx, libs/mark-flow-ui/src/hooks/use_display_settings_manager.ts, libs/mark-flow-ui/src/index.ts
From VVSG 2.0:
> 7.1-A – Reset to default settings
> If the adjustable settings of the voter interface have been changed by the voter or election worker during the voting session, the system must automatically reset to the default setting when the voter finishes voting, verifying, and casting.
- Add a step to the `resetBallot` app state function to also reset the display settings (since this marks the start of a new voter session).
- Adds a shared react hook to `libs/mark-flow-ui` that monitors auth status and voting session changes and resets to the default settings whenever an election official card is inserted, since non-voter-facing screens are optimised for the default display settings.
- When the card is removed, we restore the display settings to the previous voter state before the …
=> [VxMark] Reset display settings whenever a new voting session is started

apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/routes.ts
Splits the Ballots screen into two tabs, one for the list of ballot styles and one for the ballot layout settings. While this does move the settings one click further away from the ballot previews, I think it helps with the overall organization of the app. Plus, these settings won't actually be modified very much, since they are global settings. Definitely room to improve on this in the future, but a small cleanup for now.
https://github.com/votingworks/vxsuite/assets/530106/1f7f3123-fd36-4135-a1ea-5ba4fb6af49a
=> VxDesign: Ballot styles/ballot layout tabs

libs/custom-scanner/src/protocol.test.ts
Another `fast-check` case of flakiness, I addressed this one by fixing the random seed.
=> test(custom-scanner): use seed for flaky fast-check test

apps/design/shared/src/layout.ts
It was rendering the date in the current user's timezone rather than UTC, which could make it off by a day.
=> VxDesign: Fix election date timezone bug

apps/admin/frontend/package.json, apps/admin/integration-testing/package.json, apps/central-scan/integration-testing/package.json, apps/design/frontend/package.json, apps/design/shared/package.json, apps/mark-scan/frontend/package.json, apps/mark-scan/integration-testing/package.json, apps/mark/frontend/package.json, apps/mark/integration-testing/package.json, apps/scan/frontend/package.json, libs/mark-flow-ui/package.json, libs/ui/package.json, pnpm-lock.yaml
I don't think this is being used by any of the eslint configurations and it's been throwing peer dependency warnings. Better to get rid of than update if not needed.
=> chore(eslint): remove `eslint-plugin-flowtype`

apps/scan/backend/src/types.ts, apps/scan/backend/test/helpers/shared_helpers.ts, apps/scan/frontend/src/components/display_settings_manager.test.tsx, apps/scan/frontend/src/components/display_settings_manager.tsx, libs/types/src/index.ts, libs/types/src/precinct_scanner.ts
Followup from https://github.com/votingworks/vxsuite/pull/3706, addressing VVSG 7.1-A (Reset to display default settings).
Got guidance from @mattroe about how to handle rejected ballots:
> I think we should reset once a ballot leaves the document scanner -- whether it's casted in the box or a voter takes it from the machine.
Updating the reset logic to always reset when the scanner moves into the `no_paper` state (vs when moving from `accepted` to `no_paper` as before).
https://github.com/votingworks/vxsuite/assets/264902/378a12d9-794b-4192-a612-cb2746714b63
- Updating the existing unit test accordingly
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage …
=> [VxScan] Always reset display settings when paper leaves the scanner

apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, apps/mark-scan/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark-scan/frontend/src/pages/__snapshots__/not_found_page.test.tsx.snap, apps/mark-scan/frontend/src/pages/__snapshots__/start_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/not_found_page.test.tsx.snap, libs/mark-flow-ui/src/pages/__snapshots__/print_page.test.tsx.snap, libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap, libs/ui/src/app_base.tsx, libs/ui/src/bmd_paper_ballot.tsx, libs/ui/src/index.ts, libs/ui/src/themes/vx_theme_provider.test.tsx, libs/ui/src/themes/vx_theme_provider.tsx
With the new UI themes enabled, most of the `Prose` component's text-specific styling gets stripped - this breaks the styling of the `BmdPaperBallot` a bit, so updating the layout and styling, using the newer typography components, to more closely match the pre-themes styling.
Also adding a `VxThemeProvider` wrapper around the `styled-components/ThemeProvider` to simplify theme installation, since `BmdPaperBallot` now relies on themed components.
- Manual testing in VxMark (ballot printing) and VxAdmin (L&A packages) to verify styling
- Updated affected tests/snapshots
=> [libs/ui] Fix BmdPaperBallot printout styling

.circleci/config.yml, libs/monorepo-utils/src/circleci.ts
The CircleCI plugin we use for downloading chrome for integration tests broke, so we had to apply a workaround, but they applied a bug fix so we can revert the workaround. 
Issue: https://github.com/CircleCI-Public/browser-tools-orb/issues/75#issuecomment-1640923560
=> Revert CircleCI Workaround Fix

apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, apps/central-scan/frontend/src/components/button_bar.tsx, apps/central-scan/frontend/src/components/prose.tsx, apps/mark-scan/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, libs/ui/src/__snapshots__/button_bar.test.tsx.snap, libs/ui/src/__snapshots__/modal.test.tsx.snap, libs/ui/src/button_bar.tsx, libs/ui/src/button_list.tsx, libs/ui/src/modal.tsx, stylelint.shared.js
All modals in `vxsuite` are currently appearing fullscreen. This is because the new `stylelint` config applied a new syntax for `@media` queries that isn't supported until Chromium 104, but our version of `electron` is many versions behind that.
=> fix(lint): reverse stylelint media query notation rule & add comments to config

apps/admin/frontend/src/components/hand_marked_paper_ballot.tsx, apps/admin/frontend/src/utils/get_ballot_layout_density.ts, apps/admin/frontend/src/utils/get_ballot_layout_page_size.ts, apps/central-scan/backend/src/store.ts, apps/design/backend/src/app.ts, apps/design/backend/src/ballot_interpretation.test.ts, apps/design/frontend/src/ballot_viewer.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/shared/src/layout.ts, apps/scan/backend/src/store.ts, libs/ballot-encoder/src/stats.test.ts, libs/converter-nh-accuvote/src/convert/convert_election_definition.ts, libs/converter-nh-accuvote/src/convert/convert_election_definition_header.test.ts, libs/cvr-fixture-generator/src/cli/generate/main.ts, libs/cvr-fixture-generator/src/generate_cvrs.ts, libs/types/src/cdf/ballot-definition/convert.test.ts, libs/types/src/cdf/ballot-definition/convert.ts, libs/types/src/cdf/ballot-definition/fixtures.ts, libs/types/src/election.test.ts, libs/types/src/election.ts, libs/types/src/election_utils.ts
We're relying on this field more and more in VxDesign and the interpreter, so we should make it a required part of the election definition rather than setting independent defaults in various locations where we try to use it.
N/A
Updated all test fixtures.
=> Require Election.ballotLayout

apps/design/backend/package.json, apps/design/backend/src/all_bubble_ballots.ts, apps/design/backend/src/app.ts, apps/design/backend/src/ballot_interpretation.test.ts, apps/design/backend/src/store.ts, apps/design/frontend/src/ballot_screen.tsx, apps/design/frontend/src/ballot_viewer.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/elections_screen.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/tabulation_screen.tsx, apps/design/shared/src/encode_metadata.ts, apps/design/shared/src/layout.ts, libs/ballot-interpreter/package.json, libs/ballot-interpreter/src/interpret.ts, libs/ballot-interpreter/tsconfig.build.json, libs/ballot-interpreter/tsconfig.json, pnpm-lock.yaml
Modifies libs/ballot-interpreter to check the election hash (there was already logic for checking precinct/test mode).
In order to have the correct election hash encoded in the ballot metadata QR code, we have to first lay out all of the ballots to compute gridLayouts. To support this change, we also undo passing an ElectionDefinition around in VxDesign, since we only need the Election data until we're finally ready to layout the ballots and compute the hash.
Also changes VxDesign to show a placeholder QR code in ballot previews to help distinguish them from real ballots that have an encoded election hash.
In browser preview with placeholder QR code
Updated existing automated tests
=> Check election hash for VxDesign ballots

.pnpmfile.cjs, libs/api/package.json, libs/auth/package.json, libs/logging/package.json, package.json, pnpm-lock.yaml
Our `pnpm install` is noisy because we're logging changes / checks we're doing of our dependencies, some of which are no longer necessary. See comments.
=> chore(monorepo): make `pnpm install` less noisy

apps/admin/frontend/test/render_in_app_context.tsx, apps/central-scan/frontend/test/api.tsx, apps/central-scan/frontend/test/render_in_app_context.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx, apps/mark/frontend/test/helpers/mock_api_client.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/ui/src/error_boundary.test.tsx, libs/ui/src/error_boundary.tsx
In order to catch API mock errors and display their messages in test output, we make sure that test helpers that provide an API are wrapped in an error boundary. That way, when a `screen.getByText(...)` fails, the DOM output will be the text of the actual mock error, not just a confusing random bit of DOM.
=> Add TestErrorBoundary to test helpers

vxsuite.code-workspace
Since moving the TypeScript dependency to the top level of the workspace (instead of nested in each package), VS Code has been giving me an error about not being able to find TypeScript. This points the workspace settings to the top-level install.
In order to make it work, I had to add the root directory to the list of folders. I think this has a nice side effect of also allowing easy searching for files in that folder (which until now don't show up in the file search bar). So far it doesn't seem to have any negative side effects that I've noticed.
=> Fix VSCode workspace TypeScript path

apps/admin/backend/schema.sql, apps/admin/backend/src/store.ts, apps/central-scan/backend/schema.sql, apps/central-scan/backend/src/store.ts, apps/mark-scan/backend/schema.sql, apps/mark-scan/backend/src/store.test.ts, apps/mark-scan/backend/src/store.ts, apps/mark/backend/schema.sql, apps/mark/backend/src/store.ts, apps/scan/backend/schema.sql, apps/scan/backend/src/store.ts, libs/types/src/system_settings.ts
As the system settings grows to encompass more complex data, it's easier to store the JSON blob rather than convert it to SQL columns. We use a schema to validate the data on retrieval to ensure that it complies with the current type definition.
N/A
=> Store system settings as JSON blob in db

apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/pages/admin_screen.test.tsx, apps/mark-scan/frontend/src/pages/admin_screen.tsx, apps/mark-scan/frontend/src/pages/insert_card_screen.test.tsx, apps/mark-scan/frontend/src/pages/insert_card_screen.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark-scan/frontend/src/pages/replace_election_screen.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx
* Always checks for `query.isSuccess` when querying precinct selection
* Returns null instead of an empty `Result`
No behavior change
=> Safer react query handling

apps/admin/backend/schema.sql, apps/admin/backend/src/app.ts, apps/admin/backend/src/store.test.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/full_results.ts, apps/admin/backend/src/tabulation/manual_results.ts, apps/admin/backend/src/tabulation/utils.test.ts, apps/admin/backend/src/tabulation/utils.ts, apps/admin/backend/src/types.ts, apps/admin/frontend/src/utils/election.ts, libs/types/src/tabulation.ts, libs/utils/src/tabulation/tabulation.test.ts, libs/utils/src/tabulation/tabulation.ts
Rather than translate / lookup ballot styles into their party affiliations in our tabulation code, put that lookup into the persistent store and use the database to gather that information. It's still not hiccup-free but I think this is clearer / safer.
Existing testing passes.
=> refactor(admin): track ballot style party ids in store

apps/admin/backend/src/app.auth.test.ts, apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/test/app.ts, apps/central-scan/backend/src/auth.test.ts, apps/central-scan/backend/src/central_scanner_app.ts, apps/mark-scan/backend/src/app.auth.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/test/app_helpers.ts, apps/mark/backend/src/app.auth.test.ts, apps/mark/backend/src/app.ts, apps/mark/backend/test/app_helpers.ts, apps/scan/backend/src/app.ts, apps/scan/backend/src/app_auth.test.ts, libs/auth/src/dipped_smart_card_auth.test.ts, libs/auth/src/dipped_smart_card_auth_api.ts, libs/auth/src/inserted_smart_card_auth.test.ts, libs/auth/src/inserted_smart_card_auth_api.ts, libs/auth/src/lockout.test.ts, libs/auth/src/lockout.ts, libs/auth/src/sessions.test.ts, libs/auth/src/sessions.ts
This helps avoid errors where a field is accidentally omitted and falls
back to the default, as discussed here: https://github.com/votingworks/vxsuite/pull/3852#discussion_r1301848429.
N/A
=> libs/auth: Require machine state configuration params

apps/admin/backend/schema.sql, apps/admin/backend/src/exports/csv_results.ts, apps/admin/backend/src/store.test.ts, apps/admin/backend/src/store.ts, apps/admin/frontend/src/components/test_deck_tally_report.tsx, libs/ui/src/reports/precinct_scanner_tally_reports.tsx, libs/utils/src/tabulation/contest_filtering.test.ts, libs/utils/src/tabulation/contest_filtering.ts
Adds ability to filter contests (decide which contests should appear in a report) into the VxAdmin store and uses the new logic for CSV exports. In the second commit, I replace some of the consumers of the complex util from #3788 with a simpler util. 
I'm not able to remove all the old code yet because I need to refactor the way tally report data is served to the VxAdmin frontend, which I will work on next.
Added contest filtering testing to `store.test.ts`.
=> refactor(admin): use DB for contest filtering

apps/admin/backend/schema.sql, apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/store.test.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/card_counts.test.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/tabulation/manual_results.test.ts, apps/admin/backend/src/tabulation/write_ins.test.ts, apps/admin/backend/src/types.ts, apps/admin/backend/test/app.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/screens/unconfigured_screen.test.tsx, apps/admin/frontend/src/screens/unconfigured_screen.tsx, apps/admin/frontend/test/helpers/api_mock.ts
System settings are election-specific, since they are imported at the same time (in the election package). Since the backend of VxAdmin supports storing multiple elections, it makes sense to store the system settings with each election.
In making this change, I also thought it made sense for the API to configure the election to reflect this change as well.
N/A
- Manually tested configuring/unconfiguring
=> VxAdmin: Store system settings with election

libs/auth/src/apdu.test.ts, libs/auth/src/apdu.ts, libs/auth/src/card_reader.test.ts, libs/auth/src/card_reader.ts
This changes `CardReader::transmit` to record the number of bytes still available to be read and to then request exactly that number of bytes while reading the response.
Some Java cards, like CAC cards, are pretty strict about this. This commit backports some of @benadida's changes made to support CAC cards.
n/a
=> fix(auth): follow the protocol more closely

apps/central-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark/frontend/src/app_root.tsx, libs/eslint-plugin-vx/src/configs/react.ts, libs/eslint-plugin-vx/src/configs/recommended.ts, libs/eslint-plugin-vx/src/rules/index.ts, libs/eslint-plugin-vx/src/rules/no_react_hook_mutation_dependency.ts, libs/eslint-plugin-vx/tests/rules/no_react_hook_mutation_dependency.test.ts
Closes #3794. We've seen a bug or two related to re-render cycles due to mutations changing on every render. The resulting pattern is not cute, but it avoids bugs!
=> lint: add rule to prevent using mutations as dependencies in react hook dep arrays

apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/cvr_files.ts, apps/admin/frontend/src/components/export_election_ballot_package_modal_button.test.tsx, apps/admin/frontend/src/components/export_election_ballot_package_modal_button.tsx, apps/admin/frontend/test/helpers/api_mock.ts, libs/auth/src/apdu.ts, libs/auth/src/artifact_authentication.test.ts, libs/auth/src/artifact_authentication.ts, libs/backend/src/ballot_package/ballot_package_io.test.ts, libs/backend/src/ballot_package/ballot_package_io.ts, libs/backend/src/exporter.ts, libs/backend/src/scan/cast_vote_records/export.ts, libs/backend/src/scan/cast_vote_records/legacy_export.test.ts, libs/backend/src/scan/cast_vote_records/legacy_export.ts, libs/backend/src/scan/globals.ts, libs/types/src/ballot_package.ts, libs/types/src/cast_vote_records.ts, libs/types/src/index.ts, libs/types/src/tallies.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3838
This PR adds signing to the new CVR export function for continuous export. Alongside each CVR export directory will now be a `.vxsig` file that contains a signature of the export's top-level metadata file, where that metadata file further contains a hash of all the contents of the CVR export directory. (The hashing logic is coming in its own PR.) To accomplish this, I made a number of changes to artifact auth functions in the auth lib, highlighted in PR comments.
=> Add signing to new CVR export function

frontends/election-manager/src/components/full_test_deck_tally_report_button.tsx, frontends/election-manager/src/components/test_deck_tally_report.tsx, frontends/election-manager/src/screens/print_test_deck_screen.tsx, frontends/election-manager/src/utils/election.ts
Correct how we determine test deck tallies on `m16-dev`. Currently we create a full election tally and try to "manually" precompute the important subtallies. Instead, we can convert each test ballot to a mock CVR and use the election tally utilities to create subtallies as the system normally would.
Addresses bug in 2023 MS primary in which primary test decks showed up with 0 counts.
=> base test deck tally on mock CVRs

libs/auth/src/cast_vote_record_hashes.test.ts, libs/auth/src/cast_vote_record_hashes.ts, libs/backend/src/scan/cast_vote_records/export.ts
Some perf improvements to #3898.
Rather than reading all the file data for a given directory upfront, read it at the point where we actually need it to compute the hash. Additionally, we don't need to read all the file data for a given file all at once. It can be streamed while we compute the hash incrementally.
n/a
=> perf(auth): read file data as needed

apps/scan/backend/schema.sql, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, libs/auth/package.json, libs/auth/src/artifact_authentication.test.ts, libs/auth/src/artifact_authentication.ts, libs/auth/src/cast_vote_record_hashes.test.ts, libs/auth/src/cast_vote_record_hashes.ts, libs/auth/src/config.ts, libs/auth/src/index.ts, libs/auth/src/java_card.ts, libs/auth/src/lockout.ts, libs/auth/tsconfig.build.json, libs/auth/tsconfig.json, libs/backend/src/scan/cast_vote_records/export.ts, libs/types/src/cast_vote_records.ts, pnpm-lock.yaml
Issue link: https://github.com/votingworks/vxsuite/issues/3838
This PR implements the long discussed Merkle-tree-backed scheme for efficient hashing of continuously exported CVRs! Much more context can be found in the [Continuous Export Tech Spec](https://docs.google.com/document/d/1ruFBhxPbP0NvxuEDZXfl-wzz-ikBODBIbvSJKDLaIMI/edit#heading=h.adjk78a95otw).
=> Implement Merkle-tree-backed scheme for efficient hashing of continuously exported CVRs

apps/scan/backend/src/app.ts, apps/scan/backend/src/scanners/custom/app_config.test.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_tally_report_paths.test.tsx, apps/scan/frontend/src/components/export_results_modal.test.tsx, apps/scan/frontend/src/components/export_results_modal.tsx, apps/scan/frontend/src/screens/poll_worker_screen.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/backend/src/scan/cast_vote_records/export.ts
Issue links: https://github.com/votingworks/vxsuite/issues/3914, https://github.com/votingworks/vxsuite/issues/3916
This PR has VxScan use the new export format for full exports, when the continuous export feature flag is enabled. It also has VxScan update the export metadata on polls close (to indicate that polls have been closed).
=> Have VxScan use new export format for full exports

apps/central-scan/backend/schema.sql, apps/central-scan/backend/src/backup.ts, apps/central-scan/backend/src/central_scanner_app.test.ts, apps/central-scan/backend/src/central_scanner_app.ts, apps/central-scan/backend/src/importer.ts, apps/central-scan/backend/src/store.test.ts, apps/central-scan/backend/src/store.ts, apps/scan/backend/src/app.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, libs/backend/src/scan/cast_vote_records/export.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3918
While we're aren't bringing continuous export to VxCentralScan, we do still want to use the new export format on VxCentralScan (multiple CVR JSON files instead of just one) so that VxAdmin only has to worry about one format on import. This PR has VxCentralScan use the new export format, when the continuous export feature flag is enabled.
We've talked about using a slightly modified version of the format on VxCentralScan, where each directory and CVR JSON file corresponds to a batch instead of a single CVR. But I'm not going to make that change until I do some performance testing on the current format. If there's a significant performance benefit to exporting by batch, I'll make changes. Otherwise, …
=> Have VxCentralScan use new export format

apps/admin/frontend/src/components/reporting/export_report_pdf_button.test.tsx, apps/admin/frontend/src/components/reporting/export_report_pdf_button.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.test.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx, apps/admin/frontend/src/screens/tally_report_builder.test.tsx, apps/admin/frontend/src/setupTests.ts, apps/admin/frontend/src/utils/reporting.test.ts, apps/admin/frontend/src/utils/reporting.ts, libs/utils/src/filenames.ts
Follow up to #3927, adding ability to export reports as PDFs to the report builder. Functionality already exists for other tally pages so it should look familiar.
For the file names, I took the same approach as with the report titling - if there are only two levels of simple filters, generate a name. Otherwise, just call it "custom." We hit "custom" in fewer cases here because the filename represents all reports in a list rather than just one, so the filter is only the `filter` and the `groupBy` is separately encoded in the filename. Whereas for report titles, we try to combine the `filter` and the identity of the current group.
For example, say you have "Absentee" filter and "By Precinct" grouping. The report names might be:
1. Precinct 1 Absentee Ballots Tally Report
2. Precinct 2 …
=> feat(admin): Tally Report Builder - Export Report PDF

apps/admin/backend/jest.config.js, apps/admin/backend/package.json, apps/admin/backend/src/app.results_csv_export.test.ts, apps/admin/backend/src/exports/csv_results.test.ts, apps/admin/backend/src/exports/csv_results.ts, apps/admin/backend/test/csv.ts, pnpm-lock.yaml
_probably review by commit_
Please read [this Slack conversation](https://votingworks.slack.com/archives/CEL6D3GAD/p1693945053137789) for full context. In short, we want all filters that are applied to a report to be apparent in the `.csv` export. There's an alternate approach I could have chosen (see slack convo) and I'm absolutely open to pushback if you think the alternate is better, but this way means less change for the final exports.
Alongside the change to `.csv` files, I basically rewrote all the testing for results `.csv` exports. For the better! More coverage.
=> Self-Documenting `.csv` Exports

apps/admin/backend/schema.sql, apps/admin/frontend/src/components/reporting/filter_editor.test.tsx, apps/admin/frontend/src/components/reporting/filter_editor.tsx, apps/admin/frontend/src/components/reporting/group_by_editor.test.tsx, apps/admin/frontend/src/components/reporting/group_by_editor.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.test.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx, apps/admin/frontend/src/screens/tally_report_builder.test.tsx, apps/admin/frontend/src/utils/reporting.test.ts, apps/admin/frontend/src/utils/reporting.ts, libs/ui/src/reports/custom_filter_summary.test.tsx, libs/ui/src/reports/custom_filter_summary.tsx
Adds "Scanner" and "Batch" to the filtering and grouping options of the report builder.
https://github.com/votingworks/vxsuite/assets/37960853/612b61bf-10f1-4fe7-bae9-242268860cbe
=> Tally Report Builder - Scanner + Batch Dimensions

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/index.ts, apps/design/backend/src/store.ts, apps/design/backend/test/helpers.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/ballot_viewer.tsx, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/tabulation_screen.test.tsx, apps/design/frontend/test/fixtures.ts, apps/design/frontend/test/routing_helpers.tsx, libs/hmpb/layout/src/layout.ts, libs/types/src/election_utils.ts
Adds basic support for primary elections to VxDesign, including:
- A field to select either a "general" or "primary" election type
- Only showing the field to add party associations to contests for primary elections
- Generating party-specific ballot styles
- Displaying the party associated with each ballot style
- Displaying the party name on primary election ballots
(sound on!)
https://github.com/votingworks/vxsuite/assets/530106/278adfa0-60ad-4eaa-a431-519e2b9f31cb
- Visual confirmation of ballot design
(Note: since I don't have basic test coverage for a lot of VxDesign from the prototyping phase, I'm trying to add it as I improve various features. I did that for most of this PR, but ran out of time to cover the contests screen)
=> VxDesign: Primary elections

apps/admin/backend/src/app.results.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/card_counts.test.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/manual_results.test.ts, apps/admin/backend/src/tabulation/manual_results.ts
We already have code to generate ballot counts, but the original use case was only to make the precinct or voting method breakdowns that appear on the reports page. It supported grouping, but not filtering.
We'll be creating a "Ballot Count Report Builder" similar to the "Tally Report Builder," which will require filtering of results. This PR adds that capability to the VxAdmin backend, leaving the frontend untouched for now.
=> admin: Ballot Count Report Builder Backend

apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/frontend/src/pages/print_page.tsx, libs/mark-flow-ui/src/pages/__snapshots__/print_page.test.tsx.snap, libs/mark-flow-ui/src/pages/print_page.tsx, libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap, libs/ui/src/bmd_paper_ballot.test.tsx, libs/ui/src/bmd_paper_ballot.tsx
https://github.com/votingworks/vxsuite/issues/3872
* Adds an optional 1.75in margin to the BMD ballot component so the top of the ballot isn't cut off when presenting the ballot for validation
* Changes the implementation of the print state
* The old implementation triggered the scan state too early. When printing longer ballots, the paper would advance such that `paperInOutput` would return true in the middle of a print, causing the paper to be pulled into the scanner before printing was done.
**Before**
**After**
* Added test to BMD ballot component
=> support a large top margin on bmd_paper_ballot

apps/admin/backend/src/app.ts, apps/admin/backend/src/cast_vote_records.ts, apps/admin/backend/src/legacy_cast_vote_records.test.ts, apps/admin/backend/src/legacy_cast_vote_records.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/types.ts, apps/admin/frontend/src/components/import_cvrfiles_modal.tsx, libs/auth/scripts/mock_card.ts, libs/auth/src/artifact_authentication.test.ts, libs/auth/src/artifact_authentication.ts, libs/auth/src/live_check.ts, libs/backend/src/cast_vote_records/import.ts, libs/backend/src/cast_vote_records/index.ts, libs/utils/src/cast_vote_records.ts, libs/utils/src/filenames.test.ts, libs/utils/src/filenames.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3926
This PR completes the end-to-end wiring of continuous export! It specifically updates VxAdmin to support importing the new CVR export format. The user experience is unchanged by this PR. Just a lot of under-the-hood tweaks.
All of the new logic is feature flag gated. Once I merge this PR, I'll work on pruning the feature flag and old CVR export/import logic.
I've mostly punted on automated tests, which I'll add in follow-up PRs, since this PR is large enough as is.
=> Update VxAdmin to support importing new CVR export format

apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts
Removes the legacy state machine class from paper handler driver. Will conflict with https://github.com/votingworks/vxsuite/pull/3962
Issue: https://github.com/votingworks/vxsuite/issues/3876
No changes to behavior
* Automated tests pass
* QA'd on hardware
=> remove legacy PaperHandlerStateMachine class

apps/admin/backend/src/app.ts, apps/admin/frontend/src/utils/initial_setup_package.ts, apps/design/backend/src/app.ts, libs/backend/src/ballot_package/test_utils.ts, libs/types/src/ballot_package.ts, libs/types/src/ballot_package_metadata.ts, libs/types/src/index.ts, libs/types/src/language_code.ts, libs/types/src/ui_string_audio_clips.test.ts, libs/types/src/ui_string_audio_clips.ts, libs/types/src/ui_string_audio_keys.test.ts, libs/types/src/ui_string_audio_keys.ts, libs/types/src/ui_string_translations.test.ts, libs/types/src/ui_string_translations.ts, libs/utils/src/ballot_package.ts
Related tech spec [here](https://docs.google.com/document/d/1a2GRj1g4aOawEssPdTCgbv-qs28d-M_dyMEfzm4I4nM/edit?usp=sharing).
Adding new types/schemas for translation/audio-related data files we'll be adding to the election package zip file:
- `BallotPackageMetadata`: Will be loaded from `metadata.json` - currently just contains a `version` field which will allow us to verify the ballot package version and the machine build version match up. Wasn't sure if this might make sense to add to the existing `SystemSettings` instead - LMK if you think so.
- `UiStringsPackage`: Per-language string translations for all enabled languages - to be loaded from `appStrings.json` and merged with additional election strings translations from the election CDF.
- `UiStringAudioClips`: List of audio clips, …
=> [libs/types] Add translation/audio schemas to BallotPackage

apps/scan/backend/src/app.ts, apps/scan/backend/src/app_usb_drive.test.ts, apps/scan/backend/src/scanners/custom/app_config.test.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/components/cast_vote_record_sync_modal.test.tsx, apps/scan/frontend/src/components/cast_vote_record_sync_modal.tsx, apps/scan/frontend/src/components/export_results_modal.test.tsx, apps/scan/frontend/src/components/export_results_modal.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, apps/scan/frontend/test/helpers/mock_usb_drive.ts, libs/backend/src/cast_vote_records/export.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3924
Before continuous export, if a USB was removed from a VxScan mid-day, and a different one was connected in its place, say because the original USB failed and was no longer able to mount, no additional action would need to be taken. With continuous export, if a USB is removed mid-day, and a different one is connected in its place, CVRs need to be rewritten to the new USB, i.e. the USB needs CVRs (re)synced. This PR adds code and a UX for this.
In this video, you'll see that I remove a USB and insert another in its place, triggering the (re)sync UX.
https://github.com/votingworks/vxsuite/assets/12616928/a6efc717-e354-4ff7-b66f-9212622cbffe
`libs/backend` tests are coming in a follow-up PR
=> Detect when a newly inserted VxScan USB needs CVRs (re)synced

apps/admin/backend/src/types.ts, libs/types/src/tabulation.ts, libs/ui/src/reports/ballot_count_report.stories.tsx, libs/ui/src/reports/ballot_count_report.test.tsx, libs/ui/src/reports/ballot_count_report.tsx, libs/ui/src/reports/index.ts, libs/utils/src/tabulation/lookups.test.ts, libs/utils/src/tabulation/lookups.ts, libs/utils/src/tabulation/tabulation.test.ts, libs/utils/src/tabulation/tabulation.ts
Adds a `BallotCountReport` component to `libs/ui`, with testing and lots of stories.
@kofi-q in terms of table layout, I ended up getting exactly what I wanted with `grid`. I'm not able to set preferences on _which_ attribute columns to prioritize over others, but I am able to have number rows always fit content, attribute rows usually fit content, and filler rows to expand for appearance.
It's not easy to do through `storybook`, but I confirmed that this prints almost as well as `<table>` when the content stretches across multiple pages.
| Report Description | Screenshot |
| most common expected use case - by precinct | <img width="817" alt="Screen Shot 2023-09-15 at 3 29 41 PM" src="https://github.com/votingworks/vxsuite/assets/37960853/efe03b5d-f504-441 …
=> Ballot Count Report Component

apps/admin/backend/src/cast_vote_records.ts, libs/backend/src/ballot_package/ballot_package_io.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/src/cast_vote_records/import.test.ts, libs/backend/src/cast_vote_records/import.ts, libs/backend/src/cast_vote_records/legacy_export.test.ts, libs/backend/src/cast_vote_records/legacy_export.ts, libs/backend/src/cast_vote_records/legacy_import.test.ts, libs/backend/src/cast_vote_records/legacy_import.ts, libs/cvr-fixture-generator/package.json, libs/cvr-fixture-generator/src/cli/generate/main.test.ts, libs/cvr-fixture-generator/src/cli/generate/main.ts, libs/cvr-fixture-generator/src/generate_cvrs.ts, libs/cvr-fixture-generator/src/utils.ts, libs/cvr-fixture-generator/tsconfig.build.json, libs/cvr-fixture-generator/tsconfig.json, pnpm-lock.yaml
Issue link: https://github.com/votingworks/vxsuite/issues/3890
A very first step in removing old CVR code, this PR updates `libs/cvr-fixture-generator` to use the new CVR export format. In my next PR, I'll actually generate new fixtures and have app tests use them.
This PR also makes various small tweaks to `libs/backend` functions, all geared around prep for removal of old CVR code.
=> Update libs/cvr-fixture-generator to use new CVR export format (plus other small tweaks)

libs/custom-scanner/src/cli/demo/index.ts
We were accidentally writing the image data for `sideA`.
n/a
Tested manually.
=> fix(custom-scanner): write `sideB` to `sideB.pgm`

apps/scan/backend/src/app_results.test.ts, apps/scan/backend/src/app_usb_drive.test.ts, apps/scan/backend/src/scanners/custom/app_config.test.ts, apps/scan/backend/src/scanners/custom/app_scan.test.ts, apps/scan/backend/src/scanners/custom/app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/custom/app_scan_power_off.test.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/backend/test/helpers/shared_helpers.ts, libs/auth/src/artifact_authentication.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/src/cast_vote_records/test_utils.ts, libs/test-utils/src/mock_function.test.ts, libs/test-utils/src/mock_function.ts
VxScan backend tests have gotten quite flaky since my recent merge to enable continuous export by default, without a feature flag. Unsurprisingly, my [rudimentary approach](https://github.com/votingworks/vxsuite/blob/2a1441689e87312d56041930dd8fd8c19ac7ceda/apps/scan/backend/test/helpers/shared_helpers.ts#L137-L146) for waiting for continuous export to finish in tests isn't quite cutting it 😅.
This PR introduces a more robust waiting mechanism. Whenever a CVR export operation starts, we write a hidden `.export-in-progress` file to the USB drive. And when the operation completes, we delete that file. Tests can check for the lack of that file.
I've also combined this mechanism with https://github.com/votingworks/vxsuite/pull/3984 to introduce proper recovery …
=> Decrease VxScan backend test flakiness and introduce proper recovery from failures midway through a CVR export operation

apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/api_machine_configuration.test.tsx, apps/mark/frontend/src/api.ts, apps/mark/frontend/src/api_machine_configuration.test.tsx, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/api_machine_configuration.test.tsx, libs/ui/package.json, libs/ui/src/hooks/ui_strings_api.test.tsx, libs/ui/src/hooks/ui_strings_api.ts, libs/ui/src/index.ts, libs/ui/tsconfig.build.json, libs/ui/tsconfig.json, pnpm-lock.yaml
Related spec [here](https://docs.google.com/document/d/1a2GRj1g4aOawEssPdTCgbv-qs28d-M_dyMEfzm4I4nM/edit?usp=sharing).
- Adding shared `react-query` frontend client for the shared UI Strings backend API.
- Only implementing `getAvailableLanguages()` for now and will flesh out over time
- Exporting an instance of the shared API in each frontend for use in components.
- Also triggering the included `onMachineConfigurationChange` whenever a configure or unconfigure mutation happens.
- Added libs/ui unit tests for the shared API logic.
- Added app frontend unit tests to verify `onMachineConfigurationChange` is being triggered appropriately.
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates …
=> [libs/ui] Shared UI Strings API react-query client

apps/admin/backend/jest.config.js, apps/admin/backend/src/app.ballot_count_report_csv_export.test.ts, apps/admin/backend/src/app.tally_report_csv_export.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/exports/csv_ballot_count_report.test.ts, apps/admin/backend/src/exports/csv_ballot_count_report.ts, apps/admin/backend/src/exports/csv_results.ts, apps/admin/backend/src/exports/csv_shared.ts, apps/admin/backend/src/exports/csv_tally_report.test.ts, apps/admin/backend/src/exports/csv_tally_report.ts, apps/admin/backend/src/types.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/components/reporting/export_csv_button.test.tsx, apps/admin/frontend/src/components/reporting/export_csv_button.tsx, apps/admin/frontend/test/helpers/mock_api_client.ts, libs/types/src/tabulation.ts, libs/ui/src/reports/ballot_count_report.test.tsx, libs/ui/src/reports/ballot_count_report.tsx
_review by commit_
Closes #3990. Does not expose the new feature on the frontend, but adds the backend capability to generate a ballot count report CSV and save it to the USB drive.
100% automated coverage
=> Ballot Count Report CSV

libs/ui/.storybook/preview.tsx, libs/ui/src/app_base.tsx, libs/ui/src/fonts/load_fonts.tsx
Came up in https://github.com/votingworks/vxsuite/pull/4022 that we could end up with multiple instances of our font declarations in dev (due to [react dev quirks in strict mode](https://github.com/votingworks/vxsuite/pull/4022) and/or HMR).
- Adding an `unloadFonts()` cleanup step to make sure we only have one copy of the fonts installed.
- Also wrapping Storybook preview in `<React.StrictMode>` to mirror what we do in our apps.
- Manual
- ~[ ] I have added the "user_facing_change" label to this PR to …
=> [libs/ui] Maintain only one instance of Vx fonts across re-mounts

apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.test.tsx, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.test.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx
Currently, if you create a combination of filters and group by clauses in a report builder such that there are no results at all, the report viewing area will just be blank. Although this should be rare, I wanted to add in some sort of warning text in this situation so a user does not think the app is broken. Examples where this might show up:
1) User tries to "group by batch" but no CVRs are loaded. There are no batches, so nothing to group by.
2) User creates an impossible filter (e.g. filtering for ballots associated with the democratic party but with republican ballot styles) and applies a grouping
This does not apply in some cases. For example, imagine a case (3) in which you set up an impossible filter as in example (2) but _do not_ have a grouping - you'll just get a zero or blank …
=> feat(admin): Add "No Results" Warning to Report Builders

apps/scan/backend/jest.config.js, apps/scan/backend/src/scanners/custom/app_config.test.ts, apps/scan/backend/test/helpers/custom_helpers.ts
VxScan backend tests are still a little bit flaky, even after https://github.com/votingworks/vxsuite/pull/4009. One issue in particular has been around for a while:
<table>
</table>
Looks like tests can rapidly hop from the `accepted` state to the `no_paper` state, such that checks for the `accepted` state fail, even though we do pass through that state. This PR increases the delay in the default test state machine to ensure that we don't "miss" the `accepted` state.
This PR also bumps a timeout for an expectedly long running test and drops the code coverage threshold. There seems to be an element of randomness involved in how much code VxScan backend tests cover - we sometimes fall below the current thresholds, even when all tests succeed.
=> More flaky test fixes

libs/backend/src/ui_strings/ui_strings_api.ts, libs/backend/src/ui_strings/ui_strings_api_test_runner.ts, libs/types/src/ui_strings_api.ts, libs/ui/src/hooks/ui_strings_api.test.tsx, libs/ui/src/hooks/ui_strings_api.ts
Wiring up a `getUiStrings` react-query client API to the backend store for future use with our string translation library.
Also updating the nullable return types in the API from `Optional<T>` to `T | null`, since react-query doesn't like `undefined` query data values.
- Updated backend and frontend API tests
=> [i18n/audio] Pipe data through to getUiStrings react-query client

apps/admin/backend/src/app.cvr_files.test.ts, apps/admin/backend/src/app.ts, apps/admin/frontend/src/components/import_cvrfiles_modal.tsx, apps/admin/frontend/src/components/save_backend_file_modal.tsx, apps/central-scan/backend/src/central_scanner_app.ts, apps/central-scan/frontend/src/components/export_results_modal.test.tsx, apps/central-scan/frontend/src/components/export_results_modal.tsx, apps/central-scan/frontend/src/screens/admin_actions_screen.test.tsx, apps/central-scan/frontend/src/screens/admin_actions_screen.tsx, apps/scan/backend/src/app.ts, apps/scan/frontend/src/components/export_results_modal.test.tsx, apps/scan/frontend/src/components/export_results_modal.tsx, libs/backend/src/cast_vote_records/build_cast_vote_record.ts, libs/backend/src/cast_vote_records/canonicalize.test.ts, libs/backend/src/cast_vote_records/canonicalize.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/src/exporter.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/src/log_documentation.test.ts, libs/logging/src/log_event_ids.ts, libs/types/src/cast_vote_records.ts, libs/types/src/errors.ts, libs/ui/src/cast_vote_records.test.ts, libs/ui/src/cast_vote_records.ts, libs/ui/src/index.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3917
This PR handles miscellaneous continuous-export / CVR-related cleanup. Most notably, it:
- Cleans up CVR-related logging, consistently handling this logging in app backends
- No longer has backends prepare UI copy and shifts this logic to frontends
=> Clean up CVR-related logging and no longer have backends prepare UI copy

apps/admin/backend/src/app.cvr_files.test.ts, apps/admin/backend/src/store.ts
Both @carolinemodic and I recently stumbled across the following unexpected edge case behavior in the VxAdmin CVR import flow. If you try to import a file that's not a perfect duplicate of another but also contains no new CVRs, you first see a message indicating that the import was successful but that no new CVRs were added, which is expected. What's unexpected is that you can then still try to import the export again. And on the second import attempt, you see a different message, indicating that the export is a duplicate. Ideally, after the first import attempt, you shouldn't be able to import the export again.
The bug fix ended up being a 1-word addition to a SQL query 😅. As Beyonce once famously said, "to the **left**" (join).
_Before_ 😢 …
=> Properly handle CVR exports that aren't perfect duplicates of another but also contain no new CVRs

libs/backend/src/cast_vote_records/import.ts, libs/types/src/hmpb.test.ts, libs/types/src/hmpb.ts
We fairly often have data for a single sheet spread across multiple tuples rather than nested within a single tuple. To make this easier to work with, `mapSheet` now accepts multiple `SheetOf` values and spreads the pages from each in the call to the provided function.
```ts
expect(mapSheet([1, 2], [3, 4], (x, y) => x + y)).toEqual([4, 6]);
```
Automated.
=> refactor: use `mapSheet` with split sheet data

libs/ballot-interpreter/src/hmpb-rust/js/mod.rs
This has been a `clippy` lint for quite some time, but I thought it was a bug in `clippy`. Turns out you can use `Debug` formatting with inline variables too.
n/a
Automated.
=> style(ballot-interpreter): use variable directly

libs/auth/package.json, libs/auth/src/apdu.test.ts, libs/auth/src/apdu.ts, pnpm-lock.yaml
We were not validating:
- that the encoded tag is the one we expected
- that the first length byte is ≤ 0x80 if it isn't one of the special 0x81 or 0x82 values
- that the TLV response didn't contain more data than the length said it should
See [Slack discussion](https://votingworks.slack.com/archives/CEL6D3GAD/p1696958808975429).
n/a
Automated, manually tested that programming a sysadmin card and using it in VxScan still works.
=> fix(auth): do more validation of TLV messages

apps/mark-scan/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark-scan/frontend/src/components/display_settings_button.tsx, apps/mark-scan/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark-scan/frontend/src/pages/__snapshots__/start_page.test.tsx.snap, apps/mark-scan/frontend/src/pages/contest_page.tsx, apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/components/display_settings_button.tsx, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark/frontend/src/pages/__snapshots__/start_page.test.tsx.snap, apps/mark/frontend/src/pages/contest_page.tsx, libs/mark-flow-ui/src/components/__snapshots__/contest.test.tsx.snap, libs/mark-flow-ui/src/components/__snapshots__/yes_no_contest.test.tsx.snap, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/contest_header.tsx, libs/mark-flow-ui/src/components/ms_either_neither_contest.tsx, libs/mark-flow-ui/src/components/yes_no_contest.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/election_strings.test.tsx, libs/ui/src/ui_strings/election_strings.tsx, libs/ui/src/ui_strings/index.ts, libs/ui/src/ui_strings/ui_string.tsx
_Easier by commit_
Adding `@votingworks/ui/appStrings` and `@votingworks/ui/electionStrings` shared string component renderers (building off `<UiString>`) and starting off with a few proof-of-concept strings to try out different usage patterns.
Replacing a few strings on the `CandidateContest` pages in `Mark` and `Mark-Scan`.
https://github.com/votingworks/vxsuite/assets/264902/aaee2716-ddc2-4f62-b6c7-a80358c11958
- Manual: populated the DB with test translations and added the `UiStringContextProvider` to the app root of `Mark` to verify functionality. Using a stand-in language picker for testing until we have an actual voter-facing component.
- Added unit tests for the …
=> [i18n/audio] Replace a few strings in Mark[-Scan] with language-aware versions

libs/usb-drive/src/usb_drive.test.ts, libs/usb-drive/src/usb_drive.ts
VSAP has two "devices" which are causing problems:
- a USB partition acting as / formatted as an LVM (logical volume manager). we can disallow this by skipping drives which have a filesystem type of "LVM." There's no documentation I can find on a proper enumeration of all file types, so I'm simply excluding file systems which include "LVM" in the name
-  "logical volume" that is part of that LVM. this is easy to exclude, because we can limit our search to proper partitions
=> VSAP USB Drive Hotfix

apps/mark/frontend/src/app_cardless_voting.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/components/__snapshots__/election_info.test.tsx.snap, apps/mark/frontend/src/components/election_info.test.tsx, apps/mark/frontend/src/components/election_info.tsx, apps/mark/frontend/src/pages/__snapshots__/start_page.test.tsx.snap, apps/mark/frontend/src/pages/start_page.test.tsx, apps/mark/frontend/src/pages/start_page.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/types/src/ui_string_translations.ts, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/date_string.test.tsx, libs/ui/src/ui_strings/date_string.tsx, libs/ui/src/ui_strings/election_strings.tsx, libs/ui/src/ui_strings/index.ts, libs/ui/src/ui_strings/number_string.test.tsx, libs/ui/src/ui_strings/number_string.tsx, libs/ui/src/ui_strings/utils.test.tsx, libs/ui/src/ui_strings/utils.tsx, libs/utils/src/extract_cdf_ui_strings.test.ts, libs/utils/src/extract_cdf_ui_strings.ts, libs/utils/src/format.test.ts, libs/utils/src/format.ts, libs/utils/src/precinct_selection.ts
_Easier by commit_
Fleshing out `@votingworks/ui/electionStrings` to include all the translatable/spoken strings in the election definition so far.
Making the `VxMark` `StartPage` language-aware to test out the new election strings, which led to adding support for number and date i18n -- the audio piece of that is going to require a bit more planning and coordination with the VxDesign work, so I'll start writing up some thoughts in the spec.
- Also, to avoid audio interpolation, the previous `"Your ballot contains x contests."` string is now `"Number of contests on your ballot: x"`
https://github.com/votingworks/vxsuite/assets/264902/481d65a7-4c80-4d98-bcdd-3794d9613fca …
=> [i18n/Audio] Adding renderers and helpers for remaining election strings

apps/admin/backend/src/app.ballot_count_report_csv_export.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/exports/csv_ballot_count_report.test.ts, apps/admin/backend/src/exports/csv_ballot_count_report.ts, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.test.tsx, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx, apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.test.tsx, apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.tsx, apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.test.tsx, apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.tsx, apps/admin/frontend/src/screens/reporting/precinct_ballot_count_report_screen.tsx, apps/admin/frontend/src/screens/reporting/voting_method_ballot_count_report_screen.tsx, apps/admin/frontend/test/helpers/mock_api_client.ts, libs/types/src/tabulation.ts, libs/ui/src/reports/ballot_count_report.stories.tsx, libs/ui/src/reports/ballot_count_report.test.tsx, libs/ui/src/reports/ballot_count_report.tsx
@mattroe and I discussed how our policy with manual results is that we _always_ show them separately on reports where they contribute to the overall ballot count or vote count. This is what we do for the tally reports - if there are any manual results, the reports flip to show manual counts.
When I built the ballot count reporting (PDF and CSV), I included options to show the ballot count breakdown differently. 'none' would never show manual counts, and 'manual' would always show manual counts. This is in violation of our decided policy.
In this PR, I simply remove the idea the ballot count breakdown as an editable feature - it is always the maximal option - BMD, HMPB, Total and, if applicable, Manual.
=> Manual Counts Policy - Ballot Count Reporting

apps/admin/backend/src/app.tally_report_csv_export.test.ts, apps/admin/backend/src/app.tally_reports.test.ts, apps/admin/backend/src/exports/batch_results.test.ts, apps/admin/backend/src/exports/batch_results.ts, apps/admin/backend/src/exports/csv_tally_report.test.ts, apps/admin/backend/src/exports/csv_tally_report.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/tabulation/full_results.ts, apps/admin/backend/src/tabulation/write_ins.test.ts, apps/admin/backend/src/tabulation/write_ins.ts, apps/admin/integration-testing/e2e/reports.spec.ts-snapshots/viewing-and-exporting-reports-1-chromium-linux.dat, libs/types/src/election.ts, libs/types/src/tabulation.ts, libs/utils/src/compressed_tallies.test.ts, libs/utils/src/compressed_tallies.ts, libs/utils/src/tabulation/index.ts, libs/utils/src/tabulation/tabulation.test.ts, libs/utils/src/tabulation/tabulation.ts, libs/utils/src/tabulation/tally_reports.test.ts, libs/utils/src/tabulation/tally_reports.ts, libs/utils/src/votes.test.ts, libs/utils/src/votes.ts
_review by commit, there's a refactor and bug fix in the log_
Closes #4069 alongside #4073. Updates the tally CSV exports so that they split manual and scanned results.
N/A, example file attached:
[TEST-full-election-tally-report__2023-10-23_13-11-49.csv](https://github.com/votingworks/vxsuite/files/13078796/TEST-full-election-tally-report__2023-10-23_13-11-49.csv)
=> Manual Tally Policy - CSV Tally Reports

libs/fixtures/data/electionGridLayoutNewHampshireAmherst/castVoteRecords/manual/864a2854-ee26-4223-8097-9633b7bed096/cast-vote-record-report.json
While testing write-in adjudication, @adghayes identified an inconsistency in our one manually created CVR fixture. All the `WriteInImage` fields reference the front image, but two of the contests with write-ins are actually on the back of the ballot and should reference the back image.
Our actual CVR export logic is doing the right thing. The reason this fixture has an issue is because I recently modified it by hand to use the new CVR export format and made a human error 🙈.
=> Fix manually created CVR fixture

apps/scan/backend/src/app_config.test.ts, libs/auth/README.md, libs/auth/jest.config.js, libs/auth/src/apdu.test.ts, libs/auth/src/apdu.ts, libs/auth/src/cac/common_access_card_api.ts, libs/auth/src/card.ts, libs/auth/src/index.ts, libs/auth/src/integration_test_utils.ts, libs/auth/src/piv.test.ts, libs/auth/src/piv.ts, libs/backend/jest.config.js, libs/backend/package.json, libs/backend/src/cast_vote_records/build_cast_vote_record.test.ts, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/src/cast_vote_records/file_system_utils.test.ts, libs/backend/src/cast_vote_records/file_system_utils.ts, libs/backend/src/cast_vote_records/test_utils.ts, libs/backend/test/fixtures/interpretations.ts, libs/backend/test/utils.ts, libs/types/src/byte.ts, libs/usb-drive/src/mocks/memory_usb_drive.ts, pnpm-lock.yaml
Issue link: https://github.com/votingworks/vxsuite/issues/4058
Finally adding the tests that I've punted on for so so long. This PR gets the new CVR export functions in `libs/backend` up to 💯% code coverage. I'll be opening a separate PR for the new CVR import functions.
=> Get the new CVR export functions in libs/backend up to 100% code coverage

libs/backend/jest.config.js, libs/backend/package.json, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/import.test.ts, libs/backend/src/cast_vote_records/import.ts, libs/types/src/cast_vote_records.ts, pnpm-lock.yaml
Issue link: https://github.com/votingworks/vxsuite/issues/4058
The counterpart to https://github.com/votingworks/vxsuite/pull/4090, this PR gets the new CVR import functions in `libs/backend` up to 💯% code coverage. It also adds one e2e test of export and subsequent import of that export.
=> Get the new CVR import functions in libs/backend up to 100% code coverage

.circleci/config.yml, libs/monorepo-utils/src/circleci.ts
In the event we rename `ballot-interpreter` or add any other Rust addons this will ensure everything is set up properly.
n/a
Automated.
=> ci: build any/all rust addons during setup

apps/admin/backend/src/app.tally_reports.test.ts, apps/admin/backend/src/exports/csv_tally_report.ts, apps/admin/backend/src/tabulation/tally_reports.ts, apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, libs/ui/jest.config.js, libs/ui/src/reports/admin_tally_report.stories.tsx, libs/ui/src/reports/contest_results_table.test.tsx, libs/ui/src/reports/contest_results_table.tsx, libs/utils/src/tabulation/tally_reports.test.ts, libs/utils/src/tabulation/tally_reports.ts
Closes #4014. Updates tally reports such that contest tables include significant tallies for write-in candidates. Insignificant write-ins are shown as "Other Write-In" or "Write-In." It works by adding the WIA candidates with the most votes until it is clear from the table who the winners are (the "Other Write-In" category is smaller than the winners).
Added automated testing of algorithm and its appearance in reports. Manually tested full flow with a robust data set to confirm it performs end-to-end, in a variety of WIA situations.
=> Show Significant Write-Ins in Tally Reports

apps/scan/backend/src/app_config.test.ts
test is being flaky with a confusing error message ([example](https://app.circleci.com/pipelines/github/votingworks/vxsuite/12630/workflows/f3c18897-8403-4dc0-b88c-8afd281142d7/jobs/427840)), but i'm guessing it's just due to test timeout. bumping
=> bump continuous export test timeout

apps/admin/frontend/src/components/election_manager.tsx, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx, apps/admin/frontend/src/components/reporting/shared.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx, apps/admin/frontend/src/screens/reporting/all_precincts_tally_report_screen.tsx, apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.tsx, apps/admin/frontend/src/screens/reporting/full_election_tally_report_screen.tsx, apps/admin/frontend/src/screens/reporting/precinct_ballot_count_report_screen.tsx, apps/admin/frontend/src/screens/reporting/single_precinct_tally_report_screen.tsx, apps/admin/frontend/src/screens/reporting/tally_report_builder.tsx, apps/admin/frontend/src/screens/reporting/voting_method_ballot_count_report_screen.tsx, apps/admin/frontend/src/screens/reporting/write_in_adjudication_report_screen.test.tsx, apps/admin/frontend/src/screens/reporting/write_in_adjudication_report_screen.tsx, apps/admin/frontend/src/screens/write_in_adjudication_report_screen.test.tsx, apps/admin/frontend/src/screens/write_in_adjudication_report_screen.tsx
review by commit
Closes #4071. During the reporting revamp, all the report pages got a new look. Except the WIA report page. This PR makes it look similar to the other pages.
Manually tested print and PDF export to confirm refactor didn't break anything.
=> WIA Report Page Styling

apps/admin/frontend/src/screens/manual_data_summary_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.tsx
this was a temporary restriction during the state transition. #4046 was supposed to be a fix, but missed another place that the ballot style was hardcoded. this removes the hardcoding and adds regression testing
=> fixup #4046: Ability to Add Absentee Manual Results 

libs/utils/src/extract_cdf_ui_strings.test.ts, libs/utils/src/extract_cdf_ui_strings.ts
Adding CDF string extractors for a few more election strings.
Leaving out `precinctName` and `districtName` for now, since I need to get clarification on some specifics first.
- Unit test coverage
=> [i18n/audio] Add more CDF election string extractors

apps/admin/backend/src/app.tally_reports.test.ts, apps/admin/backend/src/exports/csv_shared.ts, apps/admin/backend/src/exports/csv_tally_report.test.ts, apps/admin/backend/src/exports/csv_tally_report.ts, apps/admin/backend/src/tabulation/card_counts.test.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/manual_results.test.ts, apps/admin/backend/src/tabulation/manual_results.ts, apps/admin/backend/src/tabulation/tally_reports.ts, apps/admin/backend/src/types.ts, apps/admin/frontend/src/utils/reporting.test.ts, apps/admin/frontend/src/utils/reporting.ts, libs/types/src/tabulation.ts, libs/ui/src/reports/ballot_count_report.test.tsx, libs/ui/src/reports/ballot_count_report.tsx, libs/ui/src/reports/custom_filter_summary.tsx, libs/ui/src/reports/utils.ts
Closes #4116. Currently, when you group by batch or scanner in the report builders, manual results are just silently dropped. This PR starts including them.
In tally reports, they end up on a separate page:
If the filters are too specific, it will be called "Manual" in the custom filter description:
In ballot count reports, they are separated into different rows:
In the CSV exports, they are represented by a placeholder ID in separate rows:
Updated testing across the board to account, manually tested.
=> admin(feat): include manual results when grouping by scanner or batch

libs/types/src/cdf/ballot-definition/convert.ts, libs/utils/src/extract_cdf_ui_strings.test.ts, libs/utils/src/extract_cdf_ui_strings.ts
Adding CDF string extractors for the last couple remaining election strings.
- Added unit test coverage
=> [i18n/audio] Add CDF string extractors for precinct/district names

apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_tally_report_paths.test.tsx, libs/ui/src/reports/precinct_scanner_ballot_count_report.test.tsx, libs/ui/src/reports/precinct_scanner_report_header.test.tsx, libs/ui/src/reports/precinct_scanner_report_header.tsx, libs/ui/src/reports/precinct_scanner_tally_report.test.tsx, libs/ui/src/reports/precinct_scanner_tally_reports.test.tsx
As we standardize report naming in VxAdmin (see #4122), we [agreed](https://votingworks.slack.com/archives/CEL6D3GAD/p1698179698723679) that we should be careful with the word "Official" and it shouldn't appear on VxScan reports.
=> VxScan: remove "Official" label from reports

libs/ui/src/__snapshots__/loading.test.tsx.snap, libs/ui/src/__snapshots__/progress_ellipsis.test.tsx.snap, libs/ui/src/progress_ellipsis.tsx
I've been spending lots of time looking at CVR import/export modals, and I recently noticed that the dots in the ellipsis animation are getting clipped. It just occurred to me that our recent font change 🤖 is probably responsible.
_Before_
https://github.com/votingworks/vxsuite/assets/12616928/81d9c958-da53-4b8e-a347-5aa9f27c31c7
_After :tada:_
https://github.com/votingworks/vxsuite/assets/12616928/3f15f8a5-2885-4c31-a7e7-f988908b357c
=> Update loading ellipsis animation to account for font change

apps/mark-scan/frontend/src/app.tsx, apps/mark-scan/frontend/src/index.tsx, apps/mark/frontend/src/app.tsx, apps/mark/frontend/src/index.tsx, apps/scan/frontend/src/app.tsx, apps/scan/frontend/src/index.tsx, libs/ui/src/ui_strings/ui_strings_context.test.tsx, libs/ui/src/ui_strings/ui_strings_context.tsx, libs/ui/test/ui_strings/test_utils.tsx
Installing the shared `UiStringContextProvider` in `Vx[Scan|Mark|Mark-Scan]` to connect `<UiString>` instances to the backend API.
Only enabling the context provider for dev/prod app instances (and integration tests) and leaving it disabled for the functional jest tests, since it was going to be too much unnecessary overhead to add mock versions of the UiString API endpoints and set up expectations in all existing tests that render the root `<App>` component directly.
- Unit test coverage for the added conditional provider installation
- Planning on following up later integration test coverage to verify e2e functionality from configuration through changing languages, …
=> [i18n/audio] Install UiStringContextProvider in voter-facing apps

apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/mark_official_button.test.tsx, apps/admin/frontend/src/components/mark_official_button.tsx, apps/admin/frontend/src/screens/reporting/full_election_tally_report_screen.test.tsx, apps/admin/frontend/src/screens/reporting/full_election_tally_report_screen.tsx, apps/admin/frontend/src/screens/reporting/reports_screen.tsx, apps/admin/integration-testing/e2e/reports.spec.ts
Closes #4072. I moved the button from the Full Election Tally Report page to the Reports page. 
I also changed the language from "Mark Tally Results as Official" to "Mark Election Results as Official" because that made more sense to me, "tally results" seems a bit redundant and unfamiliar.
https://github.com/votingworks/vxsuite/assets/37960853/20f5205a-ee7a-4d38-b652-7edbd093468f
https://github.com/votingworks/vxsuite/assets/37960853/f6a128fd-c733-4aff-a8cc-bcf28e218180
=> Move Mark Official Button

apps/admin/frontend/src/components/admin_tally_report_by_party.test.tsx, apps/admin/frontend/src/components/admin_tally_report_by_party.tsx, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx, apps/admin/frontend/src/components/test_deck_tally_report.tsx, apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.test.tsx, apps/admin/frontend/src/screens/reporting/tally_report_builder.test.tsx, apps/admin/frontend/src/screens/reporting/write_in_adjudication_report_screen.test.tsx, apps/admin/frontend/src/screens/reporting/write_in_adjudication_report_screen.tsx, libs/ui/src/reports/admin_tally_report.stories.tsx, libs/ui/src/reports/admin_tally_report.test.tsx, libs/ui/src/reports/admin_tally_report.tsx, libs/ui/src/reports/ballot_count_report.stories.tsx, libs/ui/src/reports/ballot_count_report.test.tsx, libs/ui/src/reports/ballot_count_report.tsx, libs/ui/src/reports/utils.ts, libs/ui/src/reports/write_in_adjudication_report.stories.tsx, libs/ui/src/reports/write_in_adjudication_report.test.tsx, libs/ui/src/reports/write_in_adjudication_report.tsx
Part of #4112. Currently VxAdmin reports do not show "Test" on reports when they represent test data. We definitely want them to!
=> Prefix VxAdmin Printed Reports w/ "Test" for Test Results

apps/admin/backend/src/app.cvr_files.test.ts, apps/admin/backend/src/cast_vote_records.ts, apps/admin/backend/test/app.ts, apps/admin/integration-testing/e2e/reports.spec.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/src/cast_vote_records/test_utils.ts
Part of #3935. See [discussion](https://votingworks.slack.com/archives/CEL6D3GAD/p1693940716686119). Instead of exporting CVRs to a path (relative to USB drive) of `./cast-vote-records/election-XXXXXXXX`, export to `./election-XXXXXXXX/cast-vote-records`.
=> CVR Subdirectory Structure

apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx, apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.test.tsx, apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.tsx, apps/admin/frontend/src/components/reporting/export_tally_report_csv_button.test.tsx, apps/admin/frontend/src/components/reporting/export_tally_report_csv_button.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx, apps/admin/frontend/src/screens/reporting/write_in_adjudication_report_screen.tsx, apps/admin/frontend/src/utils/reporting.test.ts, apps/admin/frontend/src/utils/reporting.ts, libs/utils/src/filenames.ts
By commit...
1. refactor to maintain "test" prefix more consistent across repo
2. adds "official" or "unofficial" to report files exported from VxAdmin
3. standardizes WIA .pdf export filename to match the others.
=> VxAdmin Polish: file export naming

apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/layout.tsx, apps/design/frontend/src/tabulation_screen.tsx, libs/ui/src/card.tsx
Adapts the Card component for use in desktop apps. Currently it was only used in one place: the VxMark review screen, so it was a pretty easy change.
Then replaces the makeshift Card component in VxDesign with the libs/ui component.
Before
After
Automated tests, visual confirmation
=> Desktop theme Card

apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/pages/validate_ballot_page.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/review.test.tsx, libs/mark-flow-ui/src/components/review.tsx, libs/mark-flow-ui/src/pages/review_page.tsx, libs/types/src/election.ts, libs/types/src/election_utils.ts, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/election_strings.tsx, libs/ui/src/voter_contest_summary.stories.tsx, libs/ui/src/voter_contest_summary.tsx, libs/ui/src/with_scroll_buttons.tsx
Replacing strings shown on the ballot review pages in Mark/Mark-Scan with language-aware `<UiString>` versions.
Updated the undervote count warning text as described [here](https://docs.google.com/document/d/1xtt5q1Pet5j1RHVsduvOcRGrqDkGspFeKhKc1aVscKE/edit?usp=sharing), in order to avoid interpolated audio.
|  |  |
|  ![Screenshot 2023-10-30 at 14 53 14](https://github.com/votingworks/vxsuite/assets/264902/50297448-2d54-49af-9511-74f9ea19e2e4) | ![Screenshot 2023-10-30 at 15 09 37](https://github.com/votingworks/vxsuite/assets/264902/5ece5319-0574-4c09-99c6-bca36156157a) |
- Manually testing out translated text for now - integration tests and lint checks later down the line
- Existing tests as regression guards …
=> [mark-flow-ui] Use language-aware strings on ballot review page

apps/mark-scan/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark-scan/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap, apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap, libs/mark-flow-ui/src/components/__snapshots__/contest.test.tsx.snap, libs/mark-flow-ui/src/components/candidate_contest.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/index.ts
Replacing the vote counter strings in the header of the BMD contest screens with non-interpolated alternatives (see [string updates doc](https://docs.google.com/document/d/1xtt5q1Pet5j1RHVsduvOcRGrqDkGspFeKhKc1aVscKE/edit#heading=h.sh408d16sc6) for more context).
This simplifies translation/text-to-speech as well as our audio playback logic.
https://github.com/votingworks/vxsuite/assets/264902/e220b344-db32-484a-aee3-237aeb757f6f
- Added unit tests to verify counter updates based on selected votes.
- Manual verification for string translation for now
=> [mark-flow-ui] Remove app strings with interpolated values

apps/admin/backend/src/app.ts, apps/central-scan/backend/src/end_to_end_hmpb.test.ts, apps/central-scan/integration-testing/e2e/configuration.spec.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/test/app_helpers.ts, apps/mark/backend/src/app.test.ts, apps/mark/backend/test/app_helpers.ts, apps/mark/integration-testing/e2e/scroll_buttons.spec.ts, apps/scan/backend/src/app_config.test.ts, apps/scan/backend/test/helpers/shared_helpers.ts, apps/scan/frontend/src/config/globals.ts, libs/backend/src/ballot_package/ballot_package_io.test.ts, libs/backend/src/ballot_package/ballot_package_io.ts, libs/backend/src/ballot_package/test_utils.ts, libs/backend/src/cast_vote_records/test_utils.ts, libs/backend/src/ui_strings/ui_strings_machine_configuration_test_runner.ts, libs/utils/src/filenames.test.ts, libs/utils/src/filenames.ts
Closes #3935. Previously, ballot packages would be exported to a USB drive like so:
```./ballot-packages/sample-county_example-primary-election_06414087b1__2023-10-30_12-57-46.zip```
Now, we export them like this:
```./sample-county_example-primary-election_06414087b1/ballot-packages/ballot-package__2023-10-30_12-56-55.zip```
This means that all of our in-system files are being exported in the same way, to a top-level election directory, a file type subdirectory, then a filename. I kept `ballot-package` in the file name for the ballot package so that it wouldn't be _just_ a date if it got out of context. Could add file hash in too if desirable.
- updated automated testing, added a test
- manually tested exporting from VxAdmin and loading into VxMark
=> change ballot package location on USB

libs/backend/src/ballot_package/test_utils.ts, libs/backend/src/ui_strings/ui_strings_api.ts, libs/backend/src/ui_strings/ui_strings_api_test_runner.ts, libs/backend/src/ui_strings/ui_strings_machine_configuration.ts, libs/backend/src/ui_strings/ui_strings_machine_configuration_test_runner.ts, libs/backend/src/ui_strings/ui_strings_machine_deconfiguration_test_runner.ts, libs/backend/src/ui_strings/ui_strings_store.ts, libs/utils/src/ballot_package.test.ts, libs/utils/src/ballot_package.ts
_Related tech spec [here](https://docs.google.com/document/d/1a2GRj1g4aOawEssPdTCgbv-qs28d-M_dyMEfzm4I4nM/edit?usp=sharing)._
Piping data from the `uiStringAudioIds.json` ballot package file through to the app backend DB and exposing via the `getUiStringAudioIds()` API.
This file contains mappings from UI string keys to audio clip IDs for each supported language in a given election.
- Added test cases for parsing the file, loading it into the DB and fetching via the API.
- ~[ ] I have added the …
=> [i18n/Audio] Wire up UI String audio IDs store and API

libs/auth/README.md, libs/auth/src/apdu.ts, libs/auth/src/artifact_authentication.test.ts
Issue link: https://github.com/votingworks/vxsuite/issues/4100
I'd previously mocked `safeParseJson` in artifact authentication tests to avoid having to prepare a complete `CastVoteRecordExportMetadata` object. But my original mock of `safeParseJson` was incorrect and masked a bug (the mock expected an object, but the real `safeParseJson` expects a string) . The mock has since been fixed, but this PR takes things one step further to prevent future mistakes and mocks the `CastVoteRecordExportMetadata` Zod schema instead.
=> Avoid completely mocking safeParseJson in artifact authentication tests

libs/mark-flow-ui/src/components/review.test.tsx, libs/mark-flow-ui/src/components/review.tsx
This got broken in a rebase as identified here: https://github.com/votingworks/vxsuite/pull/4144#discussion_r1377166409. I also fixed the DOM nesting warning for nested buttons while I was at it.
For some reason that I couldn't figure out, the automated test passes even with this bug. It seems like the onPress event from the Change button bubbles up successfully in the test DOM, but not in the actual DOM. I couldn't figure out any way to make the test fail, so I gave up.
Instead, manually tested and confirmed that the tabbing/screen reader still works.
=> Bugfix: Fix VxMark review screen Change button

libs/ui/src/reports/ballot_count_report.tsx
Would close #4021.
The ballot count reports are row striped for readability. But on print, the rows show up a lot lighter than in digital documents. Or it's possible it's due the screen I use in development.
Anyway, here I make the rows darker for print, which doesn't affect the previews but does affect the printed and exported PDFs. 
It is worth noting that the architecture we want is where a PDF is generated on the backend and that is what is shown to the frontend, so there's no difference between printed and previewed styles... but I'll worry about that once we get there. Setting the shading to the midpoint of these two colors would have also been fine, if not quite as tuned.
=> make row striping darker for print

libs/ui/src/button.test.tsx, libs/ui/src/button.tsx, libs/ui/src/segmented_button.test.tsx, libs/ui/src/segmented_button.tsx
Updates SegmentedButton to work with the desktop theme.
This required also tweaking Button, which previously rendered all disabled buttons with the same background in the touchscreen theme. This doesn't work well for segmented buttons, which need to show which button is selected even when disabled. So I nixed that and removed the background color changes for disabled buttons in touchscreen themes.
https://github.com/votingworks/vxsuite/assets/530106/ff3f4410-44fe-407f-a57a-50edbf23d59c
Updated existing automated tests
=> Desktop SegmentedButton

apps/admin/frontend/package.json, apps/central-scan/frontend/package.json, apps/design/backend/package.json, apps/design/backend/schema.sql, apps/design/backend/src/store.test.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/index.ts, apps/design/backend/src/worker/worker.ts, apps/mark-scan/frontend/package.json, apps/mark/frontend/package.json, apps/scan/frontend/package.json, libs/auth/src/cryptography.end_to_end.test.ts, script/src/run-dev/index.ts
This PR adds scaffolding for VxDesign background task processing, something that we need for cloud translation and audio clip generation but that could also prove useful for ballot generation, which is likely to become more time consuming as we build additional VxDesign functionality.
Everything is running locally, but I'm designing things to make the eventual transition to a Heroku deployment as easy as possible. I'm accordingly 1) running the background worker in its own process separate from the backend server process and 2) mimicking the DB schema that Arlo uses for background task processing.
Here, I'm having the election-creation endpoint kick off a no-op job:
https://github.com/votingworks/vxsuite/assets/12616928/7c09d907-b680-4c3d-bfef-65bd5a3d74dd
=> Add scaffolding for VxDesign background task processing

libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/election_info.tsx, libs/mark-flow-ui/src/components/review.tsx, libs/ui/src/ui_strings/app_strings.test.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/date_string.tsx, libs/ui/src/ui_strings/number_string.tsx
Removing `appStrings.[date|number]` in favour of using `<NumberString>` and `<DateString>` directly.
Also enabled adding a stop-gap unit test to enforce matching object keys and `uiStringKey`s.
=> [libs/ui] Remove appStrings.[date|number]

libs/mark-flow-ui/src/pages/cast_ballot_page.tsx, libs/mark-flow-ui/src/pages/print_page.tsx, libs/ui/src/ui_strings/app_strings.tsx
Converting voter-facing strings on the `CastBallotPage` and `PrintPage` screens in `Mark` and `Mark-Scan` to `<UiString>`s
Removing redundant `aria-label`s and deprecated `<Prose>` elements along the way.
https://github.com/votingworks/vxsuite/assets/264902/d8fa56d5-a016-4f1a-a573-33e0e75a8e6f
https://github.com/votingworks/vxsuite/assets/264902/78b7f654-152b-46c0-8791-6cd4040c5612
- Manual
=> [i18n/Aduio] Consolidate strings on BMD CastBallotPage screens

libs/utils/src/Hardware/utils.ts
Adds support for the build in card reader on the new lenovo thinkpad model 
https://github.com/votingworks/vxsuite/issues/4164 
n/a
Run on new lenovo thinkpad, did not see card reader not detected screen, used built in card reader successfully
=> Add build in thinkpad card reader support

apps/mark-scan/frontend/src/app_quit_on_idle.test.tsx, apps/mark-scan/frontend/src/components/ballot.tsx, apps/mark-scan/frontend/src/config/globals.ts, apps/mark/frontend/src/app_quit_on_idle.test.tsx, apps/mark/frontend/src/components/ballot.tsx, apps/mark/frontend/src/config/globals.ts, libs/mark-flow-ui/src/config/globals.ts, libs/mark-flow-ui/src/pages/idle_page.tsx, libs/ui/src/loading.tsx, libs/ui/src/ui_strings/app_strings.tsx
Converting text on the BMD `IdlePage` screens to use the language-aware `<UiString>`. 
Some wording changes were needed to enable better-sounding audio, but might need some tweaking in the future.
| Default  | Sample Translation |
| ![Screenshot 2023-11-07 at 12 32 17](https://github.com/votingworks/vxsuite/assets/264902/8cf05836-de9f-47fb-9871-bdb5d20fb298) | ![Screenshot 2023-11-07 at 12 33 39](https://github.com/votingworks/vxsuite/assets/264902/40633c9c-2954-4a8c-8e2e-474141256dc1) |
| ![Screenshot 2023-11-07 at 12 32 41](https://github.com/votingworks/vxsuite/assets/264902/7224b46a-9903-4515-95b0-2083d9d55114) | ![Screenshot 2023-11-07 at 12 34 05](https://github.com/votingworks/vxsuite/assets/264902/560e03d9-ff33-472e-a1ad-a4938ddbbc02) |
| …
=> [Mark|Mark-Scan] Replace text on IdlePage screens with <UiString>s

apps/mark-scan/frontend/src/pages/continue_to_review_page.tsx, libs/ui/src/ui_strings/app_strings.tsx
Converting text on the `Mark-Scan` `ContinueToReviewPage` to language-aware `<UiString>`s and adding audio prompts/button autofocus for voters relying on audio.
| Default  | Sample Translation |
| ![Screenshot 2023-11-07 at 14 39 43](https://github.com/votingworks/vxsuite/assets/264902/9c62b7f1-65ef-4344-9cc9-ae3aabd3676e) | ![Screenshot 2023-11-07 at 14 39 36](https://github.com/votingworks/vxsuite/assets/264902/74d001c8-7353-4e9c-a29e-d69506e17e35) |
- Manual
=> [i18n/Audio] <UiString>ify the Mark-Scan ContinueToReviewPage

libs/auth/README.md, libs/auth/scripts/check_pin.ts, libs/auth/scripts/configure-dev-java-card, libs/auth/scripts/configure_java_card.ts, libs/auth/scripts/generate-test-keys-and-certs, libs/auth/scripts/generate_dev_keys_and_certs.ts, libs/auth/scripts/mock_card.ts, libs/auth/scripts/program-dev-system-administrator-java-card, libs/auth/scripts/program_system_administrator_java_card.ts
Was working on some scripts for testing the Google Cloud Translation and Text-to-Speech API integrations and took a quick detour to make some low-hanging improvements to `libs/auth` scripts.
Main update is that `libs/auth` scripts can now be run from anywhere. Previously, many had to be run from the root of the `libs/auth` directory, as noted in the `libs/auth` README:
> Note that all scripts are meant to be run from `libs/auth/` and not `libs/auth/scripts/`.
I also made some tweaks to the recently added PIN-checking script, most notably no longer requiring specifying `VX_MACHINE_TYPE=admin` when checking a VxSuite card's PIN.
=> Update libs/auth scripts such that they can be run from anywhere

apps/mark-scan/frontend/src/pages/casting_ballot_page.tsx, apps/mark-scan/frontend/src/pages/jam_cleared_page.tsx, apps/mark-scan/frontend/src/pages/jammed_page.tsx, apps/mark-scan/frontend/src/pages/load_paper_page.tsx, libs/mark-flow-ui/src/pages/idle_page.tsx, libs/ui/src/ui_strings/app_strings.tsx
Converting text on a few remaining screens in `Mark-Scan` to language-aware `<UiString>`s.
Adding `id="audiofocus"` where relevant (although, starting to think through how to get our new speech engine to automatically read out the relevant text without us having to remember to tag every page/modal).
| Default  | Sample Translation |
| <img width="434" alt="Screenshot 2023-11-08 at 10 15 46" src="https://github.com/votingworks/vxsuite/assets/264902/df3b2d86-3f0e-492b-9c9d-f0ef653c0692">  | <img width="434" alt="Screenshot 2023-11-08 at 10 16 06" src="https://github.com/votingworks/vxsuite/assets/264902/c919a882-cda6-4d5c-b881-5b67ff079127">  |
- Manually verified translation works as expected
- Existing tests as regression guards …
=> [i18n/Audio] <UiString>ify simple voter-facing screens in Mark-Scan

apps/design/backend/scripts/.eslintrc.json, apps/design/backend/scripts/synthesize-speech, apps/design/backend/scripts/synthesize_speech.ts, apps/design/backend/scripts/translate-text, apps/design/backend/scripts/translate_text.ts, apps/design/backend/tsconfig.json, libs/auth/scripts/check_pin.ts, libs/auth/scripts/configure_java_card.ts, libs/auth/scripts/create_production_machine_cert_signing_request.ts, libs/auth/scripts/generate_dev_keys_and_certs.ts, libs/auth/scripts/mock_card.ts, libs/auth/scripts/program_system_administrator_java_card.ts, libs/auth/scripts/read_java_card_details.ts
As I've been iterating on the Google Cloud API integrations in VxDesign for language and audio file generation, I've been finding it helpful to be able to test the integrations end-to-end via scripts. Automated tests give me some assurance that things will work, but they (intentionally) mock the Google Cloud API clients so don't give full assurance.
I've added one script for testing text translation:
```
Usage: translate-text 'Text to translate' <target-language-code>
Arguments:
<target-language-code>	es | zh
```
And another script for testing speech synthesis:
```
Usage: synthesize-speech 'Text to convert to speech' <language-code> <output-file-path>
Arguments:
<language-code>	en | es | zh
<output-file-path>	Should end in .mp3
```
=> Add scripts for testing Google Cloud API integrations

apps/mark-scan/frontend/src/components/centered_page_layout.tsx, apps/mark-scan/frontend/src/pages/ask_poll_worker_page.tsx, apps/mark-scan/frontend/src/pages/ballot_invalidated_page.tsx, apps/mark-scan/frontend/src/pages/blank_page_interpretation_page.tsx, apps/mark-scan/frontend/src/pages/casting_ballot_page.tsx, apps/mark-scan/frontend/src/pages/continue_to_review_page.tsx, apps/mark-scan/frontend/src/pages/jam_cleared_page.tsx, apps/mark-scan/frontend/src/pages/jammed_page.tsx, apps/mark-scan/frontend/src/pages/load_paper_page.tsx, apps/mark-scan/frontend/src/pages/remove_invalidated_ballot_page.tsx, apps/mark-scan/frontend/src/pages/replace_blank_sheet_page.tsx, libs/ui/src/ui_strings/app_strings.tsx
Converting strings on the `Mark-Scan` `AskPollWorkerPage` screens to language-aware `<UiString>`s.
Chose to split out the poll-worker-facing pieces of these screens to separate screen components  - this will make it easier in the future to add file-level eslint rule exceptions when we introduce linting to enforce translations for voter-facing strings.
Also opportunistically consolidated the structure for some voter-facing screens  into a `CenteredPageLayout` to simplify.
| Default  | Sample Translation | With Card Inserted |
| ------------- | ------------- | ------------- |
| ![Screenshot 2023-11-08 at 11 46 44](https://github.com/votingworks/vxsuite/assets/264902/2b1a2a30-80b7-4f48-a533-886347538bd5) | ![Screenshot 2023-11-08 at 11 48 …
=> [i18n/Audio] <UiString>-ify the 'Ask Poll Worker For Help' pages in Mark-Scan

apps/design/backend/src/language_and_audio/speech_synthesizer.test.ts, apps/design/backend/src/language_and_audio/speech_synthesizer.ts
@kofi-q proactively pointed out an edge case in his review of https://github.com/votingworks/vxsuite/pull/4171#pullrequestreview-1717995232.  i18next catalog strings can contain tags that interfere with speech synthesis, e.g. "Do you prefer <1>apple pie</1> or <3>orange marmalade</3>?" (an apples-to-oranges comparison, I know 😉). This PR cleans text in preparation for speech synthesis accordingly.
```
./synthesize-speech 'Do you prefer <1>apple pie</1> or <3>orange marmalade</3>?' en audioClip.mp3
```
_Before this PR_
https://github.com/votingworks/vxsuite/assets/12616928/d3256a48-4c64-4df9-8bf8-058df9e8caf8
I will not stop finding this audio clip hilarious 😆
_After this PR_
https://github.com/votingworks/vxsuite/assets/12616928/d15fcad3-6d9f-4c09-8d93-7b42dbbfc838
Less comedic, more …
=> Clean text before text-to-speech processing

apps/design/backend/README.md, apps/design/backend/src/language_and_audio/README.md, apps/design/frontend/README.md
This PR adds documentation for Google Cloud authentication, specifically when running VxDesign locally. This authentication is necessary if you want to be able to generate language and audio files.
=> Add documentation for Google Cloud authentication

libs/ui/src/display_settings/color_settings.tsx, libs/ui/src/display_settings/index.tsx, libs/ui/src/display_settings/size_settings.tsx, libs/ui/src/display_settings/tab_bar.tsx, libs/ui/src/ui_strings/app_strings.tsx
Converting text in the shared `DisplaySettings` menu component to language-aware `<UiString>`s.
- Manual verification + existing tests as regression checks
=> [i18n/Audio] <UiString>-ify the DisplaySettings menu

libs/utils/src/extract_cdf_ui_strings.test.ts, libs/utils/src/extract_cdf_ui_strings.ts
@adghayes ran into a bug with ui string extraction where older Vx election fixtures with numeric IDs (precinct ID, party ID, etc) would cause issues when converted to CDF elections and imported into voter-facing apps.
This change explicitly sets numeric IDs in the `UiStringTranslations` object.
Before:
```ts
{
precinctName: [
'Precinct A',
'Precinct B',
],
}
```
After:
```ts
{
precinctName: {
'0': 'Precinct A',
'1': 'Precinct B',
},
}
```
- Added a unit test to repro the bug and then verify the fix
- ~[ ] …
=> [fix/uistrings] Avoid numeric entity IDs getting treated as array indices

libs/ui/i18next-parser.config.ts
Noticed a quirk in app string catalog generation. While the new catalog generation logic handles the addition and removal of strings to `app_strings.tsx`, it doesn't handle updates to existing strings.
-----
So imagine we have the following in `app_strings.tsx`:
```ts
buttonDone: () => <UiString uiStringKey="buttonDone">Done</UiString>,
```
The catalog will contain:
```json
"buttonDone": "Done",
```
If we then edit `app_strings.tsx`, e.g.:
```ts
buttonDone: () => <UiString uiStringKey="buttonDone">Done!</UiString>,
```
The catalog should read:
```json
"buttonDone": "Done!",
```
But it'll currently remain unchanged.
-----
This PR addresses this gap with a config tweak. The relevant config field is a bit abstractly named. But you can see how it does what we want by following this issue to …
=> Make sure that catalog values are properly updated

apps/central-scan/backend/src/fujitsu_scanner.test.ts, apps/central-scan/backend/src/fujitsu_scanner.ts, libs/cvr-fixture-generator/src/cli/generate/main.ts, libs/cvr-fixture-generator/src/generate_cvrs.ts, libs/cvr-fixture-generator/src/utils.ts, libs/hmpb/layout/src/layout.ts, libs/types/src/cdf/ballot-definition/convert.ts, libs/types/src/election.test.ts, libs/types/src/election_utils.ts
Adds support to VxCentralScan for all of our ballot paper sizes. Also consolidates specification of ballot paper sizes to a single util function.
I have not yet tested the actual functionality of this change, since I don't have long paper sizes or a Fujitsu.
=> VxCentralScan: Support all paper sizes

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/frontend/src/tabulation_screen.test.tsx, apps/design/frontend/src/tabulation_screen.tsx
Adds option on the Tabulation screen to adjudication unmarked write-ins. Also starts including the set system settings in the setup package - previously it was just exporting the default regardless of what was set in the app.
Edited automated tests accordingly + tested manually.
=> VxDesign blank ballot adjudication option

libs/ballot-interpreter/src/__snapshots__/interpret_nh_hmpb.test.ts.snap, libs/ballot-interpreter/src/interpret.ts, libs/ballot-interpreter/src/interpret_nh_hmpb.test.ts, libs/ballot-interpreter/src/legacy_adapter.ts
In the NH legacy ballot adapter, we were treating uninterpretable ballots as scanning errors, which in central-scanner just interrupt the batch scanning and effectively cause one ballot go unaccounted for.
This PR fixes the error that gets reported in this case.
We should probably also fix the silent swallowed error.
~TODO: needs a test, probably a high-level test, to make sure the right error gets surfaced when scanning, say, a blank sheet of paper.~
=> unreadable pages in the NH legacy adapter should show up as unreadable pages, not as scanning errors

docs/commit_signing.md
Debian 12 ships with a new enough git, so we don't need to build it.
=> docs: remove explicit build steps for git

libs/ballot-interpreter/src/hmpb-rust/debug.rs, libs/ballot-interpreter/src/hmpb-rust/qr_code/detect.rs, libs/ballot-interpreter/src/hmpb-rust/qr_code/mod.rs, libs/ballot-interpreter/src/hmpb-rust/qr_code/rqrr.rs, libs/ballot-interpreter/src/hmpb-rust/qr_code/zbar.rs
We previously only showed `No QR code found` when a QR code could not be detected. This wasn't very useful because it didn't really clarify why it wasn't detected. Now we include the search bounds in both `Ok` and `Err` variant QR code debug images to make it clearer.
| Successful | Failed |
|-|-|
|![image](https://github.com/votingworks/vxsuite/assets/1938/5500fee4-02f5-42d5-b985-daead9b97344)|![20231100_182029-ballot-0001_debug_qr_code](https://github.com/votingworks/vxsuite/assets/1938/f936d12d-86b5-4c4b-9554-bd882c4ac2b4)|
Tested manually
=> feat(ballot-interpreter): include more QR code debug metadata

libs/mark-flow-ui/src/components/election_info.tsx, libs/types/src/ballot_package.ts, libs/types/src/cdf/ballot-definition/convert.ts, libs/types/src/ui_string_translations.ts, libs/ui/src/ui_strings/election_strings.tsx, libs/utils/src/ballot_package.test.ts, libs/utils/src/ballot_package.ts, libs/utils/src/extract_cdf_ui_strings.test.ts, libs/utils/src/extract_cdf_ui_strings.ts
Noticed that the only date we need to translate and/or generate audio for, so far, is the election date -- to avoid having to piece together audio fragments to read out dates, this PR adds support for pre-generating language-specific date strings and audio for the election date.
The CDF doesn't currently provide support for `InternationalizedText` strings for the election date, so the approach here is to add a new `vxElectionStrings.json` file to the ballot package, which will contain non-CDF election-specific translations. 
Also adding an `ElectionStringKey.ELECTION_DATE` key and corresponding string extractor and renderer.
- New test cases for new ballot package file and string extraction logic
- Updated affected tests …
=> [i18n/Audio] Enable for pre-generated election date strings and audio

apps/mark-scan/frontend/src/utils/ScreenReader/aria_screen_reader.test.ts, apps/mark-scan/frontend/src/utils/ScreenReader/aria_screen_reader.ts, apps/mark/frontend/src/utils/ScreenReader/aria_screen_reader.test.ts, apps/mark/frontend/src/utils/ScreenReader/aria_screen_reader.ts
It was misspelled.
Manually tested and updated broken unit test.
=> Fix screen reader support for aria-labelled-by attribute

apps/admin/backend/src/store.ts, apps/central-scan/backend/src/store.ts, apps/scan/backend/schema.sql, apps/scan/backend/src/app_config.test.ts, apps/scan/backend/src/app_results.test.ts, apps/scan/backend/src/app_usb_drive.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/backend/test/helpers/shared_helpers.ts, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/test/utils.ts, libs/utils/src/index.ts, libs/utils/src/sqlite.test.ts, libs/utils/src/sqlite.ts
Issue link: https://github.com/votingworks/vxsuite/issues/4096
This PR improves continuous export failure recovery by moving the export operation "progress marker" from the USB drive to the VxScan store.
We currently write a `.vx-export-in-progress` file to the USB drive at the start of every continuous export operation. We then delete the file when the operation completes. If an export operation fails midway and a machine has to be restarted, the existence of that file on startup tells us that a resync is required.
The main downside to using a file on the USB drive is that the write of that file itself may fail. In that case, the machine won't know that a resync is required after restart. Switching to a piece of state on the machine is more robust, especially …
=> Improve continuous export failure recovery by moving the export operation "progress marker" from USB drive to VxScan store

apps/scan/frontend/src/screens/scan_warning_screen.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
Converting text on the "blank ballot" `ScanWarningScreen` states in VxScan to language-aware `<UiString>`s.
Also removing the string, `"Your votes will count, even if you leave some blank."` from the `BlankBallotWarningScreen`, since it's not relevant for that state.
- Manual + existing tests
=> [i18n] VxScan: <UiString>ify blank ballot warning screens

apps/design/backend/scripts/synthesize_speech.ts, apps/design/backend/scripts/translate_text.ts, apps/design/backend/src/language_and_audio/speech_synthesizer.ts, apps/design/backend/src/language_and_audio/translator.test.ts, apps/design/backend/src/store.test.ts, libs/backend/src/ui_strings/ui_strings_api_test_runner.ts, libs/backend/src/ui_strings/ui_strings_machine_configuration_test_runner.ts, libs/types/src/language_code.ts, libs/types/src/ui_string_audio_clips.test.ts, libs/ui/src/hooks/ui_strings_api.test.tsx, libs/ui/src/ui_strings/language_context.test.tsx, libs/ui/src/ui_strings/number_string.test.tsx, libs/ui/src/ui_strings/ui_string.stories.tsx, libs/ui/test/ui_strings/test_strings.tsx, libs/utils/src/ballot_package.test.ts, libs/utils/src/extract_cdf_ui_strings.test.ts, libs/utils/src/format.test.ts
Using more explicit `xx-YY...` language codes, where relevant, to enable better translations and formatting (noticed `'es'` defaults to `'es-ES'` when formatting numbers, for example, which means we end up with `4.096` instead of the more common `4,096` in the Americas).
Also adding both 'Simplified' and 'Traditional' variants of Chinese language codes.
=> [i18n/Audio] Use stricter IETF language codes for better translations/audio

libs/auth/scripts/cac_get_cert.ts, libs/auth/src/cac/common_access_card_api.ts, libs/auth/src/card.ts, libs/auth/src/mock_file_card.test.ts, libs/auth/src/mock_file_card.ts, libs/auth/test/utils.ts
I noticed that the interfaces for `Card` and `CommonAccessCardCompatibleCard` didn't actually include all the methods that they should have. I added a `BaseCard` interface to capture the `disconnect` method, then fixed `CommonAccessCardCompatibleCard` to include `PinProtectedCard` to ensure it has `checkPin`.
n/a
Automated type checking.
=> fix(auth): correct card interface APIs

apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/config/types.ts, apps/mark-scan/frontend/src/contexts/ballot_context.ts, apps/mark-scan/frontend/src/pages/start_screen.tsx, apps/mark-scan/frontend/test/test_utils.tsx, apps/mark/frontend/src/app_root.tsx, apps/mark/frontend/src/config/types.ts, apps/mark/frontend/src/contexts/ballot_context.ts, apps/mark/frontend/src/pages/start_screen.tsx, apps/mark/frontend/test/test_utils.tsx, libs/mark-flow-ui/src/config/types.ts
This was added in 5c46e9cbc2eeb26cd25772fabe7948c7566e7272 and only makes sense in a world where we store votes on a voter card. Since we no longer do that, there's no need to keep this flag around.
n/a
Automated, plus some manual clicking around.
=> refactor(mark): remove unused `forceSaveVoteFlag`

apps/mark/frontend/src/apimachine_config.test.tsx, apps/mark/frontend/src/app.test.tsx, apps/mark/frontend/src/app_card_unhappy_paths.test.tsx, apps/mark/frontend/src/app_cardless_voting.test.tsx, apps/mark/frontend/src/app_contest_candidate_no_party.test.tsx, apps/mark/frontend/src/app_contest_ms_either_neither.test.tsx, apps/mark/frontend/src/app_contest_multi_seat.test.tsx, apps/mark/frontend/src/app_contest_single_seat.test.tsx, apps/mark/frontend/src/app_contest_write_in.test.tsx, apps/mark/frontend/src/app_contest_yes_no.test.tsx, apps/mark/frontend/src/app_data.test.tsx, apps/mark/frontend/src/app_polls_flows.test.tsx, apps/mark/frontend/src/app_quit_on_idle.test.tsx, apps/mark/frontend/src/app_replace_election.test.tsx, apps/mark/frontend/src/app_root.tsx, apps/mark/frontend/src/app_setup_errors.test.tsx, apps/mark/frontend/src/app_test_mode.test.tsx, apps/mark/frontend/src/lib/gamepad.test.tsx, apps/mark/frontend/test/helpers/election.ts
We store this in the backend and should not be storing it locally. This is a step in the direction of removing `kiosk`-based API uses.
n/a
Automated test changes. Manually configured, unconfigured, opened and closed polls, and voted.
=> refactor(mark): remove election definition from local storage

apps/admin/frontend/src/__snapshots__/app.test.tsx.snap, libs/ui/src/reports/admin_tally_report.stories.tsx, libs/ui/src/reports/contest_results_table.test.tsx, libs/ui/src/reports/contest_results_table.tsx, libs/ui/src/reports/precinct_scanner_tally_reports.stories.tsx
Closes #4024. Adds term description, the same string which appears on the ballot, to tally reports. Also modifies the styling in the case where there is no term description to be slightly less cramped.
|  Type  | Scanned Only  | Manual Too |
| ------------- | ------------- | --------- |
| Before | <img width="248" alt="Screen Shot 2023-11-17 at 1 09 39 PM" src="https://github.com/votingworks/vxsuite/assets/37960853/e1c1ad42-ec3c-4c61-92ff-8ca5573b3394"> | <img width="243" alt="Screen Shot 2023-11-17 at 1 09 31 PM" src="https://github.com/votingworks/vxsuite/assets/37960853/e601a307-4317-48a1-bf55-c8fbce0fe6c4"> |
| After, no term  | <img width="239" alt="Screen Shot 2023-11-17 at 1 02 43 PM" src="https://github.com/votingworks/vxsuite/assets/37960853/c76abfc9-76cb-4732-a5a3-d8ad77c29d0f"> …
=> add term description to tally reports

apps/central-scan/backend/.eslintrc.json, apps/central-scan/backend/scripts/copy-batch, apps/central-scan/backend/scripts/copy_batch.ts, apps/central-scan/backend/tsconfig.json, apps/design/backend/.eslintrc.json, apps/design/backend/scripts/.eslintrc.json, apps/design/backend/scripts/synthesize_speech.ts, apps/design/backend/scripts/translate_text.ts, apps/scan/backend/.eslintrc.json, apps/scan/backend/scripts/.eslintrc.json, apps/scan/backend/scripts/copy-sheets, apps/scan/backend/scripts/copy_sheets.ts, apps/scan/backend/tsconfig.json, libs/auth/.eslintrc.json, libs/auth/scripts/.eslintrc.json, libs/auth/scripts/check_pin.ts, libs/auth/scripts/configure_java_card.ts, libs/auth/scripts/create_production_machine_cert_signing_request.ts, libs/auth/scripts/generate_dev_keys_and_certs.ts, libs/auth/scripts/mock_card.ts, libs/auth/scripts/program_system_administrator_java_card.ts, libs/auth/scripts/read_java_card_details.ts
In preparation for upcoming QA, I'm committing a script that I've been using to facilitate my own scale testing. The script copies a scanner store's sheet records to quickly bump the sheet count up without having to physically scan ballots.
Because the script is copying sheets rather than creating them from scratch, a first sheet does have to be physically scanned before the script can be used. The script reminds you of this, if relevant:
```
$ ./copy-sheets 10
❌ Scanner store should contain at least one sheet to copy
```
-----
For safety, I added a check to ensure that the script cannot be run in production:
```
$ NODE_ENV=production ./copy-sheets 
❌ Cannot be run in production
```
-----
And finally, the script does not cover continuous export to the USB drive, but it does surface the …
=> Add sheet-copying scripts to facilitate scale testing

.circleci/config.yml, libs/auth/package.json, libs/auth/scripts/configure-dev-simulated-cac-card, libs/auth/scripts/configure-simulated-cac-card, libs/auth/scripts/configure_simulated_cac_card.ts, libs/auth/src/cac/common_access_card.test.ts, libs/auth/src/cac/common_access_card.ts, libs/auth/src/cac/common_access_card_certs.ts, libs/auth/src/piv.ts, libs/monorepo-utils/src/circleci.ts, pnpm-lock.yaml
Allow us to program a JavaCard to mimick a CAC card as best as possible. Important changes:
- use the same key slots as the CAC card
- use RSA2048 instead of ECC
all the changes are downstream from those two requirements.
=> add scripts and capabilities for building a simulated CAC card out of a JavaCard

apps/central-scan/backend/src/store.test.ts, apps/central-scan/backend/src/store.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, libs/backend/src/cast_vote_records/export.ts
Closes #4095. Removes unused `batchLabel` field.
=> remove `batchLabel`

libs/utils/src/Hardware/utils.ts
https://github.com/votingworks/vxsuite/issues/4164
The smartcard reader got swapped out when we ordered more thinkpads so supporting both the old and new 
tested on real hardware
=> support both possible thinkpad card readers

apps/mark-scan/backend/README.md, apps/mark-scan/backend/build-patinputd.sh, apps/mark-scan/backend/package.json, apps/mark-scan/backend/src/custom-paper-handler/cli/state_machine_cli.ts, apps/mark-scan/backend/src/custom-paper-handler/constants.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/pat-input/README.md, apps/mark-scan/backend/src/pat-input/connection_status_reader.test.ts, apps/mark-scan/backend/src/pat-input/connection_status_reader.ts, apps/mark-scan/backend/src/pat-input/constants.ts, apps/mark-scan/backend/src/pat-input/mock_connection_status_reader.ts, apps/mark-scan/backend/src/pat-input/patinputd.c, apps/mark-scan/backend/src/pat-input/vsapgpio.c, apps/mark-scan/backend/src/pat-input/vsapgpio.h, apps/mark-scan/backend/src/server.ts, apps/mark-scan/backend/test/app_helpers.ts, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/pages/pat_device_identification/pat_device_identification_page.tsx, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/src/log_event_ids.ts
* Adds support for the hardware's built-in PAT input
* Does not affect support for the Swifty USB switch (useful for development)
**Architecture**
* The hardware sends 3 signals over GPIO: connection status, A signal, and B signal. A and B signal are generic terms for what is most commonly "sip" and "puff" (not necessarily in that order)
* GPIO values are available by writing to and reading from the filesystem. See: [sysfs interface](https://www.ics.com/blog/gpio-programming-using-sysfs-interface)
* A daemon `patinputd.c` polls the `sysfs` interface and emits keypress events when A or B signal is detected
* The frontend's existing `gamepad` + USB switch integration already handles these keypress events
* The backend has been updated to read connection status from the `sysfs` interface …
=> Integrate built-in PAT input

apps/scan/backend/src/util/results.ts
Closes #4084. Not sure how I or someone else didn't catch this before, as the bug appears to happen whenever you insert a poll worker card for a primary election on VxScan with more than one ballot scanned.
We need to add a regression test but it's a bit of a lift, so I created a ticket to circle back to: #4252.
I and @carolinemodic tested manually. For automated testing, need to circle back to #4252.
=> fix tabulation for non-zero primary results

apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/confirm_removing_file_modal.tsx, apps/admin/frontend/src/components/remove_all_manual_tallies_modal.tsx, apps/admin/frontend/src/screens/manual_data_entry_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_entry_screen.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.tsx, apps/admin/frontend/src/screens/tally_screen.test.tsx, apps/admin/frontend/src/screens/tally_screen.tsx
Closes #2837.
"Manually Entered Results" -> "Manual Tallies"
https://github.com/votingworks/vxsuite/assets/37960853/25163b0a-00b2-4e3c-958a-b3492f2ed31b
=> Update Manual Tally Copy

libs/utils/src/Hardware/utils.ts
Hex code value had two letters transposed. This correctly identifies the vendor id.
=> Update hex code vendor ID for Alcor Link AK9563 card reader

apps/central-scan/frontend/src/screens/scan_ballots_screen.test.tsx, apps/central-scan/frontend/src/screens/scan_ballots_screen.tsx
It's not currently clear what is supposed to happen if you try to delete a batch while scanning is in progress. We've seen the scanner device keep scanning even though the batch is deleted, which is weird. Quick fix: disable the buttons.
=> VxCentralScan: Disable "Delete Batch" buttons while scanning

apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/app_root.tsx, apps/admin/frontend/src/components/app_routes.tsx, apps/admin/frontend/src/components/export_election_ballot_package_modal_button.tsx, apps/admin/frontend/src/components/mark_official_button.tsx, apps/admin/frontend/src/components/navigation_screen.tsx, apps/admin/frontend/src/router_paths.ts, apps/admin/frontend/src/screens/election_screen.tsx, apps/admin/frontend/src/screens/manual_data_entry_screen.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.tsx, apps/admin/frontend/src/screens/print_test_deck_screen.test.tsx, apps/admin/frontend/src/screens/reporting/reports_screen.tsx, apps/admin/frontend/src/screens/tally_screen.test.tsx, apps/admin/frontend/src/screens/tally_screen.tsx, apps/admin/frontend/src/screens/unconfigured_screen.tsx, apps/admin/integration-testing/e2e/reports.spec.ts, apps/central-scan/frontend/src/components/export_results_modal.tsx, apps/central-scan/frontend/src/navigation_screen.tsx, apps/central-scan/frontend/src/screens/ballot_eject_screen.tsx, apps/central-scan/frontend/src/screens/scan_ballots_screen.tsx, libs/ui/src/card.stories.tsx, libs/ui/src/card.test.tsx, libs/ui/src/card.tsx, libs/ui/src/election_info_bar.tsx, libs/ui/src/icons.tsx
Adds a variety of small tweaks to VxCentralSystem and VxAdmin to improve how they use the desktop theme.
Central Scan - adjudication
Admin - Election Manager - Election screen (formerly Ballots screen)
Admin - Election Manager - tallies and marking as official
https://github.com/votingworks/vxsuite/assets/530106/54dd0dbd-f0c6-4028-9bc2-9bbc808b0148
=> Central system design polish

libs/backend/src/cast_vote_records/file_system_utils.ts
`fs.copyFile` has issues on real USB drives when `src` and `dest` are both on USB.
=> fix(randomize-cvrs): use `execFile('cp')` instead of `fs.copyFile`

apps/central-scan/frontend/src/screens/unconfigured_election_screen_wrapper.tsx, apps/mark-scan/frontend/src/pages/unconfigured_election_screen_wrapper.tsx, apps/mark/frontend/src/pages/unconfigured_election_screen_wrapper.tsx, apps/scan/frontend/src/components/cast_vote_record_sync_modal.tsx, apps/scan/frontend/src/components/display_settings_manager.tsx, apps/scan/frontend/src/screens/unconfigured_election_screen_wrapper.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, libs/ui/src/hooks/use_change_listener.test.ts, libs/ui/src/hooks/use_change_listener.ts
Allows selecting a subset of the data and only triggering the change handler when that subset changes.
n/a
New automated test for the hook.
=> feat(ui): add selector to `useQueryChangeListener`

apps/scan/backend/scripts/copy_sheets.ts
We want the first `N` sheets, and `iter` + `take` is an easy, clear way to do that.
n/a
=> refactor(scan): use `iter` to clarify intent

apps/scan/frontend/src/screens/poll_worker_screen.tsx, libs/backend/src/logs/logs_api.ts
- Combine imports from the same source.
- remove `eslint-disable` directives that weren't doing anything (though the `no-empty` did fix the issue because the block was no longer empty, but then the directive doesn't suppress any lints so eslint warns; just replace it with a comment saying that we're ignoring exceptions)
n/a
=> style: fix some minor lints

apps/central-scan/backend/src/store.test.ts, apps/central-scan/backend/src/store.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/screens/cast_vote_record_sync_required_screen.test.tsx, apps/scan/frontend/src/screens/cast_vote_record_sync_required_screen.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx
Issue link: https://github.com/votingworks/vxsuite/issues/4285
This PR fixes various VxScan bugs around mode switching (i.e. switching between test and official mode). The bugs include the following:
1. Switching mode after polls have been opened (and even subsequently closed) is supposed to return the polls to their initial closed state. But VxScan is currently only "half" switching - the backend is updating but the frontend is not.
2. Switching mode does not result in the creation of a new export directory for continuous export, when it should.
3. The only way to currently clear the CVR sync required screen is to click the screen's sync button. But other actions can also render a sync to USB drive unnecessary. One such action is switching from test mode to …
=> Fix various VxScan mode-switching bugs

apps/scan/frontend/src/components/full_screen_prompt_layout.tsx
Fixes: #4288
The scan warning screen generally has two action buttons, one to return the ballot and one to cast the ballot. In some cases (e.g. if casting overvoted ballots is disallowed), there may only be one button. This PR ensures we center the lone button in those cases.
Single button
https://github.com/votingworks/vxsuite/assets/530106/9e69d105-2d7e-48e9-b2d1-c72339d6763e
Double button (no regression)
https://github.com/votingworks/vxsuite/assets/530106/e29c67f3-3eeb-48da-a9ab-130c0cfc59c1
Manual test
=> VxScan: Center single action button on scan warning screen

libs/usb-drive/scripts/mount.sh
Closes #4286. Now, phantom drive entries are removed on each mount, so the user will only ever see one in the file menu.
Tested on a prod image - because the changes are confined to a script, it's possible to just change the script and test in prod.
=> unmount phantom drives before mounting drive

apps/central-scan/frontend/src/screens/ballot_eject_screen.test.tsx, apps/central-scan/frontend/src/screens/ballot_eject_screen.tsx, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts
Addresses bug where VxCentralScan will crash on exporting CVRs sometimes if there is an unmarked write-in. We were making the assumption that the image exists for the page with the UWI, but not ensuring it for VxCentralScan's minimal export's. Bug fixed in first commit.
Second commit prevents "Tabulate as is" for overvote ballots if `precinctScanDisallowCastingOvervotes` is set.
=> Address Two `nh-march` VxCentralScan Bugs

apps/admin/backend/src/adjudication.test.ts, apps/admin/backend/src/adjudication.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/types.ts, apps/admin/frontend/src/screens/write_ins_adjudication_screen.test.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx
Closes #4313. Allows you to unselect adjudications in WIA.
Laying out here because it is almost identical now, except that the candidate buttons are not `containerLow` (gray) and there is a little margin between the write-in candidate section and the mark as invalid button
https://github.com/votingworks/vxsuite/assets/37960853/3f86651e-1010-44a0-915a-7208f5f838f5
Lots of automated testing changes, manual testing too.
=> Allow Unselecting WIA Adjudications

libs/eslint-plugin-vx/src/rules/no_floating_results.ts, libs/eslint-plugin-vx/src/util/index.ts, libs/eslint-plugin-vx/tests/rules/no_floating_results.test.ts
Previously we only checked if the type as literally `Result`, but it didn't support type aliases like `type CustomResult = Result<T, E>;`. This fixes that.
Function returns `Promise<ExportDataResult>`:
| Before (no error) | After (ESLint error) |
|-|-|
|<img width="397" alt="image" src="https://github.com/votingworks/vxsuite/assets/1938/d9010af3-becd-4025-8dce-2b24c3fc49c3">|<img width="851" alt="image" src="https://github.com/votingworks/vxsuite/assets/1938/2e7d84c7-ded3-47b6-abc4-00a0c8e5dd88">|
=> fix(eslint-plugin-vx): support `Result` type aliasing

libs/ui/src/number_pad.tsx, libs/ui/src/unlock_machine_screen.tsx
@mattroe noticed that the buttons in the PIN entry were hard to press on VxScan, so this PR makes them a bit bigger.
Before
After
Manual test
=> Fix PIN entry numpad button sizing

libs/backend/src/logs/logs_api.test.ts, libs/backend/src/logs/logs_api.ts
Once we moved to `cp`, we also have to create intermediate directories.
=> fix(logs): create intermediate diretories for log exports

apps/admin/frontend/src/components/import_cvrfiles_modal.tsx
Fixes: #4327 
Instead of using `WithScrollButtons` - a touch-screen scroll component - make a desktop-style scrollable table for the CVR import modal table.
Scrolling
https://github.com/votingworks/vxsuite/assets/530106/67c6c918-81a8-4a59-a09e-91fbcd25d743
No scrolling needed
Manual testing.
Also did a search to ensure `WithScrollButtons` isn't getting used anywhere else in a desktop app.
=> VxAdmin: Scrollable CVR import table

apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/geography_screen.tsx, libs/eslint-plugin-vx/src/rules/gts_no_unnecessary_has_own_property_check.ts, libs/types/src/cdf/ballot-definition/convert.ts
There are still a few instances of `Object.fromEntries` left, but these ones were the easy ones to convert. This is part of my exploration into how difficult it would be to convert uses of `Record` into `Map`.
n/a
Existing automated tests.
=> refactor: replace `Object.fromEntries` with `Map`

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
Predicates passed to e.g. `Array::filter` don't have to return `boolean`. They can return anything, and the truthiness of the value determines matches. This change brings the `IteratorPlus` predicates in line with that precedent.
```ts
const candidates = [
{ name: 'Bob' },
{ name: 'MICKEY', isWriteIn: true },
] as const;
// previously, `c.isWriteIn === true` would be required since `isWriteIn` is `boolean | undefined`
console.log('Write-in candidate count:', iter(candidates).filter((c) => c.isWriteIn).count());
```
Additional unit tests.
=> fix(basics): make `IteratorPlus` predicates like `Array` predicates

apps/admin/frontend/prodserver/package.json, apps/central-scan/frontend/prodserver/package.json, apps/mark-scan/frontend/prodserver/package.json, apps/mark/frontend/prodserver/package.json, apps/scan/frontend/prodserver/package.json, pnpm-lock.yaml
Some workspace tools (not `pnpm`) do not like having multiple packages in the workspace with the same name. This change gives each `prodserver` package its own name.
n/a
=> build: give `prodserver` packages unique names

apps/admin/backend/src/cast_vote_records.ts, apps/admin/frontend/src/screens/manual_data_entry_screen.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.tsx, apps/admin/frontend/src/screens/tally_screen.tsx, apps/central-scan/backend/src/index.ts, apps/central-scan/frontend/src/screens/scan_ballots_screen.tsx, libs/backend/src/cast_vote_records/build_cast_vote_record.ts, libs/backend/src/cast_vote_records/build_report_metadata.test.ts, libs/backend/src/election_package/election_package_io.ts, libs/ballot-encoder/src/index.ts, libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts, libs/converter-nh-accuvote/jest.config.js, libs/converter-nh-accuvote/test/utils.ts, libs/cvr-fixture-generator/src/generate_cvrs.ts, libs/test-utils/src/console.ts, libs/utils/src/tabulation/tabulation.ts, libs/utils/src/tabulation/tally_reports.ts, libs/utils/src/tabulation/transformations.test.ts
Adds `maxBy` and `minBy` helper methods and updates some places to use them as well as the existing `sum` and `count` methods.
```ts
async function getOldestFile(paths: string[]): Promise<Optional<string>> {
return await iter(paths)
.async()
.minBy(async (path) =>
(await fs.lstat(path)).ctime.getTime()
);
}
```
=> refactor: use `IteratorPlus` helper methods

apps/admin/frontend/jest.config.js, apps/admin/frontend/src/components/remove_all_manual_tallies_modal.tsx, apps/admin/frontend/src/screens/manual_data_entry_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_entry_screen.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.tsx, apps/admin/frontend/src/screens/tally_screen.test.tsx, apps/admin/frontend/src/screens/task_screen.tsx
Fixes #4353 
- Restructures the Edit Tallies page layout to a "task mode" layout inspired by write-in adjudication
- Replaces the table-based implementation with simpler flexbox to fix some of the weird layout issues from the original bug report
- Adds selective auto-focus tags to ensure smooth keyboard nav
https://github.com/votingworks/vxsuite/assets/530106/c99258b0-4b8d-408f-80f5-1b36c50337d2
(Note that in this video it appears there may be a bug where write-in candidates are not included in the validation of total ballots counted, but I'm going to look into that separately as a follow up if necessary)
Manual testing
=> Manual tally entry polish

libs/ui/src/radio_group.tsx
We currently use this specifically in the display settings, which looks weird in extra-large without an adjustment. This probably won't address every case (e.g. if we are supporting languages that take up more space) but it works for now.
Before
After
Manual test
=> Shrink padding in radio group when size mode is extra-large

libs/ui/package.json, libs/ui/src/hooks/ui_strings_api.test.tsx, libs/ui/src/hooks/ui_strings_api.ts, libs/ui/src/hooks/use_current_language.test.tsx, pnpm-lock.yaml
Adding react-query clients for the `getUiStringAudioIds` and `getAudioClips`.
The plan is to lazy-load audio clips as `UiString` components get rendered -- the backend `getAudioClips()` endpoint is called via a batched client `getAudioClip()` method that combines all `getAudioClip()` queries within a default `10ms` window. Using the unfortunately named `@yornaath/batshit` library recommended in the `react-query` docs.
Once everything's wired up, will do some benchmarking to figure out if we need to optimise the audio clip fetching to make sure there's no significant latency in playing audio.
- New test cases for the react queries and batching logic.
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, …
=> [i18n/Audio] Add react clients for UI String audio APIs

apps/scan/backend/src/app.ts, apps/scan/backend/src/app_config.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/store.ts, apps/scan/backend/src/util/workspace.ts, apps/scan/backend/test/helpers/custom_helpers.ts, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/src/cast_vote_records/file_system_utils.ts
Issue link: https://github.com/votingworks/vxsuite/issues/4322
This PR addresses various continuous export edge cases, that I think explain some of the odd behaviors that we've seen in prod. Unfortunately, the issues that we've seen, like unexpected crashes and spurious "CVR Sync Required" screens, have been hard to repro with consistency in dev (VxDev or VM). So I'm partly hypothesizing. There may be other sources of problems out there.
More on the specific fixes in GitHub comments.
=> Ensure that continuous export operations do not interleave and avoid spurious "CVR Sync Required" screens

libs/utils/src/ballot_styles.ts, libs/utils/src/extract_cdf_ui_strings.ts
We're planning to just use the built-in methods and `iter` from `@votingworks/basics` for operating on lists. This change just removes the most trivial use of `lodash`.
n/a
=> refactor: remove `lodash.find`

apps/admin/backend/schema.sql, apps/admin/backend/src/app.ts, apps/admin/backend/src/store.ts
We haven't been deleting election data from the VxAdmin store on unconfigure, which could lead to the disk filling up over time.
https://votingworks.slack.com/archives/C060FEVB2L8/p1702320174466059
=> VxAdmin: delete election on unconfigure rather than simply marking as 'deleted'

apps/admin/frontend/src/components/export_election_package_modal_button.test.tsx, apps/admin/frontend/src/components/export_election_package_modal_button.tsx, libs/ui/src/button.test.tsx, libs/ui/src/button.tsx
Fixes #4043 
- Adds a new `loading` prop to `Button` that disables the button and shows a loading spinner.
- Uses this prop to add a loading state to the Save Election Package modal.
https://github.com/votingworks/vxsuite/assets/530106/78f61728-92ee-480f-b926-260cbdbbda39
Manual and automated tests
=> VxAdmin: Loading state for "Save Election Package"

apps/admin/integration-testing/e2e/support/auth.ts
=> Fix unconfiguring VxAdmin in integration test

apps/admin/frontend/src/screens/settings_screen.test.tsx, apps/admin/frontend/src/screens/settings_screen.tsx, apps/central-scan/frontend/src/screens/settings_screen.tsx, apps/central-scan/frontend/src/screens/system_administrator_screen.test.tsx, apps/central-scan/frontend/src/screens/system_administrator_screen.tsx
Fixes #4347 
For parity, we want the election manager and system admin roles to be able to save logs on all machines. This PR updates VxAdmin and VxCentralScan to enable that. VxMark/MarkScan is being tracked by @kshen0 
VxAdmin - election manager
VxCentralScan - system admin
Added new tests
=> Allow election manager and system admin to save logs on central system

apps/scan/backend/src/app_ui_strings.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/server.test.ts, apps/scan/backend/src/types.ts, apps/scan/backend/test/helpers/custom_helpers.ts
Before this change, the tests would print warnings that there were resources being held that were preventing NodeJS from exiting within 1s of the tests ending. The state machine's paper status polling was why. This change stops the state machine when the tests are over to prevent that from happening.
n/a
=> test(scan): stop state machine on test end

apps/scan/backend/src/index.ts, apps/scan/backend/src/server.ts
We already resolve the other values in `main`, might as well do the same here. This is part of the changes I'm making for making the Custom state machine decide when to scan.
n/a
=> refactor(scan): pass `auth` to `start`

apps/scan/backend/schema.sql, apps/scan/backend/scripts/copy_sheets.ts, apps/scan/backend/src/app.ts, apps/scan/backend/src/app_config.test.ts, apps/scan/backend/src/app_export.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/test/helpers/shared_helpers.ts, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/test/utils.ts, libs/utils/src/mutex.ts
After merging https://github.com/votingworks/vxsuite/pull/4365, I thought of two more continuous export edge cases worth addressing.
In that previous PR, I was focused on avoiding spurious "CVR Sync Required" screens. But a specific race condition could also cause us to miss a case where we _should_ display the screen. Consider the following sequence:
1. Ballot 1 is accepted, and we set `isContinuousExportOperationInProgress` to true
2. Export operation 1 (for ballot 1) starts
3. Ballot 2 is accepted, and we set `isContinuousExportOperationInProgress` to true
4. Export operation 1 completes and sets `isContinuousExportOperationInProgress` to false
5. Export operation 2 (for ballot 2) starts
6. Export operation 2 fails
We'd fail to display the "CVR Sync …
=> Address two more continuous export edge cases

apps/scan/backend/package.json, apps/scan/backend/src/scanners/custom/app_scan.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, pnpm-lock.yaml
Issue link: https://github.com/votingworks/vxsuite/issues/4326
See **#issue-custom-scanner-state-machine-v3** in Slack for lots of additional context.
In our stress testing of the scanner state machine, we've identified edge cases that are unlikely to come up in real use but that we want to protect against regardless. One such issue we've dubbed "wind-up-less double-sheet".
When we prep a second ballot just in front of the scanner before accept of a first ballot, and the second ballot isn't close enough to trigger the sensors for the "remove your ballot" notice, the first ballot is ejected without the typical backwards wind-up. The second ballot can then be passed through the scanner without being counted.
Because we only consider the front of the scanner to have paper if all of the front …
=> Protect against wind-up-less double-sheet

apps/scan/backend/src/scanners/custom/state_machine.ts, libs/custom-scanner/src/custom_a4_scanner.test.ts, libs/custom-scanner/src/custom_a4_scanner.ts, libs/custom-scanner/src/types.ts
Issue link: https://github.com/votingworks/vxsuite/issues/4326
See **#issue-custom-scanner-state-machine-v3** in Slack for lots of additional context.
In our stress testing of the scanner state machine, we've identified edge cases that are unlikely to come up in real use but that we want to protect against regardless. One such issue we've dubbed "double-sheet w wind-up" (distinct from "[wind-up-less double sheet](https://github.com/votingworks/vxsuite/pull/4395)").
When a second ballot is inserted as a first ballot is being accepted, it's possible for the second ballot to be passed through the scanner without being counted. The timing has to be just right to escape the existing safeguards in the state machine. But there are other conditions that also have to …
=> Protect against double-sheet w wind-up

apps/scan/frontend/src/components/misvote_warnings/contest_list.tsx, libs/mark-flow-ui/src/components/button_footer.tsx, libs/mark-flow-ui/src/components/ms_either_neither_contest.tsx, libs/mark-flow-ui/src/pages/cast_ballot_page.tsx, libs/mark-flow-ui/src/pages/start_page.tsx, libs/types/src/ui_theme.ts, libs/ui/src/bmd_paper_ballot.stories.tsx, libs/ui/src/button.test.tsx, libs/ui/src/themes/make_theme.ts
Now that we've fully moved onto the expanded color roles, we can remove the deprecated legacy color roles and the corresponding color definitions (note that these colors have already been preserved in new definitions).
N/A
=> Cleanup legacy colors

libs/auth/src/artifact_authentication.ts
Just noticed this interesting failure in CI and realized that I've seen it before. It isn't a flaky test but a real issue!
Still wrapping my mind around what causes the signature length to vary, but the current theory is that it has something to do with truncation of leading 0s. So while 72 is the right upper bound, 70 and even 69 aren't ideal lower bounds. Landing on 60 as a super safe lower bound.
Will open an issue to revisit this and fully understand it. We can update the bounds accordingly, then.
=> Fix bad assumption re signature length in .vxsig files

apps/admin/backend/src/app.ts, apps/admin/backend/src/tabulation/card_counts.ts, apps/admin/backend/src/tabulation/full_results.ts, apps/admin/backend/src/util/filters.test.ts, apps/admin/backend/src/util/filters.ts, apps/admin/frontend/src/components/admin_tally_report_by_party.tsx, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.test.tsx, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx, apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.test.tsx, apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.tsx, apps/admin/frontend/src/components/reporting/export_tally_report_csv_button.test.tsx, apps/admin/frontend/src/components/reporting/export_tally_report_csv_button.tsx, apps/admin/frontend/src/components/reporting/filter_editor.test.tsx, apps/admin/frontend/src/components/reporting/filter_editor.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.test.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx, apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.tsx, apps/admin/frontend/src/screens/reporting/tally_report_builder.tsx, apps/admin/frontend/src/utils/election.ts, apps/admin/frontend/src/utils/reporting.test.ts, apps/admin/frontend/src/utils/reporting.ts, apps/admin/frontend/test/helpers/mock_api_client.ts, libs/types/src/admin/reporting.ts, libs/ui/src/reports/admin_tally_report.tsx, libs/ui/src/reports/ballot_count_report.tsx, libs/ui/src/reports/custom_filter_summary.test.tsx, libs/ui/src/reports/custom_filter_summary.tsx, libs/utils/src/tabulation/lookups.ts
Closes #4275.  Adds ability to filter by "District" to the report builders. This could include things like wards, cities, sub-jurisdictions, etc.
Under the hood, it just converts a list of districts to a list of ballot styles. We don't have districts arranged in the election definition in such a way that we can do groupings by them, just filtering.
https://github.com/votingworks/vxsuite/assets/37960853/d7062f5d-91ad-4beb-88cb-04afed43c278
I had trouble thinking of a good way to write resilient tests for this. At each endpoint in `app.ts` on the backend, we convert from the frontend filter format, which contains district IDs, to a the more basic version. Ideally testing would ensure this always happens, but it's laborious because there's four endpoints to test and no existing fixtures. I …
=> VxAdmin: Add District Filtering

apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/scan/backend/package.json, apps/scan/backend/src/app_usb_drive.test.ts, libs/auth/src/live_check.test.ts, libs/backend/src/cast_vote_records/export.test.ts
VxSuite tests have gotten quite flaky lately. Using the list of flaky tests on the (super helpful) [CI insights page](https://app.circleci.com/insights/github/votingworks/vxsuite/workflows/test/tests?branch=main) as a guide, I've made a number of small tweaks to decrease flakiness. More on the specifics of the fixes in GitHub comments.
=> Decrease VxSuite test flakiness

apps/design/backend/src/store.ts
Fixes: #4063 
There was a well-intentioned assertion guarding against an edge case in primary elections where there were no partisan contests (which would result in no ballot styles being generated). The intention was to explain to the user why there were no ballot styles in that case. However, crashing the app until partisan contests are added prevents the user from being able to address the issue, so it was not a good solution.
N/A
Manual test
=> VxDesign: Fix bug for primary elections

apps/design/frontend/jest.config.js, apps/design/frontend/src/api.ts, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/nav_screen.tsx, apps/design/frontend/src/utils.test.ts, apps/design/frontend/src/utils.ts
Fixes #4067, #4068
Fixes a few bugs with the contests form:
- Create globally unique contest/candidate IDs (ended up implementing a solution for all forms that create IDs)
- Use candidate index instead of candidate ID when making local state updates, since ID may be edited
Also adds tests for the contests form and cleans up some small bits of styling.
N/A
Added tests
=> VxDesign: Fix bugs in contests form

libs/utils/.eslintrc.json, libs/utils/src/json_stream.test.ts, libs/utils/src/json_stream.ts
Since I was keeping track of _all_ objects that had been serialized as part of the initial `jsonStream` call, this would fail to serialize:
```ts
const o = {};
jsonStream([o, o]);
```
That's not a cycle, so it should be fine. This change updates the cycle tracking to only look at the ancestors of the current object being serialized.
While I was making this change I remembered that `JSON.stringify` respects `toJSON` being defined on objects, so I added that feature.
=> fix(utils): correct `jsonStream` cycle false positive

apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/election_info_screen.tsx
This is a more flexible term that can encompass non-county entities like NH towns and cities.
Update automated test
=> VxDesign: Rename County -> Jurisdiction

apps/scan/frontend/jest.config.js, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx
When switching from test mode to official mode while a CVR sync is required, you may see a flicker of the warning message typically displayed when you try to switch in the reverse direction (from official mode to test mode) without syncing CVRs first.
To repro reliably in dev, I had to slow down USB drive status polling:
https://github.com/votingworks/vxsuite/assets/12616928/5cafee1d-bb67-43d8-8906-f060dc9a0ae2
I think we're seeing this more reliably in prod, probably because our prod machines aren't as performant as our dev machines.
This PR fixes the issue by invalidating the USB drive status React query on mode switch, instead of just waiting for the next poll.
We didn't catch this earlier because the warning used to live in a modal, only surfaced when you …
=> Avoid warning flicker when switching from test mode to official mode while a CVR sync is required

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iter.test.ts, libs/basics/src/iterators/iter.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts, libs/utils/src/ballot_styles.ts
Adds `IteratorPlus::isEmpty` and allows the argument to `iter` to be nullish, treating such values as an empty iterator. This allows for more succinctly checking whether e.g. a possibly-nullish array is empty:
```ts
iter(election.gridLayouts).isEmpty()
```
This changes one place where we were previously using `lodash.isempty` to use this pattern.
=> feat(basics): add `IteratorPlus::isEmpty`

apps/admin/frontend/src/screens/reporting/reports_screen.test.tsx, apps/admin/frontend/src/screens/reporting/reports_screen.tsx
Hides WIA report section and link button when there are no WIA contests. Closes #4414. 
w/ write-ins:
w/o write-ins:
- automated coverage
- manual check
=> hide WIA report when no write-in contests

libs/backend/src/cast_vote_records/build_cast_vote_record.test.ts, libs/backend/src/cast_vote_records/build_cast_vote_record.ts, libs/ballot-interpreter/test/fixtures/m17-backup/cast-vote-record-report.json, libs/fixtures/data/electionGridLayoutNewHampshireTestBallot/castVoteRecords/manual/864a2854-ee26-4223-8097-9633b7bed096/cast-vote-record-report.json, libs/types/src/cdf/cast-vote-records/index.test.ts, libs/types/src/cdf/cast-vote-records/index.ts, libs/types/src/cdf/cast-vote-records/vx-schema.json, libs/utils/src/votes.test.ts, libs/utils/src/votes.ts
In pursuit of removing custom fields from the CVR CDF, removes `vxWriteIns`.
=> Remove `vxWriteIns` from CVR

libs/auth/src/cast_vote_record_hashes.test.ts, libs/backend/src/cast_vote_records/build_report_metadata.ts, libs/backend/src/split.test.ts, libs/ballot-encoder/src/bits/bit_writer.ts, libs/ballot-encoder/src/bits/utils.ts, libs/custom-paper-handler/src/cli/driver_cli.ts, libs/custom-paper-handler/src/driver/scanner_capability.ts, libs/custom-paper-handler/src/printing.ts, libs/cvr-fixture-generator/src/cli/generate/main.test.ts, libs/cvr-fixture-generator/src/generate_cvrs.ts, libs/cvr-fixture-generator/src/utils.ts, libs/utils/src/json_stream.test.ts
I looked for places where we were building an array using `.push` inside a `for` loop and found some that I thought could be improved using `IteratorPlus`, either with `iter` directly or one of the helpers like `integers`. There are more, but this seemed like a good starting point of the ones that I felt were fairly clearly better this way.
n/a
=> refactor: use `IteratorPlus` in a few more places

apps/scan/backend/src/app.ts, apps/scan/backend/src/app_flow.test.ts, apps/scan/backend/src/app_flow.ts, apps/scan/backend/src/globals.ts, apps/scan/backend/src/index.ts, apps/scan/backend/src/scanners/custom/app_scan.test.ts, apps/scan/backend/src/scanners/custom/app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/custom/app_scan_jam.test.ts, apps/scan/backend/src/scanners/custom/app_scan_power_off.test.ts, apps/scan/backend/src/scanners/custom/app_scan_precinct_config.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/types.ts, apps/scan/backend/src/util/construct_auth_machine_state.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/backend/test/helpers/shared_helpers.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, libs/types/src/precinct_scanner.ts
This change copies the logic from the frontend that controlled whether to trigger a scan into the backend. Most of that logic was in deciding which screen to render, with the last part on the `VoterScreen` itself. In the future it might make sense to render the screen based on the new backend status I'm calling "app flow state", but I wanted to make minimal changes to the frontend as part of this change.
Note in this video that we never call the `scanBallot` endpoint (which no longer exists):
https://github.com/votingworks/vxsuite/assets/1938/e1615fe5-8162-41a4-a440-d03accb3c74c
=> [VxScan] Decide when to scan on the backend

libs/auth/scripts/cac/configure_simulated_cac_card.ts, libs/auth/scripts/configure_java_card.ts, libs/basics/src/iterators/index.ts, libs/basics/src/iterators/lines.test.ts, libs/basics/src/iterators/lines.ts, libs/hmpb/layout/src/layout.ts, libs/image-utils/test/utils.ts, libs/monorepo-utils/src/pnpm.ts
The changes made as part of this PR are fairly trivial examples where we're working on relatively small strings, so at best this is a minor improvement in semantic clarity and in correctness (splits on `\r\n` and `\n`). However, the real benefit comes when working on large files where we would previously read the whole file because it's easier. See below for an example.
Helps us avoid running afoul of the problem described in #4443.
```ts
// old
const contents = fs.readFileSync(path, { encoding: 'utf8' });
const lines = contents.split('\n');
for (const line of lines) {
…
}
// new
const input = fs.createReadStream(path, { encoding: 'utf8' });
for await (const line of lines(input)) {
…
}
```
=> feat(basics): add `lines` iterator helper

libs/utils/src/json_stream.test.ts, libs/utils/src/json_stream.ts
These already worked, but they didn't type check properly.
See new tests for an example.
=> fix(utils): allow `jsonStream` to accept iterables at any nesting level

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/lines.ts, libs/basics/src/iterators/types.ts
Adds `groupBy` and `filterMap` in the same style as the equivalents from Rust's [`std::iter::Iterator`](https://doc.rust-lang.org/1.74.1/std/iter/trait.Iterator.html). Adds examples to most of the existing methods.
```ts
const messages = [
{ author: 'Brian', content: 'Are we `std::iter::Iterator` yet?' },
{ author: 'Brian', content: 'We seem to be close.' },
{ author: 'Jonah', content: '🫠' },
{ author: 'Brian', content: '🦀🎉' },
];
for (const messageRunByAuthor of iter(messages).groupBy(
(a, b) => a.author === b.author
)) {
console.log(`${messageRunByAuthor?.[0]?.author} said:`);
for (const { content } of messageRunByAuthor) {
console.log(`  ${content}`);
}
}
// Brian said:
//   Are we `std::iter::Iterator` yet?
//   We seem to be close.
// Jonah said:
//   🫠
// Brian said:
//   🦀🎉
```
=> `IteratorPlus` docs & a couple more methods

.circleci/config.yml, docs/development/best_practices/typescript.md, docs/exercises/.eslintignore, docs/exercises/.eslintrc.json, docs/exercises/01-iteration/01-toArray.exercise.ts, docs/exercises/01-iteration/02-map.exercise.ts, docs/exercises/01-iteration/03-filter.exercise.ts, docs/exercises/01-iteration/04-take.exercise.ts, docs/exercises/01-iteration/05-async.exercise.ts, docs/exercises/01-iteration/06-json.exercise.ts, docs/exercises/01-iteration/07-math.exercise.ts, docs/exercises/01-iteration/08-advanced.exercise.ts, docs/exercises/README.md, docs/exercises/jest.config.js, docs/exercises/package.json, docs/exercises/src/collecting.ts, docs/exercises/src/example.ts, docs/exercises/src/todo.ts, docs/exercises/tsconfig.json, libs/utils/src/json_stream.ts, pnpm-lock.yaml, pnpm-workspace.yaml
Adds some interactive exercises to teach the basics of using `iter`. Also updates the best practices doc with some specific reasons to use the iteration helpers.
One of the intermediate `iter` exercises:
```ts
// 04-async.ts
//
// Task: Complete the `countNonBlankLines` function using `lines` to count the
// number of non-blank lines in the the file at a given path.
//
// Note: `lines` returns an `AsyncIterablePlus<string>`, which is an async
// iterable. You can use the same set of methods on the async version as with
// the sync version, but they return and accept promises instead of values.
import { lines } from '@votingworks/basics';
import { readFile } from 'fs/promises';
import { TODO } from '../src/todo';
import { run } from '../src/example';
async function countNonBlankLines(path: …
```
=> docs: add exercises and docs for `iter`

docs/exercises/01-iteration/03-filter.exercise.ts, docs/exercises/01-iteration/09-image-diff.exercise.ts
- Fixes a type issue on the 03-filter exercise
- Adds a new 09-image-diff exercise
=> Iter exercises tweak and addition

apps/admin/backend/src/app.ts, apps/admin/backend/src/exports/csv_ballot_count_report.test.ts, apps/admin/backend/src/exports/csv_ballot_count_report.ts, apps/admin/backend/src/exports/csv_tally_report.test.ts, apps/admin/backend/src/exports/csv_tally_report.ts, apps/admin/backend/src/util/export_file.ts, apps/admin/backend/test/csv.ts, libs/backend/src/exporter.test.ts, libs/backend/src/exporter.ts
Allows export functions to accept iterables, which are generally easier to create than streams. Converts a couple simple cases that exposed streams but were already using iterables internally to just expose the iterables directly.
n/a
=> Allow exporting from iterables

apps/design/backend/src/app.ts, apps/design/frontend/package.json, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/utils.ts, apps/design/frontend/test/id_helpers.tsx, apps/design/frontend/test/setupTests.ts, pnpm-lock.yaml
Closes #4423 
Instead of generating human-readable IDs for districts, precincts, contests and parties, generate random unique IDs. Also, remove the ability for users to edit those IDs.
This will help ensure global ID uniqueness in the election definition and make sure referential integrity is maintained (e.g. since a party's ID never changes, any references to that party will never need to change).
Contests table now has "Type" column instead of "ID" column
=> VxDesign: Stable entity IDs

libs/ui/src/hooks/use_audio_controls.test.tsx, libs/ui/src/hooks/use_audio_controls.ts, libs/ui/src/index.ts, libs/ui/src/ui_strings/audio_context.test.tsx, libs/ui/src/ui_strings/audio_context.tsx, libs/ui/src/ui_strings/audio_playback_rate.ts, libs/ui/src/ui_strings/audio_volume.ts, libs/ui/src/ui_strings/ui_strings_context.tsx, libs/ui/test/ui_strings/test_utils.tsx
Fleshing out the `UiStringsAudioContext` (renamed from `AudioContext` to avoid the name collision with the native web audio API) to manage global audio settings and expose controls for modifying them.
Adding a `useAudioControls` hook to externally expose the parts of the `UiStringsAudioContext` that need to be available outside of `libs/ui`. Future PRs will add the internal audio playback utilities that make use of the remaining context values.
- Unit tests for the context API and external hook
- Some manual testing with a local prototype 
- ~[ ] I have added a screenshot and/or …
=> [i18n/Audio] Expose audio controls via the UiStringsContextProvider

apps/central-scan/backend/src/store.ts, apps/scan/backend/src/store.ts
This has been unused since #1456 when it became the responsibility of the `DbClient` class, but it was never removed from the `Store` classes.
n/a
=> chore: remove unused `Store.getSchemaDigest` method

libs/ui/src/ui_strings/audio_context.tsx
Fixing an issue from https://github.com/votingworks/vxsuite/pull/4463 with unused `AudioContext` instances getting created on re-renders of the `UiStringsAudioContextProvider`. Ensuring that we only create an `AudioContext` once per app load.
- Existing automated tests + manual testing with debug logging
=> [i18n/audio] Fix repeated web AudioContext instantiations

apps/design/backend/jest.config.js, apps/design/backend/package.json, apps/design/backend/schema.sql, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/index.ts, apps/design/backend/src/server.ts, apps/design/backend/src/store.test.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/index.ts, apps/design/backend/src/worker/tasks.ts, apps/design/backend/src/worker/worker.ts, apps/design/backend/src/workspace.ts, apps/design/backend/test/helpers.ts, apps/design/backend/tsconfig.build.json, apps/design/backend/tsconfig.json, apps/design/frontend/jest.config.js, apps/design/frontend/package.json, apps/design/frontend/src/api.ts, apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/export_screen.tsx, apps/design/frontend/src/utils.test.ts, apps/design/frontend/src/utils.ts, apps/design/frontend/tsconfig.json, pnpm-lock.yaml
This PR moves election package generation to VxDesign's background worker. Election package generation is likely to get much slower once we start translating and generating audio clips, so it'll no longer be reasonable to perform it synchronously. The patterns established in this PR can also be used to handle ballot and test deck generation asynchronously.
The UX is still pretty bare bones. We can add progress bars and other optimizations in future PRs. We may also want to distinguish the act of generating the election package and downloading it. Note that I've artificially slowed down election package generation for this video 🐌
https://github.com/votingworks/vxsuite/assets/12616928/a30e6738-9033-48b2-80ac-a69dac53f372
_Error handling_ …
=> Move election package generation to VxDesign's background worker

libs/hmpb/layout/package.json, libs/hmpb/layout/src/layout.test.ts, libs/hmpb/layout/src/layout.ts, libs/hmpb/layout/tsconfig.json, pnpm-lock.yaml
Closes #4369 
NH runs simultaneous town and school district elections. The ballots for these two elections need to be scanned on the same scanner, meaning they must use the same election definition. However, they need to show a different election title on the ballot. For now, we add a special case in the ballot layout code to support this.
https://github.com/votingworks/vxsuite/assets/530106/34818b5e-81e5-4c97-aa86-bd9185387314
- Added unit test
- Manual test in VxDesign
=> Change election title on ballots for NH school districts

apps/design/backend/src/app.test.ts, apps/design/backend/src/worker/context.ts, apps/design/backend/src/worker/generate_election_package.ts, apps/design/backend/src/worker/tasks.ts, apps/design/backend/src/worker/worker.ts, apps/design/backend/test/helpers.ts
This PR translates app strings and adds them to election packages exported by VxDesign, in the format expected by VxSuite machines. The first translation run, before the VxDesign translation cache was populated, was actually quite fast! (The slowest part of language and audio file generation is going to be speech synthesis.)
https://github.com/votingworks/vxsuite/assets/12616928/d39e032a-ebe7-4974-81d3-b816bc0a5e28
=> Translate app strings and add to election packages

libs/mark-flow-ui/src/pages/start_page.tsx, libs/ui/src/ui_strings/index.ts, libs/ui/src/ui_strings/read_on_load.test.tsx, libs/ui/src/ui_strings/read_on_load.tsx
Replacing the existing pattern of assigning `id='audiofocus'` to introductory sections of pages with a dedicated `<ReadOnLoad>` component.
The upcoming pre-generated audio "screen reader" will get triggered by focus/click events in the same way the kiosk-browser screen reader does. This component mostly mirrors the functionality in the old BMD `FocusManager` by simulating a user click on its container element, but there's room later improvement if we want to have a way of queuing up multiple sections of a page with multiple `<ReadOnLoad>` instances.
Will be following up later with PRs to update the other `id='audiofocus'` instances.
https://github.com/votingworks/vxsuite/assets/264902/64fc4f24-b0c0-42f4-924a-f853c5d48370
- Unit tests + manual verification with prototype audio player.
- ~[ …
=> [i18n/audio] Add <ReadOnLoad> for reading intro text on page/route load

apps/design/backend/src/app.test.ts, apps/design/backend/src/worker/generate_election_package.ts
We want to translate election date, but there isn't an `InternationalizedText` field in the CDF schema for it. This PR accordingly translates election date and adds it to election packages via the `vxElectionStrings.json` file that @kofi-q introduced in https://github.com/votingworks/vxsuite/pull/4202.
_Sample `vxElectionStrings.json` file_
```json
{
"zh-Hans": {
"electionDate": "2024年1月1日"
},
"zh-Hant": {
"electionDate": "2024年1月1日"
},
"en": {
"electionDate": "January 1, 2024"
},
"es-US": {
"electionDate": "1 de enero de 2024"
}
}
```
=> Translate election date and add to election packages

apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_setup_errors.test.tsx, apps/mark-scan/frontend/src/pages/insert_card_screen.test.tsx, apps/mark-scan/frontend/src/pages/insert_card_screen.tsx
https://github.com/votingworks/vxsuite/issues/4471
Removes a message that warns when an accessible controller is not connected. This is a leftover from VxMark's detachable controller. VxMarkScan's controller isn't detachable and so should always be connected.
There's an argument to be made that we should still check for the built-in controller's connection status. While a hardware failure is unlikely, it might be worth it to add this back in the future. However, continually reporting connection status to the frontend requires a little planning so for now we should remove this misleading error.
Before
After
=> remove irrelevant accessible controller connection warning

apps/mark-scan/frontend/src/components/centered_page_layout.tsx, apps/mark-scan/frontend/src/pages/card_error_screen.tsx, apps/mark-scan/frontend/src/pages/insert_card_screen.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark-scan/frontend/src/pages/replace_election_screen.tsx, apps/mark-scan/frontend/src/pages/validate_ballot_page.tsx, apps/mark-scan/frontend/src/pages/wrong_election_screen.tsx, apps/mark-scan/frontend/src/utils/trigger_audio_focus.ts, apps/mark/frontend/src/pages/card_error_screen.tsx, apps/mark/frontend/src/pages/insert_card_screen.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/src/pages/replace_election_screen.tsx, apps/mark/frontend/src/pages/wrong_election_screen.tsx, apps/mark/frontend/src/utils/trigger_audio_focus.ts, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/contest_header.tsx, libs/mark-flow-ui/src/components/yes_no_contest.tsx, libs/mark-flow-ui/src/pages/cast_ballot_page.tsx, libs/mark-flow-ui/src/pages/idle_page.tsx, libs/mark-flow-ui/src/pages/print_page.tsx, libs/mark-flow-ui/src/pages/review_page.tsx, libs/ui/src/__snapshots__/modal.test.tsx.snap, libs/ui/src/modal.test.tsx, libs/ui/src/modal.tsx
Using the `<ReadOnLoad>` component added in https://github.com/votingworks/vxsuite/pull/4483 on voter-facing screens and modals in the BMD apps. This replaces the previous `id="audiofocus"`/`id="modalaudiofocus"` tags and removes them altogether from non-voter-facing screens/modals.
Adding a default `<ReadOnLoad>` instance to the shared `<Modal>` component, which can be disabled for more complex modals (e.g. the write-in candidate modal, where we only want a portion of the modal content to be read on open). This is a no-op for apps with no audio and/or translations and also a no-op when there are no `<UiString>` instances in the modal. That being said, open to defaulting to autoplay disabled and having voter-facing modals explicitly enable it, if that feels more appropriate. …
=> [i18n/audio] Use <ReadOnLoad> component in BMD screens and modals

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
Per https://github.com/votingworks/vxsuite/pull/4489#discussion_r1446390035.
Keeps `iter.toString` as an alias for `iter.join` as it's semantically nicer when there's no separator.
n/a
- Updated tests.
=> feat(basics): rename `iter.toString` to `iter.join`

apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/custom-paper-handler/types.ts, apps/mark-scan/frontend/src/app_cardless_voting.test.tsx, apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_states.test.tsx, apps/mark-scan/frontend/src/pages/ballot_invalidated_page.test.tsx, apps/mark-scan/frontend/src/pages/ballot_invalidated_page.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark-scan/frontend/src/pages/remove_invalidated_ballot_page.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/3909
Improves the flow for spoiling a ballot in post-print ballot validation
* Rather than restarting the voter session, the session is saved. The voter is returned to the review screen after the poll worker removes the old ballot, loads a new sheet, and removes their card
* The ballot spoil flow now checks that the ballot is removed by the poll worker before allowing the poll worker to continue
Happy path
https://github.com/votingworks/vxsuite/assets/1060688/75a28cb1-e35f-44ee-8213-bccd34d25a42
Lightly stress testing pulling paper early and repeated auth changes
https://github.com/votingworks/vxsuite/assets/1060688/a89d9fa6-8547-4c7f-9662-7bf8205a3abc
- updated component and e2e tests
=> Save voter session on ballot spoil

apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts
https://github.com/votingworks/vxsuite/issues/4470
Fixes a bug where test mode was hardcoded for interpretation
N/A
=> pull test mode from store when interpreting

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/src/test_decks.test.ts, apps/design/backend/src/worker/generate_election_package.ts, apps/design/frontend/jest.config.js, apps/design/frontend/src/ballot_screen.tsx, apps/design/frontend/src/ballot_viewer.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/utils.test.ts, apps/design/frontend/src/utils.ts, apps/design/frontend/test/fixtures.ts, libs/hmpb/layout/src/layout.test.ts, libs/hmpb/layout/src/layout.ts, libs/hmpb/render-backend/src/ballot_fixtures.ts
Changing the solution for #4369. In #4482, we hardcoded an election title override for NH school district elections. However, we have more customizations needed for school district elections (e.g. adding a clerk signature: #4481). So we'll need a way to attach custom content to precinct splits (which is how we'll model the town and school elections - each will have its own precinct split).
This PR removes the election title override hardcoding and instead adds a field for a custom election title override to the precinct split form.
https://github.com/votingworks/vxsuite/assets/530106/285f9b46-c4e0-49a5-9860-330d6870ccfa
- Added new tests to cover the geography screen
- Some basic manual testing
=> VxDesign: Add custom election title field to precinct split form

libs/ui/src/set_clock.test.tsx
Calling `aDate.set` with a time that is exactly the daylight savings time border changes the time zone offset, whereas the date returned from the modal retains the original offset.
=> Fix flaky property test for PickDateTimeModal

apps/design/backend/src/app.test.ts, apps/design/frontend/jest.config.js, apps/design/frontend/src/ballot_screen.tsx, apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/image_input.tsx, libs/hmpb/layout/src/document_svg.tsx, libs/hmpb/layout/src/document_types.ts, libs/hmpb/layout/src/layout.test.ts, libs/hmpb/layout/src/layout.ts, libs/ui/src/button.tsx, libs/ui/src/card.tsx, libs/ui/src/file_input_button.tsx
Closes #4481 
Builds on #4495 to allow uploading a clerk signature image and caption for a precinct split. The image and caption are rendered in the ballot header.
https://github.com/votingworks/vxsuite/assets/530106/fc39ba69-3b38-42e9-ba29-7a804da499f4
- Manual test that layout works with signatures of varied length/image size (captured in video)
=> VxDesign: Add clerk signature image/caption custom content to ballots

apps/admin/backend/package.json, apps/admin/backend/src/index.ts, apps/central-scan/backend/package.json, apps/central-scan/backend/src/index.ts, apps/design/backend/package.json, apps/design/backend/src/index.ts, apps/design/backend/src/worker/index.ts, apps/design/backend/tsconfig.build.json, apps/design/backend/tsconfig.json, apps/mark-scan/backend/package.json, apps/mark-scan/backend/src/index.ts, apps/mark/backend/package.json, apps/mark/backend/src/index.ts, apps/scan/backend/package.json, apps/scan/backend/src/index.ts, libs/backend/package.json, libs/backend/src/dotenv.ts, libs/backend/src/index.ts, pnpm-lock.yaml
This PR moves repeated dotenv logic to `libs/backend` and adds dotenv logic to the VxDesign backend. This logic is necessary for our `.env*` file based feature flagging to work in app backends.
Doing this as a pre-req before I add a feature flag for skipping cloud translation and speech synthesis in VxDesign.
Manually tested that env vars in `.env` files are still properly recognized in app backends
=> Move repeated dotenv logic to libs/backend and add dotenv logic to VxDesign backend

libs/printing/package.json, libs/printing/src/printer/cli.ts, libs/printing/src/printer/configure.test.ts, libs/printing/src/printer/configure.ts, libs/printing/src/printer/device_uri.test.ts, libs/printing/src/printer/device_uri.ts, libs/printing/src/printer/print.test.ts, libs/printing/src/printer/print.ts, libs/printing/src/printer/types.ts, libs/printing/src/utils/exec.test.ts, libs/printing/src/utils/exec.ts, libs/printing/test/args_worker.js, libs/printing/test/echo_worker.js, pnpm-lock.yaml
- use `test.each` rather than reimplementing it
- allow printing from a stream of data
- make `exec` return `Result`
- test `exec` using real `child_process.spawn`
- use `iter` for processing `lpinfo` stdout
- use `never` return type for never-returning function
=> various improvements & PR feedback for #4502

apps/design/frontend/jest.config.js, apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/image_input.test.tsx, apps/design/frontend/src/image_input.tsx
Closes #4500 
Adds support for PNG/JPEG images for seals and clerk signatures by embedding them within an SVG using the `<image>` tag.
- Added unit tests for `ImageInput`
- Manually tested uploading a PNG seal and rendering ballots/configuring VxAdmin
=> VxDesign: Support bitmap image uploads (PNG and JPEG)

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/candidate_rotation.test.ts, apps/design/backend/src/candidate_rotation.ts
Closes #4514 
Automatically re-orders the candidates of all contests whenever the election is saved. This ensures that the candidate order on the ballot follows the NH statutes.
https://github.com/votingworks/vxsuite/assets/530106/1c16a2c2-2594-415c-9858-7dc8366b11d4
- Some basic manual testing
=> VxDesign: Rotate contest candidates on save

apps/design/backend/jest.config.js, apps/design/backend/src/store.test.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/worker.ts
At some point during my testing of VxDesign, I ctrl-c'd the worker while a background task was being processed. On subsequent VxDesign startup, the UI was "locked," indicating that a background export operation was in progress when one was not.
This PR updates the VxDesign background worker to requeue interrupted tasks on startup.
Arlo uses a very similar cleanup mechanism.
=> Requeue interrupted background tasks on VxDesign worker startup

apps/design/backend/scripts/synthesize_speech.ts, apps/design/backend/scripts/translate_text.ts, apps/design/backend/src/language_and_audio/index.ts, apps/design/backend/src/language_and_audio/translation_overrides.ts, apps/design/backend/src/language_and_audio/translator.test.ts, apps/design/backend/src/language_and_audio/translator.ts, apps/design/backend/test/helpers.ts, libs/types/src/language_code.ts
Cloud speech synthesis is great! Cloud translation is... good, but sometimes off. My favorite example is the Spanish translation of "Green Party" to "Fiesta Verde" 🟢 🎉 😆
We expect that election officials will proof translations and add their own overrides. But before we implement election-level overrides (which we will before cert), we should also have global Vx-managed overrides, to make the default translations as good as possible. This PR introduces a very rudimentary mechanism for that. We can build upon this rudimentary mechanism (e.g. with a UI and proper `Store` persistence) down the road.
=> Add mechanism for global Vx-managed translation overrides

apps/admin/frontend/src/screens/unconfigured_screen.test.tsx, apps/admin/frontend/src/screens/unconfigured_screen.tsx, apps/design/backend/src/app.test.ts, apps/design/backend/src/language_and_audio/app_strings.ts, apps/design/backend/src/worker/generate_election_package.ts, libs/backend/src/election_package/election_package_io.test.ts, libs/backend/src/election_package/election_package_io.ts, libs/types/src/election_package_metadata.ts, libs/types/src/index.ts
This PR adds a metadata file to the election packages exported by VxDesign. The metadata file specifies the machine version, which for now can only be "latest". We use the machine version to determine which strings to include in `appStrings.json` and will use it for other delineations down the road as well, as we have different versions of software running in the field.
https://github.com/votingworks/vxsuite/assets/12616928/d72c92fc-1dda-4035-a188-46575db54352
=> Add metadata file to election packages exported by VxDesign

apps/admin/backend/schema.sql, apps/admin/backend/src/adjudication.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/exports/csv_ballot_count_report.test.ts, apps/admin/backend/src/exports/csv_tally_report.test.ts, apps/admin/backend/src/store.test.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/card_counts.test.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/tabulation/manual_results.test.ts, apps/admin/backend/src/tabulation/write_ins.test.ts, libs/backend/src/election_package/election_package_io.test.ts, libs/backend/src/election_package/election_package_io.ts
The workflow for election packages involves the following steps:
1. Export an election package from VxDesign
2. Import the election package onto VxAdmin
3. Re-export the election package from VxAdmin, this time signed
4. Import the signed election package onto the other machines
This PR updates step 3 to include all the contents generated in step 1, specifically adding language and audio files. It does so by storing the entire election package zip file in the VxAdmin DB in step 2.
https://github.com/votingworks/vxsuite/assets/12616928/76b19c5d-dc69-4f66-80d4-b485f4424bb6
=> Update VxAdmin election package exports to include everything from VxDesign

apps/design/frontend/jest.config.js, apps/design/frontend/package.json, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/nav_screen.tsx, apps/design/frontend/src/utils.test.ts, apps/design/frontend/src/utils.ts, libs/ui/src/icons.tsx, libs/ui/src/left_nav.tsx, libs/ui/src/tabbed_section/tab_bar.tsx, libs/ui/src/with_scroll_buttons.tsx, pnpm-lock.yaml
Closes #4419 
Adds a button to reorder contests to the contests screen. When clicked, the screen enters reordering mode and the user can click up/down buttons to move contests around in the order. The user can then save or cancel changes.
I originally experimented with a drag-and-drop UX, but decided to go with the simpler up/down buttons as a starting point since it's easier to implement and easier to test. I suspect we may change this feature to support contest sections and state-specific rules, so I didn't want to invest too heavily in it yet.
https://github.com/votingworks/vxsuite/assets/530106/95f485cc-b9e8-4d0e-b7d0-9edcd302d8d5
=> VxDesign: Add form to reorder contests

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iter.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
Mainly this changes the `iter` classes to enforce that there is only ever one owner of the inner iterable. This reinforces the expected usage patterns and should prevent some potentially surprising behavior of trying to reuse iterables. The rest of the changes are just small cleanups.
For example, this would have previously produced the wrong values:
```ts
const options = iter(
allContestOptions(electionFamousNames2021Fixtures.election.contests[0])
);
const names = options.map((o) => o.name).toArray();
const ids = options.map((o) => o.id).toArray();
console.log({ names, ids });
// { names: [ 'Write-In' ], ids: [] }
```
Now it will properly throw an exception: `Error: inner iterable has already been taken`
=> Various `iter` improvements

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
This was a bit of a glaring omission since it's a fairly common operation on `Array`.
```ts
// without an explicit initial value
expect(integers().take(0).reduce((a, b) => a + b)).toBeUndefined();
expect(integers().take(10).reduce((a, b) => a + b)).toEqual(45);
// with an explicit initial value
expect(integers().take(0).reduce((a, b) => a + b, 0)).toEqual(0);
```
Updated automated tests.
=> feat(basics): add `reduce` method to `iter`

libs/ui/src/search_select.test.tsx, libs/ui/src/search_select.tsx
Fixes: #4499 
Previously, if an option was falsy, we would set the selected value to `null`. This prevented the corresponding option label from being displayed.
=> Fix bug in SearchSelect component to ensure falsy options are selectable

libs/ui/src/hooks/ui_strings_api.ts, libs/ui/src/hooks/use_audio_controls.test.tsx, libs/ui/src/hooks/use_audio_controls.ts, libs/ui/src/ui_strings/audio_context.test.tsx, libs/ui/src/ui_strings/audio_context.tsx, libs/ui/src/ui_strings/play_audio_clips.tsx, libs/ui/src/ui_strings/read_on_load.test.tsx, libs/ui/src/ui_strings/read_on_load.tsx, libs/ui/src/ui_strings/ui_string_screen_reader.test.tsx, libs/ui/src/ui_strings/ui_string_screen_reader.tsx, libs/ui/src/ui_strings/ui_strings_context.tsx
Adding a `<UiStringsScreenReader>`, installed via `<UiStringsContextProvider>`. 
Listens for `focus`/`click` events and queues up audio for any voter-facing strings contained in the event target (using recently added `data-i18n-key` and `data-language-code` attributes available on `<UiString>`s).
This doesn't yet include the actual audio player -- will be following up with additional PRs to flesh out that functionality.
https://github.com/votingworks/vxsuite/assets/264902/8f4a1c51-3d11-4e2c-b1c2-5f9ace44a8b1
- New & updated unit test cases.
- Manual verification with a prototype audio player & demo data.
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage …
=> [i18n/audio] Add <UiStringsScreenReader> to trigger audio from focus/click events

apps/mark-scan/backend/src/custom-paper-handler/constants.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/custom-paper-handler/types.ts, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_states.test.tsx, apps/mark-scan/frontend/src/pages/ballot_successfully_cast_page.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/4475
Adds a screen to confirm a ballot was successfully cast. The screen borrows from [scan_success_screen](https://github.com/votingworks/vxsuite/blob/main/apps/scan/frontend/src/screens/scan_success_screen.tsx) in VxScan.
=> Add ballot cast confirmation screen to mark-scan

apps/mark-scan/accessible-controller/src/controllerd.rs, libs/test-utils/src/fake_use_audio_controls.ts, libs/types/src/ui_audio_controls.ts, libs/ui/src/hooks/use_audio_controls.test.tsx, libs/ui/src/hooks/use_audio_controls.ts, libs/ui/src/ui_strings/audio_context.test.tsx, libs/ui/src/ui_strings/audio_context.tsx, libs/ui/src/ui_strings/keyboard_shortcut_handlers.test.tsx, libs/ui/src/ui_strings/keyboard_shortcut_handlers.tsx
Adding a `toggleEnabled()` audio control method to the `useAudioControls()` hook result for dev convenience, along with a `Shift+M` keyboard shortcut.
Also modifying the shortcut keys for playback rate adjustment from `[` and `]` to `,` and `.`. The former pair collides with the VxMark shortcuts for the "scroll down" and "select" actions respectively (unsure if there's a VxMark peripheral that triggers those keys, but figured it's easier just to remap the VxMarkScan controller).
- Updated unit tests
- Manually tested with prototype audio player
- ~[ ] I have added a screenshot …
=> [i18/audio] Expose toggleEnabled() audio control API method

libs/ui/package.json, libs/ui/src/ui_strings/audio_player.test.ts, libs/ui/src/ui_strings/audio_player.ts, pnpm-lock.yaml
Adding an `AudioPlayer` implementation for the `UiStringsScreenReader`.
Currently using the `GrainPlayer` from [`Tone.js`](https://tonejs.github.io/), which is primarily intended for music applications, but provided the least glitchy implementation of pitch-invariant playback rate control that I found. It's working well as a v1 -- we could choose to write our own implementation later down the line if we find functional or performance issues once we've tested on prod hardware.
- After some idle time with no audio playing, the next clip played stutters a for a fraction of a second, so we may need to play some quiet warmup audio at regular intervals during moments of silence to smooth that out.
- Switching up from slower playback rates causes some audio to be lost, due to way data is …
=> [i18n/audio] Implement screen reader audio playback

apps/mark-scan/frontend/src/app.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark/frontend/src/app.test.tsx, apps/mark/frontend/src/app_root.tsx, libs/mark-flow-ui/src/hooks/use_session_settings_manager.test.tsx, libs/mark-flow-ui/src/hooks/use_session_settings_manager.ts, libs/mark-flow-ui/src/index.ts, libs/ui/src/ui_strings/audio_context.test.tsx, libs/ui/src/ui_strings/audio_context.tsx
Resetting language and audio settings every time a new voter session is started -- hooking into the same points as the existing display settings reset logic.
Also resetting to the default language whenever a non-voter login happens during a voting session -- some translated visual elements are shared between voter and non-voter screens, like the election info bar, so this ensures that non-voters are always presented with a fully English UI.
- Additional test cases for language and audio resets
- Manual verification
- ~[ ] I have added a screenshot and/or video to this PR to demo …
=> [i18n/audio] Reset language and audio settings before every new voting session

libs/auth/scripts/cac/configure_simulated_cac_card.ts, libs/auth/scripts/configure_java_card.ts, libs/auth/src/apdu.test.ts, libs/auth/src/apdu.ts
Issue link: https://github.com/votingworks/vxsuite/issues/4184
This PR updates VxSuite to support our new JCOP 4 Java Card stock, while still maintaining support for our old JCOP 3 Java Card stock. The change ultimately didn't involve any machine code, just initial Java Card configuration script code, which means that we could even use JCOP 4 Java Cards on v3.1 machines that we're shipping to NH, should the need ever arise.
Tested manually with both JCOP 4 and JCOP 3 Java Cards
=> Support JCOP 4 Java Cards

apps/design/frontend/jest.config.js, apps/design/frontend/src/elections_screen.test.tsx, apps/design/frontend/src/elections_screen.tsx
To help differentiate elections, convert the election list from a list of buttons to a table that shows title, date, jurisdiction, and state.
https://github.com/votingworks/vxsuite/assets/530106/7123be9d-8343-4943-9517-6dbdcbe69880
Added new unit tests
=> VxDesign: List elections using table

libs/hmpb/layout/src/layout.test.ts, libs/hmpb/layout/src/layout.ts
Causes rich text parsing to fail if the tags are unclosed or mismatched.
=> fix: bail on unclosed/mismatched tags

libs/hmpb/layout/src/layout.ts
Some customers don't want to show a seal.
=> VxDesign 3.1: Support ballots without a seal

apps/mark-scan/frontend/src/components/centered_page_layout.tsx, apps/mark-scan/frontend/src/lib/assistive_technology.test.tsx, apps/mark-scan/frontend/src/pages/ballot_successfully_cast_page.tsx, apps/mark-scan/frontend/src/pages/pat_device_identification/confirm_exit_pat_device_identification_page.tsx, apps/mark-scan/frontend/src/pages/pat_device_identification/pat_device_identification_page.tsx, apps/mark-scan/frontend/src/pages/validate_ballot_page.tsx, apps/mark/frontend/src/lib/gamepad.test.tsx, apps/mark/integration-testing/e2e/scroll_buttons.spec.ts, libs/mark-flow-ui/src/components/contest_header.tsx, libs/mark-flow-ui/src/components/display_settings_button.tsx, libs/mark-flow-ui/src/components/voter_screen.tsx, libs/mark-flow-ui/src/index.ts, libs/mark-flow-ui/src/pages/cast_ballot_page.tsx, libs/mark-flow-ui/src/pages/contest_page.tsx, libs/mark-flow-ui/src/pages/review_page.tsx, libs/mark-flow-ui/src/pages/start_page.tsx, libs/ui/src/contest_choice_button.tsx, libs/ui/src/icons.tsx, libs/ui/src/index.ts, libs/ui/src/language_settings/index.ts, libs/ui/src/language_settings/language_settings_button.tsx, libs/ui/src/ui_strings/read_on_load.test.tsx, libs/ui/src/ui_strings/read_on_load.tsx
- Consolidating voter-facing BMD screens into a shared `<VoterScreen>` layout component to keep things visually consistent.
- Moving the "Display Settings" button out of the bottom bar into a new to bar and adding a stand-in language picker alongside it.
- For the landscape BMD, all buttons stay in the right side bar as before.
- The language settings button will be omitted for elections containing only one ballot language.
- Moving the contest number/progress indicator into the bottom/side bars to co-locate with the navigation buttons.
- Build out a language settings screen
- Start exporting a non-CDF `ballotLanguageName` election string text/audio for use in the language picker
- Update the "Display Settings" button to "Settings", since it now exposes audio settings as well. …
=> [BMD] Update voter-facing screen layouts to make room for language picker

libs/hmpb/layout/src/document_svg.tsx
Previously, we were just rendering the outermost tag. Now we traverse the tree and render nested tags.
=> VxDesign 3.1: Render nested HTML formatting tags

apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/app.tsx, apps/admin/frontend/src/components/app_routes.tsx, apps/admin/frontend/src/components/navigation_screen.tsx, apps/admin/frontend/src/router_paths.ts, apps/admin/frontend/src/screens/hardware_diagnostics_screen.test.tsx, apps/admin/frontend/src/screens/hardware_diagnostics_screen.tsx, apps/admin/frontend/test/helpers/mock_api_client.ts, libs/backend/src/system_call/get_battery_info.test.ts, libs/backend/src/system_call/get_battery_info.ts, libs/ui/src/battery_display.test.tsx, libs/ui/src/battery_display.tsx, libs/ui/src/battery_low_alert.test.tsx, libs/ui/src/battery_low_alert.tsx, libs/ui/src/icons.tsx, libs/ui/src/index.ts, libs/ui/test/test_context.tsx
Makes VxAdmin battery-aware, via three separate features:
1. Adds a battery display to the nav bar which indicates a variably filled battery icon, the percent, and a charge icon if the laptop is charging.
2. Creates a modal alert when the battery level drops to a warning level. Currently I have **dismissable** warnings at 15%, 10%, and 5%, and a non-dismissable warning at 1%.
3. Adds the same battery info the diagnostics screen.
=> admin(feat): battery status

apps/design/backend/src/app.test.ts, apps/design/backend/src/language_and_audio/election_strings.ts, libs/ui/src/ui_strings/election_strings.tsx
Follow-up from https://github.com/votingworks/vxsuite/pull/4599, which caused us to start generating audio for candidate names in all ballot languages instead of reusing the English audio as before.
For now, forcing English strings and audio for candidate names and ballot style ID in the UI code to avoid this. Might revisit later to see if it's worth updating the election package to map these strings to the same audio IDs in all languages for completeness, but this approach should prevent any accidental references to non-English audio for the strings in the meantime. 
- Updated existing tests, verified manually via VxMark
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads …
=> [i18n/audio] Explcitly render non-translatable strings in English

apps/admin/backend/schema.sql, apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/store.test.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/util/workspace.test.ts, apps/admin/backend/src/util/workspace.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/screens/hardware_diagnostics_screen.test.tsx, apps/admin/frontend/src/screens/hardware_diagnostics_screen.tsx, apps/admin/frontend/test/helpers/mock_api_client.ts, libs/backend/src/disk_space_summary.test.ts, libs/backend/src/disk_space_summary.ts, libs/backend/src/index.ts, libs/db/src/client.test.ts, libs/db/src/client.ts
Shows available disk space on the VxAdmin Diagnostics page.
We only want to show users diagnostic information that is meaningful to them and would make sense to include in a "readiness report." So most standard computer diagnostics do not make the cut - you don't need to see the RAM performance because there's nothing the user (or us) can do about. Used disk space is technically actionable, although users normally will not want to delete election data to free up space. I think it will be a somewhat useful indicator to see how much disk space we actually use in production, and to catch serious memory leaks. If VxAdmin goes to a multi-election format, disk space _could_ be a regular concern.
I made a few choices in how to define "disk space" here:
- I'm not simply taking the operating …
=> VxAdmin Diagnostics: Show Disk Space

apps/admin/backend/src/app.ts, apps/admin/backend/src/cast_vote_records.ts, libs/fs/src/list_directory.test.ts, libs/fs/src/list_directory.ts, libs/usb-drive/src/list_directory_on_usb_drive.test.ts, libs/usb-drive/src/list_directory_on_usb_drive.ts
If we don't need to list all of the contents of a directory we shouldn't be forced to.
n/a
Updated automated tests.
=> perf(fs): use `opendir` instead of `readdir`

apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/app_contest_write_in.test.tsx, apps/mark-scan/frontend/src/lib/assistive_technology.test.tsx, apps/mark-scan/frontend/src/pages/contest_screen.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx, apps/mark/frontend/src/app_contest_write_in.test.tsx, apps/mark/frontend/src/lib/gamepad.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/contest.test.tsx, libs/mark-flow-ui/src/components/ms_either_neither_contest.test.tsx, libs/mark-flow-ui/src/components/ms_either_neither_contest.tsx, libs/mark-flow-ui/src/components/yes_no_contest.tsx, libs/mark-flow-ui/src/config/types.ts, libs/mark-flow-ui/src/pages/contest_page.tsx, libs/test-utils/src/index.ts, libs/test-utils/src/matchers.ts, libs/ui/src/button.test.tsx, libs/ui/src/button.tsx, libs/ui/src/contest_choice_button.test.tsx, libs/ui/src/contest_choice_button.tsx, libs/ui/src/number_pad.test.tsx, libs/ui/src/segmented_button.test.tsx, libs/ui/src/virtual_keyboard.test.tsx, libs/ui/src/voter_settings/tab_bar.test.tsx
Fixes https://github.com/votingworks/vxsuite/issues/4576
On BMD contest screens, we were previously automatically moving focus to the "next" button whenever the user makes the final available selection in the current contest -- this makes it easier for sip-and-puff voters to move to the next contest without having to scroll through the remaining contest options, but also prevented the screen reader from providing selection feedback for audio-only voters using the accessible button controller.
This limits that behaviour to only when a PAT device is connected to try to provide both PAT voters and audio-only-button-controller voters with an optimal experience.
https://github.com/votingworks/vxsuite/assets/264902/0bdbd308-b88b-4ee6-8bcd-016874353727 …
=> [BMD] Restrict "next" button autofocus to PAT voting sessions only

apps/admin/backend/src/server.test.ts, apps/admin/backend/src/server.ts, apps/central-scan/backend/src/fujitsu_scanner.test.ts, apps/central-scan/backend/src/fujitsu_scanner.ts, apps/central-scan/backend/src/importer.ts, apps/central-scan/backend/src/loop_scanner.test.ts, apps/central-scan/backend/src/loop_scanner.ts, apps/central-scan/backend/src/server.test.ts, apps/central-scan/backend/src/server.ts, apps/central-scan/backend/src/types.ts, apps/central-scan/backend/test/util/mocks.ts, apps/central-scan/frontend/src/app.test.tsx, apps/central-scan/frontend/src/app.tsx, apps/central-scan/frontend/src/app_root.tsx, apps/central-scan/frontend/src/screens/hardware_diagnostics_screen.test.tsx, apps/central-scan/frontend/src/screens/hardware_diagnostics_screen.tsx, apps/central-scan/frontend/src/screens/scan_ballots_screen.test.tsx, apps/central-scan/frontend/src/screens/scan_ballots_screen.tsx, apps/central-scan/frontend/test/api.tsx, apps/central-scan/frontend/test/fixtures.ts, apps/scan/backend/src/server.test.ts, libs/backend/src/detect_devices.test.ts, libs/backend/src/index.ts, libs/backend/src/is_device_attached.test.ts, libs/backend/src/is_device_attached.ts, libs/backend/src/test_detect_devices.ts, libs/ui/src/diagnostics/central_scan_readiness_report.test.tsx, libs/ui/src/diagnostics/central_scan_readiness_report.tsx, libs/ui/src/diagnostics/central_scanner_section.test.tsx, libs/ui/src/diagnostics/central_scanner_section.tsx
Precursor to VxCentralScan scanner diagnostic.
=> VxCentralScan: determine whether the scanner's attached on the backend and add to Diagnostic screen

libs/mark-flow-ui/src/components/review.test.tsx, libs/mark-flow-ui/src/components/review.tsx
https://github.com/votingworks/vxsuite/issues/4509
This fixes the issue where selecting a button by keyboard `Enter` (or device that depends on keyboard events ie. PAT or accessibility controller) does not activate the contest review button.
I want to be sure we're avoiding a band-aid fix. Do we actually expect `onClick` to be called when an `Enter` keypress event is received and a deeper issue is causing the no-op behavior? But from [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role) the current no-op behavior is expected for a `div` with `role="button"`:
> The button role is for clickable elements that trigger a response when activated by the user. Adding role="button" tells the screen reader the element is a button, but provides no button …
=> fix keyboard nav on review screen

apps/central-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, libs/ui/src/__snapshots__/horizontal_rule.test.tsx.snap, libs/ui/src/horizontal_rule.test.tsx, libs/ui/src/horizontal_rule.tsx
a lot of the test output for VxMark and VxMarkScan was made harder to read because of `<p>` within `<p>` warning. was also throwing console warnings. I fix that here, and give one of the elements a little more breathing room. I wasn't able to see this screen in dev on VxMarkScan (and didn't go through the code-editing effort to do so) because the screens are almost identical on both machines so the change should look good there too.
VxMark Before:
VxMark After:
=> fix nesting warning

apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/app.tsx, apps/admin/frontend/src/components/printer_alert.test.tsx, apps/admin/frontend/src/components/printer_alert.tsx, apps/admin/frontend/src/components/smartcard_modal/smartcard_modal.test.tsx, apps/admin/frontend/test/helpers/mock_api_client.ts, libs/ui/src/diagnostics/index.ts, libs/ui/src/diagnostics/printer_section.tsx
Alert the user when something happens with the printer.
Because we can't distinguish between paper empty and tray open, it will alert anytime the tray is open. But will automatically close whenever the tray is closed (with paper).
https://github.com/votingworks/vxsuite/assets/37960853/9fa4de9f-a1b5-403d-8dbe-710a7d322a38
=> VxAdmin Printer Status Alerts

apps/mark-scan/accessible-controller/src/controllerd.rs
https://github.com/votingworks/vxsuite/issues/4618
Sends a `Shift` key event along with `r` and `p` keypresses to correctly trigger keypress handlers in the apps. These keypress events map to `Pause` and `Replay` functionality.
https://github.com/votingworks/vxsuite/assets/1060688/e7a3bffd-343f-4d60-8bb4-adf653c96b05
- updated test for `handle_command` in controller daemon
=> Send Shift keypress event when sending alphabet key codes

libs/auth/README.md, libs/auth/scripts/generate-dev-keys-and-certs, libs/auth/scripts/generate_dev_keys_and_certs.ts, libs/auth/scripts/mock-card, libs/auth/scripts/mock_card.ts, libs/auth/scripts/program-production-system-administrator-java-card-without-vx-admin, libs/auth/scripts/program_production_system_administrator_java_card_without_vx_admin.ts, libs/auth/scripts/program_system_administrator_java_card.ts, libs/auth/scripts/utils.ts, libs/auth/src/certs.ts
Issue link: https://github.com/votingworks/vxsuite/issues/3762
This PR adds a script for programming a prod sys admin Java Card without a VxAdmin. This is useful for preparing backup
cards after we've shipped a VxAdmin.
This is possible because the VxAdmin cert on a card does not have to exactly match the cert on the VxAdmin; it just needs to have the same jurisdiction (and be signed by VotingWorks, of course).
=> Add script for programming a prod sys admin Java Card without a VxAdmin

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/ballot_styles.test.ts, apps/design/backend/src/ballot_styles.ts, apps/design/backend/src/index.ts, apps/design/backend/src/language_and_audio/app_strings.ts, apps/design/backend/src/language_and_audio/audio.ts, apps/design/backend/src/language_and_audio/election_strings.ts, apps/design/backend/src/store.ts, apps/design/backend/src/types.test.ts, apps/design/backend/src/types.ts, apps/design/backend/src/worker/generate_election_package.ts, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/test/fixtures.ts
Adding language codes to ballot styles generated in VxDesign to be matched up with BMD language selections (and eventually HMPB content as well).
Multi-language ballot style generation is currently hidden behind the `REACT_APP_VX_ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS` flag, since it needs to hand-in-hand with multi-language ballot content generation.
- Synthesised audio for the ballot style IDs sounds a little awkward and isn't useful for audio-only users in its current form. We may need to add a custom election string to use as alt audio text for this.
https://github.com/votingworks/vxsuite/assets/264902/5f8aca41-fa67-448e-9c0f-fdf5980472a5
- Updated ballot generation  test cases and related tests.
- Manually verified list of ballot styles in VxDesign screens and ballot exports. …
=> [i18n/audio] Generate a unique ballot style definitions/IDs for each language

libs/image-utils/src/image_data.test.ts, libs/image-utils/src/image_data.ts, libs/image-utils/src/jest_pdf_snapshot.ts
Adds `toImageBuffer` to convert `ImageData` to a PNG or JPEG image `Buffer`. This enables easy usage with `toMatchImageSnapshot`, which expects a `Buffer`.
=> image-utils: Add toImageBuffer

.circleci/config.yml, libs/monorepo-utils/src/circleci.ts
The main change is to update Rust from 1.72.0 to 1.76.0.
n/a
Automated
=> ci: update docker images

apps/design/backend/src/language_and_audio/utils.test.ts, apps/design/backend/src/language_and_audio/utils.ts, libs/ui/src/bmd_paper_ballot.dual_language.test.tsx, libs/ui/src/bmd_paper_ballot.stories.tsx, libs/ui/src/ui_strings/election_strings.tsx
Addressing a couple of content issues:
- Fixing the election string key for county name to use a single-level key
- Allowing translation/speech synthesis to run for punctuation strings (specifically, period `.`) to support audio for the BMD virtual keyboard.
|--|--|
| <img width="514" alt="Screenshot 2024-03-12 at 09 49 24" src="https://github.com/votingworks/vxsuite/assets/264902/5f16b391-ef95-4d10-8054-18ff3cd0b22c"> | <img width="514" alt="Screenshot 2024-03-12 at 09 48 16" src="https://github.com/votingworks/vxsuite/assets/264902/e14acc2a-734a-492a-9eed-e54081a09f5f"> |
- Updated tests, manual verification
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as …
=> [i18n/Audio] Content bug fixes

apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, libs/ballot-interpreter/src/interpret.ts
Hotfixes a bug in VxMarkScan where elections with `gridLayouts` (ie. all elections exported from VxDesign) would always try to interpret ballots as HMPBs.
Note that this does not fix the underlying bug, so users of VxMark + VxScan will still have this problem. A long term solution is tracked in https://github.com/votingworks/vxsuite/issues/4659.
N/A
Added test for interpreting a BMD ballot using a `gridLayouts` election
N/A
=> always interpret bmd ballots in mark-scan

apps/mark-scan/backend/src/custom-paper-handler/cli/state_machine_cli.ts, apps/mark-scan/backend/src/custom-paper-handler/constants.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/custom-paper-handler/types.ts, apps/mark-scan/backend/src/server.ts, apps/mark-scan/backend/test/app_helpers.ts, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_states.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_auth_ended_unexpectedly_page.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/3974
During either paper loading state, resets the voter session if poll worker auth is ended before paper is done loading.
* If card is pulled before paper load is attempted, the app just returns to the login page
* If card is pulled during physical paper load, the app displays a message for 5 seconds then resets
Previously, the code allowed a poll worker to pull their card either
1. before paper loading was attempted, resulting in a cardless voter session that would eventually fail at print time
2. in the middle of paper loading. In the event of a jam during paper load, the poll worker would be unaware, so we want the poll worker to remain until loading is successful.
https://github.com/votingworks/vxsuite/assets/1060688/eb0aee15-e98d-4339-95 …
=> Reset session if pollworker card is pulled during paper load prompt/intake

libs/hmpb/layout/src/layout.ts
If someone wants to leave e.g. state blank we shouldn't put a trailing comma after the county name. I realize this is going to be replaced soonish. Consider it a request to preserve this fix in the new version.
Generated some sample ballots.
=> fix(design): omit empty place parts

libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/timing_mark_metadata.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks.rs, libs/ballot-interpreter/src/hmpb-ts/types.ts, libs/ballot-interpreter/src/interpret.ts, libs/converter-nh-accuvote/src/convert/convert_election_definition.ts, libs/converter-nh-accuvote/src/convert/types.ts
I mostly wanted to make this code more readable, tested, and idiomatic. In the process I found it easiest to improve the tests by making them round-trip encode/decode, so I added encoding functionality to the metadata structs. A summary of changes:
- Make the structs contain only the fields relevant to the running program; omit fields that are only related to encoding.
- Rename the structs after the information they contain rather than their position on a ballot card.
- Add property tests for encoding/decoding.
- Use `impl` methods for encode/decode rather than free functions.
- Make some helper functions for bitwise encode/decode.
n/a
Automated.
=> feat(ballot-interpreter): add encoding for timing mark metadata

apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/custom-paper-handler/types.ts, apps/mark-scan/frontend/.codemod.bookmark, apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_states.test.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx, libs/mark-flow-ui/src/pages/cast_ballot_page.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/4542
Gives instructions to the voter when the ballot is removed during the presentation stage. On mark-scan the ideal path is for the voter to use the interface to confirm their ballot is correct, which causes the app to pull the paper back in and cast it to the rear box. But it's likely that some voters will remove the ballot during the presentation stage, especially if they realize other voters are casting their HMPBs at a precinct scanner.
In the case of early removal we should give instructions to cast at a precinct scanner rather than just ending the session.
Changes start at 0:20
https://github.com/votingworks/vxsuite/assets/1060688/eaff182f-f523-4685-aed5-7eb6a0102dbc
- added tests
=> mark-scan: Instructions for early ballot removal

libs/auth/src/java_card.ts
Rather than hardcoding a fixed number of bytes to trim we now properly parse the nested response TLV structures. While the old way didn't bite us in practice, if the signature returned was ever larger than 0x80 bytes the TLV would use two bytes to encode the length and the signature would be corrupted.
n/a
Automated tests, plus manual testing with a sysadmin card.
=> fix(auth): properly parse the challenge response

libs/auth/src/cryptography.test.ts, libs/auth/src/cryptography.ts
`FileResult::removeCallback` doesn't return a `Promise`, so there's no sense in `await`ing the result. See the value of `removeCallback` here: https://github.com/raszi/node-tmp/blob/7ae22ed2d56c10d425a66e99fe8bc10c925442e6/lib/tmp.js#L181.
n/a
Updated automated test that incorrectly mocked using a `Promise`.
=> chore(auth): remove unnecessary `async` in tmpfile cleanup

libs/auth/src/apdu.test.ts, libs/auth/src/apdu.ts, libs/auth/src/cac/common_access_card.test.ts, libs/auth/src/cac/common_access_card.ts, libs/auth/src/java_card.ts
Rather than trimming metadata by ignoring fixed-length prefixes and suffixes, we now properly parse the TLV structures. Additionally, this changes the `parseTlv` function to expect the data to be entirely consumed by the TLV structure. If it isn't, use `parseTlvPartial` instead, which returns a remainder.
n/a
Updated tests for where we had the expected responses wrong (just getting certs for CAC's).
=> fix(auth): parse all TLV responses properly
