- apps/bsd/README.md
- apps/module-scan/README.md
Some readme updates to make a few things a bit clearer and link to the new vxsuite versions of the repos.
> Readme Updates

- apps/bas/src/screens/InsertCardScreen.tsx
Closes https://github.com/votingworks/bas/issues/79
> fix(bas): clarify instructions for inserting voter cards

- apps/bas/src/App.tsx
- apps/bas/src/screens/WritingCardScreen.tsx
Closes https://github.com/votingworks/vxsuite/issues/62
> refactor(bas): say "encoding" instead of "programming"

- apps/bmd/src/AppContestMsEitherNeither.test.tsx
- apps/bmd/src/components/MsEitherNeitherContest.tsx
Fixes https://github.com/votingworks/vxmail/issues/316
> fix(bmd): add "selected" & "deselected" audio cues for either/neither

- apps/bas/src/App.tsx
- apps/bas/src/config/types.ts
- apps/bas/src/screens/AdminScreen.tsx
- apps/bas/src/screens/LoadElectionScreen.tsx
- apps/bmd/docs/smartcard.md
- apps/bmd/src/AppRoot.tsx
- apps/bmd/src/config/types.ts
- apps/bmd/src/pages/AdminScreen.test.tsx
- apps/bmd/src/pages/AdminScreen.tsx
- apps/bmd/test/helpers/smartcards.ts
- apps/bsd/src/AppRoot.tsx
- apps/bsd/src/components/ElectionConfiguration.tsx
- apps/bsd/src/config/types.ts
- apps/module-smartcards/README.md
- apps/module-smartcards/fixtures/admin/short.json
- apps/module-smartcards/writeAdminCard.py
- libs/ballot-encoder/src/election.ts
Closes https://github.com/votingworks/complete-system-ms/issues/12
> refactor: rename "clerk" to "admin"

- apps/bmd/src/AppPrintOnly.test.tsx
- apps/bmd/src/AppRoot.tsx
- apps/bmd/src/pages/PollWorkerScreen.test.tsx
- apps/bmd/src/pages/PollWorkerScreen.tsx
- apps/bmd/src/utils/date.test.ts
- apps/bmd/src/utils/date.ts
> feat(bmd): prompt poll workers to switch to live mode on election day

- libs/hmpb-interpreter/src/cli/commands/layout.ts
I typically use this command on original scanned ballot images, many of which are upside-down. This makes it so I can stop rotating them "by hand" before running the layout command on them.
> feat(hmpb-interpreter): auto-rotate images for `layout` command

- apps/bmd/src/AppContestMsEitherNeither.test.tsx
- apps/bmd/src/data/electionPrimarySample.json
- apps/bmd/src/data/electionSample.json
- apps/bmd/src/data/electionSampleNoSeal.json
- apps/bmd/src/data/electionSampleWithSeal.json
- apps/bmd/src/pages/PrintPage.test.tsx
- apps/bmd/src/pages/StartPage.test.tsx
- apps/bmd/test/testUtils.tsx
- libs/ballot-encoder/src/election.ts
These are things that needed to be fixed when moving toward cross-package references.
> Misc. TypeScript improvements

- libs/ballot-encoder/test/fuzz.test.ts
Remove unused eslint disable directive.
> refactor(ballot-encoder): clean up a couple minor things

- apps/bas/prodserver/index.js
- apps/bmd/prodserver/index.js
- apps/bsd/prodserver/index.js
- apps/election-manager/prodserver/index.js
Also changes the output message to include a URL to make it clickable in some terminals.
> refactor(all): re-sync prodserver config

- apps/module-smartcards/writePollWorkerCard.py
> script to write a poll worker card 

- apps/bsd/src/App.test.tsx
- apps/bsd/src/AppRoot.tsx
Adds a success screen with an eject USB button after importing a ballot package in BSD. It's a little strange because this workflow isn't in a modal since it's required to configure the machine. I considered having a timeout that would automatically close this message after some time but thought that might be jarring and opted to add a close button instead that will close the screen and go to the configured main app. When the user ejects the USB it will also close this screen. 
Screenshot: 
Video:
https://user-images.githubusercontent.com/14897017/105280110-e19a3d00-5b5d-11eb-9323-ed51f2f2d022.mov
https://zube.io/votingworks/vxsuite/c/2908
> Add success screen with eject button after importing ballot package

- apps/module-scan/src/cli/retry-scan/index.ts
- apps/module-scan/src/cli/retry-scan/main.test.ts
- apps/module-scan/src/cli/retry-scan/main.ts
- apps/module-scan/src/importer.test.ts
- apps/module-scan/src/importer.ts
- apps/module-scan/src/interpreter.test.ts
- apps/module-scan/src/interpreter.ts
- apps/module-scan/src/server.ts
- apps/module-scan/src/types.ts
- apps/module-scan/src/util/metadata.test.ts
- apps/module-scan/src/util/metadata.ts
- apps/module-scan/src/workers/combined.ts
- apps/module-scan/src/workers/interpret.ts
- apps/module-scan/src/workers/pool.test.ts
- apps/module-scan/src/workers/pool.ts
- apps/module-scan/src/workers/qrcode.ts
Closes #157 
These QR codes are unreadable for various reasons, but the one on the other side is readable.
> Infer a single missing HMPB QR code

- apps/election-manager/public/ballot/ballot-layout-letter.css
I refactored and then forgot to update this change.
> fix(election-manager): Fix css page size

- apps/election-manager/public/ballot/ballot-layout-letter.css
- apps/election-manager/src/__snapshots__/App.test.tsx.snap
- apps/election-manager/src/screens/BallotScreen.tsx
Draft PR until I add test coverage…
I suggest viewing changes without whitespace: https://github.com/votingworks/vxsuite/pull/239/files?w=1
https://user-images.githubusercontent.com/28444/106952292-c561d880-66e5-11eb-89e8-095701bc6158.mov
https://user-images.githubusercontent.com/28444/106817824-43fa3f80-662c-11eb-9fe1-23dd370ec358.mov
> feat(election-manager): Preview printed ballot

- apps/election-manager/src/__snapshots__/App.test.tsx.snap
- apps/election-manager/src/screens/BallotScreen.tsx
> feat(election-manager): Ballot preview "Front" and "Back" labels

- apps/election-manager/src/App.test.tsx
- apps/election-manager/src/components/PrintButton.tsx
- apps/election-manager/src/screens/BallotScreen.tsx
https://user-images.githubusercontent.com/28444/107323121-95566480-6a5a-11eb-8250-37678391c6f0.mov
> feat(election-manager): Modal confirms printer paper is correct

- apps/election-manager/src/components/HandMarkedPaperBallot.tsx
> refactor(election-manager): Remove unnecessary extra variable

- apps/election-manager/public/ballot/ballot-layout-paper-size-legal.css
- apps/election-manager/public/ballot/ballot-layout-paper-size-letter.css
- apps/election-manager/public/ballot/ballot.css
- apps/election-manager/src/App.css
- apps/election-manager/src/components/HandMarkedPaperBallot.tsx
- apps/election-manager/src/data/defaultElection.json
- apps/election-manager/src/screens/BallotScreen.tsx
- apps/election-manager/src/utils/getBallotLayoutPageSize.ts
- libs/fixtures/src/data/electionMultiPartyPrimarySample.json
- libs/fixtures/src/data/electionPrimarySample.json
- libs/fixtures/src/data/electionSample.json
- libs/fixtures/src/data/electionSampleLongContent.json
- libs/fixtures/src/data/electionWithMsEitherNeither.json
- libs/types/src/election.ts
- libs/types/src/schema.test.ts
- libs/types/src/schema.ts
I was looking for a way to implement this using classes which doesn't seem possible for setting the `@page` settings.
PagedJS does have a [feature for named pages](https://www.pagedmedia.org/about-paged-media/pagedjs-cheatsheet/) however this does not seem to be supported for the first page.
https://user-images.githubusercontent.com/28444/107608510-0b8ccf80-6bf1-11eb-9853-1692a7da20e3.mov
> Ballot paper size config

- apps/election-manager/src/screens/TallyScreen.tsx
> fix(em): align total column with numbers being summed

- apps/election-manager/src/App.test.tsx
- apps/election-manager/src/__snapshots__/App.test.tsx.snap
- apps/election-manager/src/screens/TallyReportScreen.tsx
Adds some integration tests for importing sems files
> refactor(election-manager): add integration tests for sems files

- apps/election-manager/src/App.test.tsx
- apps/election-manager/src/config/types.ts
- apps/election-manager/src/screens/BallotScreen.tsx
- apps/election-manager/src/screens/PrintedBallotsReportScreen.tsx
Show the number of precinct and absentee ballots printed in the printed ballot report. 
The snapshot changes are all just autogenerated classname changes from my changes to the Table component.
> feat(election-manager) report printed ballots by ballot type

- apps/election-manager/src/lib/votecounting.test.ts
Added ballotCountsByVotingMethod to the Tally object in but didn't test it as exhaustively as I should have.
> test(election-manager): tests for ballotCountsByVotingMethod

- apps/bsd/src/App.test.tsx
- apps/bsd/src/AppRoot.tsx
- apps/bsd/src/components/StatusFooter.tsx
- apps/bsd/test/util/hasTextAcrossElements.ts
Shows the machine ID in the footer of bsd
Before:
After:
> Show Machine ID in BSD footer

- apps/module-smartcards/README.md
- apps/module-smartcards/mockCardReader.py
> test(smartcards): build mocks from definitions

- apps/module-scan/src/interpreter.ts
Doesn't use it yet, just adding a placeholder to make it easier to have @carolinemodic build on it.
Refs #298
> feat(scan): represent election hash mismatch result

- apps/bsd/src/screens/BallotEjectScreen.tsx
- apps/bsd/src/screens/__snapshots__/BallotEjectScreen.test.tsx.snap
> More responsive layout for ballot images to remain proportional

- libs/types/src/schema.ts
This brings schema.ts back in line with election.ts.
> feat(types): add election definition schema

- apps/module-smartcards/writeAdminCard.py
don't parse and reserialize the JSON, as that will change the hash.
> fix smartcard admin card writing

- libs/fixtures/src/index.test.ts
This was the result of a merge conflict with two of my PRs.
> test(fixtures): fix tests

- apps/bmd/src/pages/PrintPage.tsx
- apps/bmd/src/utils/isEmptyObject.ts
> fix(bmd): support blank ballots

- apps/module-scan/src/interpreter.test.ts
- apps/module-scan/src/interpreter.ts
- apps/module-scan/src/store.ts
- apps/module-scan/src/workers/interpret.ts
Addresses post-hoc comments from https://github.com/votingworks/vxsuite/pull/333
> refactor(bsd): address pr comments from #133

- apps/bsd/src/screens/AdvancedOptionsScreen.test.tsx
- apps/bsd/src/screens/AdvancedOptionsScreen.tsx
https://user-images.githubusercontent.com/1938/111517701-94c48400-8712-11eb-9a94-fa61ad6c1068.mov
Closes #355
> fix(scan): show factory reset progress

- apps/election-manager/src/App.test.tsx
- apps/election-manager/src/components/ContestTally.tsx
- apps/election-manager/src/components/TallyReportMetadata.test.tsx
- apps/election-manager/src/components/TallyReportMetadata.tsx
- apps/election-manager/src/screens/TallyReportScreen.tsx
Resolves #246 
https://user-images.githubusercontent.com/28444/112076843-6abaf980-8b38-11eb-956b-b1a5bbcc64c3.mov
> Preview tally reports

- apps/bmd/src/AppRoot.tsx
- apps/bmd/src/utils/Hardware.test.ts
- apps/bmd/src/utils/Hardware.ts
- libs/@types/kiosk-browser/kiosk-browser.d.ts
- libs/test-utils/src/fakeKiosk.ts
Fixes #317, depends on votingworks/kiosk-browser#74.
> fix(bmd): correct "No Printer Connected" false positive

- apps/election-manager/src/__snapshots__/App.test.tsx.snap
- apps/election-manager/src/screens/TallyReportScreen.tsx
- apps/election-manager/src/screens/TestDeckScreen.tsx
> Condensed Test Deck Tally Reports

- apps/election-manager/src/__snapshots__/App.test.tsx.snap
- apps/election-manager/src/components/ElectionManager.tsx
- apps/election-manager/src/components/NavigationScreen.tsx
- apps/election-manager/src/routerPaths.ts
- apps/election-manager/src/screens/SmartcardsScreen.tsx
- apps/election-manager/src/setupProxy.js
Resolves: https://github.com/votingworks/vxmail/issues/150
> feat(em): Admin and Poll Worker Smartcard encoding.

- apps/precinct-scanner/src/AppRoot.tsx
- apps/precinct-scanner/src/screens/AdminScreen.tsx
- apps/precinct-scanner/src/screens/InsertBallotScreen.tsx
- apps/precinct-scanner/src/screens/PollWorkerScreen.tsx
- apps/precinct-scanner/src/screens/PollsClosedScreen.tsx
- apps/precinct-scanner/src/screens/ScanErrorScreen.tsx
- apps/precinct-scanner/src/screens/ScanSuccessScreen.tsx
- apps/precinct-scanner/src/screens/ScanWarningScreen.tsx
@carolinemodic - Feel free to merge if LGTY 😄
> feat(ps): Stub out all screens.

- apps/election-manager/src/screens/SmartcardsScreen.tsx
not merging until we fix `main` for election-manager.
> fix(em): write raw election data to card, for hash value consistency

- apps/precinct-scanner/src/screens/ScanWarningScreen.tsx
I'd post screenshots, but I gotta 💉
> feat(ps): Warning Scree: Confirm Tabulate Modal

- .gitignore
- apps/module-scan/.gitignore
- apps/module-scan/package.json
- apps/module-scan/tsconfig.json
> build(module-scan): create build files in `build`

- apps/module-scan/src/LoopScanner.ts
- apps/module-scan/src/importer.test.ts
- apps/module-scan/src/scanners/fujitsu.ts
- apps/module-scan/src/scanners/index.ts
- apps/module-scan/src/scanners/plustek.ts
- apps/module-scan/test/util/mocks.ts
- libs/plustek-sdk/src/mocks.test.ts
- libs/plustek-sdk/src/mocks.ts
- libs/plustek-sdk/src/scanner.test.ts
- libs/plustek-sdk/src/scanner.ts
Waiting on #490 to hook up to the admin screen.
Refs #511
> feat(scan): add plustek calibration support

- apps/precinct-scanner/src/AppRoot.tsx
- apps/precinct-scanner/src/screens/PollWorkerScreen.tsx
@carolinemodic - Please merge if LGTY.
> Open close polls confirm modal

- apps/bas/.vscode/extensions.json
- apps/bsd/.vscode/extensions.json
- apps/module-scan/src/importer.ts
- apps/module-scan/src/interpreter.ts
- vxsuite.code-workspace
Also adds a code spell checker with a custom wordlist.
> chore(vscode): consolidate recommended extensions

- apps/precinct-scanner/src/AppRoot.tsx
- apps/precinct-scanner/src/components/ElectionInfoBar.test.tsx
- apps/precinct-scanner/src/components/ElectionInfoBar.tsx
- apps/precinct-scanner/src/components/Layout.tsx
- apps/precinct-scanner/src/components/__snapshots__/ElectionInfoBar.test.tsx.snap
- apps/precinct-scanner/src/contexts/AppContext.ts
- apps/precinct-scanner/src/screens/AdminScreen.tsx
- apps/precinct-scanner/src/screens/InsertBallotScreen.tsx
- apps/precinct-scanner/src/screens/PollWorkerScreen.tsx
- apps/precinct-scanner/src/screens/ScanSuccessScreen.tsx
Hooks up the machine config to the ElectionInfoBar footer by refactoring it and the election definition and current precinct into AppContext
> feat(ps) hook up machine config through appcontext

- apps/module-scan/src/scanners/plustek.test.ts
- apps/module-scan/src/scanners/plustek.ts
- apps/module-scan/src/server.ts
- libs/plustek-sdk/src/mocks.test.ts
- libs/plustek-sdk/src/mocks.ts
- libs/plustek-sdk/src/scanner.test.ts
- libs/plustek-sdk/src/scanner.ts
Introduces a scanner client provider wrapper builder that will transparently reconnect to the client if it's returning values that indicate it has lost the connection. I determined these values by connecting to the scanner, turning the scanner off, then trying commands. Nearly all of the commands error with `PLKSS_ERRCODE_SANE_STATUS_IO_ERROR`, except for `scan` which errors with `PLKSS_ERRCODE_PAPER_STATUS_ERROR_FEEDING`.
Requires https://github.com/votingworks/plustekctl/pull/3
Closes #512
> fix(scan): reconnect to plustek scanner transparently

- apps/module-scan/src/scanners/plustek.test.ts
- apps/module-scan/src/scanners/plustek.ts
If multiple requests were made to a `withReconnect` scanner client before the client connected, it would spawn more than one `plustekctl` process. This ensures there is only ever one and that any clients being discarded are closed first.
> fix(scan): ensure only one `plustekctl` runs

- apps/module-scan/src/server.test.ts
- apps/module-scan/src/server.ts
> fix(scan): reject any sheets in the scanner on startup

- apps/precinct-scanner/src/App.test.tsx
- set up `window.kiosk` early so the USB code thinks it is available but has no drives
- `fakeKiosk` returns an object with Jest mocks already, so just use them
- fix a typo in a test name
- await calls to `advanceTimersAndPromises` to fix the "overlapping `act` calls" warning
> test(scan): minor fixes

- vxsuite.code-workspace
- ignore build and coverage-related files
- add a few more custom words
> chore(all): configure VS Code workspace

- apps/precinct-scanner/package.json
- apps/precinct-scanner/src/App.test.tsx
- apps/precinct-scanner/src/AppUnhappyPaths.test.tsx
- apps/precinct-scanner/src/api/config.test.ts
- apps/precinct-scanner/src/api/config.ts
- apps/precinct-scanner/src/api/scan.test.ts
- apps/precinct-scanner/src/screens/AdminScreen.test.tsx
- apps/precinct-scanner/src/screens/AdminScreen.tsx
- apps/precinct-scanner/src/screens/PollsClosedScreen.tsx
- apps/precinct-scanner/src/screens/ScanErrorScreen.test.tsx
- apps/precinct-scanner/src/screens/ScanProcessingScreen.tsx
- apps/precinct-scanner/src/screens/ScanWarningScreen.tsx
- apps/precinct-scanner/src/screens/UnconfiguredElectionScreen.tsx
- apps/precinct-scanner/src/utils/ballot-package.ts
- apps/precinct-scanner/src/utils/usbstick.ts
- apps/precinct-scanner/test/fixtures/index.ts
Adds more tests to precinct scanner. Not quite at 100% coverage but getting there.
> test(ps) add more tests to precinct scanner

- apps/precinct-scanner/src/App.test.tsx
- apps/precinct-scanner/src/AppRoot.tsx
Resets to polls being closed when: 
- The scanner election is unconfigured (and then reconfigured)
- Test mode / Live mode is toggled
- The precinct the scanner is set for is changed
https://zube.io/votingworks/vxsuite/c/3348
> Reset polls to closed when changing config

- apps/module-scan/src/buildCastVoteRecord.test.ts
- apps/module-scan/src/buildCastVoteRecord.ts
- apps/module-scan/src/interpreter.test.ts
- apps/module-scan/src/interpreter.ts
- apps/module-scan/src/server.test.ts
- apps/module-scan/src/validation.ts
> fix(scan): validate on import

- libs/hmpb-interpreter/src/Interpreter.ts
- libs/hmpb-interpreter/src/hmpb/findContests.ts
[🎵 CorresponD.A.N.C.E. by Justice 🎵](https://music.apple.com/us/album/d-a-n-c-e/259751732?i=259751997)
> fix(scan): correct typo

- libs/hmpb-interpreter/jest.config.js
- libs/hmpb-interpreter/package.json
- libs/hmpb-interpreter/src/getVotesFromMarks.test.ts
- libs/hmpb-interpreter/src/getVotesFromMarks.ts
- libs/hmpb-interpreter/src/utils/KeyedMap.test.ts
- libs/hmpb-interpreter/src/utils/templateMap.test.ts
- libs/hmpb-interpreter/src/utils/templateMap.ts
- libs/hmpb-interpreter/tsconfig.json
- pnpm-lock.yaml
Not to 100% yet, but getting closer.
Refs #598
> test(scan): improve coverage of `hmpb-interpreter`

- apps/module-scan/README.md
> Add example commands for running Ballot Scanner with fixtures data

- README.md
> docs: add a "Development Best Practices" section

- apps/module-scan/src/interpreter.ts
This is just useful info to have.
> fix(scan): log election hash info

- apps/module-scan/src/cli/mock-scanner/index.ts
Sometimes the request may not succeed. This handles the responses and shows them more cleanly than a stack trace.
> fix(scan): handle mock scanner errors better

- libs/plustek-sdk/examples/web/index.ts
Should have been done in https://github.com/votingworks/vxsuite/pull/587.
> fix(plustek-sdk): update examples with new `Result` API

- README.md
> docs: use `pnpm@5`

- apps/bmd/src/AppCardUnhappyPaths.test.tsx
- apps/bmd/src/AppCardlessVoting.test.tsx
- apps/bmd/src/AppContestCandidateNoParty.test.tsx
- apps/bmd/src/AppContestMsEitherNeither.test.tsx
- apps/bmd/src/AppContestMultiSeat.test.tsx
- apps/bmd/src/AppContestSingleSeat.test.tsx
- apps/bmd/src/AppContestWriteIn.test.tsx
- apps/bmd/src/AppContestYesNo.test.tsx
- apps/bmd/src/AppData.test.tsx
- apps/bmd/src/AppEndToEnd.test.tsx
- apps/bmd/src/AppMarkOnly.test.tsx
- apps/bmd/src/AppMarkVoterCardInvalid.test.tsx
- apps/bmd/src/AppPrintOnly.test.tsx
- apps/bmd/src/AppQuitOnIdle.test.tsx
- apps/bmd/src/AppSetupErrors.test.tsx
- apps/bmd/src/AppTestMode.test.tsx
- apps/bmd/src/DemoApp.tsx
- apps/bmd/src/components/CandidateContest.test.tsx
- apps/bmd/src/components/LinkButton.test.tsx
- apps/bmd/src/components/Text.test.tsx
- apps/bmd/src/components/YesNoContest.test.tsx
- apps/bmd/src/lib/gamepad.test.tsx
- apps/bmd/src/pages/AdminScreen.test.tsx
- apps/bmd/src/pages/ContestPage.test.tsx
- apps/bmd/src/pages/NotFoundPage.test.tsx
- apps/bmd/src/pages/PollWorkerScreen.test.tsx
- apps/bmd/src/pages/StartPage.test.tsx
- apps/bmd/src/pages/TestBallotDeckScreen.test.tsx
Per https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-screen
> test(bmd): use `screen` API

- apps/bas/tsconfig.json
- apps/bmd/tsconfig.json
- apps/bsd/tsconfig.json
- apps/election-manager/tsconfig.json
- apps/module-scan/tsconfig.json
- apps/precinct-scanner/tsconfig.json
- integration-testing/bsd/cypress/tsconfig.json
- integration-testing/election-manager/cypress/tsconfig.json
- libs/ballot-encoder/tsconfig.json
- libs/fixtures/tsconfig.json
- libs/hmpb-interpreter/tsconfig.json
- libs/lsd/tsconfig.json
- libs/plustek-sdk/tsconfig.json
- libs/test-utils/tsconfig.json
- libs/types/tsconfig.json
- libs/ui/tsconfig.json
- libs/utils/tsconfig.json
- tsconfig.shared.json
> build(all): consolidate `target` and `strict` tsconfig

- apps/bas/src/App.tsx
- apps/bas/src/utils/fetchJSON.ts
- apps/bmd/src/pages/PollWorkerScreen.tsx
- apps/bsd/src/screens/DashboardScreen.tsx
- apps/bsd/src/serviceWorker.ts
- apps/election-manager/src/components/HandMarkedPaperBallot.tsx
- apps/election-manager/src/screens/DefinitionContestsScreen.tsx
- apps/election-manager/src/screens/TallyScreen.tsx
- apps/election-manager/src/serviceWorker.ts
- apps/precinct-scanner/src/serviceWorker.ts
- libs/types/src/election.ts
Replaces a bunch of places where we could easily convert to using optional chaining. This was what I used to search: [`\b(\w+)\s*&&\s*\1[\.\[]`](https://regex101.com/r/arBsY4/1).
> style(all): use optional chaining

- apps/bmd/src/AppRoot.tsx
- apps/bmd/src/components/PrintedBallot.tsx
- apps/bmd/src/pages/PollWorkerScreen.tsx
- apps/bmd/test/helpers/election.ts
- apps/bsd/src/AppRoot.tsx
- apps/bsd/src/components/ElectionConfiguration.tsx
- apps/bsd/src/screens/BallotEjectScreen.tsx
- apps/election-manager/src/components/BallotCountsTable.tsx
- apps/election-manager/src/contexts/AppContext.ts
- apps/election-manager/src/screens/DefinitionContestsScreen.tsx
- apps/election-manager/src/screens/OvervoteCombinationReportScreen.tsx
- apps/election-manager/src/screens/PrintTestDeckScreen.tsx
- apps/election-manager/src/screens/TallyScreen.tsx
- apps/election-manager/src/screens/UnconfiguredScreen.tsx
- apps/election-manager/test/renderInAppContext.tsx
Just some things I noticed while perusing the codebase. Broken into commits by type of fix.
> Misc fixes

- apps/bmd/package.json
- apps/bmd/script/vvsg-cloc
- apps/bmd/src/AppRoot.tsx
- apps/bmd/test/helpers/election.ts
- apps/bmd/test/helpers/smartcards.ts
- apps/election-manager/src/AppRoot.tsx
- apps/election-manager/src/components/HandMarkedPaperBallot.tsx
- pnpm-lock.yaml
Mostly this is handling card data.
Extracted from #724
> fix(bmd): use `zod` instead of `JSON.parse`

- apps/bas/src/App.tsx
From https://github.com/votingworks/vxsuite/pull/724#discussion_r681324306.
> fix(typo): use the correct name for this hook

- apps/precinct-scanner/src/AppRoot.tsx
- apps/precinct-scanner/src/screens/AdminScreen.tsx
- apps/precinct-scanner/src/screens/PollWorkerScreen.tsx
Also renames it for `PollWorkerScreen` to match the other screens.
> fix(ps): format scanned ballot count

- apps/precinct-scanner/src/PreviewApp.tsx
- apps/precinct-scanner/src/PreviewDashboard.tsx
- apps/precinct-scanner/src/screens/InvalidCardScreen.tsx
- apps/precinct-scanner/src/screens/LoadingConfigurationScreen.tsx
- apps/precinct-scanner/src/screens/PollWorkerScreen.tsx
- apps/precinct-scanner/src/screens/PollsClosedScreen.tsx
- apps/precinct-scanner/src/screens/ScanErrorScreen.tsx
- apps/precinct-scanner/src/screens/ScanProcessingScreen.tsx
- apps/precinct-scanner/src/screens/ScanSuccessScreen.tsx
> test(ps): add more previews

- apps/bmd/src/pages/PollWorkerScreen.tsx
Adds more comments about the pollworker audiotrack and how to add new modals to the pollworker screen. Meant to add to https://github.com/votingworks/vxsuite/pull/742 before merging
> add more comments around pollworker audiotrack

- apps/bas/package.json
- apps/bas/src/App.test.tsx
- apps/bas/src/App.tsx
- apps/bas/src/config/types.ts
- apps/bas/src/hooks/useStateWithLocalStorage.ts
- apps/bas/src/index.tsx
- apps/bas/src/screens/AdminScreen.tsx
- apps/bas/src/screens/PrecinctBallotStylesScreen.tsx
- apps/bas/src/screens/PrecinctsScreen.tsx
- pnpm-lock.yaml
> Replace some `JSON.parse` calls

- libs/ui/src/hooks/useUsbDrive.ts
If the component using `useUsbDrive` is unmounted while one fo the async operations is running, a subsequent state update call will fail with an error. [This was happening in the tests.](https://app.circleci.com/pipelines/github/votingworks/vxsuite/1767/workflows/aaed155b-a6e6-47a0-8acf-89379faad935/jobs/21913?invite=true#step-108-34) Canceling the promises using `useCancelablePromise` fixes it.
```
console.error
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
at AppRoot (/home/circleci/project/apps/precinct-scanner/src/AppRoot.tsx:376:3)
at Route (/home/circleci/project/node_modules/.pnpm/react-router@5.2.0_rea …
```
> fix(ui): cancel promises in `useUsbDrive`

- apps/election-manager/src/utils/generateBatchTallyResultsCSV.ts
- libs/utils/src/filenames.ts
Addresses a few post-merging comments from @eventualbuddha in https://github.com/votingworks/vxsuite/pull/760
> cleanup pr comments in #760

- libs/ui/tsconfig.json
- script/src/prod-build/index.ts
- script/src/prod-build/pnpm.ts
There were actually a few issues. Look commit-by-commit to see what this fixes.
Closes #775
> Fix python apps in production builds

- apps/module-scan/test/util/mocks.ts
- libs/eslint-plugin-vx/docs/rules/gts-no-private-fields.md
- libs/eslint-plugin-vx/package.json
- libs/eslint-plugin-vx/src/configs/recommended.ts
- libs/eslint-plugin-vx/src/rules/gts-no-private-fields.ts
- libs/eslint-plugin-vx/src/rules/index.ts
- libs/eslint-plugin-vx/tests/rules/gts-no-private-fields.test.ts
- libs/eslint-plugin-vx/tsconfig.json
- libs/utils/src/deferred.ts
- pnpm-lock.yaml
https://google.github.io/styleguide/tsguide.html#private-fields
Refs #764
> style(lint): enforce & fix GTS "no private fields" rule

- apps/bmd/src/utils/ScreenReader/AriaScreenReader.ts
- apps/bmd/src/utils/ScreenReader/SpeechSynthesisTextToSpeech.ts
- apps/election-manager/src/lib/ConverterClient.ts
- apps/election-manager/src/utils/CastVoteRecordFiles.ts
- apps/module-scan/src/LoopScanner.ts
- apps/module-scan/src/cli/util/spinner.ts
- libs/ballot-encoder/src/bits/BitReader.ts
- libs/ballot-encoder/src/bits/encoding.ts
- libs/eslint-plugin-vx/src/configs/recommended.ts
- libs/eslint-plugin-vx/src/rules/gts-parameter-properties.ts
- libs/eslint-plugin-vx/src/rules/index.ts
- libs/eslint-plugin-vx/tests/rules/gts-parameter-properties.test.ts
- libs/eslint-plugin-vx/tests/rules/no-array-sort-mutation.test.ts
- libs/eslint-plugin-vx/tsconfig.json
https://google.github.io/styleguide/tsguide.html#parameter-properties
Refs #764
> style(lint): use parameter properties

- apps/election-manager/src/utils/CastVoteRecordFiles.ts
Progress toward https://google.github.io/styleguide/tsguide.html#use-readonly.
Refs #788
> style(em): use `readonly` in `CastVoteRecordFiles`

- apps/precinct-scanner/src/PreviewApp.tsx
- apps/precinct-scanner/src/screens/InsertBallotScreen.tsx
- apps/precinct-scanner/src/screens/PollsClosedScreen.tsx
- apps/precinct-scanner/src/screens/SetupPowerPage.tsx
Sorry about this, thanks for catching. I had pushed these changes but I didn't realize it timed out and failed (issue with configuration on a different wifi then I usually use).
> feat(ps) add previews for no power connected statuses

- libs/ui/jest.config.js
- libs/ui/package.json
- libs/ui/src/TallyReportSummary.tsx
- pnpm-lock.yaml
We lost this somewhere along the way.
> test(coverage): fix enforcement of `/ui` coverage

- apps/election-manager/src/__snapshots__/App.test.tsx.snap
- apps/election-manager/src/components/HandMarkedPaperBallot.tsx
- apps/election-manager/src/components/Prose.tsx
- apps/election-manager/src/data/defaultElection.json
- apps/election-manager/src/utils/getBallotLayoutDensity.ts
- libs/types/src/election.ts
> feat(EM): Support ballot density.

- apps/precinct-scanner/package.json
- apps/precinct-scanner/prodserver/setupProxy.js
- apps/precinct-scanner/src/App.test.tsx
- apps/precinct-scanner/src/AppRoot.tsx
- apps/precinct-scanner/src/AppUnhappyPaths.test.tsx
- apps/precinct-scanner/src/PreviewApp.tsx
- apps/precinct-scanner/src/PreviewDashboard.tsx
- apps/precinct-scanner/src/config/globals.ts
- apps/precinct-scanner/src/config/types.ts
- apps/precinct-scanner/src/contexts/AppContext.ts
- apps/precinct-scanner/src/screens/UnlockAdminScreen.tsx
- apps/precinct-scanner/src/utils/machineConfig.ts
- libs/test-utils/src/smartcards.ts
https://user-images.githubusercontent.com/14897017/134047295-ed9d55ec-9b4e-4961-8e4b-4d9251fefc0f.mov
> feat(ps) ask for security code to unlock admin screen

- apps/precinct-scanner/src/App.test.tsx
- apps/precinct-scanner/src/AppUnhappyPaths.test.tsx
- apps/precinct-scanner/src/screens/UnconfiguredElectionScreen.tsx
> fix(scan): load latest ballot package in PS

- apps/precinct-scanner/src/AppRoot.tsx
This was a temporary hack for dev that I did not mean to commit. Made a ticket to add a test for this: https://zube.io/votingworks/vxsuite/c/3698
> fix(ps) check pollworker card election hash match

- apps/module-scan/src/scanners/plustek.ts
- libs/plustek-sdk/src/scanner.test.ts
- libs/plustek-sdk/src/scanner.ts
This was implemented as a change to `plustek-sdk`. The `#scan` client method now takes a predicate called `shouldRetry` to determine whether a retry should happen. Then, `module-scan` uses this to retry up to 2s.
This should fix an issue where the scanner sees a paper but can't actually grab it. It reports it is ready to scan, but actually scanning results in an IO error. This gives the scanner up to 2s to grab it before giving up.
> fix(scan): retry scans for up to 2s

- apps/bas/.eslintrc.json
- apps/bas/src/App.tsx
- apps/bas/src/AppRoot.test.tsx
- apps/bas/src/AppRoot.tsx
- apps/bas/src/components/Button.tsx
- apps/bas/src/components/ButtonBar.tsx
- apps/bas/src/components/ButtonList.tsx
- apps/bas/src/components/Heading.tsx
- apps/bas/src/components/Main.tsx
- apps/bas/src/components/MainNav.tsx
- apps/bas/src/components/ProgressBar.tsx
- apps/bas/src/components/Prose.tsx
- apps/bas/src/components/Screen.tsx
- apps/bas/src/components/Select.tsx
- apps/bas/src/components/Text.tsx
- apps/bas/src/index.tsx
- apps/bas/src/screens/AdminScreen.tsx
- apps/bas/src/screens/InsertCardScreen.tsx
- apps/bas/src/screens/LoadElectionScreen.tsx
- apps/bas/src/screens/LockedScreen.tsx
- apps/bas/src/screens/NonWritableCardScreen.tsx
- apps/bas/src/screens/PollWorkerScreen.tsx
- apps/bas/src/screens/PrecinctBallotStylesScreen.tsx
- apps/bas/src/screens/PrecinctsScreen.tsx
- apps/bas/src/screens/RemoveCardScreen.tsx
- apps/bas/src/screens/WritingCardScreen.tsx
Enable + autofix, no manual cleanup required.
Refs #1063
> style(bas): `gts-no-default-exports`

- libs/eslint-plugin-vx/src/configs/recommended.ts
- libs/test-utils/package.json
- libs/test-utils/src/arbitraries.ts
- libs/ui/src/hooks/useSmartcard.ts
- pnpm-lock.yaml
Enable `@typescript-eslint/no-unused-vars` ESLint rule.
> style(all): error on unused vars

- libs/utils/.eslintrc.json
- libs/utils/src/Card/MemoryCard.test.ts
- libs/utils/src/Card/MemoryCard.ts
- libs/utils/src/Card/WebServiceCard.ts
- libs/utils/src/Card/index.ts
- libs/utils/src/Hardware/KioskHardware.test.ts
- libs/utils/src/Hardware/KioskHardware.ts
- libs/utils/src/Hardware/MemoryHardware.test.ts
- libs/utils/src/Hardware/MemoryHardware.ts
- libs/utils/src/Hardware/index.test.ts
- libs/utils/src/Hardware/index.ts
- libs/utils/src/Printer/LocalPrinter.ts
- libs/utils/src/Printer/NullPrinter.ts
- libs/utils/src/Printer/index.ts
- libs/utils/src/Storage/KioskStorage.test.ts
- libs/utils/src/Storage/KioskStorage.ts
- libs/utils/src/Storage/LocalStorage.test.ts
- libs/utils/src/Storage/LocalStorage.ts
- libs/utils/src/Storage/MemoryStorage.test.ts
- libs/utils/src/Storage/MemoryStorage.ts
- libs/utils/src/Storage/index.ts
Enabled & autofixed, no manual fixes required.
Refs #1063
> style(utils): `gts-no-default-exports`

- libs/ui/.eslintrc.json
- libs/ui/src/LinkButton.test.tsx
- libs/ui/src/LinkButton.tsx
- libs/ui/src/index.ts
Enable, autofix, cleanup.
Refs #1063
> style(ui): `gts-no-default-exports`

- libs/logging/src/logEventIDs.ts
Adds the documentation information for the logs in: https://github.com/votingworks/vxsuite-complete-system/pull/116
> feat(logging) add docs for system usb logs

- apps/bas/prodserver/index.js
- apps/bmd/prodserver/index.js
- apps/bsd/prodserver/index.js
- apps/module-scan/package.json
- apps/module-scan/src/index.ts
- apps/module-scan/src/server.ts
- apps/module-scan/tsconfig.json
- apps/precinct-scanner/prodserver/index.js
- libs/logging/src/types.ts
- pnpm-lock.yaml
Note this does NOT add anything to module-smartcards or module-converter-sems yet since we are planning to rewrite those in javascript. 
@eventualbuddha Interested in your feedback on the module-scan logs, I didn't want to fall down the rabbit hole of trying to update all the other log() calls yet but will convert those over to the logger and remove that other log variable down the road.
> feat(all) add application startup logs to all apps

- libs/eslint-plugin-vx/docs/rules/gts-module-snake-case.md
- libs/eslint-plugin-vx/src/configs/recommended.ts
- libs/eslint-plugin-vx/src/rules/gts_module_snake_case.ts
- libs/eslint-plugin-vx/src/rules/index.ts
- libs/eslint-plugin-vx/tests/fixtures/tsconfig.json
- libs/eslint-plugin-vx/tests/rules/gts_module_snake_case.test.ts
> feat(eslint): require modules to use `snake_case`

- apps/module-scan/src/server.test.ts
https://zube.io/votingworks/vxsuite/c/3966
> fix(module-scan) hide logs in tests

- libs/lsd/.eslintrc.json
- libs/lsd/src/cli/index.ts
- libs/lsd/src/cli/options.ts
- libs/lsd/src/index.ts
- libs/lsd/src/util/geometry.ts
- libs/lsd/src/util/images.ts
- libs/lsd/src/util/path.ts
> docs(lsd): enable `gts-jsdoc` and add missing JSDoc

- libs/plustek-sdk/.eslintrc.json
- libs/plustek-sdk/src/config.ts
- libs/plustek-sdk/src/errors.ts
- libs/plustek-sdk/src/mocks.ts
- libs/plustek-sdk/src/paper_status.ts
- libs/plustek-sdk/src/plustekctl.ts
- libs/plustek-sdk/src/scanner.ts
Adds docs for all module exports.
Refs #1208
> docs(plustek-sdk): enable `gts-jsdoc`

- frontends/bsd/src/api/config.ts
- frontends/bsd/src/app_root.tsx
- frontends/bsd/src/components/export_results_modal.test.tsx
- frontends/bsd/src/contexts/app_context.ts
- frontends/bsd/src/screens/advanced_options_screen.tsx
- frontends/bsd/test/render_in_app_context.tsx
- libs/logging/src/log_event_ids.ts
Adds logs for all of the actions on the advanced options screen of BSD.
> feat(bsd) add logs for advanced screen actions

- libs/types/package.json
- libs/types/src/api/services/scan/index.test.ts
- libs/types/src/api/services/scan/index.ts
- libs/types/src/election.test.ts
- libs/types/src/election.ts
- libs/types/src/generic.test.ts
- libs/types/src/voting_method.test.ts
- libs/types/test/election.ts
- pnpm-lock.yaml
And ensure we enforce coverage testing in CI.
> test(coverage): fix coverage of `types`

- libs/eslint-plugin-vx/src/rules/gts_array_type_style.ts
- libs/eslint-plugin-vx/src/rules/gts_direct_module_export_access_only.ts
- libs/eslint-plugin-vx/src/rules/gts_func_style.ts
- libs/eslint-plugin-vx/src/rules/gts_jsdoc.ts
- libs/eslint-plugin-vx/src/rules/gts_no_array_constructor.ts
- libs/eslint-plugin-vx/src/rules/gts_no_const_enum.ts
- libs/eslint-plugin-vx/src/rules/gts_no_default_exports.ts
- libs/eslint-plugin-vx/src/rules/gts_no_for_in_loop.ts
- libs/eslint-plugin-vx/src/rules/gts_no_foreach.ts
- libs/eslint-plugin-vx/src/rules/gts_no_import_export_type.ts
- libs/eslint-plugin-vx/src/rules/gts_no_public_modifier.ts
- libs/eslint-plugin-vx/src/rules/gts_parameter_properties.ts
- libs/eslint-plugin-vx/src/rules/gts_spread_like_types.ts
- libs/eslint-plugin-vx/src/rules/gts_use_optionals.ts
- libs/eslint-plugin-vx/src/rules/no_floating_results.ts
- libs/eslint-plugin-vx/src/rules/no_import_workspace_subfolders.ts
- libs/eslint-plugin-vx/tests/fixtures/tsconfig.json
- libs/eslint-plugin-vx/tests/rules/gts_identifiers.test.ts
- libs/eslint-plugin-vx/tests/rules/gts_module_snake_case.test.ts
- libs/eslint-plugin-vx/tests/rules/gts_no_import_export_type.test.ts
- libs/eslint-plugin-vx/tests/rules/gts_object_literal_types.test.ts
- libs/eslint-plugin-vx/tests/rules/gts_parameter_properties.test.ts
- libs/eslint-plugin-vx/tests/rules/gts_unicode_escapes.test.ts
- libs/eslint-plugin-vx/tests/rules/gts_use_optionals.test.ts
- libs/eslint-plugin-vx/tests/rules/no_assert_truthiness.test.ts
- libs/eslint-plugin-vx/tests/rules/no_floating_results.test.ts
And ensure we enforce coverage testing in CI.
> test(coverage): fix coverage of `eslint-plugin-vx`

- frontends/bsd/src/api/hmpb.test.ts
- frontends/bsd/src/api/hmpb.ts
- frontends/bsd/src/app_root.tsx
- frontends/bsd/src/components/election_configuration.tsx
- frontends/bsd/src/components/export_results_modal.tsx
- frontends/bsd/src/config/types.ts
- frontends/bsd/src/screens/ballot_eject_screen.test.tsx
- frontends/bsd/src/screens/ballot_eject_screen.tsx
- frontends/bsd/src/screens/load_election_screen.tsx
- libs/logging/src/log_event_ids.ts
Adds logs to BSD when configuring an election, scanning, deleting a batch, and exporting the CVR.
> feat(bsd) add logs for scanning and configuration

- frontends/bmd/src/pages/__snapshots__/start_page.test.tsx.snap
- frontends/bmd/src/pages/start_page.tsx
> fix(bmd): correct grammar for 1-contest ballots

- script/src/prod-build/build.ts
- script/src/prod-build/deps.ts
- script/src/prod-build/globals.ts
- script/src/prod-build/index.ts
- script/src/prod-build/pnpm.ts
- script/src/prod-build/utils/exec_sync.ts
- script/src/prod-build/utils/exists_sync.ts
- script/src/prod-build/utils/maybe_require.ts
- script/src/prod-build/utils/mkdirp.ts
- script/src/prod-build/utils/relative_path.ts
- script/src/prod-build/utils/rmrf.ts
- script/src/types.ts
- script/src/validate-monorepo/validation.ts
Most of this is just reformatting code, but the changes in `index.ts` account for the service/frontend split.
> build(prod): fix `prod-build` script

- README.md
Testing with Ubuntu 20 on an Apple Silicon Mac revealed some issues with the README:
- the NodeJS download URL was hardcoded to x64 architecture; now it'll detect the archtecture and use the right one (assuming x64 or ARMv8)
- the `export PATH` to include the NodeJS `bin` was wrong
- add a step to verify that we got `pnpm` v5, since that's important
- we now need to build explicitly before starting a frontend, so add that step when trying out BMD
And some changes unrelated to the above:
- we primarily adhere to the Google TypeScript Style Guide, not Airbnb
- emphasize that we need pnpm v5
- it's Ubunbtu 18.04, not 18.0.4
- formatting updates
Refs #1278
> docs(build): quickstart fixes

- frontends/election-manager/src/components/import_cvrfiles_modal.tsx
> fix(em): explicitly say "No" when not previously imported

- services/smartcards/README.md
- services/smartcards/testCardReader.py
Task: #1330 
Beef up the existing card test script to QA multiple cards in a row.
> feat(smartcard): Smartcard QA script

- frontends/precinct-scanner/src/app_root.tsx
- libs/ui/src/hooks/use_smartcard.ts
- libs/ui/src/hooks/use_user_session.ts
- libs/utils/src/Card/memory_card.ts
- libs/utils/src/types.ts
- Update the useSmartcard hook to consume the new smartcard status
- Use the status to determine when to show a new screen with a message about the card being backwards
TODO: write tests
> feat(precinct-scanner): Show message when card inserted backwards

- frontends/precinct-scanner/src/screens/scan_processing_screen.tsx
Replace "Scanning…" with the following:
> feat(bmd): Prompt voter to wait for completed scan.

- frontends/precinct-scanner/src/app_root.tsx
- frontends/precinct-scanner/src/app_unhappy_paths.test.tsx
- frontends/precinct-scanner/src/preview_app.tsx
- frontends/precinct-scanner/src/screens/card_error_screen.tsx
> feat(precinct-scanner): Card backwards screen

- frontends/bmd/src/app_card_unhappy_paths.test.tsx
- frontends/bmd/src/app_root.tsx
- frontends/bmd/src/pages/card_error_screen.tsx
> feat(bmd): Card backwards screen

- frontends/bsd/src/components/election_configuration.tsx
- frontends/bsd/src/components/export_results_modal.test.tsx
- frontends/bsd/src/components/export_results_modal.tsx
- frontends/election-manager/README.md
- frontends/election-manager/public/index.html
- frontends/election-manager/public/manifest.json
- frontends/election-manager/src/__snapshots__/app.test.tsx.snap
- frontends/election-manager/src/app.test.tsx
- frontends/election-manager/src/components/navigation.tsx
- frontends/election-manager/src/screens/unconfigured_screen.tsx
- frontends/precinct-scanner/src/components/export_results_modal.test.tsx
- frontends/precinct-scanner/src/components/export_results_modal.tsx
> feat(all): Update Election Manager name to VxAdmin

- frontends/bsd/README.md
- frontends/bsd/prodserver/index.js
- frontends/bsd/public/index.html
- frontends/bsd/src/api/hmpb.test.ts
- frontends/bsd/src/app.test.tsx
- frontends/bsd/src/app_root.tsx
- frontends/bsd/src/components/export_results_modal.test.tsx
- frontends/bsd/src/components/main_nav.tsx
- frontends/bsd/src/contexts/app_context.ts
- frontends/bsd/src/screens/__snapshots__/ballot_eject_screen.test.tsx.snap
- frontends/bsd/src/screens/ballot_eject_screen.test.tsx
- frontends/bsd/test/render_in_app_context.tsx
- frontends/election-manager/src/components/export_election_ballot_package_modal_button.tsx
- integration-testing/bsd/cypress/integration/configuration.ts
- libs/logging/VotingWorksLoggingDocumentation.md
- libs/logging/src/log_documentation.test.ts
- libs/logging/src/log_event_ids.ts
- libs/logging/src/log_source.ts
- libs/logging/src/types.ts
- libs/ui/src/hooks/use_hardware.test.ts
- libs/ui/src/hooks/use_user_session.test.tsx
Task: #1363 
Notably, I also updated the logs, which were using the outdated name
VxBatch.
> feat(all): Update Batch Scanner name to VxCentralScan

- frontends/precinct-scanner/README.md
- frontends/precinct-scanner/public/index.html
- frontends/precinct-scanner/public/manifest.json
- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/screens/unconfigured_election_screen.tsx
- libs/ui/src/precinct_scanner_polls_report.tsx
> feat(precinct-scanner): Update Precinct Scanner name to VxScan

- frontends/bsd/src/app.test.tsx
- frontends/bsd/src/app_root.tsx
- frontends/bsd/src/components/election_configuration.test.tsx
- frontends/bsd/src/components/election_configuration.tsx
- frontends/bsd/src/screens/advanced_options_screen.test.tsx
- frontends/bsd/src/screens/advanced_options_screen.tsx
- integration-testing/bsd/cypress/integration/configuration.ts
https://user-images.githubusercontent.com/28444/151895284-72a0203f-276a-4830-95d4-a25e681b5278.mov
> feat(bsd): Simpler unconfigure language.

- frontends/election-manager/src/screens/unlock_machine_screen.test.tsx
- frontends/election-manager/src/screens/unlock_machine_screen.tsx
https://user-images.githubusercontent.com/28444/151896710-3fa2a7b9-47e4-418b-ad9a-0221457fe5b0.mov
> VxAdmin: Simpler unconfigure language.

- libs/ui/src/precinct_scanner_tally_qrcode.tsx
In the event that `PrecinctScannerTallyQrCode` is unmounted after the call to `window.kiosk.sign` is made but before it resolves, the call to `setResultsReportingUrl` after it will cause this error:
> Can't perform a React state update on an unmounted component
This change fixes that by ensuring that the `sign` call does not resolve or reject (i.e. is canceled) if the component is unmounted.
> fix(ui): cancel reporting URL update on unmount

- frontends/bmd/src/components/modal.tsx
> fix(bmd): Don't show modal in printed tally reports

- frontends/bsd/src/app.test.tsx
- frontends/bsd/src/app_root.tsx
- frontends/bsd/src/screens/admin_actions_screen.test.tsx
- frontends/bsd/src/screens/admin_actions_screen.tsx
- integration-testing/bsd/cypress/integration/configuration.ts
> CentralScan: Rename screen: 'Advanced Options' to 'Admin Actions'.

- frontends/election-manager/package.json
- frontends/election-manager/src/__snapshots__/app.test.tsx.snap
- frontends/election-manager/src/screens/advanced_screen.test.tsx
- frontends/election-manager/src/screens/advanced_screen.tsx
> feat(em): Show/set current date and time

- frontends/bsd/package.json
- frontends/bsd/src/screens/admin_actions_screen.test.tsx
- frontends/bsd/src/screens/admin_actions_screen.tsx
- pnpm-lock.yaml
> feat(bsd): Set current date and time

- .github/pull_request_template.md
Keeping things simple to start, but if anyone has suggestions for other checklist items to add please let me know!
> Create default pull request template

- frontends/bsd/src/screens/ballot_eject_screen.test.tsx
- frontends/bsd/src/screens/ballot_eject_screen.tsx
applying small bsd blank-ballot fix on maintenance branch
> fix(bsd): interpret blank single-page ballots appropriately

- frontends/bsd/src/components/export_results_modal.tsx
- frontends/election-manager/src/components/confirm_removing_file_modal.tsx
- frontends/election-manager/src/components/export_election_ballot_package_modal_button.tsx
- frontends/election-manager/src/components/export_logs_modal.tsx
- frontends/election-manager/src/components/import_cvrfiles_modal.tsx
- frontends/election-manager/src/components/import_external_results_modal.tsx
- frontends/election-manager/src/components/print_button.tsx
- frontends/election-manager/src/components/remove_election_modal.tsx
- frontends/election-manager/src/components/save_file_to_usb.tsx
- frontends/election-manager/src/screens/smartcards_screen.tsx
- frontends/election-manager/src/screens/tally_screen.tsx
> fix(em/bsd): Sort modal buttons in tab order

- libs/ui/src/modal.tsx
Didn't proofread #1457 thoroughly enough.
n/a
n/a
> fix(ui): typo

- services/smartcards/testCardReader.py
- Use VXCardObserver directly instead of going through smartcards.core.CardInterface
- Use while loops like a normal person
N/A
Manual test
> refactor(smartcards): Clean up testCardReader.py

- frontends/bmd/src/pages/poll_worker_screen.tsx
Fixes #1463
Per #1463, makes Open/Close Polls buttons green.
> fix(ui): style VxMark Open/Close Polls button as primary

- libs/ballot-interpreter-vx/src/utils/path.test.ts
Somehow this got separated from the code it was testing.
n/a
> test(scan): colocate `path` util test

- frontends/bas/src/screens/admin_screen.tsx
> fix(bas): Use danger styles for remove election definition button

- integration-testing/bsd/cypress/integration/configuration.ts
- services/scan/src/end_to_end_hmpb.test.ts
- services/scan/src/store.test.ts
- services/scan/src/store.ts
[#1409](https://github.com/votingworks/vxsuite/issues/1409)
> fix(scan): default scan service to test mode

- .github/pull_request_template.md
Adds prompts to the pull request template for user facing changes
> Update pull_request_template.md to add user_facing_change label

- script/src/prod-build/index.ts
follow up and reenable pruning with:
https://github.com/votingworks/vxsuite/issues/1591
> fix(build): stop pruning dependencies for now, as that seems to be causing errors

- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/app_tally_report_paths.test.tsx
- frontends/precinct-scanner/src/screens/poll_worker_screen.tsx
https://github.com/votingworks/vxsuite/issues/1598
Previous tests checking for unmounting usb failed, updated tests to not look for that.
> fix(scan) remove auto eject of usb on polls close

- libs/ballot-interpreter-nh/package.json
- libs/ballot-interpreter-nh/src/cli/convert/index.ts
- libs/ballot-interpreter-nh/src/debug.ts
- libs/ballot-interpreter-nh/test/fixtures/index.ts
- pnpm-lock.yaml
See https://github.com/xmldom/xmldom/issues/271
n/a
> chore(scan): update `xmldom`

- README.md
- VirtualMachineSetup.md
As the most recent engineer to go through the dev env setup instructions, I encountered just a few gaps. This PR fills in those gaps!
> Make small additions to dev env setup instructions

- frontends/bmd/src/pages/poll_worker_screen.test.tsx
- frontends/bmd/src/pages/poll_worker_screen.tsx
This is prep for adding more props for the hardware diagnostic to the pollworker screen.
N/A
N/A
> test(bmd): Factor out render in pollworker screen test

- package.json
Adds a new command `pnpm clean-all` to delete all git ignored files. The common use case for this is removing node_modules or built modules when something gets wonky.
N/A
N/A
> chore: `pnpm clean-all` command

- libs/ballot-interpreter-nh/src/layout.ts
Caused by a merge conflict.
n/a
n/a
> fix(scan): correct location for `BallotCardGeometry`

- services/scan/src/loop_scanner.test.ts
Cherry-picking f8a6fa50484462f4454aace991582dd2b62b3681 onto `main` since I think we clearly want it.
n/a
n/a
> fix type for writeFileSync data argument

- libs/eslint-plugin-vx/src/configs/recommended.ts
- services/scan/src/store.ts
Also fixes the violations that it found.
n/a
Automated.
> style(lint): enforce `explicit-module-boundary-types`

- frontends/bmd/cypress/tests/scroll_buttons.ts
- frontends/bmd/package.json
- integration-testing/bsd/package.json
- integration-testing/election-manager/package.json
- pnpm-lock.yaml
Fixes #1718
N/A
Tests should pass.
> chore(all): Upgrade to Cypress 9

- .circleci/config.yml
- services/converter-ms-sems/Makefile
- services/scan/src/cli/mock-scanner/index.test.ts
Closes #1695 
Closes #1698 
This branch was put together by @taravancil, with assistance from me. Let's review early next week.
n/a
Automated testing & light manual testing.
> Upgrade to Node 16 in dev & CI

- README.md
- script/setup-dev
Changes the `setup-dev` script to use Node 16. Also updates the setup guide to reference Node 16.
n/a
n/a
> chore(node): more v16 updates

- README.md
Fixes another place where we should have said Node 16 instead of 12.
n/a
n/a
> docs: update NodeJS version

- frontends/precinct-scanner/src/components/calibrate_scanner_modal.tsx
Closes #1737 
Fixes a typo in the precinct scanner's calibration modal.
N/A
> fixed typo in calibration modal

- frontends/bsd/src/app_root.tsx
- frontends/bsd/src/components/election_configuration.tsx
- frontends/bsd/src/components/main.tsx
- frontends/bsd/src/components/screen.tsx
- frontends/bsd/src/screens/__snapshots__/ballot_eject_screen.test.tsx.snap
- frontends/bsd/src/screens/admin_actions_screen.tsx
- frontends/bsd/src/screens/ballot_eject_screen.tsx
- frontends/bsd/src/screens/invalid_card_screen.tsx
- frontends/bsd/src/screens/load_election_screen.tsx
- frontends/bsd/src/screens/machine_locked_screen.tsx
- frontends/bsd/src/screens/unlock_machine_screen.tsx
- frontends/bsd/src/screens/write_in_adjudication_screen.tsx
> feat(bsd): use Screen from ui/lib

- libs/ballot-encoder/src/README.md
Spelling! How does it work?
n/a
n/a
> docs(ballot-encoder): fix typo

- frontends/election-manager/src/components/write_ins_transcription_screen.test.tsx
- frontends/election-manager/src/components/write_ins_transcription_screen.tsx
Fixes an import that failed on `main`.
> fix(election-manager): fix Main + MainChild import

- frontends/election-manager/src/screens/write_ins_screen.tsx
Implements some post-merge suggestions from @eventualbuddha from https://github.com/votingworks/vxsuite/pull/1796
Automated.
> chore(election-manager): improve types for WriteInsScreen

- libs/logging/tsconfig.build.json
This config should not extend `eslint-plugin-vx`'s config, but `logging`'s own `tsconfig.json`.
n/a
n/a
> build(logging): fix `tsconfig.build.json`

- frontends/precinct-scanner/src/app_root.tsx
- frontends/precinct-scanner/src/components/layout.tsx
- frontends/precinct-scanner/src/screens/admin_screen.tsx
- frontends/precinct-scanner/src/screens/card_error_screen.tsx
- frontends/precinct-scanner/src/screens/insert_ballot_screen.tsx
- frontends/precinct-scanner/src/screens/insert_usb_screen.tsx
- frontends/precinct-scanner/src/screens/invalid_card_screen.tsx
- frontends/precinct-scanner/src/screens/loading_configuration_screen.tsx
- frontends/precinct-scanner/src/screens/poll_worker_screen.tsx
- frontends/precinct-scanner/src/screens/polls_closed_screen.tsx
- frontends/precinct-scanner/src/screens/scan_error_screen.tsx
- frontends/precinct-scanner/src/screens/scan_processing_screen.tsx
- frontends/precinct-scanner/src/screens/scan_success_screen.tsx
- frontends/precinct-scanner/src/screens/scan_warning_screen.tsx
- frontends/precinct-scanner/src/screens/setup_power_page.tsx
- frontends/precinct-scanner/src/screens/setup_scanner_screen.tsx
- frontends/precinct-scanner/src/screens/unconfigured_election_screen.tsx
- frontends/precinct-scanner/src/screens/unlock_admin_screen.tsx
Rename component to reflect the components it combines.
> feat(precinct-scanner): More explicit component naming

- services/admin/.eslintignore
- services/admin/.eslintrc.json
- services/admin/.gitignore
- services/admin/jest.config.js
- services/admin/src/server.ts
- services/admin/tsconfig.json
- services/scan/tsconfig.json
This is a few fixups suggested by @eventualbuddha in the CR for https://github.com/votingworks/vxsuite/pull/1837.
Automated.
> A few fixups for `services/admin`

- integration-testing/election-manager/cypress/integration/configuration.ts
- services/converter-ms-sems/converter/SEMSinput.py
- services/converter-ms-sems/sample_files/10_3-10-2020-expected-election.json
- services/converter-ms-sems/sample_files/10_8-26-2020-expected-election.json
- services/converter-ms-sems/sample_files/10_9-22-2020-expected-election.json
- services/converter-ms-sems/sample_files/10_expected-election.json
- services/converter-ms-sems/sample_files/53_expected-election.json
> update default mark threshold to 12%

- libs/ui/src/precinct_scanner_tally_qrcode.test.tsx
- libs/ui/src/precinct_scanner_tally_qrcode.tsx
It's unlikely to happen, but it's possible that the `useEffect` that signs the VxQR results payload will set the results reporting URL to a stale value if two back-to-back renders have `kiosk.sign` calls that return out of order.
We were wrapping the `kiosk.sign` result `Promise` in `makeCancelable`, but that only prevents calling `setResultsReportingUrl` if the component _is unmounted entirely_. It does not stop an earlier render from clobbering the URL update from a re-render.
The fix is to track whether the current render is stale. `useEffect` will call the returned function both on unmount _and on re-render_. We use that to mark a render as stale and do not update the URL if it is stale by the time the `kiosk.sign` call resolves.
If this is something we find ourselves doing often it …
> fix(ui): correct `setResultsReportingUrl` race condition

- frontends/bmd/src/pages/print_only_screen.tsx
Ran across this TODO to remove an assert after upgrading TS.
N/A
N/A
> chore(bmd): Remove unnecessary assert

- libs/api/jest.config.js
- libs/ballot-encoder/jest.config.js
- libs/ballot-interpreter-vx/jest.config.js
- libs/cdf-schema-builder/jest.config.js
- libs/cdf-types-cast-vote-records/jest.config.js
- libs/cdf-types-election-event-logging/jest.config.js
- libs/eslint-plugin-vx/jest.config.js
- libs/fixtures/jest.config.js
- libs/logging/jest.config.js
- libs/lsd/jest.config.js
- libs/plustek-sdk/jest.config.js
- libs/res-to-ts/jest.config.js
- libs/test-utils/jest.config.js
- libs/types/jest.config.js
- libs/ui/jest.config.js
- libs/utils/jest.config.js
For VS Code autocomplete.
n/a
n/a
> chore(jest): annotate types for all jest config

- libs/ui/src/prose.tsx
Related: https://github.com/votingworks/vxsuite-roadmap/issues/44
> docs(ui): Add documentation for Prose component

- writing-style-guide.md
Related: https://github.com/votingworks/vxsuite-roadmap/issues/44
> docs(vxsuite): Add general writing style guide.

- frontends/election-manager/src/screens/smartcards_screen.tsx
Task: #1931
When encoding admin cards, the browser seems to convert LF to CRLF line endings when making a multi-part form request. This causes election hash mismatches. To prevent this, we use x-www-url-encoded encoding in the POST submission.
N/A
> fix(election-manager): encode election data properly when writing admin card

- frontends/bmd/src/pages/superadmin_screen.test.tsx
- frontends/bmd/src/pages/superadmin_screen.tsx
- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/app_root.tsx
so it's easy to quit kiosk-browser in vxdev.
> feature(reset): add reset button to vxmark and vxscan superadmin screens

- frontends/bsd/.eslintignore
- frontends/bsd/config/env.js
- frontends/bsd/config/jest/cssTransform.js
- frontends/bsd/config/paths.js
- frontends/bsd/jest.config.js
- frontends/bsd/package.json
- frontends/bsd/scripts/test.js
- pnpm-lock.yaml
Refs #1314
n/a
Ran `pnpm test:watch` and `pnpm test:coverage`.
> test(bsd): switch from CRA to vite

- frontends/bmd/src/app_card_unhappy_paths.test.tsx
- frontends/bmd/src/app_cardless_voting.test.tsx
- frontends/bmd/src/app_data.test.tsx
- frontends/bmd/src/app_end_to_end.test.tsx
- frontends/bmd/src/app_mark_voter_card_invalid.test.tsx
- frontends/bmd/src/app_refresh.test.tsx
- frontends/bmd/src/app_root.tsx
- frontends/bmd/src/components/__snapshots__/focus_manager.test.tsx.snap
- frontends/bmd/src/components/focus_manager.test.tsx
- frontends/bmd/src/components/focus_manager.tsx
- frontends/bmd/src/config/globals.ts
- frontends/bmd/src/config/types.ts
- frontends/bmd/src/demo_app.tsx
- frontends/bmd/src/pages/idle_page.tsx
- frontends/bmd/src/pages/poll_worker_screen.tsx
- frontends/bmd/src/pages/print_only_screen.tsx
- frontends/bmd/src/pages/print_page.tsx
- frontends/bmd/src/utils/utc_timestamp.ts
- frontends/bmd/test/helpers/smartcards.ts
- libs/test-utils/src/smartcard_auth.ts
- libs/types/src/smartcard_auth.ts
- libs/ui/src/hooks/use_smartcard_auth.test.ts
- libs/ui/src/hooks/use_smartcard_auth.ts
- libs/utils/package.json
- libs/utils/src/date.test.ts
- libs/utils/src/date.ts
- pnpm-lock.yaml
Accidentally merged #2021 into another feature branch instead of main, so reopening in a new PR.
> refactor(bmd): Use useSmartcardAuth for voters (3rd attempt)

- frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
I think this does what @eventualbuddha described to find the right contest layout bounds, but I'm not completely sure. It seems to work with our ballots on very limited testing but definitely doesn't work right on the NH ballots.
> update logic for finding layout info for contest

- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/app_unhappy_paths.test.tsx
- frontends/precinct-scanner/src/screens/scan_warning_screen.test.tsx
- frontends/precinct-scanner/src/screens/scan_warning_screen.tsx
Hides the count ballot button on VxScan for overvotes
> remove count ballot button on overvotes for precinct scanner

- libs/ballot-interpreter-nh/src/interpret/index.test.ts
Noticed that tests on main are failing. Updating these snapshots should do the trick! Not entirely sure why the corresponding PR (https://github.com/votingworks/vxsuite/pull/2091) didn't see test failures before merging - maybe some merge conflicts with another PR that GitHub didn't catch as merge conflicts
> Update snapshots to fix tests on main

- frontends/precinct-scanner/src/screens/scan_warning_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/2096
> Update NH-specific overvote copy based on recent leg

- frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
> fix(nh): show contest title and adjudication ID

- frontends/election-manager/src/screens/write_ins_screen.tsx
When contest section and title are the same, show only one.
> Small wia ux fix

- frontends/election-manager/src/utils/downloadable_archive.ts
fixes #2115
We saw this in dev but didn't take it seriously enough. It looks like the Zip / Vite refactoring for `election-manager` closed the outer zip writer, but not the inner `Kiosk.FileWriter` instance. That left the writer open, and then we couldn't eject USB drives anymore, but only when saving the ballot package.
Now we keep track of the `FileWriter` and call `end()` when needed.
> fix(em): close the kiosk filewriter when done saving zip file.

- README.md
We no longer use CRA, so this no longer applies.
n/a
n/a
> doc: remove outdated React advice

- libs/res-to-ts/bin/res-to-ts
This can cause any output not yet flushed to be lost.
n/a
n/a
> fix(res-to-ts): do not immediately exit from CLI

- frontends/bmd/src/app_card_unhappy_paths.test.tsx
- frontends/bmd/src/app_cardless_voting.test.tsx
- frontends/bmd/src/app_end_to_end.test.tsx
- frontends/bmd/src/app_mark_only.test.tsx
- frontends/bmd/src/app_mark_voter_card_invalid.test.tsx
- frontends/bmd/src/app_quit_on_idle.test.tsx
- frontends/bmd/src/app_setup_errors.test.tsx
- frontends/bmd/src/pages/insert_card_screen.tsx
Closes #1521. I didn't go with the copy suggested in the ticket because I didn't think it looked good or was necessary. 
Tried this as suggested in ticket and didn't like it because it is repetitive:
Did this instead:
> fix(bmd): remove voter card copy

- frontends/precinct-scanner/src/app_root.tsx
Three changes here:
- Split out the scanner config state into its own interface
- Rename `isScannerConfigured` to `isScannerConfigLoaded` to clarify what that flag is for
- Remove unnecessary action `unconfigureScanner` which didn't seem to actually be doing anything, since it was only used when initializing the scanner failed, which just meant the config wasn't loaded
- Manually tested two cases:
- failing to initialize when the scan service was down
- unconfiguring the scan service
> refactor(precinct-scanner): Split out scanner config state

- frontends/bmd/src/pages/superadmin_screen.test.tsx
- frontends/bmd/src/pages/superadmin_screen.tsx
- frontends/bsd/src/app.test.tsx
- frontends/bsd/src/app_root.tsx
- frontends/election-manager/src/components/election_manager.tsx
- frontends/election-manager/src/screens/settings_screen.test.tsx
- frontends/election-manager/src/screens/settings_screen.tsx
- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/app_root.tsx
- libs/@types/kiosk-browser/kiosk-browser.d.ts
- libs/test-utils/src/fake_kiosk.ts
- libs/ui/src/index.ts
- libs/ui/src/reboot_to_bios_button.test.tsx
- libs/ui/src/reboot_to_bios_button.tsx
As part of #1862, add an option to reboot into BIOS on the superadmin screen.
> Reboot to BIOS

- libs/plustek-sdk/src/config.ts
which we suspect has a race condition causing occasional segfaults.
> fix(plustek): turn off swdeskew

- frontends/election-manager/src/screens/settings_screen.test.tsx
- frontends/election-manager/src/screens/settings_screen.tsx
> feat(em): adjust display of settings screen buttons

- frontends/election-manager/src/__snapshots__/app.test.tsx.snap
- frontends/election-manager/src/app.test.tsx
- frontends/election-manager/src/screens/logic_and_accuracy_screen.tsx
- frontends/election-manager/src/screens/print_test_deck_screen.test.tsx
- frontends/election-manager/src/screens/print_test_deck_screen.tsx
> L&A Screen Instructions

- frontends/election-manager/src/__snapshots__/app.test.tsx.snap
Builds on main started failing after I merged https://github.com/votingworks/vxsuite/pull/2267, due to some under the hood conflict with another recent merge and snapshots - updating these snapshots should get things passing again!
> Fix builds on main by updating snapshots

- services/scan/src/precinct_scanner_app.test.ts
- services/scan/src/precinct_scanner_state_machine.ts
Task: https://github.com/votingworks/vxsuite/issues/2258
> fix(scan): Mark scanned ballots in simple interpreter as adjudicated

- frontends/bmd/src/app_root.tsx
- frontends/bmd/src/pages/poll_worker_screen.test.tsx
- frontends/bmd/src/pages/poll_worker_screen.tsx
Closes #1822
Open to feedback on the design!
Manual testing + automated test.
> feat(bmd): Add ballots printed count to pollworker screen

- frontends/bmd/public/fonts/noto-emoji.css
- frontends/bsd/public/fonts/noto-emoji.css
- frontends/election-manager/public/fonts/noto-emoji.css
- frontends/precinct-scanner/public/fonts/noto-emoji.css
Small cleanup suggeted by @arsalansufi
> clearnup(all): reorder font-face statements

- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/app_unhappy_paths.test.tsx
- frontends/precinct-scanner/src/screens/insert_ballot_screen.tsx
- frontends/precinct-scanner/src/screens/invalid_card_screen.tsx
- frontends/precinct-scanner/src/screens/polls_closed_screen.tsx
- frontends/precinct-scanner/src/screens/scan_busy_screen.tsx
- frontends/precinct-scanner/src/screens/scan_error_screen.test.tsx
- frontends/precinct-scanner/src/screens/scan_error_screen.tsx
- frontends/precinct-scanner/src/screens/scan_jam_screen.tsx
- frontends/precinct-scanner/src/screens/scan_processing_screen.tsx
- frontends/precinct-scanner/src/screens/scan_returned_ballot_screen.tsx
- frontends/precinct-scanner/src/screens/scan_warning_screen.test.tsx
- frontends/precinct-scanner/src/screens/scan_warning_screen.tsx
- frontends/precinct-scanner/src/screens/setup_power_page.tsx
- frontends/precinct-scanner/src/screens/setup_scanner_screen.tsx
1. Run app.
2. Go to localhost:3000/preview
> feat(ps): Design and copy review.

- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/components/replace_ballot_bag_modal.tsx
- frontends/precinct-scanner/src/preview_app.tsx
A few design and copy updates to add to @adghayes' [ Ballot Bag Capacity Stop PR](https://github.com/votingworks/vxsuite/pull/2320)
> feat(ps): replace ballot bag prompt

- frontends/precinct-scanner/src/app_root.tsx
- frontends/precinct-scanner/src/screens/polls_closed_screen.tsx
- frontends/precinct-scanner/src/screens/scan_error_screen.test.tsx
- frontends/precinct-scanner/src/screens/scan_error_screen.tsx
- frontends/precinct-scanner/src/screens/scan_jam_screen.tsx
- frontends/precinct-scanner/src/screens/scan_success_screen.tsx
- frontends/precinct-scanner/src/screens/setup_scanner_screen.tsx
Closes #2282 
I didn't add the count to "modal" pages where the voter needs to make choice, or screens instructing the user to remove a card.
> feat(ps): Add Ballots Scanned count to more pages

- frontends/precinct-scanner/src/screens/scan_warning_screen.tsx
- libs/ui/src/modal.test.tsx
- libs/ui/src/modal.tsx
https://user-images.githubusercontent.com/28444/184252859-0eeca331-71ba-43be-8da9-2fc1d7f05931.mov
Closes #1575
> feat(ps): Use large theme to make voter modals bigger.

- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/app_unhappy_paths.test.tsx
- frontends/precinct-scanner/src/screens/election_manager_screen.test.tsx
- frontends/precinct-scanner/src/screens/election_manager_screen.tsx
> fix(copy): change 'unconfigure' to 'delete election data'.

- frontends/bsd/src/screens/admin_actions_screen.test.tsx
- frontends/bsd/src/screens/admin_actions_screen.tsx
- frontends/precinct-scanner/src/components/export_backup_modal.test.tsx
- frontends/precinct-scanner/src/components/export_backup_modal.tsx
Closes #2325. Also fixes the export --> save language for backups only, as part of #1443.
> fix(ps,bsd): save backup language + consistency

- frontends/election-manager/src/app.test.tsx
- frontends/election-manager/src/screens/unconfigured_screen.tsx
Change the demo election to be the Famous Names election we use for all of our demos.
> fix(election-manager): change demo election to the famous-names one.

- frontends/bsd/src/components/ballot_sheet_image.tsx
- frontends/bsd/src/screens/__snapshots__/ballot_eject_screen.test.tsx.snap
- frontends/bsd/src/screens/ballot_eject_screen.test.tsx
- frontends/bsd/src/screens/ballot_eject_screen.tsx
> feat(bsd): clarify adjudication screen

- frontends/precinct-scanner/src/screens/scan_returned_ballot_screen.tsx
Removes the "Insert Ballot" icon from the "Returned Ballot" page, which some found confusing.
> ps: remove remove ballot icon

- libs/plustek-sdk/src/mocks.test.ts
- libs/plustek-sdk/src/mocks.ts
- libs/plustek-sdk/src/scanner.test.ts
- libs/plustek-sdk/src/scanner.ts
- services/scan/src/precinct_scanner_app.test.ts
- services/scan/src/precinct_scanner_state_machine.ts
- services/scan/src/scanners/plustek.ts
Cherry picks #2398 from m14-release-branch into main
> Cherry pick #2398: fix(scan): Fail when Plustek only returns one scanned page

- frontends/bsd/src/app.test.tsx
- frontends/bsd/src/app_root.tsx
- frontends/bsd/src/components/export_results_modal.test.tsx
- frontends/bsd/src/components/export_results_modal.tsx
- frontends/precinct-scanner/src/app.test.tsx
- frontends/precinct-scanner/src/components/export_results_modal.test.tsx
- frontends/precinct-scanner/src/components/export_results_modal.tsx
- frontends/precinct-scanner/src/screens/election_manager_screen.test.tsx
- frontends/precinct-scanner/src/screens/election_manager_screen.tsx
- integration-testing/bsd/cypress/e2e/configuration.cy.ts
https://github.com/votingworks/vxsuite/issues/2368
ot
Manual testing and ran tests
> feat(bsd) update copy to save cvrs not results

- services/scan/src/precinct_scanner_state_machine.ts
Odds an ends to make the state machine more readable. No functional changes.
N/A
> refactor(scan): Clean up the state machine

- services/scan/src/precinct_scanner_app.test.ts
- services/scan/src/precinct_scanner_state_machine.ts
Previously, if we got an unexpected scanning error and the Plustek was still responsive, we would either automatically retry scanning or reject and let the voter retry, depending on the paper status. Now, if we get an unexpected scanning error, we handle it like any other unexpected error, reconnecting to Plustek. This will hopefully make us more resilient to scanning errors where we don't know the root cause.
N/A
- Various manual scan error tests
> m14-release-branch: fix(scan): Reconnect to plustek after any unexpected scanning error

- services/scan/src/interpreter.test.ts
- services/scan/src/interpreter.ts
- services/scan/src/precinct_scanner_app.test.ts
- services/scan/src/precinct_scanner_app.ts
- services/scan/src/simple_interpreter.ts
Version of 
https://github.com/votingworks/vxsuite/pull/2439
For the m14-release-branch
> fix(scan) reject ballots with the wrong precinct

- frontends/precinct-scanner/src/app_root.tsx
Fixes bug identified in testing (https://votingworks.slack.com/archives/C03KGSP78MQ/p1661208205049509) where newly added frontend state (the last time the ballot bag was replaced, and whether the sounds are muted) were not persisted across restarts. 
> fix(ps): persist new frontend state

- services/scan/src/precinct_scanner_app.test.ts
- Reduce some of the delays
- Mock interpretation where possible
Reduces the total test time from ~140s to ~70s on my machine
> test(scan): Optimize precinct scanner app tests

- libs/fixtures/bin/generate-sample-cvr-file
- libs/fixtures/jest.config.js
- libs/fixtures/src/cli/generate-sample-cvr-file/index.ts
- libs/fixtures/src/cli/generate-sample-cvr-file/main.ts
- libs/fixtures/src/generate_cvrs.test.ts
- libs/fixtures/src/generate_cvrs.ts
- libs/fixtures/src/index.ts
- libs/fixtures/src/utils.test.ts
- libs/fixtures/src/utils.ts
Also restructures the `generate-sample-cvr-file` script to be part of `src` so we can test it. Omits tests for the CLI part as testing `yargs` is hard.
```
❯ ./bin/generate-sample-cvr-file -e data/electionMinimalExhaustiveSample/electionMinimalExhaustiveSample.json         
Wrote 168 cast vote records to output.jsonl
```
**output.jsonl**
```
{"_ballotId":"id-0","_ballotType":"absentee","_precinctId":"precinct-1","_ballotStyleId":"1M","_testBallot":true,"_scannerId":"scanner","_batchId":"batch-1","_batchLabel":"Batch 1","best-animal-mammal":[],"zoo-council-mammal":[],"new-zoo-either":["yes"],"new-zoo-pick":["yes"]}
{"_ballotId":"id-1","_ballotType":"absentee","_precinctId":"precinct-1","_ballotStyleId":"1M","_testBallot":true,"_scannerId":"scanner","_batchId":"batch-1","_batchLabel":"Batch …
```
> feat(fixtures): make `generateCvrs` available

- frontends/bsd/src/app_root.tsx
- frontends/precinct-scanner/src/components/export_backup_modal.test.tsx
- frontends/precinct-scanner/src/components/export_backup_modal.tsx
- frontends/precinct-scanner/src/screens/election_manager_screen.tsx
- services/scan/src/backup.test.ts
- services/scan/src/backup.ts
- services/scan/src/central_scanner_app.ts
- services/scan/src/precinct_scanner_app.ts
> merge https://github.com/votingworks/vxsuite/pull/2481 to the release

- frontends/bmd/src/app_root.tsx
- frontends/bmd/src/pages/system_administrator_screen.test.tsx
- frontends/bmd/src/pages/system_administrator_screen.tsx
- frontends/bsd/src/app_root.tsx
- frontends/precinct-scanner/src/app_root.tsx
- libs/ui/src/system_administrator_screen_contents.test.tsx
- libs/ui/src/system_administrator_screen_contents.tsx
- libs/ui/src/unconfigure_machine_button.test.tsx
- libs/ui/src/unconfigure_machine_button.tsx
> Disable "Unconfigure Machine" button if machine is not configured

- pnpm-lock.yaml
This is the result of running `npx browserslist@latest --update-db`.
n/a
n/a
> chore(deps): browserlist update

- .github/workflows/add-to-vxsuite.yml
> Add action to automatically add issues to vxsuite project

- frontends/precinct-scanner/src/components/replace_ballot_bag_screen.tsx
[Found by @ginvdr](https://votingworks.slack.com/archives/CJU9MSC6S/p1662037944523049).
Previously:
n/a
> fix(scan): correct typo in bag replacement copy

- README.md
- libs/utils/src/environment_flag.ts
Adds a few comments and readme update for the feature flag change.
> Add readme for feature flags and comment update 

- services/scan/src/precinct_scanner_app.test.ts
These are tests that are similar to the flaky test that we already fixed in #2535. We apply the same fix here.
> test(scan): Add delay to flaky precinct scanner tests

- frontends/election-manager/jest.config.js
- frontends/election-manager/src/screens/write_ins_adjudication_screen.tsx
- frontends/election-manager/src/screens/write_ins_screen.test.tsx
- frontends/election-manager/src/screens/write_ins_screen.tsx
- frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
Create a UI for mapping Transcription valuess to Adjudication values.
https://user-images.githubusercontent.com/28444/189997945-067b1d94-fb46-4ee0-8f22-3264a2bb5780.mov
TBD as feature is integrated with backend.
> Adjudication UI

- services/scan/src/precinct_scanner_app.test.ts
One more test that I didn't fix in #2535 or #2551
> test(scan): Fix one more flaky scanner test

- frontends/election-manager/src/__snapshots__/app.test.tsx.snap
- libs/utils/src/environment_flag.ts
We will need this for the images for the NH demo
> allow wia flag to be enabled in prod

- frontends/election-manager/src/components/election_manager_tally_report.tsx
- frontends/election-manager/src/lib/votecounting.ts
- frontends/election-manager/src/screens/tally_report_screen.tsx
Note that I'm not seeing adjudicatedOptionId always set properly but assuming it is this will include those tallies in our regular tally reports and subtract them from the write-ins row. I don't love the way I did this, or the lack of testing, we should revisit this after the demo, and also make it a configurable thing since I imagine some jurisdictions won't want this. 
Manually adjudicated as real candidates, saw the tally report adjust accordingly.
> include official write ins in tally reports

- frontends/election-manager/src/hooks/use_election_manager_store.ts
- frontends/election-manager/src/screens/write_ins_screen.test.tsx
- frontends/election-manager/src/screens/write_ins_screen.tsx
- frontends/election-manager/src/screens/write_ins_transcription_screen.test.tsx
- frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
- services/admin/src/server.ts
Review by commit.
n/a
Manual spot checking.
> misc write-in adjudication fixes

- frontends/election-manager/src/lib/backends/admin_backend.ts
- frontends/election-manager/src/lib/backends/memory_backend.ts
- frontends/election-manager/src/screens/write_ins_screen.test.tsx
- frontends/election-manager/src/screens/write_ins_screen.tsx
- frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
- services/admin/src/server.writeins.test.ts
- services/admin/src/store.test.ts
- services/admin/src/store.ts
Fixes various issues with write-in adjudication, especially #2576. Review by commit.
n/a
Did some manual testing of the fixes in Chrome against the NH Amherst election.
> Misc. WIA fixes

- frontends/election-manager/src/screens/print_test_deck_screen.tsx
The pair of `precinctId` and `ballotStyleId` should be unique per ballot. Closes #1864.
n/a
n/a
> fix(admin): use non-array index key

- frontends/bmd/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap
- frontends/bmd/src/__snapshots__/app_contest_multi_seat.test.tsx.snap
- frontends/bmd/src/__snapshots__/app_contest_single_seat.test.tsx.snap
- frontends/bmd/src/__snapshots__/app_contest_write_in.test.tsx.snap
- frontends/bmd/src/components/__snapshots__/settings_text_size.test.tsx.snap
- frontends/bmd/src/pages/__snapshots__/cast_ballot_page.test.tsx.snap
- frontends/bmd/src/pages/__snapshots__/contest_page.test.tsx.snap
- frontends/bmd/src/pages/__snapshots__/not_found_page.test.tsx.snap
- frontends/bmd/src/pages/__snapshots__/start_page.test.tsx.snap
- frontends/election-manager/src/__snapshots__/app.test.tsx.snap
- frontends/election-manager/src/app.test.tsx
- frontends/election-manager/src/components/text_input.tsx
- frontends/election-manager/src/index.tsx
- frontends/election-manager/src/screens/ballot_list_screen.tsx
- frontends/election-manager/src/screens/logic_and_accuracy_screen.tsx
- frontends/election-manager/src/screens/write_ins_screen.test.tsx
- frontends/election-manager/src/screens/write_ins_screen.tsx
- frontends/election-manager/src/screens/write_ins_transcription_screen.test.tsx
- frontends/election-manager/src/screens/write_ins_transcription_screen.tsx
- frontends/election-manager/src/utils/can_view_and_print_ballots.ts
- frontends/election-manager/src/utils/can_view_and_print_ballots_with_converter.ts
- libs/ui/src/__snapshots__/button.test.tsx.snap
- libs/ui/src/__snapshots__/button_list.test.tsx.snap
- libs/ui/src/__snapshots__/link_button.test.tsx.snap
- libs/ui/src/__snapshots__/number_pad.test.tsx.snap
- libs/ui/src/button.test.tsx
- libs/ui/src/button.tsx
- libs/ui/src/reboot_from_usb_button.test.tsx
- libs/ui/src/reboot_to_bios_button.test.tsx
https://user-images.githubusercontent.com/28444/192018892-5ea6c72d-a0c0-417d-9885-c49798d03725.mov
I've run out of time to complete the tests on this PR. @eventualbuddha graciously offered to help me wrap this up.
> Write-In Transcription UX

- script/setup-dev
I must have merged the last set of changes in an intermediate state. This ensures `TMPFILE` is bound correctly so it can be unpacked correctly.
Before screenshot from @carolinemodic:
Ran locally.
> fix(script): make `setup-dev` work

- integration-testing/election-manager/cypress/e2e/candidate_contest_tallies.cy.ts
- integration-testing/election-manager/cypress/e2e/yes_no_contest_tallies.cy.ts
Accidentally committed these some time back 🙈. Thankfully, they don't seem to have caused problems in CI
> Remove pauses from local debugging that were accidentally committed

- frontends/election-manager/src/__snapshots__/app.test.tsx.snap
- frontends/election-manager/src/app.test.tsx
- frontends/election-manager/src/components/election_manager_tally_report.tsx
- libs/ui/src/contest_tally.tsx
Design pass on @adghayes' PR https://github.com/votingworks/vxsuite/pull/2624
> feat(EM): Design pass on report with manual data

- libs/image-utils/src/count.ts
Doing all the multiplication in the previous version was actually quite slow. To avoid that, we keep track of an offset and increment it by appropriate values for every row and column. Here's some benchmark results:
```
countPixels (new) x 256,478 ops/sec ±0.62% (93 runs sampled)
countPixels (old) x 12,295 ops/sec ±0.45% (91 runs sampled)
Fastest is countPixels (new)
```
<details>
<summary>bench.ts</summary>
```ts
import Benchmark from 'benchmark';
import { countPixels, countPixelsOld, loadImage, toImageData } from './src';
const suite = new Benchmark.Suite();
loadImage(
'/home/brian/code/vxsuite/libs/ballot-interpreter-nh/data/templates/oval_scan.png'
)
.then(toImageData)
.then((ovalScan) => {
// add tests
suite
.add('countPixels (new)', function () {
countPixels(ovalScan);
}) …
```
> perf(image-utils): speed up counting pixels by color

- frontends/election-manager/src/app.test.tsx
- frontends/election-manager/src/screens/ballot_list_screen.tsx
- frontends/election-manager/src/screens/logic_and_accuracy_screen.tsx
https://github.com/votingworks/vxsuite/issues/2675
> update copy for accuvote elections

- libs/types/src/interpretation.ts
- services/scan/src/build_cast_vote_record.test.ts
- services/scan/src/build_cast_vote_record.ts
- services/scan/src/store.ts
Fixed some issues I noticed while reviewing #2677.
n/a
n/a
> minor fixes for `benadida/shrink-cvr-images`

- services/scan/src/central_scanner_app.ts
Per [@jonahkagan's comment](https://github.com/votingworks/vxsuite/pull/2702#pullrequestreview-1146657791).
n/a
n/a
> refactor(scan): use `fs/promises`

- frontends/precinct-scanner/src/screens/poll_worker_screen.tsx
Fixes issue where "Additional Reports" are the opposite of what they should be - Opened where it should be Closed, vice versa.
> fix additional report state

- frontends/election-manager/src/screens/printed_ballots_report_screen.tsx
We default to sorting lists of precincts by name in other places like the Ballots screen, so it makes sense to do so here too.
[Slack context](https://votingworks.slack.com/archives/CJU9MSC6S/p1666288940788689)
|-|-|
| ![image](https://user-images.githubusercontent.com/1938/197027914-e327ce42-35f5-4185-a398-b69549cd1d6c.png) | ![image](https://user-images.githubusercontent.com/1938/197027951-1be67a88-8b06-4b78-97b3-dc944f6d4ee2.png) |
Tested manually with [this election](https://github.com/votingworks/election-definitions/blob/98f120ec13a7fe9da4e7e54d66c63d77186189fc/2022-11-08-ms-general/60/election.json).
> fix(admin): sort Printed Ballots Report by precinct name

- frontends/election-manager/src/components/import_cvrfiles_modal.tsx
Merging two functions in the `ImportCvrFilesModal` component  that have become interchangeable after recent refactoring.
- Relying on existing tests as regression guards
- Also quick check running locally
> [VxAdmin] Merge redundant functions in CVR import modal

- frontends/bmd/src/config/globals.ts
> Update timeouts to VVSG requirements

- README.md
Minor documentation update related to testing that your initial debian quickstart works. 
- [ n/a] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [n/a ] I have added JSDoc comments to any newly introduced exports
- [n/a ] I have added a screenshot and/or video to this PR to demo the change
> remove reference to running services/smartcard 

- libs/utils/src/votecounting.ts
Came across this while looking for code related to calculating undervotes and it looks like it's currently unused, probably left behind after some refactors. Figured we might as well ✂️ 
> [utils] Remove unused getContestTallyMeta function

- script/bootstrap
- script/setup-dev
I went through the initial setup recently while testing the Custom Scanner integration and discovered some issues.
n/a
Ran the changed scripts during setup and got the desired results.
> Initial setup fixes

- .circleci/config.yml
- libs/grout/.eslintignore
- libs/grout/.eslintrc.json
- libs/grout/README.md
- libs/grout/jest.config.js
- libs/grout/package.json
- libs/grout/src/client.ts
- libs/grout/src/debug.ts
- libs/grout/src/grout.test.ts
- libs/grout/src/index.ts
- libs/grout/src/serialization.test.ts
- libs/grout/src/serialization.ts
- libs/grout/src/server.ts
- libs/grout/src/util.test.ts
- libs/grout/src/util.ts
- libs/grout/tsconfig.build.json
- libs/grout/tsconfig.json
- pnpm-lock.yaml
- script/src/validate-monorepo/validation/tsconfig.ts
- vxsuite.code-workspace
Task: #2814 
Adds the beginning of a new library, Grout, that creates type-safe RPC glue code. I recommend reading the [README](https://github.com/votingworks/vxsuite/pull/2851/files#diff-257d9336911e0f18657e5e688a7fdcadc7082d5c34d037815f2506dca3cc2e43) first to see if that makes sense before diving into the code.
N/A
- [ n/a] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage writes, or errors introduced.
- [ n/a] I have added a screenshot and/or video to this PR to demo the change
- [ n/a] I have added the "user_facing_change" label to this PR to automate an announcement in #machine-product-updates
> Introducing Grout

- libs/ballot-interpreter-nh/src/interpret/opencv/page.ts
Some spelling and `await` fixes.
n/a
n/a
> minor fixes

- apps/vx-scan/backend/src/app.ts
- apps/vx-scan/backend/src/store.ts
Follow up to PR feedback from #2862 and #2871.
> refactor(vx-scan): Add a few comments documenting key choices

- libs/grout/src/serialization.ts
Task: #2858 
Inspired by Brian's serialization scheme for Result in the worker pool code.
> refactor(grout): Use a more compact serialization for Result

- libs/grout/src/client.ts
- libs/grout/src/server.ts
Task: #2858 
They don't have to start with T.
> lint(grout): Follow the lint rules about type variable names

- .circleci/config.yml
- libs/auth/.eslintignore
- libs/auth/.eslintrc.json
- libs/auth/jest.config.js
- libs/auth/package.json
- libs/auth/src/index.test.ts
- libs/auth/src/index.ts
- libs/auth/tsconfig.build.json
- libs/auth/tsconfig.json
- pnpm-lock.yaml
- vxsuite.code-workspace
Issue link: https://github.com/votingworks/vxsuite/issues/2906
This PR initializes `libs/auth`, the new library for machine authentication on the backend, by copying scaffolding from other libs. Actual implementation will come in follow-up PRs!
> Initialize libs/auth

- libs/basics/README.md
> fix(basics): Fix typo in README

- services/admin/src/server.writeins.test.ts
> test(admin): Extend timeout for flaky test

- apps/vx-mark/backend/src/index.ts
- apps/vx-mark/frontend/config/env.js
- apps/vx-mark/frontend/vite.config.ts
Realized I forgot to update the env variable loading for the root vxsuite file to account for the extra nested folder
> Fix env loading for vxmark

- libs/ballot-interpreter-nh/src/cli/interpret/index.ts
- libs/image-utils/src/image_data.test.ts
- libs/image-utils/src/image_data.ts
For now this is what we're using on disk with the Custom scanner.
n/a
Automated.
> fix: improve handling of `.pgm` files and PGM data

- libs/types/package.json
- pnpm-lock.yaml
Just doing some housekeeping.
n/a
Automated.
> chore(types): upgrade jest & related libraries

- libs/eslint-plugin-vx/src/rules/gts_identifiers.ts
- libs/eslint-plugin-vx/tests/rules/gts_identifiers.test.ts
These are the point where a name is defined, so we need to check them.
n/a
Automated.
> fix(gts_identifiers): check namespace exports

- libs/test-utils/src/arbitraries.test.ts
- libs/test-utils/src/arbitraries.ts
Facilitates easier `fast-check` tests with these bounded values. I will be using these in the Custom scanner driver branch.
> feat(test-utils): add uint arbitraries

- libs/types/src/ui_theme.ts
- libs/ui/package.json
- libs/ui/src/card.stories.tsx
- libs/ui/src/card.test.tsx
- libs/ui/src/card.tsx
- pnpm-lock.yaml
https://user-images.githubusercontent.com/264902/218809240-56dae693-3421-4016-a5c2-a18dc0220917.mov
- Visual testing within storybook.js
- Added unit tests to verify content and optional footer are rendered as expected.
> [libs/ui] Add theme-aware Card component

- README.md
- ansible/playbooks/setup-node.yaml
https://github.com/votingworks/vxsuite/issues/3025
- Build a clean VM 
- Run: `script/setup-dev`
- Confirm node version by running: `node -v`
This closes #3025
> update node version to 16.19.1

- libs/ballot-interpreter-nh/package.json
- libs/ballot-interpreter-nh/src/interpret/index.test.ts
- libs/ballot-interpreter-nh/src/interpret/interpret_oval_marks.test.ts
- pnpm-lock.yaml
I've been slowly updating all the packages as I've touched them.
n/a
Automated
> chore(scan-nh): update jest

- .circleci/config.yml
[Slack context](https://votingworks.slack.com/archives/CEL6D3GAD/p1678735677680999)
n/a
Automated.
|-|-|
| <img width="1025" alt="image" src="https://user-images.githubusercontent.com/1938/224829681-29d6d8d2-d987-4f8f-ab8f-9f7a6438102e.png"> | <img width="1030" alt="image" src="https://user-images.githubusercontent.com/1938/224829471-a66d3e1b-356d-41b9-ae1a-7f09fbadd80f.png"> |
> ci(pnpm): update path to `pnpm` store

- apps/admin/frontend/src/app.test.tsx
- apps/admin/frontend/src/app_root.test.tsx
- apps/admin/frontend/src/app_write_in_flows.test.tsx
- apps/admin/frontend/src/components/ballot_counts_table.test.tsx
- apps/admin/frontend/src/components/print_all_ballots_button.test.tsx
- apps/admin/frontend/src/components/smartcard_modal/smartcard_modal.test.tsx
- apps/admin/frontend/src/screens/logs_screen.test.tsx
- apps/admin/frontend/src/screens/manual_data_import_index_screen.test.tsx
- apps/admin/frontend/src/screens/manual_data_import_precinct_screen.test.tsx
- apps/admin/frontend/src/screens/print_test_deck_screen.test.tsx
- apps/admin/frontend/src/screens/printed_ballots_report_screen.test.tsx
- apps/admin/frontend/src/screens/settings_screen.test.tsx
- apps/admin/frontend/src/screens/write_ins_screen.test.tsx
- apps/admin/frontend/src/screens/write_ins_transcription_screen.test.tsx
- apps/admin/frontend/test/helpers/api_mock.ts
- apps/admin/frontend/test/render_in_app_context.tsx
- apps/central-scan/frontend/src/app.test.tsx
- apps/central-scan/frontend/src/components/election_configuration.test.tsx
- apps/central-scan/frontend/src/screens/admin_actions_screen.test.tsx
- apps/central-scan/frontend/src/screens/load_election_screen.test.tsx
- apps/central-scan/frontend/test/api.ts
- apps/central-scan/frontend/test/render_in_app_context.tsx
- apps/scan/frontend/src/app.test.tsx
- apps/scan/frontend/src/app_tally_report_paths.test.tsx
- apps/scan/frontend/src/app_unhappy_paths.test.tsx
- apps/scan/frontend/test/helpers/mock_api_client.tsx
- libs/test-utils/src/mock_function.test.ts
- libs/test-utils/src/mock_function.ts
Support expecting repeated calls while still maintaining the requirements that every actual call match up with an expected call.
Also updates some app frontend tests to use this new ability!
N/A
- Added automated tests
> feat(test-utils): Add mockFunction.expectRepeatedCallsWith

- libs/test-utils/src/mock_function.ts
> doc(test-utils): Add expectedRepeatedCallsWith to mockFunction doc

- apps/central-scan/backend/src/types.ts
- apps/central-scan/backend/src/validation.ts
- libs/api/src/services/admin/types.ts
- libs/backend/src/scan/cast_vote_records/canonicalize.ts
- libs/ballot-encoder/src/index.ts
- libs/ballot-interpreter-vx/src/utils/template_map.ts
- libs/types/src/election.ts
The current implementation will be replaced as part of https://github.com/votingworks/roadmap/issues/15.
n/a
n/a
> chore(types): deprecate locales

- pnpm-lock.yaml
I don't know how this got out of sync, but it did.
n/a
Automated.
> build: resync pnpm-lock.yaml

- vxsuite.code-workspace
> chore(workspace): colocate NH interpreters

- libs/ballot-interpreter-nh-next/README.md
[As requested in Slack](https://votingworks.slack.com/archives/CEL6D3GAD/p1681149516453509).
n/a
> docs(scan-nh): basic README info on API & CLI

- docs/writing-style-guide.md
https://github.com/votingworks/vxsuite/pull/3248#discussion_r1162204866
n/a
n/a
> docs: fix grammar error

- apps/central-scan/backend/jest.config.js
Another case like the one Drew fixed in https://github.com/votingworks/vxsuite/pull/3301/commits/b17c117ba4af7b719bf578de4ece1dcf98c69597
> Fix code coverage threshold which seems to have gotten thrown off by a logical merge conflict

- libs/grout/README.md
> doc(grout): Add Date and Buffer to list of supported types

- apps/central-scan/frontend/src/screens/admin_actions_screen.test.tsx
- apps/scan/frontend/src/components/export_backup_modal.test.tsx
- apps/scan/frontend/src/components/export_results_modal.test.tsx
Some minor fixes.
n/a
Automated.
> fix some lint warnings

- apps/central-scan/frontend/src/screens/admin_actions_screen.test.tsx
Minor refactor to make this a bit more idiomatic.
n/a
Automated.
> refactor: use `deferred`

- apps/admin/frontend/jest.config.js
- pnpm-lock.yaml
> Fix broken pnpm-lock.yaml

- apps/mark/frontend/src/pages/admin_screen.tsx
- apps/mark/frontend/src/pages/diagnostics_screen.test.tsx
- apps/mark/frontend/src/pages/diagnostics_screen.tsx
- apps/mark/frontend/src/pages/poll_worker_screen.tsx
- libs/ui/src/button_list.tsx
Tweaking styling on each screen to fix anything that looks broken after enabling the new VVSG-compatible themes and making sure everything looks reasonable at the default text size on the ELO 15".
- Visual testing
- Updating any affected tests as I go
> [VxMark] VVSG Design Fit and Finish - Part 1

- pnpm-workspace.yaml
Removes globs for paths that no longer exist.
n/a
Automated.
> chore: update `pnpm-workspace.yaml`

- frontends/election-manager/src/screens/settings_screen.tsx
USB stick --> USB drive
manually
- [ X ] I have added a screenshot and/or video to this PR to demo the change
> fix(election-manager): usb drive, not usb stick.

- frontends/bmd/src/pages/poll_worker_screen.tsx
- frontends/bmd/src/utils/ScreenReader/aria_screen_reader.ts
Also turn off tts for poll worker screen, it's more confusing than helpful.
> fix(tts): stop utterance repeating, it's unreliable in its effects. 

- apps/admin/backend/jest.config.js
Another case like the ones fixed by https://github.com/votingworks/vxsuite/pull/3326 and https://github.com/votingworks/vxsuite/commit/b17c117ba4af7b719bf578de4ece1dcf98c69597
> Fix code coverage threshold thrown off by a logical merge conflict

- .circleci/config.yml
- apps/admin/integration-testing/package.json
Brings `admin` in line with `mark` and `central-scan`.
n/a
Automated.
> fix(admin): correct name of integration-testing package

- frontends/election-manager/src/screens/tally_screen.tsx
Another majestic PR that took serious PhD thinking to fix my serious PhD bug.
> fix(election-manager): fixed table column alignment for external tallies

- libs/ui/src/error_boundary.tsx
> docs(ui): fix typo

- apps/admin/frontend/src/components/confirm_removing_file_modal.tsx
> refactor(admin): remove use of `fullElectionManualTally`

- apps/admin/frontend/src/components/smartcard_modal/program_election_card_view.tsx
Applying VVSG design updates to the `ProgramElectionCard View` in VxAdmin.
- N/A
> [VxAdmin] VVSG Design Updates: ProgramElectionCardView

- apps/admin/frontend/src/components/smartcard_modal/program_system_administrator_card_view.tsx
- apps/admin/frontend/src/components/smartcard_modal/smartcard_modal.test.tsx
Applying VVSG design updates to the `ProgramSystemAdministratorCardView` in VxAdmin.
- N/A
> [VxAdmin] VVSG Design Updates: ProgramSysAdminCardView

- apps/admin/backend/src/app.ts
Fixes #3605 
When trying to zip a large election definition file into a ballot package, the zip-stream library was hanging. My hypothesis is that this was due to the stream trying to buffer all the data, since we did not pipe it to any sink before adding the file contents to the stream.
To fix this, we pipe to an output file write stream before adding any files to the stream.
I also added some error handling just in case.
N/A
Manually tested with the all bubble ballots election definition.
> admin: Fix buffer overflow when zipping large ballot packages

- apps/admin/frontend/src/screens/logic_and_accuracy_screen.tsx
Applying VVSG design updates to the `LogicAndAccuracyScreen`.
- Replacing typography components with theme-aware versions
- Fixing the page flow issues caused by enabling the new theme
- Using `<ol>|<li>` instead of the hardcoded list numbering
- No functional changes - updated changed snapshots
> [VxAdmin] VVSG Design Updates: L&A Screen

- apps/admin/frontend/src/screens/reports_screen.tsx
Applying VVSG design updates to the `ReportsScreen`:
- Replacing typography components with theme-aware versions
- Visual check
> [VxAdmin] VVSG Design Updates: Reports Screen

- apps/admin/backend/perf/tally_cvrs.test.ts
- apps/admin/backend/src/app.ts
- apps/admin/backend/src/store.ts
CVR endpoint on backend was really inefficient, weren't optimizing it since it's going to be removed soon anyway.
> Stop Silly Parsing

- libs/utils/src/votes.ts
Addresses extreme slowness in frontend rendering found during m17a QA.
> make vote conversion operation faster for legacy tally method

- libs/utils/src/environment_variable.ts
Quick fix of a copy-paste error! Have already cherry-picked this onto [m17a-release-branch](https://github.com/votingworks/vxsuite/tree/m17a-release-branch).
> Fix copy-paste error

- apps/admin/frontend/src/screens/settings_screen.tsx
Applying VVSG design updates to the `SettingsScreen` in VxAdmin:
- Replace typography components with theme-aware versions
- Remove deprecated `Prose` component
- Visual
> [VxAdmin] VVSG Design Updates: SettingsScreen

- apps/admin/frontend/src/screens/tally_screen.tsx
@kofi-q I'm going through VxAdmin and making small fixes for polish / scaling, this is the first of a few PRs.
This change leaves appearance the same, visually verified.
> change DOM nesting that is giving warnings

- libs/utils/src/environment_variable.ts
Missed that the Live Check feature flag was ignored in prod. Updating for CISA images accordingly!
> Allow Live Check in prod

- apps/scan/backend/src/scanners/custom/app_scan.test.ts
- apps/scan/backend/src/scanners/custom/state_machine.ts
https://github.com/votingworks/vxsuite/issues/3140
In this weird case we sometimes get an unreadable ballot error on a quick second feed of a ballot, there isn't a great way to prevent this but retrying scanning will succeed. This change makes it so that we always just try a second time when we see interpretation throw an error. Note that this only happens on unreadable not when interpretation returns a rejected ballot for an expected reason like the wrong precinct on the ballot. 
I also have been noticing this existing retry logic that was taken from plustek never seems to be used in the custom state machine. I removed it to simplify things and haven't noticed any change in behavior but will do more edge case testing with @mattroe to verify. …
> Always retry scanning on a intepretration fail once

- libs/ballot-interpreter-nh/ts/src/cli.ts
They were changed a while back but not updated here, presumably because we were still working with older backups with the old names.
n/a
Tested manually with a recent backup.
> fix(scan-nh): correct the image column names

- apps/admin/frontend/src/components/navigation_screen.tsx
- apps/admin/frontend/src/screens/election_manager_system_screen.tsx
- apps/central-scan/frontend/src/app_root.tsx
- apps/central-scan/frontend/src/screens/admin_actions_screen.tsx
- apps/central-scan/frontend/src/screens/unconfigured_election_screen_wrapper.tsx
- libs/auth/jest.config.js
- libs/auth/src/artifact_authenticator.ts
better button placement + allow signing of CVRs by admins
> fix comboplatter

- apps/central-scan/frontend/src/app.test.tsx
> Fix flaky apps/central-scan test

- apps/design/backend/src/all_bubble_ballots.ts
- apps/design/backend/src/ballot_interpretation.test.ts
- apps/design/frontend/src/ballots_screen.tsx
- apps/design/frontend/src/contests_screen.tsx
- apps/design/frontend/src/radio.tsx
- apps/design/shared/jest.config.js
- apps/design/shared/src/layout.ts
Adds a ballot layout density option to VxDesign. There are three density levels to choose from. Increasing the density changes the font size and spacing to help fit more ballot content on each page, while still maintaining bubbles located on grid intersections.
https://github.com/votingworks/vxsuite/assets/530106/d3f4820d-cefc-47b2-9c1b-93a6300a0703
- Visual inspection of ballots
- Updated automated testing of interpretation
> VxDesign: Ballot layout density option

- apps/design/frontend/src/elections_screen.tsx
- apps/design/frontend/src/layout.tsx
- apps/design/shared/src/layout.ts
Polishing rough edges found during QA.
> VxDesign: Polish

- apps/scan/backend/src/app_results.test.ts
This was broken on `main` and tests were failing. Probably resulted from a merge conflict or something.
> Fix import of SheetInterpretation type

- libs/types/src/byte.ts
The previous implementation unnecessarily created multiple arrays, iterators, etc. This version is simpler and likely more performant.
Somewhat silly to [microbenchmark](https://jsperf.app/qenina) this, but it's a stark difference:
> refactor(types): simplify `isByte`

- apps/admin/backend/src/app.ts
As soon as @adghayes got us up to 100% code coverage in `apps/admin/backend` (https://github.com/votingworks/vxsuite/pull/3886), I brought us back down 😅 with a logical merge conflict that is now causing CI to fail. This PR brings us back up to 100%!
> Get back up to 100% code coverage (so CI passes)

- .circleci/config.yml
- libs/monorepo-utils/src/circleci.ts
Mitigation for https://github.com/CircleCI-Public/browser-tools-orb/issues/90
> Fix CircleCI Integration Tests

- libs/ui/package.json
- libs/ui/src/icons.tsx
- libs/ui/src/index.ts
- libs/ui/src/search_select.test.tsx
- libs/ui/src/search_select.tsx
- libs/ui/src/search_select_multi.stories.tsx
- libs/ui/src/search_select_single.stories.tsx
- pnpm-lock.yaml
I'm working toward building a report builder, like roughly seen in this video:
[report-builder.webm](https://github.com/votingworks/vxsuite/assets/37960853/4458944f-89b2-4e40-aeca-2755ad1dad3b)
Due to our interpretation of VVSG requirements around reporting capabilities (e.g. 1.1.9-D, "The voting system must be capable of generating reports that consolidate vote data from selected precincts."), we think that we need to enable reports that might combine multiple, but not all, precincts or ballot styles. For a user to select multiple, but not all, of items in a list, I thought a multi-select was the best route. 
Using `react-select`.
[react-select.webm](https://github.com/votingworks/vxsuite/assets/37960853/589d8458-e168-47cc-a71e-7b5be7af92c8)
I added a storybook story if you'd like to …
> Select & Multi-Select Component

- apps/mark-scan/frontend/src/pages/validate_ballot_page.test.tsx
> apps/mark-scan: Resolve logical merge conflict in test

- frontends/election-manager/src/app_root.tsx
- frontends/election-manager/src/hooks/use_election_manager_store.ts
Addresses VxAdmin slowness experienced in Warren County on the `m16` branch by avoiding spurious re-renders and effects.
> m16 VxAdmin: stop recomputing the full election tally so much

- .circleci/config.yml
- libs/monorepo-utils/src/circleci.ts
Follow-up changes from https://github.com/votingworks/vxsuite-build-system/pull/65 and https://github.com/votingworks/vxsuite-build-system/pull/66.
n/a
- Automated testing
> ci: update docker images

- apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx
Fixes conflict from #3944 and #3931
> Fix logical merge conflict (renamed fixture)

- apps/admin/frontend/src/components/smartcard_modal/card_details_view.tsx
- apps/admin/frontend/src/screens/definition_screen.tsx
Some DOM nesting warnings appear in the console and in tests, this fixes them.
> fix dom nesting warnings in VxAdmin

- libs/ui/src/reports/ballot_count_report.test.tsx
- libs/ui/src/reports/ballot_count_report.tsx
Just adds a border to a certain cell in the ballot count report table.
> Ballot Count Report Styling Tweak Follow-Up

- libs/hmpb/render-backend/package.json
- libs/hmpb/render-backend/src/render_ballot.tsx
- pnpm-lock.yaml
See https://github.com/jindw/xmldom/issues/150.
n/a
Automated.
> fix(deps): upgrade `xmldom`

- libs/grout/package.json
- libs/grout/src/index.ts
- libs/grout/src/serialization.test.ts
- libs/grout/src/serialization.ts
- pnpm-lock.yaml
> feat(grout): allow serialization of luxon `DateTime`

- libs/@types/kiosk-browser/kiosk-browser.d.ts
Updates the type definitions to reflect https://github.com/votingworks/kiosk-browser/pull/151.
n/a
Tested in RAVE.
> feat(kiosk-browser): add `PrintOptions::raw` option

- .circleci/config.yml
- libs/monorepo-utils/src/circleci.ts
- libs/ui/i18next-parser.config.ts
- libs/ui/package.json
- libs/ui/src/ui_strings/app_strings.tsx
- libs/ui/tsconfig.json
- pnpm-lock.yaml
Adding a build step for extracting a catalog of UI Strings for translation, using `i18next-parser`.
- Copied and modified the starter config from https://github.com/i18next/i18next-parser#options
- Currently only extracting app strings, since election strings/translations will be populated based on user-provided election config input.
- Had to modify a few `appStrings` definitions to use dot-path keys instead of relying on the `uiStringSubKey` prop, since there was no out-of-the-box way to configure i18next-parser to handle the latter pattern.
- Added a stub export step (for only `main`-branch builds) to the circleci config - will fill that in once we decide on a shared …
> [libs/ui] Add UI String catalog build/extract steps

- apps/mark-scan/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap
- apps/mark-scan/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap
- apps/mark-scan/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap
- apps/mark-scan/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap
- apps/mark-scan/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap
- apps/mark-scan/frontend/src/pages/__snapshots__/not_found_page.test.tsx.snap
- apps/mark/frontend/src/__snapshots__/app_contest_candidate_no_party.test.tsx.snap
- apps/mark/frontend/src/__snapshots__/app_contest_multi_seat.test.tsx.snap
- apps/mark/frontend/src/__snapshots__/app_contest_single_seat.test.tsx.snap
- apps/mark/frontend/src/__snapshots__/app_contest_write_in.test.tsx.snap
- apps/mark/frontend/src/pages/__snapshots__/contest_page.test.tsx.snap
- apps/mark/frontend/src/pages/__snapshots__/not_found_page.test.tsx.snap
- libs/mark-flow-ui/src/components/__snapshots__/contest.test.tsx.snap
- libs/mark-flow-ui/src/components/__snapshots__/yes_no_contest.test.tsx.snap
- libs/ui/src/button.test.tsx
- libs/ui/src/button.tsx
- libs/ui/src/buttons.stories.tsx
- libs/ui/src/icons.tsx
- libs/ui/src/radio_group/radio_button.tsx
- libs/ui/src/themes/make_theme.ts
Adapts the Button component to support the desktop theme, while maintaining backwards compatibility for the existing touchscreen themes.
I recommend poking around in Storybook, but here's a sampling
https://github.com/votingworks/vxsuite/assets/530106/3036a9f7-db77-4b77-b0ca-084ba5bc0708
Touch screen themes
https://github.com/votingworks/vxsuite/assets/530106/e93948b5-e6e5-4412-9587-4a5c39668079
- Updated existing automated tests
- Added some new unit tests
- Visual inspection in Storybook
> Desktop theme Button

- apps/admin/frontend/src/components/reporting/filter_editor.tsx
- libs/ui/jest.config.js
- libs/ui/src/search_select.test.tsx
- libs/ui/src/search_select.tsx
- libs/ui/src/search_select_multi.stories.tsx
- libs/ui/src/search_select_single.stories.tsx
- libs/ui/src/select.tsx
Updates the SearchSelect component to work with the desktop theme. Also adds a disabled state, since we'll need that in forms in VxDesign.
Single
https://github.com/votingworks/vxsuite/assets/530106/c1fe2701-3abb-4008-871f-0c18d761d87b
Multi
https://github.com/votingworks/vxsuite/assets/530106/06a7196b-4159-4905-b2ec-d9299d16ef77
Only styling changed, so existing tests mostly work. Added a few unit tests for disabled state and desktop theme for coverage.
> Desktop SearchSelect

- apps/central-scan/backend/schema.sql
- apps/design/backend/package.json
- apps/design/backend/schema.sql
- apps/design/backend/src/language_and_audio/google_cloud_config.ts
- apps/design/backend/src/language_and_audio/speech_synthesizer.test.ts
- apps/design/backend/src/language_and_audio/speech_synthesizer.ts
- apps/design/backend/src/language_and_audio/translator.test.ts
- apps/design/backend/src/language_and_audio/translator.ts
- apps/design/backend/src/store.test.ts
- apps/design/backend/src/store.ts
- apps/design/backend/test/helpers.ts
- apps/scan/backend/schema.sql
- libs/auth/src/cast_vote_record_hashes.ts
- libs/backend/src/cast_vote_records/referenced_files.ts
- libs/basics/src/assert.ts
- pnpm-lock.yaml
This PR adds Google Cloud Translation and Text-to-Speech API integrations to VxDesign, in preparation for language and audio file generation. I've gone ahead and added caching to minimize API calls and, by extension, costs.
I've also done some thinking around Google Cloud auth, for both deployed and local environments. I'll add some notes to the VxDesign README in a follow-up PR, but the tldr is that I'm planning for us to use a service account in deployed environments and service account impersonation in local environments (https://cloud.google.com/iam/docs/service-account-overview + https://cloud.google.com/iam/docs/service-account-impersonation), both of which I've successfully set up.
Through this code:
```ts
const store = Store.memoryStore();
const …
```
> Add Google Cloud Translation and Text-to-Speech API integrations to VxDesign

- docs/development/best_practices/rust.md
[Rendered version](https://github.com/votingworks/vxsuite/blob/brian/docs/rust-dev/docs/development/best_practices/rust.md)
This hopefully gives VxSuite contributors some grounding to better understand and contribute to the Rust parts of the codebase.
> docs: add more info on Rust concepts & tooling

- apps/admin/frontend/package.json
- apps/admin/frontend/src/screens/logs_screen.tsx
- apps/central-scan/frontend/package.json
- apps/central-scan/frontend/src/screens/admin_actions_screen.tsx
- apps/scan/frontend/package.json
- apps/scan/frontend/src/app_root.tsx
- apps/scan/frontend/src/screens/election_manager_screen.tsx
- pnpm-lock.yaml
See https://github.com/votingworks/vxsuite/pull/4221#issuecomment-1821548701.
> remove hard backend dependency from frontends

- .gitignore
- apps/central-scan/frontend/.gitignore
- apps/mark-scan/frontend/.gitignore
- apps/mark/frontend/.gitignore
- script/src/prod-build/build.ts
- script/src/run-dev/index.ts
- vxsuite.code-workspace
A few things left over from `python` that can now be removed.
> Remove Python Vestiges

- apps/scan/frontend/src/components/full_screen_prompt_layout.tsx
- apps/scan/frontend/src/preview_dashboard.tsx
- libs/ui/src/themes/make_theme.ts
Switches VxMark and VxScan to brand purple as their primary color in medium contrast mode. Also tweaks some other colors that weren't quite meeting contrast requirements.
https://github.com/votingworks/vxsuite/assets/530106/c9d0d56a-790e-49d4-82e0-37cf5d8b2202
> Switch precinct system to purple primary color

- apps/admin/frontend/src/app.test.tsx
- apps/admin/frontend/src/components/remove_election_modal.tsx
- apps/admin/frontend/src/components/reporting/shared.tsx
- apps/admin/frontend/src/screens/manual_data_entry_screen.tsx
- apps/admin/frontend/src/screens/manual_data_summary_screen.test.tsx
- apps/admin/frontend/src/screens/manual_data_summary_screen.tsx
- apps/admin/frontend/src/screens/reporting/reports_screen.tsx
- apps/admin/frontend/src/screens/tally_screen.tsx
- apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx
- apps/central-scan/frontend/src/navigation_screen.tsx
- apps/central-scan/frontend/src/screens/ballot_eject_screen.test.tsx
- apps/central-scan/frontend/src/screens/ballot_eject_screen.tsx
- libs/ui/src/card.tsx
- libs/ui/src/left_nav.tsx
- libs/ui/src/main.tsx
- libs/ui/src/themes/make_theme.test.ts
- libs/ui/src/themes/make_theme.ts
In order to try to make VxAdmin and VxCentralScan as useable as possible on our laptop screens, increases the base font size. Then, makes a few small tweaks to fit everything nicely in the screen.
VxAdmin
https://github.com/votingworks/vxsuite/assets/530106/0e136284-13b7-4079-b851-d38f175294a7
VxCentralScan
https://github.com/votingworks/vxsuite/assets/530106/fa73d99d-a25f-4ff5-a92b-d3a8bf7ac932
Manual testing and updating automated tests
> Increase central system font size

- apps/admin/backend/schema.sql
- apps/admin/backend/src/app.ts
- apps/admin/backend/src/cast_vote_records.ts
- apps/admin/backend/src/store.ts
- apps/admin/backend/src/tabulation/card_counts.test.ts
- apps/admin/backend/src/tabulation/card_counts.ts
- apps/admin/backend/src/tabulation/manual_results.test.ts
- apps/admin/backend/src/tabulation/manual_results.ts
- apps/admin/backend/src/tabulation/utils.test.ts
- apps/admin/backend/src/tabulation/utils.ts
- apps/admin/backend/src/types.ts
- apps/admin/backend/src/util/cast_vote_records.test.ts
- apps/admin/backend/src/util/cast_vote_records.ts
- apps/admin/backend/test/mock_cvr_file.ts
- apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx
- apps/admin/frontend/src/components/reporting/filter_editor.test.tsx
- apps/admin/frontend/src/components/reporting/filter_editor.tsx
- apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.tsx
- apps/admin/frontend/src/utils/reporting.test.ts
- apps/admin/frontend/src/utils/reporting.ts
- libs/types/src/admin/index.ts
- libs/types/src/admin/reporting.ts
- libs/types/src/index.ts
- libs/ui/src/reports/ballot_count_report.tsx
- libs/ui/src/reports/custom_filter_summary.test.tsx
- libs/ui/src/reports/custom_filter_summary.tsx
_review by commit_
Closes #4070.
https://github.com/votingworks/vxsuite/assets/37960853/9c91b43e-d2d2-4a17-bebe-61390df5b5ef
Automated testing, plus a manual test from end to end with a custom data set.
> Adjudication Status Ballot Reports

- apps/admin/backend/src/adjudication.test.ts
- apps/admin/backend/src/adjudication.ts
- apps/admin/backend/src/store.ts
- apps/admin/backend/src/types.ts
- apps/admin/frontend/src/screens/write_ins_adjudication_screen.test.tsx
- apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx
cherry-picking #4313 into the release branch
> v3.1.0 - Unselect Write-Ins in Adjudication

- libs/types/src/election.ts
These appear to be unused since #3474.
n/a
> chore(types): remove unused exports

- apps/scan/backend/src/scanners/custom/state_machine.ts
I added the `trimBlackFromTopAndBottomOfImage` function when I first added the Custom state machine because the images we got back from the scanner had somewhat tall black header and footer portions that interfered with the interpreter as it was then. Maybe. It's not entirely clear because _this function doesn't seem to do what it says it does_. It's looking for rows at the top and bottom of the image that it can trim off, but in practice it always seems to trim zero rows on both ends, effectively just copying the images. We can tell it's not trimming because the `imageHeight` calculation of the trimmed image is wrong: it's using `image.imageBuffer.length / offsetPerRow`, but the numerator should be the _new_ length, not the _old_ length. If it actually were cropping any rows then the …
> perf(scan): stop copying scanned images in memory

- libs/custom-scanner/src/cli/demo/index.ts
This CLI could use a more major improvement if hardware is going to use it a lot but this just adds double sheet detection ability to autoscan and improves error handling (since that causes more frequent errors when you trigger the detection). Changes double-sheet to default to on in level 1 like the app does, but you can now set it with double-sheet 0, double-sheet 2, etc. to set it to level 1-4 or off (0). Then scan or autoscan will respect whatever you set it to. 
cc @pieguyatx
> Add double sheet detection for autoscan in custom CLI

- apps/admin/backend/src/app.ts
- apps/admin/backend/src/exports/csv_ballot_count_report.test.ts
- apps/admin/backend/src/exports/csv_ballot_count_report.ts
- apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.test.tsx
- apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx
- apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.test.tsx
- apps/admin/frontend/src/components/reporting/export_ballot_count_report_csv_button.tsx
- apps/admin/frontend/src/components/reporting/group_by_editor.test.tsx
- apps/admin/frontend/src/components/reporting/group_by_editor.tsx
- apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.test.tsx
- apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.tsx
- apps/admin/frontend/src/screens/reporting/precinct_ballot_count_report_screen.tsx
- apps/admin/frontend/src/screens/reporting/tally_report_builder.tsx
- apps/admin/frontend/src/screens/reporting/voting_method_ballot_count_report_screen.tsx
- apps/admin/frontend/test/helpers/mock_api_client.ts
- libs/fixtures/src/data/electionFamousNames2021/index.ts
- libs/ui/src/reports/ballot_count_report.stories.tsx
- libs/ui/src/reports/ballot_count_report.test.tsx
- libs/ui/src/reports/ballot_count_report.tsx
- libs/utils/src/elections.test.ts
- libs/utils/src/elections.ts
_review by commit_
Closes #4274.
https://github.com/votingworks/vxsuite/assets/37960853/85e66bcf-1ac3-48ef-a458-6e7613f6eee2
The usual.
> Ballot Count Sheet Counts CSV + Frontend

- apps/admin/backend/schema.sql
- apps/admin/backend/src/app.ts
- apps/admin/backend/src/store.ts
> delete election on unconfigure rather than simply marking as 'deleted' (#4385)

- libs/types/src/cdf/ballot-definition/__snapshots__/convert.test.ts.snap
These snapshots were removed in `main` but still exist on the release branch, so they need to be updated.
> v3.1: Fix cdf conversion snapshots

- Cargo.lock
- apps/mark-scan/accessible-controller/Cargo.toml
- apps/mark-scan/accessible-controller/src/controllerd.rs
Here are a variety of changes that you might want to incorporate. I didn't break them down by commit, but will be adding explanatory comments.
> various improvements

- apps/admin/backend/src/app.err_cdf_export.test.ts
Fixes `main` after a logical merge conflict.
n/a
> test(admin): reference new name for fixture

- apps/admin/frontend/src/screens/reporting/reports_screen.test.tsx
- apps/admin/frontend/src/screens/reporting/reports_screen.tsx
> hide WIA report when no write-in contests (#4424)

- apps/scan/backend/src/scanners/custom/state_machine.ts
Explanation in the code comment
Tested manually (and verified that automated tests still pass)
> Minor state machine tweak

- apps/central-scan/backend/src/loop_scanner.ts
Just a tiny tweak.
n/a
- Existing automated tests.
> refactor(scan): use `mapSheet`

- apps/scan/backend/src/scanners/custom/app_scan.test.ts
- apps/scan/backend/src/scanners/custom/app_scan_double_sheets.test.ts
- apps/scan/backend/src/scanners/custom/app_scan_power_off.test.ts
Some small tweaks based on the CircleCI flaky tests list.
> Attempt to fix some flaky apps/scan/backend tests

- apps/design/backend/package.json
- apps/design/backend/src/store.ts
- apps/design/frontend/jest.config.js
- apps/design/frontend/src/contests_screen.tsx
- apps/design/frontend/src/nav_screen.tsx
An assortment of small bugfixes. Details in commits.
> VxDesign cleanup

- libs/backend/src/system_call/get_battery_info.test.ts
- libs/backend/src/system_call/get_battery_info.ts
Rather than using `readFile` and `split('\n')`, use `createReadStream` and `lines`.
n/a
Updated tests.
> refactor(backend): `iter`-ify `parseBatteryInfo`

- apps/mark-scan/frontend/src/pages/ballot_successfully_cast_page.tsx
Vertically stacks elements in https://github.com/votingworks/vxsuite/pull/4541
Accidentally hit merge before pushing this commit.
See https://github.com/votingworks/vxsuite/pull/4541
See https://github.com/votingworks/vxsuite/pull/4541
> vertically stack elements

- libs/mark-flow-ui/src/components/candidate_contest.test.tsx
- libs/mark-flow-ui/src/components/candidate_contest.tsx
Add a "votes remaining in this contest" audio readout after a voter selects or deselects a candidate. This provides audio-only votes feature parity with the corresponding "votes remaining" status  rendered at the top of the contest page.
https://github.com/votingworks/vxsuite/assets/264902/3f5cc03d-93ef-4abe-9888-87d6cc2bd1ac
- Additional test assertions for the new behaviour
- Manual run with test audio data
> [i18n/audio] Improve audio feedback for candidate selection/deselection.

- apps/admin/frontend/src/index.tsx
- apps/mark-scan/frontend/src/app.tsx
- apps/mark/frontend/src/app.tsx
- apps/scan/frontend/src/scan_app_base.tsx
- libs/mark-flow-ui/.storybook/preview.tsx
- libs/mark-flow-ui/src/pages/__snapshots__/print_page.test.tsx.snap
- libs/printing/src/render.tsx
- libs/types/src/ui_theme.test.tsx
- libs/types/src/ui_theme.ts
- libs/ui/.storybook/preview.tsx
- libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap
- libs/ui/src/__snapshots__/button_bar.test.tsx.snap
- libs/ui/src/__snapshots__/horizontal_rule.test.tsx.snap
- libs/ui/src/__snapshots__/input_group.test.tsx.snap
- libs/ui/src/__snapshots__/loading.test.tsx.snap
- libs/ui/src/__snapshots__/modal.test.tsx.snap
- libs/ui/src/__snapshots__/progress_bar.test.tsx.snap
- libs/ui/src/__snapshots__/progress_ellipsis.test.tsx.snap
- libs/ui/src/__snapshots__/prose.test.tsx.snap
- libs/ui/src/__snapshots__/qrcode.test.tsx.snap
- libs/ui/src/__snapshots__/setup_card_reader_page.test.tsx.snap
- libs/ui/src/__snapshots__/test_mode.test.tsx.snap
- libs/ui/src/__snapshots__/text.test.tsx.snap
- libs/ui/src/app_base.test.tsx
- libs/ui/src/app_base.tsx
- libs/ui/src/global_styles.tsx
Assorted clean up for GlobalStyles. See commits for details
N/A
Mostly relied on searching for uses of code before removing and inspecting them to ensure they were safe to remove.
> Clean up GlobalStyles

- libs/hmpb/layout/package.json
- libs/hmpb/layout/src/document_svg.tsx
- libs/hmpb/layout/src/layout.test.ts
- libs/hmpb/layout/src/layout.ts
- pnpm-lock.yaml
> Basic rich text support for ballot measures

- apps/admin/frontend/package.json
- pnpm-lock.yaml
> Fix merge conflict in pnpm-lock.yaml

- libs/ballot-encoder/src/README.md
Make sure the documentation matches the code. It was mostly up to date already, I just clarified a few bits.
> Clean up small inconsistencies in ballot-encoder docs

- apps/central-scan/backend/src/store.test.ts
- apps/central-scan/backend/src/store.ts
- apps/central-scan/frontend/src/screens/ballot_eject_screen.tsx
Some tweaks to blank ballot handling, follow up to #3407.
> fix: VxCentralScan Blank Ballot Detection

- Cargo.lock
- Cargo.toml
- apps/mark-scan/accessible-controller/Cargo.toml
- apps/mark-scan/accessible-controller/src/commands.rs
- apps/mark-scan/accessible-controller/src/controllerd.rs
- apps/mark-scan/accessible-controller/src/device.rs
- apps/mark-scan/accessible-controller/src/port.rs
- Improves `controllerd`'s testability by introducing a `VirtualKeyboard` trait.
- Separates the code into modules.
- Various minor improvements.
n/a
As I can't actually test this on the real hardware easily, I'd like @kshen0 to give this the green light.
> [`controllerd`] more testable and idiomatic

- libs/monorepo-utils/src/cargo.ts
No strong reason for this, just noticed while I was creating https://github.com/votingworks/vxsuite/pull/4674.
> refactor: use `lines` helper and async streaming

- libs/hmpb/layout/src/layout.ts
Minor changes for things I noticed in #4703.
> Minor PR tweaks

- apps/admin/frontend/package.json
- apps/admin/frontend/src/app.test.tsx
- apps/admin/frontend/tsconfig.json
- apps/central-scan/frontend/package.json
- apps/central-scan/frontend/tsconfig.json
- apps/mark-scan/frontend/package.json
- apps/mark-scan/frontend/tsconfig.json
- apps/mark/frontend/package.json
- apps/mark/frontend/tsconfig.json
- apps/scan/backend/package.json
- apps/scan/backend/tsconfig.build.json
- apps/scan/backend/tsconfig.json
- apps/scan/frontend/tsconfig.json
- libs/mark-flow-ui/package.json
- libs/mark-flow-ui/tsconfig.build.json
- libs/mark-flow-ui/tsconfig.json
- pnpm-lock.yaml
Some cleanup I did this morning while waiting for the power to come back on.
> chore: remove `@votingworks/ballot-encoder` where it's unused

- libs/pdi-scanner/src/main.rs
- libs/pdi-scanner/ts/src/scanner_client.ts
Since errors can be sent in response to commands or as events, it makes life easier if we can differentiate them. While I was at it, I also changed the command JSON format to clarify that it is a command. This makes logs of scanner command/response cycles much clearer.
```bash
$ DEBUG=pdi-scanner ./ts/src/demo 
pdi-scanner sent: { command: 'connect' } +0ms
pdi-scanner received: { response: 'ok' } +203ms
pdi-scanner sent: { command: 'getScannerStatus' } +1ms
pdi-scanner received: { response: 'scannerStatus', status: { rearLeftSensorCovered: false, rearRightSensorCovered: false, branderPositionSensorCovered: false, hiSpeedMode: true, downloadNeeded: false, scannerEnabled: false, frontLeftSensorCovered: false, frontM1SensorCovered: false, frontM2SensorCovered: false, frontM3SensorCovered: …
```
> pdi-scanner: Differentiate command/response/event JSON objects

- libs/pdi-scanner/src/main.rs
- libs/pdi-scanner/ts/src/scanner_client.ts
The Rust code already queues commands and processes them one a time, so we can adapt the TS client to match this behavior and receive responses in the order that requests were sent. That way, the consuming code in the state machine doesn't need to worry about waiting for previous requests to complete before sending a new request (which can be an issue when transitioning from a state that polls scanner status to another state that sends an accept command or the like).
N/A
Manual testing with the state machine for now
> pdi-scanner: Support command queueing in TS client

- libs/pdi-scanner/src/rust/client.rs
Only keep the commands that we think are actually necessary. I'd like to merge this for now and try it out as I continue development, knowing we can always undo it if new information arises.
> pdi-scanner: Clean up initial commands after connect

- libs/converter-nh-accuvote/package.json
- libs/hmpb/render-backend/package.json
- pnpm-lock.yaml
https://github.com/advisories/GHSA-crh6-fp67-6883
> security(xmldom): update to v0.8.4

- libs/pdi-scanner/src/ts/demo.ts
Updates the TS demo script to continuously scan and accept ballots.
Manual test
> libs/pdi-scanner: Improve demo

- apps/design/backend/src/language_and_audio/translation_overrides.ts
Adds Spanish translation overrides.
> add Spanish translation overrides

- vxsuite.code-workspace
https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml
> chore: add recommendation for "Even Better TOML" extension

- libs/ui/src/ui_strings/language_context.tsx
Instead of relying on a single global i18next instance and updating all of its resources every render, create a new instance every render. This is just a little cleanup to make this flow less confusing. Now each render more clearly loads the latest translations from the store and creates a language context to be used by the React components.
N/A
Relying on existing automated tests
> Create new i18next instance for every backend render

- libs/hmpb/src/renderer.tsx
When inserting HTML content into the DOM, we want to wait for it to finish rendering before doing anything with it (e.g. taking measurements).
I found the `MutationObserver` API, which registers an observer to call a callback when various types of changes happen to a DOM node. Specifically, the one that is useful to us is a change in the node's children.
N/A
Manually tested that the layout bugs that were previously happening (due to measuring before content was finished rendering) are solved by this.
> libs/hmpb: Wait for HTML to load during rendering

- libs/ballot-interpreter/src/hmpb-rust/scoring.rs
At some point after Rust 1.76 the dead code linting became more aggressive, which led to the fields on `ScoredBubbleMark` that we weren't serializing being marked as unused. I removed the fields and, in the process, cleaned up some of the code that finds the best match. Rather than having three variables which are all either `None`/some sentinel value OR `Some`/a real value, we now have one variable that is either `None` when no match has been found or `Some` if one has.
n/a
> refactor(ballot-interpreter): clean up some of the scoring code

- libs/ballot-interpreter/README.md
I'm sure I missed something. Please comment if I did or if something isn't clear!
> docs(ballot-interpreter): add a high-level overview

- libs/custom-paper-handler/src/driver/scanner_status.ts
https://github.com/votingworks/vxsuite/issues/4925
Allows notched paper to be loaded in VxMarkScan.
N/A
* Tested manually
> remove check for inner right sensor

- apps/mark-scan/fai-100-controller/src/fai_100_controllerd.rs
Fixes a logical error in the FAI-100 docs and adds more explanation.
N/A
N/A comment change only
> clarify comment

- libs/ballot-interpreter/README.md
Per https://github.com/votingworks/vxsuite/pull/5021#discussion_r1672576332.
> docs(ballot-interpreter): clarify timing mark border matching

- libs/cvr-fixture-generator/src/cli/generate/main.ts
Using `Promise.all` spawns essentially all of the fixture generator loop iterations at once, resulting in rather large memory usage. This can be seen in the [RAM usage stats in CircleCI for the `test-libs-cvr-fixture-generator` job](https://app.circleci.com/insights/github/votingworks/vxsuite/workflows/test/jobs?branch=b1d8acd4-8701-4c76-8a87-7ff2320aa95f) since I changed from the loop to `Promise.all` around August 2nd.
**RAM usage for this test job recently:**
**RAM usage for this test job from this PR:**
Automated.
> fix(cvr-fixture-generator): reduce memory usage

- libs/converter-nh-accuvote/src/convert/accuvote.test.ts
- libs/converter-nh-accuvote/src/convert/accuvote.ts
- libs/converter-nh-accuvote/src/convert/convert_election_definition.ts
- libs/converter-nh-accuvote/src/convert/convert_election_definition_header.test.ts
- libs/converter-nh-accuvote/src/convert/convert_election_definition_header.ts
- libs/converter-nh-accuvote/src/convert/read_grid_from_election_definition.test.ts
- libs/converter-nh-accuvote/src/convert/read_grid_from_election_definition.ts
- libs/converter-nh-accuvote/src/convert/types.ts
> refactor(converter-nh-accuvote): separate XML parsing

- libs/image-utils/bin/pdf-to-images
Got broken by a recent refactor
> image-utils: Fix pdf-to-images script

- libs/logging/VotingWorksLoggingDocumentation.md
- libs/logging/log_event_details.toml
- libs/logging/src/log_event_ids.ts
- libs/logging/types-rust/src/log_event_enums.rs
This PR adds new log events for VVSG2 compliance and updates docs and typescript+rust types.
> New log events for vvsg2

- apps/scan/frontend/src/screens/poll_worker_fujitsu_post_print_screen.tsx
- apps/scan/frontend/src/screens/poll_worker_screen.test.tsx
These are broken according to #5238.
https://github.com/user-attachments/assets/5ef99980-8a60-4d67-a2b5-bf3159440ace
Added new test to act as regression test, confirmed flow now works in dev.
> bug fix: fix primary election polls paused and resumed reports

- apps/scan/backend/src/scanners/custom/custom_app_scan.test.ts
It was possible to move beyond the `scanning` state to the `accepting` state before the test could assert on the `scanning` state. Updated the test to ensure this won't happen by using a deferred promise.
N/A
Ensured that there are no other tests that use this assertion pattern
> scan/backend: Fix flaky test race condition for Custom scanner

- libs/basics/src/iterators/lines.test.ts
- libs/basics/src/iterators/lines.ts
Also adds a test to ensure it really works.
> docs(basics): add an example of using `lines` with `stream.pipeline`

- apps/admin/frontend/src/screens/manual_data_summary_screen.tsx
Removes unnecessary optional chaining that was causing coverage to fail.
No user facing change
Existing tests
> remove unnecessary optional chaining

- apps/design/backend/src/debug.ts
- apps/design/backend/src/language_and_audio/speech_synthesizer.ts
- apps/design/backend/src/language_and_audio/translation_source_counts.ts
- apps/design/backend/src/language_and_audio/translator.ts
Avoid spamming the logs during tests.
> apps/design/backend: Convert console.log to debug

- libs/monorepo-utils/package.json
- package.json
- pnpm-lock.yaml
Part 2 of picking https://github.com/votingworks/vxsuite/pull/5422 apart until I figure out why it fails only in CI. Follow-up to #5424.
n/a
Automated.
> chore(dev-deps): update `eslint`

- libs/fixture-generators/bin/generate-cvr-fixtures
This script was broken by https://github.com/votingworks/vxsuite/pull/5255.
N/A
Ran the script
> libs/fixture-generators: Fix bin/generate-cvr-fixtures

- libs/ballot-interpreter/src/hmpb-ts/cli.ts
Adds the ability to run the bin/interpret command line tool with the options: <election-path> <system-settings-path> <cvr-directory-path> where <cvr-directory-path> is assumed to be a folder that we save in the "cast-vote-records" folder on usb drives in production. These folders each contain a subfolder with front and back images that the script will pick out and run against the interpret tool with the other specified arguements. Should make it easier to quickly get reports after generating cvrs in prod. 
Ran script against a recent cvr export
> Add ability to use bin/interpret with path to cvr file directory

- libs/ballot-interpreter/src/hmpb-ts/cli.test.ts
- libs/ballot-interpreter/src/hmpb-ts/cli.ts
Makes some small changes to better support testing.
> test(ballot-interpreter): add a test for CVR interpretation

- apps/central-scan/backend/src/importer.ts
> allow scanning official ballots in test mode per system setting in VxCentralScan

- pnpm-lock.yaml
> chore(pnpm): re-sync lockfile

- libs/auth/src/integration_test_utils.ts
Fixing a logical merge conflict on main between https://github.com/votingworks/vxsuite/pull/5554 and https://github.com/votingworks/vxsuite/pull/5557
> Fix logical merge conflict on main

- libs/auth/src/signed_hash_validation.ts
A known follow-up to https://github.com/votingworks/vxsuite-complete-system/pull/403
> Account for renaming of directories in vxsuite-complete-system

- apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts
Issue link: https://github.com/votingworks/vxsuite/issues/5597
This PR decreases log noise on VxMark by suppressing two highly-frequent low-utility events:
- `COVER_STATUS`: Just tells us that we polled cover status and does not include the cover status itself. The transitions from cover-closed to cover-open and vice versa are already covered elsewhere.
- `NO_PAPER_ANYWHERE`: Just tells us that we polled for paper and found none.
As a kinda funny stat, we're currently writing ~1MB of logs every 5 minutes on VxMark. Given the very limited storage capacity on VxMark (~5GB), it would take 17 days to fill up the entire capacity of VxMark with logs. Of course rebooting compresses the logs down, and I think they compress pretty well. But still, this PR should render that possibility moot.
> Decrease log noise on VxMark

- libs/ballot-interpreter/test/fixtures/nh-test-ballot/election.json
Updates this election fixture to fit the updated `BallotStyle` schema.
> test(scan): fix election fixture

- libs/basics/.eslintignore
- libs/basics/jest.config.js
- libs/basics/package.json
- libs/basics/src/assert.test.ts
- libs/basics/src/collections.test.ts
- libs/basics/src/date_without_time.test.ts
- libs/basics/src/deferred.test.ts
- libs/basics/src/duplicates.test.ts
- libs/basics/src/errors.test.ts
- libs/basics/src/find.test.ts
- libs/basics/src/group_by.test.ts
- libs/basics/src/iterators/async_iterator_plus.test.ts
- libs/basics/src/iterators/async_iterator_plus.ts
- libs/basics/src/iterators/integers.test.ts
- libs/basics/src/iterators/iter.test.ts
- libs/basics/src/iterators/iterator_plus.test.ts
- libs/basics/src/iterators/iterator_plus.ts
- libs/basics/src/iterators/lines.test.ts
- libs/basics/src/iterators/lines.ts
- libs/basics/src/iterators/naturals.test.ts
- libs/basics/src/map_object.test.ts
- libs/basics/src/merge_objects.test.ts
- libs/basics/src/range.test.ts
- libs/basics/src/result.test.ts
- libs/basics/src/sleep.test.ts
- libs/basics/src/type_guards.test.ts
- libs/basics/src/typed_as.test.ts
- libs/basics/src/unique.test.ts
- libs/basics/vitest.config.ts
- pnpm-lock.yaml
> test(basics): convert tests from `jest` to `vitest`

- apps/admin/backend/test/app.ts
- apps/central-scan/backend/test/helpers/setup_app.ts
- apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts
- apps/mark-scan/backend/src/pat-input/connection_status_reader.test.ts
- apps/mark-scan/backend/src/pat-input/mock_connection_status_reader.test.ts
- apps/mark-scan/backend/src/util/hardware.test.ts
- apps/mark-scan/backend/test/app_helpers.ts
- apps/mark/backend/test/app_helpers.ts
- apps/scan/backend/test/helpers/shared_helpers.ts
- libs/auth/src/dipped_smart_card_auth.test.ts
- libs/auth/src/inserted_smart_card_auth.test.ts
- libs/backend/src/system_call/api.test.ts
- libs/backend/src/system_call/export_logs_to_usb.test.ts
- libs/db/.eslintignore
- libs/db/jest.config.js
- libs/db/package.json
- libs/db/src/client.test.ts
- libs/db/vitest.config.ts
- libs/logging/package.json
- libs/logging/src/export.test.ts
- libs/logging/src/logger.test.ts
- libs/logging/src/test_utils.test.ts
- libs/logging/src/test_utils.ts
- libs/usb-drive/src/usb_drive.test.ts
- pnpm-lock.yaml
> test(db): move from `jest` to `vitest`

- libs/usb-drive/.eslintignore
- libs/usb-drive/jest.config.js
- libs/usb-drive/package.json
- libs/usb-drive/src/list_directory_on_usb_drive.test.ts
- libs/usb-drive/src/list_directory_on_usb_drive.ts
- libs/usb-drive/src/mocks/file_usb_drive.test.ts
- libs/usb-drive/src/mocks/helpers.ts
- libs/usb-drive/src/mocks/memory_usb_drive.test.ts
- libs/usb-drive/src/mocks/memory_usb_drive.ts
- libs/usb-drive/src/usb_drive.test.ts
- libs/usb-drive/vitest.config.ts
- pnpm-lock.yaml
> test(usb-drive): replace `jest` with `vitest`

- apps/design/backend/package.json
- apps/design/backend/scripts/db_reset_dev.sh
- apps/design/backend/scripts/start.sh
https://github.com/votingworks/vxsuite/issues/5698
Updating the `db:reset` and `start` scripts to fix a couple issues with running VxDesign locally:
- Creating the `design` user as a `superuser`, to mimic what we're doing in Arlo - avoids complexity around setting up table permissions.
- Adding missing Postgres env vars for user/DB configuration to the `start` script.
> [VxDesign] Fix issues with dev Postgres

- libs/cdf-schema-builder/.eslintignore
- libs/cdf-schema-builder/jest.config.js
- libs/cdf-schema-builder/package.json
- libs/cdf-schema-builder/src/docs.test.ts
- libs/cdf-schema-builder/src/index.test.ts
- libs/cdf-schema-builder/src/json_schema.test.ts
- libs/cdf-schema-builder/src/parse_json.test.ts
- libs/cdf-schema-builder/src/util.test.ts
- libs/cdf-schema-builder/src/xsd.test.ts
- libs/cdf-schema-builder/test/mock_writable.test.ts
- libs/cdf-schema-builder/test/mock_writable.ts
- libs/cdf-schema-builder/vitest.config.ts
- pnpm-lock.yaml
> test(cdf-schema-builder): replace `jest` with `vitest`

- apps/design/backend/src/app.ts
Closes #5787
Tested with:
```
pnpm --dir apps/design/frontend build:prod && \
PGUSER=design PGPASSWORD=design PGDATABASE=design node apps/design/backend/build/index.js
```
https://github.com/user-attachments/assets/377bb618-c198-4b24-aff2-530103c37746
Manual testing.
> fix(design): ensure loading non-root URLs works

- apps/design/backend/package.json
- apps/design/backend/src/app.ts
- apps/design/backend/src/configure_sentry.ts
- apps/design/backend/src/env.d.ts
- apps/design/backend/src/index.ts
- apps/design/backend/vitest.config.ts
- apps/design/frontend/package.json
- apps/design/frontend/src/index.tsx
- pnpm-lock.yaml
Adds Sentry instrumentation to both server and client. Captures uncaught exceptions and also enables web transaction tracing (useful for performance profiling).
N/A
Manual testing
> VxDesign: Sentry instrumentation

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/worker/generate_election_package.ts
- libs/hmpb/src/render_ballot.test.tsx
- libs/hmpb/src/render_ballot.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5702
A few changes to make VxDesign export a v3-compatible election package when using the v3 NH ballot template:
- Modify the election date to account for a timezone-related issue in v3 VxSuite.
Modeled off of https://github.com/votingworks/vxsuite/pull/4750/files.
- Modify the system settings to conform to the v3 format
- Remove all of the other files besides election.json and systemSettings.json
There are technically a number of other fields added to election.json in v4, but v3 doesn't seem to mind them. @eventualbuddha if you found otherwise in your investigation of this, let me know.
- Manually tested exporting an election package and loading it into v3 VxAdmin
- Added some basic automated tests
> VxDesign: v3-compatible election package

- apps/design/frontend/src/ballot_order_info_screen.test.tsx
- apps/design/frontend/src/ballot_order_info_screen.tsx
- apps/design/frontend/src/ballots_screen.tsx
- apps/design/frontend/src/contests_screen.tsx
- apps/design/frontend/src/election_info_screen.tsx
- apps/design/frontend/src/geography_screen.test.tsx
- apps/design/frontend/src/geography_screen.tsx
- apps/design/frontend/src/tabulation_screen.test.tsx
- apps/design/frontend/src/tabulation_screen.tsx
- libs/ui/src/button.test.tsx
- libs/ui/src/button.tsx
- libs/ui/src/power_down_button.tsx
- libs/ui/src/set_clock.tsx
Closes #5788
Found it annoying to not be able to submit forms with Enter while working on #5895.
> feat(design): improve form a11y

- apps/design/backend/src/worker/index.ts
> design/backend: Fix Sentry import path

- apps/design/frontend/src/contests_screen.tsx
Refs #5897 
- make required fields block save
- trim text field values on blur
- ensure "Seats" is in the range 1..10
- confirm deletions with modals
https://github.com/user-attachments/assets/40a7d431-21b6-42f6-9b8a-04f763412b76
Manually tested since automated testing is temporarily disabled.
> feat(design): improve Contest screen UX

- apps/design/frontend/src/contests_screen.tsx
- apps/design/frontend/src/tabulation_screen.tsx
Refs #5897
- prevent crashes/resets to 0 on threshold fields
- make all visible threshold fields required
https://github.com/user-attachments/assets/da4bb840-6a7f-4853-a16b-416406c9c3a0
Manually tested since automated testing is temporarily disabled.
> feat(design): improve Tabulation screen UX

- apps/design/backend/src/types.ts
- apps/design/frontend/src/ballot_order_info_screen.test.tsx
- apps/design/frontend/src/ballot_order_info_screen.tsx
Fielding one last feedback request from Ginny (to rename the collate checkbox option for clarity) but also opening this in case anything comes up as it pertains to https://votingworks.slack.com/archives/C085YT4798C/p1738356908222099.
> Ballot order form final edits

- libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx
Instead of measuring one element at a time to snap it to the grid, batch these calls as much as possible, snapping all elements in a contest to the grid at once.
Improves 10 page ballot render from 9s to 3s
- Manual testing of perf improvement
> V3 NH ballot template: Batch elements when snapping to grid

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/file_storage_client.ts
- apps/design/backend/test/helpers.ts
- apps/design/backend/tsconfig.json
- apps/design/backend/vitest.config.ts
I fixed the ones that were easy and `test.skip`ped the rest.
n/a
Automated
> test(design): partially re-enable `app.test.ts`

- libs/hmpb/src/render_ballot.test.tsx
- libs/hmpb/src/render_ballot.tsx
V3 has a bug where the tally reports do not use the custom label for yes/no contest options (aka ballot measures or articles). As a result, the ballot will have e.g. "A" and "B" but the results will say "Yes" and "No". To work around this we transform yes/no contests in V3 elections that contain custom labels into candidate contests with candidates named using the custom label.
I've verified that the various tally reports show the correct information and include the contests where they were originally defined within the election definition.
**Interpretation is correct.**
**Overvotes work the same way.**
**Articles appear in the proper order in reports.**
Added basic automated test. Tested with draft version of Londonderry's election definition.
> fix(design): work around V3 custom yes/no label bug

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/app.ts
- apps/design/frontend/.eslintignore
- apps/design/frontend/src/api.ts
- apps/design/frontend/src/app.test.tsx
- apps/design/frontend/src/ballot_order_info_screen.test.tsx
- apps/design/frontend/src/ballot_screen.test.tsx
- apps/design/frontend/src/ballots_screen.test.tsx
- apps/design/frontend/src/ballots_screen.tsx
- apps/design/frontend/src/export_screen.tsx
- apps/design/frontend/src/tabulation_screen.test.tsx
- apps/design/frontend/test/api_helpers.tsx
- apps/design/frontend/tsconfig.json
- apps/design/frontend/vitest.config.ts
Refs #5953 
Obsoletes #5856
Re-enables one test file per commit. Note that I changed the ballot finalization API to make testing it easier (explained in the commit).
n/a
Automated tests 🎉
> test(design): re-enable some tests

- apps/design/backend/src/app.test.ts
- apps/design/backend/test/helpers.ts
- apps/design/frontend/.eslintignore
- apps/design/frontend/src/ballot_order_info_screen.test.tsx
- apps/design/frontend/src/ballot_screen.test.tsx
- apps/design/frontend/src/ballots_screen.test.tsx
- apps/design/frontend/src/election_info_screen.test.tsx
- apps/design/frontend/src/elections_screen.test.tsx
- apps/design/frontend/src/export_screen.test.tsx
- apps/design/frontend/src/features_context.test.tsx
- apps/design/frontend/src/features_context.tsx
- apps/design/frontend/src/image_input.test.tsx
- apps/design/frontend/src/tabulation_screen.test.tsx
- apps/design/frontend/test/api_helpers.tsx
- apps/design/frontend/test/fixtures.ts
- apps/design/frontend/tsconfig.json
- apps/design/frontend/vitest.config.ts
Refs #5953 
n/a
Automated tests 🥳
> test(design): re-enable some more tests

- apps/design/frontend/src/app.tsx
- apps/design/frontend/src/features_context.tsx
- apps/design/frontend/src/routes.ts
- apps/design/frontend/src/system_settings_screen.test.tsx
- apps/design/frontend/src/system_settings_screen.tsx
https://github.com/votingworks/vxsuite/issues/5999
* Renames `Tabulation` tab to `System Settings`
* Supports editing of all system settings values
https://github.com/user-attachments/assets/54de0397-5477-40aa-813c-65ca22dcaba1
- added automated tests
- manually verified form works and updated fields are present in systemSettings.json
> [VxDesign] Edit all system settings

- apps/mark-scan/backend/package.json
- apps/mark-scan/backend/src/custom-paper-handler/application_driver.ts
- apps/mark-scan/backend/src/electrical_testing/app.ts
- apps/mark-scan/backend/src/electrical_testing/background.ts
- apps/mark-scan/backend/src/electrical_testing/context.ts
- apps/mark-scan/backend/src/electrical_testing/server.ts
- apps/mark-scan/backend/src/index.ts
- apps/mark-scan/backend/src/store.test.ts
- apps/mark-scan/backend/src/store.ts
- apps/mark-scan/frontend/src/electrical_testing/api.ts
- apps/mark-scan/frontend/src/electrical_testing/app_root.tsx
- libs/logging/VotingWorksLoggingDocumentation.md
- libs/logging/log_event_details.toml
- libs/logging/src/log_event_ids.ts
- libs/logging/types-rust/src/log_event_enums.rs
- libs/utils/src/file_reading.ts
- pnpm-lock.yaml
Adds a loop for exercising the printer-scanner device in VxMark (`paper handler`).
Needs to be tested against hardware.
> VxMark electrical testing: print scan loop

- apps/scan/backend/src/electrical_testing/background.test.ts
- apps/scan/backend/src/electrical_testing/background.ts
Prints a full copy of the "VxScan Test Print" every five minutes, pausing scanning while that's happening.
https://github.com/user-attachments/assets/f4581e3e-fc9d-47be-b921-2d5413a2cc6a
I left it running on the real hardware for about 45 minutes (build 0.5.5) and it worked well, printing out the test page every five minutes as expected.
> feat(scan): stress test thermal printer

- apps/scan/backend/src/electrical_testing/background.ts
- apps/scan/backend/stress-test-print-page.pdf
The other one is pretty heavy and not really representative of our normal workload. This one is closer.
> feat(scan): use less intense test print for stress test

- apps/design/backend/schema.sql
- apps/design/backend/src/app.test.ts
- apps/design/backend/src/app.ts
- apps/design/backend/src/store.ts
- apps/design/frontend/src/election_info_screen.test.tsx
- apps/design/frontend/src/election_info_screen.tsx
- apps/design/frontend/src/features_context.tsx
- apps/design/frontend/test/fixtures.ts
- libs/fixture-generators/src/generate-election-package/generate_election_package.test.ts
- libs/fixture-generators/src/generate-election-package/generate_election_package.ts
- libs/logging/package.json
- libs/types/src/ballot_language_config.test.ts
- libs/types/src/ballot_language_config.ts
Adds ballot language selection to the Election Info screen.
https://github.com/user-attachments/assets/ca808707-d74e-4de7-a6a6-284d2800e8fc
> add ballot language to Election Info screen

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/app.ts
- apps/design/backend/src/store.ts
- apps/design/backend/vitest.config.ts
- apps/design/frontend/src/api.ts
- apps/design/frontend/src/geography_screen.test.tsx
- apps/design/frontend/src/geography_screen.tsx
- apps/design/frontend/vitest.config.ts
- libs/types/src/election.ts
Task: #6080 
Builds on the patterns established for districts in #6093 to validate precincts.
N/A - no change in functionality
> VxDesign: Backend validation for precincts form 

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/app.ts
- apps/design/backend/src/store.ts
- apps/design/frontend/src/api.ts
- apps/design/frontend/src/ballots_screen.test.tsx
- apps/design/frontend/src/ballots_screen.tsx
Task: #6080 
Continues the pattern of making separate endpoints for each form to validate the ballot layout form. 
N/A - no functional change
Updated existing tests, added some new ones
> VxDesign: Backend validation for ballot layout form

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/app.ts
- apps/design/backend/src/store.ts
- apps/design/backend/vitest.config.ts
- apps/design/frontend/src/api.ts
- apps/design/frontend/src/system_settings_screen.test.tsx
- apps/design/frontend/src/system_settings_screen.tsx
- apps/design/frontend/vitest.config.ts
> VxDesign: Backend validation for system settings form

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/app.ts
- apps/design/backend/src/store.ts
- apps/design/frontend/src/api.ts
- apps/design/frontend/src/ballot_order_info_screen.test.tsx
- apps/design/frontend/src/ballot_order_info_screen.tsx
- apps/design/frontend/src/export_screen.test.tsx
- apps/design/frontend/src/export_screen.tsx
- apps/design/frontend/vitest.config.ts
> VxDesign: Backend validation for ballot order info form

- libs/ui/vitest.config.ts
Looks like these got broken during the vitest migration.
> libs/ui: Fix exclude pattern for story files in test coverage

- apps/admin/frontend/src/screens/smart_cards_screen.test.tsx
- apps/design/backend/src/app.ts
- apps/mark-scan/backend/src/app.preprinted_ballot_insertion.test.ts
- apps/mark-scan/backend/src/app.ui_strings.test.ts
- apps/mark-scan/backend/src/custom-paper-handler/mock_paper_handler_api.ts
- apps/mark/backend/src/app.ui_strings.test.ts
- apps/scan/backend/src/app_ui_strings.test.ts
- apps/scan/frontend/src/electrical_testing/electrical_testing_screen.tsx
- libs/backend/src/system_call/api.test.ts
- libs/backend/src/system_call/api.ts
- libs/backend/src/ui_strings/ui_strings_api.ts
- libs/backend/src/ui_strings/ui_strings_api_test_runner.ts
- libs/dev-dock/backend/src/dev_dock_api.ts
- libs/grout/src/client.ts
- libs/grout/src/env.d.ts
- libs/grout/src/grout.test.ts
- libs/grout/src/server.ts
- libs/ui/src/hooks/ui_strings_api.ts
- libs/ui/src/system_call_api.test.tsx
- libs/ui/src/system_call_api.tsx
- libs/ui/test/test_context.tsx
Adds middleware to grout with the intention of using it for authentication and logging.
(Currently just a proof of concept - see test case for example usage)
> Grout middleware

- libs/grout/src/server.ts
Adds debug lines to the grout API call handling to get automatic performance stats when toggled for specific method names. I made it method specific as the auth polling and other typical practices make showing all the perf logging kind of impossible to filter through. 
Ran DEBUG=*perf:getCheckInCounts* pnpm start in pollbook/frontend and saw expected perf lines logged.
> Add basic debug perf logging for all grout endpoints

- .circleci/config.yml
- apps/mark-scan/accessible-controller/src/commands.rs
- apps/mark-scan/accessible-controller/src/port.rs
- libs/ballot-interpreter/src/hmpb-rust/interpret.rs
- libs/ballot-interpreter/src/hmpb-rust/js/mod.rs
- libs/ballot-interpreter/src/hmpb-rust/qr_code/detect.rs
- libs/ballot-interpreter/src/hmpb-rust/timing_marks/mod.rs
- libs/ballot-interpreter/src/hmpb-rust/timing_marks/slow.rs
- libs/monorepo-utils/src/circleci.ts
- libs/pdi-scanner/src/rust/rusb_async/pool.rs
- libs/pdi-scanner/src/rust/scanner.rs
- libs/types-rs/src/f32_newtype.rs
- libs/types-rs/src/geometry.rs
Follow up to https://github.com/votingworks/vxsuite-build-system/pull/155
> ci: update docker images for Rust 1.86.0

- libs/auth/src/config.test.ts
- libs/auth/src/config.ts
My bad! Similar updates in https://github.com/votingworks/vxsuite-complete-system/pull/438
> Reference correct VxPollBook cert path

- apps/pollbook/backend/src/app_config.test.ts
All of these checks for a not-found pollbook package should be wrapped in a waitFor as it may take a moment for the usb and zip to be fully processed. The comments on this test were confusing so I updated those as well.
> pollbook: fix flaky test in app config

- apps/scan/backend/src/electrical_testing/app.ts
This was broken by #6380 because we started writing JSON files alongside the images. This caused the "look for the last sheet images" logic to break since it would now find 4 files instead of 2. This fixes it by restricting to images before doing anything else.
> fix(scan): correct `getLastScannedSheet` API

- apps/scan/backend/src/electrical_testing/app.ts
- apps/scan/backend/src/electrical_testing/server.ts
- apps/scan/backend/src/electrical_testing/tasks/card_read_and_usb_drive_write_task.test.ts
- apps/scan/backend/src/electrical_testing/tasks/card_read_and_usb_drive_write_task.ts
- apps/scan/backend/src/electrical_testing/tasks/print_and_scan_task.test.ts
- apps/scan/backend/src/electrical_testing/tasks/print_and_scan_task.ts
- apps/scan/frontend/src/electrical_testing/api.ts
- apps/scan/frontend/src/electrical_testing/app_root.tsx
Refs #6253 
Fits better with `TaskController`.
> refactor: rename "loops" to "tasks"

- apps/scan/frontend/src/components/printer_management/load_paper_modal.tsx
> Update printer level color in copy from green to white

- apps/mark-scan/backend/src/electrical_testing/app.ts
- apps/mark-scan/backend/src/electrical_testing/background.ts
- apps/mark-scan/backend/src/electrical_testing/context.ts
- apps/mark-scan/backend/src/index.ts
This will allow us to pause the tasks when we update the UI to support that.
No visual or functional changes.
Tested manually in a VM to ensure pressing "Stop Testing" still works.
> refactor: switch `AbortController` to `TaskController`

- apps/scan/frontend/src/app.test.tsx
- libs/ui/src/unconfigured_election_screen.test.tsx
- libs/ui/src/unconfigured_election_screen.tsx
Closes #6137. [Slack conversation](https://votingworks.slack.com/archives/CJU9MSC6S/p1741022144200469).
> unconfigured screen copy change to redirect users to VxAdmin

- apps/design/backend/src/test_decks.test.ts
> design/backend: Bump timeout for test decks tests

- apps/pollbook/backend/src/__snapshots__/voter_history.test.ts.snap
- apps/pollbook/backend/src/app.ts
- apps/pollbook/backend/src/voter_history.test.ts
- apps/pollbook/backend/src/voter_history.ts
- apps/pollbook/backend/vitest.config.ts
Adds a basic snapshot test and updates the voter history export as detailed in: https://github.com/votingworks/vxsuite/issues/6461 
n/a see snapshot for file update example 
Ran Test
> Update Voter History Export

- apps/admin/frontend/src/screens/contest_adjudication_screen.tsx
https://github.com/votingworks/vxsuite/issues/6503
Changes the adjudication caption color to make the caption stand out more. Discussion [here](https://votingworks.slack.com/archives/C08A8D6V8F9/p1749070479658529)
NA
> apps/admin: Update adjudication caption color

- libs/pdi-scanner/examples/scan_forever.rs
Small fix for an issue from my suggestion in #6500.
> fix(scan): print elapsed time

- apps/pollbook/backend/src/barcode_scanner/socket_server.test.ts
- apps/pollbook/backend/src/barcode_scanner/socket_server.ts
Enables the node backend to reconnect to the UDS server if the socket is closed. The primary use case is if the daemon restarts.
https://github.com/user-attachments/assets/f100ba92-7af6-45a4-9939-ced8d2ef8ba8
- added tests
> [pollbook] backend reconnects to daemon on socket close

- apps/pollbook/backend/src/app_multi_node.test.ts
https://votingworks.slack.com/archives/C07CR6T1TLK/p1750110620758209 showed this line flake that is not currently wrapped in a waitFor as it should be.
> Wrap flaky line in waitFor

- libs/hmpb/src/ballot_templates/nh_ballot_template.tsx
- libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx
Some minor cleanup to improve code clarity.
N/A
Existing tests
> hmpb: Refactor some contest layout code in ballot templates

- apps/mark/backend/src/app.auth.test.ts
- apps/mark/backend/src/app.ts
https://github.com/votingworks/vxsuite/issues/6706
Adding missing API for generating signed hash validation QR codes to VxMark - copied from MarkScan.
- Unit test for now - not used in the client yet
> [Mark] Add signed hash validation endpoint

- apps/pollbook/backend/src/app_multi_node.test.ts
`setupUnconfiguredPollbooksOnNetwork` is failing on the assertion `expect(context.peerWorkspace.store.getNewEvents).not.toHaveBeenCalled();` in CI about half the time. The setup helper is called twice from the failing test and no stacktrace is provided on assertion failure. This will help narrow down if there's a reliable pattern to the assertion failure (eg. if an assumption is being broken by calling the setup function twice).
Adds minor logging to identify source of failed assertion
N/A
N/A
> add error message

- apps/design/backend/src/app.test.ts
- apps/design/backend/src/app.ts
- apps/design/backend/src/auth0_client.ts
- apps/design/backend/src/types.ts
- apps/design/frontend/src/app.test.tsx
- apps/design/frontend/src/ballot_order_info_screen.test.tsx
- apps/design/frontend/src/ballot_order_info_screen.tsx
- apps/design/frontend/src/ballots_screen.test.tsx
- apps/design/frontend/src/ballots_screen.tsx
- apps/design/frontend/src/contests_screen.test.tsx
- apps/design/frontend/src/contests_screen.tsx
- apps/design/frontend/src/election_info_screen.test.tsx
- apps/design/frontend/src/election_info_screen.tsx
- apps/design/frontend/src/elections_screen.tsx
- apps/design/frontend/src/export_screen.test.tsx
- apps/design/frontend/src/export_screen.tsx
- apps/design/frontend/src/geography_screen.test.tsx
- apps/design/frontend/src/geography_screen.tsx
- apps/design/frontend/src/nav_screen.tsx
- apps/design/frontend/src/system_settings_screen.test.tsx
- apps/design/frontend/src/system_settings_screen.tsx
- apps/design/frontend/test/api_helpers.tsx
- libs/ui/src/icons.tsx
Closes: #5907 
Shows the logged-in user's info and a log out button in the header. We only have user email addresses, no names, so that's what we show.
https://github.com/user-attachments/assets/f441b179-e7b6-45fc-86b0-d3ccce0b4740
- Manual test with Auth0 test env
- Update automated tests
> VxDesign: Show logged in user, add log out button

- apps/pollbook/backend/vitest.config.ts
Addresses coverage flake: https://app.circleci.com/pipelines/github/votingworks/vxsuite/21142/workflows/d23fd58d-0251-4904-8f39-59183a1edecc/jobs/920607
N/A
N/A
> drop pollbook coverage

- apps/pollbook/frontend/src/app_poll_worker_screen.test.tsx
- apps/pollbook/frontend/vitest.config.ts
(Hopefully) fixes a flaky test in pollbook frontend
> simplify primary election check in happy path test

- apps/pollbook/backend/src/app_config.test.ts
Possibly addresses flaky test by increasing timeout when waiting for successful configuration:
https://app.circleci.com/pipelines/github/votingworks/vxsuite/21181/workflows/79bf8b46-9950-4c9f-ad3e-b50aa7678a99/jobs/922732
> double timeout for successful usb configuration test

- apps/pollbook/frontend/src/voter_registration_screen.test.tsx
- apps/pollbook/frontend/src/voter_registration_screen.tsx
https://github.com/votingworks/vxsuite/issues/6819
Updates the copy when there are duplicate names, see ticket for details.
> update duplicate registration copy

- libs/hmpb/src/ballot_fixtures_vx_general_election_fixtures.test.ts
> hmpb: Bump flaky test timeout

- apps/pollbook/frontend/package.json
- apps/pollbook/frontend/src/app.tsx
- libs/logging/VotingWorksLoggingDocumentation.md
- libs/logging/log_event_details.toml
- libs/logging/src/log_event_enums.ts
- libs/logging/types-rust/src/log_event_enums.rs
- pnpm-lock.yaml
Log when the route on the page changes. This will be different if/when we upgrade to react router v6. 
https://github.com/votingworks/vxsuite/issues/6847
Clicked around, verified logs.
> Add logging to react router route changes

- apps/design/frontend/src/elections_screen.test.tsx
- apps/design/frontend/src/elections_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/6267
https://github.com/user-attachments/assets/7c3264ed-23ab-4387-a4e6-6f5288264281
Extended automated test
> VxDesign: Add seach filter to election screen

- libs/auth/scripts/src/program_system_administrator_java_card.ts
Issue link: https://github.com/votingworks/vxsuite/issues/6935
See https://github.com/votingworks/vxsuite-complete-system/pull/467 for more context.
> VxPollBook: Sys admin card bootstrapping

- apps/pollbook/frontend/src/app.test.tsx
- apps/pollbook/frontend/src/system_administrator_screen.test.tsx
- apps/pollbook/frontend/src/unconfigured_screen.tsx
The one piece of feedback from @mattroe after reviewing the product 🙃 .
> VxPollBook: slight copy change

- libs/types/src/system_settings.ts
> LA Demo: update default system settings

- libs/dev-dock/backend/src/dev_dock_api.ts
- libs/dev-dock/frontend/package.json
- libs/dev-dock/frontend/src/dev_dock.test.tsx
- libs/dev-dock/frontend/src/dev_dock.tsx
- libs/dev-dock/frontend/tsconfig.build.json
- libs/dev-dock/frontend/tsconfig.json
- pnpm-lock.yaml
Closes #7284.
Improves dev dock screenshot experience:
- adds keyboard shortcut (Cmd + K)
- uses modal rather than `alert()` to avoid messing up focus
- allows editing filename
https://github.com/user-attachments/assets/6054d32f-8132-4e63-a8b3-32df1d563bb5
Did add tests.
> dev dock screenshot flow improvements
