votingworks/vxsuite

apps/design/backend/src/app.ts, apps/design/backend/src/test_decks.test.ts, apps/design/backend/src/test_decks.ts
We don't need to pass the ballot documents in just to get the grid layouts, since the grid layouts are already in the election definition. Also, we don't need a layout for each precinct, since layouts are the same across precincts that share a ballot style.
This makes life a little easier when integrating the upcoming new ballot rendering stack.
Existing tests
=> Refactor: Simplify test deck generation arguments

apps/mark-scan/frontend/src/pages/print_page.tsx, apps/mark/frontend/src/pages/print_page.tsx, libs/mark-flow-ui/src/pages/__snapshots__/print_page.test.tsx.snap, libs/mark-flow-ui/src/pages/print_page.test.tsx, libs/mark-flow-ui/src/pages/print_page.tsx, libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap, libs/ui/src/bmd_paper_ballot.dual_language.test.tsx, libs/ui/src/bmd_paper_ballot.stories.tsx, libs/ui/src/bmd_paper_ballot.test.tsx, libs/ui/src/bmd_paper_ballot.tsx
Resolves https://github.com/votingworks/vxsuite/issues/4474
Applying the following changes to increase the number of contests we can fit on a single page of the BMD paper ballot:
- Decrease font size to the VVSG 2.0 minimum: `10pt`
- For VSAP prints, decrease the size of the top margin, so that the ballot header is covered by the VSAP in-feed hood, while keeping the first row of contests visible.
- Increase the number of contest columns as the number of columns increases.
- Drop party names from candidate selections when rendering 3+ columns.
- Shrink contest titles.
- Shrink English text on multi-language ballots further (75% -> 60%).
- Inline English text whenever possible on multi-language ballots (we were previously rendering on a new line in some cases).
- Reduce spacing where …
=> Update BMD paper ballot single-page layout to fit more contests

Cargo.lock
Updates dependencies in a manner compatible with the versions specified in `Cargo.toml` files. (See [docs](https://doc.rust-lang.org/cargo/commands/cargo-update.html)).
This PR only updates the versions of packages that `cargo` decides are semver-compatible with the versions specified in `Cargo.toml` files transitively. If we assume that care was taken in choosing the versions appropriately, I believe the risk of this is low. It is of course possible that an update could have a change that unintentionally breaks our code. In the worst case, this breakage is subtle and isn't caught by our tests. This risk has to be weighed against the risk of stagnation.
In the Rust ecosystem, the emphasis on staying up to date is even stronger than many others. Many crates have policies that look …
=> chore(rust): run `cargo update`

apps/mark-scan/accessible-controller/src/controllerd.rs, apps/mark-scan/pat-device-input/src/patinputd.rs
- use doc comments (triple-slash) on `clap::Parser` struct fields to have them show up both in intellisense and in `--help` output
- unconditionally run `Args::parse()` early to allow handling of `--help` and `--version` flags
```
Usage: patinputd [OPTIONS]
Options:
-s, --skip-hardware-check  Allow the daemon to run if no hardware is found
-h, --help                 Print help
-V, --version              Print version
```
=> fix(mark-scan): `clap` usage fixes

Cargo.lock, Cargo.toml, libs/ballot-interpreter/Cargo.toml, libs/ballot-interpreter/src/hmpb-rust/debug.rs, libs/ballot-interpreter/src/hmpb-rust/js/args.rs, libs/ballot-interpreter/src/hmpb-rust/js/serialization.rs
These are the ones that `cargo update` couldn't automatically update from #4734. Changes:
- [`base64` 0.21.4..0.22.0](https://github.com/marshallpierce/rust-base64/compare/v0.21.4...v0.22.0)
- [`image` 0.24.5..0.25.0](https://github.com/image-rs/image/compare/v0.24.5...v0.25.0)
- [`imageproc` 0.23.0..0.24.0](https://github.com/image-rs/imageproc/compare/6a7adf4bfc75e506452c43681ab9b9a90ecb4081...633322756992e5b15521eb9cf1dffdca73a96b3f)
- [`itertools` 0.10.5..0.12.1](https://github.com/rust-itertools/itertools/compare/v0.10.5...v0.12.1)
- [`neon` 0.10..1.0.0](https://github.com/neon-bindings/neon/compare/0.10.1...1.0.0)
- [`pretty_env_logger` 0.4.0..0.5.0](https://github.com/seanmonstar/pretty-env-logger/compare/v0.4.0...v0.5.0)
- [`rqrr` …
=> chore(rust): update outdated direct dependencies

apps/mark-scan/frontend/src/api.ts
Fixes https://github.com/votingworks/vxsuite/issues/4691
Disabling the react-query cache for the `getInterpretation` API call, to avoid UI flicker when rendering the `ValidateBallotPage`. This will ensure that we're always loading fresh data when re-rendering the page. We were already invalidating the cache for that call whenever the ballot got accepted or rejected, but since that happens in the same component that fetches the interpretation data, it was getting re-fetched and cached again immediately.
- Repro'd locally and verified the change prevents the flicker
- ~[ ] I have …
=> [fix/4691] [VxMarkScan] Disable query caching for scan interpretations

apps/mark-scan/frontend/src/lib/assistive_technology.test.tsx, apps/mark-scan/frontend/src/lib/assistive_technology.ts, apps/mark-scan/frontend/src/pages/accessible_controller_diagnostic_screen.tsx, apps/mark-scan/frontend/src/pages/continue_to_review_page.tsx, apps/mark-scan/frontend/src/pages/diagnostics_screen.test.tsx, apps/mark-scan/frontend/src/utils/mod.test.ts, apps/mark-scan/frontend/src/utils/mod.ts, apps/mark/frontend/src/lib/gamepad.test.tsx, apps/mark/frontend/src/lib/gamepad.ts, apps/mark/frontend/src/pages/accessible_controller_diagnostic_screen.test.tsx, apps/mark/frontend/src/pages/accessible_controller_diagnostic_screen.tsx, apps/mark/frontend/src/utils/mod.ts, libs/mark-flow-ui/src/pages/contest_page.tsx, libs/mark-flow-ui/src/pages/review_page.tsx, libs/mark-flow-ui/src/pages/start_page.tsx, libs/ui/src/accessible_controllers/index.ts, libs/ui/src/accessible_controllers/mark_controller_illustration.tsx, libs/ui/src/accessible_controllers/mark_scan_controller_illustration.tsx, libs/ui/src/accessible_controllers/navigation.test.tsx, libs/ui/src/accessible_controllers/navigation.ts, libs/ui/src/accessible_controllers/types.ts, libs/ui/src/index.ts, libs/ui/src/keybindings.ts, libs/ui/src/language_settings/language_settings_screen.tsx, libs/ui/src/ui_strings/index.ts, libs/ui/src/ui_strings/keyboard_shortcut_handlers.test.tsx, libs/ui/src/ui_strings/keyboard_shortcut_handlers.tsx
Related to: https://github.com/votingworks/vxsuite/issues/4623
Moving navigation, language, and audio keybindings to a shared location in libs/ui in preparation for use in the BMD accessible controller help flow.
Also fixing a couple controller navigation bugs:
- Focus navigation on the VxMark "Review" screen was previously broken - this fixes the query selectors used to find focusable elements.
- Previously, voters could accidentally navigate to a different contest while an overvote modal or write-in modal was active - this fixes the page navigation logic to no-op when a modal is active.
Also includes updates to the `MarkScanControllerIllustration` to use theme-aware styling for the interactive states - prototype of the help flow here: …
=> [libs/ui] Consolidate keybindings across apps into shared definition

.circleci/config.yml, Cargo.lock, Cargo.toml, apps/mark-scan/accessible-controller/Cargo.toml, apps/mark-scan/accessible-controller/src/controllerd.rs, apps/mark-scan/accessible-controller/src/port.rs, apps/mark-scan/daemon-utils/Cargo.toml, apps/mark-scan/daemon-utils/src/lib.rs, apps/mark-scan/pat-device-input/Cargo.toml, apps/mark-scan/pat-device-input/src/patinputd.rs, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_ids.ts, libs/logging/types-rust/src/log_event_enums.rs, vxsuite.code-workspace
Allows `controllerd` and `patinputd` to run when no hardware is found. The daemons will report failure to connect then run in a no-op loop with a heartbeat logged every 5s.
PAT input running with no hardware
Controller daemon running with no hardware
Controller daemon successfully connecting
* Manually tested both daemons run on VM
* Manually tested both hardware devices work on real hardware
=> Allow daemons to run without hardware; make more robust for different device configs

apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/lib/assistive_technology.test.tsx, apps/mark-scan/frontend/src/voter_flow.test.tsx, apps/mark-scan/frontend/src/voter_flow.tsx, libs/eslint-plugin-vx/src/configs/recommended.ts, libs/test-utils/src/fake_use_audio_controls.ts, libs/types/src/ui_audio_controls.ts, libs/ui/src/accessible_controllers/accessible_controller_sandbox.test.tsx, libs/ui/src/accessible_controllers/accessible_controller_sandbox.tsx, libs/ui/src/accessible_controllers/index.ts, libs/ui/src/accessible_controllers/mark_scan_controller_sandbox.test.tsx, libs/ui/src/accessible_controllers/mark_scan_controller_sandbox.tsx, libs/ui/src/accessible_controllers/test_utils.tsx, libs/ui/src/accessible_controllers/use_accessible_controller_help_trigger.test.tsx, libs/ui/src/accessible_controllers/use_accessible_controller_help_trigger.tsx, libs/ui/src/hooks/use_audio_controls.test.tsx, libs/ui/src/hooks/use_audio_controls.ts, libs/ui/src/keybindings.ts, libs/ui/src/ui_strings/audio_context.test.tsx, libs/ui/src/ui_strings/audio_context.tsx
Resolves https://github.com/votingworks/vxsuite/issues/4623
Adding an accessible controller sandbox screen that allows the user to try out the various buttons without triggering the default behaviour - instead, they'll receive audio feedback on what each button does.
The sandbox will be triggered by the "help" button (currently mapped to the old "replay" keybinding, `Shift+R` -- we can clean that up later) and can be exited with another two successive presses on the "help" button (the first press describes the button and tells the voter they can press it again to exit).
A little long, so recorded with increased speech rate to speed things up a bit:
https://github.com/votingworks/vxsuite/assets/264902/cc3ffc23-c8a5-4d7d-8bad-2cf38cdf0395
- New unit tests for the sandbox component and …
=> [MarkScan] Add the accessible controller help flow

apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/elections_screen.tsx
Since the rest of VxSuite 3.1 has a timezone bug that displays the election date one day earlier, modify the election date input in VxDesign to automatically set the election date one day later than entered by the user. This means we won't have to remember to manually offset the date by one day moving forward.
N/A
Updated existing automated tests, manually tested and verified the ballots and election definition have the correct dates
=> VxDesign 3.1: Account for timezone bug in election date input

apps/scan/backend/schema.sql, apps/scan/backend/src/app.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/src/types.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/custom-scanner/src/parameters.ts, libs/custom-scanner/src/protocol.ts, libs/custom-scanner/src/types.ts, libs/custom-scanner/test/arbitraries.ts
Removes the `supportsUltrasonic` flag, since all of our scanners (Custom and PDI) support multiple sheet detection, so this is an unnecessary flag. Also changes the language used in the code to refer to this feature from "ultrasonic" to "multi sheet detection" in order to better describe what the feature does, not how it works.
N/A
Existing tests
=> apps/scan: Remove ultrasonic flag

apps/scan/backend/src/printing/printer.ts, libs/utils/src/environment_variable.ts
`getEnvironmentVariable` doesn't actually convert it to a boolean, so
the check was always true.
=> apps/scan/backend: Use isFeatureFlag for Fujitsu printer env var

libs/ui/src/accessible_controllers/test_utils.tsx, libs/ui/src/accessible_controllers/use_accessible_controller_help_trigger.test.tsx, libs/ui/src/accessible_controllers/use_accessible_controller_help_trigger.tsx
The accessible controller sandbox requires two consecutive keypresses of the `TOGGLE_HELP` keybinding, but previously only worked if the `Shift` key was held across both key presses - whereas in real-world scenarios, the controller fires key press events `Shift`, `r`, `Shift`, `r` for a double press of the help button.
This change ignores the `Shift` key when determining what the last keypress was, to avoid having the `Shift` key break the exit sequence.
https://github.com/votingworks/vxsuite/assets/264902/d353ef0d-a440-41b9-8bb5-2522dd945419
https://github.com/votingworks/vxsuite/assets/264902/37e5dfd7-5f9b-483a-865d-44311398246e
- Updated unit tests to assert this behaviour …
=> [MarkScan] Fix exit key sequence for the accessible controller sandbox

apps/mark-scan/frontend/src/pages/validate_ballot_page.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
Related to: https://github.com/votingworks/vxsuite/issues/4743
Updating navigation on the `ValidateBallotPage` in MarkScan for consistency with other voter screens ("right" button to advance and cast the ballot, "left" button to reject the ballot and return) and updating the initial audio instructions to reflect that.
- Manual 
=> [MarkScan] Update audio instructions for ValidateBallotPage

libs/pdi-scanner/examples/scan_forever.rs, libs/pdi-scanner/src/client.rs, libs/pdi-scanner/src/lib.rs, libs/pdi-scanner/src/main.rs, libs/pdi-scanner/src/protocol/types.rs
A variety of improvements to libs/pdi-scanner based on the needs of the apps/scan state machine. Details in commits.
N/A
Manual testing with the scanner
=> libs/pdi-scanner: Add commands and improved error handling 

libs/backend/src/system_call/export_logs_to_usb.test.ts, libs/backend/src/system_call/export_logs_to_usb.ts
Closes #4685. I have also seen the same issue described in the same ticket when saving logs from `tty2`. I'm not sure what about saving logs is more prone to delays than other things, but in any case we can just run `sync` on the mount point to ensure the save completes before freeing up the modal / indicating the save is complete to the user.
- Automated testing confirms we are running `sync`
- I manually confirmed that the export still works after this change, although I'm not able to reproduce the original issue on my dev hardware, so I can't be 100% sure it fixes the issue, just 99% sure
=> fix: `sync` after exporting logs

libs/pdi-scanner/src/client.rs, libs/pdi-scanner/src/lib.rs, libs/pdi-scanner/src/main.rs, libs/pdi-scanner/src/scanner.rs
Detect when the scanner is disconnected (e.g. unplugged) while polling the scanner for incoming events. This manifests as `rusb_async::Error:Stall`. Propagate this error back up to the main thread and send a disconnect error event to stdout.
We also break from the loop that is detecting events when we receive an error, which causes the scanner_to_host channel to close, so we handle that case in the main thread by dropping the client (allowing the user to reconnect if desired).
```sh
$ pdictl
{"type":"connect"} # command
{"type":"ok"} # response
{"type":"error","code":"disconnected","message":null} # event
{"type":"connect"} # command
{"type":"error","code":"disconnected","message":null} # response
{"type":"connect"} # command
{"type":"ok"} # response
```
Manual tested `pdictl` as outlined …
=> pdi-scanner: Detect disconnect and send event

apps/mark-scan/frontend/src/app_contest_ms_either_neither.test.tsx, apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/config/types.ts, apps/mark-scan/frontend/src/pages/validate_ballot_page.tsx, apps/mark/frontend/src/app_contest_ms_either_neither.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/config/types.ts, libs/mark-flow-ui/src/components/review.test.tsx, libs/mark-flow-ui/src/components/review.tsx, libs/mark-flow-ui/src/config/types.ts, libs/mark-flow-ui/src/pages/__snapshots__/print_page.test.tsx.snap, libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
Addressing a couple issues found on the `ValidateBallotPage` during testing:
- Removing the icon from the `My Ballot is Incorrect` button to avoid wrapping in the default size mode.
- Updating the wording of the undervote warnings to match the strings used on the printed paper ballot, for consistency.
- Leaving the `You may still vote in this contest` wording intact for the pre-print review screen, but updating `Votes remaining in this contest:` to `Number of unused votes:` there as well, since it's semantically similar and avoids unnecessary branching in the code.
| Before  | After |
| <img width="512" alt="Screenshot 2024-04-18 at 13 32 12" …
=> [MarkScan] Post-testing updates to ValidateBallotPage

libs/ballot-encoder/package.json, libs/ballot-encoder/tsconfig.build.json, libs/ballot-encoder/tsconfig.json, libs/custom-scanner/package.json, libs/fujitsu-thermal-printer/package.json, libs/fujitsu-thermal-printer/tsconfig.build.json, libs/fujitsu-thermal-printer/tsconfig.json, libs/logging/package.json, libs/ui/package.json, pnpm-lock.yaml
Mostly removes `zod` from a number of packages, but also a couple others plus some intra-monorepo deps.
n/a
=> chore: remove unused deps

apps/mark-scan/frontend/src/apimachine_config.test.tsx, apps/mark-scan/frontend/src/app.test.tsx, apps/mark-scan/frontend/src/app.tsx, apps/mark-scan/frontend/src/app_card_unhappy_paths.test.tsx, apps/mark-scan/frontend/src/app_cardless_voting.test.tsx, apps/mark-scan/frontend/src/app_contest_candidate_no_party.test.tsx, apps/mark-scan/frontend/src/app_contest_ms_either_neither.test.tsx, apps/mark-scan/frontend/src/app_contest_multi_seat.test.tsx, apps/mark-scan/frontend/src/app_contest_single_seat.test.tsx, apps/mark-scan/frontend/src/app_contest_write_in.test.tsx, apps/mark-scan/frontend/src/app_contest_yes_no.test.tsx, apps/mark-scan/frontend/src/app_election_package_config.test.tsx, apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/app_quit_on_idle.test.tsx, apps/mark-scan/frontend/src/app_replace_election.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_setup_errors.test.tsx, apps/mark-scan/frontend/src/app_states.test.tsx, apps/mark-scan/frontend/src/lib/assistive_technology.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark-scan/frontend/test/helpers/build_app.tsx
Removing the "Reset Accessible Controller" button (which formerly reloads the page) from the Poll Worker Actions screen, since has no effect on the state of VSAP controller connection.
Manual
=> [MarkScan] Remove unused "Reset Accessible Controller" poll worker action

apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_states.test.tsx, apps/mark-scan/frontend/src/voter_flow.test.tsx, apps/mark-scan/frontend/src/voter_flow.tsx
Update the PAT device calibration step to only happen once a voter session has been started (previously could be triggered on Poll Worker screens whenever the PAT device was connected).
https://github.com/votingworks/vxsuite/assets/264902/d75f1178-1b2b-439d-a509-30dbc262ff99
- New test case for `VoterFlow` component to assert PAT calibration screen takes precedence over ballot screens
- Manual verification with mock PAT connection status reader
- ~[ ] I have added the "user_facing_change" label to this PR to automate …
=> [MarkScan] Only show PAT calibration on voter screens

apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/scanner_cover_open_screen.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, libs/pdi-scanner/src/main.rs, libs/pdi-scanner/src/protocol/packets.rs, libs/pdi-scanner/src/protocol/types.rs, libs/pdi-scanner/ts/src/scanner_client.ts, libs/types/src/precinct_scanner.ts, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
Show a blocking message when the scanner cover is open. Implemented for the PDI scanner only.
Context from @mattroe:
>I think we should populate a distinct message from the “internal connection error” screen that calls out the scanner cover is open and for a poll worker to ensure its closed.
>
> Realistically, this should only happen in the following cases:
> - cleaning (intentional)
> - not closing it all the way after cleaning (unintentional)
> - transport movement (unintentional and unlikely, but possible)
https://github.com/votingworks/vxsuite/assets/530106/79679efa-e721-436f-a820-d9b4786dee2d
Manual testing. Added one frontend test for coverage. Will add backend/driver tests later.
=> apps/scan: Detect when scanner cover is open

apps/mark-scan/backend/package.json, apps/scan/backend/package.json, apps/scan/backend/src/scanners/pdi/state_machine.ts, pnpm-lock.yaml
This will allow us to use xstate's simulated clock for testing, since all delays will use xstate machinery (rather than using rxjs for the polling delays).
N/A
Manual test
=> apps/scan: Use machines instead of observables in PDI state machine

apps/scan/backend/src/scanners/pdi/state_machine.ts
I noticed that it was possible for the `coverClosed` event to be emitted before the state machine had transitioned to the `coverOpen` state (e.g. if you open the cover slightly, remove a jammed ballot, and then immediately close it), in which case we get stuck in the `coverOpen` state. Polling the scanner status seems like a more reliable way to exit this state.
Note that I'm not concerned about missing the `coverOpen` event since that listener is registered at the root of the state machine.
We could conceivably also register the `coverClosed` event handler at the root, but I am worried that it's a bit heavy handed to say that we should transition to `waitingForBallot` at any point if we receive a `coverClosed` event (rather than only when we're already in the `coverOpen` state).
Manually …
=> apps/scan: Poll for PDI scanner cover closed status

apps/central-scan/backend/src/validation.test.ts, libs/eslint-plugin-vx/package.json, libs/hmpb/render-backend/src/next/vx_default_ballot_template.tsx, libs/message-coder/src/message_coder.ts, libs/monorepo-utils/package.json, package.json, pnpm-lock.yaml, script/package.json
Updates to TypeScript v5.4.5 (current latest).
- [What's new in TypeScript 5.3](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html)
- Import Attributes
- `resolution-mode` in Import Types
- `switch (true)` Narrowing
- Narrowing on Comparison to Booleans
- `instanceof` Narrowing Through `Symbol.hasInstance`
- Checks for `super` Property Accesses on Instance Fields
- Interactive Inlay Hints for Types (yay!)
- Setting to Prefer `type` Auto-Imports
- Optimizations by Skipping JSDoc Parsing
- Optimizations by Comparing Non-Normalized Intersections
- Consolidation Between `tsserverlibrary.js` and `typescript.js` (20.5% reduction in `typescript` package size)
- [What's new in TypeScript 5.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-4.html …
=> Update to TypeScript v5.4.5

package.json, pnpm-lock.yaml
Partially address https://github.com/advisories/GHSA-67hx-6x53-jw92
Interesting reading on the vulnerability: https://babeljs.io/blog/2023/10/16/cve-2023-45133
This change only partially addresses the issue because `@babel/traverse` is used _everywhere_. In particular, `@storybook/*` packages seem to be where many of the instances come from. We should consider upgrading cc @kofi-q.
```
┌─────────────────────┬────────────────────────────────────────────────────────┐
│ critical            │ Babel vulnerable to arbitrary code execution when      │
│                     │ compiling specifically crafted malicious code          │
├─────────────────────┼────────────────────────────────────────────────────────┤
│ Package             │ @babel/traverse                                        │ …
```
=> security(babel): remove unused `@codemod/cli`

libs/basics/src/date_without_time.test.ts
This test was failing today due to the high day of the month (30), which was overflowing the date to the next month when we set the month to February (since there are more than 30 days in Feb). See code comment for details
=> Fix DateWithoutTime test that was dependent on current date

libs/ballot-interpreter/src/hmpb-rust/timing_marks.rs
If the image is binarized by the scanner before reaching the interpreter, the Otsu threshold will be computed as 0 (pure black). We were only accepting bottom timing marks whose luminance value was less than the threshold, which was impossible with a threshold of 0. To fix this, we allow matching the threshold exactly.
Manual testing
=> libs/ballot-interpreter: Bugfix for binarized scanner images

libs/mark-flow-ui/src/hooks/use_session_settings_manager.test.tsx, libs/mark-flow-ui/src/hooks/use_session_settings_manager.ts, libs/ui/src/hooks/use_audio_enabled.test.tsx, libs/ui/src/hooks/use_audio_enabled.ts, libs/ui/src/index.ts, libs/ui/test/test_context.tsx
Updating the voter session settings manager to disable audio whenever we're not in a cardless voter auth session and return to the previous state when the cardless voter auth session is resumed.
This avoids audio continuing to play whenever the voter is "logged out" in general. Motivated by an edge case at the end of the voter session when the underlying URL is updated while the `BallotSuccessfullyCastPage` page is still rendered, triggering the screen reader (which listens on page navigation) and causes the text on that page to be repeated.
_(Volume's a little low, so you might have to turn it up a bit)_
Tough to repro the session-end repeated audio issue, since it relies on race condition, but this shows audio getting …
=> [MarkScan] Avoid repeating screen reader audio at the end of voter sessions

apps/mark-scan/frontend/src/app_cardless_voting.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/src/app_cardless_voting.test.tsx, apps/mark/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, apps/mark/integration-testing/e2e/scroll_buttons.spec.ts, libs/utils/src/ballot_styles.ts
Closes https://github.com/votingworks/vxsuite/issues/4762
On the ballot style selection screen for poll workers, we filter ballot styles down to just the primary English ballots for simplicity (ballot styles are updated accordingly under the hood when the voter later updates their display language).
This change strips the `_en` suffixes from these ballot style IDs when displayed and just renders the root ballot style IDs instead.
| <img width="523" alt="Screenshot 2024-05-01 at 12 14 01" src="https://github.com/votingworks/vxsuite/assets/264902/d2189239-a111-41b2-9584-2c43f2ffc3ac"> | <img width="518" alt="Screenshot 2024-05-01 at 12 14 29" src="https://github.com/votingworks/vxsuite/assets/264902/dd1b5db4-aff2-4b16-ac5d-65600b58e831"> …
=> [BMDs] Use language-agnostic ballot style IDs on poll worker screen

libs/types/src/cdf/ballot-definition/fixtures.ts
This was working on CI where the timezone is always UTC, but failing locally.
=> libs/types: Fix broken GeneratedDate in CDF conversion test fixture

libs/auth/src/cryptography.end_to_end.test.ts, libs/auth/src/cryptography.test.ts, libs/auth/src/cryptography.ts, libs/auth/src/tpm.ts
With the introduction of audio clips to election packages, election packages can now be substantially larger than in the past (e.g., 10+ MB instead of 50 KB). Testing with such an election package on a prod VxAdmin has surfaced an issue; digital signing of the election package hangs indefinitely. This issue is specific to prod and use of the TPM.
This PR fixes the issue by separating hashing and signing so that we can hash using the main processor and only sign using the TPM. Hashing large inputs with the TPM can be extremely slow as the TPM processor isn't particularly powerful. It's really only meant for small cryptographic operations.
=> Fix signing of large election packages in prod

apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts
Previously, we were waiting for the scanner to no longer have any document in the scanner to declare accepting complete. It's possible to trick the scanner by feeding a second ballot in while the motors are running to accept the first ballot, which results in either:
- The first ballot successfully ejected, while the second ballot is held in the front
- The first ballot successfully ejected, while the second ballot is held in the middle (covering front and rear sensors)
- The first ballot jammed, while the second ballot is held in the front
We handle this case with a few updates:
- Only declare accepting complete when the rear is cleared
- If the front is covered before the rear is cleared (very unlikely, but possible), go back to the warning to remove the second ballot before deciding …
=> apps/scan: Prevent hanging when second ballot inserted during accept

apps/scan/backend/jest.config.js, apps/scan/backend/schema.sql, apps/scan/backend/src/app.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/src/types.ts, apps/scan/frontend/jest.config.js, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, apps/scan/frontend/src/screens/scan_error_screen.test.tsx, apps/scan/frontend/src/screens/scan_error_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/pdi-scanner/examples/scan_forever.rs, libs/pdi-scanner/src/rust/client.rs, libs/pdi-scanner/src/rust/main.rs, libs/pdi-scanner/src/rust/protocol/packets.rs, libs/pdi-scanner/src/ts/demo.ts, libs/pdi-scanner/src/ts/scanner_client.test.ts, libs/pdi-scanner/src/ts/scanner_client.ts
Enables double feed detection (DFD) for the PDI scanner based on the flag stored in the VxScan db. See commits for details
Note that calibration of the DFD settings is not yet implemented and must be done with the PDI Diagnostics tool currently.
https://github.com/votingworks/vxsuite/assets/530106/d458f1b5-3367-4a05-9634-430b016c0d61
Manual testing, added automated tests
=> apps/scan: Enable double feed detection for PDI scanner

apps/mark-scan/accessible-controller/src/controllerd.rs, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/pat-input/connection_status_reader.test.ts, apps/mark-scan/backend/src/pat-input/connection_status_reader.ts, apps/mark-scan/backend/src/pat-input/constants.ts, apps/mark-scan/backend/src/pat-input/mock_connection_status_reader.ts, apps/mark-scan/backend/src/server.ts
Fixes 2 bugs with hardware daemons in prod images.
*  `PatInputConnectionStatusReader` did not check for GPIO address offset present in Debian 12, resulting in the app being unable to trigger the PAT device calibration flow on Debian 12
* `controllerd` did not receive an echo response the majority of the time on startup, likely because the device was not ready yet
No behavior change. We won't be able to QA on Debian 12 until we build a prod image, but here's a video of backwards compatibility of the PAT change on Debian 11.
https://github.com/votingworks/vxsuite/assets/1060688/c00071b7-9fd4-47e4-a3a4-f6ddc0f6f865
- updated tests
=> [mark-scan] Prod image hardware peripheral fixes

apps/design/backend/src/language_and_audio/translation_overrides.ts
The Spanish version of the name, like the English one, does not appear to contain the leading "El"/"The" definite article. This isn't really meant as the place to put all our translations and is really just an example of how to do overrides (replacing the obviously incorrect "Fiesta Verde"), but I'd still like it to be correct.
Context from Slack: https://votingworks.slack.com/archives/CEL6D3GAD/p1715015367963289
=> fix(design): drop the definite article from "Green Party" translation

apps/admin/backend/package.json, apps/admin/frontend/package.json, apps/central-scan/backend/package.json, apps/central-scan/frontend/package.json, apps/design/backend/package.json, apps/mark-scan/backend/package.json, apps/mark/backend/package.json, apps/scan/backend/package.json, apps/scan/frontend/package.json, libs/api/package.json, libs/auth/package.json, libs/backend/package.json, libs/cdf-schema-builder/package.json, libs/converter-nh-accuvote/package.json, libs/cvr-fixture-generator/package.json, libs/fs/package.json, libs/logging/package.json, libs/mark-flow-ui/package.json, libs/pdi-scanner/package.json, libs/printing/package.json, libs/types/package.json, libs/types/src/__snapshots__/election.test.ts.snap, libs/types/src/__snapshots__/schema.test.ts.snap, libs/types/src/__snapshots__/system_settings.test.ts.snap, libs/types/src/cdf/ballot-definition/__snapshots__/convert.test.ts.snap, libs/types/src/cdf/ballot-definition/convert.test.ts, libs/types/src/schema.test.ts, libs/types/src/system_settings.test.ts, libs/utils/package.json, pnpm-lock.yaml
It doesn't look like there's much in the way of new API that we'd want to use. It does add `util` and `objectUtil` namespaces to the API, but the functions they provide are already covered by existing tools.
Diff: https://github.com/colinhacks/zod/compare/v3.14.4...v3.23.5
n/a
=> chore(deps): upgrade `zod` to latest (v3.23.5)

apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_disconnect.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, libs/logging/src/test_utils.test.ts, libs/logging/src/test_utils.ts, libs/pdi-scanner/src/rust/main.rs, libs/pdi-scanner/src/ts/scanner_client.test.ts, libs/pdi-scanner/src/ts/scanner_client.ts
Makes a variety of changes to libs/pdi-scanner and apps/scan-backend to improve the behavior in edge case error scenarios. The main improvements:
- Improved reliability of recovering from unexpected errors
- Better discernment of when the scanner is in a borked state (so we can show the message to restart)
Details in the commits.
Added tests to cover each piece of new behavior, and manually tested.
=> Improve PDI scanner error handling

apps/scan/backend/src/scanners/pdi/pdi_app_scan_cover_open.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts
If left to its own devices, the PDI scanner will continue trying to scan ballots while the cover is open. Of course, this doesn't actually work because the rollers can't grab the paper. This might actually be an issue if attempting to clean the scanner while the app is running. So we explicitly disable scanning while the cover is open.
Skipping because there's not much to see
Manual test and automated test
=> apps/scan: Disable scanning while scanner cover is open

apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_jam.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts
Previously, we would reject a ballot inserted during the accepted state. Instead, we still wait until the accepted state is done, but then scan the next ballot. This is especially important for testing use cases where we want to feed many ballots in a row.
https://github.com/votingworks/vxsuite/assets/530106/aea505fc-7b45-4eb5-884b-c78aa53bf2e7
Manual testing, updated automated tests
=> apps/scan: Scan ballot inserted during accepted state

libs/pdi-scanner/src/rust/rusb_async/pool.rs, libs/pdi-scanner/src/rust/scanner.rs
- use `if let` instead of `match` when ignoring all but one branch
- name a complex type returned by `Scanner::start`
- remove `unsafe fn` that isn't used which was missing a `# Safety` doc
=> chore(pdi): fix clippy lints

apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, libs/pdi-scanner/src/rust/client.rs, libs/pdi-scanner/src/rust/main.rs, libs/pdi-scanner/src/rust/protocol/packets.rs, libs/pdi-scanner/src/rust/protocol/parsers.rs, libs/pdi-scanner/src/ts/scanner_client.ts
When a ballot is being accepted and a second ballot is inserted, we don't want the second ballot to be mistakenly sucked through the scanner. Though we have guards in place, if there's enough resistance against the first ballot, it's still possible that this can occur.
Luckily, the PDI scanner has an internal "eject pause" feature that is designed to detect a second ballot in the front and pause the ejection. It's more effective than our previous approach since it has lower level control over the motors and can act quicker.
This PR enables the eject pause feature (only for rear ejections - i.e. ballot
accepts) and adds the corresponding events for eject pause/eject resume.
https://github.com/votingworks/vxsuite/assets/530106/b7a54dc6-d990-40ef-b42e-7b3b5b5ed8fa
Note that in the 4th scan …
=> apps/scan: Enable PDI scanner eject pause feature

apps/scan/backend/src/index.ts, apps/scan/backend/src/printing/printer.ts, apps/scan/backend/src/server.test.ts, apps/scan/backend/src/server.ts, libs/fujitsu-thermal-printer/src/cli.ts, libs/fujitsu-thermal-printer/src/driver/coders.ts, libs/fujitsu-thermal-printer/src/driver/driver.ts, libs/fujitsu-thermal-printer/src/mock_printer.ts, libs/fujitsu-thermal-printer/src/printer.ts, libs/fujitsu-thermal-printer/src/status.ts
Commit 1: Currently VxScan just crashes if the printer is not attached on startup, and it cannot handle disconnects and reconnects. While this was OK for the happy path, it's not OK for the sad path and development. Changing the layers so that we are just checking for the device on every status call.
Commit 2: Finishes removing the speed setting (started in commit 1) and also specifies the print quality setting on printer connect. This is to set "Auto-Division" which we've found that we need to set to prevent spikes in power draw that go beyond our v4 PSU capabilities.
=> Fujitsu Printer Reconnect & Power Settings

apps/admin/backend/package.json, apps/central-scan/backend/package.json, apps/central-scan/frontend/package.json, apps/design/backend/package.json, apps/design/frontend/package.json, apps/mark-scan/backend/package.json, apps/mark/backend/package.json, apps/scan/backend/package.json, libs/ballot-interpreter/package.json, libs/converter-nh-accuvote/package.json, libs/custom-paper-handler/package.json, libs/custom-scanner/package.json, libs/cvr-fixture-generator/package.json, libs/fujitsu-thermal-printer/package.json, libs/hmpb/layout/package.json, libs/hmpb/render-backend/package.json, libs/image-utils/package.json, libs/logging/package.json, libs/printing/package.json, libs/res-to-ts/package.json, libs/ui/package.json, libs/usb-drive/package.json, pnpm-lock.yaml, script/package.json
Diff: https://github.com/evanw/esbuild/compare/v0.17.11...v0.21.2
Taking a look through the release notes, it looks like the changes are mostly:
- compatibility with TypeScript
- CSS transformation/bundling fixes
- optimizations
- side-effect preservation when tree shaking
=> chore(deps): upgrade to esbuild@0.21.2

libs/ui/src/ui_strings/audio_volume.ts
Updating the volume offset for screen reader audio based on calibration on VSAP hardware with our [chosen set of headphones](https://www.jlab.com/products/studio-on-ear-headphones?variant=28207115731016&currency=USD&utm_medium=product_sync&utm_source=google&utm_content=sag_organic&utm_campaign=sag_organic&srsltid=AfmBOopcrsnM5iD6c6jpM_MCXk_V30ljmh1hGxGpMNhuNX4wFOUlyARQb4c).
Based on rough measurements, applying a gain of `-68 dB` to audio from Google Cloud TTS when OS volume is set to `100%` results in a real-world output level between `63 dB SPL` and `67 dB SPL`, which falls within the VVSG 2.0 range of `60-70 dB SPL` (VVSG 2.0 7.1-K – Audio settings).
Our volume increments result in jumps of between `5 dB SPL` and `8 dB SPL`, which puts them under the `10 dB` VVSG limit.
- Highly …
=> [BMD] Update screen reader volume level, based on calibration

libs/mark-flow-ui/src/pages/contest_page.tsx
Forcing a component re-mount every time we render a new contest page to make sure the scroll state is reset when navigating between contests.
https://github.com/votingworks/vxsuite/assets/264902/74c9a636-01c0-45d0-b5bc-b3c7704fa355
https://github.com/votingworks/vxsuite/assets/264902/cdc18133-c31e-401b-80e9-b0f37ca702d4
- Manual
=> [BMD] Reset scroll state on contest navigation

apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, libs/custom-paper-handler/src/driver/coders.ts, libs/custom-paper-handler/src/driver/driver.test.ts, libs/custom-paper-handler/src/driver/driver.ts, libs/custom-paper-handler/src/driver/driver_interface.ts, libs/custom-paper-handler/src/driver/mock_driver.ts
Buffering print data (or any data) to the generic transfer-out buffer may invoke the `real-time status transmission` command if the buffered data contains a byte sequence matching that command (`0x10 0x04`). This causes unsolicited data to be passed to the generic transfer-in buffer, which breaks parsing the next time the driver issues a command that responds over the generic transfer-in buffer.
See comment here: https://github.com/votingworks/vxsuite/pull/4846/files#diff-6d4416eebc285362e1f02d2f6252d35972e5c0db67a2db365540cb87a2bea431R388 and [Slack](https://votingworks.slack.com/archives/C03Q42V9MJ5/p1715296095534459) for more.
Successful print of ballot with problematic byte sequence
https://github.com/votingworks/vxsuite/assets/1060688/7a52b519-e07a-4bba-b86c-ecf444566709
- added …
=> [mark-scan] Handle status transmission command

libs/auth/README.md, libs/auth/scripts/src/program_production_system_administrator_java_card_without_vx_admin.ts, libs/auth/scripts/src/program_system_administrator_java_card.ts, libs/auth/scripts/src/program_vendor_java_card.ts, libs/auth/scripts/src/utils.ts
Right as I merged https://github.com/votingworks/vxsuite/pull/4827, I realized that I'd made a tiny mistake with the `program-production-system-administrator-java-card-without-vxadmin` script. The libs/auth README says that you can use the script as follows:
```
VX_MACHINE_JURISDICTION=<jurisdiction> \
VX_PRIVATE_KEY_PATH=/path/to/vx-private-key.pem \
./scripts/program-production-system-administrator-java-card-without-vx-admin
```
But doing so will yield the error:
```
❌ Missing required NODE_ENV env var
```
This PR makes it such that the README is once again correct (by updating the script, not the README).
=> Fix env var quirk with VxAdmin-less prod sys admin card script

apps/mark-scan/backend/src/custom-paper-handler/scanner_status.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts
Fixes an issue where ejecting to front may sometimes result in the paper being held in the front by friction with the paper tray. In this case, the input sensors are tripped and the state machine gets stuck in `eject_to_front` state because we currently only check for complete absence of paper. 
This PR adds transitions for when paper triggers some or all input sensors, allowing the state machine to exit `eject_to_front` state.
Note in these videos I have to manually stop the paper because the paper tray of the dev unit has less friction than the paper tray of the prod unit. On the dev unit, the paper will slide all the way out of the input and avoid tripping input sensors.
Before: when paper trips input sensors, state machine is stuck in `ejecting_to_front` state. …
=> transition from eject_to_front when paper is in input

apps/admin/frontend/src/components/live_check_button.tsx, apps/admin/frontend/src/screens/settings_screen.tsx, apps/mark-scan/backend/src/app.ts, apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/components/live_check_button.tsx, apps/mark-scan/frontend/src/pages/admin_screen.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/scan/frontend/src/components/live_check_button.tsx, apps/scan/frontend/src/screens/poll_worker_screen.test.tsx, libs/ui/src/live_check_modal.tsx
This PR rebrands Live Check ➡️ (Signed) Hash Validation and adds a Hash Validation button to VxMarkScan.
Note that I prepped this very quickly, adding istanbul ignores and only updating user-facing references to Live Check. Variable names and comments still refer to the feature as Live Check and not (Signed) Hash Validation. In a time crunch for the upcoming demo, but will be revisiting all this code soon when I complete the implementation of Signed Hash Validation.
https://github.com/votingworks/vxsuite/assets/12616928/3dd7f110-7f06-4cc4-94da-81b34248d471
_While polls are open_
https://github.com/votingworks/vxsuite/assets/12616928/6c762830-821c-4f35-91dd-426166d256cd
_Before polls open / After polls close_
=> Rebrand Live Check --> (Signed) Hash Validation and add Hash Validation button to VxMarkScan

apps/scan/backend/src/scanners/pdi/state_machine.ts
We don't actually want to have multiple active listeners at a time for scanner events. The listener at the root will send a state machine event that can be caught in any state. Registering an additional listener within a state will just create a duplicate state machine event. This hasn't been causing problems because we've been transitioning away from the states with listeners before that happens, but it still presents a risk and is unnecessary.
=> apps/scan: Only listen for scanner events at root

libs/converter-nh-accuvote/src/cli/encode_metadata.ts
Generate metadata QR codes for both live and test ballots.
=> feat(encode-metadata): make QR codes for both live and test ballots.

libs/converter-nh-accuvote/jest.config.js, libs/converter-nh-accuvote/src/convert/convert_election_definition_header.ts
Previously, we had only seen "Vote for no more than n" but now we're also seeing "Vote for up to n".
Manual test
=> v3.1 converter-nh-accuvote: Parse "Vote for up to n" contest description

apps/scan/backend/src/scanners/custom/custom_app_scan_shoeshine_mode.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts
Uses the feature flag added in #4870 (`REACT_APP_VX_ENABLE_SCAN_SHOESHINE_MODE`) to enable shoeshine mode for the Custom scanner.
https://github.com/votingworks/vxsuite/assets/530106/14d65768-0b13-4ba0-9f37-97abf0d93b16
Manual and automated tests
=> VxScan: Shoeshine mode for Custom scanner

libs/ballot-interpreter/src/hmpb-rust/debug.rs
- type parameters as accepting a slice rather than a `Vec` when we don't actually need the `Vec` methods
- don't take a reference and then call `into_iter` on the reference, just use `iter` directly
- use `zip`+`cycle` rather than `enumerate`+ternary
=> style: more idiomatic Rust

libs/ballot-interpreter/src/hmpb-rust/debug.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/layout.rs
Cherry pick of #4872 onto `main`
=> libs/ballot-interpreter: Create debug image for contest option layouts

apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, libs/pdi-scanner/examples/scan_forever.rs, libs/pdi-scanner/src/rust/client.rs, libs/pdi-scanner/src/rust/main.rs, libs/pdi-scanner/src/ts/demo.ts, libs/pdi-scanner/src/ts/scanner_client.test.ts, libs/pdi-scanner/src/ts/scanner_client.ts
Task: #4825 
Previously, if you timed it just right, it was possible to trick the PDI scanner into thinking it was scanning one long ballot by inserting two ballots in quick succession back to back. In this case, the first ballot would be ejected out of the rear of the scanner into the ballot box before the issue would be detected by the interpreter.
To prevent this, we set the max paper length setting provided by the PDI scanner. After scanning (approximately) this length, the PDI scanner declares a jam and stops the motors. I found that the optimal length for stopping the motors soon enough to prevent the first ballot from being ejected was 0.5in shorter than the actual length of the ballot.
Before
https://github.com/votingworks/vxsuite/assets/530106/e41ee457-4bd1-4639-850d-a9c52efefa36 …
=> apps/scan: Set PDI scanner paper length to prevent back-to-back ballots

libs/pdi-scanner/src/rust/client.rs
I mistyped this condition when implementing the PR feedback from https://github.com/votingworks/vxsuite/pull/4843. Ideally, we'd have a test to make sure this doesn't happen, but I haven't figured out how to test the complex behavior of the Rust code yet. For now, I'd just like to fix this.
=> libs/pdi-scanner: Bugfix for typo from eject pause feature PR

libs/ui/src/hooks/use_available_languages.test.tsx, libs/ui/src/hooks/use_current_language.test.tsx
Had these shortened assertion timeouts for local debugging and accidentally committed in a previous PR. Removing to fix the [flakes](https://votingworks.slack.com/archives/CEL6D3GAD/p1713485245450899) they're causing in circleci.
=> FIX(ui): remove accidental commit of shortened test timeouts

apps/design/backend/src/candidate_rotation.ts, apps/design/frontend/src/contests_screen.test.tsx, libs/eslint-plugin-vx/src/rules/gts_func_style.ts, libs/eslint-plugin-vx/src/rules/gts_no_foreach.ts, libs/hmpb/src/render_ballot.tsx, libs/printing/src/printer/mocks/memory_printer.ts, libs/ui/src/set_clock.tsx
`a.at(-1)` is nicer than `a[a.length - 1]`. Maybe less self-documenting than `iter(a).last()`, but more platform-native.
=> refactor: use `Array::at` to access last element

apps/mark-scan/accessible-controller/src/port.rs
The controller daemon sends a health check command to the controller and expects a response back. If buttons on the controller have been pressed before the daemon has started up, the in-buffer will have data in it. That data is returned alongside the health check response. The concatenated response is unparsable by the daemon and crashes.
This PR clears the in-buffer before sending the health check command to avoid the problem.
N/A
Manually tested both cases on hardware. No automated tests since this implementation is likely going away soon.
* starting daemon without any buttons pressed
* pressing buttons on controller and then starting daemon
=> clear controller in-buffer before echo command

apps/mark-scan/backend/src/app.diagnostics.test.ts
Increases the time to wait for chromium to spin up when rendering a ballot for the paper handler diagnostic. Hopefully addresses flaky tests.
N/A
N/A
=> increase chromium spin up timeout

apps/scan/backend/package.json
We had previously limited `maxWorkers` to 2 to prevent flakiness, but I think now it may actually be causing flakiness. I don't have a good understanding of why, but there are a lot of tests that seem to be timing out on CI, which makes me think that maybe they are running much more slowly than we expect. I wouldn't necessarily expect increasing the number of workers to help with that, but maybe the machine is somehow getting bogged down by not leveraging all of its cores?
N/A
I reran the tests in CI on this branch 10 times and the apps/scan/backend tests passed every time (and executed faster than they used to)
=> apps/scan/backend: Increase maxWorkers to match other tests

apps/scan/backend/src/scanners/pdi/state_machine.ts, libs/ballot-interpreter/package.json, libs/ballot-interpreter/src/index.ts, libs/ballot-interpreter/src/interpret.ts, libs/ballot-interpreter/src/interpret_bmd_ballots.test.ts, libs/ballot-interpreter/src/interpret_nh_hmpb.test.ts, libs/ballot-interpreter/src/interpret_vx_hmpb.test.ts, libs/ballot-interpreter/src/types.ts, libs/ballot-interpreter/src/validation.test.ts, libs/ballot-interpreter/src/validation.ts, libs/types/src/system_settings.ts, pnpm-lock.yaml
Related to https://github.com/votingworks/vxsuite/issues/4622
Adding an optional `allowOfficialBallotsInTestMode` system setting -- when enabled, always interpret official ballots as test-mode ballots when scanning in test mode.
- New unit tests for the `normalizeBallotMode` validation helper and test cases to verify it's getting used in each code path (BMD ballots, NH HMPBs, Vx HMPBs).
- Existing tests as regression guard
- ~[ ] I have added the "user_facing_change" label to this PR to automate an …
=> [VxScan] Optionally allow scanning official ballots in test mode

apps/mark-scan/frontend/src/app_states.test.tsx, apps/mark/frontend/src/apimachine_config.test.tsx, apps/mark/frontend/src/app_card_unhappy_paths.test.tsx, apps/mark/frontend/src/app_cardless_voting.test.tsx, apps/mark/frontend/src/app_contest_candidate_no_party.test.tsx, apps/mark/frontend/src/app_contest_ms_either_neither.test.tsx, apps/mark/frontend/src/app_contest_multi_seat.test.tsx, apps/mark/frontend/src/app_contest_single_seat.test.tsx, apps/mark/frontend/src/app_contest_write_in.test.tsx, apps/mark/frontend/src/app_contest_yes_no.test.tsx, apps/mark/frontend/src/app_election_package_config.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/app_polls_flows.test.tsx, apps/mark/frontend/src/app_quit_on_idle.test.tsx, apps/mark/frontend/src/app_replace_election.test.tsx, apps/mark/frontend/src/app_setup_errors.test.tsx, apps/mark/frontend/src/app_test_mode.test.tsx, apps/mark/frontend/src/lib/gamepad.test.tsx, apps/mark/frontend/src/pages/admin_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.test.tsx
Most of our apps don't use URL routing (except `admin`), so this is useless and produces JSDOM warnings:
```
console.error
Error: Not implemented: navigation (except hash changes)
at module.exports (/home/parallels/code/vxsuite/node_modules/.pnpm/jsdom@20.0.1_canvas@2.11.2/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
at navigateFetch (/home/parallels/code/vxsuite/node_modules/.pnpm/jsdom@20.0.1_canvas@2.11.2/node_modules/jsdom/lib/jsdom/living/window/navigation.js:77:3)
at exports.navigate (/home/parallels/code/vxsuite/node_modules/.pnpm/jsdom@20.0.1_canvas@2.11.2/node_modules/jsdom/lib/jsdom/living/window/navigation.js:55:3)
at LocationImpl._locationObjectNavigate (/home/parallels/code/vxsuite/node_modules/.pnpm/jsdom@20.0.1_canvas@2.11.2/node_modules/jsdom/lib/jsdom/livi …
```
=> test: remove unnecessary `href = '/';`

libs/pdi-scanner/README.md
Installing these rules means we can avoid the `chmod`/`chown` shenanigans we've been doing up to this point.
=> docs: add `udev` rules for PDI scanner

libs/hmpb/src/renderer.tsx
I had tried out using a MutationObserver to wait for DOM content to load after being inserted (https://github.com/votingworks/vxsuite/pull/4957). However, the same issue occurred again, where some content was still changing after the observer fired. I think it only appeared to work by delaying things slightly without actually solving the problem.
Here is a new approach where we use requestAnimationFrame to wait for the next browser repaint. This seems to work, though similarly to last time I can't be 100% confident that it's solving the problem, so we'll need to wait and see.
N/A
Manual testing with an example that was buggy before, and now works.
=> libs/hmpb: Rework fix to wait for HTML to load during rendering

libs/ballot-interpreter/src/hmpb-rust/timing_mark_metadata.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks.rs, libs/types-rs/src/geometry.rs
- replace `let Some(_) = _ else { return None; }` with `let _ = _?;` (clippy lint)
- remove `enumerate()` since the index goes unused (clippy lint)
- improve legibility of `intersection_of_lines` call sites by using an enum
n/a
=> refactor(ballot-interpreter): improve code legibility

libs/ballot-interpreter/package.json, libs/ballot-interpreter/src/hmpb-rust/debug.rs, libs/ballot-interpreter/src/hmpb-rust/image_utils.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks.rs, libs/ballot-interpreter/src/hmpb-ts/types.ts, libs/types-rs/src/f32_newtype.rs, libs/types-rs/src/geometry.rs, libs/types-rs/src/lib.rs, pnpm-lock.yaml
Adds more debug information to the partial timing mark debug image and includes more specific reasons why the timing marks could not be found. This should not change the behavior of interpretation at all, just output more debug info along with some minor refactors.
Refs #4578
=> feat(ballot-interpreter): add more debug information for partial timing marks

apps/scan/frontend/Makefile
The first issue that I encountered while trying to run a production image on the VxScan v4 build0: The `pdictl` binary (our PDI driver) was missing. This PR makes sure that the binary is built in production.
=> Make sure pdictl binary is built in production

apps/central-scan/backend/schema.sql, apps/central-scan/backend/src/app.diagnostics.test.ts, apps/central-scan/backend/src/app.scanning.test.ts, apps/central-scan/backend/src/diagnostic.ts, apps/central-scan/backend/src/end_to_end_bmd.test.ts, apps/central-scan/backend/src/end_to_end_hmpb.test.ts, apps/central-scan/backend/src/fujitsu_scanner.test.ts, apps/central-scan/backend/src/fujitsu_scanner.ts, apps/central-scan/backend/src/importer.ts, apps/central-scan/backend/src/loop_scanner.test.ts, apps/central-scan/backend/src/loop_scanner.ts, apps/central-scan/backend/src/store.test.ts, apps/central-scan/backend/src/store.ts, apps/central-scan/backend/test/util/mocks.ts, libs/backend/src/cast_vote_records/build_cast_vote_record.test.ts, libs/backend/src/cast_vote_records/build_cast_vote_record.ts, libs/backend/src/cast_vote_records/export.ts
When an imprinter module is attached to the scanner and you scan a batch, a new BallotAuditID in the form <Batch_ID>_<Sequence> will be imprinted on each sheet and exported in the CVR, where <Sequence> is a sequential ID starting with 0000, then 0001, etc. The largest scanner we use in the central system scans in max batches of 300 so 4 digit should be plenty for this ID. The ID gets reset on each subsequent batch, and is notably different from the BallotSequenceIdx currently included in the exported CVR in that it increments on rejected sheets, and all sheets, rejected ballots, unreadables, etc. are imprinted. 
BallotAuditId is an existing CDF field we are not currently using.
When an imprinter module is not attached to the scanner everything behaves identically to how to does today. …
=> Add imprinting to the central scanner 

apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/pages/admin_screen.test.tsx, apps/mark-scan/frontend/src/pages/admin_screen.tsx
[
](https://github.com/votingworks/vxsuite/issues/3510)
Copying how we do it in VxScan eject the usb when unconfiguring as an election manager so we don't automatically reconfigure. 
https://github.com/votingworks/vxsuite/assets/14897017/87b8fc72-d82d-478c-8c85-cca87edb4ed5
Tested unconfiguring manually with and without usb mounted. 
Ran tests
=> Eject usb when unconfiguring as election manager

apps/mark-scan/backend/src/app.auth.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts
(Tangentially) related to https://github.com/votingworks/vxsuite/issues/4812
Noticed while working on the ballot re-insertion flow that we're not yet cleaning up the state machine when a poll worker resets the ballot/voter session. Adding a state machine `reset()` API method that gets called when ending a voter session - resets the state machine context and moves to `not_accepting_paper` to make sure any existing paper is ejected.
- Updated unit tests
- Tested locally with mock paper handler
- ~[ ] I have …
=> [MarkScan] Reset state machine when ending voter session

libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/yes_no_contest.tsx, libs/ui/src/accessible_controllers/navigation.test.tsx, libs/ui/src/accessible_controllers/navigation.ts, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/4927 
Because of the way React automatically handles focusing of Modals using the autofocus html5 attribute on a button inside a Modal does not work and the "Okay" to dismiss the overvote warning modal does not get properly autofocused. Instead we have to manually focus the button ref in order for it to autofocus as implemented here. Note the onAfterOpen was not triggering at the right time in the Modal component unless I passed through the isOpen parameter I know we don't otherwise use. 
Manually triggered overvotes saw "okay" focus
=> Fix bug to autofocus okay button on overvote modal

apps/scan/frontend/src/screens/scan_warning_screen.test.tsx, libs/backend/src/cast_vote_records/build_report_metadata.ts, libs/ballot-encoder/tsconfig.json, libs/eslint-plugin-vx/package.json, libs/mark-flow-ui/src/components/candidate_contest.test.tsx, libs/monorepo-utils/package.json, libs/ui/src/modal.test.tsx, package.json, pnpm-lock.yaml, script/package.json
See the release notes here: https://devblogs.microsoft.com/typescript/announcing-typescript-5-5/
I updated the few places I could easily find where we can benefit from TS v5.5's new ability to automatically infer type narrowing functions (e.g. better `filter` type narrowing). We also may benefit from a tooling perspective in the future if we turn on `isolatedDeclarations`, but this isn't straightforward to do right now.
=> chore(deps): update to `typescript` v5.5.3

apps/mark-scan/frontend/src/lib/assistive_technology.ts, apps/mark-scan/frontend/src/pages/validate_ballot_page.tsx, apps/mark/frontend/src/lib/gamepad.ts, libs/mark-flow-ui/src/pages/review_page.tsx, libs/ui/src/accessible_controllers/navigation.test.tsx, libs/ui/src/accessible_controllers/navigation.ts, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/4930
In order to prevent pressing the right arrow too quickly and accidental casting ballots this PR makes the right arrow on the review screen simply focus on the "Print my Ballot" button rather then clicking the button. So the user will now need to press the right button and the select button, unless they are using the touch screen and just press the button. I added an additional audio instruction to confirm your selections and print to the Print My Ballot when focused as well. 
Manually Tested with keyboard. Ran tests for navigation helper function changes.
=> Prevent accidental ballot casting with accessible controller 

apps/mark-scan/frontend/src/pages/inserted_invalid_new_sheet_screen.test.tsx, apps/mark-scan/frontend/src/pages/inserted_invalid_new_sheet_screen.tsx, apps/mark-scan/frontend/src/pages/inserted_unreadable_ballot_screen.tsx, apps/mark-scan/frontend/src/pages/inserted_wrong_election_ballot_screen.tsx, apps/mark-scan/frontend/src/pages/inserted_wrong_precinct_ballot_screen.tsx, apps/mark-scan/frontend/src/pages/inserted_wrong_test_mode_ballot_screen.test.tsx, apps/mark-scan/frontend/src/pages/inserted_wrong_test_mode_ballot_screen.tsx
https://github.com/votingworks/vxsuite/issues/4812
Adding error screens for the upcoming changes to scan new sheets at the start of the session.
These are shown if a newly inserted sheet contains a valid BMD ballot for a different election/precinct/ballot mode, or contains a BMD ballot with an unreadable QR code.
- Tests cases for UI branching logic 
- Manual verification locally
=> [MarkScan] UI Screens for Invalid New Sheet Insertion

libs/types-rs/src/geometry.rs
This was accidentally removed (https://github.com/votingworks/vxsuite/pull/4999#pullrequestreview-2164039558).
=> docs(ballot-interpreter): re-add missing comment

apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/app_cardless_voting.test.tsx, apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/app_root.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/pages/ballot_ready_for_review_screen.test.tsx, apps/mark-scan/frontend/src/pages/ballot_ready_for_review_screen.tsx, apps/mark-scan/frontend/src/pages/inserted_preprinted_ballot_screen.test.tsx, apps/mark-scan/frontend/src/pages/inserted_preprinted_ballot_screen.tsx, apps/mark-scan/frontend/src/pages/loading_new_sheet_screen.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx
Related to https://github.com/votingworks/vxsuite/issues/4812
Enabling support (currently behind the `MARK_SCAN_ENABLE_BALLOT_REINSERTION` feature flag) for re-inserting a printed ballot after a voter session has ended or timed out.
- Adding a new  Poll Worker screen section to bypass ballot style selection (pre-printed ballots will still be accepted after ballot style selection, though).
- Hooking up the new state machine states to poll-worker-facing screens.
- Updating load paper prompt
(Full flow [here](https://www.figma.com/design/hvboQDWXqE1PbpGbWfb9iU/%5BVxMarkScan%5D-Printed-Ballot-Scan%2FRe-Scan-Flows?node-id=2-78&t=l4h4NmR73jzOW8Zz-1)):
- New unit test cases
- Manual testing with mock paper handler (will need to verify fully on real VSAP later) …
=> [MarkScan] Implement pre-printed ballot insertion in PollWorkerScreen

libs/backend/src/system_call/get_audio_info.ts
This PR uses a wrapper script for the `pactl` command with sudo permissions. This is necessary because `pulseaudio` runs unique instances per user. The `vx-ui` user is responsible for our production X session and accompanying audio configuration. To determine if headphones are present, the `vx-services` user needs to access the `vx-ui` session, and this approach makes that possible.
=> switch to pactl wrapper with sudo

apps/scan/frontend/Makefile
https://github.com/votingworks/vxsuite/issues/5004
Fixes the something went wrong screen when printing a test page in production. There is a custom step in the pnpm build for scan-backend that copies the printed pdf to the build directory. This ensures that the backend is build through that command and the pdf gets copied over, making sure it is there when printing needs to occur. 
N/A
Tested on VxDev
=> Fix something went wrong printing test page

apps/mark-scan/fai-100-controller/src/commands.rs, apps/mark-scan/fai-100-controller/src/fai_100_controllerd.rs
Rather than accessing the `MARK_SCAN_WORKSPACE` env var when we need it, read it upfront using `clap`. This has the additional effect of allowing it to be passed as a CLI arg instead: `--mark-scan-workspace /path/to/workspace`.
Also, changes `write_pat_connection_status` to improve readability by accepting the status directly rather than passing a boolean.
=> refactor(fai-100-controller): let `clap` handle MarkScan workspace

libs/backend/src/intermediate-scripts/power-down, libs/backend/src/intermediate-scripts/reboot, libs/backend/src/intermediate-scripts/reboot-to-bios, libs/backend/src/intermediate-scripts/set-clock, libs/backend/src/intermediate_scripts.ts, libs/backend/src/system_call/api.test.ts, libs/backend/src/system_call/power_down.ts, libs/backend/src/system_call/reboot.ts, libs/backend/src/system_call/reboot_to_bios.ts, libs/backend/src/system_call/set_clock.test.ts, libs/backend/src/system_call/set_clock.ts
Issue links: https://github.com/votingworks/vxsuite/issues/4904 + https://github.com/votingworks/vxsuite/issues/5003 + https://github.com/votingworks/vxsuite/issues/4899
When we moved the system-call API from `kiosk-browser` to `libs/backend`, we missed a few pieces of configuration for production, namely some `sudo` calls and the relevant `sudoers` file update to allow those `sudo` calls to be made without having to provide the `sudo` password.
The result has been that setting the clock and interacting with reboot buttons cause VxSuite apps to crash in production.
This PR, paired with https://github.com/votingworks/vxsuite-complete-system/pull/384, remedies this.
Reproduced the crashes on a production-imaged non-locked-down VxAdmin, then copied updated source code over, rebuilt, and …
=> Fix libs/backend system calls in prod

libs/ballot-interpreter/package.json, pnpm-lock.yaml
This fixes `pnpm build` in `ballot-interpreter` when using Rust > 1.76.
=> fix(ballot-interpreter): make `pnpm build` work with newer Rust versions

libs/custom-paper-handler/src/driver/coders.ts, libs/custom-paper-handler/src/driver/driver.test.ts, libs/custom-paper-handler/src/driver/driver.ts, libs/custom-scanner/src/mocks/web_usb_device.ts
Issue https://github.com/votingworks/vxsuite/issues/5040
See explanation of issue in https://github.com/votingworks/vxsuite/pull/4846
We used to handle unexpected data sent from paper handler to host in `transferInAcknowledgement`. That function is called by most, but not all, commands. It has 2 jobs:
1. read data from generic in buffer
2. parse and handles a simple success/fail response code
This worked because printing was always followed by a call to `setScanDirection`, which does call `transferInAcknowlegdement`.
Recently we removed the call to `setScanDirection`, so the next call after printing that reads from the generic in buffer is `scan`. This call does not expect an acknowledgement. Rather, it expects a 16-byte header and a subsequent large block of scan data. Therefore `scan` …
=> Handle `realtime status transmission` response in `transferInGeneric`

apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/frontend/src/app_root.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/ballot_reinsertion_flow.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark-scan/frontend/src/voter_flow.tsx
Closes https://github.com/votingworks/vxsuite/issues/4812
Last few loose ends on the ballot re-insertion flow:
1. Making sure we keep rendering the re-insertion screens when a Poll Worker logs in during the flow (we could further improve this by creating Poll-Worker-specific screens, but this seems fine for now).
2. Adding the new states for initial sheet insertion to the branched logic for resetting the session/state machine when the Poll Worker card is removed too early.
https://github.com/user-attachments/assets/c6ff4848-400a-4d4d-8112-d21cf33efe3c
https://github.com/user-attachments/assets/742e7d87-71a2-4d93-9167-89b939dc8bf4
https://github.com/user-attachments/assets/eee3b01d-827f-4566-be02-9b27823d6700
- State machine + UI test cases
- Manual testing with mock paper handler
- ~[ ] I …
=> [MarkScan] Handle ballot re-insertion flow edge cases

apps/scan/backend/src/printing/printer.ts, libs/dev-dock/README.md, libs/dev-dock/backend/package.json, libs/dev-dock/backend/src/dev_dock_api.ts, libs/dev-dock/backend/tsconfig.build.json, libs/dev-dock/backend/tsconfig.json, libs/dev-dock/frontend/jest.config.js, libs/dev-dock/frontend/package.json, libs/dev-dock/frontend/src/api_client.tsx, libs/dev-dock/frontend/src/dev_dock.test.tsx, libs/dev-dock/frontend/src/dev_dock.tsx, libs/dev-dock/frontend/src/fujitsu_printer_mock.tsx, libs/dev-dock/frontend/tsconfig.build.json, libs/dev-dock/frontend/tsconfig.json, libs/fujitsu-thermal-printer/.gitignore, libs/fujitsu-thermal-printer/package.json, libs/fujitsu-thermal-printer/src/env.d.ts, libs/fujitsu-thermal-printer/src/index.ts, libs/fujitsu-thermal-printer/src/mocks/file_printer.test.ts, libs/fujitsu-thermal-printer/src/mocks/file_printer.ts, libs/fujitsu-thermal-printer/src/mocks/memory_printer.test.ts, libs/fujitsu-thermal-printer/src/mocks/memory_printer.ts, libs/fujitsu-thermal-printer/src/printer.ts, libs/fujitsu-thermal-printer/src/status.ts, libs/fujitsu-thermal-printer/src/types.ts, libs/fujitsu-thermal-printer/tsconfig.build.json, libs/fujitsu-thermal-printer/tsconfig.json, libs/printing/src/printer/mocks/file_printer.test.ts, libs/printing/src/printer/printer.ts, pnpm-lock.yaml
Adds mocking capabilities for the Fujitsu thermal printer used in our V4 hardware. I think this is important as we will have to iterate on the UX for the printer while not everyone has the hardware and some hardware states are difficult to reach. 
Uses the same file-based mock as auth and standard printers.
The dev dock is getting pretty big - I would be in favor of making the card selection a simple drop down to take up less space and, in general, shoot for a lo-fi UX. I want to be able to iterate on mocks - which might vary across products - without getting hung up on layout.
https://github.com/user-attachments/assets/b2880632-af3f-4c89-a07c-897a0681fcfb
Automated tests added and manually tested.
=> Mock Fujitsu Printer

apps/admin/frontend/src/screens/write_ins_adjudication_screen.test.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx
https://github.com/votingworks/vxsuite/issues/4714
Pins the "Mark write in as undervote" (renamed from invalid) and "add new candidate" buttons on the WIA screen when there are enough custom candidates that it is scrolling. Based on feedback from the spring town elections.
https://github.com/votingworks/vxsuite/assets/14897017/a9440a24-70c2-434d-83db-ba28ad11a1ff
Manually used WIA flow when there were enough options to create scroll.
=> Polish on WIA Screen

libs/custom-paper-handler/src/driver/mock_driver.ts
MarkScan run with a mock paper handler was crashing because the scan data returned had no height. The mock ImageData returned by the mock driver was given a width of 2 and no height; height is computed by dividing the length of pixel data by width, so we can either provide 4 total pixels' worth of data or explicitly set width (and height, while we're at it) to 1.
No user facing change
Manually reproduced issue and verified fix.
=> mock paper handler driver: give mock ImageData height

libs/mark-flow-ui/src/hooks/use_session_settings_manager.test.tsx, libs/mark-flow-ui/src/hooks/use_session_settings_manager.ts, libs/ui/src/app_base.tsx
Adds logic for resetting the audio-only mode flag when a voter session resets either after casting a ballot or when an election official authenticates. It is reset to its previous state when returning to a voter session. 
Started voter session , made a vote, Turned on audio-only mode, insertted pollworker card saw audio-only mode clear and pollworker text render, removed card, saw return to audio-only mode
Started voter session, turned on audio-only mode, finished casting a ballot, saw screen reset back to insert card
=> Reset Audio-Only Mode properly

.circleci/config.yml, Cargo.lock, Cargo.toml, apps/mark-scan/fai-100-controller/Cargo.toml, apps/mark-scan/fai-100-controller/Makefile, apps/mark-scan/fai-100-controller/README.md, apps/mark-scan/fai-100-controller/src/commands.rs, apps/mark-scan/fai-100-controller/src/fai_100_controllerd.rs, apps/mark-scan/fai-100-controller/src/usb_device.rs, apps/mark-scan/fai-100-controller/src/virtual_keyboard.rs, vxsuite.code-workspace
Solves https://github.com/votingworks/vxsuite/issues/4960 and https://github.com/votingworks/vxsuite/issues/4961
Adds support for the FAI-100 USB device which encompasses both ATI controller and sip & puff input on the BMD 150. The implementation is forked from the BMD 155 controller daemon.
https://github.com/user-attachments/assets/6c7447cb-fd44-487b-8f04-4afdb8d663f8
https://github.com/user-attachments/assets/24df0b63-03bf-4256-bd06-59fc4c8bc5fe
- rewrote existing tests for BMD 155 controller
- added sip and puff tests
=> Support controller and sip & puff on BMD 150 hardware

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts
The old approach took the value on the last iteration but discarded it if there weren't any more requested. This version fixes that.
=> fix(basics): ensure `take` doesn't take beyond

libs/backend/src/cast_vote_records/referenced_files.ts
This was accidentally added in https://github.com/votingworks/vxsuite/pull/5065.
=> fix(backend): remove `console.log`

apps/scan/frontend/src/components/voter_settings_manager.test.tsx, apps/scan/frontend/src/components/voter_settings_manager.tsx
https://github.com/votingworks/vxsuite/issues/5069
Adds language reset logic alongside display settings reset logic for VxScan, now matching how Mark works.
Changed voter display/language - inserted pollworker card - saw both reset
Changed voter display/language - inserted rejected ballot - saw both reset
Changed voter display/language - inserted succesfull ballot - saw both reset
=> Reset language with voter display settings on vxscan

apps/scan/frontend/src/screens/unconfigured_election_screen_wrapper.tsx
https://github.com/votingworks/vxsuite/issues/4967
The issue was that the configureMutation call was never being made previously if the usb was mounted BEFORE the election manager card was inserted. Causing it to hang forever here and never show the failure screens when the usb didn't have the right election package for the election manager card. This makes it so that its triggered properly if the usb is mounted either before or after the EM card is authenticated. 
For some reason the happy path when there was an election package on the card always worked properly even if the usb was previously mounted which I don't totally understand. 
Manually Tested
- Mount usb and then insert EM card - in success case and in error cases saw correct behavior 
- Insert EM card then mount usb - in …
=> Trigger configuration from usb properly on EM screen

apps/mark-scan/frontend/src/app_root.tsx, apps/mark/frontend/src/app_root.tsx, libs/auth/src/inserted_smart_card_auth.test.ts, libs/auth/src/inserted_smart_card_auth.ts, libs/mark-flow-ui/src/hooks/use_session_settings_manager.test.tsx, libs/mark-flow-ui/src/hooks/use_session_settings_manager.ts, libs/test-utils/src/auth.ts, libs/types/src/auth/auth.ts
Updates the Mark session resetting logic to instead of checking for if there are selected votes to determine if the pollworker card had deactivated and started a new voter session instead keeping track of a unique id per session that is checked. 
Without Selecting Votes - Activate voter session, change language/display, Insert pollworker card - see temporary reset, remove pollworker card - see display/language are still what I changed to 
With Selecting Votes - Activate voter session, change language/display, Insert pollworker card - see temporary reset, remove pollworker card - see display/language are still what I changed to 
Without Selecting Votes - Activate voter session, change language/display, Insert pollworker card - see temporary reset, deactivate session, start new voting …
=> Reset session properly in mark

libs/pdi-scanner/src/rust/scanner.rs
The PDI scanner doesn't seem to stream as it receives image data from its sensors, so it sends the data all in one go if it can. This reduces the number of incoming transfers for the image data to just one, which should reduce the odds of any image corruption that might happen if e.g. a packet is dropped. It might also make it a tiny bit faster, but I doubt the effect would be noticeable.
This change was suggested by PDI's engineering team. See the email thread from @arsalansufi dated 2024-07-15. See [this Slack thread](https://votingworks.slack.com/archives/CEL6D3GAD/p1721854880450379) for exploration related to this.
=> fix(pdi-scanner): use a larger buffer when receiving

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
When it only makes sense to call certain `iter` methods based on the contained type `T`, the better approach is to use an explicit type for `this` in the method definition rather than a ternary type resulting in `unknown` when the type doesn't match. This way actually gives us TypeScript errors and is clearer.
Automated testing, including new tests to ensure the error is triggered appropriately.
=> fix(basics): improve types of conditional `iter` methods

apps/admin/backend/src/store.ts, apps/central-scan/backend/src/store.ts, apps/scan/backend/src/store.ts, libs/db/src/client.test.ts, libs/db/src/client.ts
For situations where we insert many records over and over (i.e. CVRs) this could speed things up a lot.
=> feat(db): allow using prepared statements

libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/test/fixtures/interpretations.ts
https://github.com/votingworks/vxsuite/issues/5100
Includes images for BMD ballots with write in when exporting from a central scan minimal export (i.e. a regular cvr save, non-minimal is when you save backup) 
Ran tests
Tested on VxDev through central scan and admin import and viewed images in WIA
=> Export images with write-ins on central scanner

libs/dev-dock/frontend/src/dev_dock.tsx
I noticed that most of the time, the dev dock wasn't actually hidden fast enough to be excluded from the screenshot, so just added a little delay.
=> dev-dock: Delay before screenshotting to ensure dev dock is hidden

apps/admin/frontend/jest.config.js, apps/admin/frontend/src/screens/election_screen.test.tsx, apps/admin/frontend/src/screens/election_screen.tsx
I noticed that we were accidentally showing the abbreviated election date month name, which was unnecessary since there's plenty of space to show the full month name. Also deemphasized the configuration timestamp since it's not as important.
Before
After
Added new tests for election screen component
=> apps/admin: Format election date with full month name

apps/mark-scan/backend/src/app.auth.test.ts, apps/mark-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/custom-paper-handler/types.ts, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx
Currently if you insert the pat device while on the pollworker screen, or insert a PW card with a pat device connected you end up on a white screen. This PR fixes that and handles those cases to just go to the pollworker screen as expected. 
Connected/Disconnected PAT at various moments in PW screen flows and saw no impact, saw PAT test flow come up once voter session started (if still plugged in) as expected
Inserted PW card again once in PAT connection flow and saw PW screen display as expected.
=> Ignore Pat Connection on Pollworker Screen

apps/mark-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/globals.ts, apps/mark-scan/backend/src/pat-input/connection_status_reader.test.ts, apps/mark-scan/backend/src/pat-input/connection_status_reader.ts, apps/mark-scan/backend/src/pat-input/constants.ts, apps/mark-scan/backend/src/server.ts
https://github.com/votingworks/vxsuite/issues/4961
Updates the mark-scan backend to read from the status file that the FAI 100 daemon writes to in [this change](https://github.com/votingworks/vxsuite/pull/4986/files#diff-c62233c817bd6e84b930c564731636d8f243fd9630683a4f112cfdcfeba53b6aR65).
The format of this file is the same as the BMD 155 implementation: a single ASCII character `0` or `1` indicating connection status of a PAT device. `0` means device is connected, `1` means no device is connected. This is the interface defined by the BMD 155 GPIO sysfiles so I kept it consistent despite the divergence from typical boolean values.
VxMarkScan uses this value to know whether a PAT device is connected and by extension when to launch the PAT calibration flow for voters or during the system …
=> read FAI 100 PAT status

libs/printing/src/render.tsx, libs/ui/src/bmd_paper_ballot.tsx
Adds a comment explaining dot overflow when printing at exactly 8".
N/A
N/A
N/A not user facing
=> comment on overflow when using exactly 8in width

libs/ui/src/button.tsx
Related to https://github.com/votingworks/vxsuite/issues/5033
We noticed in manual tests that touch-based "click" events don't trigger audio in the same way that "click" events with the accessible controller do.
This change fixes our handling of touch events in the `<Button>` component by triggering an actual `click` event on the button when we detect a touch-based button press. This allows the click/focus-based screen reader to properly detect button presses.
__Context:__ 
Our `<Button>` component overrides the default browser handling of touch taps by intercepting `touchStart` and `touchEnd` and treating the pair as a button press even if the user's finger moved slightly in-between. It then triggers the `onPress` callback directly and blocks the default browser handling, which prevents …
=> [fix/5033] Fix inconsistent audio feedback on touch events

libs/ui/src/ui_strings/ui_string_screen_reader.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5087
When entering audio-only mode after muting audio, the screen reader is first unmuted, then the voter is returned to the ballot, but there was a race condition where the initial audio on the ballot screen was triggered before the screen reader's event handlers were re-registered after the mute change.
Updating the event listener registration to only happen once per app load - removing the React effect dependency on the audio mute state to avoid having the listeners removed and re-added every time we mute/unmute.
https://github.com/user-attachments/assets/35fb3939-a0eb-4e34-a38e-8757615e5514
https://github.com/user-attachments/assets/276a2b87-dffd-4df6-a21c-c4a8909d7b6b
- Manual …
=> Fix screen reader missing audio triggered immediately after unmute

apps/mark-scan/frontend/src/lib/assistive_technology.ts, libs/mark-flow-ui/src/components/contest_screen_layout.tsx, libs/ui/src/with_scroll_buttons.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5000
Contest button UX fixes:
- Add a bit of padding to avoid the focus outline getting partially cut off
- Prevent the browser from scrolling in response to the up/down arrow keys, since we're using those to tab around.
https://github.com/user-attachments/assets/283a45a4-f91a-4cb6-838d-fdbd4e7d3467
https://github.com/user-attachments/assets/d4d6b08c-9298-446b-881a-1fdfbc970ce3
- Manual
=> [VxMark] Prevent first contest button's top outline getting cut off

libs/ui/src/ui_strings/audio_context.test.tsx, libs/ui/src/ui_strings/audio_context.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5034
Updating audio context logic to leave audio settings intact when re-enabling audio after disabling.
- Updated unit test
- Manual verification
=> [Mark] Persist audio settings when enabling & re-enabling audio

libs/monorepo-utils/package.json
This isn't used and references a shell script that doesn't exist. Presumably copied from `libs/fixtures/package.json`.
=> chore(monorepo-utils): remove broken script

libs/types/src/__snapshots__/election.test.ts.snap, libs/types/src/cdf/ballot-definition/convert.test.ts, libs/types/src/cdf/ballot-definition/convert.ts, libs/types/src/cdf/ballot-definition/extract_cdf_ui_strings.test.ts, libs/types/src/cdf/ballot-definition/fixtures.ts, libs/types/src/cdf/ballot-definition/index.ts, libs/types/src/cdf/ballot-definition/vx-schema.json, libs/types/src/election.test.ts, libs/types/test/cdf_conversion_helpers.ts, libs/ui/src/seal.test.tsx, libs/ui/src/seal.tsx
Closes: #4953 
Updates our support for the ballot definition CDF to be strictly compatible with NIST's CDF by removing custom extension fields that we added. Instead, we either use a reasonable default or disable the behavior that was supported by each custom field (details in commits).
VxAdmin and VxMarkScan with no seal
Updated existing tests, manually tested
=> Strict ballot definition CDF

apps/central-scan/backend/src/importer.test.ts, apps/central-scan/backend/src/importer.ts, apps/mark-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/test/ballot_helpers.ts, apps/mark-scan/backend/test/setup_custom_matchers.ts, apps/scan/backend/jest.config.js, apps/scan/backend/src/interpret.test.ts, apps/scan/backend/src/interpret.ts, apps/scan/backend/src/scanners/custom/custom_app_scan.test.ts, apps/scan/backend/src/scanners/custom/custom_app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/src/scanners/shared.ts, libs/ballot-interpreter/benchmarks/interpret_hmpb.bench.ts, libs/ballot-interpreter/src/__snapshots__/interpret_bmd_ballots.test.ts.snap, libs/ballot-interpreter/src/__snapshots__/interpret_nh_hmpb.test.ts.snap, libs/ballot-interpreter/src/interpret.ts, libs/ballot-interpreter/src/interpret_all_bubble_ballot.test.ts, libs/ballot-interpreter/src/interpret_and_save_files.test.ts, libs/ballot-interpreter/src/interpret_bmd_and_hmp_ballots.test.ts, libs/ballot-interpreter/src/interpret_bmd_ballots.test.ts, libs/ballot-interpreter/src/interpret_nh_hmpb.test.ts, libs/ballot-interpreter/src/interpret_vx_hmpb.test.ts, libs/ballot-interpreter/src/save_images.test.ts, libs/ballot-interpreter/src/save_images.ts, libs/ballot-interpreter/test/helpers/interpretation.ts, libs/image-utils/src/image_data.test.ts, libs/image-utils/src/image_data.ts
Previously we were writing both front & back images to disk twice: once before interpretation (as a kind of staging area, I guess?) and once after. This removes the first write (and the subsequent read+decode). In addition, this ensures that the PNG encoding (which is the slowest part of saving the images) happens in parallel.
Testing on my Core i5, I'm seeing the time spend just encoding images and writing to disk going from ~450ms down to 250-300ms. Here's a chart of the total time for _all of intake, transfer, interpret, write and record_ before and after:
The median scan time went from 3.47s to 2.865s, a decrease of about 23%.
Manual testing, new automated testing to prevent regression of the PNG encoding parallelism.
=> perf(scan): optimize writing of scanned images to disk

libs/mark-flow-ui/src/components/review.test.tsx, libs/mark-flow-ui/src/components/review.tsx
https://github.com/votingworks/vxsuite/issues/5168
We were accidently just checking for a "yes" option in rendering this UI and treating an undervote like "no"
Before
After
Added test case, saw failure, did change, saw pass
Manually tested visually in the UI as seen above
=> Fix bug shows 'No' on review page for undervote yesno

apps/mark-scan/frontend/src/app.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark/frontend/src/app.test.tsx, apps/mark/frontend/src/app_root.tsx, libs/mark-flow-ui/src/hooks/use_session_settings_manager.test.tsx, libs/mark-flow-ui/src/hooks/use_session_settings_manager.ts
Fixes https://github.com/votingworks/vxsuite/issues/4947
Fixes https://github.com/votingworks/vxsuite/issues/5121
Attempting to make the `useSessionSettingsManager` hook a little less brittle and more readable:
- Moving the responsibility of resetting settings at the end of the session to the apps (VxMark, VxMarkScan), so that it's more explicit and more tightly coupled with the `resetBallot` action in each app.
- Break up the effect into smaller effects/callbacks to make sure each piece is running only when necessary.
https://github.com/user-attachments/assets/7089c5a5-552c-4be9-af7b-095b48cd2862
- Updated associated unit tests
- Manual testing:
- Insert and remove card at various points during the voter flow - verify settings are restored when card is removed.
- Deactivate voter session …
=> [Mark] Tighten up voter settings save/restore logic

apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/test/setup_custom_matchers.ts
Since we now have something that won't take forever on image mismatch trying to serialize the data, let's use it!
=> refactor(mark-scan): use `toMatchImage`

apps/mark-scan/accessible-controller/src/controllerd.rs, apps/mark-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/readiness_report.ts, apps/mark-scan/backend/src/util/hardware.test.ts, apps/mark-scan/backend/src/util/hardware.ts, apps/mark-scan/daemon-utils/src/lib.rs, apps/mark-scan/fai-100-controller/src/fai_100_controllerd.rs, apps/mark-scan/frontend/src/pages/diagnostics/diagnostics_screen.test.tsx, libs/backend/src/exec.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_ids.ts, libs/logging/types-rust/src/log_event_enums.rs, libs/ui/src/diagnostics/mark_scan_device_diagnostic_section.test.tsx, libs/ui/src/diagnostics/mark_scan_device_diagnostic_section.tsx, libs/ui/src/diagnostics/mark_scan_readiness_report.test.tsx, libs/ui/src/diagnostics/test_utils.ts
We currently check for controller connection by running `child_process.execFile('ps aux | grep controller[d])`. `execFile` doesn't support I/O redirect so this command will always fail and report no controller connection.
~`exec` behaves similarly but supports I/O redirect at the slight performance cost of starting (and ending) a shell session.~
Based on feedback, this PR changes controller daemons to write a PID file to be read by the mark-scan backend. The reported PID is checked with `kill` signal 0 to see if the daemon process is still running.
Manual testing
- Ran daemon, confirmed backend can detect controller
- Killed daemon, confirmed backend can no longer detect controller
N/A not user facing, no new actions
=> Use PID file for controller connection status

libs/usb-drive/scripts/format_fat32.sh
This PR fixes [5045](https://github.com/votingworks/vxsuite/issues/5045). By first ensuring the partition table type is `dos`, the second `sfdisk` command can successfully execute, even if the drive was originally created with the wrong table type, i.e. `gpt`. 
To test, I've created multiple USB drive configurations:
* dos - single fat32 partition
* dos - multiple fat32 partitions
* dos - single ext4 partition 
* dos - multiple ext4 partitions
* dos - multiple fat32 and ext4 partitions
* gpt - all of the above
In all cases, you end up with a dos - single fat32 partition with our expected VxUSB-XXXXX naming convention.
=> Enable formatting of non-dos partition table USB drives

libs/ballot-interpreter/src/hmpb-rust/interpret.rs
The latest Rust seems stricter about unused structs. Let's remove them!
=> build(ballot-interpreter): fix build in Rust v1.80.0

Cargo.toml, apps/mark-scan/accessible-controller/src/controllerd.rs, apps/mark-scan/fai-100-controller/src/fai_100_controllerd.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks.rs, libs/pdi-scanner/src/rust/protocol/packets.rs
Rust introduced some new clippy lints since the version we're pinned to (1.76.0). This makes `cargo clippy` report cleanly up to v1.80.0. See [this](https://rust-lang.github.io/rust-clippy/master/index.html#/lint_groups_priority) for the `Cargo.toml` change. The others are just about documentation comment formatting.
n/a
Ran `cargo clippy` locally at the project root.
=> style(rust): fix issues flagged by clippy in Rust 1.80.0

libs/ui/src/voter_settings/index.tsx, libs/ui/src/voter_settings/voter_settings.test.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5055
Resetting screen reader audio settings when the "Reset" button on the voter settings screen is pressed.
- Updated unit tests
- Local run to verify
=> [Mark] Update settings screen 'reset' button to reset audio settings

apps/scan/backend/src/scanners/pdi/pdi_app_scan_cover_open.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_jam.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/src/types.ts, apps/scan/frontend/src/screens/scan_error_screen.tsx, apps/scan/frontend/src/screens/scan_jam_screen.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
Fixes https://github.com/votingworks/vxsuite/issues/4956
Previously, if a ballot jammed during the accept command, we tried to reject it back out of the front. However, due to an unknown bug (likely a race condition), the scanner did not actually turn on the motor when it received the command to eject the ballot to the front. This caused the ballot to be recorded as rejected even though it remained in the back of the scanner (and could easily fall into the ballot box as it wasn't held by the rollers). This would result in a ballot in the ballot box that was not counted.
To ensure that a ballot in the box is always counted, we change the approach taken. Since the ballot in this case is already ejected enough from the rear of the scanner to fall into the ballot box, we always record it as …
=> VxScan: Improve handling of jam on ballot accept with PDI scanner

apps/scan/backend/src/scanners/custom/custom_app_scan.test.ts, apps/scan/backend/src/scanners/custom/custom_app_scan_double_sheets.test.ts, apps/scan/backend/src/scanners/custom/custom_app_scan_jam.test.ts, apps/scan/backend/src/scanners/custom/custom_app_scan_power_off.test.ts, apps/scan/backend/src/scanners/custom/custom_app_scan_precinct_config.test.ts, apps/scan/backend/src/scanners/custom/custom_app_scan_shoeshine_mode.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_disconnect.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_jam.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_shoeshine_mode.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/backend/test/helpers/pdi_helpers.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, libs/types/src/precinct_scanner.ts
Closes #5162 
There's no need to wait for the frontend to send an accept command. Note that I chose to _not_ check auth status and whatnot before accepting. While we've had that guard in the past (by waiting for the frontend accept command), I figured that the time between starting the scan and accepting is so short that it seems reasonable to just rely on the check we already do before starting the scan.
No change, just faster 😄 
- Manually tested with each scanner
=> VxScan: Accept ballots on backend after interpretation

libs/cvr-fixture-generator/src/cli/generate/main.test.ts, libs/cvr-fixture-generator/src/cli/generate/main.ts
CircleCI flagged `generating as BMD ballots (non-gridlayouts election)` as our [slowest test](https://app.circleci.com/insights/github/votingworks/vxsuite/workflows/test/tests). I believe it's recorded as taking 1m because that's actually the Jest timeout for the file, meaning it probably times out about 4% of the time (i.e. because 96% pass rate).
We don't actually make images with any content when generating CVR fixtures, so just re-use the images from previous generated CVRs. This speeds up the tests by a decent amount (ran the `main.test.ts` file before and after taking the best of three runs):
**BEFORE**
```
PASS  src/cli/generate/main.test.ts (40.79 s)
✓ --help (13 ms)
✓ invalid option (2 ms)
✓ missing election definition (1 ms)
✓ missing output path (1 ms)
✓ generate with defaults …
```
=> perf(cvr-fixture-generator): create one image per ballot size

apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts
Fixes #5143 
Details in the commit messages
Before
https://github.com/user-attachments/assets/1564047e-c214-44dc-a1f7-51f75b913401
After
https://github.com/user-attachments/assets/dd87a13a-9733-4c4d-b461-6b71d2999330
- Added regression test
=> VxScan: Fix erroneous jam error message after double sheet detected

apps/mark-scan/backend/src/pat-input/connection_status_reader.ts
Removes an extra log from PAT connection status reader. The actual success log is further down the function: https://github.com/votingworks/vxsuite/pull/5223/files#diff-b2fba0b85584356803af01772a0ced8158c9b86b3a3fef9fc57aaabbc22c648fR97
N/A
Logging change only
=> remove extra log from connection status reader

apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts
Fixes https://github.com/votingworks/vxsuite/issues/5142
Previously, if there was no ballot in the scanner after a scan completed, we would declare an error and try to disconnect/reconnect to the scanner, since this seemed like an impossible case. It turns out you can produce this case by pulling the ballot out soon after the scan begins. Sometimes this will result in a failed scan, but other times the scan will complete even though the ballot is gone. Since we're confident in that case that there's no ballot in the scanner, we can abandon the scan and wait for a new ballot to be inserted. This is an improvement because we don't have to spend time disconnecting/reconnecting (and we have seen at least sometimes that disconnecting and reconnecting fails, which then requires a restart of the …
=> VxScan: Don't error if ballot removed but scan completes

apps/mark-scan/frontend/Makefile
Issue link: https://github.com/votingworks/vxsuite/issues/5176
Very similar to https://github.com/votingworks/vxsuite/pull/5066, this PR _should_ fix the currently crashing VxMark paper handler diagnostic in prod by making sure that we run `pnpm build` in `apps/mark-scan/backend` as part of `make build` in `apps/mark-scan/frontend`. As a reminder, during the build process, we run `make build` in every frontend.
The `pnpm build` in `apps/mark-scan/backend` includes a command to copy over static files to the `build` directory, namely `custom-paper-handler/diagnostic/election.json`, which we need for the diagnostic. I believe the lack of that file in the `apps/mark-scan/backend/build` directory explains the crashing.
Adam tested this fix for me on a VxAustin prod VxMark :tada:
=> Fix VxMark paper handler diagnostic in prod

apps/scan/backend/scripts/copy_sheets.ts
The script was hanging saying that the db connection was busy after this PR https://github.com/votingworks/vxsuite/pull/4991/files This reverts the changes to the copy sheets script from that PR. Since this is just a script using for periodic testing and not production I think just using a basic for loop is fine. 
Copied to a qa image in tty2 and used successfully
=> Revert iter changes on copy sheets script

apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/frontend/src/app_cardless_voting.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/components/deactivate_voter_session_button.test.tsx, apps/mark-scan/frontend/src/components/deactivate_voter_session_button.tsx, apps/mark-scan/frontend/src/hooks/use_is_voter_auth.test.ts, apps/mark-scan/frontend/src/hooks/use_is_voter_auth.ts, apps/mark-scan/frontend/src/pages/ballot_ready_for_review_screen.test.tsx, apps/mark-scan/frontend/src/pages/ballot_ready_for_review_screen.tsx, apps/mark-scan/frontend/src/pages/load_paper_page.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark-scan/frontend/src/pages/remove_jammed_sheet_screen.tsx, apps/mark-scan/frontend/src/pages/waiting_for_ballot_reinsertion_screen.test.tsx, apps/mark-scan/frontend/src/pages/waiting_for_ballot_reinsertion_screen.tsx, apps/mark-scan/frontend/src/voter_flow.test.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5207
Adding a button to reset the voter session to relevant screens whenever a Poll Worker is logged in, to prevent the UI from getting stuck in certain states with no way to start over except waiting for the session timer to expire.
https://github.com/user-attachments/assets/ca7c4e4e-1d95-47d6-a43a-3a035ff2e2f1
https://github.com/user-attachments/assets/b753696a-8644-48ae-a9e0-67f5a90185f1
- Added/updated unit tests
- Manual verification runs
=> [Mark] Reset state and provide poll worker escape hatches where relevant

apps/mark-scan/backend/jest.config.js, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/frontend/src/pages/inserted_blank_sheet_instead_of_ballot_screen.tsx, apps/mark-scan/frontend/src/pages/inserted_invalid_new_sheet_screen.test.tsx, apps/mark-scan/frontend/src/pages/inserted_invalid_new_sheet_screen.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx
Resolves https://github.com/votingworks/vxsuite/issues/5232
Updating the new session flow to reject blank sheets when the Poll Worker explicitly chooses to go through the "Cast a Previously Printed Ballot" flow.
We were previously dropping them back into the ballot style selection screen if a blank sheet was inserted before picking a ballot style - this change makes behaviour more explicit to avoid confusion.
Pre-printed ballots are still accepted even after picking a ballot style in the mainline flow.
https://github.com/user-attachments/assets/84be278e-59d4-466f-b78a-80854c7361b4
- Updated unit tests
- Manual verification for the different paths to starting a new session
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any …
=> [Mark] Reject blank sheets in the explicit pre-printed ballot flow

libs/usb-drive/scripts/unmount.sh
Closes #4833. Confirmed this doesn't break the regular flow (default mounting point) and now works with a wonky mount point like `/media/vx/free-_ space`.
=> allow spaces and underscores in usb drive mount points

apps/admin/backend/src/app.test.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/util/auth.ts, apps/central-scan/backend/src/app.grout.test.ts, apps/central-scan/backend/src/store.ts, apps/central-scan/backend/src/util/auth.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/store.ts, apps/mark-scan/backend/src/util/auth.ts, apps/mark/backend/src/app.test.ts, apps/mark/backend/src/store.ts, apps/mark/backend/src/util/auth.ts, apps/scan/backend/src/app_config.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/src/util/auth.ts
Fixes #4790 
During scale testing with a large election definition, I noticed that auth polling was very slow due to loading the election definition from the database on every polling request. This caused the entire app to lag.
To fix this, I changed the auth polling to extract only the relevant fields for the election key (id and date) from the JSON at the database level.
Before
https://github.com/user-attachments/assets/5859693d-b25c-4959-bdb6-f5572ded0fd3
After
https://github.com/user-attachments/assets/087eb45d-d86b-4f42-8838-ece523939fe7
Manual testing
=> Optimize retrieval of election key during auth polling

apps/mark-scan/backend/src/app.preprinted_ballot_insertion.test.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/app.ui_strings.test.ts, apps/mark-scan/backend/src/server.ts, apps/mark-scan/backend/src/util/render_ballot.tsx, apps/mark-scan/backend/test/app_helpers.ts, libs/printing/src/index.ts, libs/printing/src/render.tsx
This PR should address https://github.com/votingworks/vxsuite/issues/5245 per my testing. After considering a few explanations that turned out to be red herrings, we ultimately found that printing sporadically stalling in production involved the Chromium `newPage` call hanging:
https://github.com/votingworks/vxsuite/blob/034edbcc5e89f33397961c7e88636af51385b81f/libs/printing/src/render.tsx#L96
We found [this relevant Playwright issue](https://github.com/microsoft/playwright/issues/3939). The poster notes that they're constantly launching new Chromium instances, like we are, and saw the issue go away after switching to a single persisted instance (among other changes). We, too, have been wanting to shift away from launching and closing a new Chromium instance every time we print, primarily …
=> Launch a single Chromium instance on VxMark startup for BMDB printing

apps/admin/frontend/src/components/navigation_screen.tsx, apps/central-scan/frontend/src/navigation_screen.tsx, libs/ui/src/session_time_limit_tracker.tsx
Fixes #5152 
The header is too crowded, so when the timer shows up, it causes weird wrapping. To fix this, we move the timer to its own banner. While we're at it, give it warning styling, since it is a warning.
I also polished the session limit modal to have left aligned text.
VxCentralScan before
VxCentralScan after
VxAdmin before
VxAdmin after
Modal before
Modal after
Manual testing
=> VxCentralScan/VxAdmin: Move session timer from header to banner

libs/image-utils/jest.config.js, libs/image-utils/src/cli/pdf_to_images.ts, libs/image-utils/src/pdf_to_images.ts
We don't actually want this exported from the library.
Same as https://github.com/votingworks/vxsuite/pull/5268, but for `main`.
=> refactor(image-utils): remove `main` export

apps/mark/integration-testing/e2e/scroll_buttons.spec.ts, libs/mark-flow-ui/src/components/yes_no_contest.test.tsx, libs/mark-flow-ui/src/components/yes_no_contest.tsx, libs/ui/src/with_scroll_buttons.tsx
Fixes https://github.com/votingworks/vxsuite/issues/4900
When yes/no contest descriptions are long enough to overflow the available screen height, we show scroll buttons, but they are only accessible to touchscreen users. Tabbing over the scroll buttons was intentionally de-activated to avoid audio-only voters having to tab over them after listening to the contest description.
This change conditionally enables tab focus for the scroll buttons when a PAT device is connected.
https://github.com/user-attachments/assets/d8f77ceb-ebc9-45f2-a4d6-a244dca6973c
- Unit test for `YesNoContext` -> `WithScrollButtons` component interaction
- Manual test for actual focus/click behaviour with PAT inputs. Would like to add a browser integration test for this eventually; just a little more effort than …
=> [Mark] Enable scrolling with PAT devices on long ballot measures

apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/insert_ballot_screen.tsx, apps/scan/frontend/src/screens/polls_not_open_screen.test.tsx, apps/scan/frontend/src/screens/polls_not_open_screen.tsx, apps/scan/frontend/src/screens/setup_scanner_screen.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx
https://github.com/votingworks/vxsuite/issues/5234
This machine does not have a built-in chargeable battery anymore so this logic is no longer relevant.
N/A
Ran tests
=> VxScan: remove battery indicators

apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/central-scan/backend/src/app.grout.test.ts, apps/central-scan/backend/src/app.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark/backend/src/app.test.ts, apps/mark/backend/src/app.ts, apps/scan/backend/src/app.ts, apps/scan/backend/src/app_config.test.ts
Various VVSG 2.0 rules specify that we must log all configuration, unconfiguration, and any errors in configuration. This PR does a review across apps of our logging during these actions and makes them consistent and adds any missing logs along with tests.
Tested manually and visually verified logs in addition to running tests.
=> [All] Add logs for configuration/unconfiguration and configuration errors

apps/admin/frontend/src/components/navigation_screen.tsx, apps/admin/frontend/src/components/reporting/ballot_count_report_viewer.tsx, apps/admin/frontend/src/components/reporting/pdf_viewer.tsx, apps/admin/frontend/src/components/reporting/shared.tsx, apps/admin/frontend/src/components/reporting/tally_report_viewer.tsx, apps/admin/frontend/src/index.tsx, apps/admin/frontend/src/screens/reporting/all_precincts_tally_report_screen.tsx, apps/admin/frontend/src/screens/reporting/ballot_count_report_builder.tsx, apps/admin/frontend/src/screens/reporting/full_election_tally_report_screen.tsx, apps/admin/frontend/src/screens/reporting/precinct_ballot_count_report_screen.tsx, apps/admin/frontend/src/screens/reporting/single_precinct_tally_report_screen.tsx, apps/admin/frontend/src/screens/reporting/tally_report_builder.tsx, apps/admin/frontend/src/screens/reporting/voting_method_ballot_count_report_screen.tsx, apps/admin/frontend/src/screens/reporting/write_in_adjudication_report_screen.tsx, apps/central-scan/frontend/src/app.tsx, libs/ui/src/search_select.tsx
On desktop apps, it's useful to have a scrollbar when scrolling is possible, both as a visual indicator of overflow and as a tool for scrolling.
VxCentralScan
https://github.com/user-attachments/assets/bc695c47-6e68-4558-a06b-95c5f59145f8
VxAdmin
Note that there are nested scrollbars on the report pages. These nested scrollable areas existed before, they just weren't as obvious. I experimented with some other solutions (e.g. one continuous scroll for all the content, a button to expand/shrink the PDF viewer to use the whole content area), but they all felt less useable overall, so I kept the current UX. It's a little ugly, but I think it works fine.
https://github.com/user-attachments/assets/7e84f370-68dd-44c2-a4f0-b5548ec8c876
Manual testing
=> VxAdmin/VxCentralScan: Show scrollbars

libs/ui/src/ui_strings/language_context.test.tsx, libs/ui/src/ui_strings/language_context.tsx, libs/ui/test/test_context.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5265
Whenever machines are unconfigured, we clear the backend DB and frontend query cache, but our translation library, i18next, has a cache of its own that we weren't clearing yet. That meant stale translations (including English strings) in the voter-facing bits of the UI. These would ordinarily get overwritten when a new election is configured, along with the new translations, but not when we use elections without translations.
Making sure we reset the i18next cache whenever the query cache changes (which happens on unconfigure).
- Added a new test case to repro and verify the fix
- Manual verification
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user …
=> [UiStrings] Clear i18next cache when backend translations are removed

apps/admin/frontend/src/components/reporting/filter_editor.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx, apps/admin/frontend/src/screens/write_ins_summary_screen.tsx, apps/central-scan/frontend/README.md, apps/central-scan/frontend/src/components/scan_button.tsx, apps/design/frontend/src/ballot_screen.tsx, libs/ui/src/diagnostics/components.ts, libs/ui/src/election_info_bar.tsx, libs/ui/src/save_readiness_report_button.tsx, libs/ui/src/search_select.tsx, libs/ui/src/typography.tsx
Task: #5247 
Fixes: https://github.com/votingworks/vxsuite/issues/5236
An assortment of polish for issues found using an election definition with long content (e.g. 100 character contest and candidate names).
Added to individual commits
Manual testing
=> Central system polish for long election content

libs/printing/src/render.test.tsx, libs/printing/src/render.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5263
On the all bubble ballot the pdf we generate is so long that canvas seg faults when converting to an image. To avoid this problem we can just break up the page when it streches beyond 100 inches, which will never happen in anything but extreme situations. If the content height is longer then a standard paper length but shorter then 100 inches we will still truncate the length of the report to the length of the content (and we will never make it smaller then a standard page). 
Note this change should really only affect the all bubble ballot.
PDF of printed all bubble polls open report 
[print-job-2024-08-21T00:36:50.587Z.pdf](https://github.com/user-attachments/files/16696348/print-job-2024-08-21T00.36.50.587Z.pdf)
Note the contest …
=> Break pages up when long enough on tally report

apps/scan/frontend/src/components/layout.tsx, apps/scan/frontend/src/screens/scan_warning_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/4964
Removing the title placeholder in the screen header when there's no title, so that the scanned ballot count falls to the left in those cases.
| Single-Language  | Multi-Language |
| ![Screenshot 2024-08-22 at 12 34 29](https://github.com/user-attachments/assets/15ab8ae3-4ba7-4e14-b1f0-7b95a54e6fcd) | ![Screenshot 2024-08-22 at 12 34 08](https://github.com/user-attachments/assets/233849ba-1886-4866-821f-24213ca96bda) |
| ![Screenshot 2024-08-22 at 12 34 38](https://github.com/user-attachments/assets/96b799c6-74c0-42f0-af88-f992410ceef5) | ![Screenshot 2024-08-22 at 12 34 45](https://github.com/user-attachments/assets/486e0ff8-e829-4389-8279-ab6fa1f8a84a) |
- Manual …
=> [Scan] Left-align ballot count when there's no header title

apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/mark-scan/frontend/src/pages/admin_screen.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/pages/admin_screen.test.tsx, apps/mark/integration-testing/e2e/scroll_buttons.spec.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/components/printer_management/election_manager_printer_tab_content.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, libs/ui/src/change_precinct_button.test.tsx, libs/ui/src/change_precinct_button.tsx, libs/ui/src/election_info_bar.tsx, libs/ui/src/modal.tsx, libs/ui/src/search_select.tsx
Task: https://github.com/votingworks/vxsuite/issues/5247
Fixes: https://github.com/votingworks/vxsuite/issues/5201
An assortment of polish for issues found using an election definition with long content (e.g. 100 character contest and candidate names).
Added to individual commits
Manual testing and automated test updates
=> VxScan UI polish for long election content

apps/scan/backend/src/app.ts, apps/scan/backend/src/util/diagnostics.ts, apps/scan/frontend/src/api.ts, libs/types/src/diagnostics.ts
Related to https://github.com/votingworks/vxsuite/issues/5193
Setting up the server/client APIs for getting and logging audio diagnostic records for upcoming work in the UI.
Following the patterns set in the print diagnostic flow.
- Deferred till the UI is hooked up
=> [Scan] Add API for audio diagnostics

apps/admin/backend/src/app.diagnostics.test.ts, apps/central-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/backend/src/app.diagnostics.test.ts
These have been flaky, and we already set the apps/scan/backend test to have a 60s timeout. So standardize the rest of the apps on that timeout.
N/A
🤞
=> Increase timeouts for readiness report tests

apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts
Increases the timeout on mark-scan state machine tests to 10s. The ballot fixture render in this step can take longer than the global timeout for that file (2s).
Hopefully addresses flaky tests: https://app.circleci.com/pipelines/github/votingworks/vxsuite/16750/workflows/8b0a21d9-f214-4e67-80fb-ec5d143af6a8/jobs/653438
N/a
Ran locally a few times but couldn't repro. We'll have to see if flakiness is reduced in CI over time.
=> Fix mark-scan test timeout

apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/printer_cover_open_screen.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/5259 
Adds a screen when the printer cover is open. This follows the pattern of the scanner cover is open screen where it is only shown when polls are open. The pollworker flows already have blocks that prevent opening/closing polls in this case. I could see moving it above the polls closed screen though but since this could just jostle open I think it makes sense to just not alert on it unless you are in a situation where it could actually present an issue. 
https://github.com/user-attachments/assets/df395ede-7a1e-4555-a1a7-a7ff0de53271
Added test, tested manually using dev dock mock. 
I am intending a more comprehensive review to add logs to any missing hardware states like this in VxScan in another PR.
=> Add printer cover is open screen

apps/mark-scan/accessible-controller/src/controllerd.rs, apps/mark-scan/accessible-controller/src/port.rs, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/util/hardware.test.ts, apps/mark-scan/backend/src/util/hardware.ts, apps/mark-scan/fai-100-controller/src/fai_100_controllerd.rs, apps/mark-scan/pat-device-input/src/patinputd.rs, apps/mark-scan/pat-device-input/src/pin.rs, libs/backend/src/exceptions.ts, libs/backend/src/system_call/get_audio_info.test.ts, libs/backend/src/system_call/get_audio_info.ts, libs/ui/src/error_boundary.test.tsx, libs/ui/src/error_boundary.tsx
In order to filter logs for only errors we need a way to identify errors, I think filtering for the required cdf field "disposition" as "failure" is the most appropriate place to do this. This PR adds the disposition: failure designation to logs it was missing from that are clearly indicating errors based on type. Just did a naive search for log event IDs with "Error" in the name. 
Ran Tests
=> Add disposition failure to all error logs in app

libs/logging/types-rust/src/types.rs
https://github.com/votingworks/vxsuite/issues/5334
Uses camelcase for log event keys when logging with Rust.
n/a
Ran Rust daemon and manually confirmed camelcase output.
```
{"source":"vx-mark-scan-fai-100-controller-daemon","eventId":"create-virtual-uinput-device-init","message":"","eventType":"system-action","user":"system","disposition":"n/a"}
```
=> camelcase log keys

libs/fs/src/election.test.ts, libs/fs/src/election.ts
During scale testing, this limit prevented us from testing with a large mock election file. I temporarily increased it to enable the testing, and the system was generally able to handle a large election around 30MB without issue. So I'm increasing this limit to the tested size so that it doesn't end up accidentally biting us later in the extremely rare case that we have an election over 10MB.
N/A
Manual scale testing
=> Increase max election file size to 30MB

apps/design/backend/src/language_and_audio/vendored_translations.json
The ballot labels for the different ballot variants (sample/test/official and precinct/absentee) all need to fit on one line in order for ballot layout to work. In Spanish, the most verbose language we support, some of the auto-translations are too long, so we use shorter vendored translations instead. These recently got reset, so updating them again to make ballot layout work.
N/A
Manual test
=> VxDesign: Update vendored translation for Spanish ballot label

apps/admin/backend/src/app.ts, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/screens/settings_screen.test.tsx, apps/central-scan/backend/src/app.ts, apps/central-scan/frontend/src/screens/system_administrator_settings_screen.test.tsx, apps/mark-scan/backend/src/app.ts, apps/mark-scan/frontend/src/pages/admin_screen.test.tsx, apps/mark/backend/src/app.ts, apps/mark/frontend/src/pages/admin_screen.test.tsx, apps/scan/backend/src/app.ts, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, libs/backend/src/system_call/api.test.ts, libs/backend/src/system_call/api.ts, libs/backend/src/system_call/export_logs_to_usb.test.ts, libs/backend/src/system_call/export_logs_to_usb.ts, libs/logging/package.json, libs/logging/src/export.test.ts, libs/logging/src/export.ts, libs/logging/src/test_utils.test.ts, libs/logging/src/test_utils.ts, libs/ui/src/export_logs_modal.test.tsx, libs/ui/src/export_logs_modal.tsx, libs/ui/src/system_call_api.test.tsx, libs/usb-drive/src/usb_drive.test.ts, pnpm-lock.yaml
https://github.com/votingworks/vxsuite/issues/5006
https://github.com/votingworks/vxsuite/issues/5333
Adds the ability to export logs as an error-only report or as CDF. The CDF conversion code was pre-existing. This just adds the UI logic and the logic to uncompress/recompress old files in addition to the error-only filtering. 
On moderately large log files this can take a minute or so for the CDF conversion, the error filtering is instantaneous which I find surprising since both need to uncompress / parse json / recompress, so I may play around a bit and see if there is something dumb we are doing. Otherwise will test on larger data from Ben and on a real image after merging. 
https://github.com/user-attachments/assets/5384cb26-290d-4da8-aceb-43daf1089569
Copied logs from a prod machine …
=> Allow CDF and Error-Only Log Exports

apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/test/app_helpers.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/src/scanners/shared.ts, libs/logging/src/logger.test.ts, libs/logging/src/logger.ts
https://github.com/votingworks/vxsuite/issues/5342
Improvements after audit state machine logging in mark and scan. We were unneccesarily downgrading the logger to BaseLogger in the function calls so I fixed that in both. I also am logging new states on the state transition logs as an explicit key in the json blob. Now that we are using Logger, I will log with the current role rather then 'system' for "event" logs that come from a user action, on VxScan this will log as "voter" if no one is currently authenticated. This makes sures on the precinct scanner that we log with the user as voter: 
1. Initiating a scan with the "scanStart" log
2. Accepting a ballot after adjudication
3. Returning a ballot after adjudication. 
Things like calibration will now be logged with the right user as …
=> Improve state machine logging

apps/scan/backend/src/printing/printer.ts, libs/fujitsu-thermal-printer/package.json, libs/fujitsu-thermal-printer/src/cli.ts, libs/fujitsu-thermal-printer/src/index.ts, libs/fujitsu-thermal-printer/src/logging.ts, libs/fujitsu-thermal-printer/src/mocks/file_printer.test.ts, libs/fujitsu-thermal-printer/src/mocks/file_printer.ts, libs/fujitsu-thermal-printer/src/printer.ts, libs/fujitsu-thermal-printer/tsconfig.build.json, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_ids.ts, libs/logging/types-rust/src/log_event_enums.rs, pnpm-lock.yaml
https://github.com/votingworks/vxsuite/issues/5339
Adds basic logging on status changes and print events for the fujitsu printer
Tested mock printer and real printer manually, saw logs as expected.
=> Add fujtisu printer logging

apps/mark-scan/backend/src/app.auth.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/custom-paper-handler/types.ts, libs/custom-paper-handler/src/driver/mock_driver.ts, libs/custom-paper-handler/src/driver/scanner_status.ts
Related to https://github.com/votingworks/vxsuite/issues/3873
Adding polling for the `optoSensor` (plastic hood open) and `coverOpen` (paper handler open) sensor flags and moving the state machine into a `cover_open_unauthorized` state accordingly, if there's no non-voter user logged in.
This will eventually be consumed in other parts of the app, to display an alert in the UI and play an alarm through the speakers.
https://github.com/user-attachments/assets/0296c450-a8d7-45fc-a143-0a8eb79a20fd
- Manual + unit tests
- ~[ ] I have added the "user_facing_change" label to this PR to …
=> [MarkScan] Add open scanner detection and associated state machine state

libs/backend/src/system_call/export_logs_to_usb.test.ts, libs/backend/src/system_call/export_logs_to_usb.ts
The CDF log files are json formatted and in order to work with the NIST cdf validator tool the extension needs to be .json, which probably makes sense anyway since ... it is json. 
Ran tests
=> Save cdf log files as json extension

apps/central-scan/backend/src/app.grout.test.ts, apps/central-scan/backend/src/app.ts, apps/central-scan/backend/src/importer.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/app.ts, apps/scan/backend/src/app.ts, apps/scan/backend/src/app_config.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_ids.ts, libs/logging/types-rust/src/log_event_enums.rs
Adds a few missing logs:
Mark: Failure log if you try to open polls when there is previous ballot data
Mark: Logs for toggling test/live mode
Scan: Logs for toggling test/love mode
Scan: Logs for toggling sounds
Scan: Logs for toggling MSD 
CentralScan: Moves the log for clearing ballot data a bit lower in the stack so that it gets logged when data is cleared through actions like toggling test/live mode 
Did actions, saw logs, ran test
=> Add various logs

apps/mark-scan/frontend/src/pages/scanner_open_alarm_screen.test.tsx, apps/mark-scan/frontend/src/pages/scanner_open_alarm_screen.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
https://github.com/votingworks/vxsuite/issues/3873
Adding missing translations for the voter-facing text on the cover open alarm screen - also adding a temporary screen reader mute to avoid trying to read on-screen text while the alarm's going off.
- unit and manual
=> [MarkScan] Translate voter-facing text on the cover open alarm screen

libs/image-utils/src/image_data.test.ts
We should consider replacing this with https://codspeed.io/ or similar. I didn't disable this only in CI because it's inconsistent even on a dev machine.
n/a
Automated.
=> test(image-utils): disable `encodeImageData` perf test

libs/ui/src/ui_strings/audio_volume.ts
Closes https://github.com/votingworks/vxsuite/issues/5352
We recently changed the model of headphones we're using on the VxMark and they require a bit more power to drive, so bumping up our volume calibration to put the default volume back in the 60-70 dB range.
- SPL meter in a styrofoam head
=> [Mark] Calibrate screen reader volume for new headphones on VSAP 150

apps/admin/frontend/src/screens/election_screen.test.tsx, apps/admin/frontend/src/screens/election_screen.tsx
https://github.com/votingworks/vxsuite/issues/5320
Current System Admin
Current Election Manager
System Admins + Election Manager without explanations
OUTDATED: Systems Admins with short explanations (Not using this approach)
Test added
=> Allow for system admins to save election packages in same way election manager can

apps/admin/backend/src/app.diagnostics.test.ts, apps/admin/backend/src/app.test.ts, apps/admin/backend/src/util/export_file.ts, apps/central-scan/backend/src/app.diagnostics.test.ts, apps/central-scan/backend/src/end_to_end_bmd.test.ts, apps/central-scan/backend/src/end_to_end_hmpb.test.ts, apps/mark-scan/backend/src/app.diagnostics.test.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/backend/test/helpers/pdi_helpers.ts, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/exporter.test.ts, libs/backend/src/exporter.ts, libs/backend/src/system_call/export_logs_to_usb.test.ts, libs/backend/src/system_call/export_logs_to_usb.ts, libs/test-utils/src/mock_function.test.ts, libs/test-utils/src/mock_function.ts, libs/usb-drive/src/mocks/file_usb_drive.ts, libs/usb-drive/src/mocks/memory_usb_drive.ts, libs/usb-drive/src/types.ts, libs/usb-drive/src/usb_drive.test.ts, libs/usb-drive/src/usb_drive.ts
Adds a `sync` method to `libs/usb-drive` so that we can easily mock sync calls in tests. This will hopefully help prevent test flakiness due to hanging sync calls in `apps/scan/backend`.
To enable easy mocking across all of the `apps/scan/backend` tests, adds a new mock function method `expectOptionalRepeatedCallsWith`.
Updated tests. Hope it solves flakiness but can't be sure - ran ~20 runs with no flake.
=> libs/usb-drive: Add `sync` method to enable mocking

apps/design/frontend/package.json, apps/design/frontend/src/rich_text_editor.tsx, pnpm-lock.yaml
For now, just enabling the keyboard shortcuts (Cmd+Z, Cmd+Shift+Z), which are turned on by default, not adding buttons.
You can't see what keys I'm pressing in this video, but it's just the two shortcuts above.
https://github.com/user-attachments/assets/4d15a1fe-23fc-4d15-b6fa-90a32051c1bc
Manual test
=> VxDesign: Add undo/redo to RichTextEditor

apps/admin/backend/src/app.write_ins.test.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/write_ins.ts
Closes #5382. Does two things:
- makes sure unmarked write-ins appear in the write-in adjudication report
- undoes the WIA adjudication queue ordering that always puts UWIs last, which can be confusing if a UWI and a proper WI are on the same ballot contest 
Updated existing test coverage to match new logic.
=> unmarked write-in accounting tweaks

apps/admin/frontend/src/components/app_routes.tsx, apps/admin/frontend/src/components/navigation_screen.tsx, apps/central-scan/frontend/README.md, apps/central-scan/frontend/src/app_root.tsx, apps/central-scan/frontend/src/navigation_screen.tsx
https://github.com/votingworks/vxsuite/issues/5266
PR for allowing EMs to access diagnostics to VXAdmin and VXCentralScan, as they are more straightforward. I'll be adding a subsequent PR for MarkScan and Scan.
**System Admin (unchanged)**
**Election manager (diagnostics added)**
=> Allow EMs to access diagnostics in VXAdmin and CentralScan

apps/admin/frontend/jest.config.js, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/app_routes.tsx, apps/admin/frontend/src/components/navigation_screen.tsx, apps/admin/frontend/src/components/smartcard_modal/smartcard_modal.test.tsx, apps/admin/frontend/src/screens/smartcards_screen.tsx
Short term fix for https://github.com/votingworks/vxsuite/issues/5388
Instead of showing the card programming modal on any screen when logged in as a sys admin, only show it on the smart cards screen. This will prevent users from accidentally resetting their system admin card PIN.
In addition, add the smart cards screen to the system admin left nav when unconfigured (to maintain the existing ability to program sys admin cards without configuring the machine). Note that currently the smart cards screen will have some misleading copy about creating election cards when unconfigured, but I'll be updating that screen in the next PR, so it's just a momentary issue.
https://github.com/user-attachments/assets/1df6516e-2cf9-4b60-a6c4-f1a5f7c321fd
Manual test and updated automated tests
=> VxAdmin: Only show card programming modal on smart cards screen

apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/app_routes.tsx, apps/admin/frontend/test/helpers/mock_api_client.ts, apps/central-scan/frontend/src/app.test.tsx, apps/central-scan/frontend/src/app_root.tsx, apps/central-scan/frontend/test/api.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/app_vendor_screen.test.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx, apps/mark/frontend/src/app_root.tsx, apps/mark/frontend/src/app_vendor_screen.test.tsx, apps/mark/frontend/test/helpers/mock_api_client.tsx, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/backend/src/env.d.ts, libs/backend/src/intermediate-scripts/reboot-to-vendor-menu, libs/backend/src/intermediate_scripts.ts, libs/backend/src/system_call/api.test.ts, libs/backend/src/system_call/api.ts, libs/backend/src/system_call/power_down.ts, libs/backend/src/system_call/reboot_to_bios.ts, libs/backend/src/system_call/reboot_to_vendor_menu.ts, libs/ui/src/index.ts, libs/ui/src/system_call_api.test.tsx, libs/ui/src/vendor_screen.test.tsx, libs/ui/src/vendor_screen.tsx, libs/ui/test/test_context.tsx
Issue link: https://github.com/votingworks/vxsuite/issues/4760
Finally pushing vendor card work over the finish line 😅
This PR adds a vendor screen and displays it after authentication with a vendor card. The exact mechanics of booting to the current TTY2 admin menu in TTY1 are covered in https://github.com/votingworks/vxsuite-complete-system/pull/395.
_VxAdmin / VxCentralScan_
_VxMark / VxScan_
=> Add vendor screen and display it after authentication with a vendor card

apps/mark-scan/frontend/src/pages/admin_screen.test.tsx, apps/mark-scan/frontend/src/pages/admin_screen.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx
https://github.com/votingworks/vxsuite/issues/5266
**Scan - Election Manager access of Diagnostics under System Settings**
https://github.com/user-attachments/assets/5350db3a-dfa2-42ee-b1c8-3943367120cd
- Note: One non-ideal functionality shown in the video is that after a user closes the Diagnostics, they return to the Configuration tab rather than remaining in the System Settings tab. This is because the `TabbedSection` is not being rendered, so state is reset. We could fix this by pulling the state to the `ElectionManagerScreen`, but I am not sure if we feel this is needed.
**MarkScan - Election Manager access of Diagnostics**
https://github.com/user-attachments/assets/9e57a4a7-68d2-4966-911a-ca11d3ae6188
=> Allow System Admins to access diagnostics in VxScan and MarkScan

apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/util/manual_results.ts, apps/admin/frontend/src/screens/manual_data_entry_screen.tsx, apps/admin/frontend/src/screens/manual_data_summary_screen.tsx, libs/types/src/admin/index.ts, libs/types/src/admin/manual_results.ts, libs/types/src/cdf/election-results-reporting/convert.test.ts, libs/types/src/cdf/election-results-reporting/convert.ts, libs/types/src/cdf/election-results-reporting/fixtures.ts
* Adds support for write-ins when importing ERR files
* Validates non-write-in candidate IDs against the machine's election definition. Returns an error if candidate IDs specified in the ERR file do not have a match in the election definition.
* Updates ERR fixtures to work with `electionGeneralDefinition`; previous mammal-themed mock values did not have a corresponding election definition.
**Write-ins**
https://github.com/user-attachments/assets/7aff1ef6-8eab-4d61-8760-f9ebd004d9b1
**Candidate ID validation**
https://github.com/user-attachments/assets/a79e854b-cc08-4a0e-b3a9-b14db77e327c
- added tests
- manually tested
=> support ERR write-ins and validate non-write-in candidate IDs

apps/admin/frontend/src/components/reporting/filter_editor.tsx, apps/admin/frontend/src/screens/election_screen.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx, apps/central-scan/frontend/src/screens/settings_screen.tsx, apps/central-scan/frontend/src/screens/system_administrator_settings_screen.tsx, apps/design/frontend/src/tabs.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/pages/admin_screen.tsx, apps/mark/frontend/src/app_root.tsx, apps/mark/frontend/src/pages/admin_screen.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, libs/backend/src/system_call/export_logs_to_usb.ts, libs/ballot-interpreter/src/hmpb-ts/cli.ts, libs/cdf-schema-builder/src/xsd.test.ts, libs/logging/src/export.ts, libs/mark-flow-ui/src/components/candidate_contest.test.tsx, libs/ui/src/power_down_button.tsx, libs/ui/src/radio_group.tsx, libs/ui/src/reports/ballot_count_report.tsx, libs/utils/src/tabulation/tabulation.ts
In particular, newer versions of `@typescript-eslint` want:
- type aliases instead of empty `extends` interfaces
- no values used only for their types
- no unused `catch` bindings
This commit doesn't update the versions of `@typescript-eslint` packages because there's some CI-only issue (https://github.com/votingworks/vxsuite/pull/5422).
n/a
Automated.
=> style: various changes to work with newer `@typescript-eslint` versions

apps/admin/frontend/src/components/import_cvrfiles_modal.test.tsx, apps/admin/frontend/src/components/import_cvrfiles_modal.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5158
Previously, if you imported a continuous CVR export from VxScan into VxAdmin, then scanned more ballots and tried to re-import the same export, the "Load" button would be disabled. This fixes the logic for disabling that button to check the export timestamp, which changes when new ballots are exported (instead of just checking the file name, which doesn't change). The backend already knows how to only import the newly added CVRs, so the only fix needed is enabling the button.
Skipping since this is fixing a regression
Manual test, updated automated tests
=> VxAdmin: Allow continuous CVR exports to be re-imported

apps/mark-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/custom-paper-handler/diagnostic/blank_page_interpretation_diagnostic_error.ts, apps/mark-scan/backend/src/custom-paper-handler/diagnostic/diagnostic_error.ts, apps/mark-scan/backend/src/custom-paper-handler/diagnostic/unknown_interpretation_diagnostic_error.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/pages/diagnostics/diagnostics_screen.test.tsx, apps/mark-scan/frontend/src/pages/diagnostics/diagnostics_screen.tsx, apps/mark-scan/frontend/src/pages/diagnostics/paper_handler_diagnostic_screen.test.tsx, apps/mark-scan/frontend/src/pages/diagnostics/paper_handler_diagnostic_screen.tsx, apps/mark-scan/frontend/test/helpers/mock_api_client.tsx
Previously the paper handler diagnostic would crash the app when an unexpected interpretation type was returned. This happened because the `onError` handler does not catch and handle errors that happen in `onDone` of a service.
To avoid this, I broke out the post-interpretation logic to its own state with clearer transitions.
- added automated tests
- manually tested in VM
=> mark-scan diagnostic: handle blank interpretation gracefully

apps/admin/frontend/package.json, apps/central-scan/backend/jest.config.js, apps/central-scan/backend/test/setupTests.ts, apps/design/backend/test/setupTests.ts, apps/mark-scan/backend/jest.config.js, apps/mark-scan/backend/src/app.preprinted_ballot_insertion.test.ts, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/app.ui_strings.test.ts, apps/mark-scan/backend/src/server.ts, apps/mark-scan/backend/src/util/render_ballot.tsx, apps/mark-scan/backend/test/app_helpers.ts, apps/mark-scan/backend/test/setupTests.ts, apps/mark/backend/jest.config.js, apps/mark/backend/test/setupTests.ts, apps/scan/backend/jest.config.js, apps/scan/backend/test/setupTests.ts, libs/bmd-ballot-fixtures/jest.config.js, libs/bmd-ballot-fixtures/package.json, libs/bmd-ballot-fixtures/src/setupTests.ts, libs/bmd-ballot-fixtures/test/setupTests.ts, libs/printing/src/render.tsx, pnpm-lock.yaml
After discussion in https://github.com/votingworks/vxsuite/pull/5431 look into this caching approach. Overall worked well with the main issue being test cleanup. I initially cleaned up the cached browser through the jest globalTeardown function but found that was still giving me warning about things being open (despite logging confirming it was closing the browser) and failing CI in bmd_ballot_fixtures. When I instead cleaned up in a global afterAll that was resolved and I noticed that is how we are already cleaning up other state in VxAdminBackend so decided that that seemed like the safer approach. 
Note the safeguard I add in the caching for the isConnected() check is in case a browser was closed mistakenly, I have never seen this happen in testing (unless I had a bug) but it seemed …
=> Print through a single chromium instance cached in libs/printing

apps/admin/backend/src/exports/csv_shared.ts, apps/admin/backend/src/exports/csv_tally_report.test.ts, apps/admin/backend/src/reports/tally_report.ts, apps/admin/backend/src/reports/titles.test.ts, apps/admin/backend/src/reports/titles.ts, apps/admin/backend/test/mock_cvr_file.ts, apps/admin/frontend/src/components/reporting/filter_editor.test.tsx, apps/admin/frontend/src/components/reporting/filter_editor.tsx, libs/ui/src/reports/admin_tally_report.stories.tsx, libs/ui/src/reports/admin_tally_report.test.tsx, libs/ui/src/reports/admin_tally_report.tsx, libs/ui/src/reports/admin_tally_report_by_party.test.tsx, libs/ui/src/reports/admin_tally_report_by_party.tsx, libs/ui/src/reports/ballot_count_report.stories.tsx, libs/ui/src/reports/ballot_count_report.test.tsx, libs/ui/src/reports/ballot_count_report.tsx, libs/ui/src/reports/custom_filter_summary.test.tsx, libs/ui/src/reports/custom_filter_summary.tsx, libs/ui/src/reports/utils.ts, libs/ui/test/fixtures.ts
Closes #5420 
Instead of showing a truncated UUID when labeling batches in reports, show the human readable name (e.g. "Batch 1", "Batch 2", etc.). Also adds the human-readable name alongside the UUID in CSV reports.
https://github.com/user-attachments/assets/782f0d66-ddf6-4591-a0e2-f1100888e2d9
Updated automated tests and did some manual testing
=> VxAdmin: Show human-readable batch name in reports

apps/admin/backend/src/app.err_cdf_export.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/util/cdf_results.ts, apps/admin/backend/src/util/ncname.ts
https://github.com/votingworks/vxsuite/issues/5368
Fixes ERR validation errors on exported CDF ERR files from VxAdmin. The errors fall into 2 categories:
1. IDs are `NCName`s ([spec](https://www.w3.org/TR/xml-names/#NT-NCName)) which can only start with letters, `_`, or `.`. They also can't have the colon character, though our IDs are unlikely to include this character.
2. IDs must be globally unique, but we used the same candidate ID for both `Candidate` and `CandidateSelection` objects. 
The fixes are:
1. Prefix all IDs with `vx_` and remove the `:` character.
2. Use a concatenation of `contest` and `candidate` IDs for `CandidateSelection`. `CandidateSelection` describes the tally for a single candidate in in a single contest so this concatenation seemed like the most accurate option. …
=> CDF ERR export: conform to NCName and ID uniqueness constraints

apps/admin/frontend/src/screens/manual_data_entry_screen.test.tsx, apps/admin/frontend/src/screens/manual_data_entry_screen.tsx
Fixes #5450 
We already prevent adding two write-ins with the same name using the "Add" button, but forgot to also disable the Enter key, which enables you to erroneously add the candidate anyway.
Manual test and added regression test
=> VxAdmin: Manual tallies - disable adding write-in with enter key if button disabled

apps/scan/backend/jest.config.js, apps/scan/backend/src/scanners/custom/state_machine.ts
Rather than summarizing what's already been written in other places, I'm linking to relevant documents:
- [Original summary for SLI](https://github.com/user-attachments/files/17197857/VxScan.v3.1.Scan.Rejection.Investigation.pdf)
- [Approval letter from SLI](https://github.com/user-attachments/files/17197858/VotingWorks.VxScan.3.1_3.1.1.Evaluation.by.SLI.Compliance.pdf)
- [Summary for NH](https://github.com/user-attachments/files/17197859/Addressing.Elevated.Ballot.Rejection.in.VxScan.v3.1.1.pdf)
This is the only change that distinguishes v3.1.0 of the software from v3.1.1. Though we've already deployed this change, I'm opening this PR and merging to a proper v3.1.1 release branch for record keeping purposes.
=> Address elevated ballot rejection

libs/ballot-interpreter/src/__snapshots__/interpret_nh_hmpb.test.ts.snap, libs/ballot-interpreter/src/adjudication_reasons.test.ts, libs/ballot-interpreter/src/adjudication_reasons.ts, libs/utils/src/votes.test.ts, libs/utils/src/votes.ts
We've noticed that on a ballots with two ballot positions for the same candidate (due to a double party endorsement) we hit a couple interrelated tabulation bugs. First, when both positions are filled out, the scanner accepts the ballot (correct) but tabulates it as an overvote:
Second, we are not detecting overvotes when the second position is filled in, but the first is not. For example, this is not rejected as an overvote:
But this is correctly rejected as an overvote:
It seems that when we introduced double endorsements we broke with an underlying assumption that each candidate had only one ballot position, which we did not completely root out.
First, when we convert marks to votes, we were not deduplicating candidates. That is why the first example was eventually tabulated as an …
=> bug: handling double endorsement tabulation

apps/mark-scan/frontend/src/app_quit_on_idle.test.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark/frontend/src/app_quit_on_idle.test.tsx, apps/mark/frontend/src/app_root.tsx
Resolves https://github.com/votingworks/vxsuite/issues/5457
More context in [this slack thread](https://votingworks.slack.com/archives/C03Q42V9MJ5/p1727815213763589), but in summary, this code was added to force an exist and restart of the (pre-electron) kiosk browser to prevent a potential memory leak that was causing older versions of VxMark to crash after extended usage. Removing, since this is no longer an issue and hasn't come up on our other electron-based apps.
- Manual 
- ~[ ] I have added the …
=> [Mark|MarkScan] Remove old memory-leak-protection frontend restart logic

apps/scan/frontend/src/components/voter_settings_manager.test.tsx, apps/scan/frontend/src/components/voter_settings_manager.tsx
https://github.com/votingworks/vxsuite/issues/5348
Old behavior: after polls close and poll worker card removal, old settings/themes persist
https://github.com/user-attachments/assets/dc8584a4-4940-4571-bb2b-17562d73aba8
New behavior: after polls close and poll worker card removal, settings/themes reset
https://github.com/user-attachments/assets/06417712-b23e-413d-9678-6feb433710b3
=> Reset settings on poll close for VxScan

apps/admin/frontend/src/contexts/app_context.ts, libs/eslint-plugin-vx/package.json, libs/monorepo-utils/package.json, libs/res-to-ts/src/utils/assert.test.ts, package.json, pnpm-lock.yaml, script/package.json
Changes in v5.6: https://devblogs.microsoft.com/typescript/announcing-typescript-5-6/
I don't see anything that dramatically affects us. The change in `assert.test.ts` is due to the "Disallowed Nullish and Truthy Checks" change. Once we update Electron and NodeJS to versions that support it, the "Iterator Helper Methods" changes will remove some of the need for `iter` in `libs/basics`, but we can't use them yet.
n/a
Automated
=> chore(deps): update `typescript` to v5.6.2

apps/scan/backend/jest.config.js, apps/scan/backend/src/scanners/pdi/pdi_app_double_feed_calibration.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, libs/ballot-interpreter/src/hmpb-ts/interpret.ts, libs/ballot-interpreter/src/hmpb-ts/types.ts, libs/ballot-interpreter/src/interpret.ts
Task: #5459 
Updates the PDI scanner state machine to fail on unexpected errors, rather than try to reject the ballot and recover. This will enable us to fail fast and catch unexpected errors in testing rather than allow them to masquerade as unexplained unreadable ballots. This is especially useful for intermittent unexpected errors.
I also did a brief audit of the interpretation code paths to see if there were any other unexpected errors that were being converted into a rejected ballot rather than failing. I found one - a JSON parsing error - and modified it.
We use the existing unrecoverable error screen
Simulated an unexpected error and manual tested. Updated automated tests.
=> VxScan: Don't try to recover from unexpected errors during scanning

Cargo.lock, Cargo.toml, libs/ballot-interpreter/Cargo.toml, libs/ballot-interpreter/src/hmpb-rust/ballot_card.rs, libs/ballot-interpreter/src/hmpb-rust/diagnostic.rs, libs/ballot-interpreter/src/hmpb-rust/image_utils.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/js/mod.rs, libs/ballot-interpreter/src/hmpb-rust/scoring.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks.rs
We don't really use the `#[time]` output anymore for timing information.
=> chore(ballot-interpreter): remove unused dependency

apps/scan/backend/schema.sql, apps/scan/backend/src/app.ts, apps/scan/backend/src/app_export.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/store.test.ts, apps/scan/backend/src/store.ts, apps/scan/backend/src/types.ts, apps/scan/backend/test/helpers/custom_helpers.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app.tsx, apps/scan/frontend/src/app_root.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/cast_vote_record_sync_required_screen.test.tsx, apps/scan/frontend/src/screens/cast_vote_record_sync_required_screen.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, apps/scan/frontend/src/screens/poll_worker_screen.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts, libs/backend/src/cast_vote_records/file_system_utils.ts, libs/backend/test/utils.ts, libs/types/src/cast_vote_records.ts, libs/ui/src/cast_vote_records.test.ts, libs/ui/src/cast_vote_records.ts, libs/ui/src/error_boundary.tsx
It's long been known that a USB drive disconnect in the middle of a CVR export operation causes a crash. What's been less known is the likelihood of a sporadic disconnect without physical USB drive removal. We now have real data on that front and saw two sporadic USB drive disconnects in the field this past election. That's high enough that we've decided to improve the recovery flow for this case.
The current recovery flow is as follows:
1. Machine accepts or rejects ballot
2. Machine saves CVR to its own drive
3. Machine saves CVR to USB drive
4. USB drive disconnects mid-write
5. Machine crashes and displays the "Something went wrong" screen
6. User restarts
7. Machine detects that the USB drive is out of sync on boot and prompts the user to sync CVRs
8. Machine simplistically syncs all …
=> Software mitigation strategies for crashes and potentially time-consuming CVR resyncs following sporadic USB drive disconnects

libs/backend/src/logs/logs_api.test.ts, libs/backend/src/logs/logs_api.ts
In a previous round of testing, SLI observed incomplete log exports. The log export success modal appears quickly before logs have been fully flushed to the connected USB drive.
We've since fixed this issue on main for v4 (https://github.com/votingworks/vxsuite/pull/4770). This PR fixes this issue retroactively for v3.
=> Properly flush logs to USB drive before indicating success

libs/ballot-interpreter/src/__snapshots__/interpret_nh_hmpb.test.ts.snap, libs/ballot-interpreter/src/adjudication_reasons.test.ts, libs/ballot-interpreter/src/adjudication_reasons.ts, libs/utils/src/votes.test.ts, libs/utils/src/votes.ts
Part of #5455. See #5446 for details.
=> bug: handling double endorsement tabulation (`main`)

libs/ui/src/error_boundary.tsx
While working on the v3.1.2 patch for New Hampshire, I found a bug in our shared React error boundary logic that exists in v4 too.
If we ever encounter an unhandled promise rejection on the frontend, the error boundary will itself crash. Here's a simple contrived example:
```tsx
<Button onPress={() => Promise.reject(new Error('Uh oh!'))}>
Test
</Button>
```
The issue is just that we have an unbound method in our error boundary class. Non-React-lifecycle methods are not automatically bound.
https://github.com/user-attachments/assets/c03b44bd-ffd2-49ae-b3b0-600e309fe48d
https://github.com/user-attachments/assets/e423cbf1-03db-4c25-a4eb-7b3932123309
=> Fix bug in error boundary

apps/admin/backend/src/store.test.ts, apps/admin/backend/src/store.ts, apps/admin/frontend/src/screens/tally/manual_tallies_tab.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, libs/types/src/election.ts, libs/utils/src/ballot_styles.test.ts, libs/utils/src/ballot_styles.ts
https://github.com/votingworks/vxsuite/issues/5481
Removes getDefaultLanguageBallotStyles and updates use cases to use getGroupedBallotStyles instead. I added defaultLanguageBallotStyle as an explicit item in BallotStyleGroup to make the code in mark/mark-scan straight forward. 
Thanks for letting me do this as its own PR haha 
Ran tests, manually tested mark and mark-scan poll worker screen selection of ballot styles and changing language as the voter
=> Remove getDefaultLangaugeBallotStyles and update uses

apps/admin/frontend/jest.config.js, apps/admin/frontend/src/screens/tally/manual_tallies_tab.tsx, libs/utils/src/ballot_styles.test.ts, libs/utils/src/ballot_styles.ts, libs/utils/src/tabulation/lookups.ts
For cases where we have a group ID and want to look it up. I realized I needed this when I was rebasing another PR after the recent refactor to ballot styles.
N/A
Added new tests
=> utils: Add `getBallotStyleGroup` helper

libs/dev-dock/backend/src/dev_dock_api.ts, libs/dev-dock/frontend/src/dev_dock.test.tsx, libs/dev-dock/frontend/src/dev_dock.tsx
The dev dock today just hard codes a few fixtures elections, I find this frustrating when I'm working with other elections so I am proposing we just generate this list from the fixtures/data directory and look for any subfolders with an election*.json file inside. 
Next step would be to add a way to autopopulate the mock usb drive with the election package for the current selected election (maybe with different system settings options) 
Used dev dock
=> Update dev dock to have full list of fixtures elections

apps/admin/backend/src/app.manual_results.test.ts, apps/admin/backend/src/app.ts, apps/admin/backend/src/types.ts, apps/admin/backend/src/util/manual_results.ts, apps/admin/frontend/jest.config.js, apps/admin/frontend/src/components/app_routes.tsx, apps/admin/frontend/src/config/types.ts, apps/admin/frontend/src/router_paths.ts, apps/admin/frontend/src/screens/tally/cast_vote_records_tab.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.test.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_tab.test.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_tab.tsx, apps/admin/frontend/src/screens/write_ins_adjudication_screen.tsx, apps/admin/frontend/test/api_mock_data.ts, apps/admin/frontend/test/helpers/mock_api_client.ts, apps/design/frontend/src/ballot_screen.tsx, libs/ui/src/global_styles.tsx, libs/ui/src/task_screen.tsx, libs/utils/src/tabulation/tabulation.test.ts, libs/utils/src/tabulation/tabulation.ts
Reworks the manual tally entry flow to address a number of UX issues. The main changes:
- Enter and save tallies for one contest at a time 
Fixes #5390 
Fixes #5381
- Default tallies to blank, not 0, and disallow saving until you fill out all the tallies 
Fixes #5295
- Enter an overall ballot count once at the beginning, then allow overriding for a specific contest if needed
Fixes #5407
https://github.com/user-attachments/assets/7183bb99-bee3-40b5-95e7-288d4de3a036
Manual testing, updated automated tests
=> VxAdmin: Polish manual tally entry flow

apps/admin/frontend/src/api.ts, apps/admin/frontend/src/app.test.tsx
I noticed that VxAdmin would crash after the following sequence:
- Configure with election A
- Create manual tallies
- Unconfigure
- Configure with election B
- Go to the manual tallies screen
The error was happening because we were [looking up a precinct ID](https://github.com/votingworks/vxsuite/blob/c517faaf2666328be9ac157999db0a57fc2a7f30/apps/admin/frontend/src/screens/tally/manual_tallies_tab.tsx#L414-L417) from the manual tallies in the election, but not finding it. This made me think that there was still cached manual tally data from the previous election that was being rendered while the new election's manual tally data was being fetched.
To prevent this from happening, I changed the logic to clear the cache after unconfiguring instead of just invalidating the queries.
Skipping …
=> VxAdmin: Clear query cache on unconfigure

apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.test.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5215
This is important when the tallies don't match the ballots cast - you need to know how many votes are allowed per voter so you can do the math to work out the expected number of votes.
Updated tests
=> VxAdmin: Show votes allowed in manual tally form

apps/admin/backend/src/app.write_ins.test.ts, apps/admin/backend/src/util/write_ins.ts
Fixes #5202 
Previously, we used ballot image dimensions based on the interpreter's computed page geometry. This doesn't always match the actual image size, since the interpreter just looks for the closest known page size (e.g. letter, legal). This was causing the write-in adjudication highlight to be slightly off, since the actual image dimensions rarely match the idealized page size exactly. To fix it, we just use the actual image dimensions instead of the idealized ones.
Before
After
Manual test, updated backend test
=> VxAdmin: Use correct image dimensions in write-in adjudication highlight

apps/admin/backend/src/exports/csv_ballot_count_report.test.ts, apps/admin/backend/src/store.ts
Currently, tally report sections / ballot count report rows are ordered by precinct ID rather than precinct name - if precinct is included in the grouping (and batch + scanner is not). The ordering problem is bigger, and I created #5501 to track for v4.1, but this seems like a safe change to sneak in for v4.0. Previously we didn't see this issue because we mostly used fixtures where the IDs were just lowercased versions of the names, but that is not be the case for VxDesign.
=> sort reports by precinct name rather than ID

apps/admin/frontend/src/screens/diagnostics_screen.test.tsx, libs/ui/src/diagnostics/printer_section.test.tsx, libs/ui/src/diagnostics/printer_section.tsx
=> show printer success icon for VxAdmin printer diagnostics as long as its connected

apps/admin/frontend/src/api.ts, apps/admin/frontend/src/app.test.tsx, apps/central-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/api.ts, apps/mark-scan/frontend/src/api_machine_configuration.test.tsx, apps/mark-scan/frontend/src/app_end_to_end.test.tsx, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/api_machine_configuration.test.tsx, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx
Follow up to #5494, applied to all apps. Ensures that there's no outdated data in the cache after unconfiguring. Uses `resetQueries` instead of `clear` so that we can await the refetch of currently active queries.
Note that I couldn't update apps/mark since it caused the app to crash. I didn't look too deeply into what would need to be fixed, but since we're not currently using apps/mark, it doesn't seem worthwhile.
N/A
Manual tested unconfigure on each app, updated automated tests
=> Clear cached query data on unconfigure in all apps

libs/mark-flow-ui/src/components/contest_header.tsx, libs/mark-flow-ui/src/components/contest_screen_layout.tsx, libs/mark-flow-ui/src/components/yes_no_contest.test.tsx, libs/mark-flow-ui/src/components/yes_no_contest.tsx
https://github.com/votingworks/vxsuite/issues/5515
Fixes a bug where ballot measure description is not shown when using XL display settings.
This change always shows the contest options and allows scrolling of the measure title and description (rather than include contest options in the scroll box). I thought this was preferable because it would cut down on repetitive scrolling for voters who know how they want to vote based on contest title alone.
**Medium**
**Large**
**XL**
**Video of scrolling behavior**
https://github.com/user-attachments/assets/11d10f2c-d81b-46b0-896f-0e88c9f895ae
* Manual testing
=> fix disappearing measure description

apps/mark-scan/frontend/src/app_root.tsx
Closes #5523. Allows the vendor and system admin screens to be accessed in hardware error states.
=> allow system admin to access system even in hardware error states

apps/mark-scan/backend/src/util/render_ballot.test.ts
Followup to https://github.com/votingworks/vxsuite/pull/5545, which removed `LanguageCode` from machine code paths, but wasn't rebased on the latest main - cleaning up the last reference from the most recent commit.
=> Update reference to removed LanguageCode enum

libs/mark-flow-ui/src/components/candidate_contest.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/yes_no_contest.test.tsx, libs/mark-flow-ui/src/components/yes_no_contest.tsx, libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
Closes https://github.com/votingworks/vxsuite/issues/5315
When voters make a selection, we play audio reading out the number of remaining votes.
This updates that audio when the final available selection in a contest is made, to make it clearer that the voter can advance to the next contest.
https://github.com/user-attachments/assets/75eb5040-db3d-4d6a-aa05-80e78d632d1b
- Unit tests and manual verification with generated audio
=> [BMD] Provide clearer audio feedback after using all votes in a contest

libs/backend/src/system_call/export_logs_to_usb.ts
Closes https://github.com/votingworks/vxsuite/issues/5346
To avoid user confusion, this updates filenames on log export directories to reflect the date/time in the locale of the machine they were saved from, instead of using the UTC date/time, which might not match the day of the election at first glance.
Initially went with a format that included the timezone code at the end, but later found the utility used for our CVR exports, so just using that to be consistent.
- Tried out a logs export on MarkScan before and after the change.
- ~[ ] I have added a screenshot and/or video to …
=> Update log export filenames to use locale timestamps instead of UTC

libs/pdi-scanner/build.rs, libs/pdi-scanner/src/rust/scanner.rs
Closes #5541
```
❯ cargo run --example scan_forever --release
Compiling pdi-scanner v0.1.0 (/media/parallels/WorkingFiles/code/vxsuite/libs/pdi-scanner)
Finished `release` profile [optimized] target(s) in 1.53s
Running `/media/parallels/WorkingFiles/code/vxsuite/target/release/examples/scan_forever`
waiting for sheet…
event: BeginScanEvent
event: EndScanEvent
Saved images from scan:
- Top: scan-0000-top.png
- Bottom: scan-0000-bottom.png
waiting for sheet…
^Creceived SIGINT
exiting
❯ NODE_ENV=production cargo run --example scan_forever --release
Compiling pdi-scanner v0.1.0 (/media/parallels/WorkingFiles/code/vxsuite/libs/pdi-scanner)
Finished `release` profile [optimized] target(s) in 3.28s
Running `/media/parallels/WorkingFiles/code/vxsuite/target/release/examples/scan_forever`
Error: …
```
=> fix(pdi-scanner): use a smaller USB buffer in development

apps/central-scan/backend/src/app.scanning.test.ts, apps/central-scan/backend/src/importer.ts, apps/central-scan/backend/src/store.ts, apps/central-scan/frontend/src/screens/ballot_eject_screen.test.tsx, apps/central-scan/frontend/src/screens/ballot_eject_screen.tsx, apps/scan/backend/src/app_scanning.test.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/src/store.ts, libs/backend/src/cast_vote_records/export.ts, libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/js/args.rs, libs/ballot-interpreter/src/hmpb-rust/js/image_data.rs, libs/ballot-interpreter/src/hmpb-rust/js/mod.rs, libs/ballot-interpreter/src/hmpb-ts/cli.ts, libs/ballot-interpreter/src/hmpb-ts/interpret.ts, libs/ballot-interpreter/src/hmpb-ts/rust_addon.d.ts, libs/ballot-interpreter/src/interpret.ts, libs/ballot-interpreter/src/types.ts, libs/types/src/system_settings.ts
Closes https://github.com/votingworks/vxsuite/issues/5538
Adds a system setting that disables streak detection for an election. We might want this in case of a ballot design that triggers false positives when looking for streaks. Because we support taking someone else's AccuVote-style ballot, we may not be able to ensure no streaks are naturally present in the original image. This is unlikely, but this gives us an escape hatch.
Automated testing and manual testing of VxCentralScan via `MOCK_SCANNER_FILES`.
=> Add vertical streak detection controls

apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.tsx
An addendum to the series of copy change PRs, changes the options on the open / close / resume prompt to be a little more direct and reformats the poll worker menu to match other screens.
| -------- | ------- |
| <img width="1060" alt="Screen Shot 2024-10-29 at 10 59 35 AM" src="https://github.com/user-attachments/assets/c46f605e-3968-4343-8c29-72ae21709420">  | <img width="1060" alt="Screen Shot 2024-10-29 at 12 29 27 PM" src="https://github.com/user-attachments/assets/0bef5473-521c-40ec-9529-80db1bf8bc91">|
| <img width="1059" alt="Screen Shot 2024-10-29 at 10 59 46 AM" src="https://github.com/user-attachments/assets/3f9b525d-525a-4bd6-92c3-3b021d77c35e"> |<img width="1060" alt="Screen Shot 2024-10-29 at 10 28 39 AM" …
=> V4 PW Flow Tweaks

apps/central-scan/backend/src/end_to_end_bmd.test.ts, apps/central-scan/backend/src/fujitsu_scanner.ts, apps/central-scan/backend/src/importer.ts, apps/central-scan/backend/src/util/workspace.ts
When scanning ballots in VxCentralScan we use `scanimage`, which puts images on disk. We then read them, interpret them, normalize them, and write them to disk at a new location of our choosing. This second image per side is the only one we really care about, and the first is just taking up space. To fix this, we now delete the directory we create for batches after the batch is completely scanned.
Additionally, this commit removes the `Workspace::scannedImagesPath` property and stops creating the `scanned-images` directory in the workspace. Before we put files for a given batch in their own directory we would put them in this directory. That hasn't been true in some time.
Watched the `ballot-images` directory during and after scanning, and added automated tests.
```
❯ tree …
```
=> fix(central-scan): only keep two images per scanned sheet

apps/central-scan/backend/src/end_to_end_bmd.test.ts, apps/central-scan/backend/src/fujitsu_scanner.test.ts, apps/central-scan/backend/src/fujitsu_scanner.ts, apps/central-scan/backend/src/importer.ts, apps/central-scan/backend/src/util/workspace.ts
Ever since #4994 we call `scanimage` twice when starting a batch, once to determine whether an imprinter is present and once to actually start the scan. Both invocations require communicating with the scanner, which means both need to open the USB device. Because we previously resolved the `isImprinterAttached` promise early in the case where the expected error message is present, the first `scanimage` instance could still be running and holding the USB device open when we try to run the second `scanimage` instance. When that happens, the second instance would fail to open the USB device and we'd get a zero-sheet batch and this error message: `scanimage: open of device fujitsu failed: Invalid argument`.
In my testing on macOS host with a Debian VM with the attached fi-7180, this happens …
=> fix(central-scan): prevent `scanimage` race

apps/admin/frontend/src/screens/smart_cards_screen.test.tsx, apps/admin/frontend/src/screens/smart_cards_screen.tsx
=> Remove Stray `assert` to allow programming sys admin cards when VxAdmin is unconfigured

apps/scan/frontend/src/screens/poll_worker_screen.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.tsx
=> always allow polls transitions when continuous export is disabled

libs/auth/src/intermediate-scripts/compute-system-hash, libs/auth/src/signed_hash_validation.ts
This PR changes the control flow of signed hash valildation. Rather than having `vxsuite` call a `vxsuite-complete-system` script, this PR brings the core script directly into `vxsuite`. This allows us to remove a lot of the previous special-casing for local dev vs. prod.
In the process, this fixes a bug that was causing us to display the UNVERIFIED placeholder hash for locked-down images instead of the real hash. The source of that bug was a faulty existence check for a script in `vxsuite-complete-system`. While the script did exist (`/vx/vendor/vendor-functions/hash-signature.sh`), it was only visible to the `vx-vendor` user, not the `vx-services` user.
Corresponding `vxsuite-complete-system` change: https://github.com/votingworks/vxsuite-complete-system/pull/412
=> Change SHV control flow

apps/mark-scan/frontend/src/pages/validate_ballot_page.tsx
Issue link: https://github.com/votingworks/vxsuite/issues/5598
Currently, on the final validation screen in VxMark, when you're given the two options, `My Ballot is Incorrect` and `Cast My Ballot`, if you press the left button on the controller, we auto-click `My Ballot is Incorrect`, which rejects your ballot and has the poll worker spoil it so that you can start over.
I'm 99% sure that that wasn't intentional, just an artifact of us intentionally auto-clicking the `Previous` button on controller left press on contest screens.
Quick fix 🛠️
=> VxMark: Don't auto-click "My Ballot is Incorrect" on controller left press

apps/central-scan/backend/src/fujitsu_scanner.test.ts, apps/central-scan/backend/src/fujitsu_scanner.ts
Issue link: https://github.com/votingworks/vxsuite/issues/5594
With 22" ballots on VxCentralScan, we've sporadically seen interpretation fail because timing marks are clipped, ~circled~ squared in red above.
To address this, we're adding some buffer to the page height param that we specify to the Fujitsu. Scanning extra is safe because the HMPB interpreter trims any extra scan area. In fact, we already rely on this trimming when scanning letter HMPBs, as we specify the BMDB height for that case (13.25 inches > 11 inches).
=> VxCentralScan: Ensure that HMPB timing marks aren't clipped

libs/ballot-interpreter/src/bmd/utils/qrcode.test.ts, libs/ballot-interpreter/src/bmd/utils/qrcode.ts, libs/ballot-interpreter/src/interpret.ts
Issue link: https://github.com/votingworks/vxsuite/issues/5593
In our final v4 QA, we found that BMDBs only scan in one orientation on VxCentralScan when it's configured for 22" HMPBs.
We search for a QR code in the top and bottom halves of the image, but under the following circumstances:
- VxCentralScan, which doesn't auto-crop when it hits the end of the paper
- 22" HMPBs
- BMDB is inserted into the scanner right side up, which results in an upside down image
The QR code happens to fall right in between the two halves. To mitigate this, we're updating the bottom search area to really be the bottom 60% of the image. The top search area is still the top 50% of the image, not 40%. We could probably change that, but I'm playing it safe and trying not to introduce another edge case at …
=> VxCentralScan: Support BMDBs in all orientations when configured for 22" HMPBs

apps/mark-scan/frontend/src/components/centered_card_page_layout.tsx, apps/mark-scan/frontend/src/pages/load_paper_page.tsx, libs/ui/src/bmd/index.ts, libs/ui/src/bmd/load_paper_animation.tsx, libs/ui/src/index.ts
Closes https://github.com/votingworks/vxsuite/issues/5108
Adding a graphic to the poll-worker-facing `Load Ballot Shee` screen to demonstrate proper sheet orientation.
Out of scope:
- This screen is reused in the `Insert Printed Ballot` flow, but the graphic will still show up as a blank sheet. We could follow up later and add a flag to optionally render ballot content if we think that's confusing for users.
https://github.com/user-attachments/assets/68cd98da-a447-4521-80b4-fdec5e43ec13
- Manual
=> [BMD] Add notched paper graphic to 'Load Ballot Sheet' screen

libs/ballot-interpreter/src/bmd/utils/qrcode.test.ts, libs/ballot-interpreter/src/bmd/utils/qrcode.ts
I've been noticing some sporadic crashes on interpretation in VxMark (Frankenstein) after applying https://github.com/votingworks/vxsuite/pull/5602. I found that this assert is sometimes failing:
https://github.com/votingworks/vxsuite/blob/3f79e47a935f0c3dfd4a94040cf264071b92cf1b/libs/ballot-interpreter/src/bmd/utils/luminosity.ts#L34
This indicates that we're attempting to read a pixel outside the bounds of the image.
I boiled this down to an issue with using `Math.round` when defining search areas. Take the super simple case of an image with width 1 and height 3:
```
0
0
0
```
The current computation will return the following bottom search area:
```
const heightMidpoint = Math.round(size.height / 2);
yield {
position: 'bottom',
bounds: {
x: 0,
y: heightMidpoint - Math.round(size.height …
```
=> Address off-by-one error in BMDB interpreter that can result in a crash on BMDB interpretation

libs/custom-paper-handler/src/driver/driver.ts
Ignores an initial "ack" if seen on the transfer in endpoint when scanning. We have sporadically seen this in weird situations and ignoring it seems harmless. Note that @eventualbuddha has seen issues with scanning the image after this in dev but we have not repro'd those testing with images.
=> Ignore an initial ack in custom printer driver scan command

apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts
Follow-up to https://github.com/votingworks/vxsuite/issues/3873
Fixes a bug in the BMD cover-open alarm logic so that the alarm is only triggered when polls are open.
- Added new test case for the `polls_closed` + `cover_open` state combination
=> [BMD] Stop triggering open-cover alarm when polls aren't open

libs/ui/src/ui_strings/language_context.test.tsx
Fixing a [flaky test](https://app.circleci.com/pipelines/github/votingworks/vxsuite/17098/workflows/5671de94-9d2c-4e29-9c06-8717ff242970/jobs/674164) in libs/ui
Was caused by the combination of a recent change to clear the i18next cache when unconfiguring a machine and the fact that this test was sharing a render context across test cases (so changes to the i18next cache in one case were affecting another).
Updating to create a new context for each test case.
- Reproduced the failure consistently by changing the order of the tests so that the unconfigure test runs first.
- Verified that this change gets the tests passing again.
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file …
=> Fix flaky language_context test in libs/ui

apps/mark-scan/backend/src/audio/outputs.test.ts, apps/mark-scan/backend/src/audio/outputs.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/src/globals.ts
We have some signal that attempting to run the `pactl set-sink-port` command too early after boot-up (which happens if we start up with the printer cover open), the `pulse audio` service may not be running yet or fully spun up.
This adds two retries with delays to attempt to wait until `pulse audio` is ready to run the command.
- Patch was tested on a VSAP 150 that seemed to be running into the issue and verified that it at least prevents crashes on startup.
- Unit tests for the retry logic
=> [BMD] Add retries to pulse audio command for output selection

CONTRIBUTORS.md
Add a contributors list and in particular include VotingWorks pioneers, the election administrators who piloted VotingWorks when it was just a prototype.
=> start contributors

libs/ballot-interpreter/src/hmpb-rust/image_utils.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-ts/__snapshots__/interpret.test.ts.snap, libs/ballot-interpreter/src/hmpb-ts/interpret.test.ts
When a ballot has a significant skew (>= 1 degree), the previous implementation of `find_scanned_document_inset` would cause too much of the ballot to be cropped out of the image. Because it would only stop cropping once the white pixels were half of a given row, the portion of a skewed ballot that would be cropped was likely to contain timing marks. At the very least, it was likely to partially or completely crop the corner timing mark, which we require in order to proceed with interpretation.
The new implementation takes a configurable ratio of white to black pixels at which to stop cropping, which we now set to 10% (vs the previous 50%). This makes the cropping much more conservative while still cropping off any edge rows/columns of pure black. This preserves the corner timing marks …
=> fix(scan): improve acceptance rate of skewed ballots

apps/admin/frontend/src/components/sidebar.tsx, apps/admin/frontend/src/screens/machine_locked_screen.tsx, apps/central-scan/frontend/src/navigation_screen.tsx, apps/central-scan/frontend/src/screens/machine_locked_screen.tsx, apps/mark-scan/frontend/src/app_root.tsx, apps/mark-scan/frontend/src/pages/system_administrator_screen.test.tsx, apps/mark-scan/frontend/src/pages/system_administrator_screen.tsx, apps/mark/frontend/src/pages/admin_screen.tsx, apps/scan/frontend/src/components/layout.tsx, apps/scan/frontend/src/screens/system_administrator_screen.tsx, libs/ui/src/election_info_bar.test.tsx, libs/ui/src/election_info_bar.tsx
Makes sure the code version is always accessible from a sysadmin screen when a machine is unconfigured. 
Changed all apps to show ElectionInfoBar in unconfigured states.
Added ElectionInfoBar to system administrator screen in MarkScan
I do want to call out this as a nontrivial change in terms of number of screenshots in the docs it might touch @adghayes 
Loaded various apps
=> [All Apps] Add code version & footer to sys admin views

libs/ui/src/ui_strings/app_strings.tsx, libs/ui/src/ui_strings/app_strings_catalog/latest.json
Spotted while preparing strings for vendor translation - this entry has a stray quotation mark at the end.
N/A - audio-only string
N/A
=> [BMD] Fix typo in audio string

apps/admin/frontend/src/screens/smart_cards_screen.test.tsx, apps/admin/frontend/src/screens/smart_cards_screen.tsx, libs/auth/src/dipped_smart_card_auth.test.ts, libs/auth/src/dipped_smart_card_auth.ts
Some quick patches around vendor card edge cases in the VxAdmin smart card UI. The current behavior in the VxAdmin smart card UI is as follows:
1. Insert a vendor card programmed for that jurisdiction and it shows up in the UI as a vendor card, with no actions
2. Insert a universal vendor card (with the special `*` jurisdiction) and it shows up in the UI as a blank card that can be overwritten
3. Insert a vendor card programmed for another jurisdiction and it shows up in the UI as a blank card that can be overwritten
4. For 1 and 2, we show a "Modify Card" heading despite the fact that you can't take any modification actions
After this PR:
1. **UNCHANGED** Insert a vendor card programmed for that jurisdiction and it shows up in the UI as a vendor card, with no actions
2. **CHANGED** …
=> Address vendor card edge cases in VxAdmin smart card UI

apps/mark-scan/frontend/src/pages/pat_device_identification/identify_input_step.tsx, apps/mark-scan/frontend/src/pages/pat_device_identification/pat_introduction_step.tsx
Fixes https://github.com/votingworks/vxsuite/issues/5630
We've noticed inconsistent responsiveness to PAT device inputs in the calibration flow - debug logging shows the event listener getting added and removed frequently (likely in response to data fetches from API polling).
Updating the related React hook dependency lists to avoid the thrash.
- Repro'd semi-consistently (took at least 2 key-press attempts to register) and then verified that inputs are responsive on single-key presses after the change.
- …
=> [BMD] Fix unstable event listeners in PAT device calibration flow

apps/mark-scan/backend/jest.config.js, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, libs/backend/src/exceptions.ts, libs/ui/src/error_boundary.test.tsx, libs/ui/src/error_boundary.tsx
In debugging the VxMark state machine during final QA, we weren't able to get much out of the box from the VxMark state machine unknown-error log because it was missing a stacktrace. And the message was sometimes empty, e.g., because it was coming from an `assert`.
This PR adds stacktrace to that log, which will be important as we actually deploy VxMarks and want meaningful logs for investigations into in-field reports.
I also took a pass through the major unknown-error logs and tweaked them to all 1) use consistent field names and 2) use type-safe means of extracting error messages since errors aren't always guaranteed to be `Error` objects.
=> Add stacktrace to VxMark state machine unknown-error log

libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks.rs
Fix some lints pointed out by clippy @ Rust 1.81.0.
=> style(scan): fix clippy lints

libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
This ensures that, if we somehow get an `IteratorPlus<Promise<T>>`, that calling `.async()` will return an `AsyncIterablePlus<T>`, not an `AsyncIterablePlus<Promise<T>>`. This is both more correct and improves the ergonomics of async iterables.
Added a type assertion.
=> fix(basics): correct the type of `iter::async`

apps/admin/backend/src/app.ts, apps/admin/backend/src/server.ts, apps/central-scan/backend/src/app.ts, apps/central-scan/backend/src/server.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/server.ts, apps/mark/backend/src/app.ts, apps/mark/backend/src/server.ts, apps/scan/backend/src/app.ts, apps/scan/backend/src/server.ts, libs/dev-dock/backend/jest.config.js, libs/dev-dock/backend/src/dev_dock_api.test.ts, libs/dev-dock/backend/src/dev_dock_api.ts, libs/dev-dock/frontend/jest.config.js, libs/dev-dock/frontend/src/dev_dock.test.tsx, libs/dev-dock/frontend/src/dev_dock.tsx
Instead of passing in the machine type (i.e. `scan` or `admin`) to the dev dock and then conditioning internally to determine the printer mocks, pass the printer config in as a parameter.
This change set up a pattern for passing in more machine-specific values to the dev dock (e.g. a handler for the mock PDI scanner).
Also moves the call to `useDevDockRouter` from `app.ts` to `server.ts` (we'll need this for the mock PDI scanner in apps/scan, so doing it everywhere for consistency).
N/A, just a refactor
=> dev-dock: Parameterize printer mock config rather than machine type

apps/scan/backend/src/index.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_disconnect.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/test/helpers/pdi_helpers.ts
Instead of passing a function to create a PDI scanner client to the state machine, create the client in the server.ts module and pass it into the state machine. In previous scanner integrations, we wanted to create new clients after failures. However, in this integration, we don't do that and instead just crash the app (part of our "fail fast" approach), so we don't ever need to recreate the client.
This refactor also prepares for introducing a mock PDI scanner client, which will also be a singleton. Since it will be referenced by the dev dock as well, it will need to be created in server.ts.
N/A
Existing automated tests
=> scan/backend: Refactor PDI scanner client creation

libs/logging/package.json
The tests were assuming UTC timezone, so running in any other timezone fails. CI runs in UTC by default, so that was going fine.
=> test(logging): fix local test running

apps/mark-scan/frontend/src/apimachine_config.test.tsx, apps/mark-scan/frontend/test/helpers/timers.ts, apps/mark/frontend/src/pages/admin_screen.test.tsx, apps/mark/frontend/src/pages/diagnostics_screen.test.tsx, apps/mark/frontend/test/helpers/timers.ts, apps/scan/frontend/src/app.test.tsx, libs/test-utils/src/advance_timers.ts, libs/ui/src/accessible_controllers/accessible_controller_sandbox.test.tsx, libs/ui/src/hooks/use_headphones_plugged_in.test.ts, libs/ui/src/ui_strings/ui_string_screen_reader.test.tsx
This way we can replace the `jest` with `vi` at individual callsites as we get to them.
=> refactor(jest): inline calls to `advanceTimers`

apps/central-scan/backend/test/helpers/setup_app.ts, apps/mark-scan/frontend/src/apimachine_config.test.tsx, apps/mark-scan/frontend/test/helpers/timers.ts, apps/mark/frontend/src/pages/admin_screen.test.tsx, apps/mark/frontend/src/pages/diagnostics_screen.test.tsx, apps/mark/frontend/test/helpers/timers.ts, apps/scan/frontend/src/app.test.tsx, libs/auth/package.json, libs/auth/src/test_utils.ts, libs/test-utils/src/advance_timers.ts, libs/ui/src/accessible_controllers/accessible_controller_sandbox.test.tsx, libs/ui/src/hooks/use_headphones_plugged_in.test.ts, libs/ui/src/ui_strings/ui_string_screen_reader.test.tsx, pnpm-lock.yaml
Refs #5740 
Unblocks converting packages using mocks from `libs/auth` from `jest` to `vitest`.
=> feat(auth): allow passing the mock `fn` to use

apps/admin/backend/test/setup_custom_matchers.ts, apps/central-scan/backend/test/setup_custom_matchers.ts, apps/design/backend/test/setupTests.ts, apps/mark-scan/backend/test/setup_custom_matchers.ts, apps/mark/backend/test/setup_custom_matchers.ts, apps/scan/backend/test/setup_custom_matchers.ts, libs/image-utils/src/jest_pdf_snapshot.ts, libs/printing/test/setupTests.ts
Enables using `toMatchPdfSnapshot` with `vitest` by turning the matcher function into a matcher builder.
n/a
Automated.
=> feat(image-utils): enable `toMatchPdfSnapshot` with `vitest`

libs/auth/src/cryptography.ts
Missed this back when I opened https://github.com/votingworks/vxsuite/pull/5620. The config file referenced by this variable no longer exists, and this variable is also now unused.
=> Remove outdated and now unused variable

libs/auth/scripts/generate-root-cert-authority-key-and-cert, libs/auth/scripts/src/check_pin.ts, libs/auth/scripts/src/generate_dev_keys_and_certs.ts, libs/auth/scripts/src/generate_root_cert_authority_key_and_cert.ts, libs/auth/scripts/src/mock_card.ts, libs/auth/scripts/src/utils.ts, libs/auth/src/certs.ts
This PR adds a script for generating a root CA key and cert:
```
$ ./scripts/generate-root-cert-authority-key-and-cert 
Options:
--common-name  The common name to use in the cert subject             [string]
--output-dir   The directory to output the generated key and cert to  [string]
Examples:
$ generate-root-cert-authority-key-and-cert --help
$ generate-root-cert-authority-key-and-cert \
--common-name "VotingWorks Development" --output-dir path/to/output-dir
```
```
$ ./scripts/generate-root-cert-authority-key-and-cert --common-name "Test 1234" --output-dir ~/test-1234
🔑 Generating private key
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
Private key written to: /home/vx/test-1234/private-key.pem
🔏 Generating cert
Enter pass phrase for /home/vx/test-1234/private-key.pem: …
```
=> Add script for generating a root CA key and cert

docs/exercises/.eslintignore, docs/exercises/README.md, docs/exercises/jest.config.js, docs/exercises/package.json, docs/exercises/src/example.ts, docs/exercises/vitest.config.ts, pnpm-lock.yaml
=> test(docs): replace `jest` with `vitest`

libs/grout/test-utils/.eslintignore, libs/grout/test-utils/jest.config.js, libs/grout/test-utils/package.json, libs/grout/test-utils/src/mock_client.test.ts, libs/grout/test-utils/src/mock_client.ts, libs/grout/test-utils/vitest.config.ts, pnpm-lock.yaml
=> test(grout/test-utils): replace `jest` with `vitest`

libs/grout/.eslintignore, libs/grout/jest.config.js, libs/grout/package.json, libs/grout/src/grout.test.ts, libs/grout/src/serialization.test.ts, libs/grout/vitest.config.ts, pnpm-lock.yaml, vitest.config.shared.mts
=> test(grout): replace `jest` with `vitest`

libs/mark-flow-ui/src/components/candidate_contest.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/contest.tsx, libs/mark-flow-ui/src/pages/contest_page.tsx, libs/ui/src/button.tsx, libs/ui/src/index.ts, libs/ui/src/virtual_keyboard/common.ts, libs/ui/src/virtual_keyboard/scan_panel_virtual_keyboard.test.tsx, libs/ui/src/virtual_keyboard/scan_panel_virtual_keyboard.tsx, libs/ui/src/virtual_keyboard/scan_panels/key_button.tsx, libs/ui/src/virtual_keyboard/scan_panels/scan_panel.tsx, libs/ui/src/virtual_keyboard/scan_panels/scan_panel_row.tsx, libs/ui/src/virtual_keyboard/virtual_keyboard.test.tsx, libs/ui/src/virtual_keyboard/virtual_keyboard.tsx
Adds scan panels to the candidate write-in screen. See [this doc](https://docs.google.com/document/d/1nan1Gwrb0CCC757h1UYK4pdGVmiUwSfuuZ2-VNZ_hpQ/edit?tab=t.0#heading=h.77fs298fyke8) for more details.
There are a few necessary follow-ups that I think should be in separate PRs to keep diff size down:
* audio strings for rows and scan panels
* resetting focus state after
* tabbing through all scan panels in a row twice
* tabbing through all keys in a scan panel twice
* remapping ATI controller direction pad for the default virtual keyboard
Note that the row with `Space` and `Delete` is a row of a single scan panel, so a voter needs to select the row, then the scan panel, and finally the desired key. I went back and forth on this decision but landed this way because
* it maintains …
=> Switch scanning for write-ins

libs/ui/src/virtual_keyboard/scan_panel_virtual_keyboard.test.tsx, libs/ui/src/virtual_keyboard/scan_panel_virtual_keyboard.tsx, libs/ui/src/virtual_keyboard/scan_panels/key_button.tsx, libs/ui/src/virtual_keyboard/scan_panels/scan_panel.tsx, libs/ui/src/virtual_keyboard/scan_panels/scan_panel_row.tsx
Small QOL change for the switch scanning keyboard for write-ins
* Focus the first row when the keyboard is first rendered
* After a row/panel/key is selected, focus the first child
* Row selected -> focus first panel
* Panel selected -> focus first key
https://github.com/user-attachments/assets/b7d1af23-9d02-4417-b7a3-ce49992ce770
Updated existing tab/enter test to expect focus without tabbing
=> automatically focus the first row/panel/key on first render and after making selections

apps/design/backend/src/candidate_rotation.test.ts, apps/design/backend/src/candidate_rotation.ts, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, libs/types/src/election.ts
* Adds structured first, middle, and last name inputs to VxDesign candidate contest creation
* Prefers to sort by last name, first name, and finally full concatenated name
https://github.com/user-attachments/assets/0cac2142-99a1-4f10-a2b9-e22978e20faf
- Added tests to `contests_screen.test.tsx` and `candidate_rotation.test.ts`
=> vxdesign structured name input

apps/design/backend/package.json, apps/design/backend/schema.old.sql, apps/design/backend/scripts/db_reset_dev.sh, apps/design/backend/src/db/client.ts, apps/design/backend/src/db/db.ts, apps/design/backend/src/store.ts, pnpm-lock.yaml
https://github.com/votingworks/vxsuite/issues/5698
Adding (unused) postgres client lib to VsDesign for the upcoming conversion from sqlite.
Currently using the default setup and relying on the standard postgres [environment variables](https://www.postgresql.org/docs/current/libpq-envars.html), which are assigned accordingly in the Heroku dashboard (https://dashboard.heroku.com/apps/tmp-vxdesign-dev/settings).
Will eventually need  a schema migration tool, but for now, just adding a `db:reset` pnpm script for dev.
- Manual for now - will set up testing in upcoming PRs, when we start wiring up the store code.
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates such as file reads or storage …
=> [Design] Add Postgres client management code

apps/design/frontend/src/app.tsx, apps/design/frontend/src/ballot_screen.test.tsx, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/features_context.test.tsx, apps/design/frontend/src/features_context.tsx, apps/design/frontend/src/features_provider.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/tabulation_screen.test.tsx, apps/design/frontend/test/api_helpers.tsx
Related to https://github.com/votingworks/vxsuite/issues/5795
Adds a `FeaturesContext` to expose feature configuration by state. Right now it's just NH vs not-NH but eventually we'll want to support different configurations for NH, MS, and VX users.
I added the "Bubble Position" SegmentedControl for illustration, but it's not wired up to anything yet.
https://github.com/user-attachments/assets/0c2ec8a1-79d0-4779-9988-5c1cf1ca627c
=> add features provider

apps/design/backend/schema.sql, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/ballots_screen.tsx
Task: #5793 
First step towards a ballot proofing flow. Adds a button to "finalize ballots" to the Ballots screen. Currently, there's no way to undo finalizing ballots, but eventually we can build this into our internal tools. Also, finalizing ballots should lock the rest of the election to prevent further edits, but that is punted for now as well.
https://github.com/user-attachments/assets/f9cf7c11-f8bd-4010-ae52-a590941dfe4b
Added new automated tests
=> VxDesign: Button to finalize ballots

apps/admin/backend/src/app.caching.test.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/tabulation/full_results.ts, apps/admin/backend/src/tabulation/write_ins.test.ts, apps/admin/backend/src/tabulation/write_ins.ts
https://github.com/votingworks/vxsuite/issues/5656
This bug fix is intended to be included in 4.0.x, so instead of fixing the underlying data structures to filter out overvote write-ins before tallies are made, this PR simply removes the extra tallies after the fact. It is less efficient, but should make the code change easier to review in cert. For 4.1, we may fix the underlying tabulation error so overvote write-ins are never tabulated, but that would be during a larger scale refactor with the adjudication revamp.
The cause of the bug is that when tabulating votes, we first tabulate votes from CVRs, and next we go through all write-ins and create a tally summary for them, ignoring write-ins that were marked as invalid, but including all other write-ins, including those that may have …
=> Remove tallies for write-ins that are part of an overvote

apps/design/backend/schema.sql, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/index.ts, apps/design/backend/src/store.ts, apps/design/backend/src/types.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/app.tsx, apps/design/frontend/src/ballot_order_info_screen.test.tsx, apps/design/frontend/src/ballot_order_info_screen.tsx, apps/design/frontend/src/routes.ts, apps/design/frontend/test/fixtures.ts
Issue link: https://github.com/votingworks/vxsuite/issues/5796
As we shift ballot data entry from Google Forms to VxDesign, we need a screen in VxDesign for ballot order info, e.g., number of ballots to print, paper color, delivery address, etc. This PR ports the [Google Form that we used last year](https://docs.google.com/forms/d/e/1FAIpQLScYssKunYzQX5E3zJMBbBS2lysoCiNFkEjLuV9Mu9g1gBGRqQ/viewform) (see page 2) into VxDesign.
Note that all fields, even those for ballot counts, accept freeform text as towns may want to communicate additional details. Again, going for parity with the Google Form from last year.
=> VxDesign: Add screen for ballot order info

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/ballot_screen.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/routes.ts
If a precinct has splits, VxDesign creates a separate ballot style for each split. When previewing a particular ballot style, we know the precinct ID and the ballot style ID, so we can figure out the relevant split ID (if there is one) from that information. If the precinct has splits, then we look up which split this ballot style corresponds to.
This refactor helps set up for factoring out the logic to add the NH-specific ballot props in all of the other places where we render ballots.
=> VxDesign: Refactor to find precinct split from ballot style in ballot preview

apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/ballots_screen.tsx
Deletes the bubble position toggle because it will always be `left` for the default template and `right` for NH.
Before
After
Manually verified it's gone and deleted the automated test.
=> remove bubble position toggle

apps/design/backend/src/app.test.ts, apps/design/backend/src/ballot_style_reports.test.ts, apps/design/backend/src/types.ts, apps/design/frontend/src/ballot_order_info_screen.test.tsx, apps/design/frontend/src/ballot_order_info_screen.tsx
This PR refines the VxDesign ballot order info screen. It specifically:
- Better aligns inputs and helper text
- Renames the "Paper Color for Polling Place Ballots" field "Paper Color for Ballots" - the values entered into this field will be used for both precinct (polling place) and absentee ballots
| - | - |
| <img width="400" alt="before" src="https://github.com/user-attachments/assets/a4f68b0e-8bd7-4a86-afac-974bd153f613" /> | <img width="400" alt="after" src="https://github.com/user-attachments/assets/9c6d3508-9a1a-467e-90ba-14455381428e" /> |
=> Refine VxDesign ballot order info screen

libs/hmpb/src/ballot_templates/nh_ballot_template.tsx
Adjusts the write-in box to match the default template as recommended [here](https://github.com/votingworks/vxsuite/pull/5852#discussion_r1925672705).
This video shows the NH template as a layer on top of the default template. As I toggle the layer visibility the box has minimal difference between NH and default.
https://github.com/user-attachments/assets/0652745b-eb98-4470-b934-40fa3e82628a
Checked with `libs/hmpb` preview tool.
=> adjust NH template write-in box

libs/hmpb/src/all_bubble_ballot_fixtures.tsx, libs/hmpb/src/ballot_components.tsx, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx
Moves shared components from the default HMPB template to `ballot_components.tsx` and updates imports.
N/A refactor
=> move shared components to ballot_components.tsx

libs/ballot-encoder/src/v3.ts, libs/ballot-encoder/vitest.config.ts, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/hmpb/src/index.ts, libs/hmpb/src/preview/browser_preview.ts, libs/hmpb/src/render_ballot.tsx
Task: https://github.com/votingworks/vxsuite/issues/5702
Creates a copy of the NH town ballot template that produces ballots and election definitions that are compatible with VxSuite v3.
Note that this ballot template isn't integrated into VxDesign yet - that will come in a later PR.
Sample ballot
[test-absentee-ballot-Center_Springfield-1_en.pdf](https://github.com/user-attachments/files/18497719/test-absentee-ballot-Center_Springfield-1_en.pdf)
Write-in adjudication
Unmarked write-in detection
Manual tests:
- Ballot scans and votes are detected correctly
- Write-in adjudication crop areas look right
- Unmarked write-ins are detected
=> V3-compatible NH town ballot template 

apps/design/backend/src/ballot_styles.test.ts, apps/design/backend/src/ballot_styles.ts, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/ballots_screen.tsx
Fixes: https://github.com/votingworks/vxsuite/issues/5871
VxDesign already doesn't generate ballot styles for precincts and precinct splits without any districts assigned. This PR extends that logic to also skip precincts/splits that have districts assigned, but the districts have no contests assigned.
Previously, precincts/splits with no ballot styles were omitted from the list of ballot styles on the ballot screen. This PR changes that screen to show these precincts/splits with a message that they don't have any contests assigned. This is a safeguard for users so they can catch any precincts/splits that should have ballots during proofing.
=> VxDesign: Don't generate ballot styles for precincts/splits without contests assigned

apps/design/backend/schema.sql, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/ballots.ts, apps/design/backend/src/index.ts, apps/design/backend/src/store.ts, apps/design/backend/src/test_decks.test.ts, apps/design/backend/src/types.test.ts, apps/design/backend/src/types.ts, apps/design/backend/src/worker/generate_election_package.ts, apps/design/backend/vitest.config.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/export_screen.tsx, apps/design/frontend/test/fixtures.ts, libs/fixture-generators/src/generate-election-package/generate_election_package.test.ts, libs/fixture-generators/src/generate-election-package/generate_election_package.ts, libs/hmpb/src/ballot_templates/index.ts, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx, libs/hmpb/src/index.ts, libs/hmpb/src/render_ballot.test.tsx, libs/hmpb/src/render_ballot.tsx, libs/hmpb/vitest.config.ts
Task: https://github.com/votingworks/vxsuite/issues/5702
To support towns that require a v3-compatible ballot vs a v4 ballot, adds a ballot template id field to the election in the database. We default all new elections to the NH ballot template. When loading an election, we pick a template based on the `Election.state` field. Internal VX users can change the template for an election via a dropdown on the Export screen (temporarily placed there until we have internal tools).
https://github.com/user-attachments/assets/412ad5fc-98e9-43c5-abb4-d1f8da64a820
Updated existing automated tests
=> VxDesign: Assign ballot template to each election

libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx
https://github.com/votingworks/vxsuite/issues/4712
Omits signature and signature caption on sample ballots.
https://github.com/user-attachments/assets/dd8ce002-9f43-48cd-b010-1cda6e4f5446
- Manually checked the render
=> Do not render signature and signature caption on sample ballot

apps/design/backend/src/types.ts, apps/design/frontend/src/ballot_order_info_screen.test.tsx, apps/design/frontend/src/ballot_order_info_screen.tsx
Was opening an issue for this when I realized that it was just as easy to just open the PR 😅
Per input from Ginny and customers, we're adding two inputs to the ballot order info screen, an option to print collated and a delivery recipient phone number.
=> Add additional inputs to VxDesign ballot order info screen

apps/design/backend/scripts/db_reset_dev.sh
I get this when running `pnpm db:reset`:
```
❯ pnpm db:reset
> @votingworks/design-backend@0.1.0 db:reset /media/parallels/WorkingFiles/code/vxsuite/apps/design/backend
> ./scripts/db_reset_dev.sh
could not change directory to "/media/parallels/WorkingFiles/code/vxsuite/apps/design/backend": Permission denied
DROP DATABASE
could not change directory to "/media/parallels/WorkingFiles/code/vxsuite/apps/design/backend": Permission denied
DROP ROLE
could not change directory to "/media/parallels/WorkingFiles/code/vxsuite/apps/design/backend": Permission denied
CREATE ROLE
could not change directory to "/media/parallels/WorkingFiles/code/vxsuite/apps/design/backend": Permission denied
CREATE DATABASE
could not change directory to "/media/parallels/WorkingFiles/code/vxsuite/apps/design/backend": …
```
=> build(design): do not require `postgres` permissions

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/generate_election_package.ts, apps/design/backend/src/worker/tasks.ts, apps/design/backend/test/helpers.ts, apps/design/frontend/package.json, apps/design/frontend/src/api.ts, apps/design/frontend/src/ballot_order_info_screen.tsx, apps/design/frontend/src/ballot_screen.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/features_context.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/nav_screen.tsx, apps/design/frontend/src/routes.ts, apps/design/frontend/src/tabulation_screen.tsx, apps/design/frontend/test/api_helpers.tsx, pnpm-lock.yaml
Pre-work for #5895 
Also removes a couple `as ElectionId` casts in favor of `unsafeParse` calls.
=> refactor(design): use `ElectionId` type for election IDs

Dockerfile.vxdesign, apps/design/backend/src/app.ts, apps/design/backend/src/configure_sentry.ts, apps/design/backend/src/env.d.ts, apps/design/backend/src/globals.ts, apps/design/frontend/index.html, apps/design/frontend/src/env.d.ts, apps/design/frontend/src/index.tsx
Follow up to #5898.
`NODE_ENV` needs to always be set to `production` to ensure that staging and production environments run the same code. So we can't use it to differentiate which environment an error occurs in when capturing it with Sentry.
Instead, we add a new env var, `DEPLOY_ENV`. We then load this into Sentry on the backend. We also pass it to the frontend via injecting it into the index.html page as a JS string (the same approach used in Arlo), since we can't inject it at build time since the Dockerfile doesn't have access to config vars during build.
N/A
Manual testing with a review app
=> VxDesign: Add DEPLOY_ENV env var to differentiate staging from production in Sentry errors

apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/tabulation_screen.test.tsx, apps/design/frontend/src/tabulation_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/5838
Disables all editing fields when ballots are finalized. Note there are a few form controls that aren't disabled:
* District search dropdown (view only)
* Ballot order form (need to order ballots after finalizing the ballots)
* Ballot template dropdown (internal use only)
* Delete Election button (will be hidden for initial release)
https://github.com/user-attachments/assets/45f3cd2d-cd7e-4b39-8a7c-762e0f39138f
- added tests for disabled state
=> disable edit forms when ballots are finalized

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/index.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/image_input.test.tsx, apps/design/frontend/src/image_input.tsx, apps/design/frontend/test/fixtures.ts, libs/ui/src/file_input_button.tsx
Adds both client and server-side validation. The client validation is fairly simple, just trimming the text and ensuring something non-blank is set. The server-side validation does a tiny bit more, and for now just crashes if it fails.
https://github.com/user-attachments/assets/7cb28a3c-efc1-49e5-a618-1964de451eca
Mostly manual testing, plus a couple new automated tests.
=> feat(design): validate Election Info screen inputs

apps/design/frontend/src/ballot_order_info_screen.test.tsx, apps/design/frontend/src/ballot_order_info_screen.tsx
Adds validation to the Ballot Order Info screen. Changes some of the inputs to more appropriate types (i.e. number/tel) and trims fields on blur. Does not add any server-side validation, which we'll add in a subsequent PR.
https://github.com/user-attachments/assets/91a20558-6dd3-4327-b776-c0d0a228ae7d
Manual testing plus some added/updated automated tests.
=> feat(design): add Ballot Order Info form validation

apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/export_screen.tsx, libs/utils/src/format.test.ts, libs/utils/src/format.ts
Task: #5862 
Adds a "Proofing Status" section to the Export screen (which will only be available to support users) that shows whether or not ballots have been finalized. If they have been finalized, shows a button to unfinalize.
https://github.com/user-attachments/assets/10cec040-575a-49a2-b24e-0c611f4428e8
Added automated tests
=> VxDesign: Unfinalize ballots button

apps/design/backend/src/app.ts, apps/design/frontend/src/ballot_screen.tsx, libs/hmpb/src/all_bubble_ballot_fixtures.tsx, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx, libs/hmpb/src/preview/browser_preview.ts, libs/hmpb/src/render_ballot.tsx, libs/hmpb/src/watermark.test.ts
Closes: #5903 
Currently, there's just one type of expected error: when a contest is too tall to fit on the page.
To deliver this error to the frontend during ballot proofing, we catch the error within the ballot template so we know what contest was too long and pass it up the stack using a `Result`.
https://github.com/user-attachments/assets/8b8a2437-0c7c-4514-8a4e-faabfb0682bc
Manual test
=> VxDesign: Show expected errors during ballot preview

Dockerfile.vxdesign, apps/design/backend/src/worker/index.ts, heroku.yml
The minimal changes necessary to actually deploy the VxDesign worker as part of our VxDesign Heroku deploy. In a separate PR, I'll include the changes to actually allow the worker to be used. Locally, the server and worker use the shared file system to pass files to each other, which naturally won't work in a deployed environment. In prod, I'll be using S3.
=> VxDesign: Deploy worker

apps/design/backend/src/app.ts, apps/design/backend/src/types.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/create_election_button.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/elections_screen.tsx, apps/design/frontend/src/features_context.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/nav_screen.tsx, apps/design/frontend/src/routes.ts
Split the features context into user features vs election features:
- User features are features that should be enabled based on the user's organization - i.e. differentiating between what VX support users can do and what election officials can do.
- Election features are features that should be enabled based on the organization of the election currently being viewed. VX support users and election officials should all have the same functionality for these features when viewing a specific election.
This model of feature flagging means we won't need any sort of feature for support users to "log in as" election official users.
Uses this feature flagging to implement a few tasks:
- https://github.com/votingworks/vxsuite/issues/5810
- https://github.com/votingworks/vxsuite/issues/5868
- …
=> VxDesign: Hide some functionality unless user is a VX support user

apps/design/backend/src/types.ts, apps/design/frontend/src/ballot_order_info_screen.test.tsx, apps/design/frontend/src/ballot_order_info_screen.tsx, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/export_screen.tsx, apps/design/frontend/src/routes.ts
This PR introduces a mechanism for finalizing ballot order info (after which it cannot be edited), and explicitly sequences ordering ballots after proofing.
This PR also adds an internal mechanism by which we can unsubmit for a user, if they need to make edits after submitting, much like the tooling we've built for the proofing flow.
_End user flow_
https://github.com/user-attachments/assets/d045d183-8b7a-4069-a503-d180b5e83925
_Internal Vx tooling_
https://github.com/user-attachments/assets/4a95cbc0-9cbd-4a9f-ab81-8e34294fdc31
=> Introduce mechanism for finalizing ballot order info, and sequence ordering ballots after proofing

apps/design/frontend/src/features_context.tsx, apps/design/frontend/src/geography_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/5917
Adds feature flags to prevent NH users from:
- Creating or deleting districts
- Creating or deleting the splits for a precinct (including editing their name or districts - editing the NH-specific fields is still allowed)
https://github.com/user-attachments/assets/64d42cb8-c49a-4374-bfd1-911611cffdad
Manual testing
=> VxDesign: Don't allow NH users to change precinct splits

apps/design/backend/src/store.ts, apps/design/frontend/src/elections_screen.tsx, libs/ui/src/icons.tsx
Closes #5862
For VX support users, adds an election status column to the election list. Also makes the list sortable by the status or org name column.
https://github.com/user-attachments/assets/454f07ae-ee37-4a1b-aa01-188caf2d9698
Manual testing
=> VxDesign: Show sortable election status and org name in election list for VX support users

apps/design/frontend/src/geography_screen.tsx
Refs #5897 
- trim text inputs on blur
- make precinct/district names required
- require precinct/district delete confirmation
https://github.com/user-attachments/assets/b4920d3a-694b-4793-9d64-acdbf4b96db5
Manual testing since automated testing is temporarily disabled.
=> feat(design): improve Geography screen UX

.circleci/config.yml, apps/design/backend/README.md, apps/design/backend/scripts/restore_db_backup.sh, apps/design/frontend/README.md, libs/monorepo-utils/src/circleci.ts
https://github.com/votingworks/vxsuite/issues/5900
Adds a script and instructions for restoring a dev db from snapshot.
N/a
- exported from prod and restored locally
=> VxDesign db restore script and downgrade to Postgres 16.6

apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/image_input.test.tsx, apps/design/frontend/src/image_input.tsx, apps/design/frontend/src/rich_text_editor.tsx
https://github.com/votingworks/vxsuite/issues/5866
https://github.com/user-attachments/assets/9bc47ff9-19e1-4215-99b3-8db2f8cb68bb
Styling when a valid seal has been previously uploaded:
(The NH seal pictured is valid and remains after I attempted to upload an invalid seal).
- manually tested
=> optionally validate image dimensions

libs/grout/src/server.ts
Closes #5938 
If we do not pass the error to the `express` handler `next`, no subsequent middleware will be able to see it.
n/a
Tested locally, produced [this error](https://votingworks.sentry.io/issues/6262334709/?project=4508717994016768&query=is:unresolved%20issue.priority:%5Bhigh,%20medium%5D&statsPeriod=1h&stream_index=0).
=> fix(grout): allow downstream error handling

apps/design/frontend/src/election_info_screen.test.tsx, apps/design/frontend/src/election_info_screen.tsx
https://github.com/votingworks/vxsuite/issues/5918
Adds a confirmation modal to the "Delete Election" button. Follows the pattern in https://github.com/votingworks/vxsuite/pull/5940
https://github.com/user-attachments/assets/9ac81a6e-5d4e-42bf-8295-8bde57c1342e
- updates the existing test, but that test needs to be updated to run with the current auth implementation before it can be built
=> add delete confirmation modal for election

apps/design/frontend/src/election_info_screen.tsx
Closes #5946
Rather than forcing the value to always be a valid date, store the draft entry while it's not valid. The built-in HTML validation will ensure we cannot submit the form while the date is invalid.
https://github.com/user-attachments/assets/1a6675c3-e5a5-4ef4-99f6-6370239b00f6
Manually tested since automated tests are temporarily disabled.
=> fix(design): allow draft dates to be invalid

Dockerfile.vxdesign
The Docker build is currently broken, potentially due to a change in corepack (related: https://github.com/nodejs/corepack/issues/612).
To unblock, updating the `Dockerfile` to install a hardcoded version of `pnpm` with `npm` instead.
- Tested with local docker build
=> [VxDesign] Docker: drop corepack, use explicit pnpm installation

apps/design/backend/package.json, apps/design/backend/src/app.ts, apps/design/backend/src/context.ts, apps/design/backend/src/env.d.ts, apps/design/backend/src/file_storage_client.ts, apps/design/backend/src/index.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/context.ts, apps/design/backend/src/worker/generate_election_package.ts, apps/design/backend/src/worker/index.ts, apps/design/backend/src/worker/tasks.ts, apps/design/frontend/src/api.ts, apps/design/frontend/vite.config.ts, pnpm-lock.yaml
This PR should get election package exports working in deployed environments by using S3 for file storage. With our current local setup, the background worker writes the election package to the local file system, and the server then pulls that file from that same file system as it's running on the same machine. In deployed environments, the the server and background worker are of course running on different machines so we need another means of sharing the file between the two. I've opted for S3.
To keep local and production code paths as close together as possible, I've set up a generic `FileStorageClient` interface, with two implementations, one for deployed environments `S3FileStorageClient` and one for local dev `LocalFileStorageClient`. Eventually, local dev could also use S3, with …
=> Get election package exports working in deployed environments by using S3 for file storage

apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/image_input.test.tsx, apps/design/frontend/src/image_input.tsx
Refs #5895
Allows removing any images. This is mostly to allow removing images where the images are optional, such as clerk signatures.
https://github.com/user-attachments/assets/c2cdf621-faa1-4ea4-b368-be78b7cf4af4
Added an automated test, manually tested with the election seal image and clerk signature.
=> feat(design): allow removing images

libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx
I believe this was missed because the watermark was added at the same time the v3 template was forked.
Tested manually only because automated tests are temporarily disabled.
=> fix(hmpb): add "PROOF" watermark to NH v3 template

apps/design/frontend/src/elections_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/5951
Since dev org IDs don't match the ones in prod, we're unable retrieve org display names for elections when running locally against prod DB snapshots, which causes the UI to crash. This removes the assertion on the org name search in the client and falls back to displaying the org ID instead.
When `NODE_ENV !== "production"`, also adding a `Jurisdiction` column to stand in for the org name, since they're closely linked. Will be repetitive for cases where we do have the org names available (running against dev data), so we can refine the show/hide logic if it become cumbersome.
- Manual for now
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, …
=> [VxDesign] Enable local dev with prod DB snapshots

libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx, libs/hmpb/src/layout_in_columns.test.ts, libs/hmpb/src/layout_in_columns.ts
The v3 ballot template copied the logic for laying out contests in columns from existing ballot templates. This logic pre-renders all of the contests to measure their heights, then uses these heights to lay out as many as possible on each page. This is normally fine, since measuring contests is quick. However, in the v3 template, rendering a contest involves measuring all of its children (contest options) to snap them to the grid. This causes a major slowdown for long ballots.
To fix this, this PR changes the column layout function to take an iterable of contests instead of a list (i.e. a lazy list). In the v3 template, we use this laziness to only measure the contests as needed by the layout function. In the other ballot templates, we keep the existing logic to measure all of the …
=> Optimize V3 NH ballot template

libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx
Meant to add these in https://github.com/votingworks/vxsuite/pull/5962 but forgot to commit them. Just silences a warning during browser preview - no functional change.
=> V3 NH ballot: Add missing React keys

apps/design/frontend/jest.config.js, apps/design/frontend/src/image_input.test.tsx, apps/design/frontend/src/image_input.tsx, apps/design/frontend/tsconfig.json
Resolves this Sentry issue: https://votingworks.sentry.io/issues/6271094120/
1. Go to the Election Info screen.
2. Click "Edit".
3. Click "Upload Seal Image".
4. Choose an image.
5. Click "Upload Seal Image" again.
6. Cancel without choosing a new image.
The image chosen in step 4 is still shown as the current selection.
The page crashes with "Something went wrong".
```
unhandled promise rejection: Error
at assertDefined (assert.ts:20:11)
at onChange (image_input.tsx:157:22)
```
=> fix(design): prevent crash on cancel image input

apps/design/frontend/src/rich_text_editor.test.tsx, apps/design/frontend/src/rich_text_editor.tsx
Fixes: https://github.com/votingworks/vxsuite/issues/5961
If a user pastes a single cell table, they probably just wanted to paste the contents of that cell, so we unwrap the table, table row, and cell and just paste the contents.
https://github.com/user-attachments/assets/dd72ef92-9de4-45cc-93a5-4ac823ee4a5d
Manual test and automated tests
=> VxDesign rich text editor: Unwrap single cell tables on paste

apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/export_screen.tsx, apps/design/frontend/src/tabulation_screen.test.tsx, apps/design/frontend/src/tabulation_screen.tsx
This PR makes two simple tweaks.
**After a ballot is finalized, we now:**
1. Still allow editing of tabulation settings, which don't actually affect the ballot
2. No longer allow editing of the ballot template - if this needs to be edited, the ballot needs to be unfinalized first
Just making these changes in prep for the next phase of ballot production.
https://github.com/user-attachments/assets/7afd2b5d-148d-41f9-a771-ef7b545416a8
=> Misc VxDesign tweaks in prep for QA

apps/design/backend/src/app.test.ts, apps/design/backend/src/ballots.ts, apps/design/frontend/jest.config.js, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/features_context.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/image_input.test.tsx, apps/design/frontend/src/image_input.tsx, apps/design/frontend/src/seal_image_input.test.tsx, apps/design/frontend/src/seal_image_input.tsx, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/ui/src/checkbox_group.test.tsx, libs/ui/src/checkbox_group.tsx
Allows setting an election seal image per precinct split that overrides the one for the election as a whole. One must still be provided at the election level, and is optional at the precinct split level.
https://github.com/user-attachments/assets/588765fe-e85a-4e69-afad-098cc329c160
Manually tested only as automated tests are still mostly disabled.
=> feat(design): allow per-precinct split seal images

apps/design/backend/src/app.test.ts
Fixes tests in CI.
I think this only happens sometimes because of a data race.
=> ci(design): don't overwrite the seal in this test

apps/design/frontend/src/contests_screen.tsx
Fixes https://votingworks.sentry.io/issues/6266281369/
1. Create a contest.
2. Delete the contest.
The contest should be deleted and the user should be redirected back to the contest list.
Most of the time, it happens exactly as expected. However, the order in which `savedElection` is updated and the `updateElectionMutation` `onSuccess` callback is called is not defined. If `savedElection` is updated first it will no longer have the contest that was just deleted and the `find` call will panic.
n/a
Automated.
=> fix(design): prevent crash on contest delete

apps/design/backend/src/ballots.test.ts, apps/design/backend/src/ballots.ts, apps/design/backend/tsconfig.build.json, apps/design/frontend/src/export_screen.tsx, libs/hmpb/src/ballot_components.tsx, libs/hmpb/src/ballot_templates/index.ts, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/hmpb/src/base_styles.tsx, libs/hmpb/src/playwright_renderer.tsx, libs/hmpb/src/preview/browser_preview_renderer.tsx, libs/hmpb/src/render_ballot.test.tsx, libs/hmpb/src/render_ballot.tsx, libs/hmpb/src/renderer.tsx
Closes https://github.com/votingworks/vxsuite/issues/5959
Adding `*Compact` versions of the NH ballot templates where we (not comprehensive):
- reduce the font-size from `12pt` to `10pt`,
- reduce line height from `1.2` to `1.1`,
- reduce spacing and padding where feasible,
- and reduce ballot measure title sizes.
Updated the ballot template picker to include the new compact variations.
V4 normal template sample [here](https://drive.google.com/file/d/1WcVDMRTHva8jWX75GgH_cUN43g4PG-rC/view?usp=drive_link)
V4 compact template sample [here](https://drive.google.com/file/d/1md-0Zg4EQZoxnBsvPysF0yPGhoPT3-6v/view?usp=drive_link)
- Manual for now
- ~[ ] I have added [logging](https://github.com/votingworks/vxsuite/tree/main/libs/logging) where appropriate to any new user actions, system updates …
=> [VxDesign] Add compact templates for NH ballots

apps/design/frontend/jest.config.js, apps/design/frontend/src/tabulation_screen.tsx
One more tweak in prep for election package exports and upcoming NH ballot QA, as I need this enabled for all v4 election package exports. Threw things under an "other" bucket for now, but don't put too much stock in that. We'll be revisiting this soon, as we add additional toggles for other system settings to unblock SLI's testing.
=> Add checkbox for "allowOfficialBallotsInTestMode" setting

apps/design/backend/src/worker/generate_election_package_and_ballots.ts, apps/design/backend/vitest.config.ts, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx
Addresses issues raised in QA for https://github.com/votingworks/vxsuite/issues/5952
* Fixes a bug where compact NH v3 template was exporting v4 election package. Now exports v3 election package for compact NH v3 template
* Adjusts write-in area bounds for NH compact layouts
All images in https://drive.google.com/drive/folders/1KhoQQsBdQed4QMXyMx2HjaJKlghk_eQK?usp=sharing
**v3 legal compact**
**v3 letter compact**
**v4 legal compact**
**v4 letter compact**
Manual rendering with `libs/ballot-interpreter` debugger.
=> Adjust write-in area bounds for compact layouts

apps/admin/frontend/src/components/reporting/filter_editor.tsx, apps/admin/frontend/src/screens/reporting/single_precinct_tally_report_screen.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_tab.tsx, apps/design/frontend/.eslintignore, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/export_screen.tsx, apps/design/frontend/tsconfig.json, apps/design/frontend/vitest.config.ts, apps/scan/frontend/src/screens/election_manager_screen.tsx, libs/types/src/election.test.ts, libs/types/src/election.ts, libs/ui/src/change_precinct_button.tsx, libs/ui/src/contest_choice_button.test.tsx, libs/ui/src/contest_choice_button.tsx, libs/ui/src/modal.tsx, libs/ui/src/search_select.test.tsx, libs/ui/src/search_select.tsx, libs/ui/src/search_select_multi.stories.tsx, libs/ui/src/search_select_single.stories.tsx, libs/ui/src/segmented_button.stories.tsx, libs/ui/src/segmented_button.test.tsx, libs/ui/src/segmented_button.tsx, libs/ui/src/tabbed_section/tabbed_section.tsx
Refs #5953 
Closes #5893
Re-enabling and fixing the tests revealed a few problems with this screen:
- deleting the First Name field would instantly insert the rest of the name as the first name; this was due to the "fallback" logic we had
- submitting without a District selected was allowed but produced an invalid contest
To fix the name issue, I changed the form to work with "draft" versions of the contest and candidate data structures that better fit the form. We then validate the data on form submit, both using the HTML `required` attribute and then using our Zod schemas.
Re-enabled automated tests, plus some manual testing.
=> fix(design): improve `ContestsScreen` UX

apps/design/backend/package.json, apps/design/backend/src/ballots.ts, apps/design/backend/src/color-tints.csv, apps/design/backend/src/worker/generate_election_package_and_ballots.ts, apps/design/backend/vitest.config.ts, libs/hmpb/src/ballot_components.tsx, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/index.ts, pnpm-lock.yaml
Add a color tint option to the NH v4 ballot template, tinting all previously gray boxes (instructions, contest headers, and footers).
Manual testing
=> Add color tinting to NH ballot template

Dockerfile.vxdesign, heroku.yml, run-vxdesign
Issue link: https://github.com/votingworks/vxsuite/issues/6022
This PR unblocks generating translations and audio in production (and staging) VxDesign by setting up our Google Cloud credentials there! I've done so in the simplest way possible for now, and we can refine as we scale VxDesign up.
In Heroku, we just need to set the following env vars:
- `GOOGLE_APP_CREDENTIALS` - `/vx/config/google-cloud-credentials.json`
- `GOOGLE_APP_CREDENTIALS_CONTENTS` - Secret information from the Google Cloud console
- `REACT_APP_VX_ENABLE_CLOUD_TRANSLATION_AND_SPEECH_SYNTHESIS` - `TRUE`
I'll take care of setting these values in both staging and production. Note that I may hold off on enabling the last variable in production until we have a way to show multi-language options for SLI but not NH …
=> VxDesign: Set up Google Cloud credentials for translations/audio in prod

libs/hmpb/src/render_ballot.tsx
Mitigates but does not close https://github.com/votingworks/vxsuite/issues/5985.
Uses a `for` loop instead of unbounded `Promise.all` to render ballots in `renderAllBallotsAndCreateElectionDefinition`. Rendering in parallel seemed to cause resource contention and slow down overall ballot and election package export time.
N/A
- manually tested render of large ballot package locally
=> limit render concurrency

apps/admin/frontend/src/app.test.tsx, apps/design/backend/src/ballot_style_reports.test.ts, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/mark-scan/backend/src/app.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, vitest.config.shared.mts
Removes ad hoc test timeout configs that were already 10s, assuming they are set to that for CI purposes.
n/a
Automated.
=> ci: set test timeout to 10s in CI only

apps/scan/backend/src/electrical_testing/app.ts, apps/scan/backend/src/electrical_testing/background.test.ts, apps/scan/backend/src/electrical_testing/background.ts, apps/scan/backend/src/electrical_testing/context.ts, apps/scan/backend/src/electrical_testing/server.ts, apps/scan/backend/src/electrical_testing/simple_scanner_client.ts, apps/scan/backend/src/index.ts, apps/scan/frontend/package.json, apps/scan/frontend/src/electrical_testing/api.ts, apps/scan/frontend/src/electrical_testing/app_root.tsx, libs/ballot-interpreter/src/index.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_ids.ts, libs/logging/types-rust/src/log_event_enums.rs, pnpm-lock.yaml
Includes the PDI scanner component as part of the stress test loop. Also adds a "Stop Testing" button to stop all the tests, with no way right now to re-start them.
https://github.com/user-attachments/assets/6f3e3250-6771-439c-af90-e1d502b3b801
Manually tested:
Some basic automated tests added.
=> feat(scan): include scanner component in stress test

libs/backend/package.json, libs/backend/src/language_and_audio/ballot_strings.test.ts, libs/backend/src/language_and_audio/election_package_string.test.ts, libs/backend/test/fixtures/hmpb_strings_catalog.ts, pnpm-lock.yaml
This PR removes a circular dependecy that's blocking creating images:
```
libs/hmpb --(dep)--> libs/ui --(dep)--> libs/backend --(dev dep)--> libs/hmpb
```
I specifically addressed this by removing the last link in the chain from libs/backend to libs/hmpb.
Verified that the step in the image building process that's failing fails before this change and succeeds after this change.
=> Remove circular dependency

apps/design/frontend/src/ballot_order_info_screen.tsx, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/election_info_screen.tsx, apps/design/frontend/src/elections_screen.tsx, apps/design/frontend/src/export_screen.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/hooks/use_title.test.ts, apps/design/frontend/src/hooks/use_title.ts, apps/design/frontend/src/system_settings_screen.tsx
Having the same document title for all pages makes it harder to navigate the site, especially when you have multiple tabs open.
https://github.com/user-attachments/assets/27378240-f09a-4e5f-bdbd-6263395b5f4f
Tested manually and added an automated test suite.
=> feat(design): update `title` based on the screen

libs/custom-paper-handler/src/driver/driver.ts, libs/custom-paper-handler/src/driver/driver_setup.test.ts, libs/custom-paper-handler/src/driver/test_utils.ts, libs/custom-scanner/src/open_scanner.test.ts, libs/custom-scanner/src/open_scanner.ts, libs/custom-scanner/src/parameters.ts, libs/custom-scanner/src/protocol.ts, libs/fujitsu-thermal-printer/src/driver/driver.ts, libs/pdi-scanner/src/rust/scanner.rs
While we shouldn't need this in production, and realistically won't need it with most USB devices, it's possible for the kernel to decide that it has a driver to handle one of our devices. In that event, it will open and claim the interface and trying to claim the interface ourselves will fail. This happens on a default install of Debian 12 with the Fujitsu thermal printer.
=> fix(usb): detach kernel driver

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/elections_screen.test.tsx
Closes https://github.com/votingworks/vxsuite/issues/5533
Assigning newly generated IDs when importing elections, to avoid conflict errors from importing an election that has already been previously created/imported.
Currently mirroring the `createElection` pattern and sending up a new ID from the client - opened https://github.com/votingworks/vxsuite/issues/6055 for potentially moving ID generation server-side.
- ~[ ] I have added the "user_facing_change" label to this PR to …
=> [VxDesign] Generate new IDs for imported elections

apps/mark-scan/backend/src/electrical_testing/background.ts, apps/mark-scan/backend/src/electrical_testing/context.ts, apps/mark-scan/backend/src/index.ts, apps/mark-scan/frontend/src/electrical_testing/app_root.tsx, apps/scan/backend/src/electrical_testing/background.ts, apps/scan/backend/src/electrical_testing/context.ts, apps/scan/backend/src/index.ts, apps/scan/frontend/src/electrical_testing/app_root.tsx, libs/basics/src/errors.test.ts, libs/basics/src/errors.ts, libs/ui/src/electrical_testing_screen.test.tsx, libs/ui/src/electrical_testing_screen.tsx, libs/ui/src/index.ts
This PR handles some miscellaneous electrical testing app cleanup. It specifically:
- Adds a test button for testing the touch screen
- Adds a "Last key press" field for testing VxMark controller and PAT input
- Left aligns content (instead of center aligning) so that text doesn't hop around so much
- Refines error message extraction logic to avoid `[object Object]` status messages
Also sets up a shared `ElectricalTestingScreen` component to consolidate logic across VxMark and VxScan.
_VxMark_
https://github.com/user-attachments/assets/8f00087a-680e-4e8f-81bb-099a0a07f935
_VxScan_
https://github.com/user-attachments/assets/0ce8f37b-2524-410d-9841-a7b234f45278
=> Miscellaneous electrical testing app cleanup

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/generate_election_package_and_ballots.ts, apps/design/backend/src/worker/tasks.ts, apps/design/backend/test/helpers.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/export_screen.test.tsx
A quick follow-up to https://github.com/votingworks/vxsuite/pull/6039
Rather than passing the user org ID to the background task for export, I think it makes sense to pass the election org ID. The one circumstance where these two can differ is when a Vx user with the Vx org ID exports an election package for a customer. Feature flags, like whether to export with translations and audio, should be determined given the election org ID rather than the exporting user org ID. An NH election package exported by a Vx user shouldn't have translations and audio enabled for example.
=> Use election org ID rather than user org ID in export background task

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/vitest.config.ts, apps/design/frontend/src/clone_election_button.test.tsx, apps/design/frontend/src/clone_election_button.tsx, apps/design/frontend/src/create_election_button.tsx, apps/design/frontend/src/elections_screen.test.tsx, apps/design/frontend/src/elections_screen.tsx, apps/design/frontend/test/api_helpers.tsx, apps/design/frontend/vitest.config.ts, libs/ui/src/icons.tsx
Closes https://github.com/votingworks/vxsuite/issues/5530
(Some alternatives/future ideas considered in this thread: https://votingworks.slack.com/archives/C085YT4798C/p1740606709518789)
Adding UI for cloning elections from the election list screen (API added in https://github.com/votingworks/vxsuite/pull/6051). Uses the same pattern from `CreateElectionButton` - Vx users get an org selection modal; single-org users get a new election created immediately) - we could explore adding a confirmation for the latter eventually, but easy enough to delete accidental copies at the moment.
https://github.com/user-attachments/assets/163c3257-18b9-4ecc-8e24-201a2dcc667b
https://github.com/user-attachments/assets/fcc04aca-7e14-4048-ba3c-3ca0350b9cf6 …
=> [VxDesign] Add UI for cloning elections

app.json, apps/design/backend/src/globals.ts
Task: #6079 
Sets up the necessary config (mainly in app.json) to automatically provision Heroku review apps and their necessary resources.
After this PR, the only manual step required will be initializing the db schema by running the following command locally:
```
DATABASE_URL=<copy from Heroku> psql $DATABASE_URL < schema.sql
```
The imminent migration tooling should make this unnecessary, so I'm not worried about automating it for now.
N/A
Created a review app from this branch
=> design/backend: Add review app config to app.json

apps/admin/backend/src/tabulation/write_ins.test.ts
This test has been flaky, with this [line](https://github.com/votingworks/vxsuite/blob/main/apps/admin/backend/src/tabulation/write_ins.ts#L467) not being consistently hit. 
I was able to reproduce locally about half the time. The ordering of the `writeInRecords` returned from the store was inconsistent, so I updated the test to adjudicate based on optionId, instead of assuming a certain ordering. This ordering mattered because if the "unmarked" write-in gets adjudicated as "invalid", then that cvr has no overvote, so the invalid overvote case is never hit.
=> Fix flaky test

apps/scan/backend/src/electrical_testing/background.test.ts, apps/scan/backend/src/electrical_testing/background.ts, apps/scan/backend/src/electrical_testing/server.ts, apps/scan/backend/src/electrical_testing/simple_scanner_client.ts, apps/scan/backend/src/store.ts, libs/pdi-scanner/src/ts/scanner_client.test.ts, libs/pdi-scanner/src/ts/scanner_client.ts
Mostly this just causes the loop to not exit when reconnecting fails. Additionally, this adds logging whenever the testing status message changes.
Some example logging:
```
[backend:run] {"source":"vx-scan-backend","eventId":"info","eventType":"system-status","user":"system","message":"Setting electrical testing status message","disposition":"na","component":"usbDrive","statusMessage":"Success"}
[backend:run] {"source":"vx-scan-backend","eventId":"info","eventType":"system-status","user":"system","message":"Setting electrical testing status message","disposition":"na","component":"scanner","statusMessage":"Received event: scanStart"}
[backend:run] {"source":"vx-scan-backend","eventId":"info","eventType":"system-status","user":"system","message":"Setting electrical testing status …
```
=> fix(scan): attempt to recover from failed scanner reconnects

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/ballot_styles.test.ts, apps/design/backend/src/ballot_styles.ts, apps/design/backend/src/ballots.test.ts, apps/design/backend/src/ballots.ts, apps/design/backend/src/election_package_strings.test.ts, apps/design/backend/src/election_package_strings.ts, apps/design/backend/src/index.ts, apps/design/backend/src/store.ts, apps/design/backend/src/types.ts, apps/design/backend/src/worker/generate_election_package_and_ballots.ts, apps/design/frontend/src/ballots_screen.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/utils.ts, libs/backend/src/language_and_audio/ballot_strings.test.ts, libs/backend/src/language_and_audio/ballot_strings.ts, libs/backend/src/language_and_audio/election_package_string.test.ts, libs/backend/src/language_and_audio/election_package_strings.ts, libs/fixture-generators/src/generate-election-package/generate_election_package.test.ts, libs/fixture-generators/src/generate-election-package/generate_election_package.ts, libs/hmpb/src/ballot_templates/index.ts, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/types/src/election.test.ts, libs/types/src/election.ts, libs/types/src/index.ts, libs/types/src/test_utils.ts
Closes https://github.com/votingworks/vxsuite/issues/5975
Ensures that changes to precinct split-specific fields (text or image) update the election hash.
* Adds `additionalHashInput` to the shared `Election` type and the `election.json` file exported by VxDesign via test deck or election package export. Into this property we add hashes of precinct split signature and seal override images.
* Adds `electionTitleOverride` and `clerkSignatureCaption` to `hmpbStrings` in `election.json`
nb. I decided to write to `election.json` the hashes of the images, rather than the SVGs themselves, since we have seen images up to our max 5 MB and one election may have several precinct splits each with their own seal override and signature. See [discussion](https://votingworks.slack.com/archives/C014MGC0WRE …
=> Make precinct split config affect election hash

libs/ballot-interpreter/bin/qa-interpret
Script for simplifying CLI arguments when doing QA for write-in area eg. https://github.com/votingworks/vxsuite/issues/5952
N/A
Manually run then cleaned up/generalized slightly. Committing as-is but might need adjustments to your use case the first time
=> add script for manually QAing write-in area bounds

apps/design/backend/src/app.test.ts, apps/design/backend/test/helpers.ts, apps/design/backend/vitest.config.ts, libs/backend/src/election_package/election_package_io.test.ts, libs/backend/src/election_package/election_package_io.ts
Re-enables the remaining skipped tests in design/backend/src/app.test.ts
N/A
The tests pass
=> design/backend: Re-enable skipped tests

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/vitest.config.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/vitest.config.ts
Task: #6080 
Adds backend validation to the districts form. Adds new CRUD API methods for districts and validates input on the backend. Since there is also frontend validation, we don't actually expect invalid input to be sent to the backend, so we just throw errors if invalid input occurs.
N/A - no functionality changed
=> VxDesign: Backend validation for districts form

apps/design/backend/schema.sql, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/generate_test_decks.ts, apps/design/backend/src/worker/tasks.ts, apps/design/backend/test/helpers.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/export_screen.tsx, apps/design/frontend/vitest.config.ts
https://github.com/votingworks/vxsuite/issues/6086
Moves test deck generation to the background worker to avoid 30s request timeout.
https://github.com/user-attachments/assets/198ab8d0-4814-499d-9a57-1068b67c7c42
- updated existing test decks tests
=> export test decks from background worker

apps/design/frontend/src/api.ts, apps/design/frontend/src/geography_screen.tsx
I realized that these forms could be a bit simpler and more straightforward if they didn't take in the entire list of saved entities, but rather only the one that was being edited.
N/A
Existing test coverage
=> VxDesign: Refactor districts/precincts forms

apps/design/frontend/src/system_settings_screen.tsx, apps/scan/backend/src/app_scanning.test.ts, apps/scan/backend/src/electrical_testing/simple_scanner_client.ts, apps/scan/backend/src/scanners/pdi/pdi_app_diagnostic.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/src/store.ts, libs/dev-dock/backend/src/dev_dock_api.test.ts, libs/pdi-scanner/examples/scan_forever.rs, libs/pdi-scanner/src/rust/client.rs, libs/pdi-scanner/src/rust/main.rs, libs/pdi-scanner/src/rust/protocol/types.rs, libs/pdi-scanner/src/rust/rusb_async/pool.rs, libs/pdi-scanner/src/ts/demo.ts, libs/pdi-scanner/src/ts/mock_scanner.test.ts, libs/pdi-scanner/src/ts/scanner_client.test.ts, libs/pdi-scanner/src/ts/scanner_client.ts, libs/types/src/system_settings.ts, vxsuite.code-workspace
See [Slack thread](https://votingworks.slack.com/archives/C08EMS6529F)
Adds a system setting called "Bitonal Threshold" which will be passed to the PDI scanner for black & white scans to determine the threshold for determining whether a pixel is black or white. Note that this setting cannot be per ballot style but must be per election (or theoretically, at highest granularity, per scanner). If ballots for an election are printed on multiple colors of paper then this single value must work appropriately for all of them. This likely means non-white color should be quite light if there are any white ballots in the mix and that the contrast between any two ballot paper colors should not be very high.
Though this will allow us to scan paper that is not white, scanning in grayscale would be a …
=> feat(scan): allow configuring scanner's bitonal threshold

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/vitest.config.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/vitest.config.ts
Task: #6080 
Continuing the patterns established in #6093, #6095, and #6097. Adds backend validation to the parties form.
N/A
Added new tests (pretty much all of this code was not covered)
=> VxDesign: Backend validation for parties form

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/vitest.config.ts
Task: #6080 
Adds backend form validation for the contests form.
N/A
Updated existing tests, added some new tests
=> VxDesign: Backend validation for contests form

apps/design/backend/src/app.test.ts
Since the `finalizeBallots` endpoint captures a timestamp on the backend, the approach of comparing to an expected timestamp created in the test was flaky. To make this more reliable, use fake timers to set the exact timestamp.
N/A
N/A
=> design/backend: Use fake timers to fix flaky test

apps/admin/frontend/src/screens/write_ins_adjudication_screen.test.tsx
This test fails inconsistently, and I think it is because the `await` call might be met from some other page item before the mock calls are all made. I've updated the test to wait on the ballot image itself, as that should ensure the page data has actually loaded. 
I'm not 100% certain this will fix it, so I'll keep an eye on it.
I got the old test to fail only one out of 20 times locally. The new test hasn't failed in 20 local attempts.
=> VxAdmin: Fix flaky test

apps/scan/backend/src/printing/print_report_section.ts, libs/auth/src/config.ts, libs/auth/src/index.ts, libs/auth/src/quick_results_signed_url.ts, libs/auth/src/signed_quick_results_signed_url.ts, libs/types/src/system_settings.ts, libs/ui/src/reports/precinct_scanner_tally_qr_code.tsx, libs/ui/src/reports/precinct_scanner_tally_report.tsx, libs/ui/src/reports/precinct_scanner_tally_reports.tsx
When the system settings file has a quick results reporting URL specified, encodes a QR code using the URL to submit the tally represented by the polls closed report. 
Open to adding tests but wasn't sure what was necessary for this small demo feature. 
Relevant related updates to the server: https://github.com/votingworks/quickresults-server/pull/12 
Example Polls Closed Report 
[vxqrsamplereport.pdf](https://github.com/user-attachments/files/19326632/vxqrsamplereport.pdf)
Manually tested by scannign ballots, creating report, scanning QR code and verifying it took me to the right encoded URL with the tally properly represented.
=> Reimplement writing vxqrcode on Polls Closed Report

apps/design/backend/migrations/1742326862308_add-test-deck-task-info.js
Adding missing columns to the `elections` table for the test deck worker task:
- `test_decks_task_id`
- `test_decks_url`
Making this a no-op for existing columns (to make sure it works on new and existing DBs), since they're included in the init script, but hadn't yet been added to staging/prod.
Output from local run:
```sh
> node-pg-migrate up
> Migrating files:
> - 1742326862308_add-test-deck-task-info
ALTER TABLE "elections"
ADD IF NOT EXISTS "test_decks_task_id" text CONSTRAINT "fk_test_decks_background_tasks" REFERENCES background_tasks(id) ON DELETE SET NULL,
ADD IF NOT EXISTS "test_decks_url" text;
INSERT INTO "public"."pgmigrations" (name, run_on) VALUES ('1742326862308_add-test-deck-task-info', NOW());
Migrations complete!
```
- Testing locally, with and without the existing …
=> [VxDesign] Add missing test deck task info columns to DB

apps/design/backend/src/db/client.ts, apps/design/backend/test/test_store.ts
`node-pg-migrate` implements locking on DB migrations to ensure that only one is running at a time - this is causing occasional [failures](https://app.circleci.com/pipelines/github/votingworks/vxsuite/19126/workflows/65da1096-d5b2-4589-8041-3e9effb84943/jobs/795066) in our tests, where we run multiple in parallel (but, against different schemas).
Adding an option to disable locking just for tests, since we generate a new, unique schema name for each instance of each test file - we don't have to worry about conflicting migrations in those cases.
- Reproduced the failure locally (1 out of 5 runs), tested with locking turned off and haven't run into any failures so far (8 runs) - wouldn't expect the same error as before, FWIW; just making sure we're not introducing another failure path.
- …
=> [VxDesign] Avoid DB migration lock race conditions in tests

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/index.ts, apps/design/backend/vitest.config.ts, apps/design/frontend/src/clone_election_button.test.tsx, apps/design/frontend/src/clone_election_button.tsx, apps/design/frontend/src/elections_screen.test.tsx, apps/design/frontend/src/elections_screen.tsx, apps/design/frontend/test/fixtures.ts
Don't send the entire election record to the frontend, just the fields needed. Compute the election status on the backend. This isn't strictly necessary yet, but sets up a more reasonable interface for easy refactoring/optimizing of data loading from the db later. The basic goal was just to remove all knowledge of ElectionRecord from the frontend.
N/A
=> VxDesign: Return minimal info in listElections response

apps/design/frontend/src/contests_screen.tsx, apps/design/frontend/src/geography_screen.tsx
Follow up to https://github.com/votingworks/vxsuite/pull/6114. A recent refactor moved the finding of each district/precinct/party/contest up into the edit form component. This meant that the guard that detected when the entity wasn't found (which can occur momentarily after deletion) was no longer reachable. This fix moves the guard next to the find.
N/A
Manually tested and confirmed no error logs in the console
=> VxDesign: Fix guards preventing error on rerender after delete

apps/design/backend/migrations/1742941957696_regenerate-duplicate-ids.js
Detects elections with duplicate IDs (for districts/precincts/parties/contests) and regenerates their IDs. This migration can probably be removed once it's been run, since we now have a change in place to prevent duplicate IDs from being saved in the first place.
N/A
Ran on a db snapshot and then ran the migration from #6117 to confirm that there are no more unique index errors for any of the election content.
=> VxDesign: Migrate duplicate IDs in election content

libs/types/src/cdf/ballot-definition/convert.ts, libs/types/src/cdf/ballot-definition/fixtures.ts, libs/types/test/cdf_conversion_helpers.ts, libs/types/test/election.ts
When an election is exported in VxDesign in CDF format and is multi-language the IDs are created in the style: `{ballotStyleGroupID}_{languageCode}`. If we detect ballots in this format from VxDesign we should parse out the group ID from it so that ballots that are intended to be the same but different language varients of one another are handled properly. In order to use a multi-language election in CDF format as intended in the VxSuite system the ExternalIdentifiers must be specified in this format. 
N/A 
Loaded a multi-language CDF election into VxAdmin, configured VxMark and VxScan and scanned hmpbs and verified language selector worked as expected.
=> Fix bug with multi-language CDF imports to VxSuite

apps/design/backend/migrations/1742944839600_election-content-tables.js
When I switched the contests.ballot_order column to be a serial instead of a number, I forgot to remove the insertion of numbers from the migration (to allow for unique serials to be generated instead).
=> VxDesign: Fix contest insertion in relational tables migration

apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/src/image_input.test.tsx, apps/design/frontend/src/image_input.tsx, apps/design/frontend/src/rich_text_editor.tsx, apps/design/frontend/src/seal_image_input.tsx, libs/ui/src/images/index.ts, libs/ui/src/images/normalize.ts, libs/ui/src/index.ts
Closes https://github.com/votingworks/vxsuite/issues/6091
- Adding a normalization step to image uploads, which shrinks large images to fit within specified bounds
- Adding maximum bounds for seals, signatures, and ballot measure images, based on the largest display/print size we expect.
- The ballot renderer renders images with their original width and height, which causes page overflow for large-enough images. We'll need to add max size restrictions there, which would allow us to set the max upload size appropriately for display in VxMark.
- This PR doesn't address potentially large SVG uploads (large image wrapped in an SVG).
- We can probably relax the 5MB restriction a bit, now that we're resizing before upload, but maybe worth addressing the large-SVG case first.
- Would be useful …
=> [VxDesign] Resize large user images before upload

libs/auth/README.md, libs/auth/scripts/remote-card-vx-certifier, libs/auth/scripts/src/configure_java_card.ts, libs/auth/scripts/src/remote_card_vx_certifier.ts, libs/auth/src/config.test.ts, libs/auth/src/config.ts, libs/auth/src/index.ts, libs/auth/src/java_card.test.ts, libs/auth/src/java_card.ts, libs/auth/src/keys.ts, libs/auth/src/signed_quick_results_reporting.ts
A little side project to take a task off my plate haha
We have a remote machine certification flow that we've used quite extensively to certify machines that are in the possession of someone who doesn't have acccess to the root VotingWorks private key. We don't yet have an analogous flow for card certification. This PR adds support for that and will make it such that others aren't blocked on the few of us with possession to the latest key when they need smart cards compatible with v4.0.1+ software images. Right now, we've been getting by by certifying and shipping cards around the country, which works but isn't great in a pinch.
Person without access to the root VotingWorks private key:
```
NODE_ENV=production VX_PRIVATE_KEY_PATH=remote WORKING_DIRECTORY=/media/psf/Shared …
```
=> Add support for a remote card certification flow

apps/mark-scan/fai-100-controller/src/fai_100_controllerd.rs
Exits with code `1` when the daemon fails to read from the FAI 100 (ATI controller + PAT input) USB device.
n/a
* Manual testing on hardware to be performed by @jdVotingWorks
=> FAI 100 daemon: exit on error when reading from device

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/context.ts, apps/design/backend/src/index.ts, apps/design/backend/test/helpers.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/base_types/log_source.ts, libs/logging/src/log_event_ids.ts, libs/logging/types-rust/src/log_event_enums.rs
Closes #6140 
Adds logging middleware to the design/backend API to log method arguments. This will allow us to cross reference API logs with alerts to better investigate.
Note that these logs are logged when the request is received before executing the API method handler. I went back and forth over whether it should happen before or after, but we already have logs from Heroku that are recorded after the request with status code and response time, so the before logs should fill in the information gap (namely, the input parameters) that we need for debugging. It might be a bit difficult to have to look at both log lines together to make sense of things, but the advantage of logging before the handler is that the request will be logged even if the app crashes. I figured that would be nice to …
=> design/backend: Log API calls

apps/scan/backend/src/electrical_testing/app.ts, apps/scan/frontend/src/electrical_testing/api.ts, apps/scan/frontend/src/electrical_testing/electrical_testing_screen.tsx, apps/scan/frontend/src/electrical_testing/sheet_images_modal.test.tsx, apps/scan/frontend/src/electrical_testing/sheet_images_modal.tsx
Adds a button to the "Scanner" status card that allows viewing the latest scanned image, if one exists.
https://github.com/user-attachments/assets/4405ceb6-29f0-4136-9013-5665b20031b1
Added some basic tests, but mostly tested manually. Ensured the button is absent when there are no scanned images and present and working when there are.
=> feat(scan): add basic view of latest hardware testing scanned image

libs/utils/src/hmpb/all_contest_options.test.ts, libs/utils/src/hmpb/all_contest_options.ts
When we know the contest type we know the contest option type. This change encodes this knowledge in the type system.
=> fix(utils): add overloads for contest types

libs/fixture-generators/src/generate-election-package/generate_election_package.ts
Regression from https://github.com/votingworks/vxsuite/pull/6069 that caused all election fixtures to be generated with multiple languages instead of respecting the `isMultiLanguage` flag.
=> libs/fixture-generators: Fix bug when picking languages to translate

apps/pollbook/frontend/src/add_voter_screen.tsx, apps/pollbook/frontend/src/address_input_group.tsx, apps/pollbook/frontend/src/app.test.tsx, apps/pollbook/frontend/src/app_poll_worker_screen.test.tsx, apps/pollbook/frontend/src/name_input_group.tsx, apps/pollbook/frontend/src/poll_worker_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx, apps/pollbook/frontend/vitest.config.ts
Closes https://github.com/votingworks/vxsuite/issues/6197.
Time out check-in and registration confirmation screens after 3s.
Check in:
https://github.com/user-attachments/assets/bd299897-a45a-4e03-a3e0-4b53d0037f36
Registration:
https://github.com/user-attachments/assets/10c26dce-c74b-4b9e-9888-d07779cae8d7
=> automatically reset after successful check in

libs/types/src/ui_theme.ts, libs/ui/src/icons.test.tsx, libs/ui/src/icons.tsx, libs/ui/src/themes/color_theme.stories.tsx, libs/ui/src/themes/make_theme.ts
Fixes: https://github.com/votingworks/vxsuite/issues/6167
Adds a new theme color `inverseWarningAccent`. Uses it for inverse warning icons (needed in VxPollbook).
Updated unit tests
=> libs/ui: Add inverseWarningAccent color to themes

apps/design/backend/src/app.test.ts, apps/design/backend/src/features.ts, apps/design/backend/src/globals.ts
We've [recently set up](https://votingworks.slack.com/archives/C085YT4798C/p1744203568443159) a `Vx Demos` org to use for external demos and would like to be able to demo the full feature set of VxDesign without displaying the full list of orgs like we do on the `VotingWorks` support account.
Adding feature flag configuration for the demo org, with most features switched on.
Will be adding the org ID env variable in prod.
- Updated unit tests 
- Manual test with mock IDs
- ~[ ] I have added the …
=> [VxDesign] Enable creation/export features for the 'Vx Demos' org

apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/index.ts, apps/pollbook/backend/src/pollbook_package.ts, apps/pollbook/backend/src/server.ts, apps/pollbook/backend/test/app.ts, apps/pollbook/frontend/src/api.ts, apps/pollbook/frontend/src/app.test.tsx, apps/pollbook/frontend/src/app.tsx, apps/pollbook/frontend/src/machine_locked_screen.tsx, apps/pollbook/frontend/src/nav_screen.tsx, apps/pollbook/frontend/src/system_admin_screen.tsx, apps/pollbook/frontend/src/system_administrator_screen.test.tsx, apps/pollbook/frontend/src/system_administrator_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx, apps/pollbook/frontend/test/render_in_app_context.tsx, apps/pollbook/frontend/vitest.config.ts, libs/logging/src/base_types/log_source.ts
Adds system administrator login and the following behavior.
* Election screen
* configure/unconfigure
* Settings screen
* Save logs
* Date & Time
I'll open separate PRs for USB formatting and Secure Hash Validation.
**Configure and unconfigure election**
https://github.com/user-attachments/assets/f5b44f39-1083-4afa-a704-396ababe7ccc
**Settings Screen**
https://github.com/user-attachments/assets/c11dcb75-ad1e-451a-a046-0231b7cb9ac8
=> VxPollbook: System admin login

apps/design/backend/src/worker/ballot_pdfs.test.ts, apps/design/backend/src/worker/ballot_pdfs.ts, apps/design/backend/src/worker/generate_election_package_and_ballots.ts, apps/design/backend/src/worker/grayscale.ts
We recently added support for tinted headers/footers to v4 NH ballots, which removed the grayscale conversion for all v4 NH ballots. This resumes grayscale conversion for all ballots except tinted v4 NH ballots.
This is to remove the responsibility of color space conversion from the print service provider (and to avoid the potential waste of printing non-color content in color).
Most recent relevant thread: https://votingworks.slack.com/archives/C08B80X72LE/p1744290147068419
Ballot tinting task: https://github.com/votingworks/vxsuite/issues/6141
| Non-Tinted  | Tinted |
| ![Screenshot 2025-04-10 at 14 33 56](https://github.com/user-attachments/assets/5a2ff3df-9095-48df-966b-843b9421e661) | ![Screenshot 2025-04-10 at 14 34 …
=> [VxDesign] Resume grayscale PDF conversion for non-tinted NH ballots

apps/admin/frontend/src/screens/tally/import_election_results_reporting_file_modal.tsx
Closes #5642. Confirmed there are no other messed up instances across apps. Visual bug is a result of some incomplete copy / UX edits I did for 4.0 release.
=> remove stray USB image

apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/frontend/src/screens/settings_screen.tsx, apps/pollbook/backend/src/app.ts, apps/pollbook/frontend/src/api.ts, apps/pollbook/frontend/src/machine_locked_screen.tsx, apps/pollbook/frontend/src/system_administrator_screen.test.tsx, apps/pollbook/frontend/src/system_administrator_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx, apps/pollbook/frontend/test/render_in_app_context.tsx, libs/ui/src/format_usb_modal.test.tsx, libs/ui/src/format_usb_modal.tsx, libs/ui/src/index.ts
https://github.com/votingworks/vxsuite/issues/6234
* reverts to previous copy for unconfigured screen https://github.com/votingworks/vxsuite/pull/6254#issuecomment-2794707175
* factors out `FormatUsbButton` to `libs/ui`
* adds usage of `FormatUsbButton` to VxPollbook
* deletes some unused params in `apps/pollbook` test helpers
https://github.com/user-attachments/assets/aa1cf5a4-dd0b-4c43-aa4f-23ad4cf251e5
- added tests to `libs/ui` and boundary tests to `apps/pollbook`
=> [VxPollbook] System admins can format USB drives

Cargo.toml, libs/ballot-interpreter/src/hmpb-rust/qr_code/detect.rs, libs/logging/bacon.toml, libs/pdi-scanner/bacon.toml
Per the Rust Programming Language Community Discord, `clippy::nursery` lints are not really ready for prime time.
https://discord.com/channels/273534239310479360/1120124565591425034/1361808848448655510
=> style(clippy): disable `nursery` lints

apps/admin/frontend/src/config/globals.ts, apps/admin/frontend/src/screens/tally/import_cvrfiles_modal.tsx, apps/admin/frontend/src/screens/unconfigured_screen.test.tsx, apps/admin/frontend/src/screens/unconfigured_screen.tsx
Closes #6064. Restricts loading VxAdmin from an election definition `.json` file to development. 
Tested manually & test written.
file selector in development:
file selector outside of development
=> VxAdmin: only allow loading `.zip` files in production

apps/design/backend/migrations/1742941957696_regenerate-duplicate-ids.js, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/ballots.test.ts, apps/design/backend/src/ballots.ts, apps/design/backend/src/index.ts, apps/design/backend/src/store.ts, apps/design/backend/src/utils.ts, apps/design/backend/src/worker/generate_election_package_and_ballots.ts, apps/design/backend/src/worker/generate_test_decks.ts, apps/design/frontend/src/ballot_screen.test.tsx, apps/design/frontend/src/ballots_screen.test.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/test/fixtures.ts, libs/backend/src/language_and_audio/ballot_strings.test.ts, libs/backend/src/language_and_audio/ballot_strings.ts, libs/backend/src/language_and_audio/election_package_string.test.ts, libs/backend/src/language_and_audio/election_package_strings.ts, libs/fixture-generators/src/generate-election-package/generate_election_package.test.ts, libs/fixture-generators/src/generate-election-package/generate_election_package.ts
#6298 combines the precinct types for VxDesign and the rest of VxSuite, which means VxDesign no longer needs to pass precincts around separately from the election object. This PR cleans up a bunch of that extra logic to avoid confusion in the future.
N/A
=> VxDesign: Cleanup precinct handling code

libs/auth/scripts/src/configure_java_card.ts, libs/auth/scripts/src/program_production_system_administrator_java_card_without_vx_admin.ts, libs/auth/src/config.test.ts, libs/auth/src/config.ts, libs/auth/src/java_card.test.ts, libs/auth/src/java_card.ts
When programming a Java Card, we write the cert authority cert of the VxAdmin that programmed the card to the card. In code, we refer to this certificate slot on the card as the `VX_ADMIN_CERT_AUTHORITY_CERT` slot. Let's rename that `PROGRAMMING_MACHINE_CERT_AUTHORITY_CERT` as the certificate in this slot may soon be either a VxAdmin cert or a VxPollBook cert.
Separating this rename out from the main PR for VxPollBook cert setup and card programming setup.
=> Generalize identifier for programming machine cert on Java Cards in prep for VxPollBook-programmed cards

apps/pollbook/backend/src/app_config.test.ts
https://github.com/issues/assigned?issue=votingworks%7Cvxsuite%7C6250
I wasn't sure how to handle both the fact that the usb drive polling is triggered every 100ms and can take 100ms or more to occur when I first wrote these tests and solved the problem by both advancing fake time and going back to real timers and sleeping. I have since learned through other tests that using vi.waitFor is the better and more robust solution so hoping this will solve the flakiness issue. 
n/a
Run several times locally & in CI
=> [VxPollBook] Fix flaky text app_config.test.ts

libs/logging/src/export.ts, libs/utils/src/json_stream.test.ts, libs/utils/src/json_stream.ts
https://github.com/votingworks/vxsuite/issues/6219
In an attempt to speed up CDF log exports, this adds support to `jsonStream` for handling raw JSON values, identified by instances of a new `RawJson` utility class. Using this in the VxF-to-CDF log converter to pre-stringify log events before yielding to the `jsonStream`, since the latter starts to get fairly expensive for large arrays and nested objects.
Assumption is that each log entry has a known shape, is fairly small, has its only freeform fields, `Details | Description` already stringified anyway.
Tested on `~127MB` sample log file from VxScan, this brings the export time from `~62-64 seconds` down to `~35-37 seconds` on my machine.
We can potentially shave off an extra `~30+` seconds by moving the log schema validation out of …
=> [logging] CDF exports: stringify each event before passing to jsonStream

apps/pollbook/frontend/src/machine_locked_screen.tsx
https://github.com/votingworks/vxsuite/issues/6297
Centers text on the unlock screen.
Before
After
Manually tested render
=> center align the unlock screen

apps/mark-scan/frontend/src/app_cardless_voting.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx
Revision to #6316 
Based on some team feedback, "ballot style" is a better descriptor than "precinct" in this flow.
Updated tests
=> VxMark: Use "ballot style" copy for voter session activation flow

libs/logging-utils/index.d.ts, libs/logging-utils/package.json, libs/logging-utils/src/lib.rs, libs/logging-utils/test/index.test.ts, pnpm-lock.yaml
Introducing the `ThreadsafeFunction` indirection caused the call context with `logger.logAsCurrentRole` to be lost, so `this` was `undefined` which caused a crash. This changes the API to just accept a plain function to avoid this problem.
n/a
Added a test that uses the real `Logger`, though that's sort of moot with the API change.
=> fix(logging-utils): don't crash when logging from converter

libs/logging-utils/README.md, libs/logging-utils/package.json, libs/logging-utils/test/zellij-layout.kdl, pnpm-lock.yaml
This adds a `build:watch` script to make it easier to rebuild the Rust addon whenever the code changes. Additionally, if you have `zellij` installed, running `pnpm test` in development will run both `vitest` and `pnpm build:watch`.
Tested locally in VS Code, Zed, and Ghostty. VS Code steals ^Q, so quitting `zellij` there is less ideal (just spam ^C).
=> build(logging-utils): improve the build & test loop DX

apps/mark-scan/frontend/src/app_cardless_voting.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, libs/utils/src/ballot_styles.test.ts, libs/utils/src/ballot_styles.ts
Another follow up to #6316
In a general election, there's exactly one ballot style group for each precinct or split. However, in a primary election, there are multiple - one for each party. To handle this case, we add a second selection step for the party when a poll worker is starting a new voter session.
https://github.com/user-attachments/assets/fde4d667-bfe0-4ad3-ac80-cd2556d67d50
- Added new test coverage
- Relied on existing tests to prevent regressions for the general election case
=> VxMark: Handle primary elections in start voter session flow

libs/dev-dock/frontend/src/dev_dock.test.tsx
Mimic the timeout from an assertion a few lines above.
=> dev-dock: Fix flaky test by increasing timeout

apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.test.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_shared_components.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_tab.test.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_tab.tsx, apps/admin/integration-testing/e2e/screenshots.spec.ts, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, libs/types/src/election.test.ts, libs/types/src/election_utils.ts
Task: https://github.com/votingworks/vxsuite/issues/6123
Instead of selecting a ballot style ID and a precinct in two dropdowns, merge this choice into a single dropdown that uses precinct/split name (and party name, in primaries), to label each ballot style/precinct combination.
https://github.com/user-attachments/assets/c0eb5d11-9ee7-4db7-a275-ed6e8b57f622
Manual testing and updated automated tests
=> VxAdmin: Improve ballot style selection in manual tally entry 

apps/pollbook/backend/vitest.config.ts
In #6345, I moved all upgraded packages, including `pollbook/backend`, to negative test thresholds. It seems like `pollbook/backend` has variable line coverage across runs. Perhaps due to inconsistent behavior across network simulations? To prevent these failures on main, bumping the threshold by 1.
=> bump `pollbook/backend` `vitest` threshold

apps/design/frontend/src/system_settings_screen.test.tsx, apps/design/frontend/src/system_settings_screen.tsx
Ensure all form controls are disabled by default and enable them only after clicking the "Edit" button.
=> fix(design): disable controls until "Edit" is clicked

libs/printing/src/printer/device_uri.test.ts, libs/printing/src/printer/device_uri.ts
Fix for #5525. Address issue where VxAdmin (and VxPollBook) crash occasionally when left idle overnight. Root cause analysis [in comment](https://github.com/votingworks/vxsuite/pull/6348#issuecomment-2840845466). Fix is just retrying on failure. 
Automated tests cover the retry code paths. Manually tested that this closes the issue.
=> VxAdmin: address crashing on idle

apps/admin/backend/src/app.ts, libs/fs/src/list_directory.test.ts, libs/fs/src/list_directory.ts, libs/usb-drive/src/list_directory_on_usb_drive.ts
Closes #5673. Instead of only searching the root of the USB, also searches up to a depth of 3, which means that packages exported on VxAdmin will later be detected by an unconfigured VxAdmin. This is mostly to address internal annoyance during testing. There are probably few customer use cases because customers should be using freshly formatted drives, but if they are re-using a drive and do not place the VxDesign file at the root, it would likely be caught now.
=> VxAdmin: search for election packages on USB drive up to depth 3

apps/admin/frontend/src/components/adjudication_double_vote_alert_modal.tsx, apps/admin/frontend/src/components/write_in_adjudication_button.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx
Feedback from offsite electioneers - 
1. Rename "Not a mark" to "Invalid mark"
2. Unsure where to click at first to adjudicate a write-in, what to do after clicking, and where to click to create a new candidate. They liked when I adjusted the copy to give more direction in placeholder texts (3 places)
Edit 5/6 - Drew signed off on these during sync today
Old...
https://github.com/user-attachments/assets/e6b2f7a5-879c-42b4-a7c7-9ac5908140ba
New...
https://github.com/user-attachments/assets/f6ab3910-d606-4412-915a-5dcb4a4dddd5
=> Adjust contest adjudication copy for clarity

apps/admin/frontend/src/utils/reporting.test.ts, apps/admin/frontend/src/utils/reporting.ts
Follow up to #6341. Instead of putting the ballot style ID in the report filename when filtering by ballot style, just bail and call it a custom report (similar to how we no longer show the ballot style ID in the report title).
N/A
=> VxAdmin: Don't include ballot style ID in report filenames

apps/design/frontend/src/system_settings_screen.test.tsx, apps/design/frontend/src/system_settings_screen.tsx, libs/backend/src/cast_vote_records/build_cast_vote_record.test.ts, libs/backend/src/cast_vote_records/build_cast_vote_record.ts, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts, libs/types/src/system_settings.ts
https://github.com/votingworks/vxsuite/issues/5778
Now that Admin will be doing mark adjudication, the original snapshot is no longer optional, as it contains mark threshold data. This snapshot will also eventually be needed for [cumulative cvr export](https://docs.google.com/document/d/1rfK6BX375Tjiv3eaPYaYNr3VkPGIIF6TQctHIEUHnho/edit?tab=t.lxnmmzw8zcea)
Old VxDesign
New VxDesign
=> Remove castVoteRecordsIncludeOriginalSnapshots system setting

libs/auth/src/inserted_smart_card_auth.ts
https://github.com/votingworks/vxsuite/issues/6217
We recently added response diffing logic to polling requests across VxSuite to skip updating the cache (and triggering re-renders) when the data hasn't changed.
On VxMark, we're running into an edge case where the auth object changes on every request, since we generate a new (unused) session expiry date each time and this was causing performance issues on pages with lots of elements and manifesting in glitchy audio playback.
Patching by locking the session expiry to a static future date, since it's unused, to keep the auth status response stable for diffing. Voter sessions have a separate timeout logic path.
- Reproduced audio issues in a VM with CPU limiting on the kiosk-browser process - then, verified that there's no audible glitching …
=> [libs/auth] Fix audio performance issues due to unstable auth data

apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx
Jonah noticed a [test failure](https://app.circleci.com/pipelines/github/votingworks/vxsuite/19927/workflows/b7e438cb-7f9b-4af7-aa41-e6140cf0d055/jobs/843444/tests#failed-test-0). I haven't been able to repro nor have I seen it occur on other test invocations, but I think this change is helpful. 
The repeated change is when scrolling from cvr A to cvr B - previously the tests awaited the checkboxes to appear as a signal the digital ballot has loaded, but maybe the checkboxes would be around from the previous cvr. Now, we wait for the testID to change before looking for the checkboxes.
=> Admin: Fix flaky contest adjudication test

apps/scan/backend/src/app_export.test.ts
This test sporadically fails when run locally (hasn't failed in CI yet as far as I can tell, but it's conceptually possible for it to fail there, too). Addressed by explicitly advancing time to ensure that we get two CVR export directories with unique directory names, e.g., `TEST__machine_0000__2025-05-07_10-15-51` and `TEST__machine_0000__2025-05-07_10-15-52`
```
FAIL  src/app_export.test.ts > continuous CVR export, including polls closing, followed by a full export
AssertionError: expected [ Array(1) ] to have a length of 2 but got 1
- Expected
+ Received
- 2
+ 1
❯ src/app_export.test.ts:165:36
163|       }
164|       console.log(exportDirectoryPaths);
165|       expect(exportDirectoryPaths).toHaveLength(2);
|                                    ^
166|
167|       for (const …
```
=> Address flaky test by explicitly advancing time

apps/central-scan/backend/src/app.ts
The JSON parser was interfering with the grout API, since the deprecated API endpoints were mounted first at the app root. To fix this, we mount the deprecated API router at `/central-scan` so that its middleware is scoped only to those endpoints.
N/A
Manually tested that I can run the app locally and the dev dock works
=> central-scan/backend: Don't mount deprecated API endpoints at root

apps/mark-scan/frontend/src/app_contest_write_in.test.tsx, apps/mark/frontend/src/app_contest_write_in.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/mark-flow-ui/src/components/review.test.tsx, libs/mark-flow-ui/src/components/review.tsx, libs/mark-flow-ui/src/components/write_in_candidate_name.test.tsx, libs/mark-flow-ui/src/components/write_in_candidate_name.tsx, libs/ui/src/index.ts, libs/ui/src/ui_strings/play_audio_clips.test.tsx, libs/ui/src/ui_strings/play_audio_clips.tsx, libs/ui/src/virtual_keyboard/virtual_keyboard.tsx
Resolves https://github.com/votingworks/vxsuite/issues/6328
Updating the candidate contest and review screens to read out write-in candidate names as the same series of letters that were typed out on the write-in keyboard (we would previously read out "write-in" instead).
- Noticing how weird it sounds for the screen reader to say "single quote" - will follow up with a PR to update that to say "apostrophe" instead.
https://github.com/user-attachments/assets/15a8bbcc-44e3-452b-ba5a-01f5e302b211
https://github.com/user-attachments/assets/4f29f962-8ee4-43b5-ba2c-899f607ad84e
- Mostly manual for verifying audio - with basic unit tests to make sure expected, valid characters render successfully as individual letters.
=> [VxMark] Read out write-in candidate names just are they were typed

apps/admin/backend/src/exports/csv_shared.ts, apps/admin/backend/src/reports/titles.ts, apps/admin/backend/src/util/cast_vote_records.ts, apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.tsx, apps/design/backend/src/test_decks.test.ts, apps/scan/frontend/src/screens/poll_worker_fujitsu_post_print_screen.tsx, libs/backend/src/cast_vote_records/build_cast_vote_record.ts, libs/ballot-interpreter/src/interpret_bmd_and_hmp_ballots.test.ts, libs/ui/src/reports/admin_tally_report_by_party.tsx, libs/ui/src/reports/ballot_count_report.tsx, libs/ui/src/reports/custom_filter_summary.tsx, libs/ui/src/reports/precinct_scanner_report_header.tsx, libs/ui/src/reports/write_in_adjudication_report.tsx, libs/utils/src/ballot_styles.test.ts, libs/utils/src/ballot_styles.ts, libs/utils/src/tabulation/index.ts, libs/utils/src/tabulation/lookups.test.ts, libs/utils/src/tabulation/lookups.ts
Closes #6357. 
The bug was occurring because we were using `indexOf` to identify the index of the `contest` within the list of `contests`. Because these are objects, this only works if the contests are identical object references. Because the `contest` is coming from the `getContestById` function which is actually caching results for faster lookups, the comparison stops working as soon as the `electionDefinition` cached by React Query is different than the one cached by `getContestById`. I'm not sure how this happens in practice, but you can recreate this bug in dev with the React Query devtools by resetting the `getCurrentElectionMetadata` query while doing manual results.
As far as the fix - the current fix is just a one line fix to address the issue. Any suggestions to do more to avoid …
=> VxAdmin: fix zero index manual tally bug

apps/admin/frontend/src/components/app_routes.tsx, apps/pollbook/backend/src/index.ts, apps/pollbook/frontend/src/app.test.tsx, apps/pollbook/frontend/src/app.tsx, apps/pollbook/frontend/test/mock_api_client.tsx
https://github.com/votingworks/vxsuite/issues/6309
Adds vendor auth support. Duplicates https://github.com/votingworks/vxsuite/pull/6411, which was accidentally branched off another feature branch.
@nikhilb4a sorry for the mixup! Rerequesting review since merging is blocked again. (Reopened rather than rebased in order to push the more accurate branch name)
https://github.com/user-attachments/assets/87a4a248-37f1-404f-b811-c40fe3746676
Added test that vendor screen is rendered. The rest of the vendor flow is covered by library tests.
=> Pollbook vendor auth

apps/central-scan/frontend/prodserver/index.js, apps/scan/frontend/prodserver/index.js
I noticed that the log source was incorrect in some VxScan logs. Looks like a copy-paste error.
N/A
Checked all the prodserver files
=> Fix log source in scan/central-scan frontend prodserver

.dockerignore, Dockerfile.vxdesign
The VxDesign deploy pipeline's been broken by a new transitive dependency on Rust tooling (which previously didn't need to be installed).
Adding a Rust installation layer to the Docker image to unblock. This also required removing `mark-scan` from the `dockerignore` list, since the Rust build fails otherwise, when it can't find all the projects referenced in the root `Cargo.toml`
- Via a Heroku review app
=> [VxDesign] Add Rust installation to deploy container image

apps/central-scan/backend/src/app.ts, apps/central-scan/backend/src/end_to_end_bmd.test.ts, apps/central-scan/backend/src/end_to_end_hmpb.test.ts, apps/central-scan/frontend/src/app.test.tsx, apps/central-scan/frontend/src/components/export_results_modal.test.tsx, apps/central-scan/frontend/src/components/export_results_modal.tsx, apps/central-scan/frontend/src/screens/diagnostics_screen.tsx, apps/central-scan/frontend/src/screens/scan_ballots_screen.test.tsx, apps/central-scan/frontend/src/screens/scan_ballots_screen.tsx, apps/central-scan/frontend/src/screens/settings_screen.test.tsx, apps/central-scan/frontend/src/screens/settings_screen.tsx, apps/central-scan/frontend/test/api.tsx, libs/backend/src/cast_vote_records/export.test.ts, libs/backend/src/cast_vote_records/export.ts
https://github.com/votingworks/vxsuite/issues/5781
Previously `central-scan`'s `exportCastVoteRecordsToUsbDrive` mutation offered a minimal export that excluded most ballot images (those w/o write-ins and rejected ballots). Now we plan to include them all to ensure ballots with marginal marks will be viewable. If performance is hit too significantly, we can optimize this by filtering out images. Conversation [here](https://votingworks.slack.com/archives/CEL6D3GAD/p1746555973582259).
This PR removes the `isMinimalExport` option for cvr exports on `central-scan` and the "Save Backup" UI option, as "Save CVRs" will now always perform the same comprehensive backup that "Save Backup" previously did.
https://github.com/user-attachments/assets/ab99b9b3-cb31-4ac5-a386-890982741c55 …
=> CentralScan: Always export all ballot images

apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/app_config.test.ts, apps/pollbook/backend/src/app_multi_node.test.ts, apps/pollbook/backend/src/networking.ts, apps/pollbook/backend/src/peer_app.ts, apps/pollbook/backend/src/types.ts, apps/pollbook/frontend/src/api.ts, apps/pollbook/frontend/src/app.test.tsx, apps/pollbook/frontend/src/app_election_manager_screen.test.tsx, apps/pollbook/frontend/src/app_poll_worker_screen.test.tsx, apps/pollbook/frontend/src/election_info_bar.tsx, apps/pollbook/frontend/src/election_manager_screen.test.tsx, apps/pollbook/frontend/src/machine_locked_screen.tsx, apps/pollbook/frontend/src/nav_screen.tsx, apps/pollbook/frontend/src/smart_cards_screen.test.tsx, apps/pollbook/frontend/src/system_administrator_screen.test.tsx, apps/pollbook/frontend/test/mock_api_client.tsx
https://github.com/votingworks/vxsuite/issues/6179
Following up on https://github.com/votingworks/vxsuite/pull/6370 this PR finishes the implementation of the new pollbook package hash. It updates the networking logic to only "connect" two machines and share events in the ballot hash and pollbook package hash match, rather than checking the election id. In addition we update the frontend to show the first 7 characters each of the ballotHash-pollbookPackageHash as the election ID in the UI, matching the ballotHash-electionPackageHash structure in vxsuite. 
Tested UI was updated as appropriate, tested basic connection logic.
=> Implement Pollbook Package Hash

libs/pdi-scanner/src/rust/main.rs, libs/pdi-scanner/src/rust/rusb_async/error.rs, libs/pdi-scanner/src/rust/rusb_async/mod.rs
Task: https://github.com/votingworks/vxsuite/issues/5984
In production environments, we've seen `LIBUSB_TRANSFER_ERROR` occur when the scanner is disconnected due to a USB blip (root hardware cause still unknown). To mitigate this, we create a new error variant for this specific error code and treat it as a disconnection. The higher-level state machine logic already tries to reconnect continuously when disconnected, and manual testing has shown that this is sufficient to recover from one of these blips.
There is a slight risk that there may be other causes of `LIBUSB_TRANSFER_ERROR` that are not disconnections, but rather actual unrecoverable errors. In that case, after this change, we'll be showing the "Internal Connection Problem" screen instead of the "restart the scanner" message. I …
=> pdi-scanner: Treat LIBUSB_TRANSFER_ERROR as disconnection

libs/pdi-scanner/examples/scan_forever.rs, libs/pdi-scanner/src/rust/client.rs, libs/pdi-scanner/src/rust/main.rs, libs/pdi-scanner/src/rust/parse_traffic.rs, libs/pdi-scanner/src/rust/protocol/image.rs
Task: https://github.com/votingworks/vxsuite/issues/6127
We saw a few cases in the field where the logging indicated that a failed scan (likely due to the paper not being grabbed by the rollers) was followed quickly after by a second scan starting. In these cases, the state machine hadn't yet finished attempting to clear out the ballot from the first failed scan, and crashed when the second scan started, since it was unexpected.
To prevent scan events from occurring in rapid succession like this, we disable the auto-feeding immediately after receiving the scan end event from the PDI scanner. Unfortunately, we have to turn the feeder back on in order to eject ballots, but we do so immediately before sending the eject command, so it should be fairly safe.
N/A - wasn't able to reproduce the …
=> pdi-scanner: Disable auto-feeding after scan completes

apps/pollbook/backend/src/app.test.ts, apps/pollbook/backend/src/local_store.ts, libs/db/src/client.test.ts, libs/db/src/client.ts
https://github.com/votingworks/vxsuite/issues/6164
Ignore case, apostrophes, dashes, and whitespace in voter name search.
This is `o(n)`. I haven't noticed any slowdown on the test pollbook package with ~6000 voters but we'll most likely want to replace the regexp search with computing and storing a normalized name column in the future. I didn't do it in this PR because
1. This was much faster to write
2. I'm not sure how much is still in flux with pollbook package reading, voter input files, and so on
https://github.com/user-attachments/assets/3e6b3668-1014-4dbd-9c70-a49e128fa97f
https://github.com/user-attachments/assets/ca0d6568-17fd-4e45-a72d-c141488d1235
https://github.com/user-attachments/assets/10835a69-9ca8-45ca-aa73-592d2203a6cf
- Pollbook backend tests
- libs/db tests
=> [pollbook] handle punctuation and whitespace in search

libs/types/src/system_settings.ts
Task: #6360 
Adds a new system settings flag to enable VxScan to read ballot IDs from HMPBs, encrypt them, and add them to the CVRs.
N/A
Nothing to test quite yet, but will get tested in future PRs
=> Add system settings flag to enable auditable ballot IDs

apps/mark-scan/frontend/src/app.tsx, apps/mark-scan/frontend/src/electrical_testing/app.tsx, apps/mark-scan/frontend/src/mark_scan_app_base.tsx
For use in both the real app and the hardware test app, so we can use `@votingworks/ui` et al in both.
No changes yet, but this is needed to bring the new HTA UI that we use in VxScan.
Manually tested in a VM to ensure the HTA still works as-is.
=> refactor: extract `MarkScanAppBase`

libs/backend/src/system_call/api.test.ts, libs/backend/src/system_call/export_logs_to_usb.test.ts, libs/backend/src/system_call/export_logs_to_usb.ts, libs/ui/src/export_logs_modal.test.tsx, libs/ui/src/export_logs_modal.tsx
https://github.com/votingworks/vxsuite/issues/6325
We had a report come out of cert testing of a `copy-failed` error during a logs export, but we don't have granular enough logs to figure a root cause.
Adding the original error as additional log metadata to help with that (as well as upcoming attempts to repro on a real machine).
- Manual + updated unit tests
=> [libs/backend] Add more detail to log export errors

libs/ballot-encoder/README.md, libs/ballot-encoder/src/index.test.ts, libs/ballot-encoder/src/index.ts, libs/ballot-interpreter/src/hmpb-rust/metadata/hmpb.rs, libs/ballot-interpreter/src/hmpb-rust/metadata/types.rs, libs/types/src/election.ts
Adds the ability to encode an audit ballot ID to ballot metadata (which goes in the HMPB QR code). I ended up repurposing the ballot ID field that I just removed in #6374 but had left in the encoding for backwards compatibility - a nice coincidence. I also added the ability to decode the audit ballot ID in the ballot interpreter.
N/A
=> Add support for audit ballot ID to encoded ballot metadata

apps/design/backend/src/worker/generate_election_package_and_ballots.ts, libs/ballot-encoder/src/index.ts, libs/ballot-interpreter/src/hmpb-rust/metadata/hmpb.rs, libs/ballot-interpreter/src/hmpb-rust/metadata/types.rs, libs/types/src/election.ts, libs/types/src/system_settings.ts
Missed a couple spots in #6439 😳  
N/A
=> Rename system settings flag for VxScan ballot audit IDs

apps/admin/integration-testing/e2e/screenshots.spec.ts
I've noticed this test timeout somewhat often and just saw it fail on main. When I last worked on it I noticed it silently retrying sometimes increasing ci times, and seems like it's often enough that we should bump it. It's pretty comprehensive (lots of adjudications, reports) so it feels reasonable to give it this longer timeout.
=> apps/admin: Bump timeout for flaky integration test

libs/ballot-interpreter/src/interpret_vx_hmpb.test.ts, libs/hmpb/src/ballot_components.tsx, libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx
Task: #6360 
Removes the printed ballot audit ID from HMPBs to improve privacy. It will still be encoded in the QR code metadata.
N/A
Existing automated tests
=> Remove ballot audit ID plaintext from HMPB footer

libs/ui/src/virtual_keyboard/virtual_keyboard.test.tsx
Might fix the flaky test for VirtualKeyboard: https://app.circleci.com/pipelines/github/votingworks/vxsuite/19751/workflows/db1bdd70-6ece-4fd4-9409-48e0b747159a/jobs/833610
I believe the test assertion happens before the DOM updates on rare occasions. To try to fix this, we use `vi.waitFor` to wait until the expected key is focused.
N/A
Couldn't repro locally so we'll see if this solves the issue in CI.
=> Fix flaky test in VirtualKeyboard

apps/scan/backend/src/electrical_testing/tasks/print_and_scan_task.ts
Closes https://github.com/votingworks/vxsuite/issues/6463
FAT32 doesn't like colons in filenames. This replaces them with dashes.
n/a
=> fix(scan): make the HTA image filenames safe for FAT32

apps/scan/backend/src/electrical_testing/app.ts, apps/scan/backend/src/electrical_testing/simple_scanner_client.ts
Closes #6462
Currently we're limited to testing ballots that are 11" long. This unblocks testing longer ballots, but introduces the possibility that we double-feed ballots in testing. We can overcome this later by adding a configuration setting for the ballot length.
n/a
=> fix(scan): scan up to 22" ballots in HWTA

apps/central-scan/backend/.eslintrc.json, apps/mark-scan/backend/.eslintrc.json, apps/mark/backend/.eslintrc.json, apps/scan/backend/.eslintrc.json
These were added due to a bug or configuration issue with an older version of TypeScript and/or `@typescript-eslint/eslint-plugin`. Removing them seems to have no effect on linting, so I'm removing them.
n/a
Automated linting.
=> chore(eslint): remove outdated overrides

apps/scan/backend/package.json, apps/scan/backend/schema.sql, apps/scan/backend/src/app.ts, apps/scan/backend/src/app_export.test.ts, apps/scan/backend/src/export.ts, apps/scan/backend/src/scanners/shared.ts, apps/scan/backend/src/store.ts, apps/scan/backend/test/helpers/pdi_helpers.ts, apps/scan/backend/tsconfig.json, libs/auth/scripts/decrypt-cvr-ballot-audit-ids, libs/auth/scripts/src/decrypt_cvr_ballot_audit_ids.ts, libs/auth/src/cryptography.end_to_end.test.ts, libs/auth/src/cryptography.test.ts, libs/auth/src/cryptography.ts, libs/auth/src/index.ts, libs/backend/src/cast_vote_records/export.ts, pnpm-lock.yaml
Task: #6360 
When the `precinctScanEnableBallotAuditIds` system setting is turned on, VxScan will:
- Generate a random secret key on configure and store it in the db
- Encrypt ballot audit IDs from scanned ballot metadata and add them to the CVR
This PR also adds a script to decrypt the ballot audit IDs for all of the CVRs in an export directory, copying them into a new directory and renaming each CVR JSON file with the decrypted audit ID for easy reference during an audit.
Example encrypted ballot audit ID in a CVR
Example decryption script output from a CVR export with ballots with audit IDs 1, 2, and 3
- Manual end to end testing
- Added new automated tests
=> VxScan: Encrypt ballot audit IDs

apps/scan/backend/src/app.ts, apps/scan/backend/src/app_export.test.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/components/save_ballot_audit_id_secret_key_button.tsx, apps/scan/frontend/src/screens/election_manager_screen.test.tsx, apps/scan/frontend/src/screens/election_manager_screen.tsx, libs/auth/scripts/src/decrypt_cvr_ballot_audit_ids.ts
Task: #6360 
Adds a button the VxScan election manager screen (under the CVRs and Logs tab) to save the ballot audit ID secret key to the inserted USB drive. Only shows the button if the system settings flag for this feature is enabled. Exports the key to a plain text file at the root directory of the USB drive.
https://github.com/user-attachments/assets/f94d50b5-9a42-485d-bec8-78c3af0efbd4
- Manual test
=> VxScan: Button for election manager to save ballot audit ID secret key to USB drive

apps/scan/frontend/src/api_machine_configuration.test.tsx, apps/scan/frontend/src/api_provider.tsx, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/components/layout.tsx, apps/scan/frontend/src/components/scanned_ballot_count.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/ui/src/__snapshots__/bmd_paper_ballot.test.tsx.snap, libs/ui/src/__snapshots__/modal.test.tsx.snap, libs/ui/src/ui_strings/read_on_load.tsx, libs/ui/src/ui_strings/with_alt_audio.tsx
https://github.com/votingworks/cert-discrepancies/issues/123
Enabling the screen reader for voter-facing app and election strings VxScan. Audio playback will be dependent on [headphones being plugged in](https://github.com/votingworks/vxsuite/blob/c44f5d2/libs/ui/src/ui_strings/audio_context.tsx#L100-L103) - headphone detection is done via [shell command](https://github.com/votingworks/vxsuite/blob/main/libs/backend/src/system_call/get_audio_info.ts) to pulse audio, which will need to be tested on a production machine to verify the configuration and output parsing used for VxMark are sufficient here.
Adding a `<ReadOnLoad>` to the shared `<Screen>` component for voter-facing instances to trigger audio whenever headphones are plugged in or a screen/modal transition happens. Might need to …
=> [VxScan] Enable screen reader audio for voter-facing screens

libs/ballot-interpreter/src/hmpb-rust/diagnostic.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs
We want it to be the case that we can always reinterpret an image and get the same result as the initial interpretation. This may not have been the case before because we used the pre-cropping threshold (which should be lower or equal) to determine the threshold we use. With just the cropped image it is impossible to recover that pre-cropping threshold, so we cannot reinterpret in exactly the same way. This change fixes that by re-computing the threshold after cropping.
I had to set a maximum threshold for the diagnostic function because we're scanning white pages and the automatic threshold may end up being set fairly high. This is the nature of [Otsu's Method](https://en.wikipedia.org/wiki/Otsu%27s_method):
> This threshold is determined by minimizing intra-class intensity variance, or …
=> fix(scan): recompute threshold after cropping

libs/eslint-plugin-vx/vitest.config.ts, libs/ui/vitest.config.ts, vitest.config.shared.mts
Closes https://github.com/votingworks/vxsuite/issues/6072
Removes our custom config merge function and replaces it with `mergeConfig` from `vitest`.
n/a
Automated testing. I also diffed the merged configs in a few project and found that the only difference is in how values excluded from coverage were handled. `mergeConfig` appends the arrays from the base and the extension together, whereas ours replaced the values. I think `vitest`s is probably more correct.
=> chore(vitest): use built-in `mergeConfig`

apps/pollbook/frontend/src/nav_screen.test.tsx, apps/pollbook/frontend/src/nav_screen.tsx
https://github.com/votingworks/vxsuite/issues/6205
Users have found it confusing that this number does not include the current machine. This adds one to the number to accomplish that. Adds basic testing of the network icon, more testing of the modal will come when we revamp that. 
Ran Tests
=> Add one to connected machine count and add basic testing

apps/scan/frontend/src/screens/voter_screen.test.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, apps/scan/frontend/src/utils/use_scan_feedback_audio.test.ts, apps/scan/frontend/src/utils/use_scan_feedback_audio.ts, apps/scan/frontend/src/utils/use_sound.ts, libs/ui/src/index.ts
https://github.com/votingworks/vxsuite/issues/6484
Now that we're enabling screen reader audio over headphones on VxScan, the scan success/fail sounds collide with speech audio and are redundant. Skipping those sounds whenever we detect that headphones are plugged in.
https://github.com/user-attachments/assets/ae625cfc-6a7f-4ab4-b0b6-d134e7fbe7f4
https://github.com/user-attachments/assets/ef53b435-0fb3-4bfc-a557-b727fadc3ecc
- Manual & unit tests - broke out state-based audio logic to make testing easier
=> [VxScan] Mute scan success/fail sound effects when using headphones

apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.test.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.tsx
Closes #6381 and #6356. In testing negative manual tally values, I noticed decimal values are currently also allowed, which this PR also addresses.
The issue of number inputs changing on scroll is just browser behavior. The two options I could find to turn of it off were a) use a text input or b) use event handlers to stop the default behavior. I preferred a) because it seemed a bit cleaner and lent itself to solving the negative number problem.
- updated existing tests
- new test for negative and decimal
- there isn't a way to test the scroll thing because it's browser behavior, not react behavior, that does not exist in the test environment
=> VxAdmin: prevent negative and decimal manual tallies + prevent change on scroll

apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.test.tsx, apps/admin/frontend/src/screens/tally/manual_tallies_form_screen.tsx
Issue link: https://github.com/votingworks/vxsuite/issues/6129
This PR addresses a bug where contest overrides of ballot counts are wrongly cleared when the manual tally flow is reopened.
https://github.com/user-attachments/assets/c9dba68c-3a02-4bae-8756-72a94fd6c603
=> Address bug where contest overrides of ballot counts are wrongly cleared

libs/pdi-scanner/src/rust/client.rs, libs/pdi-scanner/src/rust/main.rs
In #6386, we added a "disable feeder" command after receiving the `EndScan` event (in order to prevent a new scan from starting too quickly). It turns out there's a built-in setting for this behavior, so we use that instead (which should be even more effective).
N/A
Some basic manual testing
=> pdi-scanner: Use built-in setting to disable feeder after scan

libs/types-rs/src/geometry.rs
Previously, `Rect::zero` used with `foldl` to determine an extent of `Rect` instances would always start at the origin. Now it properly starts at the minimum x and y values present in all the non-zero-sized `Rect`s.
|-|-|
|![CleanShot 2025-05-28 at 20 13 49@2x](https://github.com/user-attachments/assets/afb74344-55e1-4897-a6e3-11f8697323a5)|<img width="180" alt="image" src="https://github.com/user-attachments/assets/764b59ba-ef5e-4227-9438-65192864ea3c" />|
Tested manually for its effect on debug images. Added a unit test.
=> fix(types-rs): ignore zero-sized rects in `Rect::union`

libs/ballot-encoder/README.md
([Slack thread](https://votingworks.slack.com/archives/CJU9MSC6S/p1748543525840719))
We (mistakenly) made the maximum size 4096 instead of 4095, so that would take 13 bits rather than 12 since the indexes are 0-based.
=> docs: correct bit count for indexes

libs/ballot-interpreter/src/hmpb-rust/interpret.rs
Task: #5294 
Now that we're switching the PDI scanner from bitonal to grayscale scanning, the ballot images it produces are much larger. In order to preserve the amount of disk space used, we want to binarize them before saving. For reference, the binarized images are ~100KB, while the grayscale images are ~4MB.
Previously, the interpreter passed through whatever ballot images it was given after cropping and normalizing their orientation. This PR changes it to also binarize the image. This will also have the side-effect of binarizing images in VxCentralScan, which will be good for consistency.
Example binarized image
- Added a basic unit test
- Ran benchmarks and saw no perf regression
=> ballot-interpreter: Save binarized ballot images

libs/ballot-interpreter/src/hmpb-ts/cli.ts
`writeImageData` expects `ImageData` instances, not look-alikes.
n/a
Tested manually.
=> fix(scan): make `bin/interpret --json` work again

docs/exercises/01-iteration/09-image-diff.exercise.ts, libs/ballot-interpreter/src/interpret_all_bubble_ballot.test.ts, libs/ballot-interpreter/src/interpret_vx_hmpb.test.ts, libs/basics/src/iterators/async_iterator_plus.test.ts, libs/basics/src/iterators/async_iterator_plus.ts, libs/basics/src/iterators/iterator_plus.test.ts, libs/basics/src/iterators/iterator_plus.ts, libs/basics/src/iterators/types.ts
Mirrors Rust's [`std::slice::chunks_exact`](https://doc.rust-lang.org/std/primitive.slice.html#method.chunks_exact) method.
```ts
const pairs = iter([1, 2, 3, 4]).chunksExact(2);
assert.deepStrictEqual([...pairs], [[1, 2], [3, 4]]);
```
New automated tests.
=> feat(basics): add `iter::chunksExact`

apps/pollbook/backend/src/app_multi_node.test.ts
When we're relying on the networking polling interval on multiple machines to trigger it is somewhat tricky in tests to make sure we're waiting enough time for the condition we're looking for. I tried various timeout settings, using shouldAdvanceTime as true, etc. but the only thing that seemed to make tests reliably pass was adding an increased timeout on all the waitFor calls, so this sets up that pattern in app_multi_node, its not possible to set this with a global config. 
n/a
Used modified CI that runs only this job 25 times, ran that 3x total and saw no failures.
=> Fix Flaky PB Networking Test

libs/ballot-interpreter/src/hmpb-rust/image_utils.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs
In the event that there is no need to crop off any pixels from the image, skip copying the pixels over to a newly allocated image and just return the original.
n/a
=> perf(scan): stop uselessly cropping images

libs/mark-flow-ui/src/components/candidate_contest.test.tsx, libs/mark-flow-ui/src/components/candidate_contest.tsx, libs/ui/src/virtual_keyboard/scan_panel_virtual_keyboard.test.tsx, libs/ui/src/virtual_keyboard/scan_panel_virtual_keyboard.tsx, libs/ui/src/virtual_keyboard/virtual_keyboard.test.tsx, libs/ui/src/virtual_keyboard/virtual_keyboard.tsx
Resolves https://github.com/votingworks/vxsuite/issues/6444
Follow-up from https://github.com/votingworks/vxsuite/pull/6509, which addresses the lock-up issue for the tactile-controller-based UX. This fixes the issue for the PAT device (sip/puff, etc) UX.
Updating logic in `ScanPanelVirtualKeyboard` so that rows that have no enabled keys can't be activated (before, you could drill in and then get stuck when the individual keys are displayed).
https://github.com/user-attachments/assets/04644bf9-9c05-44c4-8463-dada80c2ec80
https://github.com/user-attachments/assets/3bc2e862-192c-4112-a857-156b20eacdf1
- Manual + new/updated unit tests
=> [VxMark] Prevent PAT keyboard lockup after hitting write-in char limit

libs/ballot-interpreter/Cargo.toml, libs/ballot-interpreter/benches/main.rs, libs/ballot-interpreter/bin/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/ballot_card.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/js/mod.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks/mod.rs, libs/ballot-interpreter/src/hmpb-ts/addon.ts, libs/ballot-interpreter/src/hmpb-ts/interpret.test.ts, libs/ballot-interpreter/src/hmpb-ts/interpret.ts, libs/ballot-interpreter/src/interpret.ts, libs/ballot-interpreter/src/types.ts
As part of deciding whether to stop doing timing mark inference it is useful to be able to see how the interpreter performs without it on specific ballots or on a corpus of ballots. Does not hook it up to system settings or anything like that in production.
n/a
Added an automated test to verify that the interpreter fails to find timing marks in a ballot without some bottom timing marks.
=> feat(scan): add option to disable timing mark inference

apps/admin/backend/src/app.adjudication.test.ts, apps/admin/backend/src/store.ts
Closes: 
https://github.com/votingworks/vxsuite/issues/6532
This PR updates the adjudication queue ordering:
- Previously the queue was ordered by insertion order.
- Now the queue is ordered according to the flow we think will be the simplest for adjudicators - write-ins/no marginal mark -> write-ins and marginal marks -> marginal marks only.
Backend test
=> VxAdmin: Update adjudication queue ordering

apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.tsx
Closes:
https://github.com/votingworks/vxsuite/issues/6504
Previously the primary button was enabled when revisiting a previously adjudicated cvr. But, we thought this might be confusing, and that a user should use "Skip" if they have made no new adjudications.
https://github.com/user-attachments/assets/8c375a63-5b8b-45c3-9df8-226a7690608b
The video shows that when revisiting a previously adjudicated ballot, `Save & Next` is disabled since there have been no changes.
Frontend tests
=> VxAdmin: Disable primary adjudication button if there have been no changes

libs/pdi-scanner/src/rust/client.rs, libs/pdi-scanner/src/rust/main.rs
Previously, we were only loading them in the case where we needed to retry the initial commands after connect. This was happening so consistently that I didn't notice the bug until just recently.
To mitigate this, I instead moved the request for the image calibration tables to within the initial commands after connect.
N/A
Manual test
=> pdi-scanner: Ensure we always load image calibration tables

apps/pollbook/backend/src/avahi.test.ts, apps/pollbook/backend/vitest.config.ts
The avahi code was for some reason being "covered" when running test locally (where I have avahi installed) but not when run in CI. In the tests for networking I had mocked out everything at this layer and was never intentionally testing the file so I added a basic test file covering the avahi.ts code so that that is reliably covered in both CI and locally. 
Depends on: https://github.com/votingworks/vxsuite/pull/6549
N/A
Ran CI Job 50x and saw no failures.
=> Stablize coverage thresholds in Pollbook Backend

apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, apps/admin/frontend/src/api.ts, apps/admin/frontend/src/app.test.tsx, apps/admin/frontend/src/components/mark_official_button.tsx, apps/admin/frontend/src/screens/election_screen.test.tsx, apps/admin/frontend/src/screens/election_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/6124
Adds a button to the Election screen for system admins to revert election results to unofficial after they have been marked official (after confirming in a modal).
Note that we only show the callout when election results are marked official, so after reverting there's no confirmation message on screen other than the fact that the callout is gone. While I wouldn't normally want to have a flow with no visual confirmation message, I think it's ok since (1) this isn't a main flow (2) there's still confirmation via the disappearance of the callout, and (3) you can easily check that it worked by logging in as an election manager.
https://github.com/user-attachments/assets/e162b5d2-2a32-4afd-bb80-cca15305dcd9
- Manual test
- Added …
=> VxAdmin: Button for system admin to revert election results to unofficial

libs/backend/src/system_call/api.test.ts, libs/backend/src/system_call/get_audio_info.test.ts, libs/backend/src/system_call/get_audio_info.ts, libs/ui/src/hooks/use_headphones_plugged_in.test.ts, libs/ui/src/hooks/use_headphones_plugged_in.ts
https://github.com/votingworks/vxsuite/issues/6484
- `getAudioInfo` initially parsed output from `pactl list sinks` to figure out if headphones are connected (for VxMark) to the builtin audio card.
- To support screen reader audio in VxScan, we're connecting a USB controller with an audio card, which will register as a USB audio device and potentially with a `"Speaker"` type - still need to verify the details once I have a device on hand, but stubbing this out for now to get the framework in place.
- Will also be adding functionality later on for playing audio to a specific audio sink (output device), which will require specifying the sink name.
- Given all that, this expands `getAudioInfo` to include details for the builtin audio card as well as a detected USB audio card, if any. Now …
=> [VxScan] Add USB audio card detection to libs/backend:getAudioInfo

libs/auth/src/cryptography.test.ts, libs/auth/src/env.d.ts, libs/auth/src/keys.ts
This PR exposes a `USE_STRONGSWAN_TPM_KEY` environment variable to support creating a CSR with the VxPollBook strongSwan TPM key. We'll use this in vxsuite-complete-system to create a second TPM key/cert pair for securing local networking on VxPollBook. A second TPM key is necessary because this key requires different attributes than the TPM key we use for auth operations.
=> Support creating CSR with VxPollBook strongSwan TPM key

apps/admin/frontend/src/components/write_in_adjudication_button.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx, libs/ui/src/search_select.tsx
https://github.com/votingworks/vxsuite/issues/6242
This PR adds an icon to the "Add candidate" and "Invalid mark" dropdown options, to help distinguish them from the existing candidate options.
https://github.com/user-attachments/assets/e7582fcc-7e1e-429d-87fc-d6fa0f0077bf
Manual testing and updated existing tests
=> VxAdmin: Add icons to non-candidate adjudication dropdown options

apps/scan/backend/src/app.ts, apps/scan/backend/src/electrical_testing/tasks/print_and_scan_task.test.ts, apps/scan/backend/src/electrical_testing/tasks/print_and_scan_task.ts, apps/scan/backend/src/scanners/custom/state_machine.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_jam.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_shoeshine_mode.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts, apps/scan/backend/src/types.ts, apps/scan/backend/test/helpers/pdi_helpers.ts, apps/scan/backend/test/helpers/shared_helpers.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/screens/voter_screen.tsx, apps/scan/frontend/vitest.config.ts
Closes: #6122 
Previously, we enforced a 2.5s delay after a ballot was accepted before another ballot could be scanned. This caused issues for both election officials during L&A (who need to scan many ballots in succession) and voters with multi-sheet ballots (who didn't want to wait between sheets).
We had previously thought this delay was necessary to prevent the scanner from overheating, but it turns out this is not an issue.
This PR removes the delay. In order to make sure the user gets feedback that their ballot was accepted, we now wait for the frontend to tell the backend when it can allow another ballot to be inserted after accept. The frontend waits to send this signal to the backend until it's made sure to show the accepted screen and play the associated chime. The frontend then …
=> VxScan: Allow scanning another ballot immediately after accepting a ballot

apps/scan/backend/src/server.test.ts, apps/scan/backend/src/server.ts, libs/backend/src/system_call/index.ts, libs/backend/src/system_call/set_default_audio.test.ts, libs/backend/src/system_call/set_default_audio.ts
https://github.com/votingworks/vxsuite/issues/6484
During testing with various USB audio cards, some devices were *not* automatically selected as the default output by the system (seems to only happen for devices that identify as having a headphone output). The tactile controller we've settled on for VxScan is one of those, so this change ensures that we set the USB device as the default output, if detected at startup. This only affects the screen reader audio played in the client/kiosk-browser.
- Triggering a server shutdown if the USB device was detected, but we can't set it as the default.
- Logging if we can't detect the USB device at all - we may eventually want to throw  there as well, but we'll need to support older machines without the USB audio addition for now.
- Unit + manual …
=> [VxScan] Set USB audio as default output at startup

apps/scan/backend/src/audio/player.test.ts, apps/scan/backend/src/audio/player.ts, apps/scan/backend/src/server.test.ts, apps/scan/backend/src/server.ts, libs/backend/src/system_call/get_audio_info.test.ts, libs/backend/src/system_call/get_audio_info.ts, libs/backend/src/system_call/set_default_audio.test.ts, libs/backend/src/system_call/set_default_audio.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_enums.ts, libs/logging/types-rust/src/log_event_enums.rs
https://github.com/votingworks/vxsuite/issues/6484
Follow-up from recent work adding screen reader audio support to VxScan - replacing a few placeholder log event IDs related to system audio.
- Updated relevant tests
=> [VxScan] Add/update IDs for audio-related log events

apps/pollbook/barcode-scanner-daemon/Cargo.toml
We shouldn't have both `license` and `license-file`, and the latter is for when using a non-standard license.
=> chore(pollbook): remove extraneous `Cargo.toml` field

apps/admin/frontend/src/components/adjudication_double_vote_alert_modal.tsx, apps/admin/frontend/src/components/contest_option_button.tsx, apps/admin/frontend/src/components/discard_changes_modal.tsx, apps/admin/frontend/src/components/marginal_mark_flag.tsx, apps/admin/frontend/src/components/write_in_adjudication_button.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.tsx, libs/ui/src/checkbox_button.tsx
https://github.com/votingworks/vxsuite/issues/6554
https://github.com/votingworks/vxsuite/issues/6323
This PR:
1. Improves keyboard navigation. New behavior: Tab moves user into and out of option list, rather than scrolling within the list. Up and Down arrow keys move user within the list, following `aria-listbox` guidelines. Enter/space toggle list checkbox items. Left/Right arrow keys move user between ballots (Back/Skip). Tab indexes are updated so user can jump straight to the first item requiring adjudication in the list. `TabIndex` is set to `-1` for all inner checkboxes, as we navigate via the containers. - EDIT: This is no longer included in this PR. Some miscellaneous keyboard improvements are still included like autofocusing on modal primary buttons.
2. Adds support for …
=> VxAdmin: Improve adjudication interface keyboard navigation + support marginally marked write-ins

apps/scan/backend/src/server.ts
Related toL https://github.com/votingworks/vxsuite/issues/6484
Issue found during QA: https://votingworks.slack.com/archives/CJU9MSC6S/p1749840805240489
With the newly added audio device detection at server startup, VxScan was crashing because it seems the PulseAudio service didn't get fully spun up before we run out of retry attempts.
Verified on a QA image that bumping up from 4 to 5 attempts works consistently, so just bumping up the initial wait time to 2 seconds instead, just to be extra safe.
- Tested on prod hardware with QA image.
=> [VxScan] Increase # of retries when detecting audio devices at startup

apps/pollbook/barcode-scanner-daemon/src/unitech_ts100_daemon.rs
* don't error when scanner is disconnected
* infinitely retry scanner connection on startup and after scanner disconnection
`ctrl+c` exit before connecting to scanner
https://github.com/user-attachments/assets/96dc1a4b-dc5d-422f-a336-5d1cda948dcb
`ctrl+c` exit after connecting to scanner
https://github.com/user-attachments/assets/27c23628-73a4-4528-9b9f-6c6900194cfd
Scanner disconnect and reconnect
https://github.com/user-attachments/assets/e4981a34-84dc-4d7f-a004-dfdd728c5d5e
=> support scanner disconnect/reconnect

apps/pollbook/backend/src/app_multi_node.test.ts
This test was flaky in checking the configuration over the network automatically happened. This does make sense to be one of the slower steps in the test so trying to bump the timeout for that waitFor specifically to hopefully resolve. The test actually failed due to a test coverage issue but I think it was just because this test failing lowered the coverage under the barrier. 
Flake: https://app.circleci.com/pipelines/github/votingworks/vxsuite/20605/workflows/74df3ded-52c9-4ac9-ac2d-029908306bb4/jobs/887198
=> Extend timeout for network config test

apps/mark-scan/frontend/src/pages/admin_screen.tsx, apps/mark-scan/frontend/src/pages/insert_card_screen.tsx, apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/src/pages/admin_screen.tsx, apps/mark/frontend/src/pages/insert_card_screen.tsx, apps/mark/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, libs/ui/src/test_mode.test.tsx, libs/ui/src/test_mode.tsx
Closes #6599 
Builds on #6636. The main difference here is that the banner was only being show in 3 places:
- Insert card screen - updated to callout
- Poll worker screen - updated to callout
- Election manager screen - removed, since the control to switch between official and test mode is on this screen, so it's redundant (also, it didn't easily fit alongside the title)
VxMarkScan
VxMark
Manual test
=> VxMark/VxMarkScan: Replace test mode banner with callout 

apps/pollbook/backend/schema.sql, apps/pollbook/backend/scripts/simulate_check_ins.ts, apps/pollbook/backend/src/app.test.ts, apps/pollbook/backend/src/local_store.test.ts, apps/pollbook/backend/src/local_store.ts, apps/pollbook/backend/src/store.ts, apps/pollbook/backend/src/store_multi_node.test.ts, apps/pollbook/backend/src/types.ts, apps/pollbook/backend/src/voter_helpers.ts, apps/pollbook/frontend/src/voter_search_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx, libs/db/src/client.ts
* Adds `*_middle_name` and `*_suffix` fields to the `voters` table.
* Updates `findVoterWithName` and `searchVoters` to pass those fields. Behavior should be unchanged for both.
* `findVoterWithName` still applies events to the `voter` objects but does not use the events for name matching
* Currently the search frontend does not pass middle name or suffix
Manual test of existing behavior:
https://github.com/user-attachments/assets/88b7e6ea-9c34-48b3-8968-4d8c676efef1
- updated tests
- added test that `findVoterWithName` does not find a match if middle name or suffix doesn't match
=> [pollbook] Include middle name and suffix on `voters` table

apps/scan/backend/src/electrical_testing/app.ts, apps/scan/backend/src/electrical_testing/server.ts, apps/scan/backend/src/index.ts, apps/scan/frontend/src/electrical_testing/api.ts, apps/scan/frontend/src/electrical_testing/app_root.tsx
Closes https://github.com/votingworks/vxsuite/issues/6484
- Mirroring the prod app setup to detect and configure both the builtin and USB audio devices.
- Not hard-failing when audio configuration fails like we do in prod, since it's helpful to just log and degrade functionality in this case.
- Adding controls for playing audio separately through the speaker and/or the headphones (via USB audio).
- Manual
=> [scan] Support both speaker and headphone audio in the HWTA

apps/admin/frontend/src/components/write_in_adjudication_button.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.tsx
[Slack discussion](https://votingworks.slack.com/archives/C08A8D6V8F9/p1750118348609899)
1. Simplifies copy - combines `marginally marked write-ins` and `unmarked write-ins` into `ambiguous write-ins`. Also removes the marginal mark flag from write-ins, as we now show the typical write-in adjudication button, treating marginally marked write-ins the same as unmarked write-ins. We also dropped some words where it was repetitive/wordy i.e. `Write-In adjudicated as Invalid Write-In` -> `Write-In adjudicated as Invalid`.
2.  Replaces the disabled `Skip` button with `Exit` when viewing the last ballot in a queue. We already disable the `Finish` button until there have been changes/all adjudications made, so it seemed unhelpful to have another disabled button right next to it. …
=> apps/admin: Update adjudication copy + replace disabled skip button when viewing last ballot in queue

apps/central-scan/backend/package.json
All the other packages use this command.
=> chore(central-scan): unify `test:coverage` command

libs/ballot-encoder/README.md
This should have been removed in #6374.
=> ballot-encoder: Remove outdated sentence from docs

apps/admin/backend/src/app.ts, apps/admin/backend/src/cast_vote_records.ts, apps/admin/backend/src/tabulation/full_results.test.ts, apps/admin/backend/src/util/cast_vote_records.test.ts, apps/admin/backend/src/util/cast_vote_records.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_enums.ts, libs/logging/types-rust/src/log_event_enums.rs
https://github.com/votingworks/vxsuite/issues/6618
We want to better understand what thresholds would work well for marginal mark adjudication, so we are introducing a log that includes: 1) total marks (over 0.00 score) and 2) a distribution of low scores (0.2 and below) in 0.01 increments
Example of a Scan import followed by a CentralScan:
Automated tests and reviewed log
=> apps/admin, libs/logging: Add log for mark scores distribution on cvr import

apps/pollbook/backend/vitest.config.ts
I've been seeing some flakiness on main with the following error:
```
ERROR: Coverage for branches (80%) does not meet global threshold (80.18%)
```
I suspect that there's a test that only sometimes exercises a branch, so I'm adjusting the threshold accordingly.
=> Tweak VxPollBook backend code coverage threshold

apps/pollbook/backend/src/app.test.ts, apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/app_config.test.ts, apps/pollbook/backend/src/app_multi_node.test.ts, apps/pollbook/backend/src/app_networking.test.ts, apps/pollbook/backend/src/avahi.test.ts, apps/pollbook/backend/src/avahi.ts, apps/pollbook/backend/src/local_store.test.ts, apps/pollbook/backend/src/local_store.ts, apps/pollbook/backend/src/networking.ts, apps/pollbook/backend/src/peer_app.test.ts, apps/pollbook/backend/src/peer_app.ts, apps/pollbook/backend/src/peer_store.ts, apps/pollbook/backend/src/pollbook_package.ts, apps/pollbook/backend/src/store.test.ts, apps/pollbook/backend/src/store.ts, apps/pollbook/backend/src/store_multi_node.test.ts, apps/pollbook/backend/src/types.ts, apps/pollbook/backend/test/app.ts, apps/pollbook/backend/test/test_helpers.ts, apps/pollbook/backend/vitest.config.ts, apps/pollbook/frontend/src/election_manager_screen.test.tsx, apps/pollbook/frontend/src/election_manager_screen.tsx, apps/pollbook/frontend/src/nav_screen.test.tsx, apps/pollbook/frontend/src/nav_screen.tsx, apps/pollbook/frontend/src/system_administrator_screen.test.tsx, apps/pollbook/frontend/src/types.ts, apps/pollbook/frontend/src/unconfigured_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx
Updates pollbook connection logic to only share events when the code version and precinct match, along with the previous blockers. Also in rethinking the potential race conditions and edge cases here added two more stricter checks (see commits 2 and 3 respectively):
- Checks in the same transaction when setting precinct that events do not exist and return an error to the frontend if they do. The frontend is already checking if events exist and disabling the button but its possible one could sneak in from another machine and this will prevent the write from saving if it happens. The UI handles the error by just disabling the button not showing a message, since this is never really expected to happen in the real world I think thats ok. 
- Returns the current pollbook configuration …
=> Do not sync events across pollbooks when code version and/or precinct do not match

apps/pollbook/backend/src/app_multi_node.test.ts, apps/pollbook/backend/src/networking.ts, apps/pollbook/backend/src/peer_store.ts, apps/pollbook/backend/src/types.ts
Follow-up and depends on: https://github.com/votingworks/vxsuite/pull/6643
We want to block configuration over the network when the code version is incompatible, and we will (in the next task) have a somewhat different UI treatment for that situation compared to the rest of the possible of reasons to end up in "MismatchedConfiguration." So this updates the implementation to create a seperate enum value IncompatibleSoftwareVersion and updates the networked configuration code in the backend to make sure we are only configuring from machines in "MismatchedConfiguration" 
The frontend is already only displayed pollbooks with the state MismatchedConfiguration in the UI to configure from so that will automatically now not show ones with wrong code versions. 
N/A
Rant Tests
=> Do not allow configuration over the network between machines with incompatible code versions

apps/pollbook/backend/src/barcode_scanner/unix_socket.ts
Silences barcode scanner connection logs when `ENOENT` in addition to existing `ECONNREFUSED`.
N/A logging change
=> ignore ENOENT when deciding on daemon connection logging

apps/central-scan/frontend/src/api.ts
In transitioning the last VxCentralScan non-Grout endpoints to Grout + react-query (https://github.com/votingworks/vxsuite/pull/6660), we've introduced an edge-case bug. Funnily enough, we recognized the possibility of this bug existing the first time we tried completing this transition (https://github.com/votingworks/vxsuite/pull/5475#discussion_r1790497508).
After removing a ballot that requires adjudication, the next ballot that requires adjudication surfaces a blank white screen:
https://github.com/user-attachments/assets/c4f1bfd5-74cf-4b7f-9a8f-622f28dd1580
The underlying code flow looks something like this:
* The `getNextReviewSheet` query returns the ballot to be adjudicated.
* After the ballot is confirmed removed in the UI, the query is rerun and expectedly returns `null`.
* On …
=> Address VxCentralScan blank screen issue

apps/admin/backend/src/app.test.ts, apps/admin/backend/src/app.ts, libs/types/src/cdf/election-results-reporting/convert.test.ts, libs/types/src/cdf/election-results-reporting/fixtures.ts
A feature that we thought would only be for cert - CDF election results reporting (ERR) import - is finding a use case in NH cities, where we want to aggregate results across wards. Reminder that, in NH cities, every ward (precinct) will have its own VxAdmin (for onsite write-in adjudication), and an additional VxAdmin will be provided for consolidation across the wards. We're ironing out the exact process in this [VotingWorks City Results Aggregation Instructions](https://docs.google.com/document/d/1JZE3omk5jCk7IydbVyWC4I1Gy7G0Ch_EFP8NtoSMeu8/edit?usp=sharing) doc.
In final QA, I found an issue with the code and the plan as it pertains to primary elections, of which we have one this fall. ERR exports are imported through the manual tally entry UI, which first requires selection of a …
=> Filter down to contests for specified ballot style on ERR import

apps/pollbook/frontend/src/voter_search_screen.test.tsx, apps/pollbook/frontend/src/voter_search_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx
https://github.com/votingworks/vxsuite/issues/6630
Shows an error message when a barcode is scanned but it's not parsable as a driver's license
Pollworker screen:
Election manager screen:
Video:
https://votingworks.slack.com/archives/C07CR6T1TLK/p1751066312970399
- manually tested
- added unit tests for component
=> [pollbook] display error message when unknown ID type is scanned

apps/pollbook/backend/src/app.test.ts, apps/pollbook/backend/src/local_store.ts, apps/pollbook/backend/src/store.test.ts, apps/pollbook/backend/src/store.ts, apps/pollbook/backend/vitest.config.ts, apps/pollbook/frontend/src/app_poll_worker_screen.test.tsx, apps/pollbook/frontend/src/election_manager_screen.test.tsx, apps/pollbook/frontend/src/poll_worker_screen.tsx, apps/pollbook/frontend/src/shared_components.tsx, apps/pollbook/frontend/src/types.ts, apps/pollbook/frontend/src/voter_confirm_screen.test.tsx, apps/pollbook/frontend/src/voter_confirm_screen.tsx, apps/pollbook/frontend/src/voter_details_screen.test.tsx, apps/pollbook/frontend/src/voter_details_screen.tsx, apps/pollbook/frontend/src/voter_search_screen.test.tsx, apps/pollbook/frontend/src/voter_search_screen.tsx, apps/pollbook/frontend/src/voters_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx
https://github.com/votingworks/vxsuite/issues/6156
Implements the restrictions for checking in, or making other voter changes, when a voter is not in the correct precinct. Address changes are always permitted as you can change a voter address into the current precinct. Notably as implemented in a previous PR you can NOT change a voter address outside of the precinct, this combined with the fact that you can only sync with machines configured for the same precinct means that we do not have to worry about the voter being configured for the correct precinct on the backend as there is no way for an event to sneak in and change that if the frontend is allowing a check in (or name change/ etc.). I have previously added backend errors for situations like checking in a voter that is flagged as …
=> VxPollbook Multi Precinct Check In Restrictions

apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/barcode_scanner/client.ts, apps/pollbook/backend/src/types.ts, apps/pollbook/backend/vitest.config.ts, apps/pollbook/barcode-scanner-daemon/src/unitech_ts100_daemon.rs, apps/pollbook/frontend/src/nav_screen.test.tsx, apps/pollbook/frontend/src/nav_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx, libs/ui/src/icons.tsx
https://github.com/votingworks/vxsuite/issues/6632
Adds a connection status icon to the nav bar. The daemon must be running and the device must be connected for the indicator to show `connected` (which we show just by hiding the warning indicator). Otherwise it shows a warning indicator.
https://github.com/user-attachments/assets/ecf43865-cbbe-437d-8494-e0db79edb243
=> [pollbook] Barcode scanner connection status

libs/hmpb/src/all_bubble_ballot/template.tsx, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/v3_nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx, libs/hmpb/src/base_styles.tsx, libs/hmpb/src/playwright_renderer.tsx, libs/hmpb/src/preview/browser_preview_renderer.tsx, libs/hmpb/src/render_ballot.tsx, libs/hmpb/src/renderer.tsx
Fixes https://github.com/votingworks/vxsuite/issues/6076
Having the renderer be responsible for including `BaseStyles` was always a bit of a violation of the abstraction that templates specify content and styling while the renderer is just responsible for rendering it. It was a shortcut I put in place since all templates shared the same base styles.
This started to break down when we needed to parameterize the styles based on ballot props (namely, adding `compact`, which changes font size and line height). In the future, it looks like we'll also need to change the fonts for upcoming NH state ballots.
To get ahead of this, I added a new field to the ballot template to specify the base styles to use. The renderer will still only add this to the document head once at the beginning, but it …
=> hmpb: Refactor to move base style definition into ballot templates

libs/ballot-interpreter/bin/debug-timing-marks.rs, libs/ballot-interpreter/src/hmpb-rust/ballot_card.rs, libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks/mod.rs
This measurement should be generally quite close to the bottom border-only measurement because they're both measuring features of the timing mark grid at the scale (ahem) of the page, but in practice will likely be a bit higher due to it incorporating some of the skew that may be present toward the top of the scan. Taking the median distance from the left to right timing marks will mitigate that effect to some degree. On the TRR corpus the difference in the measures is very close, about 0.08% average / 0.03% median.
Note that actually using this measurement to reject ballots is still disabled by default, and we'll need to do some testing to determine whether the previously determined 98.5% threshold is still a good value before we use it in an election.
This keeps the ability to compute …
=> feat(scan): change scale measurement to use full width

libs/fixtures/src/tmpdir.test.ts, libs/fixtures/src/tmpdir.ts
`vxsuite` has lots of temporary files and directories created in tests, and is inconsistent about cleaning them up. When an effort is made to clean them up, there are often per-package ways of doing so that are effective to varying degrees. This is a step toward unifying tmpfile handling.
The idea is that all tests that need to create temporary files will use these functions to do so rather than using `tmp` (or `tmp-promise`). Why not use `tmp`? It refuses to delete temporary directories recursively on process exit when `setGracefulCleanup` is enabled, instead requiring that you call `dirSync` with `unsafeCleanup: true` and then manually invoke the `removeCallback` method on the returned `DirEntry`. This makes creating temporary files and directories in tests somewhat painful and …
=> feat(fixtures): add API to make temp files/dirs

apps/design/frontend/src/ballot_screen.tsx
A small bit of polish I came across while working on other tasks.
Before
After
=> VxDesign: Move action buttons to bottom of sidebar in ballot preview screen

apps/pollbook/frontend/src/voter_details_screen.test.tsx, apps/pollbook/frontend/src/voter_details_screen.tsx, apps/pollbook/frontend/src/voters_screen.tsx
https://github.com/votingworks/vxsuite/issues/6440
Cosmetic changes for election manager voter search UX.
cc @adghayes for product feedback
**Search**
**Voter checked in**
* Buttons look misaligned relative to each other even though they are correctly aligned to their columns
* We might consider a hamburger menu on these columns as functionality continues to grow and it becomes cumbersome to add more buttons
* "Close" button is actually in the opposite place compared to the pollworker screen, where it's on the bottom left
* In a footer with only 1 button I think it feels more natural to keep it on the right because I generally associate action with sides of the screen (left for previous, right for next, probably has to do with reading direction)
* That said, open to feedback if we want to …
=> voter details page style changes

apps/design/backend/migrations/1751482460757_add-ballot-compact.js
It turns out `pgm.db.query` doesn't register newly added columns from earlier in the migration, but `pgm.sql` does.
Ran migration locally with a db snapshot
=> VxDesign: Fix migration to add ballot_compact column

apps/admin/frontend/src/screens/tally/import_cvrfiles_modal.tsx, apps/admin/frontend/src/screens/tally/import_election_results_reporting_file_modal.tsx
For our manual imports on VxAdmin, other than the election package, we are not actually passing the right arguments to electron to filter out files of the wrong extension. The incorrect instances were corrected to match the correct instances. Tested manually.
=> VxAdmin: fix extension filtering

apps/mark-scan/frontend/src/pages/poll_worker_screen.tsx, libs/mark-flow-ui/src/components/poll_worker/index.ts, libs/mark-flow-ui/src/components/poll_worker/sections.tsx, libs/mark-flow-ui/src/components/poll_worker/update_polls_button.tsx
https://github.com/votingworks/vxsuite/issues/6706
Splitting out PollWorkerScreen sections that will be common between Mark and MarkScan:
- Header section, with optional test mode banner.
- Polls state management section, along with with the `UpdatePollsButton` component.
- System section containing the signed hash validation control.
Code unchanged, except for splitting the sections out into components and taking in state/mutation methods as props.
- Existing tests in MarkScan cover the code paths for these sections
=> [MarkScan] Extract reusable sections from PollWorkerScreen

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/test/helpers.ts, apps/design/backend/vitest.config.ts, libs/grout/src/server.ts
The `/files` endpoint is separate from the main Grout API, so it has bespoke auth guards. This PR cleans up the auth handling to make it better fit with the rest of the API.
N/A
Added test coverage, since this endpoint was uncovered
=> VxDesign: Cleanup auth for /files endpoint

apps/mark/frontend/src/apimachine_config.test.tsx, apps/mark/frontend/src/app.test.tsx, apps/mark/frontend/src/app.tsx, apps/mark/frontend/src/app_card_unhappy_paths.test.tsx, apps/mark/frontend/src/app_cardless_voting.test.tsx, apps/mark/frontend/src/app_contest_candidate_no_party.test.tsx, apps/mark/frontend/src/app_contest_ms_either_neither.test.tsx, apps/mark/frontend/src/app_contest_multi_seat.test.tsx, apps/mark/frontend/src/app_contest_single_seat.test.tsx, apps/mark/frontend/src/app_contest_yes_no.test.tsx, apps/mark/frontend/src/app_election_package_config.test.tsx, apps/mark/frontend/src/app_end_to_end.test.tsx, apps/mark/frontend/src/app_polls_flows.test.tsx, apps/mark/frontend/src/app_root.tsx, apps/mark/frontend/src/app_setup_errors.test.tsx, apps/mark/frontend/src/pages/poll_worker_screen.test.tsx, apps/mark/frontend/src/pages/poll_worker_screen.tsx, apps/mark/frontend/test/helpers/build_app.tsx, apps/mark/integration-testing/e2e/scroll_buttons.spec.ts
https://github.com/votingworks/vxsuite/issues/6706
Using `PollWorkerScreen` components extracted from MarkScan in Mark to bring the latter up to date with v4 UX/mechanics.
Also removing the old `Reset Accessible Controller` workaround, which [isn't needed anymore](https://votingworks.slack.com/archives/CEL6D3GAD/p1752172516769329).
Updated pieces include:
- New, human-friendly labels for and updated UX ballot style picker
- Signed hash validation control
- Layout/copy/iconography updates for start/resume voting session interstitials
First commit has PollWorkerScreen changes - may be more helpful to view the incoming code as a plain, non-diff file, since there's so much change.
https://github.com/user-attachments/assets/2f9e374c-a664-40de-9a9b-c4b012d50818
- Updated existing tests, copied …
=> [Mark] Use shared components in PollWorkerScreen for parity with MarkScan

libs/pdi-scanner/examples/get_test_string.rs
This broke when we introduced code that needed the tokio async runtime.
=> fix(scan): make `get_test_string` example work

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, libs/grout/package.json, libs/grout/src/grout.test.ts, libs/grout/src/server.ts, pnpm-lock.yaml
Instead of logging the API call when it's received (before the method handler is called), we log the API call after its handled and include the outcome (success or failure) as well as any error that occurred.
Example log line for `getUser` request when user is not logged in
```
[backend:run] 2025-07-14T22:23:22.791Z design-backend:app {
[backend:run]   source: 'vx-design-service',
[backend:run]   eventId: 'api-call',
[backend:run]   eventType: 'application-action',
[backend:run]   user: 'system',
[backend:run]   message: undefined,
[backend:run]   disposition: 'failure',
[backend:run]   methodName: 'getUser',
[backend:run]   input: undefined,
[backend:run]   userAuth0Id: undefined,
[backend:run]   userOrgId: undefined,
[backend:run]   error: 'auth:unauthorized'
[backend:run] }
```
- Added …
=> VxDesign: Log outcome of API calls

apps/scan/backend/test/helpers/electrical_test.ts, libs/ballot-interpreter/src/find_timing_mark_grid.test.ts, libs/ballot-interpreter/src/hmpb-rust/js/mod.rs, libs/ballot-interpreter/src/hmpb-rust/lib.rs, libs/ballot-interpreter/src/hmpb-rust/timing_marks/scoring.rs, libs/ballot-interpreter/src/hmpb-ts/addon.ts, libs/ballot-interpreter/src/hmpb-ts/types.ts, libs/hmpb/src/ballot_fixtures.ts, libs/hmpb/src/generate_fixtures.test.ts, libs/hmpb/src/generate_fixtures.ts
Adds `findTimingMarkGrid` to `@votingworks/ballot-interpreter` for use in the HWTA. We'll replace analysis of blank paper with some analysis of the detected timing mark grid.
n/a
New automated testing.
=> feat(ballot-interpreter): add API to find timing mark grid

libs/pdi-scanner/examples/scan_forever.rs
In some situations we would try to scan but not pull the paper through. In that case, we'd see that there is no paper covering the rear sensors and not bother to eject _or_ to restore the feeder mode. This meant that the scanner would no longer auto-scan fed paper. This change fixes it by always setting the feeder mode to `AutoScanSheets` before waiting for paper.
n/a
Tested manually by holding the paper under the front sensors but not touching the feeding mechanism until the scanner stopped trying, then feeding the paper in again.
=> fix(scan): make `scan_forever` example more resilient

apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx
They were accidentally pointed to the districts tab rather than the
precincts tab.
- Manual test
- Added test coverage
=> VxDesign: Fix incorrect breadcrumbs links for precinct forms

apps/design/backend/migrations/1752705340558_geography-unique-indexes.js, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/vitest.config.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/geography_screen.test.tsx, apps/design/frontend/src/geography_screen.tsx, apps/design/frontend/vitest.config.ts
Task: #6263 
Enforces the following uniqueness constraints using db indexes:
- Districts: unique name within an election
- Precincts: unique name within an election
- Precinct splits: unique name within a precinct
https://github.com/user-attachments/assets/c0cef7ec-c11b-4956-aada-83f49fbc069e
=> VxDesign: Require districts/precincts/splits to have unique names

apps/design/backend/migrations/1752784464060_party-unique-index.js, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx
Task: #6263 
Within an election, require that each party has a unique full name, short name, and abbreviation, since all three function as unique labels for a party.
https://github.com/user-attachments/assets/b506c18b-f141-44d7-815e-2b9377bda994
- Manual test
=> VxDesign: Require unique party names/abbreviations within elections

apps/pollbook/barcode-scanner-daemon/src/unitech_ts100_daemon.rs, apps/pollbook/frontend/src/voter_search_screen.tsx
https://github.com/votingworks/vxsuite/issues/6761
Due to a rebase or merge error changes from https://github.com/votingworks/vxsuite/pull/6690 were reverted in https://github.com/votingworks/vxsuite/commit/72fa8832b9c783332076053b7d6adc3dd21fc596#diff-db907df85a5204be810706c80bacf83c6528c649ff90d04e3697a47bc2d4358f.
This adds the changes from https://github.com/votingworks/vxsuite/pull/6690 back in. It also changes render priority so the "Could not read barcode" error modal shows even if search results exist on the page.
https://github.com/user-attachments/assets/701d454b-e37d-4d04-acdf-cf0cc2892261
=> restore error modal when an invalid barcode is scanned

libs/printing/src/printer/print.test.ts, libs/printing/src/printer/print.ts, libs/printing/src/printer/types.ts
https://github.com/votingworks/vxsuite/issues/6789
Ran into an issue printing on legal-sized paper while testing out pre-printed ballot marking on VxMark, since it was using the device default `letter` size. Adding an option for `legal` as well to the print API (mostly for dev/testing - we'll likely be doing the upcoming demo of the bubble-marking feature with letter-sized paper).
We'll eventually want to support the longer custom sizes as well, but that requires some coordination between configuring the printers with custom size options and using references to those in the shell command, so we'll tackle that later.
- Unit for shell command format + manual verification
=> [printing] Add support for printing to legal-sized paper via lpr

apps/pollbook/backend/src/event_helpers.ts, apps/pollbook/backend/src/store_multi_node.test.ts, apps/pollbook/frontend/src/voter_confirm_screen.test.tsx, apps/pollbook/frontend/src/voter_confirm_screen.tsx, apps/pollbook/frontend/src/voter_details_screen.test.tsx, apps/pollbook/frontend/src/voter_details_screen.tsx
Updates the following
- When a voter is in the wrong precinct we now disable the update address buttons 
- When a voter is flagged inactive fixes a bug that was preventing check ins on the backend. The feature was originally written so that check ins would be blocked, and specific efforts were went to to make sure that even in rare offline syncing scenarios an illegal check in could not sneak in. When Drew then updated the logic to ALLOW for check ins on inactive voters some of those backend checks were missed and we were silently ignoring these checks in, this fixes that. 
- When a voter is flagged as inactive enable all other actions, see discussion: https://votingworks.slack.com/archives/C07CR6T1TLK/p1753135409790919
- 
https://github.com/votingworks/vxsuite/issues/6818
The view when a …
=> Update disabled/enabled actions for wrong precinct and inactive voters

apps/pollbook/frontend/src/nav_screen.test.tsx, apps/pollbook/frontend/src/nav_screen.tsx
https://github.com/votingworks/vxsuite/issues/6736
When showing the connected pollbooks change the copy to "Synced" to designate when they are sharing events and "Connected" when the pollbook is unconfigured and sees another pollbook.
=> Update connection copy to "synced"

apps/pollbook/backend/scripts/simulate_check_ins.ts, apps/pollbook/backend/src/__snapshots__/voter_history.test.ts.snap, apps/pollbook/backend/src/app.test.ts, apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/app_multi_node.test.ts, apps/pollbook/backend/src/app_multi_precinct_election.test.ts, apps/pollbook/backend/src/local_store.ts, apps/pollbook/backend/src/receipts/check_in_receipt.tsx, apps/pollbook/backend/src/receipts/receipt_helpers.tsx, apps/pollbook/backend/src/types.ts, apps/pollbook/backend/src/voter_history.test.ts, apps/pollbook/backend/vitest.config.ts, apps/pollbook/frontend/src/app_poll_worker_screen.test.tsx, apps/pollbook/frontend/src/poll_worker_screen.tsx, apps/pollbook/frontend/src/select_party_screen.tsx, apps/pollbook/frontend/src/shared_components.tsx, apps/pollbook/frontend/src/strings.test.ts, apps/pollbook/frontend/src/strings.ts, apps/pollbook/frontend/src/voter_confirm_screen.test.tsx, apps/pollbook/frontend/src/voter_confirm_screen.tsx, apps/pollbook/frontend/src/voter_details_screen.test.tsx, apps/pollbook/frontend/src/voter_search_screen.tsx, apps/pollbook/frontend/test/mock_api_client.tsx, apps/pollbook/frontend/vitest.config.ts
Adds a `NOT_APPLICABLE` option for the `ballotParty` field on check-ins. `ballotParty` describes the chosen ballot in a primary check in:
* Registered Democrats or Republicans must choose the corresponding `DEM` or `REP` ballot
* Undeclared voters can choose either `DEM` or `REP` but must choose one
In generals there are no party ballots to choose from so this field doesn't really make sense. Previously we were just writing `voter.party` ie. `REP`, `DEM`, or `UND` but the value in this field had no meaning. In this PR we make it explicit that the value is unused for generals by writing `NOT_APPLICABLE` for all general election check ins.
Recapping previous discussion, we originally wanted to and still want to keep this field as required in the API and schema because the type safety is …
=> [pollbook] Add `NOT_APPLICABLE` option to check-in `ballotParty` property

apps/scan/backend/src/electrical_testing/tasks/print_and_scan_task.ts
#6799 broke scanning with the VxScan HWTA because it removed the line to enable scanning. This adds it back. Additional testing showed that the scanner would also stop accepting sheets if the initially-inserted one was removed. This fixes that as well.
n/a
Tested manually with both the initial scan as well as removing the sheet and re-inserting it.
=> fix(hwta): enable scanning on startup

apps/pollbook/backend/src/app.test.ts, apps/pollbook/backend/src/app_multi_precinct_election.test.ts
When testing it is not helpful to see the grout error messages logged to the console unconditionally. If the messages are different, we'll get an expectation failure in the test.
**Before:**
```
stderr | src/app_multi_precinct_election.test.ts > in a primary, a declared voter must check in with a party selection matching the declared party
Error: Expected check-in party DEM to match voter party REP
at assert (/home/brian/code/vxsuite/libs/basics/build/assert.js:14:15)
at checkInVoter (/home/brian/code/vxsuite/apps/pollbook/backend/src/app.ts:288:13)
at /home/brian/code/vxsuite/libs/grout/build/server.js:130:32
at Layer.handle [as handle_request] (/home/brian/code/vxsuite/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
at next …
```
=> test(pollbook): suppress expected errors

apps/pollbook/backend/test/app.ts
When the pollbooks announce to the network that they exist for discovery by other pollbooks it requires calling and leaving open this process with avahi. The backend index.ts file when running the app either in dev or in production will close this thread on exit but the tests are operating slightly downstream from that logic and need to remember to clean this up at the end of their runs.
=> clean up avahi services after tests

apps/pollbook/backend/src/avahi.test.ts, apps/pollbook/backend/src/avahi.ts, apps/pollbook/backend/test/app.ts
As discussed there was an issue with how this runningProcess variable was handled in conjunction with the withManyApps test helper. In real life there should only be one pollbook app running per machine and using a static variable here is fine but the withManyApps helper creates multiple instances of the app within a process. The test behavior seems unchanged by this change to ensure that the mutlitple apps have their own publish-service thread running but its possible this could help alleviate some of the flakiness issues we've been seeing.
=> Update running process varaible to be a map

apps/pollbook/frontend/src/api.ts, apps/pollbook/frontend/src/app_poll_worker_screen.test.tsx, apps/pollbook/frontend/test/mock_api_client.tsx
Resets the value for the stale time to the default of 0. See https://github.com/votingworks/vxsuite/pull/6848 for original context. @jonahkagan pointed out that the default is 0 and we should default to that unless there is a good reason for another value (as in the case with the rest of vxsuite). 
Tested by making sure changes between pollbooks propagated on the election manager voter details page.
=> Use default react stale time timeout 

apps/scan/frontend/src/electrical_testing/app.tsx, apps/scan/frontend/src/electrical_testing/app_root.tsx
_(This is part 3 of a series of PRs extracted from #6862 – [Go to Part 2](https://github.com/votingworks/vxsuite/pull/6868))_
This lets us get rid of the janky `scale` styles and small font sizes. Note that this isn't where we want to leave this screen, see https://github.com/votingworks/vxsuite/pull/6862 for the goal UI.
Tested locally.
=> feat(hwta-scan): switch to `desktop` size mode

apps/pollbook/backend/package.json, apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/peer_app.ts, apps/pollbook/backend/src/security_middleware.ts, pnpm-lock.yaml
In order to prepare for possible RABET-V certification implements some standard security headers. While it would be unlikely for these headers to come into play in our locked down secure private network theoretically if a malicious actor managed to get onto a machine on the network they could then attempt to create a MITM type of attack that these could help protect against. 
Requirement context: https://rabetv.docs.cisecurity.org/en/latest/appendices/security_requirements.html#requirement-use-secure-http-response-headers 
6.1.1 Requirement: Use secure HTTP response headers
Details: To protect against cross-site scripting (XSS) and man-in-the-middle (MITM) attacks, use the Content Security Policy (CSP) and Public-Key-Pins headers.
https://github.com/votingworks/vxsuite/issues/6471
N/A
Ran …
=> [VxPollbook] Add basic security headers

apps/scan/backend/src/electrical_testing/app.ts
_(This is part 6 of a series of PRs extracted from #6862 – [Go to Part 5](https://github.com/votingworks/vxsuite/pull/6875))_
The images may not be fully saved to the USB drive when we try to read them for the frontend, so just always pull from the local disk for the purposes of displaying the images.
n/a
Tested manually, saw that the images no longer occasionally failed to load.
=> fix(hwta-scan): prevent data race with saved images

apps/scan/backend/src/electrical_testing/app.ts, apps/scan/backend/src/electrical_testing/context.ts, apps/scan/backend/src/electrical_testing/tasks/print_and_scan_task.ts, apps/scan/backend/src/index.ts, apps/scan/backend/test/helpers/electrical_test.ts, apps/scan/frontend/src/electrical_testing/api.ts, apps/scan/frontend/src/electrical_testing/app_root.tsx
Adds a button to the printer controls that requests that a print start as soon as possible. It does this by clearing the "last printed at" timestamp, which will trigger a print during the printer/scanner's next tick on the event loop.
Tested manually with a mock printer.
=> feat(hwta-scan): allow printing on demand

apps/pollbook/backend/src/barcode_scanner/client.test.ts
`socket.io` was removed in #6680.
=> chore(pollbook): remove outdated mock

.circleci/config.yml, apps/pollbook/backend/.circleci/config.yml, libs/monorepo-utils/bin/generate-circleci-config, libs/monorepo-utils/src/circleci.test.ts, libs/monorepo-utils/src/circleci.ts, libs/monorepo-utils/src/index.ts, script/src/validate-monorepo/validation/circleci.ts
In order to avoid flaky pollbook tests bothering the rest of vxsuite but still run them for pollbook changes we will now only run the "test" step of apps-pollbook-backend when there are changes in the apps/pollbook/backend directory. You can see whether or not tests were run by looking at the apps-pollbook-backend CI step and looking for the "test" step. You can also look at the output of check-updated-files-for-test-filter  which is the CI step that runs first and decides how to run the pollbook step. 
Set up in the circle CI config generation script so that we can move other apps to this model in the future if we wish. A new second circle ci config will now live in apps/pollbook/backend for the pollbook ci config. 
https://github.com/votingworks/vxsuite/issues/6853
See this branch: …
=> Run apps-pollbook-backend tests only when code changes occur

apps/admin/backend/src/app.ts, libs/fs/src/list_directory.test.ts, libs/fs/src/list_directory.ts, libs/usb-drive/src/list_directory_on_usb_drive.ts
Closes #6841. Updates the `listDirectory` method underlying VxAdmin's search for election packages on a USB drive to ignore not only hidden files but also hidden directories and their contents.
=> ignore hidden directories in VxAdmin election packages search

apps/pollbook/barcode-scanner-daemon/src/parse_aamva.rs, apps/pollbook/barcode-scanner-daemon/src/unitech_ts100_daemon.rs
* Removes a spammy log that happens when we see an empty line in the scan data. The empty line is expected at the end of every valid driver's license scan
* Removes a line that logs the first few characters of scanned data. Since we can't anticipate the format of non-AAMVA barcodes we shouldn't log them in case the first few characters are PII.
Logging change only
Manually verified
=> remove spammy log and possible PII log

apps/pollbook/frontend/src/app_poll_worker_screen.test.tsx, apps/pollbook/frontend/src/poll_worker_screen.tsx, apps/pollbook/frontend/src/voter_confirm_screen.tsx, apps/pollbook/frontend/src/voter_search_screen.test.tsx, apps/pollbook/frontend/src/voter_search_screen.tsx
https://github.com/votingworks/vxsuite/issues/6866
Automatically applies the issuing state to the form on the "Confirm Voter Identity" page when scanning an out-of-state driver's license.
In all these videos a Massachusetts ID is being scanned.
In this video there is exactly 1 match so we jump right to the check-in page and prefill `MA - Massachusetts`
https://github.com/user-attachments/assets/62e9a3ce-cbb4-4683-a250-4c877978ebd8
In this video there is >1 match so we make the pollworker choose and don't prefill the state. I think it's likely we should prefill the US state. While we're not jumping right to the check-in page, it seems clear that the intended voter was found, so their ID scan should be considered valid. If so, we can add that behavior in a follow-up PR. …
=> Apply OOS DL US state to check-in page when there's exactly 1 hit for ID scan

apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/local_store.test.ts, apps/pollbook/backend/src/local_store.ts, apps/pollbook/backend/src/types.ts, apps/pollbook/backend/test/test_helpers.ts, apps/pollbook/backend/vitest.config.ts, apps/pollbook/frontend/src/api.ts, apps/pollbook/frontend/src/statistics_screen.test.tsx, apps/pollbook/frontend/src/statistics_screen.tsx, apps/pollbook/frontend/src/voter_confirm_screen.test.tsx, apps/pollbook/frontend/src/voter_registration_screen.test.tsx, apps/pollbook/frontend/vitest.config.ts
Makes the following changes to the stats screen: 
- Only shows stats for the configured precinct, if set. 
- Makes the y-axis not include fractions
- Removes participation percent
- For a general election adds a party filter to the voter card, filters as expected
- For a primary election adds a party filter to the stats page as a whole, filters whole page
- Primary election, undeclared filter hides throughput and changes "Check Ins" to "Declared Party" 
I went back and forth in working on this change on how much to seperate or combine the code for the primary vs general cases, ultimately landing on seperating it out more. Initially I had both the backend and frontend more combined but that involved both the backend and frontend checking for primary vs. general and doing different logic …
=> VxPollBook: Update Statistics Screen for primaries and other tweaks

apps/pollbook/backend/scripts/simulate_check_ins.ts, apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/app_config.test.ts, apps/pollbook/backend/src/app_multi_precinct_election.test.ts, apps/pollbook/backend/src/backup_worker.ts, apps/pollbook/backend/src/local_store.test.ts, apps/pollbook/backend/src/local_store.ts, apps/pollbook/backend/src/store.ts, apps/pollbook/backend/src/store_multi_node.test.ts, apps/pollbook/backend/src/voter_history.test.ts, apps/pollbook/backend/vitest.config.ts
Makes some adjustments to the simulate script largely to unbreak it:
- Fixes a bug mixing up which of primary/general elections to send the ballot party for 
- Updates to only check in voters in the same precinct
- Working on that made me realize we should check and throw an error if we try to do something like check in a voter when a precinct is not yet configured
- Consolidated some of the "matchConfiguredPrecinctId" query param passing now that we only need to ever get all voters in a specific situation for the statistics screen, migrated all other functionality to call getVotersInPrecinct/Sorted
- No longer tries to check in a voter if they are already checked in
- Ran script for electionSimpleSinglePrecinct and electionMultiPartyPrimary to confirm working results. 
if my change is …
=> VxPollBook: Simulate Script Tweaks

apps/pollbook/backend/package.json, apps/pollbook/backend/src/__snapshots__/voter_history.test.ts.snap, apps/pollbook/backend/src/voter_checklist.tsx, apps/pollbook/backend/src/voter_history.test.ts, apps/pollbook/backend/src/voter_history.ts, pnpm-lock.yaml
https://github.com/votingworks/vxsuite/issues/6907
* Prevents `NOT_APPLICABLE` ballot party from showing up in the paper backups during generals. This value is assigned to `checkIn.ballotParty` as a dummy value but shouldn't be user-facing.
https://github.com/votingworks/vxsuite/issues/6666
* Adds timestamps to the voter history export
Updated snapshot test
if my change is specific to one of those products.
where appropriate for any new user actions.
automate an announcement in #machine-product-updates.
=> VxPollBook: very small export adjustments

apps/pollbook/frontend/package.json, apps/pollbook/frontend/prodserver/index.js, apps/pollbook/frontend/src/app.tsx, libs/logging/src/base_logger.ts, libs/logging/src/types.ts, pnpm-lock.yaml
Closes https://github.com/votingworks/vxsuite/issues/6968 
Fixes the frontend logging for VxPollBook, this could all be clearer but you need to give window.kiosk to the logger when creating it and it needs to be listed as a CLIENT_SIDE_LOG_SOURCE in the logging framework for the logger command to pipe to window.kiosk.log which will send it to the logging pipeline in the image. 
N/A
Hacked this change onto an imaged machine, saw logs appear as expected.
=> VxPollBook: Fix frontend logging

apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/app_multi_node.test.ts, apps/pollbook/backend/src/networking.ts, apps/pollbook/backend/src/peer_app.ts, apps/pollbook/backend/src/peer_store.ts
Closes https://github.com/votingworks/vxsuite/issues/6966
Makes two changes to network management:
- Checks that machines are in a currently communicating state before transitioning to ShutDown, this will prevent LostConnection -> ShutDown transitions specifically which we should not perform as we can not know if a machine shut down when we are not connected to it. 
- Removes the current knowledge about the list of machines when reseting the network. We already do this on reboot and after discussion decided it makes the most sense that when you click reset network something in lost connection would be removed. 
Copied build dir to a imaged machine performed the following tests:
- Connected two machines, shut one down, verified transition -> powered off. Reset network. Saw machine no …
=> VxPollBook: Networking Management Tweaks

apps/pollbook/backend/src/app_config.test.ts, apps/pollbook/backend/src/pollbook_package.ts
When an error would throw in this function we might be in a state where the election was saved in the database but the pollbook package file was not saved as an asset successfully, that then causes on the next loop of the interval that we see we have an election and we kill the configuration polling declaring success. However the usb configuration status is still "loading"
- When there is an error thrown we should roll back if there is an election set to prevent this situation
- If for some reason we to have getElection return a result in the pollbook package polling interval we should clear the configuration status so that we don't end up in a wedged state after clearing the polling interval. 
N/A
Tested ripping out a usb mid-configuration and saw the state properly reset.
=> VxPollBook: Handle errors in usb configuration to prevent wedged state properly

apps/scan/frontend/src/components/printer_management/load_paper_modal.tsx
Closes https://github.com/votingworks/vxsuite/issues/6955
To future proof against lever color changes (in early prototypes we've used both green and white), we've opted to fully remove the lever color from the UI copy. This will make it such that, if we ever have to change the lever color after cert, we won't have to go through a Trusted Build and prepare a wholely new software image.
| - | - |
| <img width="400" alt="before" src="https://github.com/user-attachments/assets/258afbc0-73a8-404b-9fd8-97d6513998bf" /> | <img width="400" alt="after" src="https://github.com/user-attachments/assets/b8c33fa3-d0df-4541-8639-01f6b579e9a4" /> |
=> VxScan: Remove reference to color of paper roll holder lever

apps/design/backend/src/app.test.ts, apps/design/backend/src/store.ts, apps/design/frontend/src/contests_screen.test.tsx, apps/design/frontend/src/contests_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/5676
New functionality:
1. All new candidate contests are inserted ahead of ballot measures by `ballotOrder` (backend)
2. All new contest orderings have candidate contests ahead of ballot measures (frontend)
3. Candidate contests and ballot measures are shown in separate tables (frontend)
https://github.com/user-attachments/assets/1aa81e3b-8aa9-4a71-867f-9245f3a3db32
Manually tested:
1. Existing election has ballot measure ahead of candidate contest
4. Reorder contests -> Save with the new default order in UI
5. Generate ballots, election package. Report has all candidate contests ahead of ballot measures
=> VxDesign: Order candidate contests ahead of ballot measures

apps/pollbook/backend/src/local_store.test.ts, apps/pollbook/backend/src/local_store.ts
Closes https://github.com/votingworks/vxsuite/issues/6992
* Period chars were not being respected in the punctuation-agnostic search
* ie. searching for `St. Clair` if a voter's name was `St Clair` would not work, and vice versa
I refactored the regex construction for exact and prefix searching because it wasn't very DRY.
**Before**
https://github.com/user-attachments/assets/2647d5da-99b4-4903-9867-216b375d6964
**After**
https://github.com/user-attachments/assets/35521d40-21c2-45f4-b004-e19dd162e847
- manually tested
- added store test
=> VxPollBook: ignore period in voter search

apps/pollbook/frontend/src/voter_search_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/6976
Issue: scanning `ID B` when data from `ID A` is in the search state results in navigating to the check-in screen for `ID A` (but it should be for `ID B`).
* The `VoterSearch` component uses two effects to handle updates to the scanned ID as reported by the backend
* Effect 1: when the scanned ID changes, it populates the search query params with data from the scanned ID
* Effect 2: when there's a scanned ID and exactly 1 ID search result, navigate to the next page. For pollworkers the next page is the check-in screen. For election managers the next page is the voter details page.
The above setup works for scanning from an empty search state or manually entered data because the existing search data doesn't specify `exactMatch: true` …
=> VxPollBook: prevent redirecting too early when IDs are scanned in succession

apps/pollbook/backend/src/local_store.test.ts, apps/pollbook/backend/src/local_store.ts, apps/pollbook/frontend/src/statistics_screen.test.tsx, apps/pollbook/frontend/src/statistics_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/6983
* Filters absentee check-ins from the voter throughput stats
* Updates the title to "Precinct Voter Throughput" to suggest this (in line with "Precinct" and "Absentee" voters being distinct in the stats above)
- updated FE test for new copy
- added test to local_store that absentee check in isn't reported in throughput stats
- x] I have prefixed my PR title with "VxDesign: ", "VxPollBook: ", or "HWTA: " if my change is specific to one of those products.
=> VxPollBook: filter absentee checkins from throughput stats

apps/pollbook/barcode-scanner-daemon/src/aamva_jurisdictions.rs, apps/pollbook/frontend/src/mailing_address_input_group.tsx, apps/pollbook/frontend/src/us_states.ts, apps/pollbook/frontend/src/voter_confirm_screen.tsx, apps/pollbook/frontend/src/voter_search_screen.tsx
Closes #7032. 
Tested manually.
No tests changed. Hard to test against a static list.
=> VxPollBook: update list of AAMVA issuers and mailing provinces to avoid crash

apps/admin/frontend/src/hooks/use_contest_adjudication_state.test.ts, apps/admin/frontend/src/hooks/use_contest_adjudication_state.ts, apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx
Some suggested changes for #6343:
- Small style warning fixes.
- Use `Map` instead of `Record` to make the types a bit stricter and make this new code less susceptible to failing with option IDs like `toString`.
=> Suggestions for #6343

apps/central-scan/frontend/src/components/export_results_modal.tsx, libs/ui/src/format_usb_modal.tsx
Closes https://github.com/votingworks/vxsuite/issues/6960
Closes https://github.com/votingworks/vxsuite/issues/6961
After some discussion with SLI, for two cert discrepancies both involving errors that (expectedly) surface when USB drives are removed while being written to, we landed on warnings not to remove the USB drives as acceptable solutions.
This task prompted a general discussion about our progress modals, and if we have time before the cert campaign ends, it could be nice to revisit all progress modals holistically (https://github.com/votingworks/vxsuite/issues/7049). For now though, what we've landed on in this PR is reasonably compatible with the old pattern still in use elsewhere.
_VxAdmin USB format modal_
| - | - |
| <img width="400" alt="format-before" …
=> Add warnings not to remove USB drives to VxAdmin USB format modal and VxCentralScan CVR save modal

apps/pollbook/frontend/src/nav_screen.test.tsx, apps/pollbook/frontend/src/nav_screen.tsx
=> VxPollBook: add a space within "pollbook" :)

apps/pollbook/backend/src/store.ts, apps/pollbook/backend/src/store_multi_node.test.ts
The check_in_status table is only used for performance reasons for the check in counts that populate on the top of the poll worker screen and in the network modal. We are properly handling double checks in when viewing a voter as the getVoter function will get all events for that voter, and resolve them consistently. However I had an error in the way I was updating the machine_id in the materialized view, causing it to be wrong and produce confusing behavior. Here is how it works as an example: 
Machine A checks in Bob at 6:01
Machine B checks in Bob at 6:02 
When Machine A syncs the check in event from Machine B whenever it is fetching Bob it will return the Machine B check in since the last write wins. 
When Machine B syncs the check in event from Machine A it will save it but will …
=> VxPollBook: Fix machine id updates in check in status mat view

apps/pollbook/backend/src/app.ts, apps/pollbook/backend/src/store.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_enums.ts, libs/logging/types-rust/src/log_event_enums.rs
Adds a check when saving a check in event to see if we detect a double (or triple, etc.) check in and log in that event. I was intentionally trying NOT to add another DB query  in the interest of making this the safest possible change which is why I am piggy backing off of the existing getVoter call, the event for the current check in WILL be included already there so we need to check for the number of check in events. When we apply events to the voter we clear out any check in data when we see an undo (even if there was a double check in prior to the undo, for example) so to detect a double check in we want to look at all of the events AFTER the most recent Undo (if there was one) and see if there is more then one event with the type CheckIn. 
I also noticed some more noisy logs now that …
=> VxPollBook: Log double check ins when detected

apps/design/frontend/src/app.tsx, apps/design/frontend/src/elections_screen.test.tsx, apps/design/frontend/src/elections_screen.tsx
Adds some polish to the filter on the elections screen:
- Auto-focus the filter on mount
- Add a button to clear the search
- Persist search when navigating to other pages and coming back to election list
- Only scroll the table so that the filter input doesn't resize while typing
https://github.com/user-attachments/assets/2df5bb5c-1bd0-4bee-a27f-fa608eb421ac
=> VxDesign: Polish for election list filter

apps/central-scan/backend/src/importer.ts, libs/logging/VotingWorksLoggingDocumentation.md, libs/logging/log_event_details.toml, libs/logging/src/log_event_enums.ts, libs/logging/types-rust/src/log_event_enums.rs
Closes https://github.com/votingworks/vxsuite/issues/7060
This is in response to a cert discrepancy reported by SLI:
> SLI does not see any documentation for printing errors in regards to the imprinters on the Ricoh fi-819PRB and fi-760PRB. Since the imprinters provide a printing function, there should be some potential messages. Such as the imprinter being detached.
I've opted for a simple imprinter status log that indicates whether or not the imprinter is registering as attached. This log is emitted on scan start.
I didn't want to add a log on actual disconnect/reconnect since that would require some kind of event listening and/or polling. The way we currently check imprinter status involves sending a scan request to the Fujitsu, and I don't want us constantly making that request to the …
=> VxCentralScan: Log imprinter attachment status on scan start

libs/ui/src/keyboard_navigation.test.ts, libs/ui/src/keyboard_navigation.ts
https://github.com/votingworks/vxsuite/issues/6988
Recent clarifications on an RFI regarding peripherals on precinct scanners (details in [Slack](https://votingworks.slack.com/archives/CE7LM9LQ2/p1754960059785999)) mean that we'll need to support PAT input devices on VxScan.
We'll be using the same X-Keys XK3 USB switch that we've picked for VxMark, which can be [configured](https://docs.google.com/document/d/10Nf5HZ_de-WPGGbndrgrNZ9RdifD83t_q-AyIIalTyI/edit?tab=t.wb9xymjo57u5) to emit any keyboard events we want. We're currently configuring it to emit the same `ArrowDown` and `Enter` events as the tactile controller, but will move over to using the `1` and `2` keys that we've been using for VxMarkScan, both for consistency and to help distinguish between tactile controller events and PAT …
=> [Scan/Mark] Support navigation via PAT-specific keyboard events

apps/design/backend/migrations/1756159958924_organizations-table.js, apps/design/backend/scripts/create_org.ts, apps/design/backend/scripts/create_user.ts, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/auth0_client.test.ts, apps/design/backend/src/auth0_client.ts, apps/design/backend/src/env.d.ts, apps/design/backend/src/store.ts, apps/design/backend/src/types.ts, apps/design/backend/test/helpers.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/app.test.tsx, apps/design/frontend/src/clone_election_button.test.tsx, apps/design/frontend/src/elections_screen.test.tsx, apps/design/frontend/src/org_select.tsx, apps/design/frontend/test/api_helpers.tsx
Closes https://github.com/votingworks/vxsuite/issues/7070
Auth0 is the source of truth for organizations. VxDesign currently loads organizations from the Auth0 API in a few different places:
1. On every API request, load the user's organization name 
2. When listing elections, load each election's organization name
3. When creating/cloning an election, load a list of organizations to select the new election's org (only for users with access to all orgs)
This is problematic if Auth0 has an outage, since it will impede users from using VxDesign (in particular, users that are already logged in and have a stored session cookie). To prevent this, this PR makes a few changes:
1. Stop loading the user's organization name - we weren't actually using it
2. Cache the organizations in the database …
=> VxDesign: Improve resilience to Auth0 outages

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts
I didn't rebase off of `main` before merging, which resulted in my new tests not having the new param for `setupApp()`, causing main to fail.
NA
=> VxDesign: Update tests with new param

libs/hmpb/src/render_ballot.tsx
The API method that calls this function already cleans up the renderer. Plus, this method shouldn't cleanup resources that it receives as an argument - those should be the responsibility of the caller.
N/A
Existing tests
=> libs/hmpb: Remove duplicate renderer.cleanup() call

libs/usb-drive/src/block_devices.test.ts, libs/usb-drive/src/block_devices.ts, libs/usb-drive/src/usb_drive.test.ts, libs/usb-drive/src/usb_drive.ts, libs/usb-drive/vitest.config.ts
Closes #7092. The bug is that, when we mount a USB drive, we acquire a lock (mutex) in the `libs/usb-drive` code. For ejecting and formatting, the lock is released in a `finally` block. Since our mounting takes place during a `status` call, which we don't want to hang, we `void` the promise and let the lock persist between calls. The lock is only released once we detect the mount point via `lsblk` and count the drive as mounted, which can take a second. If you remove the USB drive after we successfully mounted i.e. `mount.sh` has exited but _before_ the mount point is detected during `lsblk`, the lock is never released and USB drives cannot be mounted and used until the machine is restarted.
The fix is, as part of our `mount` logic, polling `lsblk` until we get a mount and calling the …
=> USB Handling: fix mount wedge state

apps/design/backend/src/index.ts
If it ever gets out of sync, we can simply restart the app to fix it.
N/A
Manual test
=> VxDesign: Sync organizations cache on startup

libs/hmpb/src/ballot_components.tsx, libs/hmpb/src/ballot_templates/la_ballot_template.tsx, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/ballot_templates/vx_default_ballot_template.tsx, libs/hmpb/src/render_ballot.tsx
I noticed that our adjudication ballot viewer does not work for elections without write-ins, because we rely on the field `optionBoundsFromTargetMark` when determining the contest layout, and that field gets a zero value if we don't find a write-in on a ballot. This value is then used for every contest on the ballot when determining option/contest bounds. 
To fix this, we now fallback to a contest option box, and last a ballot measure box.
This ensures that an election will still have a pretty accurate value for `optionBoundsFromTargetMark` in elections without write-ins, and even elections without candidate contests.
Before - contest from election with no write-in: 
After - contest from election with no write-in:
After - contest from election with only a BM:
Manual testing
=> Enable adjudication ballot viewing for elections without write-ins

apps/design/backend/src/index.ts
In development, if working with a prod db backup locally (e.g. for debugging a prod issue), syncing the auth cache will fail, since the local app isn't connected to the prod Auth0 tenant. In this case, we don't need to sync the auth cache on startup anyway, since the db should already be up to date. For other dev use cases, the db migrations run by `pnpm db:reset-dev` will sync the cache.
N/A
Manual test
=> VxDesign: Only sync auth cache on startup in production

apps/design/backend/src/app.results.test.ts, apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/index.ts, apps/design/backend/src/types.ts, apps/design/backend/test/helpers.ts, apps/design/frontend/src/api.ts, apps/design/frontend/src/app.tsx, apps/design/frontend/src/public_api.ts, apps/design/frontend/src/reporting_results_confirmation_screen.tsx, apps/design/frontend/src/routes.ts, apps/design/frontend/vite.config.ts
Adds the basic scaffolding in VxDesign for an endpoint that will be encoded in the QR code itself, hit with query paramters of the results data, pass that data to a grout backend endpoint to save it, and return a UI to the user confirming the results. The actual UI and logic in the "save" endpoint here are not meant to be fully featured and will be fleshed out further in future PRs. This is just a barebones setup that receives a url, formatted and encoded in the historical format used for previous demos, and returns the parsed information back to the frontend to be displayed. 
This page is NOT meant to be behind oauth, so tweaks to how we enforce that needed to be made to allow for this carve out. 
See in review app, legal qr code url: …
=> VxDesign: VxQR: Implement scaffolding in VxDesign for VxQR reporting endpoint

apps/scan/backend/src/app.ts, apps/scan/backend/src/app_quick_results.test.ts, apps/scan/frontend/src/api.ts, apps/scan/frontend/src/app.test.tsx, apps/scan/frontend/src/app_unhappy_paths.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.test.tsx, apps/scan/frontend/src/screens/poll_worker_screen.tsx, apps/scan/frontend/test/helpers/mock_api_client.tsx, libs/ui/src/qrcode.tsx, libs/ui/src/reports/precinct_scanner_tally_report.tsx
Closes https://github.com/votingworks/vxsuite/issues/7206
just adding @carolinemodic 's work on this branch..
Additional changes:
1. Header added to Scan's Quick Results screen
2. Removed QR code from precinct tally report
Header added to Scan's Quick Results screen:
Manual testing
=> Cherry-pick VxQR on screen

apps/admin/backend/schema.sql, apps/admin/backend/src/app.adjudication.test.ts, apps/admin/backend/src/cast_vote_records.ts, apps/admin/backend/src/store.ts, apps/admin/backend/src/types.ts, apps/admin/backend/src/util/cast_vote_records.ts, apps/admin/backend/test/mock_cvr_file.ts, apps/admin/frontend/src/screens/contest_adjudication_screen.test.tsx, apps/admin/frontend/src/screens/contest_adjudication_screen.tsx, apps/design/frontend/src/system_settings_screen.test.tsx, apps/design/frontend/src/system_settings_screen.tsx
Closes https://github.com/votingworks/vxsuite/issues/6505
Porting this over from the `la-demo` branch [PR
](https://github.com/votingworks/vxsuite/pull/7142)
https://github.com/user-attachments/assets/e7f3802f-af9d-46de-aa5e-999df7e14834
Automated tests added/updated
Manual testing
=> VxAdmin: Add support for overvote and undervote adjudication

apps/mark-scan/backend/src/app.diagnostics.test.ts, apps/mark-scan/backend/src/app.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.test.ts, apps/mark-scan/backend/src/custom-paper-handler/state_machine.ts, apps/mark-scan/backend/test/ballot_helpers.ts, apps/scan/backend/src/app_scanning.test.ts, apps/scan/backend/src/sheet_requires_adjudication.ts, libs/ballot-interpreter/src/adjudication_reasons.ts, libs/ballot-interpreter/src/bmd/interpret.ts, libs/ballot-interpreter/src/bmd/utils/qrcode.ts, libs/ballot-interpreter/src/hmpb-rust/js/image_data.rs, libs/ballot-interpreter/src/hmpb-rust/js/mod.rs, libs/ballot-interpreter/src/hmpb-ts/addon.ts, libs/ballot-interpreter/src/hmpb-ts/cli.ts, libs/ballot-interpreter/src/hmpb-ts/debug.test.ts, libs/ballot-interpreter/src/hmpb-ts/interpret.test.ts, libs/ballot-interpreter/src/hmpb-ts/interpret.ts, libs/ballot-interpreter/src/hmpb-ts/scoring_report.ts, libs/ballot-interpreter/src/hmpb-ts/types.ts, libs/ballot-interpreter/src/interpret.ts, libs/ballot-interpreter/src/interpret_all_bubble_ballot.test.ts, libs/ballot-interpreter/src/interpret_and_save_files.test.ts, libs/ballot-interpreter/src/interpret_blank_sheet.test.ts, libs/ballot-interpreter/src/interpret_bmd_and_hmp_ballots.test.ts, libs/ballot-interpreter/src/interpret_bmd_ballots.test.ts, libs/ballot-interpreter/src/interpret_vx_hmpb.test.ts, libs/ballot-interpreter/src/types.ts, libs/ballot-interpreter/test/helpers/interpretation.ts
This change provides a small speed boost to HMPB interpretation by changing the contract of the Rust code to never pass image data back, instead writing the normalized ballot image data to disk in the location that the calling JS code wants it to go.
<details>
<summary>
Built both versions (JS writes, Rust writes) and ran them several times. Typical times on my i5 machine were <b>75ms</b> for Rust, <b>280ms</b> for JS.
</summary>
<pre>
❯ node compare.js
setup: 131.41ms
JS Writes: 283.72ms
Rust Writes: 72.745ms
❯ node compare.js
setup: 140.669ms
JS Writes: 296.398ms
Rust Writes: 79.841ms
❯ node compare.js
setup: 132.113ms
JS Writes: 274.477ms
Rust Writes: 75.326ms
❯ node compare.js
setup: 145.867ms
JS Writes: 303.028ms
Rust Writes: 81.836ms
❯ node compare.js
setup: 146.944ms
JS Writes: …
=> perf(scan): improve speed of interpretation pipeline

libs/hmpb/src/render_ballot.tsx
Patch to fix #7216 for contests with no candidates.
N/A
Manual test
=> VxDesign: Fix candidate rotation assertion for contests with no candidates

libs/hmpb/src/ballot_templates/nh_ballot_template.test.ts, libs/hmpb/src/ballot_templates/nh_ballot_template.tsx, libs/hmpb/src/render_ballot.test.tsx
Closes #7160 
Special cases some specific contests in the November 2025 election that use rotation by precinct (they have a legal exception). Since this is a very specific exception, we hardcode it for now. In the future, we can revisit whether we want to support this in a more general way.
(Skipping because this logic only applies to specific contests from production data)
- Manual test with the specific contests this applies to
- Basic unit test
=> VxDesign: Rotate candidates by precinct for some hardcoded NH contests

apps/design/backend/migrations/1758572282198_add-last-exported-ballot-hash.js, apps/design/backend/src/app.test.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/generate_election_package_and_ballots.ts
Saves the ballot hash to the elections DB for easier future reference when a ballot package is exported and the ballot hash is generated. 
This does NOT backfill this field on existing records we don't have a way of knowing what the value is so it seems complex to try to fill this in, although we could approximate with whatever the current ballot hash for the election would be. For the VxQr use case of this new field this is ok as we do not need to have any elections that have already been exported work with VxQr. If other features want to utilize this field this might need to be reconsidered however. 
Ran migration locally, saw db column added. Ran automated test testing basic functionality.
=> VxDesign: Persist last exported ballot hash

apps/design/backend/src/index.ts
Ran into an issue in dev where the API requests fail after doing a DB reset, due to missing dev orgs in the cache.
Adding the startup org sync call for non-auth-enabled dev as well to make sure they get restored after DB resets.
- Manual
=> VxDesign: Sync dev auth orgs to the DB cache

libs/ballot-interpreter/src/hmpb-rust/interpret.rs, libs/ballot-interpreter/src/hmpb-ts/types.ts, libs/types-rs/src/election.rs
Any `Election` with HMPBs will have this field, but a BMD-only election will not. This brings the Rust type better in line with the TypeScript version.
=> fix(types-rs): allow for missing `gridLayouts`

apps/design/backend/src/worker/ballot_pdfs.test.ts, apps/design/backend/src/worker/ballot_pdfs.ts, apps/design/backend/src/worker/generate_election_package_and_ballots.ts
Task: #7233 
- Only convert NH ballots to grayscale, since the conversion is only needed for the NH printer
- When converting to grayscale, process all of the ballots concurrently
N/A
Manual test to confirm speed increase, updated automated test
=> VxDesign: Optimize converting ballots to grayscale

apps/design/backend/src/app.test.ts, apps/design/backend/src/app.ts, apps/design/backend/src/store.ts, apps/design/backend/src/worker/generate_election_package_and_ballots.ts, apps/design/backend/src/worker/generate_test_decks.ts, apps/design/backend/src/worker/tasks.ts, apps/design/backend/test/helpers.ts, apps/design/frontend/src/export_screen.test.tsx, apps/design/frontend/src/export_screen.tsx
Task: #7233 
Removes sample ballots from the default ballot export. Adds a checkbox to add them back in. This reduces the default number of ballots exported by 1/3, which will save time for the most common use cases.
Also changes the control for whether or not to export audio into a checkbox and moves it inline with the other export options for consistency/clarity.
=> VxDesign: Don't export sample ballots by default

apps/design/backend/src/ballots.ts, libs/hmpb/src/render_ballot.tsx
Adds some assertions to help clarify what's wrong when trying to export without ballot styles defined. I opted not to build anything into the UI for now since eventually we probably want to require ballots are finalized before exporting, which would make this a non-issue.
=> VxDesign: Guards to prevent exporting without ballot styles

apps/scan/backend/src/scanners/pdi/pdi_app_scan.test.ts, apps/scan/backend/src/scanners/pdi/pdi_app_scan_double_sheet.test.ts, apps/scan/backend/src/scanners/pdi/state_machine.ts
While debugging another scan issue, I noticed that "teasing" a ballot (triggering a scan, but removing it before the scanner can grab it) was resulting in an error message to restart the scanner.
I've tested this behavior countless times and never seen this error message before, so I'm assuming it was either behavior that was introduced accidentally or that my scanner is behaving slightly differently than before.
The reason this error message is shown is because the state machine is getting jam flag from the scanner, so it tries to reject the ballot. Since there's no ballot, it thinks it has successfully rejected the ballot. However, if the frontend sees the `rejected` state with no error code, it assumes something weird happened and shows the message to restart the scanner (since there's …
=> VxScan: Improve error message when ballot removed before scan

apps/mark/backend/src/util/print_ballot.test.tsx, apps/mark/backend/src/util/print_ballot.tsx, libs/printing/src/printer/types.ts, libs/printing/supported_printers/generic-postscript-driver.ppd
Currently we can create ballots from VxMark that print marks onto pre-printed ballots. It's been limited to letter and legal size ballots because the typical LaserJet Pro 4001dn supports maximum 14" paper. With a custom tray and custom firmware provided by HP, however, plus some configuration changes, we can print on up to 22" paper. This PR allows those sizes. 
I'm not sure if we can detect the firmware version systematically, which would be nice to only allow this option when it's availabile. The key change is actually not the "engine firmware" but the "formatter firmware" which I think would be even more unlikely to detect. I think on those printers, the job just fails (as it now would crash the app). 
Tested manually on 22", 19", and 17".
=> VxMark: support printing longer ballot sizes

apps/design/backend/migrations/1759851149270_add-tts-edits.js, apps/design/backend/src/store.test.ts, apps/design/backend/src/store.ts, libs/types/src/tts_strings.ts
https://github.com/votingworks/vxsuite/issues/7264
Updating the DB schema and types for managing TTS string edits.
Outline of the current plan:
- When there are no edits yet for a given string, the UI will be seeded with the original election string - a DB entry for the TTS edit is only populated when the string is modified and saved in the UI.
- Edits are retrieved form the DB based on a `[election ID, original string]` primary key, meaning that if the original string is modified to a string with no associated TTS edit, the TTS editing UI defaults again to the new base string. If the base string is reverted to a previous value, the old TTS edit will essentially be re-associated with the string.
- When generating audio, we'll look up any existing TTS edits for each relevant string and use …
=> VxDesign: Use original strings as keys for tts_strings (now tts_edits)
